### ISSUE TITLE
_XOPEN_SOURCE and _POSIX_C_SOURCE warnings when building on Linux

### ISSUE THREAD

**Issue by sunyab** [PixarAnimationStudios/USD#1]
Platform: RHEL7
Compiler Version: gcc 4.8.5

When building USD on Linux, we get many warnings due to redefinitions of the _XOPEN_SOURCE and _POSIX_C_SOURCE macros. This is likely due to Python headers not being included at the top of files as required (see https://docs.python.org/2/c-api/intro.html#include-files). We should be able to fix this by moving these headers up in the include order.

**Comment by mistafunk** [comment]
unsurprisingly, i'm seeing the same on gentoo linux

**Comment by amooty** [comment]
Filed as internal issue #135152.

**Comment by sunyab** [comment]
Commit 27fcbafae adds a workaround for this issue. In my local builds, I no longer receive these warning messages. The bigger issue of reordering Python includes to accommodate their requirements still exists, but we hope to address that when we take a closer look at how we structure our Python-related code.

Thanks to @sirpalee for suggesting the workaround on the usd-interest forum!

**Comment by sunyab** [comment]
This is fixed in 27fcbaf in release 0.7.5. Closing.
