### ISSUE TITLE
usdMaya for OSX

### ISSUE THREAD

**Issue by zhoub** [PixarAnimationStudios/USD#10]
Hi !

I'm trying to build usdMaya but I think that's not possible because on the MAC even Maya 2017 it was still built with libstdc++, and USD it's using C++11 everywhere, but useMaya refers to the MPxData which has the interfaces refer to the std::ostream directly, so there is the conflict on the linking.

> Undefined symbols for architecture x86_64:
>   "MPxData::readBinary(std::__1::basic_istream<char, std::__1::char_traits<char> >&, unsigned int)", referenced from:
>       vtable for UsdMayaStageData in stageData.cpp.o
>   "MPxData::writeASCII(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
>       vtable for UsdMayaStageData in stageData.cpp.o
>   "MPxData::writeBinary(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
>       vtable for UsdMayaStageData in stageData.cpp.o

**Comment by ShadowM8** [comment]
Haven't tried to build it myself yet but just wanted to note that starting from 2016.5 Maya on OSX links against libc++

**Comment by drwave** [comment]
That’s good news.

There’s a similar issue w/SketchUp 2016 and the fact that they use libstdc++. My understanding is that they are switching to libc++ for 2017.

**Comment by zhoub** [comment]
Sorry 2017 still uses libstdc++

http://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__files_Setting_up_your_build_environment_Mac_OS_X_environment_htm

**Comment by ShadowM8** [comment]
I don't trust that page :)
We've been building our plugins against libc++ starting with 2016.5, in various venues AD engineers have said that they build against libc++ at this point.

Also, running 'otool -L maya' shows it linking to libc++.

**Comment by amooty** [comment]
Filed as internal issue #135162.

**Comment by drwave** [comment]
Anybody made any progress on getting the Maya plug-ins to compile? I've very close, but am down to something that must be silly - when linking I'm getting a bunch of undefined symbols for MObject:: 

doing nm in /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/*dylib I'm actually not seeing that class defined, but I realize that it's the root class for a lot of plug-in stuff, so I'm missing something obvious...

**Comment by drwave** [comment]
Anybody made any progress on getting the Maya plug-ins to compile with the maya2017 devkit? I'm very close, but am down to something that must be silly - when linking I'm getting a bunch of undefined symbols for MObject:: 

MObject::kNullObj
MObject::MObject(MObject const&)
MObject::MObject()
MObject::~MObject()
MObject::operator=(MObject const&)
MObject::hasFn(MFn::Type) const
MObject::isNull() const
MObject::apiType() const
MObject::operator==(MObject const&) const
MObject::operator!=(MObject const&) const

doing nm in /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/*dylib I'm actually not seeing that class defined, but I realize that it's the root class for a lot of plug-in stuff, so I'm missing something obvious...

**Comment by drwave** [comment]
Anybody made any progress on getting the Maya plug-ins to compile with the maya2017 devkit? I'm very close, but am down to something that must be silly - when linking I'm getting a bunch of undefined symbols for MObject:: 

MObject::kNullObj
MObject::MObject(MObject const&)
MObject::MObject()
MObject::~MObject()
MObject::operator=(MObject const&)
MObject::hasFn(MFn::Type) const
MObject::isNull() const
MObject::apiType() const
MObject::operator==(MObject const&) const
MObject::operator!=(MObject const&) const

doing nm in /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/*dylib I'm actually not seeing that class defined, but I realize that it's the root class for a lot of plug-in stuff, so I'm missing something obvious...

**Comment by drwave** [comment]
Anybody made any progress on getting the Maya plug-ins to compile with the maya2017 devkit? I'm very close, but am down to something that must be silly - when linking I'm getting a bunch of undefined symbols for MObject:: 

MObject::kNullObj
MObject::MObject(MObject const&)
MObject::MObject()
MObject::~MObject()
MObject::operator=(MObject const&)
MObject::hasFn(MFn::Type) const
MObject::isNull() const
MObject::apiType() const
MObject::operator==(MObject const&) const
MObject::operator!=(MObject const&) const

doing nm in /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/*dylib I'm actually not seeing that class defined, but I realize that it's the root class for a lot of plug-in stuff, so I'm missing something obvious...

**Comment by drwave** [comment]
Anybody made any progress on getting the Maya plug-ins to compile with the maya2017 devkit? I'm very close, but am down to something that must be silly - when linking I'm getting a bunch of undefined symbols for MObject:: 

MObject::kNullObj
MObject::MObject(MObject const&)
MObject::MObject()
MObject::~MObject()
MObject::operator=(MObject const&)
MObject::hasFn(MFn::Type) const
MObject::isNull() const
MObject::apiType() const
MObject::operator==(MObject const&) const
MObject::operator!=(MObject const&) const

doing nm in /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/*dylib I'm actually not seeing that class defined, but I realize that it's the root class for a lot of plug-in stuff, so I'm missing something obvious...

**Comment by drwave** [comment]
Anybody made any progress on getting the Maya plug-ins to compile with the maya2017 devkit? I'm very close, but am down to something that must be silly - when linking I'm getting a bunch of undefined symbols for MObject:: 

MObject::kNullObj
MObject::MObject(MObject const&)
MObject::MObject()
MObject::~MObject()
MObject::operator=(MObject const&)
MObject::hasFn(MFn::Type) const
MObject::isNull() const
MObject::apiType() const
MObject::operator==(MObject const&) const
MObject::operator!=(MObject const&) const

doing nm in /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/*dylib I'm actually not seeing that class defined, but I realize that it's the root class for a lot of plug-in stuff, so I'm missing something obvious...

**Comment by zhoub** [comment]
You need the devkit from ADN 
https://apps.autodesk.com/MAYA/en/Detail/Index?id=6303159649350432165&appLang=en&os=Mac
