### ISSUE TITLE
Hydra update regression with 19.11 rc1

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1003]
### Description of Issue
Changing a variant selection on an instanced prim causes what appears to be a second copy of the prim to appear in the viewport (but without the transform applied to the instance, so maybe it is the master prim showing up?)

### Steps to Reproduce
1. Load the star4.usda file from the attached zip file into usdview.
[stars.zip](https://github.com/PixarAnimationStudios/USD/files/3741809/stars.zip)
Zoom out a bit so you can see the origin.
2. In the Interpreter window, run:
l = Sdf.Layer.FindOrOpen("star5.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)
3. Notice there are now two 5-pointed stars (one at the origin).
4. Switch to another render delegate and the star at the origin disappears, so it is an update issue. But this bug happens with every render delegate, so it is not a Storm problem.
5. Try this procedure with an older build of USD, and it behaves properly (I tested with a version of USD created from the August 23rd dev branch - commit 2776697638d2e8f23a0d07e2450cd3b9d8c50b8d, more or less).

### Package Versions
19.11-rc1

**Comment by jilliene** [comment]
Filed as internal issue #USD-5638
