### ISSUE TITLE
Hydra update issue when removing parent primvar

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1004]
### Description of Issue
When a primvar is inherited from a parent to a child prim, and the primvar on the parent prim is blocked (or deleted), the child prim is not updated in hydra to reflect the change.

### Steps to Reproduce
1. Load grid.usda into usdview from the attached archive.
[grid.zip](https://github.com/PixarAnimationStudios/USD/files/3741856/grid.zip)
2. In the Interpreter window, run:
l = Sdf.Layer.FindOrOpen("gridnocolor.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)
3. The color on the grid should disappear, but it does not. This happens with all the render delegates I tested.

### Package Versions
19.11-rc1

**Comment by jilliene** [comment]
Filed as internal issue #USD-5639
