### ISSUE TITLE
Deactivating and reactivating instanced prims makes two copies show up

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1005]
### Description of Issue
When instanced prims are deactivated then reactivated, a second copy of those prims (without the instance transforms applied) shows up in the viewport. This is render-delegate independant.

This might be the same as #1003, as the end result looks the same, but the replication process is more direct and much more common.

### Steps to Reproduce
1. Open the attached files into usdview.
[crag.zip](https://github.com/PixarAnimationStudios/USD/files/3744652/crag.zip)
2. In the Interpreter window, run:
p = usdviewApi.stage.GetPrimAtPath('/testgeometry_crag1')
p.SetActive(False)
p.SetActive(True)
3. Suddenly there are two copies of all the geometry, one that looks right, the other much larger and without materials.

### Package Versions
19.11-rc1

**Comment by jilliene** [comment]
Filed as internal issue #USD-5640
