### ISSUE TITLE
hgiGL does not link in Windows with Python and GL support in debug builds (v19.11-rc2)

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#1006]
### Description of Issue

hgiGL does not link in Windows with Python and GL support in debug builds

### Steps to Reproduce
`python build_scripts\build_usd.py --debug  _install`

errors out with

```
LINK : fatal error LNK1104: cannot open file 'python27_d.lib' [C:\Users\aluk\git\USD\_install\build\USD\pxr\imaging\lib\hgiGL\hgiGL.vcxproj]
```

### System Information (OS, Hardware)

Visual Studio 2017 (v141)
Windows SDK 10.0.17763.0

### Package Versions

v19.11-rc2

### Build Flags

`--debug`

**Comment by jilliene** [comment]
Filed as internal issue #USD-5641

**Comment by asluk** [comment]
boost.python provides a workaround for this on Windows, which is why other libraries such as hd do not hit this issue, because they also have python bindings - https://github.com/boostorg/python/blob/boost-1.65.1/include/boost/python/detail/wrap_python.hpp#L9

If I add

```
#if defined(PXR_PYTHON_SUPPORT_ENABLED) && defined(ARCH_OS_WINDOWS)
// Enable debug builds to link without debug binaries of Python.
#include <boost/python/detail/wrap_python.hpp>
#endif // defined(PXR_PYTHON_SUPPORT_ENABLED) && defined(ARCH_OS_WINDOWS)
```

to pch.h in hgiGL after `#include <boost/preprocessor/tuple/to_seq.hpp>`, i.e., before `Python.h`, the build links properly.

I don't know how these PCHs are generated though, so I'm not sure what the real fix should be,

**Comment by c64kernal** [comment]
Thanks for raising this @asluk  -- we have a fix for this and will land it in dev after the current 20.02 release is finalized. More details on what's coming for this in issue #785.
