### ISSUE TITLE
Linear to sRGB for float buffers is really slow

### ISSUE THREAD

**Issue by marsupial** [PixarAnimationStudios/USD#1008]
8adde93eb7e34f61b15e29ca087920dc1da5aedd introduced a lot of slowness if one is providing a float32[4] buffer to draw with.

@fpsunflower quickly flagged the **powf** in **DspyLinearTosRGB** as a potential culprit.

Assuming that is correct, is there a recommended way one can force **applyColorQuantization** to **false** from within their delegate (particularly in the case the delegate has been instantiated via **UsdImagingEngineGL**)

Or is there a chance this can all be done on the GPU for 19.11-rc3 ?

**Comment by lumonix** [comment]
@marsupial 

Yea it is real slow :(
We have the gpu work planned pretty soon, but not for rc3 that I am aware of.

On UsdImagingGLEngine there is an api called: SetColorCorrectionSettings

If you supply it with the id of: HdxColorCorrectionTokens->disabled
It should disable all color correction / quantization and recover the previous perf.

You'll get raw pixels though (not converted to SRGB).

**Comment by jilliene** [comment]
Filed as internal issue #USD-5646
