### ISSUE TITLE
glf/simpleLight.cpp uses GL fixed function pipeline

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#101]
GlfSimpleLight::Draw uses the OpenGL fixed function pipeline, and therefore won't compile on platforms lacking support for older GL versions, same for GlfSimpleLightingContext, GlfSimpleMaterial::Bind,

**Comment by jtran56** [comment]
Filed as internal issue #139656.

**Comment by meshula** [comment]
closed as no longer relevant.
