### ISSUE TITLE
Cannot open usda file via USDStage::Open function in C++

### ISSUE THREAD

**Issue by sameek4** [PixarAnimationStudios/USD#1011]
I am attempting to add runtime dependency for usda in Unreal engine 4, however the issue I faced with the latest version, is the file format when passed via full file name and path string value, to the UsdStage::Open command, returns null. This works fine in Unreal editor mode, with a previous release already included with Unreal 4.23, however, that does not work with the packaged build, so was trying to include the latest edition. However, this particular function returning null seems like a dead end. Kindly help

**Comment by sameek4** [comment]
I am attempting to add runtime dependency for usda in Unreal engine 4, however the issue I faced with the latest version, is the file format when passed via full file name and path string value, to the UsdStage::Open command, returns null. This works fine in Unreal editor mode, with a previous release already included with Unreal 4.23, however, that does not work with the packaged build, so was trying to include the latest edition. However, this particular function returning null seems like a dead end. Kindly help

**Comment by jilliene** [comment]
Filed as internal issue #USD-5657

**Comment by hshakula** [comment]
I have no idea about your setup. But when I am a very long time ago started playing with USD I had an issue which was absolutely the same. It didn't work because of incorrect usd installation, namely because of missing `${USD_INSTALL_DIR}/lib/usd` folder. Make sure you have this folder somewhere near your USD libraries

**Comment by sameek4** [comment]
You are right. I jusr figured it out. The folder name for the resources have to be "usd" , and it also have to be kept at the Project Binaries , along with the other dlls.
