### ISSUE TITLE
[katana] Nested instancing breaks `geometry.instanceSource` paths

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#1014]
### Description of Issue

When multiple levels of instancing are present in a prim's hierarchy, and the prim is read in by a `PxrUsdIn` node in `as sources and instances` mode, the `geometry.instanceSource` paths generated for the second (lower) level of instancing incorrectly point to a `Masters` group under the parent instance source (which has no child groups).

I'm attaching a tarball containing the files necessary for reproduction.

### Steps to Reproduce
1. Download and extract [the attached tarball (nestedInstanceBug.tar.gz)](https://github.com/PixarAnimationStudios/USD/files/3774037/nestedInstanceBug.tar.gz)
2. Read in `threeMixers.usda` in `as sources and instances` mode, and observe that instancing works correctly.
3. Replace the stage path with `nineMixers.usda`, and observe that the instances no longer compose properly.

More specifically, if you look at the "outer" `instance source` location (at `/root/world/geo/Masters/master/variants/m0`), you will see that its children are themselves instances, which is what one would expect. However, their `geometry.instanceSource` paths incorrectly point to paths mounted under the parent `m0` location, when the `instance source` location for the nested instances is actually built under `/root/world/geo/Masters/Mixer/variants/m0`.

### Package Versions

USD 0.19.11, Katana 3.1v7

**Comment by jilliene** [comment]
Filed as internal issue #USD-5665

**Comment by emeroo** [comment]
Hi Nathan,

When we build out masters, we create a stub hierarchy to put them in and then re-invoke PxrUsdIn with a different "location" and "isolatePath" in order to get it to read just the prim we care about. This is causing usdInArgs->GetRootLocation() to no longer be the "original" root location and breaks computation of the master's path in the Katana scene (e.g., instead of "/root/world/geo/Masters/foo", you get something like "/root/world/geo/Masters/m0/nested/geo/Masters/foo" for a nested instance).

I would argue that the change proposed in https://github.com/PixarAnimationStudios/USD/pull/1015 shouldn't just apply to the case where "masterParentPath" is empty, but rather all cases. I might also suggest using the "location" stored in the UsdIn op args before falling back on interface.getRootLocationPath().

I am using your repro scene to test out a reworked version of PR 1015 that has this chunk of logic instead:

`
                if (!masterPath.empty())
                {
                    interface.setAttr(
                            "type", FnKat::StringAttribute("instance"));

                    // If we are a nested instance, the UsdIn args' root location will
                    // no longer be the "original" root location specified on the
                    // PxrUsdIn node.
                    // This is because BuildIntermediate reinvokes PxrUsdIn with
                    // different UsdIn args when building out masters.
                    // We can get at the original root location by querying the op args
                    // rather than the UsdIn args.
                    //
                    std::string rootLocationPath = FnAttribute::StringAttribute(
                        opArgs.getChildByName("location")).getValue(
                            interface.getRootLocationPath(), false);
                    interface.setAttr("geometry.instanceSource",
                            FnAttribute::StringAttribute(
                                rootLocationPath + 
                                masterParentPath +
                                "/Masters/" + masterPath));
                    
                    // XXX, ConstraintGroups are still made for models 
                    //      that became instances. Need to suppress creation 
                    //      of that stuff
                    interface.deleteChildren();
                    skipAllChildren = true;
                }`

**Comment by emeroo** [comment]
I'm seeing correct geometry.instanceSource values for the nested instances with this change. Let me know what you think.
I was told that ILM also uses "as sources and instances" mode, so we may want to check that this is kosher with them too... I'm waiting to hear back about how that process might work.

**Comment by nrusch** [comment]
Thanks @emeroo. I was originally going to switch over to `interface.getRootLocationPath()` wholesale, but I left the branching in there in case anyone was relying on it somehow.

Falling through the `"location"` attr from the op args before hitting `interface.getRootLocationPath()` makes sense to me; I've updated #1015 appropriately.

**Comment by emeroo** [comment]
Rad! This change _should_ produce the same behavior as before for non-nested instances, even those with a "masterParentPath"... I shudder to think that anyone was relying on the weirdo nested "/root/world/geo/Masters/m0/nested/geo/Masters/foo" result. :scream:

**Comment by emeroo** [comment]
I'm shooting out an email to get ILM's eyes on https://github.com/PixarAnimationStudios/USD/pull/1015. Stay tuned!

**Comment by emeroo** [comment]
ILM is cool with it, so we'll pull 1015 into a change on our end and get it deployed. Thanks again, Nathan!

**Comment by sunyab** [comment]
#1015 has been released with USD v20.02, closing!
