### ISSUE TITLE
Missing Python bindings for usdSchemaExamples

### ISSUE THREAD

**Issue by sunyab** [PixarAnimationStudios/USD#102]
The Python bindings for the usdSchemaExamples library are not being built. In addition, the library is missing the moduleDeps.cpp file needed for script module initialization.

This was reported by Guillaume Laforge on the usd-interest group here:
https://groups.google.com/d/msg/usd-interest/n7Y22jE3asQ/8AZ5mEcxBAAJ

### System Information (OS, Hardware, etc.)
All

### Package Versions
0.7.1

### Build Flags
N/A
    
### Steps to Reproduce
1. Attempt to follow the Python example at the bottom of the "Generating New Schema Classes" tutorial at http://graphics.pixar.com/usd/docs/Generating-New-Schema-Classes.html.

**Comment by jtran56** [comment]
Filed as internal issue #139678.
