### ISSUE TITLE
Inconsistent bounding boxes in USD

### ISSUE THREAD

**Issue by HdC-adsk** [PixarAnimationStudios/USD#1024]
### Description of Issue
There are two versions of bounding boxes in USD and they are inconsistent.

* Selection bounding box: the bounding box is calculated from the local bounding box and the local-to-world transformation. It looks correct and easy to validate since it can be visualized in USDView.

* Frustum-culling bounding box: the bounding box is exactly the same as the selection bounding box for regular meshes, but for built-in primitives like cone, sphere, cylinder etc, the transformation is the the result of local-to-world transformation multiplied with a "mesh transformation". As a result, the world bounding box will be incorrect, and causing view frustum intersection test to return false result, while false positive will lead to unnecessary draw call, and false negative will lead to object disappearance.

The issue was originally reported on usd-interest: https://groups.google.com/forum/#!topic/usd-interest/I16VT5n4XkE

### Steps to Reproduce
Please open [InvalidBBox.zip](https://github.com/PixarAnimationStudios/USD/files/3811021/InvalidBBox.zip) to see the usda scene and the video on how to reproduce the issue.

### System Information (OS, Hardware)
Non platform-specific

### Package Versions
All

### Build Flags
Default

**Comment by jilliene** [comment]
Filed as internal issue #USD-5678
