### ISSUE TITLE
[Storm] Error when rendering textures on Windows with Radeon GPU

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#1026]
### Description of Issue

On windows, with a Radeon GPU, if I try to display a textured cube in usdview:

https://github.com/elrond79/usd_samples_shapes/raw/master/cube_texture.usdz

...I get this error:

```
Warning: in CompileShader at line 263 of USD\src\pxr\imaging\lib\hdSt\glslProgram.cpp -- Failed to compile shader (GL_FRAGMENT_SHADER): Fragment shader failed to compile with the following errors:
ERROR: 0:339: error(#438) Extension GL_ARB_bindless_texture is requried' by use image/sampler as output parameters'.
ERROR: error(#273) 1 compilation errors.  No code generated


ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_19__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 241 in file USD\src\pxr\imaging\lib\hdSt\drawBatch.cpp : 'Failed to compile shader for prim /pCube1.'
```

Per Pol's suggestion, I tried doing

```
set TF_DEBUG=GLF_DEBUG_CONTEXT_CAPS
```

...and USD thinks I don't have GL_ARB_bindless_texture:

```
ARB_bindless_texture               = 0
```

However, consulting OpenGL Extensions Viewer (http://realtech-vr.com/admin/glview) tells me that it should be available on my GPU / driver.

As a workaround, if I manually set this env var:

```
set GLF_ENABLE_BINDLESS_TEXTURE=1
```

...then it works.

### Steps to Reproduce
1. Download https://github.com/elrond79/usd_samples_shapes/raw/master/cube_texture.usdz onto a windows machine with a Radeon GPU
2. usdview cube_texture.usdz

### System Information (OS, Hardware)
Windows 10 Pro (10.0.18362 Build 18362)
AMD Radeon R9 M370X
Radeon Graphics Drivers Crimson 15.11 2-9-2016
OpenGL Version 4.5

### Package Versions
USD-0.19.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-5683
