### ISSUE TITLE
[windows][cmake] PXR_LIB_PREFIX not used when creating .lib files

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#1027]
### Description of Issue

With PXR_LIB_PREFIX left at it's default value of lib (even on windows), I get output files that look like:

```
ar.lib
usd.lib
libar.dll
libusd.dll
```

Similarly, if I set PXR_LIB_PREFIX=myprefix_, I get files like:

```
ar.lib
usd.lib
myprefix_ar.dll
myprefix_usd.dll
```

### Steps to Reproduce
1. Build on windows

### System Information (OS, Hardware)
Windows 10

### Package Versions
usd-0.19.11

### Build Flags
-DPXR_LIB_PREFIX=myprefix_

**Comment by jilliene** [comment]
Filed as internal issue #USD-5687

**Comment by elrond79** [comment]
For cross reference, this was being discussed in this thread on usd-interest:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/usd-interest/vQkPIKXTrHE/vN_ALJ21FAAJ
