### ISSUE TITLE
[usdrecord] Default value of subdivision is set to high

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#1029]
### Description of Issue
The default value for subdivision when using usdrecord is set to high, while the default value for subdivision is set to low in usdview. This can cause excessive memory usage when rendering a scene with polymeshes/HdStorm, and there is no visible indication of what's happening because usdview opens the same file without issues.

Either we should set the default value the same as for usdview, or introduce an environment variable that controls the default subdivision level for usdrecord (maybe for usdview too?).

### Steps to Reproduce
1. Open any scene with a subdiv mesh in usdrecord and compare memory usage to usdview.

### System Information (OS, Hardware)
It doesn't matter.

### Package Versions
Latest dev.

### Build Flags
It doesn't matter.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5690
