### ISSUE TITLE
Switch testHdBasicDrawing unit test to non-Qt?

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#103]
It would be great if the UsdImaging, Hd and Hdx unit tests were built against GLFW, or simply garch. Presently testHdBasicDrawing still requires a Qt C++ linkage:

if (QT4_FOUND)
    pxr_build_test(testHdBasicDrawing
        LIBRARIES
            hd
            glf
            glfq
            Qt4::QtCore
            Qt4::QtOpenGL
        CPPFILES
            unitTestGLDrawing.cpp
            testenv/testHdBasicDrawing.cpp
    )
endif()

**Comment by c64kernal** [comment]
Thanks Nick!  This has already been fixed and will coming soon to a dev branch near you!

**Comment by jtran56** [comment]
Filed as internal issue #139698.

**Comment by meshula** [comment]
Heh, that is super fine :)

**Comment by takahito-tejima** [comment]
it's already in dev.
https://github.com/PixarAnimationStudios/USD/commit/22c321daf30d61129d8e45456e22722cd299ddd3#diff-a3d976811ef2a4b0180955e2aff0c1a4

**Comment by meshula** [comment]
Ah thank! My fork was out of date.
