### ISSUE TITLE
Build problems with clang-cl (clang on Windows)

### ISSUE THREAD

**Issue by e4lam** [PixarAnimationStudios/USD#1030]
I have a clang-cl project that uses a pre-built USD library (with MSVC, but that's fine because they're ABI compatible). I had to make a few source header adjustments that clang complained about:

- `pxr/base/lib/tf/preprocessorUtils.h`: Replace uses of `ARCH_OS_WINDOWS` with `ARCH_COMPILER_MSVC` because clang-cl's preprocessor is better. This fixes many compiler errors with the use of boost cpp.
- `pxr/usd/lib/sdf/fileFormat.h`: Remove `SDF_API` from "= delete" methods because it doesn't make sense to export deleted methods. I'm surprised that the other compilers allow this.
- `pxr/usd/lib/ar/asset.h`: Remove `AR_API` from "= delete" methods for same reason as previous.

I hope someone can make these fixes. Thank you!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5691

**Comment by e4lam** [comment]
I found another problem, this time with the definitions of ARCH_CONSTRUCTOR and ARCH_DESTRUCTOR in `pxr/base/lib/arch/attributes.h` where they need to be defined in the section used by `defined(ARCH_COMPILER_CLANG)`, however, it tests for `defined(ARCH_OS_WINDOWS)` first. I just moved that whole `#elif defined(ARCH_COMPILER_GCC) || defined(ARCH_COMPILER_CLANG)` so that it's tested before the `#elif defined(ARCH_OS_WINDOWS)` and it fixed the problem. I think that perhaps the right change here is to move the GCC/CLANG section up and also change `#elif defined(ARCH_OS_WINDOWS)`  to `#elif defined(ARCH_COMPILER_MSVC)` to be more precise.

**Comment by spitzak** [comment]
People do use gcc and other non-msvc compilers to compile code for Windows, so it is likely ARCH_OS_WINDOWS is the correct test for some of these.

**Comment by e4lam** [comment]
@spitzak I'm certainly *not* advocating that ARCH_OS_WINDOWS be replaced with with ARCH_COMPILER_MSVC everywhere, but only in these particular cases where it seems to me that they were intended for MSVC. The particular issue in `pxr/base/lib/arch/attributes.h` deals with the understanding of particular MSVC specific pragma's and `__declspec(allocate())`. clang-cl is usually pretty good in warning about things that it doesn't understand/implemented but for some reason is just silently not doing the right thing in this case.

**Comment by e4lam** [comment]
To expand on the `pxr/base/lib/arch/attributes.h` issue, it only showed up when trying to use `AR_DEFINE_RESOLVER()` in client code and then noticing that it had failed to register the resolver because the ctor (and presumably the dtor as well) never gets called when the plugin library is loaded.

**Comment by LazyDodo** [comment]
USD export support recently landed in blender, which broke the clang-cl build (same setup as @e4lam  msvc build libs, getting linked with clang-cl), can confirm changing  the test for the `TF_PP_IS_TUPLE` macro at

https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/lib/tf/preprocessorUtils.h#L192

to test for `ARCH_COMPILER_MSVC` rather than `ARCH_OS_WINDOWS` fixes at-least the compile time errors.   

If this change could be made in mainline USD it be one less patch for us to apply manually.

**Comment by c64kernal** [comment]
@e4lam and @LazyDodo -- apologies I can't seem to find a PR, do you mind making one if one doesn't exist. (Check out this page if this is your first PR: http://graphics.pixar.com/usd/docs/Contributing-to-USD.html

Thanks!

**Comment by LazyDodo** [comment]
Sadly your CLA requirements prevent me from sending a PR, you'll have to do with my description of the issue and work out the actual code change your self.
