### ISSUE TITLE
testOslParser - No module named Mentor.Runtime

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#1032]
### Description of Issue
When I run the testOslParser test, I get this failure:

```
Traceback (most recent call last):
  File "/luma/dev/paulm/rez-release/usd/0.19.11.luma01/platform-linux/gcc-6.3/tests/testOslParser", line 26, in <module>
    from Mentor.Runtime import FindDataFile
ImportError: No module named Mentor.Runtime
```

Not sure whether Mentor is some python module that should be available if you have OSL, or if it's some Pixar internal thing that leaked out into the public repo...

### Steps to Reproduce
1. run tests with OSL enabled

### System Information (OS, Hardware)
CentOS 7

### Package Versions
usd-dev (702873ecea7fed0d0a43f25ba4c93a901602ff98)
osl-1.10.5

### Build Flags
PXR_ENABLE_OSL_SUPPORT=ON

**Comment by sunyab** [comment]
Thanks @elrond79, it's the latter case -- we'll have a fix up shortly!

**Comment by elrond79** [comment]
Great, thanks!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5693

**Comment by sunyab** [comment]
Closing this out, this issue was introduced in the dev branch and was fixed with the above commit. Thanks!

**Comment by elrond79** [comment]
Awesome, thanks!
