### ISSUE TITLE
NULL-ptr exception when rendering a non-camera in HdPrman

### ISSUE THREAD

**Issue by guillaume-lafo-mpc** [PixarAnimationStudios/USD#1035]
In our Hydra-based application, we support rendering without an USD camera, taking in only the view and projection matrices. We recently upgraded to USD 19.11 and had to patch HdPrman to support this case properly.

Is it obsolete to render without an USD camera?

To set the rendering frustum, we use the HdRenderPassStateShared::SetCameraFramingState function before calling the HdEngine::Executable function. During the rendering process, HdxPrman_RenderPass::_Executable is called and crashes at line 195 (hdCam->SetRileyCameraParams....) because 'hdCam' is a null pointer. 

I wish I could just send you the diff file with the patch that I wrote. Unfortunately, that's not an option with this company. My fix was to add null-pointer checks when accessing hdCam and re-introduce the code from 19.07 that pushes the camera parameters through Riley.

Thanks for looking into this issue,
Guillaume Laforte

**Comment by poljere** [comment]
Thanks for reporting this issue Guillaume. It is not absolete to use state injection instead of a scenegraph backed camera, our Storm render delegate supports both methods. We should fix this.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5698
