### ISSUE TITLE
[hydra] Add support for aborting renders

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#1039]
Currently, performing a synchronous, complete render using Hydra (similar to what `UsdAppUtilsFrameRecorder` does) requires a pattern that looks more or less like this:

```
auto tasks = taskController->GetRenderingTasks();
do {
    engine.Execute(renderIndex, &tasks);
}
while (!taskController->IsConverged());
```

One thing that is notably absent from the current execution API is a way to abort a render. With the introduction of USD-side schemas for describing renderer settings and artifacts, it seems inevitable that Hydra is going to need to grow additional client-facing functionality around controlling render delegates, including the ability to cleanly abort rendering tasks.

This may involve `HdEngine` growing an `AbortTasks` method or something similar. I imagine the renderer-facing API would also need to grow new functionality for communicating such task state changes to the render delegate.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5703

**Comment by c64kernal** [comment]
Hi @nrusch -- look in usdview under the "View" menu for "Stop Render" and "Pause Render" -- following that code path should give you an idea of what code is required to implement this functionality in your backend or client. Let us know if there's more you need here or if we missed something. Thanks!
