### ISSUE TITLE
Cache line size hardcoded at compile time, causes runtime abort if size does not match

### ISSUE THREAD

**Issue by martin-pw** [PixarAnimationStudios/USD#1049]
### Description of Issue
Runtime abort if running on a machine that does not have a 64 byte cache line size, or if a cache line size query fails to return a valid cache line size:

 ArchError: ARCH_CACHE_LINE_SIZE is not set correctly.
  Function: Arch_ValidateAssumptions
      File: third_party/usd/pxr/base/arch/assumptions.cpp
      Line: 155
Aborted (core dumped)

Cannot simply recompile since this problem exists with third party code that builds in USD.

Would be great to have an environment variable that would skip the check and let us continue running at our own risk.

### Steps to Reproduce
1. Run a third party app that includes USD on machine that does not return '64' for the cache line size.

### System Information (OS, Hardware)
Debian 9 running on hardware that does not return cache line size information.

### Package Versions
USD 19.11

### Build Flags
Standard

**Comment by jilliene** [comment]
Filed as internal issue #USD-5725

**Comment by sunyab** [comment]
This was addressed with commit 62f65d04 in 20.02. Closing this out, thanks!
