### ISSUE TITLE
maya plugins some error 

### ISSUE THREAD

**Issue by thewaylord** [PixarAnimationStudios/USD#1051]
usd build finish ! 
and  usdview  good working
but maya some have error 
i import PointInstancedMedCity.usd
// Error: Failed to open layer @PointInstancedMedCity.usd@ -- Runtime Error in Open at line 827 of C:\test\USD-master\pxr\usd\lib\usd\stage.cpp // 
// Error: Cannot open USD file PointInstancedMedCity.usd -- Runtime Error in Read at line 387 of C:\test\USD-master\third_party\maya\lib\usdMaya\translatorModelAssembly.cpp // 
// Warning: Unable to retrieve displayColor on Material: <NONE> or Gprim: /MediterraneanHills/Buildings/Prototypes/prototype_0/mesh_0 // 
// Warning: Could not read color set values from primvar 'displayColor' on mesh: /MediterraneanHills/Buildings/Prototypes/prototype_0/mesh_0 // 
// Warning: Unable to retrieve and assign data for color set <displayColor> on mesh </MediterraneanHills/Buildings/Prototypes/prototype_0/mesh_0> // 

what am i doing wrong

**Comment by c64kernal** [comment]
Hi @thewaylord -- the only thing that comes to mind is somehow the plugins aren't finding the dlls they need... have you set up the environment variables as described here: http://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html

Also, note that these plugins are no longer maintained in this repo and they've been migrated to:

https://github.com/Autodesk/maya-usd

Hope this helps!
