### ISSUE TITLE
Trying to build USD with renderman

### ISSUE THREAD

**Issue by suekieza** [PixarAnimationStudios/USD#1054]
### Description of Issue
Build fails when i add the prman flags to my complie, see crash log and build log
### Steps to Reproduce
1. Run USD build as I normally would added in the two prman flags:
python /home/suesauer/Documents/USDPXR/USD/build_scripts/build_usd.py /home/suesauer/Documents/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya --alembic --prman --prman-location /opt/pixar/RenderManProServer-23.0/

### System Information (OS, Hardware)
Linux Centos 7

### Package Versions
LAtest build of master
### Build Flags
python /home/suesauer/Documents/USDPXR/USD/build_scripts/build_usd.py /home/suesauer/Documents/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya --alembic --prman --prman-location /opt/pixar/RenderManProServer-23.0/
[CMakeOutput.log](https://github.com/PixarAnimationStudios/USD/files/3927147/CMakeOutput.log)
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/3927148/CMakeError.log)
[log.txt](https://github.com/PixarAnimationStudios/USD/files/3927151/log.txt)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5740

**Comment by pkanyuk** [comment]
Hi there, I ran into this too, I think that's because there's no renderman-23 directory under third_party, just renderman-22.  I can build USD with prman22 just fine, but I get the same error with 23.   Do we dare just copy renderman-22 to renderman-23, fix some paths, and see if it works?  Or is there more to this?

Thanks!
-- Paul

**Comment by drwave** [comment]
My understanding is that the RenderMan API that is used to talk to Hydra changed significantly between 22 and 23, and the new code has not been checked into the tree. I got that from the RenderMan support forums. I can try and dig up the exact post.

I’m using it in Houdini 18, which does work.

**Comment by pkanyuk** [comment]
Hey Wave, sounds right, my naive attempt to just rename the renderman-22 director to renderman-23 didn't work at all.  I'll ask around to see what the situation is.  Thanks!

**Comment by drwave** [comment]
Note: I did the same thing myself a few weeks ago, so I feel ya!

**Comment by suekieza** [comment]
Yeah also using it so that I can use H18. Thanks for the replay at least I know now it is not me being dumb somehow. :D

**Comment by sunyab** [comment]
As a (very late) follow-up: we have a pending change that should provide better diagnostic messages when trying to build USD with an unsupported version of RenderMan. This should be pushed out to the dev branch soon.

**Comment by suesauer** [comment]
Thanks for the follow-up. I'll go ahead and close this issue.

**Comment by suesauer** [comment]
looks like I can't close it :/ weird
