### ISSUE TITLE
Python modules not building

### ISSUE THREAD

**Issue by JesseFK** [PixarAnimationStudios/USD#1056]
### Description of Issue
Even though it seems to find everything it needs it's not building the Python modules/Python programs. I've tried installing reinstalling things but nothing seems to work so maybe someone here can help.

### Steps to Reproduce
1.  Run build_usd.py with flags below

### System Information (OS, Hardware)

Windows 10

### Package Versions

Python 2.7.15
Jinja2 2.0
PySide 1.2.2
PyOpenGL 3.1.0

### Build Flags

"C:\Python27\python.exe" build_usd.py -v -v -v --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem --with-python" --force-all --python --no-maya C:\usd

### Log
[log.txt](https://github.com/PixarAnimationStudios/USD/files/3949961/log.txt)

**Comment by c64kernal** [comment]
Sorry I haven't looked too deeply, but for some reason CMake is thinking that you've turned off building of shared libraries... (just noting this quick while I'm thinking about it in case it helps any other debugging)

**Comment by c64kernal** [comment]
Indeed, your log shows that -DBUILD_SHARED_LIBS=OFF is being passed down to CMake, which is turning off these modules. The build_usd.py line that you give here doesn't seem like it would do that, have you modified your build_usd.py, or is the log.txt from some other invocation? Those are the only thoughts that come to mind at the moment...

**Comment by jilliene** [comment]
Filed as internal issue #USD-5746

**Comment by JesseFK** [comment]
Thanks for the help! I didn't change anything in the build_usd.py, and the log was from basically 2 minutes before I posted. Instead I ended up just deleting the build and source code and redownloaded everything and now it seems to be fine.
