### ISSUE TITLE
Variant disappearing when using FlattenLayerStack()

### ISSUE THREAD

**Issue by blevin** [PixarAnimationStudios/USD#1060]
Francois Lord reports that the USD layer flattening is losing variant selections:

    https://groups.google.com/forum/#!topic/usd-interest/gAfIRGPVeSs

I was able to confirm this in the dev branch of USD.  The _Reduce() code looks like it should already handle this case, so hopefully it is a straightforward fix.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5751

**Comment by sunyab** [comment]
Fixed in USD v20.02, closing!
