### ISSUE TITLE
Errors occurring when using usdview

### ISSUE THREAD

**Issue by Ryanagogo** [PixarAnimationStudios/USD#1063]
### Description of Issue
When loading in the example sphere, only the bounding box shows up in the usd view, and there are a number of errors that show up in the console window

I've attached the errors

[load_sphere_error_16-12-19.txt](https://github.com/PixarAnimationStudios/USD/files/3965780/load_sphere_error_16-12-19.txt)

### Steps to Reproduce
1. build usd 19.11.  Load in the test sphere with usdview

### System Information (OS, Hardware)
Windows 10 Pro
Intel Xeon E-2276M
NVIDIA Quadro RTX 5000
64GB DDR4 ECC DRAM

### Package Versions
usd 19.11

Jinja2     2.10.3
MarkupSafe 1.1.1
pip        19.3.1
PyOpenGL   3.1.4
PySide     1.2.4
PyYAML     5.2
setuptools 41.2.0
Shiboken   1.2.2
wheel      0.33.6

### Build Flags
I have built this USD as part of building the maya-usd

python build_scripts\build_usd.py --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya "C:\USD"

**Comment by jilliene** [comment]
Filed as internal issue #USD-5753
