### ISSUE TITLE
USD should be made to work with Python 3

### ISSUE THREAD

**Issue by d3zd3z** [PixarAnimationStudios/USD#1067]
The python scripts in USD seem to be based off of Python 2. Python 2 will have reached end-of-life on January 1, 2020. There will be no release, no bug fixes. In addition, most distributions will stop including python2 by default, and will likely be removing the package entirely.

This issue can help track updating the python scripts within USD to work with Python 3.

**Comment by c64kernal** [comment]
Thanks for the suggestion -- this is on our radar and we hope to land it soon starting from the work in PR #928

**Comment by jilliene** [comment]
Filed as internal issue #USD-5763

**Comment by sunyab** [comment]
Initial Python 3 support has landed in the dev branch and will be included in 20.05, marking as pending release.

**Comment by sunyab** [comment]
Oops, meant to close this out. Python 3 support is in the 20.05 release.
