### ISSUE TITLE
USD API "UsdSkel_BlendShape" has some choreography error

### ISSUE THREAD

**Issue by aaronmack** [PixarAnimationStudios/USD#1068]
### Description of Issue
Some pictures and expressions are incorrect. Here: https://graphics.pixar.com/usd/docs/api/_usd_skel__schemas.html#UsdSkel_BlendShape
### Steps to Reproduce
1. Want to get more information about Blendshape

### System Information (OS, Hardware)
Centos7

**Comment by spiffmon** [comment]
Sorry about that, @aaronmack !  If you refresh your browser, you should find the formula images there now, and this shouldn't happen again in the future.
