### ISSUE TITLE
Drawmode does not inherit as expected on instanceable prims

### ISSUE THREAD

**Issue by noWookies** [PixarAnimationStudios/USD#1069]
### Description of Issue
It seems that "drawmode" inheritance is not working as expected on instances. 
We noticed this when setting up city environments which had instances shared across "buildings". This is an urgent issue for us as it is affecting artist UX.

### Steps to Reproduce
1. In the attached example, there are two instances in two assemblies (4 instances in total, resulting in one master).
2. When setting drawmode to bounds on one assembly, two bounds are drawn for the assemblies' children, but the other two instances dissappear.
3. When drawmode is reverted to "default", those two instances remain undrawn.
![instancing_drawmode](https://user-images.githubusercontent.com/1433061/71254221-6379ce80-237e-11ea-88e5-e1effbfa02da.gif)

#### USD Files used in Repro
[bbox_instancing_bug.zip](https://github.com/PixarAnimationStudios/USD/files/3988247/bbox_instancing_bug.zip)

### System Information (OS, Hardware)
Linux, Windows

### Package Versions
USD-19.7-19.11

**Comment by spiffmon** [comment]
Hi @noWookies ,
   I have confirmed this is still broken in our latest dev, and in fact I got failed verifies in the shell, as well.  Clearly needs to be fixed, though I don't think we'll even be able to look at it until the New Year, and the first potential release that would have a fix would be 20.05, roughly releasing in April.
   The only workaround I found, which clearly is insufficient, is to change drawmode on an ancestor prim that includes all of the instances whose masters may be affected by the change.

**Comment by noWookies** [comment]
Thanks @spiffmon ,

Is the 20.05 timeline due to resourcing or is there other development which should be be completed before this can be fixed ?

I'm mainly asking because we could attempt to address this as well (OSS FTW! :P) We'd welcome any pointers on a recommended approach!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5764

**Comment by spiffmon** [comment]
Hi @noWookies ,
   It's 20.05 as release simply because 20.02 is already in alpha, and 20.05 is the next release... though hopefully a fix would appear in dev sooner.  Most folks are already OOO for the holidays - let us discuss and get back to you in the New Year!  

Happy Holidays,
--spiff

**Comment by noWookies** [comment]
Happy New Year :)
Just checking in to see if you had a chance to discuss yet ?

**Comment by spiffmon** [comment]
A fix is IP.

--spiff
