### ISSUE TITLE
Tf diagnostics crash on Windows

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#107]
### System Information (OS, Hardware, etc.)
Windows

Repro:

1. Trigger a TF_ERROR (or similar)
2. Crash

It looks like a lot of the guts are commented out.

This includes things like writing the wrong value type to a Usd Attribute, etc, so it would be *super* helpful to get these messages.

**Comment by amooty** [comment]
Filed as internal issue #140408.

**Comment by amooty** [comment]
Hey @jcowles! We were unable to repro this on our end, and the test works as expected, so I am closing it out. Please let us know if you see it again!
