### ISSUE TITLE
Local installs of Boost 1.70+ can take precedence over USD builds of boost

### ISSUE THREAD

**Issue by robpieke** [PixarAnimationStudios/USD#1071]
(all the below is based on OSX - it might or might not also apply to Linux&Windows)

As per https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake#L230 if you have Boost 1.70+ installed locally, CMake can pick it up instead of the version of Boost built by the build script. 

```
-- Found Boost: /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options python 
```

This is a problem if your local installation of boost python is for Python 3, and you can end up with nasty errors like:

```
[ 46%] Linking CXX shared library _garch.so
Undefined symbols for architecture x86_64:
  "boost::python::detail::init_module(char const*, void (*)())", referenced from:
      _init_garch in module.cpp.o
      _initlibgarch in module.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pxr/imaging/lib/garch/_garch.so] Error 1
make[1]: *** [pxr/imaging/lib/garch/CMakeFiles/_garch.dir/all] Error 2
```

Thankfully, a few lines down, the solution is given (https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake#L241)

When I make the following change, I'm back up and running again

```
diff --git a/build_scripts/build_usd.py b/build_scripts/build_usd.py
index c844e9dd5..688773063 100644
--- a/build_scripts/build_usd.py
+++ b/build_scripts/build_usd.py
@@ -299,6 +299,7 @@ def RunCMake(context, force, extraArgs = None):
             '-DCMAKE_INSTALL_PREFIX="{instDir}" '
             '-DCMAKE_PREFIX_PATH="{depsInstDir}" '
             '-DCMAKE_BUILD_TYPE={config} '
+            '-DBoost_NO_BOOST_CMAKE=ON '
             '{osx_rpath} '
             '{generator} '
             '{extraArgs} '
```

**Comment by jilliene** [comment]
Filed as internal issue #USD-5771

**Comment by c64kernal** [comment]
Thanks for reporting this @robpieke -- we ran into the same issue when our CI was updated, and here is how Varun fixed it: [commit](https://github.com/PixarAnimationStudios/USD/commit/87def4e490acc2ba64d3ceb2b14115f5fa4f8634) We're discussing now making that the default behavior of the build script.

**Comment by tototuo** [comment]
Thank you @robpieke , I add this configuration and it works well !

**Comment by robpieke** [comment]
> We're discussing now making that the default behavior of the build script.

Looks like this didn't make it for 20.02 ... hopefully 20.05?

**Comment by spiffmon** [comment]
Yes, Rob - it's tagged for 20.05.

--spiff
