### ISSUE TITLE
[Document/Code inconsistency] Location of Bootstrap info in USDC

### ISSUE THREAD

**Issue by syoyo** [PixarAnimationStudios/USD#1072]
### Description of Issue

In the comment, it says Bootstrap is written at the end of file.

https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usd/crateFile.h#L441

But the implementation(and existing USDC/USDZ) assumes bootstrap is placed at the beginning of file.

https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usd/crateFile.cpp#L2498

So I think comment is wrong. 
Or old version of USDC places Bootstrap data at the end of file?

### Steps to Reproduce
1.

**Comment by gitamohr** [comment]
You're right; that comment is incorrect.  I'll fix it up -- thank you.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5772

**Comment by syoyo** [comment]
🎉
