### ISSUE TITLE
Build on GNU/Linux at Google Cloud Shell

### ISSUE THREAD

**Issue by thang12l** [PixarAnimationStudios/USD#1073]
### Description of Issue
Build get stuck at Installing USD step

Building with settings:
  USD source directory          /home/usrname/USD_SRC
  USD install directory         /usr/local/USD
  3rd-party source directory    /usr/local/USD/src
  3rd-party install directory   /usr/local/USD
  Build directory               /usr/local/USD/build
  CMake generator               Default
  Downloader                    curl
  Building                      Shared libraries
    Config                      Release
    Imaging                     Off
      Ptex support:             Off
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  Off
      usdview:                  Off
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off
  Dependencies                  boost, TBB
STATUS: Installing boost...
STATUS: Installing TBB...
STATUS: Installing USD...

### Steps to Reproduce
1.  python USD_SRC/build_scripts/build_usd.py --no-usdview --no-imaging /usr/local/USD

### System Information (OS, Hardware)
GNU/Linux
Linux 4.19.72+
#1 SMP Sun Dec 15 09:26:40 PST 2019 x86_64
(Google Cloud Shell)

### Package Versions
v19.11

### Build Flags
--no-usdview --no-imaging

**Comment by StephenRadachy** [comment]
Was curious as to which distro is used for cloud-shell - turns out it's Chromium OS:

```shell
cat /proc/version
Linux version 4.19.72+ (chrome-bot@host) (Chr
omium OS 9.0_pre365631_p20190821-r3 clang version 9.0.0 (/var/cache/chromeos-cache/
distfiles/host/egit-src/llvm-project 6b043f051836635a1e88da4d0464e6569bd7b625) (bas
ed on LLVM 9.0.0svn)) #1 SMP Sun Dec 15 09:26:40 PST 2019
```

Based on a quick search - it looks like Chromium OS uses Glibc, so good there. IIRC I wasn't able to compile on Alpine since they use musl.

---

@thang12l I'd try adding the `-v` flag to see if you get better debugging information from there.


If that doesn't help triage the issue - I've been able to successfully build a Docker image with [Debian Buster](https://wiki.debian.org/DebianBuster) (**note:** I didn't use the `--no-imaging` flag)
https://gist.github.com/StephenRadachy/aa347075a5719f2b895511a14cf89aa3

**Comment by thang12l** [comment]
Thank @StephenRadachy ,

I got no so much information for debugging with the -v flag too. Stuck at cmake process.
----
  3rd-party source directory    /home/thang12l/USD/src
  3rd-party install directory   /home/thang12l/USD
  Build directory               /home/thang12l/USD/build
  CMake generator               Default
  Downloader                    curl
  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             Off
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  Off
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off
  Dependencies                  OpenSubdiv
STATUS: Installing OpenSubdiv...
INFO: Downloading https://github.com/PixarAnimationStudios/OpenSubdiv/archive/v3_1_1.zip to /home/thang12l/USD/src/v3_1_1.zip
INFO: Running "curl -# -L -o v3_1_1.zip.tmp https://github.com/PixarAnimationStudios/OpenSubdiv/archive/v3_1_1.zip"
######################################################################## 100.0%
INFO: Extracting archive to /home/thang12l/USD/src/OpenSubdiv-3_1_1
INFO: Running "cmake -DCMAKE_INSTALL_PREFIX="/home/thang12l/USD" -DCMAKE_PREFIX_PATH="/home/thang12l/USD" -DCMAKE_BUILD_TYPE=Re
lease   -DNO_EXAMPLES=ON -DNO_TUTORIALS=ON -DNO_REGRESSION=ON -DNO_DOC=ON -DNO_OMP=ON -DNO_CUDA=ON -DNO_OPENCL=ON -DNO_DX=ON -D
NO_TESTS=ON -DGLEW_LOCATION="/home/thang12l/USD" -DNO_PTEX=ON -DNO_TBB=ON "/home/thang12l/USD/src/OpenSubdiv-3_1_1""
INFO: Running "cmake --build . --config Release --target install -- -j1"
STATUS: Installing USD...
INFO: Running "cmake -DCMAKE_INSTALL_PREFIX="/home/thang12l/USD" -DCMAKE_PREFIX_PATH="/home/thang12l/USD" -DCMAKE_BUILD_TYPE=Re
lease   -DPXR_ENABLE_PYTHON_SUPPORT=ON -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUI
LD_TESTS=OFF -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -D
PXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=OFF -DPXR_BU
ILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_BUILD_MATERIALX_PLUGIN=OFF -DPXR_BUILD_MAYA_PLUGIN=OFF -DPXR_BUILD_KA
TANA_PLUGIN=OFF -DPXR_BUILD_HOUDINI_PLUGIN=OFF "/home/thang12l/USD_SRC""
INFO: Running "cmake --build . --config Release --target install -- -j1"
 ----

**Comment by StephenRadachy** [comment]
> INFO: Running "cmake --build . --config Release --target install -- -j1"

It isn't stuck. USD takes a significant amount of time to compile. IIRC it took me ~30 minutes (with 4 cores + 4GB of RAM within Docker on my 2016 MBP) to compile it.

@thang12l What are you trying to accomplish?

**Comment by thang12l** [comment]
You are right @StephenRadachy , I changed the flag of cmake and could see its making progress. Now is 67% after 4 hours. Still waiting.

I am using the usdzconvert tool for converting from GLTF/GLB files to USDZ. The tool is downloaded from https://developer.apple.com/download/more/?=USDPython
It needs the USD python library built first.

**Comment by thang12l** [comment]
I got a successful built, after 6 hours!
Need Jinja2 before building too.
