### ISSUE TITLE
Messed up UVs when subdividing left-handed winding order geometry

### ISSUE THREAD

**Issue by ababak** [PixarAnimationStudios/USD#1075]
### Description of Issue
There is a problem with OpenSubdiv UV handling for left-handed winding order geometry (the default ).
See the [discussion from "usd-interest" group](https://groups.google.com/forum/#!topic/usd-interest/a9IC7ibOdLU)

### Steps to Reproduce
Download and extract the attached files: [cube.zip](https://github.com/PixarAnimationStudios/USD/files/4018925/cube.zip)
1. Open `cube_abc.usda` in "usdview"
1. Select "View > Complexity > **Medium**"
1. Switch to "View > Hydra Renderer > **GL**"
1. Note the messed up UVs ❌
1. Switch to "View > Hydra Renderer > **Prman**"
1. Note the UVs are ok 🍀
---
1. Open `cube_abc_fixed.usda` in "usdview"
1. Select "View > Complexity > **Medium**"
1. Switch to "View > Hydra Renderer > **GL**"
1. Note the UVs are ok 🍀 (there's a "fix" that forces orientation = "rightHanded" which fixes the GL but breaks the Prman)

### Notes
The alembic file was exported from Maya using the default settings.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5773
