### ISSUE TITLE
Incorrect stride used when reading OpenImageIO images with non-default bytes per pixel

### ISSUE THREAD

**Issue by danlea** [PixarAnimationStudios/USD#1080]
OpenImageIO images may be read with an incorrect stride (and therefore be corrupt). This occurs with, for example, 16-bit EXR/TIFF files.

https://github.com/PixarAnimationStudios/USD/blob/ad19ac016c7984273305252caeee0431c8548419/pxr/imaging/glf/oiioImage.cpp#L579

The fix is simply to calculate the `strideLength` of the input using `imageInput->spec().pixel_bytes()` rather than `GetBytesPerPixel()`.

Originally reproduced in USD 19.05.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5787

**Comment by c64kernal** [comment]
Ack! You're absolutely right, thanks so much for spotting this @danlea -- we'll get it fixed up asap.
