### ISSUE TITLE
Checking with PVS-Studio static analyser

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [PixarAnimationStudios/USD#109]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the Universal Scene Description project.

Here is the link to the article about it: http://www.viva64.com/en/b/0455/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by amooty** [comment]
Filed as internal issue #140410.

**Comment by sunyab** [comment]
Commit 3b67b43 is also related to this issue.

**Comment by sunyab** [comment]
This has been merged into release 0.7.3.
