### ISSUE TITLE
[usdview] Difficult to differentiate imaging cachePath vs render index path

### ISSUE THREAD

**Issue by moddyz** [PixarAnimationStudios/USD#1093]
### Description of Issue

When debugging imaging problems via `usdview`, it is useful to print or inspect various scene or imaging *paths* at different locations in the codebase.  

However, it is often difficult to distinguish between the types of paths (UsdPrim paths, cache paths, render index paths) by simply observing the value.  

Notably, cache paths and render index paths have the exact same value in `usdview`, because its `UsdImagingGLEngine` member is [constructed](https://github.com/PixarAnimationStudios/USD/blob/v20.02-rc1/pxr/usdImaging/usdImagingGL/engine.cpp#L128) with an absolute root path ("/") as its `delegateID`.  

It would be useful for a debug environment variable to have `usdview` construct `UsdImagingGLEngine` passing in a **non** absolute root path as its delegate ID (could be just something as simple as `UsdImagingDelegate`).  That way, it becomes easier to distinguish different types of paths by observing their value.  

### System Information (OS, Hardware)
ubuntu-18.04

### Package Versions
usd-19.11

### Build Flags
Dynamic build.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5807

**Comment by c64kernal** [comment]
Thanks for the report @moddyz -- we'll have a fix for this pushed up soon.

**Comment by moddyz** [comment]
Hey @c64kernal - did this fall off the radar? :stuck_out_tongue:

**Comment by c64kernal** [comment]
Hi @moddyz -- sorry about the lack of updates here. It's definitely not off the radar, what ended up landing in 20.05 and pushed up to dev, was a whole bunch of clean up to the way paths were handled (especially in the picking code) so that such a debug facility wouldn't need a bunch of special-casing everywhere. That all made it in already and will be in 20.05.  So now what remains is a relatively small part that actually exposes and uses an env var. That's on deck for us right now. Props to @rajabala  and @tcauchois for sorting through this stuff. As soon as that gets pushed to dev, this issue should get closed.

**Comment by moddyz** [comment]
That sounds awesome @c64kernal, thanks for the update.  Really appreciate the clean-up around that area!

**Comment by c64kernal** [comment]
Hi @moddyz this should now be in place in the dev branch.

**Comment by moddyz** [comment]
@c64kernal sweeeet.  This is going to be very useful for debugging purposes - will get it a test run, soon!

**Comment by moddyz** [comment]
Hey @c64kernal 

Gave it a try.  Working beautifully!  

Hydra doesn't seem to like non-absolute path(s) supplied to `USDIMAGINGGL_ENGINE_DEBUG_SCENE_DELEGATE_ID` - but as it is a debug feature, and the errors are pretty obvious (for developers), I think it should be fine!

Thanks again!

**Comment by tcauchois** [comment]
@moddyz Please do file issues if you find the feature tripping up hydra or usdview!

**Comment by c64kernal** [comment]
+1 to what Tom said -- and glad the feature is working out for you, thanks again to @rajabala and @tcauchois for their work on it.
