### ISSUE TITLE
TOC in BUILDING.md busted

### ISSUE THREAD

**Issue by spiffmon** [PixarAnimationStudios/USD#11]
I'm not sure if this is just misunderstanding the markdown rules or if there's a conversion error somewhere (because the pattern we're following seems rational), but all of the TOC links are broken.  The identifiers generated for the sections use exclusively lowercase, but our references in the TOC use the same capitalization as the section headers themselves.

--spiff

**Comment by amooty** [comment]
Filed as internal issue #135163.

**Comment by asluk** [comment]
This affects the section links in README.md as well, and it looks like the casing-divergence between identifiers and header text is expected-- http://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown

**Comment by pixar-oss** [comment]
The BUILDING.md issue was fixed by d15a2e894e1f6891a146212eb93b3b162fea2d7c. Closing this out.
