### ISSUE TITLE
Glf deadlock on Windows 7, 10, and macOS

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#110]
Hi there, I wanted to report an issue spotted over in the usd-build-club repo.

https://github.com/vfxpro99/usd-build-club/issues/7

I've done a build locally myself and confirmed that 

```
from pxr import Glf
```
[edited]

indeed deadlocks.

Issue 8 over there is probably the same thing. 

https://github.com/vfxpro99/usd-build-club/issues/8

Since it's reported on mac and Windows, it's happening on both the dev, and dev_win_ip branches.

**Comment by superfunc** [comment]
Do you mean ```from pxr import Glf```?

**Comment by meshula** [comment]
yes, that's what I meant (corrected)

**Comment by meshula** [comment]
On macOS, the issue was that tbbmalloc wasn't part of the prerequisites build. Making sure tbbmalloc is correctly in the path resolves it. Windows not resolved.

**Comment by amooty** [comment]
Filed as internal issue #140477.

**Comment by meshula** [comment]
It's OpenImageIO deadlocking.

 	[External Code]	
 	OpenImageIO.dll!00007ffbfee33660()	Unknown
 	OpenImageIO.dll!00007ffbfee34e99()	Unknown
 	OpenImageIO.dll!00007ffbfee34c88()	Unknown
 	OpenImageIO.dll!00007ffbfee33e57()	Unknown
 	OpenImageIO.dll!00007ffbfee33eb6()	Unknown
 	OpenImageIO.dll!00007ffbfee34869()	Unknown
 	OpenImageIO.dll!00007ffbfe7c2339()	Unknown
 	[External Code]	
 	OpenImageIO.dll!00007ffbfee74ba7()	Unknown
 	OpenImageIO.dll!00007ffbfee74cf9()	Unknown
 	[External Code]	
 	python27.dll!000000001e125268()	Unknown

**Comment by vfxpro99** [comment]
sha 0b5df2944e0b772af88efa7180ff6e7c88804908 in OpenImageIO is prior to Larry's rewrite of the OIIO thread pool logic, and does not deadlock.

**Comment by c64kernal** [comment]
Thanks for the update!
