### ISSUE TITLE
Need UsdGeomPrimvarsAPI::Remove

### ISSUE THREAD

**Issue by JasonWorks** [PixarAnimationStudios/USD#1100]
As noted in https://groups.google.com/d/topic/usd-interest/LzrWCafr1P8/discussion

It would be great if UsdGeomPrimvarsAPI::Remove and UsdGeomPrimvarsAPI::Block could be added.

The reason is that creating primvars (through UsdGeomPrimvarAPI) only requires the basic token (such as "st").  But removing via UsdPrim::RemoveProperty requires the full token ("primvar:st").  Additionally, the indexed primvar associated with could automatically be removed/blocked with the UsdGeomPrimvarAPI methods.  Finally, it can be difficult to connect that removing primvars should be done with the RemoveProperty - especially given the token name differences.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5819
