### ISSUE TITLE
__MFB_FULL_PACKAGE_NAME error

### ISSUE THREAD

**Issue by suesauer** [PixarAnimationStudios/USD#1101]
### Description of Issue
Please see https://github.com/LumaPictures/usd-qt/issues/34
### Steps to Reproduce
1. Trying to build USD-qt but I believe I'm running into a bigger issue here

### System Information (OS, Hardware)
Linux Centos 7 version:
LSB Version: :core-4.1-amd64:core-4.1-noarch Distributor ID: CentOS Description: CentOS Linux release 7.7.1908 (Core) Release: 7.7.1908 Codename: Core
Python
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
### Package Versions
USD 0.19.11
PXR_USDMAYA 0.19.11 (refactoring_sandbox branch)
MayaUSD_LIB 0.1.0
MayaUSD 0.1.0
AL_USDMaya 0.34.6
USD_Qt dev Branch
##### USD PIXAR
scl enable devtoolset-6 bash
python ~/Documents/USDPXR/USD/build_scripts/build_usd.py ~/Documents/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --alembic
##### USD MAYA
scl enable devtoolset-6 bash
python build.py --maya-location /usr/autodesk/maya2019 --pxrusd-location ~/Documents/USD --devkit-location ~/Documents/devkitBase  ~/Documents/WorkspaceRefractor
##### USD QT
scl enable devtoolset-6 bash
cmake /Documents/USD_QT/usd-qt -DCMAKE_INSTALL_PREFIX=/Documents/USD_QT/usdQt -DTBB_ROOT_DIR=~/Documents/USD -DUSD_ROOT=/Documents/USD -DBOOST_ROOT=/Documents/USD/lib -DTBB_tbb_LIBRARY_RELEASE=/Documents/USD/lib/libtbb.so

Not sure How to solve this one.

Thanks for help

**Comment by jilliene** [comment]
Filed as internal issue #USD-5828

**Comment by suesauer** [comment]
Hey there, I solved this Issue myself. The Env paths where conflicting with houdini's. Once I isolated houdini and Maya all works as expected

**Comment by c64kernal** [comment]
Thanks for the update, @suesauer
