### ISSUE TITLE
Invalid shader code in basisCurves.glslfx

### ISSUE THREAD

**Issue by HdC-adsk** [PixarAnimationStudios/USD#1103]
### Description of Issue
The shader code at https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdSt/shaders/basisCurves.glslfx#L617 looks invalid. _n1_ should be _inData[1].Neye_ instead.

### Steps to Reproduce
No user-visible issue observed.

### System Information (OS, Hardware)
All

### Package Versions
Latest

**Comment by HdC-adsk** [comment]
Conversion about this issue in usd interest group:
https://groups.google.com/forum/#!topic/usd-interest/aljnecja5U4

**Comment by jilliene** [comment]
Filed as internal issue #USD-5829
