### ISSUE TITLE
OpenVDB supported version is undocumented

### ISSUE THREAD

**Issue by fdan** [PixarAnimationStudios/USD#1110]
Hi folks,

I was looking for the openvdb version we need to use to take advantage of PXR_ENABLE_OPENVDB_SUPPORT, it doesn't seem to be documented:

https://github.com/PixarAnimationStudios/USD/blob/v20.02/VERSIONS.md

cheers,
Dan

**Comment by c64kernal** [comment]
Thanks for pointing that out @fdan! We'll get that fixed up!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5846

**Comment by fdan** [comment]
If the required VDB version is known, would you be able to share here too?

**Comment by c64kernal** [comment]
Hi @fdan  -- yeah, version 6.1.0 is the one that we're supporting on all platforms. Hope that helps!
