### ISSUE TITLE
USD SDK 20.02 produces empty renders in camera-less HdPrman 

### ISSUE THREAD

**Issue by guillaume-lafo-mpc** [PixarAnimationStudios/USD#1113]
This issue is a follow-up to https://github.com/PixarAnimationStudios/USD/issues/1035.
The fix added for the USD SDK 20.02 for https://github.com/PixarAnimationStudios/USD/issues/1035 is only partially correct.

I've fixed the issue again locally. My workstation is unfortunately still hiding through multiple levels of security.. but I think that the diff is simple enough that I can copy it here...

From the USD SKD 20.02 official release source code..
```
--- a/third_party/renderman-22/plugin/hdxPrman/renderPass.cpp
+++ b/third_party/renderman-22/plugin/hdxPrman/renderPass.cpp
@@ -227,6 +227,7 @@ HdxPrman_RenderPass::_Execute(HdRenderPassStateSharedPtr const& renderPassState,
const float fov_deg = fov_rad / M_PI * 180.0;
 
projParams->SetFloat(RixStr.k_fov, fov_deg);
+ cameraNode.params = projParams;
 
// Aspect ratio correction: modify the camera so the image aspect
// ratio matches the viewport (the image dimensions here being the
@@ -249,6 +250,7 @@ HdxPrman_RenderPass::_Execute(HdRenderPassStateSharedPtr const& renderPassState,
viewToWorldCorrectionMatrix = flipZ * viewToWorldCorrectionMatrix;
 
riley::Transform xform;
+ RtMatrix4x4 matrix;
if (hdCam) {
// Use time sampled transforms authored on the scene camera.
HdTimeSampleArray<GfMatrix4d, HDPRMAN_MAX_TIME_SAMPLES> const& 
@@ -267,7 +269,7 @@ HdxPrman_RenderPass::_Execute(HdRenderPassStateSharedPtr const& renderPassState,
} else {
// Use the framing state as a single time sample.
float const zerotime = 0.0f;
- RtMatrix4x4 matrix = HdPrman_GfMatrixToRtMatrix(
+ matrix = HdPrman_GfMatrixToRtMatrix(
viewToWorldCorrectionMatrix * viewToWorldMatrix);
 
xform = {1, &matrix, &zerotime};
```

There are two parts to this fix:
1. Make sure that the Riley camera receives the correct projection matrix.
2. The riley::Transform structure doesn't save a local copy of the 'matrix', so we need to keep it the 'matrix' variable on the stack long enough for the Riley camera's ModifyCamera function to be called.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5863

**Comment by rajabala** [comment]
Thanks for filing, and for the fix!
Is (1) necessary? We set the params member of cameraNode during construction:

`riley::ShadingNode cameraNode = riley::ShadingNode {
            riley::ShadingNode::k_Projection,
            isPerspective ? us_PxrPerspective : us_PxrOrthographic,
            us_main_cam_projection,
            projParams
        };
`

**Comment by guillaume-lafo-mpc** [comment]
Upon review, I agree that (1) looks unnecessary.

**Comment by rajabala** [comment]
Thanks for checking! We'll fix this soon.
