### ISSUE TITLE
[usdview] Support for pasting & executing multi-line text in python interpreter.

### ISSUE THREAD

**Issue by moddyz** [PixarAnimationStudios/USD#1117]
### Description of Issue

`usdview` is an *excellent* tool for presentations and developer iteration.  

One feature which would be really nice to have is the ability to paste & execute multi-line python code into the interpreter.

Currently, the multi-line pastes are not executed.

### Steps to Reproduce
1. `cd` to the root of the USD repository.
2. `usdview ./pxr/usd/usdGeom/testenv/testUsdGeomSubset/Sphere.usda`
3. Select the `green`, `blue`, and `red` GeomSubsets in the outliner.
4. Open python interpreter.
5. Copy the following multi-line text, paste into the interpreter, and hit return:
```
for prim in usdviewApi.selectedPrims:
    prim.GetAttribute('indices').Set([1,2,3])
```
6. The code will not be executed.

### Workarounds
1. You can combine the code into 1 line.
2. For multiple lines: you can copy, paste, and execute one line at a time.

### System Information (OS, Hardware)

Ubuntu-18.04

### Package Versions

19.11

### Build Flags

Dynamic build.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5865
