### ISSUE TITLE
Any plan to support hermite basis curve in houdini implementation?

### ISSUE THREAD

**Issue by zwcloud** [PixarAnimationStudios/USD#1123]
### Description of Issue
I'm trying to save a hermite curve to usd basis curve and use in Houdini but the saved curve seems incorrect in [usdview](https://graphics.pixar.com/usd/docs/Houdini-USD-Example-Workflow.html) and [unpackusd](http://www.sidefx.com/docs/houdini//nodes/sop/unpackusd.html) provided by houdini.

It seems to be not supported judging from the source code. The step size for hermite curve should be 2, I think.

     Point Tangent Point Tangent Point Tangent Point ...
       0------1------2------3------4------5------0 (vertex index)
       [========seg0========]
                     [========seg1========]

### Steps to Reproduce
https://github.com/PixarAnimationStudios/USD/blob/be1a80f8cb91133ac75e1fc2a2e1832cd10d91c8/pxr/usd/usdGeom/basisCurves.cpp#L201-L221
> BasisCurves do not yet support hermite or power bases.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5887

**Comment by c64kernal** [comment]
Hi @zwcloud  Please note the conversation here about the desire to deprecate support for hermite curves: https://groups.google.com/forum/#!topic/usd-interest/Qsp9nrzJQas -- if you require them, it would be great to post to that thread and have a discussion about their need. I think folks are currently assuming they are unused.

**Comment by zwcloud** [comment]
> 
> 
> Hi @zwcloud Please note the conversation here about the desire to deprecate support for hermite curves: https://groups.google.com/forum/#!topic/usd-interest/Qsp9nrzJQas -- if you require them, it would be great to post to that thread and have a discussion about their need. I think folks are currently assuming they are unused.

Thanks! I have post my requirement about hermite.

**Comment by c64kernal** [comment]
Thanks again @zwcloud  -- we now have support for hermite curves as a separate schema for the 20.05 release, so we're going to close this one. We suspect that the DCCs will have to add support for this at their own schedules based on their priorities.
