### ISSUE TITLE
Does anyone have successed in compiling USD with cmake in mac?

### ISSUE THREAD

**Issue by wzy88111** [PixarAnimationStudios/USD#1124]
the following is my problems: Does someone meet?

Configuring done
CMake Error in pxr/base/tf/CMakeLists.txt:
  Target "tf" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Users/wuzhaoyang1/work/3rdParty/USD/USD-master/build/include"

  which is prefixed in the source directory.

CMake Error in pxr/base/tf/CMakeLists.txt:
  Target "tf" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Users/wuzhaoyang1/work/3rdParty/USD/USD-master/build/include"

  which is prefixed in the source directory.

CMake Error in pxr/base/js/CMakeLists.txt:
  Target "js" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Users/wuzhaoyang1/work/3rdParty/USD/USD-master/build/include"

  which is prefixed in the source directory.

CMake Error in pxr/base/trace/CMakeLists.txt:
  Target "trace" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Users/wuzhaoyang1/work/3rdParty/USD/USD-master/build/include"

  which is prefixed in the source directory.

**Comment by moddyz** [comment]
@wzy88111 Have you tried building via the script provided in the repo: `build_scripts/build_usd.py`.

**Comment by meshula** [comment]
It's a good idea to start with the build script as @moddyz says in order to get an idea of how the configuration is typically structured. The error you've reported typically means cmake is confused about the way your build and install directories have been configured.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5888

**Comment by wzy88111** [comment]
> @wzy88111 Have you tried building via the script provided in the repo: `build_scripts/build_usd.py`.

I successed with the tool of build_usd.py by python, but i want to compile  xcode project with cmake,then i want to read the source code, when i do ,it failed.

**Comment by wzy88111** [comment]
> It's a good idea to start with the build script as @moddyz says in order to get an idea of how the configuration is typically structured. The error you've reported typically means cmake is confused about the way your build and install directories have been configured.

I have succeed in compiling the usd code with CMake by fix several cmakelist.txt , but  when compiling , there is still some errors

**Comment by alelordelo** [comment]
> > @wzy88111 Have you tried building via the script provided in the repo: `build_scripts/build_usd.py`.
> 
> I successed with the tool of build_usd.py by python, but i want to compile xcode project with cmake,then i want to read the source code, when i do ,it failed.

Would you mind sharing your workflow? I cannot get it to build on macOS Catalina...
https://github.com/PixarAnimationStudios/USD/issues/1206

**Comment by meshula** [comment]
How about this?

https://github.com/vfxpro99/usd-build-club/wiki/MacOS,-using-Pixar's-script

**Comment by alelordelo** [comment]
> How about this?
> 
> https://github.com/vfxpro99/usd-build-club/wiki/MacOS,-using-Pixar's-script

thanks @meshula , followed step by step. Posted on the other issue https://github.com/PixarAnimationStudios/USD/issues/1206

**Comment by johndpope** [comment]
so there's more build options here 
https://github.com/vfxpro99/usd-build-club/wiki/USD-on-macOS

UPDATE -
mac /windows / linux prebuilt binaries here  
https://github.com/Autodesk/maya-usd/releases/   

# NVIDIA   
https://developer.nvidia.com/usd

**Comment by disini** [comment]
> > It's a good idea to start with the build script as @moddyz says in order to get an idea of how the configuration is typically structured. The error you've reported typically means cmake is confused about the way your build and install directories have been configured.
> 
> I have succeed in compiling the usd code with CMake by fix several cmakelist.txt , but when compiling , there is still some errors


```

CMake Error in pxr/base/tf/CMakeLists.txt:
  Target "tf" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/third_party/oneTBB/tbb-2020.3-linux/tbb/include"

  which is prefixed in the source directory.


CMake Error in pxr/base/trace/CMakeLists.txt:
  Target "trace" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/third_party/oneTBB/tbb-2020.3-linux/tbb/include"

  which is prefixed in the source directory.


CMake Error in pxr/base/work/CMakeLists.txt:
  Target "work" INTERFACE_INCLUDE_DIRECTORIES property contains path:
```


hello, I have the same problem on the cmake stage, how did you fix that ? Much appreciated!

**Comment by wzy88111** [comment]
您发给我的信件已经收到。谢谢！祝您生活愉快！                              吴朝阳

**Comment by meshula** [comment]
@disini, are you doing an in source build? If so, can you try building OpenUSD to a location that is not in the source tree?

**Comment by disini** [comment]
> @disini, are you doing an in source build? If so, can you try building OpenUSD to a location that is not in the source tree?

hello @meshula , the OpenUSD repository was not built in any other project as a third party, I did building the OpenUSD's own source code and project independently, the only change of this project is I put the oneTBB 2020.3 source code into the "third_party" sub-directory under the OpenUSD's source tree,

as suggested by @sunyab  
https://github.com/PixarAnimationStudios/OpenUSD/issues/2964#issuecomment-1959803763

 is there something wrong for doing this?

**Comment by meshula** [comment]
Nothing wrong, I was specifically looking for clues about the error message  `... prefixed in the source directory.`

**Comment by disini** [comment]
> Nothing wrong, I was specifically looking for clues about the error message `... prefixed in the source directory.`

Thanks so much!
