### ISSUE TITLE
HdStorm does not draw Mesh that has PxrSurface Material

### ISSUE THREAD

**Issue by guillaume-lafo-mpc** [PixarAnimationStudios/USD#1128]
We have upgraded our project to USD SDK 20.02, a few weeks ago and we have found a small issue. When trying to render meshes, in Storm, that are assigned complex materials, they do not render. We are proposing a simple patch, so I will attach it to this "issue report".

Our main export process generates RenderMan shader graphs in USD, built around the PxrSurface shader node as their root. With the introduction of the support for shader graphs in Storm, in the USD SDK 20.02: Storm now attempts to use and understand the shader graphs for RenderMan and fails. When Storm fails to understand the shader graph: it stops matching the mesh with render passes, so the mesh completely disappears from the scene.

In previous versions of the USD SDK, we would have the mesh appear using the Fallback shader which mainly used the "displayColor" attribute. The proposed patch brings back this behavior. I apologize for the files being text-copies: unfortunately, I am reporting this issue through our network security layer...

Regards,
Guillaume Laforte

-----

Attachment 1: A simple test_data file: 

```
#usda` 1.0
def "root"
{
	def Material "PxrSurface"
	{
        color3f displayColor = (1, 0.1, 0.1)
		token outputs:surface.connect = </root/PxrSurface/surface.outputs:out>
		token outputs:ri:surface.connect = </root/PxrSurface/surface.outputs:out>
		def Shader "surface"
		{
			uniform token info:id = "PxrSurface"
			token outputs:out
		}
	}
    def Sphere "sphereWithMaterial"
    {
        rel material:binding = </root/PxrSurface>
    }
}
```

-----

Attachment 2: The proposed patch to fix the issue

```
From feb4c8684ca70c781aadca57aa0cf8f8c679fc1d Mon Sep 17 00:00:00 2001
From: Guillaume Laforte <guillaume-lafo@mpcfilm.com>
Date: Fri, 28 Feb 2020 13:44:37 -0500
Subject: [PATCH] Fixes the drawing of HdSt meshes with the fallback material.

---
 pxr/imaging/hdSt/material.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/pxr/imaging/hdSt/material.cpp b/pxr/imaging/hdSt/material.cpp
index dd9ecbe..35826d4 100644
--- a/pxr/imaging/hdSt/material.cpp
+++ b/pxr/imaging/hdSt/material.cpp
@@ -128,6 +128,7 @@ HdStMaterial::Sync(HdSceneDelegate *sceneDelegate,
         // fallback material.
         geometrySource = std::string();
         materialMetadata = _fallbackGlslfx->GetMetadata();
+        materialTag = _materialTag;
     }
 
     _surfaceShader->SetFragmentSource(fragmentSource);
-- 
2.19.0
```

-----

**Comment by poljere** [comment]
That is definitely a regression. Even if we don't support PxrSurface on Storm, we should still use the fallback material. Thanks for reporting this issue.

**Comment by spiffmon** [comment]
@guillaume-lafo-mpc , why would you connect _outputs:surface_ to the PxrSurface network, especially when you've already done the correct thing of connecting _outputs:ri:surface_ to it?  I believe we guide, if not require, that only networks you believe should be consumable by any renderer (like, ideally, non-custom MaterialX networks) be connected to the "universal" outputs:surface terminals.

Even after fixing the regression, it will certainly get you faster TTFI with storm if you don't ask it to analyze material networks it has no hope of understanding.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5896
