### ISSUE TITLE
usdview does not respect the USD spec in regards to texture scale and bias

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#1129]
### Description of Issue

In relation to #990, it seems that also texture scale (e.g. for multiplying a texture by a color) and bias are not supported in usdview GL renderer. They work in Embree renderer, which in turn does not support textures it seems.

### Steps to Reproduce
1. open attached file in usdview
[CubeTextured.zip](https://github.com/PixarAnimationStudios/USD/files/4281372/CubeTextured.zip)

GL:
![image](https://user-images.githubusercontent.com/2693840/75778239-b77a3980-5d57-11ea-91ab-c8790f7e7b3b.png)

Embree:
![image](https://user-images.githubusercontent.com/2693840/75778212-afba9500-5d57-11ea-9717-e3db6d278923.png)

Expected:
![image](https://user-images.githubusercontent.com/2693840/75778267-c5c85580-5d57-11ea-80dc-9fde7c9be826.png)

### System Information (OS, Hardware)
Windows 10

**Comment by c64kernal** [comment]
Thanks for reporting this, @soraryu -- we expect this to work in Storm (GL renderer) so this is a bug that we will try to fix... thanks again!

**Comment by soraryu** [comment]
Great! Is there any way to test Storm already / preview it? We're currently churning out a ton of USDZ and GLTF models and I'd be happy to report issues early. Some of them are pretty complex and thus produce a lot of interesting issues that don't happen with trivial configurations.

**Comment by c64kernal** [comment]
Yes! If you grab the dev branch, the default usdview renderer (GL) is the Storm renderer... so you've been testing it already!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5900

**Comment by hybridherbst** [comment]
Another example file:
https://github.com/PixarAnimationStudios/USD/files/4529345/TextureScaleBug.zip
