### ISSUE TITLE
In Python UsdGeomPrimvar.SetIndices does not take a list 

### ISSUE THREAD

**Issue by koen-v** [PixarAnimationStudios/USD#1138]
### Description of Issue
using a list of int's in UsdGeomPrimvar.SetIndices() causes an exception, it works by wrapping them in a Vt.IntArray() contstructor

### Steps to Reproduce

This code will cause an exception:
materials_var = UsdGeom.PrimvarsAPI(model_mesh_prim).CreatePrimvar('material', Sdf.ValueTypeNames.StringArray, UsdGeom.Tokens.uniform )
materials_var.Set(material_names)
materials_var.SetIndices(material_indices)

Boost.Python.ArgumentError: Python argument types in
    Primvar.SetIndices(Primvar, list)
did not match C++ signature:
    SetIndices(class pxrInternal_v0_19__pxrReserved__::UsdGeomPrimvar {lvalue}, class pxrInternal_v0_19__pxrReserved__::VtArray<int> indices, class pxrInternal_v0_19__pxrReserved__::UsdTimeCode time=Usd.TimeCode.Default())

### System Information (OS, Hardware)
windows 10

**Comment by jilliene** [comment]
Filed as internal issue #USD-5926
