### ISSUE TITLE
SetPopulationMask() doesn't trigger an ObjectsChanged notice

### ISSUE THREAD

**Issue by nxkb** [PixarAnimationStudios/USD#1139]
### Description of Issue
When the population mask of a stage changes where it will cause re-population of prims, there should be an ObjectsChanged notice, but currently no notices are produced.

Our main concern is with how this prevents a usdview plugin from triggering a ui update when manipulating the population mask, so I'll describe that for the repro case...

### Steps to Reproduce
1.  open usdview and the interpreter
2. run `usdviewApi.stage.SetPopulationMask(Usd.StagePopulationMask([Sdf.Path('/nonexistent_prim')]))`
3. usdview is now displaying invalid prims!

### Package Versions
tested on usd-0.20.02

**Comment by jilliene** [comment]
Filed as internal issue #USD-5927
