### ISSUE TITLE
"Vector iterators incompatible" in Sdf copyUtils

### ISSUE THREAD

**Issue by seando-adsk** [PixarAnimationStudios/USD#1146]
### Description of Issue
This [line of code](https://github.com/PixarAnimationStudios/USD/blame/master/pxr/usd/sdf/copyUtils.cpp#L488) contains an **operator==** comparing two iterators that can come from different containers.

According to the standard comparing iterators from different contains is undefined. Once such example is [here](https://stackoverflow.com/questions/4657513/comparing-iterators-from-different-containers).

In the code **finalIt** could be from either the src or dst. When it's from the dst, this will trigger the following exception on Windows if you compile with STL iterator debugging:
    _STL_VERIFY(this->_Getcont() == _Right._Getcont(), "vector iterators incompatible");

It should be a simple enough fix, but I wanted to log an issue to get your opinion on it and to see if there are other places that would need to be fixed.

### Steps to Reproduce
1. Compile on Windows with iterator debugging enabled. 
2. Invoke the SdfCopySpec function.

### System Information (OS, Hardware)
Windows 10

### Build Flags
_ITERATOR_DEBUG_LEVEL > 0

**Comment by jilliene** [comment]
Filed as internal issue #USD-5940

**Comment by sunyab** [comment]
@seando-adsk Thanks for filing this! We have a fix that should be pushed out to the dev branch soon.
