### ISSUE TITLE
Need a way to disable TfMakeDirs in SdfLayer::_WriteToFile

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#1148]
For usd layers in Omniverse, saving fails due to the TfMakeDirs call in SdfLayer::_WriteToFile. We'd like a way to disable this behavior that is compliant with the current thinking on Ar 2.0

Details at
https://groups.google.com/d/msg/usd-interest/9nyQ1xqJLFU/R8UnMeojEQAJ

**Comment by jilliene** [comment]
Filed as internal issue #USD-5942

**Comment by asluk** [comment]
Hi team,

It's fairly critical for our own roadmap that a solution lands for this in v20.08. I imagine that Ar 2.0 won't be part of that release, but do you envision some near-term fix/runtime switch for this `SdfLayer::_WriteToFile` behavior? Let me know any way I can help.

Thanks!

**Comment by spiffmon** [comment]
Hey @asluk - we're going to see if there's something forward-looking we can do in the 20.08 timeframe - stay tuned!

**Comment by asluk** [comment]
Thank you, @spiffmon !
