### ISSUE TITLE
same anchored UDIM texture path used in multiple layers overwrite each other

### ISSUE THREAD

**Issue by kenmcgaugh** [PixarAnimationStudios/USD#1151]
### Description of Issue
When the same anchored UDIM texture path is used in multiple layers and should therefore resolve to different texture files on disk, they all resolve to exactly one file. Which file is used is dependent on the order in which the prims are defined.

### Steps to Reproduce
1. Download and unzip the repro:
[usd_udim_bug.zip](https://github.com/PixarAnimationStudios/USD/files/4406494/usd_udim_bug.zip)

2. cd into the usd_udim_bug directory

3. Follow instructions in the README.txt file

### System Information (OS, Hardware)
Ubuntu 18.04

### Package Versions
usd-20.02

**Comment by jilliene** [comment]
Filed as internal issue #USD-5966

**Comment by c64kernal** [comment]
Hi @kenmcgaugh -- we rolled out a new texture system in Storm to dev recently that should address this problem. It'll be included in the currently scheduled 20.08 release, but you can test it out in dev right now if you'd like.

**Comment by kenmcgaugh** [comment]
I can confirm this fixes the issue on my end. Thanks!

**Comment by c64kernal** [comment]
Excellent, thank you for confirming @kenmcgaugh!
