### ISSUE TITLE
Stuck at "STATUS: Installing USD . . ."

### ISSUE THREAD

**Issue by AirWreckaStuff** [PixarAnimationStudios/USD#1153]
### Description of Issue
Running the script in Windows 10 using the x86 Native Tools Command Prompt for VS 2017, I keep getting stuck in "STATUS: Installing USD . . ."
After exiting the script I see the last steps:
Building with settings:
  USD source directory          C:\Users\...\USD
  USD install directory         C:\Users\...\USD
  3rd-party source directory    C:\Users\...\USD\src
  3rd-party install directory   C:\Users\...\USD
  Build directory               C:\Users\...\USD\build
  CMake generator               Default
  Downloader                    curl

  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          Off
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  On
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off
    Katana Plugin               Off
    Houdini Plugin              Off

  Dependencies                  None
STATUS: Installing USD...
Traceback (most recent call last):
  File "build_usd.py", line 2035, in <module>
    force=context.ForceBuildDependency(dep))
  File "build_usd.py", line 1338, in InstallUSD
    RunCMake(context, force, extraArgs)
  File "build_usd.py", line 334, in RunCMake
    multiproc=FormatMultiProcs(context.numJobs, generator)))
  File "build_usd.py", line 211, in Run
    l = p.stdout.readline()
KeyboardInterrupt

I've also tried on a virtual machine installing to C:\Program Files\USD, which I thought could be an issue but am getting the same issue there.
### Steps to Reproduce
1. Installed VS 2017, Cmake, Python 2.7.17, NASM, pip, PySide, PyOpenGL on Windows 10 x64
2. Opened x86 Native Tools Command Prompt for VS 2017, ran script as shown in instructions
3. Get stuck.

### System Information 
Windows 10 Pro, x64 based processor Dell Precision 5540

### Package Versions
release v20.02

### Build Flags

I'm a developing developer so I'm hoping for some guidance how to address this.   Thank you for your time!!

**Comment by moddyz** [comment]
@AirWreckaStuff - how long did you let that run for?  USD takes a good length of time to compile, depending on your machine specs!

The python stacktrace just looks like it's waiting on the CMake subprocess (which is building USD) to complete.

**Comment by sunyab** [comment]
Hi @AirWreckaStuff:

- You will need to be in the **x64 Native Tools Command Prompt**, not the x86 one. There was a typo in the instructions in README.md for Visual Studio 2017 that has since been fixed.
 
- You can add the "-vv" parameter when you run build_usd.py to get more verbose output. That will allow you to see if the build is proceeding as @moddyz suggests or if something is broken. 

Hope that helps!

**Comment by AirWreckaStuff** [comment]
@moddyz I had let it run overnight just to make sure, but it was just hung so I took @sunyab tips.
These tips were helpful, and I'm now able to build successfully, with errors(unknown compiler versions).  I then had an issue with usdview not actually doing anything and was able to find solutions for that here https://github.com/PixarAnimationStudios/USD/issues/1095 and here https://github.com/PixarAnimationStudios/USD/issues/1133.
Next steps for me is the Maya Plug in now, wish me luck!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5967
