### ISSUE TITLE
Generated Doxygen tag file is invalid XML

### ISSUE THREAD

**Issue by ColinKennedy** [PixarAnimationStudios/USD#1159]
### Description of Issue
I attempted to build USD's documentation as a tag file for personal use but found that the generated file has missing closing tags. In other words, the tag file is invalid.

Here's a relevant snippet (check reproduction steps to try it, too). Note the missing `</compound>` tag, for example:

```xml
    <class kind="struct">UsdRenderSpec</class>
    <class kind="struct">UsdRenderSpec::Product</class>
    <class kind="struct">UsdRenderSpec::RenderVar</class>
    <member kind="function">
      <type>USDRENDER_API UsdRenderSpec</type>
      <name>UsdRenderComputeSpec</name>
      <anchorfile>usd_render_2spec_8h.html</anchorfile>
      <anchor>a10af2b89fb104abe136685da074e10c5</anchor>
      <arglist>(UsdRenderSettings const &amp;settings, UsdTimeCode time, std::vector&lt; std::string &gt; const &amp;namespaces)</arglist>                                                                                         
    </member>
  <compound kind="struct">
    <name>UsdRenderSpec</name>
    <filename>usd_render_2spec_8h.html</filename>
    <anchor>struct_usd_render_spec</anchor>
  <compound kind="struct">
    <name>UsdRenderSpec::Product</name>
    <filename>usd_render_2spec_8h.html</filename>
```

Also, I tried posting this on usd-interest first but for some reason I can't see my post. Sorry if this is a double-post

### Steps to Reproduce
```sh
git clone https://github.com/PixarAnimationStudios/USD
(cd USD && git checkout v20.02 && echo "GENERATE_TAGFILE = documentation.tag" >> pxr/usd/usd/Doxyfile.in)
python USD/build_scripts/build_usd.py /usr/local/USD-20.02 --docs
grep -m 1 -C 8 UsdRenderSettings /usr/local/USD-20.02/build/USD/docs/documentation.tag
```

In the output of the first match (`-m 1`) it should be easy to see that there's a missing </compound> tag. It's not the only case where tags are missing but it's the simplest one to find for this reproduction.

### System Information (OS, Hardware)
CentOS Linux release 7.7.1908 (Core)
Hardware (`lscpu` output)
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
Stepping:              2
CPU MHz:               1249.536
CPU max MHz:           3600.0000
CPU min MHz:           1200.0000
BogoMIPS:              5187.76
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
```

### Package Versions
gcc / g++: 4.8.5
python: 2.7.5
PySide: 1.2.4
OpenGL: 3.1.5
cmake: 2.8.12.2
Doxygen: 1.8.5

### Build Flags
python USD/build_scripts/build_usd.py /usr/local/USD-20.02 --docs

**Comment by jilliene** [comment]
Filed as internal issue #USD-5970

**Comment by ColinKennedy** [comment]
Hi - quick update - I re-ran USD's build script with doxygen 1.8.19 and that fixed the issue. I'm all set now!

**Comment by spiffmon** [comment]
Glad you're all set, @ColinKennedy - we do document 1.8.14 as minimum doxygen version, so I'll close this out.
