### ISSUE TITLE
Need include of nap.h in tf/testEnv/SIGSEGV.cpp

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#116]
Doing a top of tree, dev_win_ip Windows build, tf/testEnv fails to compile because SIGSEGV.cpp references ArchSleep, defined in arch/nap.h.

Adding the necessary #include allows a windows build to succeed.

**Comment by superfunc** [comment]
Do you know how its picking up the definition in other builds?

**Comment by amooty** [comment]
Filed as internal issue #141007.

**Comment by meshula** [comment]
It's specific to the dev_win_ip branch ~ dev uses POSIX sleep.

**Comment by c64kernal** [comment]
Thanks for the report!  Should be fixed now.

**Comment by meshula** [comment]
Thanks :)
