### ISSUE TITLE
Error updating native instances

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1163]
### Description of Issue
There is a bug in the hydra native instancing update procedure such that the update fails given the right morphing of the stage.

### Steps to Reproduce
1. Load first.usda from the attached zip file into usdview:
[instanced_cubes.zip](https://github.com/PixarAnimationStudios/USD/files/4489064/instanced_cubes.zip)

2. In the interpreter window, run:
l = Sdf.Layer.FindOrOpen("second.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)

3. An error is printed to the console:
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_20__pxrReserved__::UsdImagingDelegate::_GetUsdP
rim' at line 531 in file F:/dev_tools/src/usd/usd-20.05/USD-py2.7/pxr/usdImaging
/usdImaging/delegate.h : 'Failed verification: ' p ' -- No prim found for id: /F
lattened_Master_1/instancer1'
And the viewport doesn't show the new geometry. You can see that second.usda should look just like first.usda by loading it directly into usdview.

### System Information (OS, Hardware)
Tested on Windows 10.

### Package Versions
Tested with 19.11 and 20.05 with the same results.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5997
