### ISSUE TITLE
UsdFlattenLayerStack doesn't resolve time sampled asset paths

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1168]
### Description of Issue
The UsdFlattenLayerStack method updates asset paths in the flattened layer (since the locations of the original layers may be different from the location of the new layer). By default relative asset paths are converted to full paths. But this asset path updating doesn't happen for time sampled asset paths (or arrays of asset paths).

I have a fix for this which I will submit as a PR shortly.

### Steps to Reproduce
1. From the attached archive, run the flattentest.py script.
[flatten_test.zip](https://github.com/PixarAnimationStudios/USD/files/4498149/flatten_test.zip)
2. Notice in flattened_default.usda, the asset paths for the texture map on the cube and the field path on the volume have been update to use full paths. In flattened.usda, where the texture map and field paths are time sampled, the asset paths have not been updated to full paths, and are no longer valid.

### Package Versions
Tested in 20.05

**Comment by jilliene** [comment]
Filed as internal issue #USD-6001

**Comment by sunyab** [comment]
Closing, this should be fixed in the 20.08 release. Thanks!
