### ISSUE TITLE
Fatal error due to TfDebugSymbolsChangedNotice on OSX

### ISSUE THREAD

**Issue by sunyab** [PixarAnimationStudios/USD#117]
### Description of Issue
It seems like there's a registry function ordering issue that causes issues on OSX related to 
the registration of the TfDebugSymbolsChangedNotice. This shows up as fatal errors when importing modules in Python. This was noted by @zhoub and others in issue #19 -- see comment on Oct 1 for a workaround.

Note that this does not happen for all OSX builds. I've seen this issue on one of our internal test machines but not others.

### Steps to Reproduce
1. In Python, simply try to import any USD module, e.g. "from pxr import Usd"

### System Information (OS, Hardware)
OSX

**Comment by amooty** [comment]
Filed as internal issue #141019.
