### ISSUE TITLE
GlfBaseTexture, automatic mipmapping and core OpenGL profile

### ISSUE THREAD

**Issue by ShaderManager** [PixarAnimationStudios/USD#1171]
### Description of Issue
`GlfBaseTexture` uses old OpenGL1.4 functionality to generate mipmap chain, which is deprecated and removed in core OpenGL 4.5 profile. For example, this leads to broken texture object for default domelight and following inability to calculate IBL tables properly.
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/imaging/glf/baseTexture.cpp#L368
Possible fix is to use glGenerateMipmap instead.

### Steps to Reproduce
1. Create OpenGL 4.5 context with core profile bit
2. Try to use GlfBaseTexture with automatic mipmap generation.

### Package Versions
Tested with 20.05.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6009
