### ISSUE TITLE
USDView: USDPreviewSurface: wrong shading if metallic is present

### ISSUE THREAD

**Issue by mistafunk** [PixarAnimationStudios/USD#1174]
### Description of Issue
We are exporting a glTF PBR (metallic roughness) example to USD and view it with USDView Storm. Example is from here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WaterBottle

Reference:
![image](https://user-images.githubusercontent.com/1630632/79877502-9693a380-83ec-11ea-87b9-a18ae8a38a29.png)

USDView:
![image](https://user-images.githubusercontent.com/1630632/79877411-7cf25c00-83ec-11ea-8ae3-6771b6f80e23.png)

Relevant USD snippet:
```       def Shader "PBRShader"
        {
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor.connect = </Materials/BottleMat_1/texSampler_WaterBottle_png.outputs:rgb>
            color3f inputs:emissiveColor.connect = </Materials/BottleMat_1/texSampler_WaterBottle_2_png.outputs:rgb>
            float inputs:metallic.connect = </Materials/BottleMat_1/texSampler_WaterBottle_3_png.outputs:b>
            color3f inputs:normal.connect = </Materials/BottleMat_1/texSampler_WaterBottle_1_png.outputs:rgb>
            float inputs:occlusion.connect = </Materials/BottleMat_1/texSampler_WaterBottle_3_png_2.outputs:r>
            float inputs:roughness.connect = </Materials/BottleMat_1/texSampler_WaterBottle_3_png_1.outputs:g>
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }
```

USD files: [CE7863_pbr_bottle.zip](https://github.com/PixarAnimationStudios/USD/files/4510578/CE7863_pbr_bottle.zip)

If the metallic shader input is disconnected, the look is more or less as expected:
![image](https://user-images.githubusercontent.com/1630632/79878188-72849200-83ed-11ea-846d-68c7dd08f411.png)

### Package Versions
USD 20.05 on Linux

### Build Flags
default build via python script

**Comment by jilliene** [comment]
Filed as internal issue #USD-6010

**Comment by JoshuaSenouf** [comment]
I feel like you get the right result in our reference because you have something to reflect in the first place, like a constant sky color or a HDRi.

In the case of usdview, there is nothing to reflect in the first place, so it is like it is receiving a pure black as the color to reflect, hence the result you see, which makes the result technically "correct" and not buggy I think, even if that's not what we desire.

In order to avoid that, you would need a textured DomeLight in order for the metalness of your material to work.

**Comment by spiffmon** [comment]
Exactly right, @JoshuaSenouf .  20.05 (and several earlier releases) should have a textured dome light available in usdview's View settings menu.  The only catch is that it will only work with Storm, currently... hdPrman is hardwired to use a constant dome light if the scene itself does not contain any lights.

**Comment by lightwolf** [comment]
I seem to have the same issue. USDPReviewSurface ignores the dome light if useSpecularWorkflow is 0 
![image](https://user-images.githubusercontent.com/348976/89198910-25988600-d5ae-11ea-9d3c-9f3a1cc8bf9a.png)

In this sample (USD 20.08), the middle sphere uses a metallic workflow (set to 0.8 for demonstration purposes) but the dome light texture is not to be seen.
On the specular spheres (left and right) it is.

I've attached the sample .usda

[Spec_Metal_Test.zip](https://github.com/PixarAnimationStudios/USD/files/5016869/Spec_Metal_Test.zip)

**Comment by poljere** [comment]
I am not sure this is the same issue. 

If you look closely, I think one of the two specular highlights (in the second sphere) is actually the sun of the environment texture. You can try to disable the camera light to confirm it : View > Lights > Camera Light,

**Comment by lightwolf** [comment]
It is. However, like the original reporter I've been converting gltf2 as well, which is why I noticed it in the first place.
![image](https://user-images.githubusercontent.com/348976/89226755-c867f900-d5dc-11ea-90c6-ae1956c2d5f6.png)
It may be just the confusion that metallic shading in gltf2 works very differently. But then shouldn't a high level of metalness reflect the environment?

**Comment by lightwolf** [comment]
I hope you don't mind me extending this thread.

Just for testing, I've replaced the computation of F0 in previewSurface.glslfx with

`F0 = mix(vec3(0.04), diffuseColor, metallic);`
in both
`if (!useSpecularWorkflow) {`
clauses. That's what gltf does: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#appendix-b-brdf-implementation.
_(This is just me hacking)_

The result is a lot closer to the gltf "ground truth":
![image](https://user-images.githubusercontent.com/348976/89292212-491a0a00-d65c-11ea-8076-f2f8f3e6cbe1.png)
than the shipped shader:
![image](https://user-images.githubusercontent.com/348976/89292656-f856e100-d65c-11ea-8da9-aead934d3ed3.png)
_(Those two screenshots are from my own viewer, but the viewing component is identical to USDView)_
For reference, the same model in the gltf2 viewer (using a different HDR)
![image](https://user-images.githubusercontent.com/348976/89292955-70250b80-d65d-11ea-9001-0fc0811f7bde.png)

I've attached the original as well as a usda version of the mesh - it's a part of the gltf samples.
[Damaged_Helmet_usda.zip](https://github.com/PixarAnimationStudios/USD/files/5022035/Damaged_Helmet_usda.zip)

**Comment by clach** [comment]
We currently have two changes in dev that should improve the appearance of metals in UsdPreviewSurface (see the [new 2.3 spec](http://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html#UsdPreviewSurfaceProposal-Version2.3-CurrentHead) for more details). One changes the calculation of F0, very similar to what @lightwolf suggests (though more generalized for any IOR). The second is perhaps more subtle, and adds a new token input “sourceColorSpace” to UsdUVTexture, allowing for better control of in what color space a texture is interpreted. For the water bottle asset, our texture loader was using the occlusion/roughness/metallic texture as sRGB, which is likely incorrect. Setting these UsdUvTexture nodes to use “raw” as their sourceColorSpace should mitigate that issue and (in tandem with our changes to the F0 calculation) result in a visual output more similar to the reference provided.

**Comment by lightwolf** [comment]
@clach Now we're talking. Pretty. :)
![image](https://user-images.githubusercontent.com/348976/91558440-a4c37480-e936-11ea-97d9-92521c2f5013.png)

**Comment by JGamache-autodesk** [comment]
And a gramophone, for comparison:
![image](https://user-images.githubusercontent.com/56274617/118327004-94a6f180-b4d3-11eb-878e-ebad6b9d092d.png)
