### ISSUE TITLE
VtMatrix4fArray compile error but not for VtMatrix4dArray

### ISSUE THREAD

**Issue by josiahmanson** [PixarAnimationStudios/USD#1178]
### Description of Issue

Using VtMatrix4fArray instead of VtMatrix4dArray (float vs double) gives compiler error.

This code compiles and works correctly.

UsdPrim skelPrim;
VtMatrix4dArray matrices;
skelPrim.GetAttribute( TfToken( "restTransforms" ) ).Get( &matrices );

But this code fails to compile.

UsdPrim skelPrim;
VtMatrix4fArray matrices;
skelPrim.GetAttribute( TfToken( "restTransforms" ) ).Get( &matrices );

The error produced is as follows.

1>D:\USD\20.05\include\pxr\usd\usd\attribute.h(433,46): error C2338:
1>D:\Project\file.cpp(260): message : see reference to function template instantiation 'bool pxrInternal_v0_20__pxrReserved__::UsdAttribute::Get<pxrInternal_v0_20__pxrReserved__::VtMatrix4fArray>(T *,pxrInternal_v0_20__pxrReserved__::UsdTimeCode) const' being compiled
1>        with
1>        [
1>            T=pxrInternal_v0_20__pxrReserved__::VtMatrix4fArray
1>        ]

The stopping point in a debug build seems to stop on the line static_assert(SdfValueTypeTraits<T>::IsValueType, "") in the code below.

    template <typename T>
    bool Get(T* value, UsdTimeCode time = UsdTimeCode::Default()) const {
        static_assert(!std::is_const<T>::value, "");
        static_assert(SdfValueTypeTraits<T>::IsValueType, "");
        return _Get(value, time);
    }

This suggests to me that the float version of the matrix class is not having the attributes set correctly.

### Steps to Reproduce
1. Try to compile the code I mentioned.

### System Information (OS, Hardware)

Windows 10 version 1803. Using Visual Studio 2019 version 16.4.5.

### Package Versions

20.05 library compiled from source using Visual Studio 2017. (VS 2017 built the library, not the code linking to the library).

**Comment by gitamohr** [comment]
Right -- the value type VtMatrix4fArray is not currently supported in scene description.

**Comment by spiffmon** [comment]
... and even if VtMatrix4fArray _were_ available in scene description, every attribute in USD is strongly typed, and since _restTransforms_ is declared as a `matrix4d []` , any Get() call on its UsdAttribute with a  VtMatrix4fArray out-param would generate a different error.  You _can_ fetch attribute values as VtValue and use VtValue::Cast() to convert between different datatypes, if such a conversion is available.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6017

**Comment by spitzak** [comment]
It would be really nice if the error message was more like "`pxr::UsdAttribute::Get<pxr::VtMatrix4fArray>(pxr::VtMatrix4fArray&): not found`". But that is probably something for compiler developers to fix.

**Comment by c64kernal** [comment]
Thanks for the discussion everyone -- going to close this out for now.
