### ISSUE TITLE
[Storm] Crash on material changes when material is using primvar

### ISSUE THREAD

**Issue by jufrantz** [PixarAnimationStudios/USD#1182]
### Description of Issue

Since USD 20.05, we get a seg fault when attempting to change material assignments from a scene delegate in some cases. It happens when the currently bound material is using uniform primvar(s) but not the new one, when the list of required elements buffers becomes empty at draw item update.

I reproduced the issue with usdview by turning off the `enable scene materials` setting.

### Steps to Reproduce
1. Run testusdview with python script and usd scene in [reproUsdViewCrashOnMaterialChange.zip](https://github.com/PixarAnimationStudios/USD/files/4538510/reproUsdViewCrashOnMaterialChange.zip)
`testusdview --renderer GL --testScript reproUsdViewCrashOnMaterialChange.py reproUsdViewCrashOnMaterialChange.usda`

2. Notice the crash

### System Information (OS, Hardware)

Linux

### Package Versions
USD 20.05

**Comment by jilliene** [comment]
Filed as internal issue #USD-6022

**Comment by jufrantz** [comment]
Hi,
Just tested the fix on our side with USD 21.02 and it works like a charm.
Thank you !
