### ISSUE TITLE
Build 20.05 in WIndows : infamous pthread.h error!

### ISSUE THREAD

**Issue by devGitHub48** [PixarAnimationStudios/USD#1187]
Hello!
Once again, I have issues compiling USD :D
I know at some point someone change something to be able to compile correctly
### Description of Issue
The infamous pthread.h error :D

Impossible to compile the usd 20.05 USD version

-- Configuring incomplete, errors occurred!
See also "E:/myproject/usd_20_05_boost/build/USD/CMakeFiles/CMakeOutput.log".
See also "E:/myproject/usd_20_05_boost/build/USD/CMakeFiles/CMakeError.log".

ERROR: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="e:\myproject\usd_20_05_boost" -DCMAKE_PREFIX_PATH="e:\myproject\usd_20_05_boost" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 15 2017 Win64" -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE="c:\Python27\python.exe" -DPYTHON_LIBRARY="c:\Python27\libs\python27.lib" -DPYTHON_INCLUDE_DIR="c:\Python27\Include" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EXAMPLES=ON -DPXR_BUILD_TUTORIALS=ON -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_ENABLE_OPENVDB_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_BUILD_MATERIALX_PLUGIN=OFF -DCMAKE_CXX_FLAGS="/Zm150" -DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True "E:\github\usd\USD"'
See e:\myproject\usd_20_05_boost\build\USD\log.txt for more details.

### Steps to Reproduce
1.  git checkout v20.05
2. E:\github\usd>set MAYA_PATH=C:\Program Files\Autodesk\Maya2021
E:\github\usd>set GIT=C:\Program Files\Git
E:\github\usd>set PATH=%GIT%\usr\bin;%GIT%\mingw64\bin;%PATH%
E:\github\usd>set PATH=%PATH%;c:\Python27;c:\Python27\Scripts
3. E:\github\usd>python USD\build_scripts\build_usd.py --force-all --verbose --build-args=boost,"--with-date_time --with-thread --with-system --with-filesystem" "e:\myproject\usd_20_05_boost
[build_usd_20_05_boost.log](https://github.com/PixarAnimationStudios/USD/files/4548014/build_usd_20_05_boost.log)

### System Information (OS, Hardware)
Windows 10 (1903)
### Package Versions
v20.05

I should have missed something in the build :(

**Comment by meshula** [comment]
The pthread message is a red herring. The configuration system is testing whether pthreads exist on your system or not (no, it doesn't), and it then chooses a threading model accordingly. The real problem is that cmake is unable to detect the installation of boost, which did occur correctly. I would have to guess that your step 3 is breaking something in the build system. Does it help to do this? ```E:\github\usd>python USD\build_scripts\build_usd.py --force-all --verbose "e:\myproject\usd_20_05_boost_test``` I suspect you are trying to get the USD build script to build all of boost for other purposes, but I think a good starting point would be to try to build USD in the most simple way first, to verify that your system is set up for it. Or have you got an "out of the box" standard build accomplished already?

Note that I added _test to the command here, because cmake scripts often don't like changing configurations in the same directory, so _test will force the build into a new location to avoid any configuration problems in the first directory.

**Comment by devGitHub48** [comment]
Hello Nick!

Thanks for the help.

I gave a try of your test and unfortunatelly, I have the same issue :(
```
-- Found PythonLibs: C:/Python27/libs/python27.lib (found suitable version "2.7.17", minimum required is "2.7") 
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/defaults/Packages.cmake:50 (find_package)
  CMakeLists.txt:23 (include)


CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/defaults/Packages.cmake:81 (find_package)
  CMakeLists.txt:23 (include)
```
Here are the logs:
[build_usd_20_05_boost_test.log](https://github.com/PixarAnimationStudios/USD/files/4548218/build_usd_20_05_boost_test.log)
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/4548223/CMakeError.log)
[CMakeOutput.log](https://github.com/PixarAnimationStudios/USD/files/4548224/CMakeOutput.log)

What should I check once again?

**Comment by sunyab** [comment]
Try updating your CMake version, it looks like you have 3.13 installed but you'll need 3.14 or later for boost 1.70.0.

**Comment by devGitHub48** [comment]
Oh damn!!!

**Comment by devGitHub48** [comment]
> Try updating your CMake version, it looks like you have 3.13 installed but you'll need 3.14 or later for boost 1.70.0.

So where should I send the donuts because you fixed my issues @meshula and @sunyab ??

```

Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    e:\myproject\usd_20_05_boost_cmake317_\lib\python

    The following in your PATH environment variable:
    e:\myproject\usd_20_05_boost_cmake317_\bin
    e:\myproject\usd_20_05_boost_cmake317_\lib
```
