### ISSUE TITLE
Building for Windows, have to manually edit CMakeCache.txt to fix Boost_INCLUDE_DIR:PATH

### ISSUE THREAD

**Issue by jamumamu** [PixarAnimationStudios/USD#1188]
### Description of Issue

Running build_usd.py on Windows will fail to find the boost header files when building USD--even though it successfully downloaded and build boost in an earlier step.

### Steps to Reproduce

1. Follow the helpful instructions here: https://www.manicmachinegames.com/blog/2019/1/10/tutorial-setting-up-and-building-pixars-usd-on-windows

2. With everything set up right the entire process works, however when the `build_usd` script reaches the step where it's "Installing USD" it fails due to this line in CMakeCache.txt: `Boost_INCLUDE_DIR:PATH=Boost_INCLUDE_DIR-NOTFOUND`

3. Edit the script to read something like `Boost_INCLUDE_DIR:PATH=C:/USD/include/boost-1_70`

4. Re-run the script and now it will build the USD library successfully.

### System Information (OS, Hardware)

Windows 10 Pro, Visual Studio 2017, Python 2.7

### Package Versions

Compiling with change `ebac0a8` (Merge release v20.05)

### Build Flags
Default

**Comment by sunyab** [comment]
Hi @jamumamu, what version of cmake do you have installed? You may need to update your CMake to a newer version, as boost 1.70 requires CMake 3.14+

**Comment by jamumamu** [comment]
`cmake version 3.12.18081601-MSVC_2`

Thanks for the suggestion--I'll upgrade and give it another try in a fresh dir.

**Comment by jamumamu** [comment]
Confirmed that building with CMake 3.17 works as intended.

Tip for other people encountering this problem: make sure you're not accidentally using the version of CMake that comes with Visual Studio!
