### ISSUE TITLE
Missing DllMain.cpp in pxr\imaging\plugin\hdStream

### ISSUE THREAD

**Issue by zhoub** [PixarAnimationStudios/USD#119]
https://github.com/PixarAnimationStudios/USD/tree/master/pxr/imaging/plugin/hdStream

CMake reports the error about missing DllMain.cpp

**Comment by jtran56** [comment]
Filed as internal issue #141323.

**Comment by c64kernal** [comment]
Thanks for the report.  Should be fixed now.
