### ISSUE TITLE
Generating doxygen tag file from documentation build

### ISSUE THREAD

**Issue by moddyz** [PixarAnimationStudios/USD#1195]
### Description of Issue

It would be useful for the doxygen build process to generate a tagfile - so other documentation can reference the USD docs.

An option to enable this, or perhaps for a tagfile to always be generated with documentation is built would be extremely helpful!

Thanks!!

### System Information (OS, Hardware)

`ubuntu-18.04`

### Package Versions

`usd-20.05`

### Build Flags

```
-DPXR_BUILD_DOCUMENTATION=ON
```

**Comment by jilliene** [comment]
Filed as internal issue #USD-6038
