### ISSUE TITLE
UsdImaging is not drawing point instancers with non-default prototypes properly

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#1198]
[sphereInstancer.zip](https://github.com/PixarAnimationStudios/USD/files/4588776/sphereInstancer.zip)

Load the attached usda in usdview. It is a point instancer with a sphere prototype that has its radius set to 20.4

usdview will draw the instances as unit spheres.

If you then select the radius attribute on the prototype and 

`usdviewApi.property.Set(20.4)
`
in the interpreter, you'll see the result that should have come up upon initial draw.

Thanks for looking!

**Comment by spitzak** [comment]
Even when it draws correctly, the automatic clipping planes in usdview seem to be for the points and clip off the sphere closest to the camera.

**Comment by spiffmon** [comment]
That usually indicates incorrect authored _extent_ - if you change a sphere's radius, it is on you to also reauthor its extent.

You **can** disable the automatic clipping planes with the 'c' hotkey (it's a toggle).  The auto-clipping is most useful when navigating big sets.. less useful for detail work.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6055.

**Comment by c64kernal** [comment]
Hey @asluk  -- what happens when you use "double" on the radius instead of "float"? (see schema: https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/usdGeom/schema.usda#L560). (props to @tcauchois for noticing that)

**Comment by asluk** [comment]
D'oh, yes that was it! Sorry for the noise-- thanks very much!
