### ISSUE TITLE
Error in documentation of UsdMeshGeometry.cornerIndices

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1199]
### Description of Issue

The documentation in the mesh.h header file says "The vertex indices of all vertices that are sharp corners." I believe this should actually say "The point indices of all points that are sharp corners".

**Comment by qa8302** [comment]
> ### Description of Issue
> 
> 
> 
> The documentation in the mesh.h header file says "The vertex indices of all vertices that are sharp corners." I believe this should actually say "The point indices of all points that are sharp corners".
> 
>

**Comment by jtran56** [comment]
Filed as internal issue #USD-6057.

**Comment by spiffmon** [comment]
This was addressed by [commit f0c39c5](https://github.com/PixarAnimationStudios/USD/commit/f0c39c54bdac19bb03f41fb56cbc666f41504644#diff-7fbb17730ae9b2f6e1c1f7538d9ddeae)
