### ISSUE TITLE
USDPython 0.64 missing blendshapes

### ISSUE THREAD

**Issue by alelordelo** [PixarAnimationStudios/USD#1202]
Goal:
Convert from FBX to USD, preserving morph targets

What I did:
Used USDPython 0.64 converter bellow:
https://developer.apple.com/download/more/?=USDPython

Output:
Opened in Xcode, but morph targets are not there

**Comment by c64kernal** [comment]
Hi @alelordelo, unfortunately USDPython is not maintained here, you will have to report the issue through Apple.
