### ISSUE TITLE
"UsdTransform2d" broken in usdview

### ISSUE THREAD

**Issue by jackcaron** [PixarAnimationStudios/USD#1207]
### Description of Issue

`UsdTransform2d` used to work in `usdview` (_or at least not crash_).

### Steps to Reproduce
1. Use `usdview` to open a usdz file that contains the `UsdTransform2d`

### System Information (OS, Hardware)

- Ubuntu 18.04

### Package Versions

20.05

### Build Flags
`-no-alembic --no-draco --no-ptex --no-hdf5 --no-materialx --no-tutorials`

**Comment by spiffmon** [comment]
Hi @jackcaron , UsdTransform2d has never worked in Storm or HdPrman (though we plan to fix that soon), but it should not cause a crash.  It would help alot if you could provide an asset that's causing crashes for you.

Cheers,
--spiff

**Comment by jackcaron** [comment]
I don't remember if the tiling was working in Hydra, but at least I could inspect the file before looking at it in AR Kit (_not doing dev on iOS/Mac, so trying to rely on this tool as much as I can before borrowing a device to test_).

https://drive.google.com/open?id=14IxEiGTH00p6u5TuKddXX_HRZZ0kbIum  (_let me know if it doesn't work_).

Then simply use `usdview`.

**EDIT**: new link on my drive instead

**Comment by drwave** [comment]
That file doesn’t seem to be public.

**Comment by jtran56** [comment]
Filed as internal issue #USD-1207.

**Comment by sunyab** [comment]
This should be addressed by commit 30e3c987 in the dev branch. Marking as pending release for the upcoming 20.08 release.

**Comment by jackcaron** [comment]
thanks a lot @sunyab

**Comment by sunyab** [comment]
Closing, this should be fixed in the 20.08 release. Thanks!
