### ISSUE TITLE
Crash in UsdImagingInstancerAdapter::GetScenePrimPath

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1210]
### Description of Issue
When an instanced piece of geometry is switched to "bouds" draw mode, the next attempt to call GetScenePrimPath for that primitive will crash.

### Steps to Reproduce
1. Load the pigref.usda file from the attached archive into usdview.
[pig.zip](https://github.com/PixarAnimationStudios/USD/files/4651487/pig.zip)
2. In the Interpreter window, run:
s = usdviewApi.stage
p = s.GetPrimAtPath('/testgeometry_pighead1')
m = UsdGeom.ModelAPI(p)
a = m.CreateModelDrawModeAttr()
a.Set('bounds')
3. Select the bounding box, or move the mouse over the bounding box if you have rollover tooltips enabled. usdview will crash.

### Package Versions
USD 20.05

**Comment by jtran56** [comment]
Filed as internal issue #USD-6076.
