### ISSUE TITLE
usdImaging engine can't do AOV's with period in them

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1215]
### Description of Issue
AOV's with various characters (space and period at least) in them produce errors and never make the bprim. I think what is needed is to fix HdxTaskController::_GetAovPath() but need more info on what characters are valid, probably replacing all of them with underscore will work and not produce collisions.

### Steps to Reproduce
1. In usdview, pick AOV/other and type "foo:a.b" as the AOV name

### System Information (OS, Hardware)
Linux

### Package Versions
USD 20.02

**Comment by spitzak** [comment]
Actually it fails on almost all punctuation marks, which makes it pretty impossible to use the proposed lpe: aov names.

**Comment by spitzak** [comment]
The following patch does fix it, though I think it could be improved with more accuracy as to what characters are allowed in a path component:

```
--- a/pxr/imaging/hdx/taskController.cpp
+++ b/pxr/imaging/hdx/taskController.cpp
@@ -819,8 +819,15 @@ HdxTaskController::GetPickingTasks() const
 SdfPath
 HdxTaskController::_GetAovPath(TfToken const& aov) const
 {
-    std::string str = TfStringPrintf("aov_%s", aov.GetText());
-    std::replace(str.begin(), str.end(), ':', '_');
+    std::string str = "aov_";
+    str.reserve(4 + aov.GetString().length());
+    for (char c : aov.GetString()) {
+        if (std::isalnum(c) || (c&0x80 /*assume UTF-8 is ok*/)) {
+            str.push_back(c);
+        } else {
+            str.push_back('_');
+        }
+    }
     return GetControllerId().AppendChild(TfToken(str));
 }
 

```

**Comment by jtran56** [comment]
Filed as internal issue #USD-6085.
