### ISSUE TITLE
Support animated light visibility and other properties

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#1216]
Currently, animating light visibility has no effect on the rendered image-- HdLights do not have a dirty bit for visibility, and UpdateForTime is not called for sprims, per the latest state of https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usdImaging/usdImaging/lightAdapter.cpp .

[lightAnimVis.zip](https://github.com/PixarAnimationStudios/USD/files/4655834/lightAnimVis.zip)

See attached example for a sphere, and a sphere light with animated visibility.

Spinning off from https://groups.google.com/d/msg/usd-interest/Z5kAJoUTd1g/AJoibTf2BQAJ

**Comment by jtran56** [comment]
Filed as internal issue #USD-6081.

**Comment by asluk** [comment]
Verified that this was fixed by https://github.com/PixarAnimationStudios/USD/commit/16a59effb78e03e4a49c4d23d54aac316673c037
