### ISSUE TITLE
boost downloading source is crazily slow

### ISSUE THREAD

**Issue by iqch** [PixarAnimationStudios/USD#1224]
### Description of Issue

source https://downloads.sourceforge.net/project/boost/boost/1.70.0/boost_1_70_0.tar.gz in builsd_scripts/build_usd.py works really slow and may lead to an hour or more wasting of time just waiting file arrived. Boost itself distributes it from different location, which works really faster
https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz

### Steps to Reproduce
1. 

### System Information (OS, Hardware)
Win10 Pro64

### Package Versions
20.00

**Comment by jtran56** [comment]
Filed as internal issue #USD-6090.

**Comment by sunyab** [comment]
This was (indirectly) addressed by 22853b19. build_usd.py now downloads from boostorg.jfrog.io, which is the location boost.org advertises for downloads: https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html.

This change will be part of the upcoming release.

**Comment by sunyab** [comment]
This was addressed in the 21.11 release.
