### ISSUE TITLE
USD build on linux Red Hat Enterprise Linux Server release 7.6 (Maipo) fails

### ISSUE THREAD

**Issue by ytneosoft** [PixarAnimationStudios/USD#1226]
### Description of Issue
USD build fails on Red Hat Enterprise Linux Server release 7.6 (Maipo)
Not able to figure out what the exact error

### Steps to Reproduce
1. python usdsrc/build_scripts/build_usd.py -v --no-usdview ${USD_BUILD_PATH}

### System Information (OS, Hardware)
OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
Processor: product: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz

### Package Versions
USD: 20.05
gcc: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39.0.3)

### Build Flags
[ 51%] Linking CXX shared library libhgiGL.so
[ 52%] Built target hgiGL
gmake: *** [all] Error 2

ERROR: Failed to run 'cmake --build . --config Release --target install -- -j4'
[log.txt](https://github.com/PixarAnimationStudios/USD/files/4687770/log.txt)

[CMakeCache.txt](https://github.com/PixarAnimationStudios/USD/files/4687641/CMakeCache.txt)

**Comment by sunyab** [comment]
Hi @ytneosoft, what version of g++ are you running? If you could post the CMakeCache.txt from your build directory (typically <inst>/build/USD) that could help narrow things down.

**Comment by ytneosoft** [comment]
Hi @sunyab 
I am using gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39.0.3)
Please find CMakeCache.txt file below 
[CMakeCache.txt](https://github.com/PixarAnimationStudios/USD/files/4687654/CMakeCache.txt)

**Comment by sunyab** [comment]
USD 20.05 requires C++14 which is not supported by 4.8.5, so you'll need to use a newer gcc version to build.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6091.
