### ISSUE TITLE
UsdSkel display crash

### ISSUE THREAD

**Issue by cameronwhite** [PixarAnimationStudios/USD#1228]
### Description of Issue
This is a crash we've encountered working interactively with UsdSkel in Houdini, but can reproduce standalone in usdview with a stripped down file.

### Steps to Reproduce
1. Extract [usdskel.tar.gz](https://github.com/PixarAnimationStudios/USD/files/4704474/usdskel.tar.gz) and enter the folder
2. Copy over the `HumanFemale` folder from the [UsdSkel sample](http://graphics.pixar.com/usd/downloads.html), which is too large to include as a Github attachment
2. Run `usdview usdskel_1.usda`
3. Ensure that `View` -> `Display Purposes` -> `Guide` is enabled
4. Scrub the timeline a bit.
5. In the interpreter, run
```
l = Sdf.Layer.FindOrOpen("usdskel_2.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)
```
6. Scrubbing the timeline should crash immediately (example crash log is included in the archive)

### System Information (OS, Hardware)

Ubuntu 18.04, gcc 7.5

### Package Versions

USD 20.05

**Comment by spiffmon** [comment]
Thanks, @cameronwhite - we are IP on pulling in PR #1213

**Comment by cameronwhite** [comment]
Great, thank you!
I think this crash is unrelated to the one fixed in my PR, since it's occuring in the skeleton imaging rather than in BakeSkinning

**Comment by spiffmon** [comment]
Ah - so sorry I conflated the two; I thought I saw "baking" in this report, but now I see I was imagining it.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6104.
