### ISSUE TITLE
Point Instanser incorrect processing

### ISSUE THREAD

**Issue by iqch** [PixarAnimationStudios/USD#1230]
### Description of Issue

usdview or its stageView widget shows incorrectly point instancer content in frames without instances defined - just keep content of latest non-empty state

### Steps to Reproduce

#usda 1.0
(
    endTimeCode = 3
    startTimeCode = 1
)

def PointInstancer "Proximities"
{
    rel prototypes = </ball>
    quath[] orientations = []
    point3f[] positions = []
    point3f[] positions.timeSamples = {
        1: [],
        2: [(3, 0, 0),(6, 0, 0)],
        3: [(3, 0, 0),(6, 0, 0),(9, 0, 0)]
    }
    int[] protoIndices = []
    int[] protoIndices.timeSamples = {
        1: [],
        2: [0,0],
        3: [0,0,0]
    }
    float3[] scales = []
    float3[] scales.timeSamples = {
        1: [],
        2: [(1, 1, 1),(1, 1, 1)],
        3: [(1, 1, 1),(1, 1, 1),(1, 1, 1)]
    }
}

def Sphere "ball"
{
    color3f[] primvars:displayColor = [(1, 1, 1)]
    double radius = 1
    token visibility = "hidden"
}

screengrab
https://vimeo.com/424909279

### System Information (OS, Hardware)
USD20.05 Win10 MSVS2017 Win64
Python3.6

**Comment by jtran56** [comment]
Filed as internal issue #USD-6100.
