### ISSUE TITLE
centos7 build error

### ISSUE THREAD

**Issue by joonkyun** [PixarAnimationStudios/USD#1233]
### Description of Issue
using python2.7.16 in anaconda
installed packages
cmake version 3.13.4
pyside-tools
python-pyside
python-devel
PyOpenGL
libpng-devel
mesa-libGL-devel
mesa-libGLU-devel
libXrandr
libXrandr-devel
libXcursor-devel
glfw
glfw-devel
glew-devel
libXi-devel
boost-python
boost-python-devel
```
[ 49%] Building CXX object pxr/base/trace/CMakeFiles/_trace.dir/wrapTestTrace.cpp.o
In file included from /usr/local/src/USD-20.05/pxr/base/vt/dictionary.cpp:26:0:
/usr/local/src/USD-20.05/pxr/base/vt/dictionary.h:64:53: error: wrong number of template arguments (0, should be 1)
     typedef std::map<std::string, VtValue, std::less<>> _Map;
                                                     ^
In file included from /usr/include/c++/4.8.2/functional:49:0,
                 from /usr/local/USD/include/boost/functional/hash/hash.hpp:20,
                 from /usr/local/USD/include/boost/functional/hash.hpp:6,
                 from /usr/local/src/USD-20.05/pxr/base/tf/pyObjWrapper.h:31,
                 from /usr/local/src/USD-20.05/pxr/base/vt/value.h:32,
                 from /usr/local/src/USD-20.05/pxr/base/vt/dictionary.h:31,
                 from /usr/local/src/USD-20.05/pxr/base/vt/dictionary.cpp:26:
/usr/include/c++/4.8.2/bits/stl_function.h:231:12: error: provided for ‘template<class _Tp> struct std::less’
     struct less : public binary_function<_Tp, _Tp, bool>
            ^
In file included from /usr/local/src/USD-20.05/pxr/base/vt/dictionary.cpp:26:0:
/usr/local/src/USD-20.05/pxr/base/vt/dictionary.h:64:54: error: template argument 3 is invalid
     typedef std::map<std::string, VtValue, std::less<>> _Map;
```
### Steps to Reproduce
1. /home/myName/anaconda2/bin/python build_scripts/build_usd.py /usr/local/USD

### System Information (OS, Hardware)
centos 7.4
intel core i7-9700k
geforce RTX 2070

### Package Versions
USD 20.05

What can I do ?
Please help me.
Thank you.
[log.txt](https://github.com/PixarAnimationStudios/USD/files/4726981/log.txt)

**Comment by sunyab** [comment]
It looks like you're using gcc 4.8.5, which does not have full support for C++14 required by USD. Please try using a newer version of gcc, like gcc 6.

**Comment by joonkyun** [comment]
> It looks like you're using gcc 4.8.5, which does not have full support for C++14 required by USD. Please try using a newer version of gcc, like gcc 6.

Thank you sunyab
I tried using gcc 6.5 but I got a same error

**Comment by sunyab** [comment]
Could you post a log file showing your build error with gcc 6?

**Comment by jtran56** [comment]
Filed as internal issue #USD-6115.

**Comment by dolivares-spin** [comment]
We're also having this issue building 20.05 on Centos 7 with gcc 4.8.5.  Tried gcc 6.4.0 and 10.1.0 which gave different errors related to libstdc++.so.6 being out of date.  20.02 builds ok.

[usd_20.05_gcc485_log.txt](https://github.com/PixarAnimationStudios/USD/files/4839923/usd_20.05_gcc485_log.txt)
[usd_20.05_gcc640_log.txt](https://github.com/PixarAnimationStudios/USD/files/4839924/usd_20.05_gcc640_log.txt)

**Comment by Acidpix** [comment]
I have issue for build 20.05 too , im using gcc 6.3.0
[log.txt](https://github.com/PixarAnimationStudios/USD/files/4850797/log.txt)

**Comment by gitamohr** [comment]
Acidpix, the log you posted shows a build with gcc 4.8.5:
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5

**Comment by dolivares-spin** [comment]
I believe you need to set the CC and CXX environment variables to the paths to gcc and g++ respectively to get cmake to use them.

**Comment by dolivares-spin** [comment]
This was fixed for us by installing the devtoolset-8 software collection library on centos 7.

**Comment by sunyab** [comment]
Just wanted to note that if you're using the devtoolset software collection on CentOS to get newer developer tools, you may need to enable the environment for that toolset via the `scl enable` command. See https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/ (or the documentation for your installed devtoolset version) for more information.

Closing this out.
