### ISSUE TITLE
Skinning display issues with inherited primvars

### ISSUE THREAD

**Issue by cameronwhite** [PixarAnimationStudios/USD#1234]
### Description of Issue

Inherited skinning primvars (`primvars:skel:jointIndices`, `primvars:skel:jointWeights`, `primvars:skel:geomBindTransform`) are supported by `BakeSkinning`, but not when displaying skinned meshes normally.

### Steps to Reproduce
1. Open the attached file ([rigid_skinning.zip](https://github.com/PixarAnimationStudios/USD/files/4730785/rigid_skinning.zip)) in `usdview` and switch to `/cameras/camera1`
2. Adjust the visibility to view `/Model/SkinnedArm`, `/Model/RigidSkinnedArm`, and `/Model/Parent/RigidSkinnedArm` individually. No skinning occurs for `/Model/Parent/RigidSkinnedArm` which inherits the skinning primvars from `/Model/Parent`
3. Run `UsdSkel.BakeSkinning(usdviewApi.stage.Traverse())` in the interpreter, which produces the expected results. (There is some odd interpolation on frames 2 and 4, but I think that's because BakeSkinning only evaluates on the skel animation's time samples)

### System Information (OS, Hardware)

USD 20.05

**Comment by jtran56** [comment]
Filed as internal issue #USD-6114.

**Comment by cameronwhite** [comment]
It looks like this was fixed in 20.08, probably due to 2da43d8d. Thanks!
