### ISSUE TITLE
Suggestion for CMake statement ordering

### ISSUE THREAD

**Issue by foundry-markf** [PixarAnimationStudios/USD#1241]
### Description of Issue

The top-level CMakeLists.txt (in the dev branch) currently begins with:

```
project(usd)

cmake_minimum_required(VERSION 3.12)
```

The documentation for CMake says that `project` should come _after_ `cmake_minimum_required`. See https://cmake.org/cmake/help/latest/command/project.html#usage
and https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#cmake-minimum-required

In switching these statements around, for macOS builds (albeit still experimental) at least, this proposal changes the policy that identifies the compiler as AppleClang rather than Clang. See https://cmake.org/cmake/help/latest/policy/CMP0025.html
So a change to `cmake/defaults/CXXDefaults.cmake` is also required, i.e.

```
if (CMAKE_COMPILER_IS_GNUCXX)
    include(gccdefaults)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    include(clangdefaults)
elseif(MSVC)
    include(msvcdefaults)
endif()
```

to change the `STREQUAL` to `MATCHES`.
All the other cases I have found for clang already use `MATCHES` or explicitly check for AppleClang.

### System Information (OS, Hardware)
I've tried this out on a macOS build on a much older version of USD, and has made my builds behave as I would expect when using CMake 3+.

I've not tried it on other platforms (yet), but it appears to be making the USD CMake scripts more inline with recommended practices.

Thanks

**Comment by jtran56** [comment]
Filed as internal issue #USD-6120.
