### ISSUE TITLE
Crash in UsdImaging when "moving" an instanced primitive to a different scene graph location

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1245]
### Description of Issue
After loading a particular USD file with a payload that contains an instanceable reference, updating the scene to load the same payload to a different scene graph location leads to a crash in the instancerAdapter.cpp in UsdImaging.

### Steps to Reproduce
1. Load testA.usda into usdview from the attached zip file:
[instanceableCrash.zip](https://github.com/PixarAnimationStudios/USD/files/4782498/instanceableCrash.zip)
2. In the Interpreter window, run the following commands:
l = Sdf.Layer.FindOrOpen("./testB.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)
3. usdview will crash in UsdImagingInstanceAdapter::_Populate calling _GetPrim(instancerPath).IsInMaster() (because the _GetPrim call returns a null UsdPrim).

### Package Versions
Approximately USD 20.05 (https://github.com/sideeffects/USD/tree/dev_houdini18.5.197, which is 20.05 plus a few additional changes, most or all of which I believe are in the USD dev branch already).

**Comment by c64kernal** [comment]
Filed as internal issue #USD-6146

**Comment by c64kernal** [comment]
We have a fix for this checked in and should be included in the 20.08 release.
