### ISSUE TITLE
Sdf compilation error

### ISSUE THREAD

**Issue by krzykli** [PixarAnimationStudios/USD#125]
When compiling the current head revision of `dev_win_ip` branch (8cac49c03e3b20a2dcc661dc27b62736fcf993ce) I'm getting the following error:
```
O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\USD\pxr\usd\lib\sdf\path.cpp(232): error C2039: 'ContainsTargetPath': is not a member of 'SdfPath' [O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\stage\prereq\build\USD\pxr\usd\lib\sdf\sdf.vcxproj]
O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\USD\pxr\usd\lib\sdf\path.cpp(233): error C2270: 'ContainsTargetPath': modifiers not allowed on nonmember functions [O:\dev\krzysztof.klimczy\workspace\usdBuildFixed\Projects\stage\prereq\build\USD\pxr\usd\lib\sdf\sdf.vcxproj]
O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\USD\pxr\usd\lib\sdf\path.cpp(234): error C2065: '_pathNode': undeclared identifier [O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\stage\prereq\build\USD\pxr\usd\lib\sdf\sdf.vcxproj]
```
#### System Information (OS, Hardware)
Windows 7

**Comment by jtran56** [comment]
Filed as internal issue #141430.

**Comment by c64kernal** [comment]
Hi!  Do you mind checking to see if your sdf/path.h has ContainsTargetPath declared?
I'm not able to reproduce this problem locally unfortunately.  Do you have any more information on how your project is configured?  Were you able to successfully compile dev_win_ip before a certain commit?  Thanks for any additional information!

**Comment by krzykli** [comment]
Hey @c64kernal, just to give you a quick feedback - from memory, I've built USD successfully with 2bea7ca40e4d63014eb3e9b9f447799b068a7ca1, but it failed already with 1549b884da3a0af295b98e344ccd5bdb01af6757, with the error message above. I had a quick peek at the `sdf/path.h` and everything there seems to be in order. My config follows https://github.com/vfxpro99/usd-build-club.
If I have enough time today I will rebuild USD again with these two commits to double-check this for you.

**Comment by krzykli** [comment]
I can confirm now what I wrote in the previous comment.
On my machine 1549b884da3a0af295b98e344ccd5bdb01af6757 will fail to compile (also because of #116), but I have no problems with the commit before it. Would be great if somebody else could check this as well so we can rule out the possibility this issue affects just me :)

**Comment by c64kernal** [comment]
Hi @krzykli -- thanks for confirming.  I've tried again and I can't seem to get the same issue building from head.  Apologies for a silly question, but are you building from a fresh branch completely from scratch?  (Note: I don't use build-club)

**Comment by meshula** [comment]
Another related question, did you try deleting the published headers? Cmake doesn't detect stale headers very well, so my suspicion is that the new headers did not get published, and so you are compiling against a version of the header without the declspec in it.

**Comment by krzykli** [comment]
Thanks for the tip @meshula. That was exactly it! I've deleted the published headers, and successfully recompiled USD. Now I know to keep an eye on it.
Apologies for the noise.
Closing!
