### ISSUE TITLE
UsdImaging destroys prims unnecessarily

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1250]
### Description of Issue
Any changes (create, remove, and set) of an unknown attribute causes the prim to be destroyed and recreated. This does not happen if an attribute the sceneDelegate knows about is changed.

It would be better to do nothing. Call Sync() if it is proper for a render delegate to access arbitrary attributes.

### Steps to Reproduce
Add some message to Mesh::Finalize()
usdview some geometry and select a mesh
usdviewApi.prim.CreateAttribute("foo", Sdf.GetValueTypeNameForValue(True)).Set(False)
You can see Finalize was called.

### System Information (OS, Hardware)
Linux

### Package Versions
20.05

**Comment by jtran56** [comment]
Filed as internal issue #USD-6170.

**Comment by spitzak** [comment]
Possibly related: changing the value of lightLink or shadowLink on a Light also causes the Light prim to be destroyed and recreated.
