### ISSUE TITLE
Boost_PYTHON_LIBRARY not populated with Boost1.70+ unless -DBoost_NO_BOOST_CMAKE is specified

### ISSUE THREAD

**Issue by kaarrot** [PixarAnimationStudios/USD#1255]
The Boost_PYTHON_LIBRARY variable is not populated when built with boost1.70+ unless explicitly pass Boost_NO_BOOST_CMAKE=ON (this is not documented in BUILDING.md)

Most bindings are built as expected only failing at runtime due to unresolved symbols.

Would it be possible to improve logic how Boost Python is detected and report problems at CMake configuration step?
- Perhaps a warning message  could be added if Boost_PYTHON_LIBRARY is not set.
- The else branch does not set Boost_PYTHON_LIBRARY at all and the variable is used in quite a few places. Would this link with with BoostPython correctly?
- Can the check for Boost_NO_BOOST_CMAKE be completely removed or extra branch added to handle the case when CMake modules could not be found
https://github.com/PixarAnimationStudios/USD/blob/master/cmake/defaults/Packages.cmake#L63

I was able to built and link successfully with the following command.
`
cmake .. -DPXR_USE_PYTHON_3=ON -DCMAKE_INSTALL_PREFIX=~/toolchains/usd_boost_1_71_1 -DPXR_BUILD_TESTS=OFF  -DBOOST_INCLUDEDIR=~/boost_1_71_0 -DBOOST_LIBRARYDIR=~/boost_1_71_0/stage/lib -DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON
`

**Comment by jtran56** [comment]
Filed as internal issue #USD-6196.
