### ISSUE TITLE
support for arm64

### ISSUE THREAD

**Issue by kaarrot** [PixarAnimationStudios/USD#1256]
ARM64 seems to be supported in some places - https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/arch/defines.h#L57
There are few other where it is not handled and falls into "Unknown architecture" category and fails the build.
- https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/arch/math.h#L100
- https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/arch/math.h#L123
- https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/arch/stackTrace.cpp#L624
- https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/arch/timing.h#L72

I was able to patch these and built but I was wondering what is the official status for Arm64 at the moment?
Thank you.

**Comment by c64kernal** [comment]
Hi @kubaroth -- the official status is "unsupported" for now, of course, as you can imagine that will change, unfortunately I don't have a timeline handy for you.

**Comment by kaarrot** [comment]
Sounds good. Thank you @c64kernal
