### ISSUE TITLE
Should building for Windows with Python 3.8 fail pre 20.8 as well?

### ISSUE THREAD

**Issue by chrizzFTD** [PixarAnimationStudios/USD#1260]
### Description of Issue

Hi,

Thanks for this amazing project! It's always exciting to see the upcoming release changelog.

I've just read that the [changelog for the 20.8 release](https://github.com/PixarAnimationStudios/USD/blob/22429596649721c8c4eccab71bad37e5c8cb5e47/CHANGELOG.md) has this entry:

> Python 3.8 on Windows now causes an error, as USD does not support this version on Windows.

I was wondering what the changes compared to `20.5` are to make the build fail when attempting Windows + Python-3.8. I see the build script references this python `what's new` entry:

https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew

Did things change since `20.5` that will cause an issue now? or is the `20.5` release not expected to build properly on Windows with python 3.8 either?

I'm asking because I was able to build succesfully (it seems) USD `20.5` on Windows with Python-3.8 via [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) and was keen on building again for `20.8`
I have not played too much with it other than loading stages in USD View and a bit of USD API calls, though.

![usdview_py38_win](https://user-images.githubusercontent.com/8294116/87138071-3cb2c380-c2e1-11ea-8b04-7786c4dca3f4.PNG)

Thanks!

### Steps to Reproduce
1. 

### System Information (OS, Hardware)

Windows 10
Python 3.8.3

### Package Versions

USD-20.5
Visual Studio 2019
PyOpenGL-3.1.5
PySide2-5.15.0
cmake-3.17.2
jinja2-2.11.2

### Build Flags
```
(py38usd205build) C:\>python "B:\write\code\git\USD\build_scripts\build_usd.py" -v "B:\write\builds\py38usd205build"

Building with settings:
  USD source directory          B:\write\code\git\USD
  USD install directory         B:\write\builds\py38usd205build
  ...
    Python support              On
      Python 3:                 On
...
```

**Comment by meshula** [comment]
The failure mentioned is that the python modules don't load as a result of a recent python change that ignores DLLs in the PATH:

```
On Windows, CDLL and subclasses now accept a winmode parameter to specify flags 
for the underlying LoadLibraryEx call. The default flags are set to only load DLL 
dependencies from trusted locations, including the path where the DLL is stored (if a 
full or partial path is used to load the initial DLL) and paths added by add_dll_directory(). 
(Contributed by Steve Dower in bpo-36085.)
```

We weren't able to discover how to accommodate this new behavior in time for the release in common cases such as doing a build for a global python install.

I have not used the conda environment, and it's exciting that it worked for you. Could you add a few notes for a n00b such as myself, as to how I could try to reproduce your steps?

**Comment by sunyab** [comment]
@chrizzFTD Hi, thanks for filing this! The 20.05 release was not expected to work with Python 3.8 on Windows either but we added the error in 20.08 to give people an earlier warning about this.

In our testing trying to import any of the Python modules under 3.8 failed, so I'm very surprised usdview is working. I've seen other reports of software packages running into similar issues with 3.8 too. Do you have any other environment variables set for Python? And does the os.add_dll_directory method exist if you try to call it in the usdview interpreter?

**Comment by jtran56** [comment]
Filed as internal issue #USD-6209.

**Comment by chrizzFTD** [comment]
Thanks for the replies, @meshula, @sunyab !

> We weren't able to discover how to accommodate this new behavior in time for the release in common cases such as doing a build for a global python install.

I wonder if this is the reason why it's been working on my side. I use conda to manage environments, so when building I use python from that environment instead of the "global" system one.

I tried a build from the current `dev` branch and it successfully completed after commenting these lines:

https://github.com/PixarAnimationStudios/USD/blob/22429596649721c8c4eccab71bad37e5c8cb5e47/build_scripts/build_usd.py#L1979-L1983


### Suggested steps on how to reproduce conda build

A bit more info can be found [on this blog post](http://blog.christianlb.io/building-usd-on-windows-for-python-3) which started  as an experiment.
Also, I do not know how to accomplish the first three steps from a terminal, sorry!

1. Install [miniconda for windows](https://docs.conda.io/en/latest/miniconda.html)
   Note: "conda" environment manager comes in two flavours: 
   - [Anaconda](https://docs.anaconda.com/anaconda/user-guide/getting-started/), which is [conda](https://docs.conda.io/projects/conda/en/latest/index.html) + a lot of extra utilities
   - [miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) is the main bootstrap for "conda", so that's why I prefer it
2. Install [Visual Studio Build Tools 2019](https://visualstudio.microsoft.com/visual-cpp-build-tools/)
3. Launch [Anaconda Prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/#open-anaconda-prompt) (it came as part of the `miniconda` installation)
4. Create a new conda environment with python 3.8
   ```bash
   (base) C:\>conda create -n py38usd208releasebuild python=3.8
   ```
5. Activate that environment
   ```bash
   (base) C:\>conda activate py38usd208releasebuild
   ```
6. Install jinja2 and CMake via conda
   ```bash
   (py38usd208releasebuild) C:\>conda install -c anaconda jinja2 cmake
   ```
7. Install PySide2 and PyOpenGL via pip
   ```bash
   (py38usd208releasebuild) C:\>python -m pip install PySide2 PyOpenGL
   ```
8. Get the developer command prompt for visual studio 2019
   ```bash
   (py38usd208releasebuild) C:\>conda install -c rdonnelly vs2019_win-64
   ```
9. Run the build script
   ```bash
   (py38usd208releasebuild) C:\>python "B:\write\code\git\USD\build_scripts\build_usd.py" -v "B:\write\builds\py38usd208releasebuild"
   ...
   Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    B:\write\builds\py38usd208releasebuild\lib\python

    The following in your PATH environment variable:
    B:\write\builds\py38usd208releasebuild\bin
    B:\write\builds\py38usd208releasebuild\lib
   ```
10. Set environment variables
    ```bash
    (py38usd208releasebuild) C:\>set PYTHONPATH=%PYTHONPATH%;B:\write\builds\py38usd208releasebuild\lib\python
    (py38usd208releasebuild) C:\>set PATH=%PATH%;B:\write\builds\py38usd208releasebuild\bin;B:\write\builds\py38usd208releasebuild\lib
    ```
11. Confirm USD can import
    ```bash
    (py38usd208releasebuild) C:\>python -c "from pxr import Usd;print(Usd)"
    <module 'pxr.Usd._usd' from 'B:\\write\\builds\\py38usd208releasebuild\\lib\\python\\pxr\\Usd\\_usd.pyd'>
    ```

12. Try USD View
    ```bash
    (py38usd208releasebuild) C:\>usdview "B:\read\cg\downloads\Kitchen_set\Kitchen_set\Kitchen_set.usd"
    ```

    ![usdview_py38_usd208release_win](https://user-images.githubusercontent.com/8294116/87214879-f490b100-c373-11ea-8980-98c9a41e4e03.PNG)


I ran a second build with a redirected output to a file [usd_build.log](https://github.com/PixarAnimationStudios/USD/files/4906277/usd_build.log) in case it's useful.


```
(py38usd208releasebuild) C:\>python "B:\write\code\git\USD\build_scripts\build_usd.py" -vv "B:\write\builds\py38usd208releasebuild01" 1> A:\write\usd_build.log 2>&1
```
> Do you have any other environment variables set for Python?

Not that I know of. After setting the ones from the USD build these are my `PATH` and `PYTHONPATH` variables:

```bash
(py38usd208releasebuild) C:\>echo %PATH%
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;C:\Users\Christian\.conda\envs\py38usd208releasebuild;C:\Users\Christian\.conda\envs\py38usd208releasebuild\Library\mingw-w64\bin;C:\Users\Christian\.conda\envs\py38usd208releasebuild\Library\usr\bin;C:\Users\Christian\.conda\envs\py38usd208releasebuild\Library\bin;C:\Users\Christian\.conda\envs\py38usd208releasebuild\Scripts;C:\Users\Christian\.conda\envs\py38usd208releasebuild\bin;C:\ProgramData\Miniconda3\condabin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\CMake\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\Christian\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\Christian\AppData\Local\Programs\Python\Python38;C:\Users\Christian\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\Christian\AppData\Local\Programs\Python\Python37-32;C:\Users\Christian\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\Christian\AppData\Local\Programs\Python\Python36;C:\Users\Christian\AppData\Local\Microsoft\WindowsApps;B:\__appdata__\rez\Scripts\rez;.;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;B:\write\builds\py38usd208releasebuild\bin;B:\write\builds\py38usd208releasebuild\lib

(py38usd208releasebuild) C:\>echo %PYTHONPATH%
%PYTHONPATH%;B:\write\builds\py38usd208releasebuild\lib\python
```
I just realized that on the `PATH` variable I still get some directories from previous global python `Python36` and `Python37` system installations under `C:\Users\Christian\AppData\Local\Programs\Python\`. I wonder if that causes any discrepancy in any way? I hope not as the python interpreter being used in the environment always points to `3.8`:
```
(py38usd208releasebuild) C:\>python -VV
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]

(py38usd208releasebuild) C:\>python -c "import sys;print(sys.executable)"
C:\Users\Christian\.conda\envs\py38usd208releasebuild\python.exe
```


> does the os.add_dll_directory method exist if you try to call it in the usdview interpreter?

I can confirm `os.add_dll_directory` exists in the usdview interpreter in both `20.5` and `20.8 release candidate`

**Comment by meshula** [comment]
This is fantastic, thanks! I will attempt a repro as soon as my office is cool enough to enter :)

**Comment by meshula** [comment]
Conda recipe is working for me on Mac as well. Thanks for laying it out so explicitly!

**Comment by Trafle** [comment]
What can I do to get it to work???

**Comment by chrizzFTD** [comment]
Hi @Trafle, have you tried the `conda` recipe from https://github.com/PixarAnimationStudios/USD/issues/1260#issuecomment-656985888?

I just tried this from the current `release` branch with `Python-3.9`, I commented out these lines:

https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/build_scripts/build_usd.py#L1995-L1999

And after following the recipe, USD successfully built for me:

```bash
(base) C:\Users\Christian>conda create -n py39usd2105build python=3.9
(base) C:\Users\Christian>conda activate py39usd2105build
(py39usd2105build) C:\Users\Christian>conda install -c anaconda jinja2 cmake
(py39usd2105build) C:\Users\Christian>python -m pip install PySide2 PyOpenGL
(py39usd2105build) C:\Users\Christian>conda install -c rdonnelly vs2019_win-64
(py39usd2105build) C:\Users\Christian>python B:\write\code\git\USD\build_scripts\build_usd.py -v B:\write\builds\py39usd2105build
...
Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    B:\write\builds\py39usd2105build\lib\python

    The following in your PATH environment variable:
    B:\write\builds\py39usd2105build\bin
    B:\write\builds\py39usd2105build\lib

(py39usd2105build) C:\Users\Christian>set PYTHONPATH=%PYTHONPATH%;B:\write\builds\py39usd2105build\lib\python
(py39usd2105build) C:\Users\Christian>set PATH=%PATH%;B:\write\builds\py39usd2105build\bin;B:\write\builds\py39usd2105build\lib
(py39usd2105build) C:\Users\Christian>usdview B:\read\cg\downloads\Kitchen_set\Kitchen_set\Kitchen_set.usd
```

![usdview](https://user-images.githubusercontent.com/8294116/115984418-557b3400-a5ea-11eb-9637-63ec577b9bd8.PNG)

**Comment by chrizzFTD** [comment]
Closing as the [21.08 release added support](https://github.com/PixarAnimationStudios/USD/blob/00643360a6ab66c764eec8b9e8b0de3de40e0c78/CHANGELOG.md#build) for 3.8+ on all platforms, thanks!
