### ISSUE TITLE
Recent USD build and Houdini USD

### ISSUE THREAD

**Issue by ChokmahBinah** [PixarAnimationStudios/USD#1265]
### Description of Issue
Hello Pixar USD users :)

Here it's more about a question.

I'd like to test recent USD releases with Houdini 18.5 USD. 
The fact is that when I set my environment variables USD works fine but Houdini USD no work anymore.

If I remove environment variables Houdini USD works fine again.

Is there a way to make the two works together ?

(Sorry I still am a noob at this kind of things ^^)

Thanks in advance.

Florian.

**Comment by marktucker** [comment]
This question probably belongs on the SideFX forum, or maybe usd-interest, not here... But the basic answer is that you can't just build USD and run Houdini with that USD build in your path. Houdini ships with it's own USD libraries, and there will definitely be conflicts between the two sets of libraries and plugins. It is in theory possible to replace the USD library that ships with Houdini (using https://github.com/sideeffects/HoudiniUsdBridge) but that's a very advanced topic, intended only for large studios with the development resources to support the kind of major surgery required to get all the pieces building and working together.

**Comment by ChokmahBinah** [comment]
Okay I'll go ask my question on SideFX forum then :)

Thanks you for the explanations ;)

Cordially.

**Comment by hshakula** [comment]
Don't pollute the global environment with USD's PATH and PYTHONPATH.
Write a simple wrapper script that will set those variables in the environment local to the running process.

If you have no idea how to do it, let me know what's your platform.

**Comment by ChokmahBinah** [comment]
Hello @hshakula ,

Thank you a lot for your help. It's seems really interesting. :D

I am on Windows 10 2004.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6220.

**Comment by hshakula** [comment]
Create .cmd file in the root of your USD installation (%USD_ROOT%) with such content:
```
@echo off

pushd %~dp0
set USD_INSTALL_ROOT=%CD%
popd

setlocal

set PYTHONPATH=%USD_INSTALL_ROOT%\lib\python;%PYTHONPATH%
set PATH=%USD_INSTALL_ROOT%\bin;%USD_INSTALL_ROOT%\lib;%PATH%
set PATH=C:\Python36;C:\Python36\Scripts;%PATH%

%*

endlocal
```

When you had USD env variable entries set in the global environment you were able to run usdview as-is: `usdview args...`.
Now you just need to prepend the path to this file to such commands so to run usdview you will do:
`%USD_ROOT%\usd.cmd usdview args...`

Note about python: edit this line `set PATH=C:\Python36;C:\Python36\Scripts;%PATH%` so that it matches to python you need or remove this line at all if you have only one python install and it's already in PATH

**Comment by ChokmahBinah** [comment]
Thank you a lot @hshakula ,

I'll try this a soon as possible :)

**Comment by ChokmahBinah** [comment]
Your script works like a charm @hshakula  ;)

Thank you a lot :)

**Comment by c64kernal** [comment]
Thanks for the help everyone, closing this one. Wrapper scripts that set env vars are how we handle this as well.
