### ISSUE TITLE
Storm pre-multiplies texture alpha into RGB, which is incorrect for many textures

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#1269]
### Description of Issue
When loading textures into Storm for PreviewSurface, the alpha channel is pre-multiplied into the other color channels.

This is a problem when the color channels are actually shading data. For example, we export a single mask texture with R=Metallic, G=AO, B=Detail, A=Roughness, but when roughness (A) goes to zero, it takes all other channels to zero also.

It's hard to confirm, but this appears to be the case in usdview 20.08.

Comment from @poljere:

> In Storm, we premultiply all four channel textures regardless of how they will be used, which is not a perfect solution (as you saw). This trick let us generate mips with premultiplied alpha, and use them for lighting, which is good for the color/opacity case, but bad for other cases. 

### Steps to Reproduce
1.  See this USDZ file, which has a texture described as above

https://drive.google.com/file/d/12XkePimchIhiz7Q50OyiwYGGtPB3ZfDz/view?usp=sharing

See how the image below changes just by adding the alpha channel for roughness:

![image](https://user-images.githubusercontent.com/1510114/87835469-1097c500-c842-11ea-8b11-250560a95faa.png)

### System Information (OS, Hardware)
Windows 10
GTX 1080Ti

### Package Versions
USD 20.08-rc3

### Build Flags
python build_scripts\build_usd.py --build-monolithic --openimageio --alembic ..\_build-monolithic-py\

**Comment by sunyab** [comment]
Filed as internal issue #USD-6223
