### ISSUE TITLE
TfHashMap/Set version check incorrect, at least for clang

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#127]
On clang we want to use the std::unordered_map version of TfHashMap and TfHashSet:

The failing version check reads as follows:

````
#elif __cplusplus > 201103L
// Use C++11 unordered_map.
#include <unordered_map>
````

But should read:
````
#elif __cplusplus >= 201103L
// Use C++11 unordered_map.
#include <unordered_map>
````
I am guessing that this test would hold true on other compilers...?

**Comment by jtran56** [comment]
Filed as internal issue #141456.
