### ISSUE TITLE
Error building usdAbc with PXR_ENABLE_HDF5_SUPPORT=OFF

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1273]
### Description of Issue

I get an error when I try to use usdAbc.so if I've built with `PXR_ENABLE_HDF5_SUPPORT=OFF`. 
Specifically, I see:

```
usdAbc.so: undefined symbol: H5T_STD_U16LE_g
```

(Note that I haven't yet confirmed that this goes away with `PXR_ENABLE_HDF5_SUPPORT=ON`, but I believe the named symbol comes from hdf5.)

### Steps to Reproduce
1. Build v20.08 with `PXR_ENABLE_HDF5_SUPPORT=OFF`, then run any of the usdAbc tests (or just import the `UsdAbc` python module)

### System Information (OS, Hardware)

CentOS 7.7

### Package Versions

usd-20.08
alembic

### Build Flags

-DPXR_ENABLE_HDF5_SUPPORT=OFF

**Comment by jtran56** [comment]
Filed as internal issue #USD-6239

**Comment by pmolodo** [comment]
Ooops - this was actually because I was linking against a newer version of alembic, that was built in a slightly different way.

My alembic 1.5.8, which I had been using previously, consisted of multiple static libraries, ie:

- libAlembicAbc.a
- libAlembicCoreHDF5.a
- libAlembicCoreOgawa.a
- ...etc

My new alembic 1.7.11 consists of only a single static library:

- libAlembic.a

Not sure if this is change in the way alembic itself is built, or if I changed some build options between the two options. Regardless, not your folks problem - just documenting what I found in case others stumble into the same thing...
