### ISSUE TITLE
Test errors when using PXR_OVERRIDE_PLUGINPATH_NAME 

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1274]
### Description of Issue

If you set a custom `PXR_PLUGINPATH_NAME`, then 3 tests fail (ones that are apparently using a custom asset resolver).  
Presumably something in these tests is hardcoding the use of `PXR_PLUGINPATH_NAME` to add this plugin.

### Steps to Reproduce

1.  Build with `-DPXR_OVERRIDE_PLUGINPATH_NAME=MY_PXR_PLUGINPATH`
2. Run tests for any of:
    - testUsdDancingCubesExample
    - testUsdRecursivePayloadsExample
    - testHdTiny

The first two will fail will similar looking errors - basically, it can't get the file type for what looks like an un-resolved path. ie, here's the error for testUsdDancingCubesExample:

```
Warning: in _ReportErrors at line 2815 of /lumalocal/rez-build/usd/0.20.08/src/pxr/usd/usd/stage.cpp -- Could not open asset @/tmp/tmp2dTFV7/empty.usddancingcubesexample@ for payload on prim @test.usda@,@anon:0x17bdfe0:test-session.usda@</Root> -- Cannot determine file format for @/tmp/tmp2dTFV7/empty.usddancingcubesexample:SDF_FORMAT_ARGS:target=usd@. (instantiating stage on stage @test.usda@ <0x17bf4b0>)
Traceback (most recent call last):
  File "/luma/dev/paulm/rez-release/usd/0.20.08/platform-linux/gcc-6.3/tests/testUsdDancingCubesExample", line 38, in <module>
    assert dynamicFormat
AssertionError
Error: return code 1 doesn't match expected 0 (EXPECTED_RETURN_CODE).
```

the `testHdTiny` errors with something in _DiscoverPlugins, so I suspect it's related as well:

```
Warning: in _DiscoverPlugins at line 202 of /lumalocal/rez-build/usd/0.20.08/src/pxr/imaging/hf/pluginRegistry.cpp -- Plugin HdTinyRendererPlugin type information incomplete
```

### System Information (OS, Hardware)

CentOS 7.7

### Package Versions

usd-20.08

### Build Flags

`-DPXR_OVERRIDE_PLUGINPATH_NAME=MY_PXR_PLUGINPATH`

**Comment by pmolodo** [comment]
Submitted a PR that fixes this: https://github.com/PixarAnimationStudios/USD/pull/1275

**Comment by jtran56** [comment]
Filed as internal issue #USD-6245
