### ISSUE TITLE
Turning off the  visibility of a light does not disable the light it casts into the scene in usdview

### ISSUE THREAD

**Issue by koen-v** [PixarAnimationStudios/USD#1277]
When hiding a light I would expect the light to not cast light into the scene anymore. However, testing this in the current usd view, the lights still contribute.

Please see the attached usda and toggle the light visibility in the scene tree, please note how this does not affect the 3d viewer. ( Deactivating the light does work.

Thanks,
Koen

[light.zip](https://github.com/PixarAnimationStudios/USD/files/4995882/light.zip)

**Comment by jtran56** [comment]
Filed as internal issue #USD-6255
