### ISSUE TITLE
Unnecessary python includes in sdf/spec.cpp

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#128]
These Python related includes are unneeded, and can be removed from sdf/spec.cpp bringing us one step closer to a clean Pythonic separation from the C++ portions of the libraries.

````
#include "pxr/base/tf/pyError.h"
#include <boost/python/extract.hpp>
#include <boost/python/object.hpp>
````

**Comment by jtran56** [comment]
Filed as internal issue #141457.
