### ISSUE TITLE
'Layer path is empty' error in UsdUtilsComputeAllDependencies

### ISSUE THREAD

**Issue by timthehoff** [PixarAnimationStudios/USD#1288]
### Description of Issue
ComputeAllDependencies throws an error if it encounters a Value Clip definition with an invalid templateAssetPath.

This happens when the file analyzer tries to find the directory of the template path to glob for files. If this directory is empty, the error isn't caught and an error is raised:

> ErrorException:  Error in 'pxrInternal_v0_19__pxrReserved__::SdfComputeAssetPathRelativeToLayer' at line 92 in file /bluesky/design/users/ricardocat/dev/USDpackage/build/base_platform-bss.2018.3/RenderManProServer-23.3_2069290/USD-prefix/src/USD/pxr/usd/lib/sdf/layerUtils.cpp : 'Layer path is empty'

I'm going to be submitting a PR with a fix.

### Steps to Reproduce
```
from pxr import Usd, UsdUtils
stage = Usd.Stage.CreateNew('/tmp/clipError.usda')
prim = stage.DefinePrim('/clip')
Usd.ClipsAPI(prim).SetClipTemplateAssetPath(' ')
stage.GetRootLayer().Save()
UsdUtils.ComputeAllDependencies(stage.GetRootLayer().identifier)
```

**Comment by jtran56** [comment]
Filed as internal issue #USD-6282
