### ISSUE TITLE
USD versioning tags

### ISSUE THREAD

**Issue by frenchdog** [PixarAnimationStudios/USD#13]
Hi,

I heard that the current version was 0.7, but I'm not sure if it is possible to get this specific version 
easily as there is no release point tags in the USD git repo. 

It would be great to get such version tags before we get to many commits.

Thanks

**Comment by sunyab** [comment]
Hi @frenchdog, perfect timing -- we added the v0.7.0 release tag just last night. Closing this out, thanks for filing!

**Comment by frenchdog** [comment]
:+1: thanks!
