### ISSUE TITLE
Slow transform manipulation performance for heavy mesh

### ISSUE THREAD

**Issue by huidong-chen** [PixarAnimationStudios/USD#1300]
### Description of Issue
Transform manipulation performance for heavy mesh is extremely slow.

We see this issue in Maya with both VP2RenderDelegate and HdStorm-based ALDrawOverride, 99% of the main-thread time is spent in USD reading from crate file and decompressing large primvar data buffer.

Initial discussion on this issue can be found at usd-interest forum:

https://groups.google.com/g/usd-interest/c/697eATsMcJM

### Steps to Reproduce
1. Load asset in Maya with maya-usd plugin loaded. Or load in USDView if you have a way to manipulate transform.
2. Manipulate the transformation 
3. Frame rate is ~0.5fps.
4. If I short-circuit the UsdImagingMeshAdapter::TrackVariability() function body, manipulation frame rate will be 27fps.

**Comment by huidong-chen** [comment]
Please contact me if you need the heavy mesh which we used to reproduce https://github.com/Autodesk/maya-usd/issues/566

**Comment by jtran56** [comment]
Filed as internal issue #USD-6304

**Comment by Xaia** [comment]
Hi, I was asked by @HdC-adsk to reupload the heavy mesh asset. You can download it here: https://we.tl/t-d3BmmUbC4r (link expires in 1 week (8th of September).

**Comment by gitamohr** [comment]
Thanks HdC-adsk for the excellent report, and thanks Xaia for sharing the asset!  I have checked in a fix for the performance bug in the USD core internally.  Without the fix, translating this asset takes ~1600 msec to redraw in usdview on my machine.  With the fix, it takes ~130 msec.
