### ISSUE TITLE
Cannot load 19.07 maya plugin in Maya2017

### ISSUE THREAD

**Issue by JerryKon** [PixarAnimationStudios/USD#1301]
### Description of Issue
Following error occured when loading maya plugin.

: (kFailure): Unexpected Internal Failure
Stack trace:
  KERNELBASE.dll!DebugBreak
  libarch.dll!pxrInternal_v0_19__pxrReserved__::ArchDebuggerAttach
  libarch.dll!pxrInternal_v0_19__pxrReserved__::ArchLogPostMortem
  libtf.dll!pxrInternal_v0_19__pxrReserved__::TfLogCrash
  libtf.dll!pxrInternal_v0_19__pxrReserved__::TfDiagnosticMgr::PostFatal
  libtf.dll!pxrInternal_v0_19__pxrReserved__::Tf_DiagnosticHelper::IssueFatalError
  libtf.dll!pxrInternal_v0_19__pxrReserved__::TfScriptModuleLoader::GetInstance
  libtf.dll!pxrInternal_v0_19__pxrReserved__::Tf_NoticeRegistry::_Send
  libtf.dll!pxrInternal_v0_19__pxrReserved__::TfNotice::Send
  libtf.dll!pxrInternal_v0_19__pxrReserved__::Tf_PyInitWrapModule
  _usdMaya.pyd!pxrInternal_v0_19__pxrReserved__::init_module_usdMaya
  boost_python-vc141-mt-1_65_1.dll!boost::python::handle_exception_impl
  boost_python-vc141-mt-1_65_1.dll!boost::python::detail::init_module
  python27.dll!PyImport_AppendInittab
  python27.dll!PyImport_ImportModuleLevel
  python27.dll!PyImport_ImportModuleLevel
  python27.dll!PyImport_ImportModuleNoBlock
  python27.dll!PyImport_ImportModuleLevel
  python27.dll!PyAST_FromNode
  python27.dll!PyCFunction_Call
  python27.dll!PyObject_Call
  python27.dll!PyEval_CallObjectWithKeywords
  python27.dll!PyEval_EvalFrameEx
  python27.dll!PyEval_EvalCodeEx
  python27.dll!PyImport_ExecCodeModuleEx
  python27.dll!PyImport_ExecCodeModuleEx
  python27.dll!PyImport_ExecCodeModuleEx
  python27.dll!PyImport_ImportModuleLevel
  python27.dll!PyImport_ImportModuleLevel
  python27.dll!PyImport_ImportModuleNoBlock
  python27.dll!PyImport_ImportModuleLevel
  python27.dll!PyAST_FromNode
  python27.dll!PyCFunction_Call
  python27.dll!PyObject_Call
  python27.dll!PyEval_CallObjectWithKeywords
  python27.dll!PyEval_EvalFrameEx
  python27.dll!PyEval_EvalCodeEx
  python27.dll!PyEval_EvalCode
  CommandEngine.dll!TpythonInterpreter::executeCommand
  OpenMaya.dll!MGlobal::executePythonCommand

### Steps to Reproduce
1. 

### System Information (OS, Hardware)
Windows10, visual studio 2019
### Package Versions
19.07
### Build Flags
python ..\USD-19.07\build_scripts\build_usd.py -v ^
        --alembic --hdf5 ^
        --maya --maya-location %maya% ^
        --src %src_install% ^
        --build %build_install% ^
        --generator "Visual Studio 16 2019" ^
        %install%

**Comment by meshula** [comment]
Hi there, I see you built with VS2019. The Maya plugin has very specific build requirements on Visual Studio version. The details are here - https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md

**Comment by jtran56** [comment]
Filed as internal issue #USD-6305

**Comment by c64kernal** [comment]
Apologies, but we're no longer supporting this version of the plugin. Please consider using a newer version of USD and the Autodesk plugin that @meshula pointed to.
