### ISSUE TITLE
UsdPreviewSurface clearcoat in RenderMan expected behavior?

### ISSUE THREAD

**Issue by drwave** [PixarAnimationStudios/USD#1307]
### Steps to Reproduce
1. in usdview or Houdini 18, load this asset. In Storm, or HoudiniGL, or Karma or Octane it looks as expected, but rendered with RenderMan it is super over bright. If you disconnect the clearcoat or set it to 0.0, it looks fine in RenderMan.

### System Information (OS, Hardware)
macOS 10.15 and 11 beta

### Package Versions
Houdini 18.0.499 and usdview (branch of current dev branch)

![Drummer_Octane](https://user-images.githubusercontent.com/1679418/91623778-b9f9cc80-e951-11ea-8645-a0c533579aee.jpg)
![Drummer_RenderMan](https://user-images.githubusercontent.com/1679418/91623779-bb2af980-e951-11ea-889d-41929f9d7364.jpg)
![Drummer_Karma](https://user-images.githubusercontent.com/1679418/91623780-bbc39000-e951-11ea-9478-a0f85c85308f.jpg)
![Drummer_HoudiniGL](https://user-images.githubusercontent.com/1679418/91623781-bc5c2680-e951-11ea-8375-de869b550229.jpg)

[toy_drummer.usdz.zip](https://github.com/PixarAnimationStudios/USD/files/5144540/toy_drummer.usdz.zip)

**Comment by drwave** [comment]
Here's a simpler example that still shows the blown out behavior in RenderMan:

[ClearCoatRangeSpheres.usda.zip](https://github.com/PixarAnimationStudios/USD/files/5146167/ClearCoatRangeSpheres.usda.zip)

**Comment by jtran56** [comment]
Filed as internal issue #USD-6318
