### ISSUE TITLE
Storm BasisCurves interpolate varying primvars incorrectly

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1308]
### Description of Issue
Varying primvars (displayColor at least) are not interpolated correctly. Widths do seem to be interpolated correctly

### Steps to Reproduce
Attached rdla file should render six very similar cone shapes using basisCurves, assuming I understand the interpolation correctly. Instead the colors don't match, even though the widths (using the same interpolation as the colors) do seem to match.

### System Information (OS, Hardware)
Linux

### Package Versions
20.05

![curvesVarying](https://user-images.githubusercontent.com/1229073/91776737-e5bfc100-eba2-11ea-8c84-864ea5c5fc1f.png)
[curvesVarying.zip](https://github.com/PixarAnimationStudios/USD/files/5153009/curvesVarying.zip)

**Comment by spitzak** [comment]
Above image is with complexity=Very High. Setting complexity=Low will also undesirable artifacts.

**Comment by drwave** [comment]
RenderMan doesn’t like “linearVarying” and “bezierVarying”:

For linearVarying it complains thusly:

third_party/renderman-23/plugin/hdPrman/context.cpp -- </linearVarying> primvar 'displayColor' size (3) did not match expected (2)
third_party/renderman-23/plugin/hdPrman/context.cpp -- </linearVarying> primvar 'widths' size (3) did not match expected (2)

And for “bezierVarying” it says:

third_party/renderman-23/plugin/hdPrman/context.cpp -- </bezierVarying> primvar 'displayColor' size (3) did not match expected (5)
third_party/renderman-23/plugin/hdPrman/context.cpp -- </bezierVarying> primvar 'widths' size (3) did not match expected (5)

**Comment by jtran56** [comment]
Filed as internal issue #USD-6319
