### ISSUE TITLE
hdPrman erroring with exr textures in UsdPreviewSurface network

### ISSUE THREAD

**Issue by kenmcgaugh** [PixarAnimationStudios/USD#1313]
### Description of Issue
Using a UsdPreviewSurface network with exr textures (via UsdUVTexture) render fine in Storm, but throw an "unsupported data type" error in hdPrman.

### Steps to Reproduce
1.  Download and unzip repro:
[hdPrman_exr_bug.zip](https://github.com/PixarAnimationStudios/USD/files/5181073/hdPrman_exr_bug.zip)
2. Load hdPrman_exr_bug.usda into usdview and note how the geo is textured in Storm. Switch to Prman render delegate and notice the geo no longer renders textured and error message is printed.
3. Load hdPrman_exr_bug_works.usda into usdview. This version uses an 8-bit png texture instead of 16-bit half exr texture and works both in Storm and Prman.

### System Information (OS, Hardware)
Linux Ubuntu-18.04

### Package Versions
usd-20.08

**Comment by jtran56** [comment]
Filed as internal issue #USD-6328
