### ISSUE TITLE
Add BlockVariantSelection to VariantSets

### ISSUE THREAD

**Issue by chrisrydalch** [PixarAnimationStudios/USD#1319]
There is currently no API to set a VariantSet's Selection to be an empty string, in order to effectively block weaker variant selections. Both SetVariantSelection() and ClearVariantSelection() usd the same Sdf APIs, which interpret an empty string as nothing, and don't author any specs into the layer.

After a discussion on [usd-interest](https://groups.google.com/g/usd-interest/c/F96G1S8AWUA), adding a request for a BlockVariantSelection() method.

Thanks!

**Comment by jtran56** [comment]
Filed as internal issue #USD-6336

**Comment by chrisrydalch** [comment]
![screenshot-area-2020-09-10-004635](https://user-images.githubusercontent.com/37886383/93689088-312a0880-fa99-11ea-80be-cb514931c5f1.png)

BTW, we'll have a PR for this, probably some time this coming week. 

Thanks!

**Comment by sunyab** [comment]
PR #1340 was merged in commit fff84622 in the dev branch, marking as pending release.

**Comment by tallytalwar** [comment]
Thanks, this was included in the 21.02 release.
