### ISSUE TITLE
Custom attributes [discussion]

### ISSUE THREAD

**Issue by BSalem** [PixarAnimationStudios/USD#132]
Hi all,
I modified the maya usdImport and Katana PxrUsdIn in regards to the custom attributes that were written inside a USD, and I wish if we can be on the same page before I finalize it and submit a pull request, wishing to have it compatible what you might have planned on the same thing for the future.

My implementation is as follows:
A: Maya:
   1. Any custom attributes under "userProperties" or "arbGeomParams" names spaces will be created in maya on the primitive shape node.
   2. Any custom attributes under "userXfProperties" will be created in maya on the primitive transform node.
(currently, only static attrs are supported).

B: Katana:
    1. PxrUsdIn will respect and auto create the attributes found under 'userXfProperties' the same way it does when finding 'userProperties'.
    2. I added 'arbGeomParams' to be respected and behave the same way of userProperties (this is not important since userProperties already does what we need).

Please let me know what do you think, and if this implementation makes sense for you.

On the other side, please advise on which source file of usdMaya I should put my addUserProperties function on... currently, I injected my function into the "usdMaya/translatorUtil.h".

Kind Regards,
Belal

**Comment by spiffmon** [comment]
Hi Belal!
    Sounds like there are two issues you're addressing: user properties, and primvars.

For user properties and how to segregate them with respect to Maya's xform/shape split, if it's not realistic to apply a simple rule like "all userProperties (**not** primvars) get applied to the xform parent of the shape", then I think a more "USD-ish" approach might be to add customData on **Maya export** that identifies whether Maya should reimport the attribute to the xform or to the shape (if most attributes go to one or the other, a default might be handy).  The reason an approach like this might be preferable is that this is really (from a USD perspective, at least) a peculiarity of Maya, that we'd rather not inflict on the rest of the pipeline.  Katana is flexible enough that we are able to add transforms directly onto the gprims we import, so the USD data model can be reflected perfectly.

A pattern we've used in some other internal plugins that may be interesting is to carve out a "Maya" sub-dictionary in customData, which can then contain any named, Maya-specific fields we want to add in the future.  Using the [UsdObject customData API's](http://graphics.pixar.com/usd/docs/api/class_usd_object.html#a0684efa005e63f61e00d53da957bfc43), you could, for example, do something like:
```
attr = prim.CreateAttribute(TfToken("userProperties:myAttr", SdfValueTypeNames->Float);
attr.SetCustomDataByKey(TfToken("maya:importToShape"), VtValue(true));
```

For primvars, our hope has been that we can address alembic-isms on Maya export, only.  For example, our usdAbc alembic FileFormat translator automatically converts alembic .arbGeom into [UsdGeomPrimvar](http://graphics.pixar.com/usd/docs/api/class_usd_geom_primvar.html) properties, which all out plugins already know how to import and export.

My apologies that we have been slow to follow up on making the alembicChaser provide full support for honoring existing alembic tagging in Maya files. Would you be interested in helping to flesh out the chaser more?

**Comment by BSalem** [comment]
Hi, 
Thanks for the detailed information, this was greatly helpful in that I can follow your same rules so the compatibility don't break up when you do any future updates.
besides that, the SetCustomDataByKey to inform future import targets to shape is a cool method that I didn't know about.. this what I was trying to workaround by only the namespace which is not efficient as your method.
In regards to Alembic chaser, I built my staff to use my custom alembic for alembics and usd for usds, I didn't test it or work with it yet, but I will concentrate in implementing it in my staff here benefit from the usd functionalities that I'm losing them if depended on my alembic plugin only.

**Comment by jtran56** [comment]
Filed as internal issue #141500.

**Comment by spiffmon** [comment]
Sounds good, Belal!  Closing, as it sounds like you have what you need?
