### ISSUE TITLE
UDIM resolution broken for symlinks to non-UDIM paths

### ISSUE THREAD

**Issue by marsupial** [PixarAnimationStudios/USD#1329]
### Description of Issue
New[ish] code to share UDIM textures when they are symlinks breaks down if they are symlinks to non-UDIM textures.
_ResolveAssetAttribute in pxr/usdImaging/materialParamUtils.cpp attempts to deduce the following:
```
/symlink/a_<UDIM>.exr => /realpath/realfile_1001.exr
/symlink/b_<UDIM>.exr => /realpath/realfile_1001.exr
```
This seems to allow sharing a common key for **/symlink/a_<UDIM>.exr**  and **/symlink/b_<UDIM>.exr**, but will break down when the symlinks point to a file that is not a UDIM tile (i.e. **/realpath/realfile_some_other_convention.exr**)

It occurs to me that this may actually be fundamentally flawed and even the solution in #1330 may be insufficient, given that there could be two UDIM paths that resolve to the same first-tile, but diverge on subsequent tiles:
```
/symlink/a_1001.exr => /realpath/realfile_1001.exr
/symlink/a_1002.exr => /realpath/another_1002.exr

/symlink/b_1001.exr => /realpath/realfile_1001.exr
/symlink/b_1002.exr => /realpath/totallydifferent_1002.exr
```
I think any resolution/transformation via symlinks in this case would make **/realpath/realfile_1001.exr** the key, for both **a_\<UDIM\>.exr** and **b_\<UDIM\>.exr** which would give incorrect results.

**Comment by spitzak** [comment]
Changing the paths also makes error messages hard for users to figure out.
It would be better if the code that actually read the image did the readlink calls and determines if the image is one it has already loaded and if so reuse it.

**Comment by marsupial** [comment]
I'm leaning towards @spitzak's conclusion too...all of this magic seems better suited at the ArResolver level or in the render itself.

Should #1330 be closed or changes to just remove the symlink resolution?

**Comment by jtran56** [comment]
Filed as internal issue #USD-6351

**Comment by sunyab** [comment]
I spent a little bit of time looking at this and I agree with you both. I've made a change internally that just removes the symlink processing, so the UDIM pattern matching is done on the authored paths and not the paths of the symlinked files. This should go out in the next push. Thanks!
