### ISSUE TITLE
maya plugin: Add ability to export nParticles to UsdGeomPoint

### ISSUE THREAD

**Issue by chadrik** [PixarAnimationStudios/USD#133]
As an FX artist using Maya I would like to be able to export nParticles as USD for consumption by downstream departments.

Maya's Nucleus dynamics system can be extended to support additional cache formats via [MPxCacheFormat](http://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__cpp_ref_class_m_px_cache_format_html).  Adding a new cache format provides a new drop-down option when configuring the cache settings in Maya.  I think this would make a good addition to the current Maya plugin.

In addition to the `MPxCacheFormat` which will allow authoring .usd files during simulation, we might want to add support for exporting particle nodes to the USD `MPxFileTranslator`.  There will likely be some caveats to this, such as only exporting particles which have been previously cached to .usd, which would likely mean we'll want to create a reference to the cache file instead of embedding the data in the export.  We can flesh out those details when we get further along.  

Luma is planning to implement this feature, so there's no work required on your part, I just wanted to get approval on the addition of this to the usdMaya plugin, and to check to make sure this doesn't overlap with other ideas that you all have brewing.  For example, it might be a good lead-in to the PointInstancer schema that you're developing.

**Comment by spiffmon** [comment]
Exporting nParticles as UsdGeomPoints or UsdGeomPointInstancer (it's live in 0.7.2 - [check it out!](https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usdGeom/pointInstancer.h), there are still API niceties on the way for consumers, and Katana support isn't there yet, but Hydra support is) sounds great.  We don't do much sim in Maya anymore, but we do think that makes alot of sense.  We've just started thinking about what features/packages in Maya would want to export into PointInstancers... we think that we may want to add our own internal Maya plugin-node to the OSS plugin for how to represent a UsdGeomPointInstancer on **import**.  It sounds like nParticles has some support for object instancing, and PointInstancer would definitely be the way to go there.  Let's keep this dialog going!

I took a quick look at MpxCacheFormat, and it looks super-duper low-level, not even supporting named data collections of any sort.  What does it buy you to add USD as an MpxCacheFormat?  Or is that the only way to export nParticles, and you can infer how the various arrays your plugin is given should map to points and primvars on a UsdGeomPoints prim? 

Do nParticles ever live inside a DAG as part of a larger scene you'd be exporting?

**Comment by chadrik** [comment]
> I took a quick look at MpxCacheFormat, and it looks super-duper low-level, not even supporting named data collections of any sort.

It's there but it's easy to miss if you're just skimming. There is a separate object called [MCacheFormatDescription](http://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__cpp_ref_class_m_cache_format_description_html) that holds all that info.

> is [MpxCacheFormat] the only way to export nParticles...?

I believe it is also be possible to use [MFnParticleSystem](http://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__cpp_ref_class_m_fn_particle_system_html) to query a particle node (and thus indirectly its cache), but I think in practice this is not what you'd want to do.  Here are a few reasons why:

- Maya's native cache format is not actually all that great, so I think there's a good chance using USD as a cache format will be an improvement.  
- Re-exporting a sim that's already cached wastes disk space. 
- Re-exporting a sim that's already cached wastes time:  exporting a scene containing cached particle nodes should be very quick, since we just make add a reference to the existing cache.

The one advantage that I can think of to using `MFnParticleSystem` is that you could export a particle system that hasn't been cached or one that's been cached to a different format. If it's a feature that people want, it could be reasonable to add support for this to the export routine -- specifically detecting uncached particle systems or foreign caches and falling back to `MFnParticleSystem` -- but it's not a feature that is particularly interesting to me.

> Do nParticles ever live inside a DAG as part of a larger scene you'd be exporting?

Yes.

**Comment by jtran56** [comment]
Filed as internal issue #141501.

**Comment by sunyab** [comment]
Cleaning up old issues, the Maya plugin has long been retired in favor of Autodesk's [maya-usd](https://github.com/Autodesk/maya-usd)
