### ISSUE TITLE
Question : Impossible to load usd file, what did I do wrong?

### ISSUE THREAD

**Issue by devGitHub48** [PixarAnimationStudios/USD#1332]
### Description of Issue
I have this issue when I try to load a simple asset

`_OpenLayerAndUnlockRegistry at line 3019 of E:\github\usd\USD\pxr\usd\sdf\layer.cpp -- Cannot determine file format for @usd\test.usda:SDF_FORMAT_ARGS:target=usd@`

Here is my file
```
#usda 1.0

def Cube "Box"
{
    float3 xformOp:scale = (5, 5, 5)
    uniform token[] xformOpOrder = ["xformOp:scale"] 
}
```

### Steps to Reproduce
1. Add usd 20.05 to our game engine
2. try to load a simple asset

### System Information (OS, Hardware)
Windows 10
Visual 2017

### Package Versions
v20.05

### Build Flags
USD\build_scripts\build_usd.py --force-all --verbose --alembic --debug --build-args=boost,"--with-date_time --with-thread --with-system --with-filesystem"

**Comment by asluk** [comment]
Likely your usd plugin paths are not set up properly. The usd binaries are ideally copied to wherever you are installing them with their original file hierarchy intact.

You can diagnose what plugins usd is discovering by setting the env var TF_DEBUG to PLUG_*

**Comment by devGitHub48** [comment]
Oh damn, I forgot to copy them.
I'll try that and let you know!

Thanks

**Comment by jtran56** [comment]
Filed as internal issue #USD-6354

**Comment by devGitHub48** [comment]
I should still do something wrong :(

I added the plugin folder as explained (same file hierarchy)

```
    std::string pluginPath = std::string("pathtomyproject\\x64\\Release\\plugin\\usd");
    auto plugins = PlugRegistry::GetInstance().RegisterPlugins(pluginPath);
    std::string temp(m_filePath.ToCString());
    m_supported = UsdStage::IsSupportedFile(temp);

    if (!m_supported)
```

`m_supported` is false
I have 4 loaded plugins which seems ok.

I know I should miss something :(

**Comment by asluk** [comment]
I would suggest setting the env var TF_DEBUG to PLUG_* , and then running usdview on one of the usd or usda files in the tutorials.

If that works, compare the TfDebug output to that of your game engine to see what's different. Good luck!

**Comment by devGitHub48** [comment]
Thanks @asluk 
Will do this this afternoon

**Comment by devGitHub48** [comment]
Ok!
So our engine was pointing to the external code
And was missing the lib folder.

Now it gets all the plugins!
Thanks

Last question
Can we set up our own allocator?

**Comment by devGitHub48** [comment]
Sorry, let me clarify the question :
Could I change the allocator but not at compil time?

**Comment by sunyab** [comment]
Hi @devGitHub48, we don't have the ability to change allocators at runtime built into USD itself.

**Comment by devGitHub48** [comment]
Thanks @sunyab !

**Comment by sunyab** [comment]
No problem, I'm going to close this issue out. Thanks @asluk for the support!

**Comment by devGitHub48** [comment]
Yep !
Thanks @asluk and @sunyab
