### ISSUE TITLE
Windows 10 Nvidia binaries DLL load failed

### ISSUE THREAD

**Issue by ollied-xx** [PixarAnimationStudios/USD#1334]
### Description of Issue
Not sure if its a aproprate to post here about using the binaries supplied by nvidia but thought I would give it a shot.  I am giving these binaires a try to see if I can get USD up and running on windows without needing to fully build it myself.  After installing py27 version.  Setting PATH and PYTHONPATH to the desired values and installing PySide2 and PyOpenGL, I am getting the following erroring when trying out usdcat.

From what I can tell, this should be working.  Wanted to check to see if there is something I am missing?

`Traceback (most recent call last):
  File "E:\downloads\usd-20-08-win64_py27_release\bin\usdcat", line 241, in <module>
    sys.exit(main())
  File "E:\downloads\usd-20-08-win64_py27_release\bin\usdcat", line 165, in main
    from pxr import Usd
  File "E:\downloads\usd-20-08-win64_py27_release\lib\python\pxr\Usd\__init__.py", line 24, in <module>
    from . import _usd
ImportError: DLL load failed: The specified module could not be found.`

### Steps to Reproduce
1. Download USD 20.08, Python 2.7 from https://developer.nvidia.com/usd#bin
2. Add %USDROOT%\bin and %USDROOT%\lib to the front of %PATH%
3. Add %USDROOT%\lib\python to the front of %PYTHONPATH%
4. Install PySide and PyOpenGL to python

### System Information (OS, Hardware)
Windows 10
Python 2.7.18
PySide 1.2.4

**Comment by asluk** [comment]
Try installing Microsoft Visual C++ Redistributable for Visual Studio 2017 x64 from https://visualstudio.microsoft.com/vs/older-downloads/ under “Redistributables and Build Tools“, and then running usdcat again.

**Comment by ollied-xx** [comment]
Thanks @asluk.  Have given that a try.  No luck unfortunately.

**Comment by asluk** [comment]
Hmm. Does  “Redistributables and Build Tools“ include dumpbin ? If so you can 

dumpbin /dependents _usd.pyd

and try to see what DLLs it is trying to load (though you might need to dumpbin on those as well).

Apologies; I don't know of another way in Windows to get specifically at exactly which DLL it can't find.

**Comment by ollied-xx** [comment]
Thanks @asluk.  I tracked down dumpbin and gave that a try.  Produced the following.

`E:\downloads\usd-20-08-win64_py27_release\bin>dumpbin /dependents _usd.pyd
Microsoft (R) COFF/PE Dumper Version 14.27.29111.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file _usd.pyd
LINK : fatal error LNK1181: cannot open input file '_usd.pyd'`

Which did not tell me much.  Trying a different dependency trawler, it appears to look as if everything is correct.

![image](https://user-images.githubusercontent.com/3763817/93970078-8e88b880-fd2a-11ea-8173-6dd71b8a9dc7.png)

Not too sure where to go from here?  Feels like heading down a bit of a rabbit hole with this one.  No dramas if there is no clear next steps from here.  I'll change tack and maybe look at building from scratch.

**Comment by asluk** [comment]
Apologies if you’ve already tried it, but can you run dumpbin and/or your other trawler on E:\downloads\usd-20-08-win64_py27_release\lib\python\pxr\Usd\_usd.pyd ? I’m not at a PC right now, so I can’t remember the exact location or run dumpbin on my own binaries to compare at the moment.

The dump from usd.dll looks good from what you posted, so it looks like something is specifically going wrong with the python bindings. I think there’s another tool in the usd bin folder called sdfdump or something that is C++ only; running that on a usd or usda file might give more info as to whether your issue is python specific.

Thanks for your patience!
-a.

**Comment by ollied-xx** [comment]
Thanks for the info.  That gives me the following information.

`E:\downloads\usd-20.05-win64_py36_release\lib\python\pxr\Usd>dumpbin /dependents _usd.pyd
Microsoft (R) COFF/PE Dumper Version 14.27.29111.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file _usd.pyd

File Type: DLL

  Image has the following dependencies:

    usd.dll
    pcp.dll
    sdf.dll
    vt.dll
    gf.dll
    tf.dll
    arch.dll
    python36.dll
    boost_python36-vc141-mt-x64-1_70.dll
    tbb.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    KERNEL32.dll

  Summary

       54000 .data
        D000 .pdata
        1000 .pxrctor
       80000 .rdata
        3000 .reloc
        1000 .rsrc
       ED000 .text`

Trying it in the other trawler gives me the following.
![image](https://user-images.githubusercontent.com/3763817/94099946-6f9d2b80-fde9-11ea-9881-620acfcf7fd9.png)

**Comment by meshula** [comment]
The little red X's mean the dlls can't be resolved in the path... if you echo %PATH% and %PYTHONPATH% from the command line where usdcat is failing, can you spot the directories with the missing dlls (usd.dll et al)? For the dependencies.exe tool to work, the variables will need to be set in the global user environment, using either the awkward Windows settings panel, or using a tool like RapidEnv. (https://www.rapidee.com/en/about)

**Comment by ollied-xx** [comment]
Thanks @meshula.  I am pretty sure I have set the environment variables correctly.  Please see the screen shot for what I have atm.

![image](https://user-images.githubusercontent.com/3763817/94224820-9d997300-feb0-11ea-8731-64c296e3fc85.png)

Thanks for taking the time to look into this, apreciate it.

**Comment by ollied-xx** [comment]
Thanks @meshula.  I am pretty sure I have the environment variable set up correctly.  This is what I have at the moment.

![image](https://user-images.githubusercontent.com/3763817/94225072-48aa2c80-feb1-11ea-8140-ec1e8da5d187.png)

Thanks for taking the time to look into this, apreciate it.

**Comment by meshula** [comment]
Since you have both a 20.05 and a 20-08 directory, could you try running usdcat again from the 20.05 bin? Your command line in the screen shot shows running usdcat in a 20-08/bin directory. I imagine the problem will still persist if you run from 20.05, but it would be good to eliminate possible sources of errors.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6369

**Comment by ollied-xx** [comment]
OMG I feel like such a chump!  It was litterly that typo.  I had the versions mixed up between 20.05 and 20.08.  I must have looked over those paths so many time to check I had it all correct.  All good now by the looks of things.  Thanks for your help guys, appreciate it.  

![image](https://user-images.githubusercontent.com/3763817/94510321-b917bd00-01d3-11eb-9329-dbee7032b303.png)

**Comment by meshula** [comment]
Great! I'm relieved it's not some new twist cmake or somesuch has thrown at us that we need to work through :)
