### ISSUE TITLE
maya plugin: add support for referencing as an alternative to assemblies

### ISSUE THREAD

**Issue by chadrik** [PixarAnimationStudios/USD#134]
After a very thorough investigation of Maya's assemblies we've concluded that they are inadequate (an understatement), so we've endeavored to add support for Maya's "Old-school" references to the USD Maya plugin.  Old-school referencing can suffer from poor performance with large numbers of files and edits, but our 15 years of experience using it has shown that it is stable and supports the features that we need.

We've built a working prototype and will be creating a PR for it shortly, but in the meantime I thought I'd open an issue to explain the design and provide a chance for feedback from the community.

# Design Overview

The overarching idea is that Maya references can be used anywhere that assembly nodes are currently.

The proposal consists of 4 related, but independent features to be added to the USD importer:
- Representations
- References to USD files
- Proper handling of namespaces
- References to Maya files

## Representations

Maya's assemblies have the notion of "representations", which are different ways of viewing a specific segment the scene hierarchy.  The active representation is specified per assembly node, and all nodes within the assembly conform to that representation.  USD's `pxrUsdReferenceAssembly` provides four representations: 

- "contracted":  create a proxy node displaying all nodes below the assembly
- "expanded": create transforms and proxy nodes in the hierarchy below this reference, stopping at sub-references
- "full":  create transforms and "real" nodes (i.e. geometry) in the hierarchy below this reference, stopping at sub-references
-  "playback": create a proxy node optimized for playback

We can control representations on import/reference by setting some data in the scene prior to invoking our `MPxFileTranslator`.  The translator can then refer to this data to control how it creates nodes.  

Changing of VariantSets can be handled in the same way as representations.

### Changing State

In order to avoid the need to reload the entire scene from the root reference each time a VariantSet or representation is changed, which would be prohibitively slow for large scenes, we create a Maya reference for each USD reference.  This also gives us the ability to unload an individual reference (and by extension, all its children), which is akin to the state that an Assembly node is in when no representation is selected.

One challenge is that `MPxFileTranslator` lacks the callbacks of `MPxAssembly` for interpreting reference edits when reloading a reference.  In practice this may mean that edits made to nodes in "full" mode will not be reflected when switched to "collapsed" (i.e. proxy) mode.   For example, if you translate node "Foo", then change representations such that "Foo" is now contained within a proxy node, the edits for "Foo.translate" will not be picked up by our proxy without some work.  There *may* be some way to get access to the edits via `MItEdits` in proxy mode, so we will look into this.  It might also mean that changing variants is slower than with `pxrUsdReferenceAssembly` (need to investigate this further).

One boon is that assembly representations can only be controlled at the assembly node-level, but in designing this system we could conceivably control them at the node level, i.e. allowing individual shapes within a reference to be set to proxy or full.  

(Note: we've yet to begin work on representations)

## References to USD Files

The details of how we create nested references to USD files is worth explaining.  Creating a Maya reference takes two arguments: the path to the file to reference, and the options encoded as a string.   Technically what our `MPxFileTranslator` needs to know is the path to the *root* usd file being loaded, and a prim path.  In other words, the file path is always the same for all nested references, but the options change at each location.  In practice we can't use the same path at each level because Maya prevents reference cycles, so we *must* generate a unique, existing path for each sub-reference.  To do so, we inspect the stage to find the path of the USD reference and use that path when creating the Maya reference, but the path itself is not used by our `MPxFileTranslator`; instead, we provide both the root usd file and the prim path as part of the options string.  Even though using these unique sub-reference paths is a workaround, they are useful from a UI perspective. For example, Maya's reference UI displays a hierarchy of the referenced usd files, which is much more useful than if it had displayed the same root path over and over.

## Namespaces

Unlike assemblies, Maya references are safe to use without namespaces, so the DAG hierarchy in Maya can exactly mirror the DAG in USD.  We still need to add namespaces to DG nodes that we create during import or reference, since unlike USD, Maya DG nodes do not have a parent DAG.

By default, we plan to use the prim path as a namespace, since this is the only way to automatically avoid (most) name clashes.  For example,  prim `</chars/wolf1/shaders/shader>` becomes maya node `usd:chars:wolf1:shaders:shader`.  The root `usd:` namespace is required because Maya has a rule that a root namespace cannot have the same name as a node.  So, we cannot have both the root namespace "chars" and node "chars".

As an additional option we'd like to support using a custom string specified on the referencing prim to control the namespace of DG nodes below it.  It will be up to user or pipeline to ensure safety.

## Referencing Maya files

We would also add a mechanism within the USD Maya plugin for triggering the creation of references to Maya scenes (i.e. .ma and .mb files) from placeholder prims.  We would achieve this by watching for prims with a `maya:reference` attribute.   This feature was fleshed out in issue #126 and I'll eventually move that to its own issue, but I thought I should include a summary here for the sake of completeness.

References to Maya files would be placed under a group (i.e. transform) named after the reference prim.  The group is required because a reference to a Maya file can contain many top-level nodes, and there is no concept akin to a default prim: i.e. no facility for specifying a default node, renaming nodes, or filtering nodes.  So we imagine that the root of the referenced scene is the default prim.

Namespaces would follow the same rules described above (converting prim path to namespace) however unlike with .usd files, the namespace would be applied to both DG *and* DAG nodes alike, instead of just DG nodes, because we don't have the ability to control this for .ma/b files. 

For example, given a maya scene "wolf.mb":

```
wolf
  claws
  fur
extra
```

We would export a placeholder scene "wolf.usd" containing a `maya:reference` attribute that points to "wolf.mb".  The simplest placeholder file looks like this:

```
(
    defaultPrim = "placeholder"
)

def "placeholder"
{
    custom asset maya:reference = @/path/to/wolf.mb@
}
```

You can of course put geometry under the placeholder for viewing outside of Maya.

A usd scene can consume that placeholder file as a reference:

```
wolf1                -> @/path/to/wolf.usd@</>
  wolf
    claws
    fur
  extra
wolf2                -> @/path/to/wolf.usd@</>
  wolf
    claws
    fur
  extra
```

On importing or referencing into Maya, the placeholder prims would be converted into Maya references:

```
wolf1                => /path/to/wolf.mb
  usd:wolf1:wolf
    usd:wolf1:claws
    usd:wolf1:fur
  usd:wolf1:extra
wolf2                => /path/to/wolf.mb
  usd:wolf2:wolf
    usd:wolf2:claws
    usd:wolf2:fur
  usd:wolf2:extra
```

It may make sense to control reading the `maya:reference` attribute via a representation, e.g. named "Full (maya)".

### Referencing 

Currently, when attempting to create a Maya reference to a .usd file (e.g. `file -reference ...`), a `pxrUsdReferenceAssembly` node is created each time that a USD reference is traversed, which results in an error because Maya disallows nesting assemblies and references.  Since the current behavior results in an error, we felt that a good place to start was to disable the generation of assemblies when invoked from a Maya reference.

### Importing

Importing will require a new option to choose between creating assemblies or references, since in this case either option could technically work.

### Exporting

On export we drop any namespaces added by the import/reference mechanism.   Namespaces not created by our system are handled as they are currently:  `:` is replaced with `_`.

As with Assemblies, during export we will generate a USD reference whenever a Maya reference is encountered.

One question to answer is how we determine that a namespace has been added by our system vs created externally.  Most scenarios are obvious -- namespaces present on a node within a reference to a .usd file could have only been created by our system -- but imports of .usd files (wherein we lose provenance) make this more complicated. 

# Pros/Cons of Referencing vs Assemblies

Pros
- objects can be placed in sets (incl. display layers, render layers, shading groups)
- namespaces are *not* required on DAG nodes
- representations can be specified at the node level rather than Assembly level
- less bloated: a single edit is stored per attribute, rather than a unbounded queue as with assemblies

Cons
- no callbacks for interpreting reference edits when changing representations. 

---

I think that about sums it up.  We'll be making a pull request shortly for the core functionality, sans representations.  Comments and suggestions are welcome.

(edit1: added synopsis of plan for references to maya files, and exports)
(edit2: added pros/cons)
(edit3: added more detail about namespaces and representations, and examples of references to Maya files)
(edit 4: added note about VariantSets)
(edit 5: clarified that this is 4 features)
(edit 6: added example of placeholder file)

**Comment by jtran56** [comment]
Filed as internal issue #141524.

**Comment by spiffmon** [comment]
Hi Chad,
    This sounds really interesting, and well considered.  We are working on getting the right knowledgeable folk here together to discuss before we try to give any feedback - hoping that will happen next week.

Happy New Year!
--spiff

**Comment by chadrik** [comment]
Hi Spiff,

Quick update:  progress on this feature is going quite well.  References are working and DG namespaces are almost done.

I wanted to give you a heads up that getting referencing working resulted in a little bit of collateral damage, but nothing too bad.  Currently, import and export are handled by different `MPxFileTranslator`s -- registered as `pxrUsdExport` and `pxrUsdImport` -- but we've discovered a bug with Maya Referencing related to this design.  Basically, Maya gets confused by the two translators when saving out a maya file, and it tags each reference with the name of the *exporter* instead of the *importer*:

```
//Maya ASCII 2016R2 scene
//Name: testUsdRef3.ma
//Last modified: Fri, Jan 06, 2017 03:34:23 PM
//Codeset: UTF-8
file -rdi 1 -ns "foo" -rfn "fooRN" -typ "pxrUsdExport" "/shots/s00_01/s00_01.usd";
file -rdi 2 -rpr "s00_01_anim" -rfn "s00_01_animRN" -op "primPath=/World/sets/Room_set;topLayerUsd=/shots/s00_01/s00_01.usd;parent=sets;parentRefPaths=/shots/s00_01/s00_01_anim.usd"
         -typ "pxrUsdExport" "/shots/s00_01/s00_01_anim.usd";
<snip>
file -r -ns "foo" -dr 1 -rfn "fooRN" -typ "pxrUsdExport" "/shots/s00_01/s00_01.usd";
```

When loading this scene we get an error because pxrUsdExport (obviously) doesn't know how to read usd files.

As far as we can tell, the benefit of separate translators is mostly one of UI: you can register a separate set of options and GUI for each.  I took a look at Alembic to see how they approach this and they have an `MPxFileTranslator` for import only; export is handled by a command instead, so no help there.  The developer on this project, @elrond79, has submitted a bug to ADSK and tried a number of hacks to get around the issue, but at this point it appears our best option is to merge the translators into one, and doing so was fairly trivial.  He was able to find the right combination of global MEL variables to detect what context the GUI is being call from, so on the surface everything looks and behaves exactly as it did.

**Comment by ltitleydwarf** [comment]
Hey,
I'm interested in the work you guys are doing. Whats the right branch to checkout to investigate your changes ? I've cloned your luma fork, and found 'references' but that hasn't had any commits since Jan. At the moment I'm just interested in cloning and seeing where you got up to.

**Comment by chadrik** [comment]
Hi @ltitleydwarf ,
We're wrapping up a sprint to get the foundations of our USD pipe rolled out, so we'll be taking some time in the week or two to get our feature branches cleaned up and pushed.  We've completed References to USD files, Proper handling of namespaces, References to Maya files, but not Representations.  I should say that while we're glad to push up the work that we've done, I need to work out with @spiffmon whether or not it makes sense for us to make a pull request for these referencing features, because we'll soon be working toward an alternate solution.

**Comment by ltitleydwarf** [comment]
> because we'll soon be working toward an alternate solution.
An alternate solution to what you've just developed ?

**Comment by sunyab** [comment]
Cleaning up old issues, the Maya plugin has long been retired in favor of Autodesk's [maya-usd](https://github.com/Autodesk/maya-usd)
