### ISSUE TITLE
[hydra] No way to efficiently select unique prims + instances

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1343]
### Description of Issue

As an artist, the most common type of selection done is to select at the prim level (ie, when `pickTarget` is `pickPrimsAndInstances`.   This is common enough that it is the default setting for pickTarget.  However, the underlying code doesn't really align with this.  The closest corresponding option for `resolveMode` is `resolveUnique` - however, that defines "unique" as being the combination of all possible picking information - ie, it constructs a hash including not just prim and instance, but also elementIDs / edgeIDs / pointIDs.  This means that scenarios with marquee selection in particular, we can be having a lot of extra unnecessary calls to `HdxPickResult::_ResolveHit`, as well as a lot of missed opportunities for the same-as-the-previous-hash optimization used in `HdxPickResult::ResolveUnique`.

I can see two ways to address this:

- modify `HdxPickFromRenderBufferTask::Execute` and `HdxPickTask::Execute` to not even retrieve `elementIDs` / `edgeIDs` / `pointIDs` if the `pickTarget` isn't appropriate for them.  This would give better performance if you just care about prims + instances, but if anyone else was relying on having access to the faces/edges/verts, it would no longer be available, so it would be a potentially breaking change.  (There also isn't any `pickTarget` option that would allow the caller to retrieve all the possible info - though perhaps one could be added.)
- add a new `resolveMode` (say, `resolveUniquePrims`, or `resolveUniquePrimsAndInstances`) that would ignore the other bits when calculating the hash for determining "uniqueness".  Or, alternatively, add a new masking param, `uniqueFilter`, that would allow callers to precisely pick which parts they want to consider when determining uniqueness.

More info here: https://groups.google.com/g/usd-interest/c/Cgosy3r7Vv4?pli=1

### System Information (OS, Hardware)
Windows 10

### Package Versions

usd-0.20.08

**Comment by rajabala** [comment]
Thanks for filing, Paul.
The picking render pass in Storm doesn't use aov's yet, and requires all of the ID draw (render) target attachments to be bound.
The attachment binding points aren't code gen'd yet.

Re: the underlying issue, we can certainly extend `HdxPickResult::_GetHash` to factor the pickTarget and skip unnecessary information. This way, we don't need to introduce a resolution mode _per_ combination, and can continue to use `resolveUnique`.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6383
