### ISSUE TITLE
HdCoordSys crash

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1346]
### Description of Issue
In an HdCoordSys::Sync() the following code will crash if the prim referred to by the coordSys does not exist:
```
    if (*dirtyBits & DirtyBits::DirtyTransform) { // pxr::HdChangeTracker::IsTransformDirty uses wrong bit!
        mXform = sceneDelegate->GetTransform(GetId()); // this crashed when prim does not exist
    }

```
### Steps to Reproduce
Use --mask in usdview to remove the object referred to by a coordSys and then render with a renderDelegate that tries to use the transform.

### System Information (OS, Hardware)
Linux

### Package Versions
20.8

**Comment by jilliene** [comment]
Filed as internal issue #USD-6386

**Comment by c64kernal** [comment]
Thanks for filing @spitzak  -- if you happen to have a small shareable usd file that exhibits this, that would be super helpful.

**Comment by c64kernal** [comment]
Nevermind, we have a repro, thanks again!
