### ISSUE TITLE
Instanced UsdSkel - xforms not applied in HdStorm

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1347]
### Description of Issue

When instancing UsdSkel riggs, it seems like per-instance xforms are not properly applied.

### Steps to Reproduce
1. Download the and extract the [HumanFemale usd sample](https://graphics.pixar.com/usd/files/UsdSkelExamples.zip)
2. Download the attached [HumanFemale.instanced.usda.zip](https://github.com/PixarAnimationStudios/USD/files/5307132/HumanFemale.instanced.usda.zip), extract, and place `HumanFemale.instanced.usda` in the same folder as `HumanFemale.usd` / `HumanFemale.walk.usd` / `HumanFemale.keepAlive.usd`.
3. Open `HumanFemale.instanced.usda` in usdview
4. Note that the 3 instances are all placed "on top of" each other.
5. Edit the `HumanFemale.instanced.usda` - comment out the three "instanceable = true" lines.
6. Re-open `HumanFemale.instanced.usda` in usdview
7. Note that the models are now properly offset.

### System Information (OS, Hardware)
Windows 10

### Package Versions
dev tip (533030f94bab9e4b2df5e8896b867b3379bfeafc)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6387

**Comment by pmolodo** [comment]
Great, thanks!
