### ISSUE TITLE
Instanced UsdSkel - blendshapes not applied in HdStorm

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1348]
### Description of Issue

When instancing UsdSkel riggs, it seems like blendshapes are not properly applied.

### Steps to Reproduce
1. Download the and extract the [HumanFemale usd sample](https://graphics.pixar.com/usd/files/UsdSkelExamples.zip)
2. Download the attached [HumanFemale.instanced.usda.zip](https://github.com/PixarAnimationStudios/USD/files/5307132/HumanFemale.instanced.usda.zip), extract, and place `HumanFemale.instanced.usda` in the same folder as `HumanFemale.usd` / `HumanFemale.walk.usd` / `HumanFemale.keepAlive.usd`.  
3. Open `HumanFemale.instanced.usda` in usdview
4. Note that the 3 instances don't seem to have any facial blendshapes applied (ie, eyes are mostly closed).
5. Edit the `HumanFemale.instanced.usda` - comment out the three "instanceable = true" lines.
6. Re-open `HumanFemale.instanced.usda` in usdview
7. Note that the faces now have blendshapes (ie, eyes are mostly open).

### System Information (OS, Hardware)
Windows 10

### Package Versions
dev tip (533030f94bab9e4b2df5e8896b867b3379bfeafc)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6388

**Comment by pmolodo** [comment]
Confirmed working as of 23.02 (probably long before), closing.
