### ISSUE TITLE
USD Ascii integer array formatting includes human readable comma grouping on Windows

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#1350]
### Description of Issue
A user of the USD Unity SDK (@awnzl)  reported this problem:
https://github.com/Unity-Technologies/usd-unity-sdk/issues/198

```
Just replaced Digit Grouping on variant without commas in my Windows Region settings, and commas in usda files disappeared :)

Setting: Control Panel -> Clock and Region -> Region -> Additional Settings... -> Digit grouping
```

### Steps to Reproduce
1.  Enable digit grouping
2. Export USD ASCII file with an integer array longer than 1000 (or whatever it takes in your region to get additional digit grouping)

The C# repro is:

```
var usdFaceVertexIndices = new VtIntArray();

for (int idx = 0; idx < 1010; ++idx)
    usdFaceVertexIndices.push_back(idx);

USD.NET.Scene scene = USD.NET.Scene.Create();
var stage = new UsdStageWeakPtr(scene.Stage);

UsdGeomMesh mesh = UsdGeomMesh.Define(stage, new SdfPath("/Test"));
mesh.CreateFaceVertexIndicesAttr(new VtValue(usdFaceVertexIndices));

scene.Stage.GetRootLayer().Export(@"c:\temp\test.usda");
```

### System Information (OS, Hardware)
Windows

### Package Versions
20.08

### Build Flags
monolithic, no python, no imaging

**Comment by gitamohr** [comment]
Does this happen in a standalone repro?  Is Unity configuring locale stuff?

**Comment by meshula** [comment]
I believe we use ostreams as is in Sdf, rather than forcing particular facets. There are ramifications to reading as well, since setting some locale on Monday, writing a file, setting another locale on Tuesday and reading Monday's file could fail.

**Comment by jcowles** [comment]
I don't have a functioning Python build of USD handy just now, would one of you mind giving it a try?

(If you don't have time, I can try to repro when I have a moment to revive my python build)

**Comment by gitamohr** [comment]
I don't have a functioning Windows box handy just now, but it works fine on Linux! ;-)

**Comment by jcowles** [comment]
Ok, got it going -- neither the C# nor Python version of this bug is reproducible for me :(

I'm going to pick up this thread on the original Unity bug and report back.

**Comment by jcowles** [comment]
Thinking about this more, this is the default setting in Windows, if it were a systematic defect, lots of people should be hitting this, but this is the first report I've heard.

I'm going to close this out and reopen if/when we can repro.
