### ISSUE TITLE
The Half class in base/gf/ilmbase_half.h should update HALF_DIG define

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1354]
### Description of Issue

The HALF_DIG define in base/gf/ilmbase_half.h is set to 2. In the OpenEXR project, this value has been updated to 3: https://github.com/kdt3rd/openexr/commit/0000624e7d8281b92757cfe86a8b9f629aa4b940

The USD copy of this header should probably updated similarly.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6407
