### ISSUE TITLE
Dynamic File Format plugins should not require a file on disk

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#1356]
### Description of Issue
As per forum discussion : https://groups.google.com/g/usd-interest/c/GuhQzdCeNTI/m/kM109LnhAgAJ

Right now dynamic file formats require a file on disk, even if that file format is only dynamic and runs entirely off the SDF_FORMAT_ARGS. We would like to be able to run a format purely from the ARGS without any requirement for a dummy file.

We have been skirting around this issue by prefixing the identifier with anon: ie "anon:.format:SDF_FORMAT_ARGS:xxx=xxx" which allows us to bypass the limitation of having a file and work truly as a totally in memory layer. This however has caused some issues in Houdini-18 and Solaris which assumes it owns all of the anon layers and does some processing on them which causes our format to fail after import. This is also a hack and as Spiff said on the forums it is not guaranteed to work in all situations as is.

### Steps to Reproduce
1. Try and create a payload to a dynamic file format extension without a valid file.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6416
