### ISSUE TITLE
[CHANGELOG.md] Hyperlinks to issues and pull requests

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1362]
Hello,

Would it be possible for the [CHANGELOG.md](https://github.com/PixarAnimationStudios/USD/blob/release/CHANGELOG.md)'s **Issue** and **PR** references to become hyperlinks (they're consistently formatted for the most part!)

This would improve the change log browsing experience for developers interested in the code changes and discussions as part of the issue / PR.  A nice to have really :)

... and, cheers to Pixar's USD team for providing clear & concise change logs every release.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6421

**Comment by c64kernal** [comment]
Thanks for the sug, it's a good idea!
