### ISSUE TITLE
[USD Glossary] API Schema description needs update

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1363]
Now that applied API schema contributes to a prim's type identity ([UsdPrimTypeInfo](http://graphics.pixar.com/usd/docs/api/class_usd_prim_type_info.html)),  the [API Schema USD glossary entry](https://graphics.pixar.com/usd/docs/USD-Glossary.html#USDGlossary-APISchema
) looks like it needs an update, specifically the excerpt:
"An API schema is a prim Schema that does not represent an object's type-identity"

**Comment by rlei-weta** [comment]
Also, under [Fallback](https://graphics.pixar.com/usd/docs/USD-Glossary.html#USDGlossary-Fallback):
"Many IsA Schemas define attributes that have an identifiable value..."

It _might_ be also worth mentioning applied API schemas as to not suggest to the reader that only IsA schema(s) define attributes which have fallback values.

**Comment by spiffmon** [comment]
Thanks for the report, @rlei-weta - should be better now... the [API Schema entry](https://graphics.pixar.com/usd/docs/USD-Glossary.html#USDGlossary-APISchema) had numerous problems!
