### ISSUE TITLE
Upgrade boost to 1.70.0 on macos

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#1369]
### Description of Issue

Under Xcode 12, b2, the build engine for boost 1.6x.x, no longer compiles due to clang now defaulting to the warning that a function has been implicitly declared, has been defaulted to be an error. A full description of the problem, by @rlei-weta is here: https://github.com/boostorg/build/issues/664

The current code in the build script reads as follows:

```python
if Linux() or MacOS():
    if Python3():
        BOOST_URL = "https://downloads.sourceforge.net/project/boost/boost/1.70.0/boost_1_70_0.tar.gz"
    else:
        BOOST_URL = "https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.gz"
    BOOST_VERSION_FILE = "include/boost/version.hpp"
```

If on macOS we only ever get 1.70.0 then an Xcode 12 build will succeed for Python2 as well. This solution deviates from the vfx2018 platform, but that seems unavoidable.

A proposed fix would be:

```python
if MacOS():
    BOOST_URL = "https://downloads.sourceforge.net/project/boost/boost/1.70.0/boost_1_70_0.tar.gz"
    BOOST_VERSION_FILE = "include/boost/version.hpp"
elseif Linux():
    if Python3():
        BOOST_URL = "https://downloads.sourceforge.net/project/boost/boost/1.70.0/boost_1_70_0.tar.gz"
    else:
        BOOST_URL = "https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.gz"
    BOOST_VERSION_FILE = "include/boost/version.hpp"
```

### Steps to Reproduce

1. Try to build usd with the stock build script, for Python2, under Xcode 12

### System Information (OS, Hardware)

Xcode 12

**Comment by jilliene** [comment]
Filed as internal issue #USD-6447
