### ISSUE TITLE
[codegenTemplates] Dangling isPrivateApply reference

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1371]
The *isPrivateApply* feature is removed but there's still a reference to it here:
https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/usd/codegenTemplates/schemaClass.h#L291

If there is currently no reliance on jinja2's graceful handling of undefined attributes during code generation, one suggestion would be to add a `undefined=jinja2.StrictUndefined` kwarg when constructing the `Environment` object - which can help catch errors like this :)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6449
