### ISSUE TITLE
[UsdSkel Python Bindings] wrapSkinningQuery.cpp ComputeExentsPadding typo

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1375]
Looks like the method should be `ComputeExtentsPadding`:
https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/usdSkel/wrapSkinningQuery.cpp#L221
https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/usdSkel/wrapSkinningQuery.cpp#L230

**Comment by jilliene** [comment]
Filed as internal issue #USD-6461

**Comment by c64kernal** [comment]
Well spotted, thank you!
