### ISSUE TITLE
Hyperlinks to Attributes under PropertySpec are broken

### ISSUE THREAD

**Issue by HamedSabri-adsk** [PixarAnimationStudios/USD#1376]
### Description of Issue
While reading the PropertySpec section in USDGlossary, I noticed that the Hyperlink to Attributes are broken.

### Steps to Reproduce
Under PropertySpec, clicking on Attributes link doesn't seem to work.

http://graphics.pixar.com/usd/docs/USD-Glossary.html#USDGlossary-PropertySpec

Browsers that I tried:  FireFox / Chrome

**Comment by spiffmon** [comment]
Thanks, @HamedSabri-adsk - don't know how that happend - others in that entry were clipped also.  Fixed internally, so I'll close this, but it may take a bit to push it out.
