### ISSUE TITLE
USD handles Windows mount points/junctions incorrectly

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1377]
### Description of Issue
When trying to write files to locations that are under Windows mount points (junctions), the USD path handling code in Tf and Arch has issues that cause failures.

### Steps to Reproduce
1. Open a command prompt as an administrator.
2. Assuming a machine has two drives, C and D, create a folder D:\bar.
3. From C:\, run 'mklink /J foo D:\bar\sub'
4. Start python and run:
from pxr import Usd
s = Usd.Stage.CreateInMemory()
s.Export('C:/foo/sub/out.usda')
Produced this error: Insufficient permissions to write to destination directory 'C:\sub'
s.Export('C:/foo/out.usda')
Produced this error: Cannot create path to write 'c:/foo/sub/out.usda'

Note that these are two different errors, indicating two different bugs.

### System Information (OS, Hardware)
Windows

**Comment by jilliene** [comment]
Filed as internal issue #USD-6462

**Comment by sunyab** [comment]
Closing old issue, this was fixed by #1378.
