### ISSUE TITLE
[Docs] Typo in 'Maximizing USD Performance' page

### ISSUE THREAD

**Issue by ronen** [PixarAnimationStudios/USD#1382]
Typo in:
> [http://graphics.pixar.com/usd/docs/Maximizing-USD-Performance.html#MaximizingUSDPerformance-WhatmakesaUSDsceneheavy/expensive?](http://graphics.pixar.com/usd/docs/Maximizing-USD-Performance.html#MaximizingUSDPerformance-WhatmakesaUSDsceneheavy/expensive?) 

"redundandtly" should be "redundantly":

<img width="798" alt="Screen Shot 2020-11-03 at 2 52 48 PM" src="https://user-images.githubusercontent.com/125620/97987799-908f6e00-1de4-11eb-910d-3307550caed2.png">

**Comment by spiffmon** [comment]
Fixed!
