### ISSUE TITLE
[Docs] Bad link to jemalloc docs in 'Maximizing USD Performance' page?

### ISSUE THREAD

**Issue by ronen** [PixarAnimationStudios/USD#1383]
The section "Use an allocator optimized for multi-threading":
* http://graphics.pixar.com/usd/docs/Maximizing-USD-Performance.html#MaximizingUSDPerformance-Useanallocatoroptimizedformulti-threading

includes a link to jemalloc  at [http://www.canonware.com/jemalloc/](http://www.canonware.com/jemalloc/).  I'm currently finding that page fails to load (server timeout).  

But in any case, the official home page for jemalloc seems to be at [http://jemalloc.net](http://jemalloc.net), which works fine.

Should the link be updated?

**Comment by spiffmon** [comment]
Wow, it's been awhile, @ronen !  Thanks for the alerts - I've addressed both this and the other issue you filed, and have updated the site - lmk if you find anything else.

Cheers,
--spiff

**Comment by ronen** [comment]
> Wow, it's been awhile, @ronen ! Thanks for the alerts - I've addressed both this and the other issue you filed, and have updated the site - lmk if you find anything else.

Hi @spiffmon !  Yes it's been ages.  Amazing work you've done on USD, quite the progress from the "hook files" of way back when... 😄
