### ISSUE TITLE
material on skinned mesh is not visible in usdview

### ISSUE THREAD

**Issue by emanuelshalev** [PixarAnimationStudios/USD#1384]
### Description of Issue
material on skinned mesh is not visible in usdview
regression from version 20.08 to 20.11
### Steps to Reproduce
sample usd with skinned green arm here
https://groups.google.com/d/msgid/usd-interest/55f9a3d5-134c-49e4-b23c-5b67eaf884a7n%40googlegroups.com

**Comment by trebconnell** [comment]
Reproduces with multiple renderers on Windows 10 ; v20.11

Seems like issue may be in Hydra, but I'm not too familiar with Hydra internal logic.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6471
