### ISSUE TITLE
domelight not visible in usdview (using hdri background and light)

### ISSUE THREAD

**Issue by emanuelshalev** [PixarAnimationStudios/USD#1385]
### Description of Issue
skydome light not visible in usdview

### Steps to Reproduce
usd asset with domelight
def DomeLight "domeLight"
{
    #can download hdri domelight from here: https://hdrihaven.com/hdris/
    asset texture:file = @anyskydome.exr@
    token texture:format = "latlong"
}

full example:
*******************************
#usda 1.0

def DomeLight "domeLight"
{
    #can download hdri skydome from here: https://hdrihaven.com/hdris/
    asset texture:file = @anyskydome.exr@
    token texture:format = "latlong"
}

def Material "material"
{
	token outputs:surface.connect = </material/shader.outputs:surface>

	def Shader "shader"
	{
		uniform token info:id = "UsdPreviewSurface"
		color3f inputs:diffuseColor = (0, 1, 0)
		token outputs:displacement
		token outputs:surface
	}
}
	
def Xform "root" ()
{
    def Mesh "cube"
    {
        uniform bool doubleSided = 1
        float3[] extent = [(-0.5, -0.5, -0.5), (0.5, 0.5, 0.5)]
        int[] faceVertexCounts = [4, 4, 4, 4, 4, 4]
        int[] faceVertexIndices = [0, 1, 3, 2, 2, 3, 5, 4, 4, 5, 7, 6, 6, 7, 1, 0, 1, 7, 5, 3, 6, 0, 2, 4]
        rel material:binding = </material>
        point3f[] points = [(-0.5, -0.5, 0.5), (0.5, -0.5, 0.5), (-0.5, 0.5, 0.5), (0.5, 0.5, 0.5), (-0.5, 0.5, -0.5), (0.5, 0.5, -0.5), (-0.5, -0.5, -0.5), (0.5, -0.5, -0.5)]
        color3f[] primvars:displayColor = [(0, 0, 1)]
        float2[] primvars:st = [(0.375, 0), (0.625, 0), (0.625, 0.25), (0.375, 0.25), (0.625, 0.5), (0.375, 0.5), (0.625, 0.75), (0.375, 0.75), (0.625, 1), (0.375, 1), (0.875, 0), (0.875, 0.25), (0.125, 0), (0.125, 0.25)] (
            interpolation = "faceVarying"
        )
        rel material:binding = </material>
        int[] primvars:st:indices = [0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 8, 9, 1, 10, 11, 2, 12, 0, 3, 13]
        token visibility = "inherited"
        float xformOp:rotateX = 45
        float xformOp:rotateY = 45
        double3 xformOp:translate = (0, 0, 0)
        uniform token[] xformOpOrder = ["xformOp:rotateX", "xformOp:rotateY", "xformOp:translate"]
    }

}

*******************************

**Comment by trebconnell** [comment]
Reproduces with multiple renderers on Windows v20.11

Seems like issue may be in Hydra, but I'm not too familiar with Hydra internal logic.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6472
