### ISSUE TITLE
Patch for soversion

### ISSUE THREAD

**Issue by luyatshimbalanga** [PixarAnimationStudios/USD#1387]
### Description of Issue
This patch allows versioning .so files for building a package
### Steps to Reproduce
1. Build package on either Fedora or Mageia

### System Information (OS, Hardware)
Fedora

### Package Versions
All version
### Patch

[USD-20.11-soversion.patch.txt](https://github.com/PixarAnimationStudios/USD/files/5505916/USD-20.11-soversion.patch.txt)

**Comment by c64kernal** [comment]
Thanks @luyatshimbalanga -- please see http://graphics.pixar.com/usd/docs/Contributing-to-USD.html, submit a CLA and then a PR for this patch if you'd like to pursue getting it merged. Thanks again.
