### ISSUE TITLE
stage.GetPrimAtPath() not working in usdc

### ISSUE THREAD

**Issue by suesauer** [PixarAnimationStudios/USD#1390]
### Description of Issue
If you run python.py on the usda supplied the code works as expected, if you run the python.py on the supplied usdc it fails saying "Accessed invalid null prim"

### Steps to Reproduce
run python.py on the given usds:
[geom.tar.gz](https://github.com/PixarAnimationStudios/USD/files/5529865/geom.tar.gz)

### System Information (OS, Hardware)
Linux centos 7.6
### Package Versions
USD dev 58b40b1129d3a119586187662525cf5e1d688c50
### Build Flags
python2.7 $SCRIPT_DIR/USDPXR/USD/build_scripts/build_usd.py $SCRIPT_DIR/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --alembic --materialx --tests --openvdb

**Comment by gitamohr** [comment]
I had to add import statements to python.py to get the Usd and Sdf modules, but after doing that both files seem to behave correctly.  I do not get the "Accessed invalid null prim" error.  I can use usdcat to convert the usdc file to text, and there are some minor differences in metadata, but the prim structure is identical.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6481

**Comment by suesauer** [comment]
seems to be working for me now as well, \:D/  not sure why it was not working before.
