### ISSUE TITLE
[User Docs] "Deep" / "Self" Anchor links

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1394]
Hello,

The [USD user docs](https://graphics.pixar.com/usd/docs/index.html) provides rich and accessible information (cheers to the USD team for curating these over the years!).  

It is often desirable to share an _anchor link_, such as to a glossary entry, when referring to a specific section of the doc during discussions.

Would it be possible to provide ["deep" or "self" anchor links](https://ux.stackexchange.com/questions/36304/use-of-mouse-over-paragraph-marker-in-headlines-for-permalink) for the headings in the user doc pages?  This would be a _nice-to-have_ UX  upgrade over navigating to the top of the page to grab the link from the TOC.

[AnchorJS](https://www.bryanbraun.com/anchorjs/) is an example of a tool for generating deep anchor links on existing pages.

Thank you!!

**Comment by jtran56** [comment]
Filed as internal issue #USD-6487

**Comment by sunyab** [comment]
These anchor links should now exist in the new documentation site that was rolled out with the 22.03 release. Closing this out, thanks!

**Comment by rlei-weta** [comment]
Amazing... thanks!
