### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'boost_python27-vc142-mt-x64-1_70.lib'

### ISSUE THREAD

**Issue by zakkar** [PixarAnimationStudios/USD#1395]
Hi there,

I'm trying to setup USD using the console command build_usd.py, after many attempts and fixes i was finally able to execute the script but unfortunately the cmale command fail at a certain point with the following message 

  arch.vcxproj -> E:\Install\USD\build\USD\pxr\base\arch\Release\arch.dll
LINK : fatal error LNK1104: cannot open file 'boost_python27-vc142-mt-x64-1_70.lib' [E:\Install\USD\build\USD\pxr\base\tf\tf.vcxproj]

i have the Boost library installed on my machine, i also tried to put the missing lib directly the file inside the Release folder but still getting the same issue, here's the full log
[log.txt](https://github.com/PixarAnimationStudios/USD/files/5548640/log.txt)

Any help would be appreciated

**Comment by meshula** [comment]
Two questions: 

what is the path to your copy of boost_python27-vc142-mt-x64-1_70.lib?

can you also attach your CMakeCache.txt?

**Comment by zakkar** [comment]
Here's the CMakeCache
[CMakeCache.txt](https://github.com/PixarAnimationStudios/USD/files/5549023/CMakeCache.txt)

As for the path it tries to copy it from the following path that was generated with the Cmake : E:/Install/USD/lib/boost_python27-vc140-mt-x64-1_70.lib

**Comment by meshula** [comment]
Ah, it looks like you are building USD with VS2019, but your boost was built with VS2017.

It wants:

```boost_python27-vc142-mt-x64-1_70.lib```

but cmake found:

```boost_python27-vc140-mt-x64-1_70.lib```

**Comment by zakkar** [comment]
Good catch, i wouldn't had expected that they will be compiled with different versions since both are created with the cmake command in the build_usd.py. But i think the cause of that is that i started the command from visual code.
Actually i build it from anew using the command prompt from visual 2019 and it works
Thanks
