### ISSUE TITLE
Build failure on Windows when using build-usd.py

### ISSUE THREAD

**Issue by sharaths21312** [PixarAnimationStudios/USD#1400]
### Description of Issue
I attempted to build USD, and it errors out, saying "Could NOT find boost (missing: python37) (found version "1.70.0")"

### Steps to Reproduce
1. Attempt to compile with the build-usd.py script. The options don't seem to matter for this issue.

### System Information (OS, Hardware)
Windows 10 19042.630 (20H2)
Intel Core i7-5500U (2 core, 4 thread, 2.4 GHz base)
AMD Radeon R5 M330 with Radeon software 20.11.2

### Package Versions
Visual studio 2019: 16.8.2
Python 3.7.9
PyOpenGL: 3.1.5
PySide2: 5.15.2
The other dependencies are the defaults in the build-usd.py script

### Build Flags
The build flags didn't seem to affect anything, I still get the same error without any, but the command whose logs are attatched was run with:
`py -3.7 .\build_scripts\build_usd.py --prman --prman-location %RMANTREE% --openvdb --prefer-speed-over-safety`

[log.txt](https://github.com/PixarAnimationStudios/USD/files/5602579/log.txt)

**Comment by meshula** [comment]
Is there a boost python library at all in the ```D:/Sharath/Animations/Blenderwingit/USD/build``` directory, somewhere? If so, how is it named?

**Comment by sharaths21312** [comment]
Oh, I'm sorry, I thought I had cleaned the cache, but the problem was that the same error happened in the old location, and I moved the code to a new one which is in the C drive

After clearing the build directory and rebuilding, still not fixed.
This time, I've run it with no additional options
[New log.txt](https://github.com/PixarAnimationStudios/USD/files/5605681/log.txt)

**Comment by meshula** [comment]
Somewhere in your build tree, there will be a boost python dll. On my machine, building for python 2.7, it is called ```boost_python27-vc142-mt-x64-1_70.dll```. It is hiding very deep, at ```C:\Projects\Pixar\usd-install\build\boost\bin.v2\libs\python\build\msvc-14.2\release\address-model-64\python-2.7\threading-multi```. Does such a file exist on your machine, in your ```Blenderwingit/USD/build``` directory, and if so, what is it called? There are no clues to this question in the ```New log.txt``` that I can find.

**Comment by sharaths21312** [comment]
The specified directory doesn't exist. There is, however a python-3.9 folder in `address-model-64`. I think this might be an issue with boost somehow installing for Python 3.9 since it is in PATH. I'll try rebuilding after adjusting PATH to see if it works.

**Comment by sharaths21312** [comment]
After changing, it builds successfully, and usdview shows some test files I tried correctly, but running it without `--renderer HydraDisabled` causes it to crash with a warning about OpenGL 4.5 not being supported.

**Comment by meshula** [comment]
Great progress! Is there something we could add to the "how to build" notes that would have helped you debug the issue quicker?

A common cause for the GL issue is that a storm-required extension is missing. That can happen on non-nVidia hardware, or on nVidia hardware with old drivers. Is there any other information in the output, such as an explanation about why OpenGL 4.5 is not supported?

**Comment by sharaths21312** [comment]
No, there appears to be no other output regarding the error message. Intel Graphics settings shows supported openGL as 4.4 (for the iGPU) and Radeon Software shows OpenGL as simply "Not Available" (Despite me being able to run GL apps and games like Minecraft JE on it with no issues).
I have succeed in building USD for linux in the same machine, and usdview ~~appears to work properly~~ it seems to not show some scenes when using the GL renderer, but Embree works fine (glxinfo shows OpenGL 4.6 and 4.5 respectively as supported version). Could you give some clue as to how to install the extension, or is it meant to be a part of the driver?

As for easier debugging, a note might be added saying something along the lines of: "Make sure the version of python on PATH is the same version used to build USD"

**Comment by sharaths21312** [comment]
I've managed to get it working on Windows too by setting python to use the discrete GPU in graphics settings (GPU-Z shows OpenGL 4.6 support when I tried, and online documentation indicates the same).

I have another question now, I've built USD with Prman support, now how do I render a usd file from the command line with Renderman?

**Comment by meshula** [comment]
I'll have to defer the answer to that question to someone else, prman isn't in my day to day workflow. Glad you've got past the initial build/run issues!

**Comment by sharaths21312** [comment]
Thanks for all you help anyway.
Maybe you could answer this version of my question: How do I render a usd file to an image on disk with any general renderer (say, GL or Embree)

**Comment by sunyab** [comment]
You can try the [usdrecord](https://graphics.pixar.com/usd/docs/USD-Toolset.html#USDToolset-usdrecord) utility and see if that gives you what you need.

I'm glad you were able to solve your build issue! I'm going to close this out, if you have other questions or issues with usdrecord please post them to the usd-interest group or file a new issue here. Thanks!

**Comment by sharaths21312** [comment]
@sunyab Can you give a link to the group? [This one](https://groups.google.com/forum/#!forum/usd-interest) from [here](https://graphics.pixar.com/usd/overview.html) gives me a "Content Unavailable" error, and the title bar shows "Access error".

**Comment by sunyab** [comment]
@sharaths21312 That's the right link, but it appears we're having issues with allowing people to join the group. We're trying to fix this now, but in the meantime you can post an issue here if you'd like. Thanks!

**Comment by sunyab** [comment]
Hi @sharaths21312, we think we've fixed the issue with the Google group so if you try the link again you should be able to join the group. Let me know if this doesn't work for you!

**Comment by sharaths21312** [comment]
Sorry for the delay in replying, but I am able to join the group, thanks for the heads up!
