### ISSUE TITLE
Add support for Python 3.8 on Windows

### ISSUE THREAD

**Issue by rstelzleni** [PixarAnimationStudios/USD#1404]
### Description of Issue

On Windows in Python 3.8, setting the path is no longer the right way to get USD's dlls to load in Python. There is a new api function "os.add_dll_directory(dllPath)" that we need to call instead of updating the path.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6498

**Comment by sunyab** [comment]
Closing this out, support for Python 3.8+ on Windows has been added in the 21.08 release.
