### ISSUE TITLE
Publish PyPI packages for Python 3.8

### ISSUE THREAD

**Issue by rstelzleni** [PixarAnimationStudios/USD#1405]
### Description of Issue

Once we support Python 3.8 on all platforms we should publish new PyPI packages so that they can be pip installed. See
https://github.com/PixarAnimationStudios/USD/issues/1404

**Comment by jilliene** [comment]
Filed as internal issue #USD-6499

**Comment by TheShermanTanker** [comment]
Will this only be for 3.8 or both 3.8 and 3.9?

**Comment by rstelzleni** [comment]
We were planning to add 3.8 next. That's the next version we've tested and believe is working. There should be no technical hurdles I'm aware of to also add 3.9, but so far I haven't done a build against python 3.9 and ran the tests or verified anything. I'm not sure if anyone at Pixar has.

Are you currently using python 3.9? We'll definitely want to get it added to the pypi packages, it's more a question of when. If there are users on that version currently that would help us prioritize. We should probably also file a separate issue for it.

**Comment by JoshkVFX** [comment]
Not using 3.9 myself but I am using 3.8. Just wanted to check in and see if the PyPI packages for 3.8 were going to be published anytime soon?

**Comment by sunyab** [comment]
Hi @JoshkVFX, unfortunately we're not going to be able to dig into PyPI support for 3.8 until after the next USD release, which is tentatively slated for mid-April. We'll definitely keep everyone posted on our progress.

**Comment by sunyab** [comment]
PyPI packages for Python 3.8 and 3.9 on all platforms have been published with the 21.08 release today. Closing.
