### ISSUE TITLE
TransferContent not generating proper change notifications sublayer changes on "streaming" layers

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1407]
### Description of Issue
When calling TransferContent to transfer a layer with sublayers into a USDC file, the change notification system is not catching the change to the sublayers, and so the new sublayer is not composed onto the stage.

### Steps to Reproduce
1. From the attached zip file, open grid.usd into usdview (just some simple grid mesh geometry):
[transfercontentbug.zip](https://github.com/PixarAnimationStudios/USD/files/5633540/transfercontentbug.zip)
2. In the Interpreter window, run:
l = Sdf.Layer.FindOrOpen("asset.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)
(asset.usda is empty except for a sublayer of torus.usda, which contains a torus mesh)
3. Refresh the viewport, and see that it is empty. Now do:
l = Sdf.Layer.FindOrOpen("torus.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)
The torus appears, because the mesh is directly in the layer being copied.
4. When doing the TransferContent, a breakpoint set in SdfLayer::_ComputeInfoToFindOrOpenLayer will not be hit, indicating, I believe, that the torus.usda sublayer is not being loaded, I presume because the SdfChangeBlock doesn't recognize that the sublayer stack was changed (though Exporting the modified root layer indicates that the sublayer was transferred over properly).
5. If you run this same procedure using grid.usda as the file first loaded into usdview, both steps 2 and 3 show the torus as expected. This points to the fact that "_data->StreamsData()" for USDC files returning true (as opposed to false for USDA files) is likely what leads to this incorrect change handling.

### Package Versions
Tested with 20.08 and 19.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-6504
