### ISSUE TITLE
Maya Plugin "Make Instances" doesn't work ?

### ISSUE THREAD

**Issue by zhoub** [PixarAnimationStudios/USD#141]
Create 1 cube in Maya, and create another instance of it by Duplicate Special, export the file as USDA, we will find two copies of geometric data.

**Comment by spiffmon** [comment]
Hi Bo,
   Sorry, the UI label is misleading; however, the documentation for the actual export option, [-exportRefsAsInstanceable](http://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html#MayaUSDPlugins-usdExportcommandflags), gives the actual story.  The option is for making **references** instanced on export.  Currently, recognizable (to the plugin) references can only be represented by pxrUsdReferenceAssemblies; however @chadrik has posted a proposal to expand the plugins to work with Maya references, as well, in Issue #134 .

We do have an issue open internally for adding support for import/export of Maya's native instancing, but as we don't use it internally, it hasn't risen to the top of our priority list.  When this bug gets reflected internally, I'd like to repurpose it to make the UI label more reflective of what the option actually does.

**Comment by jtran56** [comment]
Filed as internal issue #141638.

**Comment by sunyab** [comment]
Cleaning up old issues, the Maya plugin has long been retired in favor of Autodesk's [maya-usd](https://github.com/Autodesk/maya-usd)
