### ISSUE TITLE
[USD Toolset User Docs] Tool help entries out of date

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1410]
Most of the help entries for the command line tools are out of date (missing some of the newer cmdline args!):
https://graphics.pixar.com/usd/docs/USD-Toolset.html

Minor typo on "The mulit-file input" (https://graphics.pixar.com/usd/docs/USD-Toolset.html#USDToolset-usdcat)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6509

**Comment by sunyab** [comment]
This should be addressed with the new documentation site that was rolled out with the 21.11 release.
