### ISSUE TITLE
PointInstancer::InvisId incorrectly hiding zero-th ID.

### ISSUE THREAD

**Issue by curtisblack** [PixarAnimationStudios/USD#1411]
The implementation of both `VisId` and `InvisId` construct an array of size one, then they _append_ the ID argument:

https://github.com/PixarAnimationStudios/USD/blob/d8a405a1344480f859f025c4f97085143efacb53/pxr/usd/usdGeom/pointInstancer.cpp#L501

https://github.com/PixarAnimationStudios/USD/blob/d8a405a1344480f859f025c4f97085143efacb53/pxr/usd/usdGeom/pointInstancer.cpp#L547

This causes the `ids` array to contain two IDs, zero and the ID specified. This then hides the zero-th ID by mistake.

**Repro**
```
auto stage = UsdStage::CreateNew("/tmp/test.usda");
auto instancer = UsdGeomPointInstancer::Define(stage, SdfPath("/Instancer"));
instancer.InvisId(1, UsdTimeCode::Default());
stage->GetRootLayer()->Save();
```

**Expected Result**
```
#usda 1.0

def PointInstancer "Instancer"
{
    int64[] invisibleIds = [1]
}
```

**Actual Result**
```
#usda 1.0

def PointInstancer "Instancer"
{
    int64[] invisibleIds = [0, 1]
}
```

**Comment by jilliene** [comment]
Filed as internal issue #USD-6510

**Comment by spiffmon** [comment]
Thank you, @curtisblack !  It looks like we don't yet use those methods anywhere, which is why we didn't notice these egregious errors... not even in a test!  We'll add test coverage as part of the fix.
