### ISSUE TITLE
Crash updating a point instancer

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1417]
### Description of Issue
When viewing a point instancer through hydra, updating the point instancer to both deactivate a prototype primitive and set a constant primvar on an ancestor of the prototype in the same update cycle will cause a crash. This happens in the hydra code for determining the dirty prims/bits to send to the render delegate (so is not specific to any particular render delegate).

### Steps to Reproduce
1. Use usdview to open ptinstance1.usda from the following zip file:
[ptinstance.zip](https://github.com/PixarAnimationStudios/USD/files/5713671/ptinstance.zip)

2. In the interpreter window, run:
l = Sdf.Layer.FindOrOpen("ptinstance2.usda")
usdviewApi.stage.GetRootLayer().TransferContent(l)

3. usdview will crash.

### Package Versions
tested with 20.08, and current dev branch

**Comment by jtran56** [comment]
Filed as internal issue #USD-6522

**Comment by sunyab** [comment]
The fix for this issue was merged in commit 85e9400b3853 and released in 21.05. Closing, thanks!
