### ISSUE TITLE
Failure to install JPEG Dependency

### ISSUE THREAD

**Issue by Akhilesh09** [PixarAnimationStudios/USD#1422]
### Description of Issue
cmake fails to install the JPEG Dependency. Can someone help me figure out what to do about the missing file.

### Steps to Reproduce
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>python USD\build_scripts\build_usd.py --openvdb --ptex --openimageio --opencolorio --ptex --alembic --hdf5 --prman --prman-location "C:\Program Files\Pixar" --tests --tutorials --examples  "C:\USD"

Building with settings:
  USD source directory          C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\USD
  USD install directory         C:\USD
  3rd-party source directory    C:\USD\src
  3rd-party install directory   C:\USD
  Build directory               C:\USD\build
  CMake generator               Default
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             On
      OpenVDB support:          On
      OpenImageIO support:      On
      OpenColorIO support:      On
      PRMan support:            On
    UsdImaging                  On
      usdview:                  On
    Python support              On
      Python 3:                 Off
    Documentation               Off
    Tests                       On
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              On
      HDF5 support:             On
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  zlib, boost, TBB, HDF5, OpenEXR, Alembic, Ptex, GLEW, OpenSubdiv, Blosc, OpenVDB, JPEG, TIFF, PNG, OpenImageIO, OpenColorIO
STATUS: Installing zlib...
STATUS: Installing boost...
STATUS: Installing TBB...
STATUS: Installing HDF5...
STATUS: Installing OpenEXR...
STATUS: Installing Alembic...
STATUS: Installing Ptex...
STATUS: Installing GLEW...
STATUS: Installing OpenSubdiv...
STATUS: Installing Blosc...
STATUS: Installing OpenVDB...
STATUS: Installing JPEG...
2021-01-02 19:48
cmake -DCMAKE_INSTALL_PREFIX="C:\USD" -DCMAKE_PREFIX_PATH="C:\USD" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 15 2017 Win64"   "C:\USD\src\libjpeg-turbo-1.5.1"
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
  The OLD behavior for policy CMP0022 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 1.5.1, BUILD = 20210102
-- Arithmetic encoding support enabled
-- Arithmetic decoding support enabled
-- TurboJPEG C wrapper enabled
-- TurboJPEG Java wrapper disabled
-- In-memory source/destination managers enabled
-- 64-bit build
-- Install directory = C:/USD
-- Compiler flags = /DWIN32 /D_WINDOWS /W3 /MT /O2 /Ob2 /DNDEBUG
-- Linker flags = /machine:x64 /INCREMENTAL:NO
-- Building x86_64 SIMD extensions
-- Configuring done
-- Generating done
-- Build files have been written to: C:/USD/build/libjpeg-turbo-1.5.1
2021-01-02 19:48
cmake --build . --config Release --target install -- /M:8
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/USD/src/libjpeg-turbo-1.5.1/CMakeLists.txt
  Generating Release/jfdctflt-sse-64.obj
  Building Custom Rule C:/USD/src/libjpeg-turbo-1.5.1/CMakeLists.txt
  Traceback (most recent call last):
    File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
      "__main__", fname, loader, pkg_name)
    File "c:\python27\lib\runpy.py", line 72, in _run_code
      exec code in run_globals
    File "C:\Python27\Scripts\nasm.exe\__main__.py", line 7, in <module>
    File "c:\python27\lib\site-packages\nasm\console.py", line 8, in main
      with open(sys.argv[1]) as f:
  IOError: [Errno 2] No such file or directory: '-fwin64'
  rdjpgcom.c
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\USD\build\libjpeg-turbo-1.5.1\simd\simd.vcxproj]
  Building Custom Rule C:/USD/src/libjpeg-turbo-1.5.1/md5/CMakeLists.txt
  wrjpgcom.c
  md5cmp.c
  md5.c
  md5hl.c
  Generating Code...
  rdjpgcom.vcxproj -> C:\USD\build\libjpeg-turbo-1.5.1\Release\rdjpgcom.exe
  wrjpgcom.vcxproj -> C:\USD\build\libjpeg-turbo-1.5.1\Release\wrjpgcom.exe
  md5cmp.vcxproj -> C:\USD\build\libjpeg-turbo-1.5.1\md5\Release\md5cmp.exe

ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:8'
See C:\USD\build\libjpeg-turbo-1.5.1\log.txt for more details.
### System Information (OS, Hardware)
Windows 10
VS 2017

**Comment by meshula** [comment]
You seem to have the nasm package installed (https://pypi.org/project/nasm/), as evidenced by this message: ```File "c:\python27\lib\site-packages\nasm\console.py", line 8, in main.``` It seems to be overriding, in your path, the nasm assembler (https://www.nasm.us) turboJpeg needs to compile. nasm, the python package targets 6502, and nasm targets x86. The documentation for turboJpeg seems to indicate that nasm has to be resolved on the PATH, and doesn't seem to offer another mechanism for overriding PATH resolution.

**Comment by Akhilesh09** [comment]
So is the issue that the nasm assembler targets x86 and not x64? I'm not sure how to do a PATH resolution for it. 
The path for Python (which is the same for the nasm module) is already added to the PATH so it should be able to find the nasm python .exe.

**Comment by meshula** [comment]
Somehow there's a nasm installed in your python site-packages, and it is not compatible with the nasm turboJpeg needs, which is why it is reporting that it doesn't understand the command line arguments the usd build is giving it. I did a search to find out where site-packages/nasm/console.py comes from, because I see that file in your log. It is definitely coming from another nasm program, which only compiles code for the 6502 processor, as used in the Apple 2, or Commodore 64, or Super Nintendo. If you didn't intend to have that installed, it's possible you installed nasm by typing ```pip install nasm``` which will give you the wrong one. You will need to use pip to uninstall it, and if USD still doesn't build, install the correct nasm using an official installer, which you can find here:  https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/

**Comment by Akhilesh09** [comment]
Yes that worked. Thanks so much!

**Comment by meshula** [comment]
Glad that solved it :) Happy building!
