### ISSUE TITLE
build error on centos7

### ISSUE THREAD

**Issue by sjmilner** [PixarAnimationStudios/USD#1423]
[log.txt](https://github.com/PixarAnimationStudios/USD/files/5767878/log.txt)
### Description of Issue
Running **python USD/build_scripts/build_usd.py /usr/local/USD** causes failure when building usd:

../USD/pxr/base/tf/hash.h:220:9: error: ‘class pxrInternal_v0_20__pxrReserved__::Tf_HashState’ has no member named ‘_Append’
gmake[2]: *** [pxr/base/tf/CMakeFiles/tf.dir/noticeRegistry.cpp.o] Error 1

ERROR: Failed to run 'cmake --build . --config Release --target install -- -j12'

### System Information (OS, Hardware)
centos 7 
3.10.0-1160.11.1.el7.x86_64
gcc 4.8.5

I've installed all the dependancies I can think of. This was a fresh install of centos 7, updated and nvidia quadro driver installed prior to USD install

**Comment by rlei-weta** [comment]
Hi @sjmilner,

In the log, there were earlier errors such as:
```
/home/client/Downloads/usd/USD/pxr/base/tf/hash.h:44:1: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 std::enable_if_t<std::is_integral<T>::value>
```

`std::enable_if_t` was added in C++14.  You'll be in a better spot using a newer compiler with full support for C++14.  gcc-6.1 has C++14 enabled by default.

You can also refer to [VERSIONS.md](https://github.com/PixarAnimationStudios/USD/blob/release/VERSIONS.md#tested) for tried and tested versions of dependencies.

**Comment by sjmilner** [comment]
thank you very much, I installed a newer gcc and re-built - everything went through fine this time

thanks again
