### ISSUE TITLE
Shader attribute value change causes the bound Rprims to be recreated

### ISSUE THREAD

**Issue by huidong-chen** [PixarAnimationStudios/USD#1427]
### Description of Issue

When editing shader attribute value (e.g. inputs:diffuseColor of USDPreviewSurface), the Rprims bound with the material will be recreated, leading to maximum update of all relevant geometric data which is inefficient. (more details at https://groups.google.com/g/usd-interest/c/WH6DgLDwNvE)

### Steps to Reproduce
1. Create a usda file and save.
```
#usda 1.0

def Xform "xform1" 
{
    double3 xformOp:translate = (0.0, 0.0, 0.0)
    uniform token[] xformOpOrder = ["xformOp:translate"]

    def Sphere "sphere1"
    {
        double radius = 2
        float3[] extent = [(-2, -2, -2), (2, 2, 2)]
        rel material:binding = </xform1/material1>
    }

    def Material "material1"
    {
        token outputs:displacement.connect = </xform1/material1/usdPreviewSurface1.outputs:displacement>
        token outputs:surface.connect = </xform1/material1/usdPreviewSurface1.outputs:surface>

        def Shader "usdPreviewSurface1"
        {
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor = (1, 0, 0)
            float inputs:opacity = 1
            token outputs:surface
        }
    }
}

```
2. Load the usda file with USDView
3. Attach debugger and set breakpoints at HdRprim ctor and dtor
4. Select the `/xform1/material1/usdPreviewSurface1.inputs:diffuseColor`
5. Edit the value with Python script: `usdviewApi.property.Set((0,1,0))`

Then the breakpoints will be hit in the debugger.

**Comment by huidong-chen** [comment]
The issue seems to have been fixed in 20.11. I reproduced it on 20.08, but not on 20.11.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6539

**Comment by huidong-chen** [comment]
I've confirmed this is a duplicate issue of https://github.com/PixarAnimationStudios/USD/issues/1250. Please close.

**Comment by c64kernal** [comment]
Thanks so much for verifying and getting back to us. Appreciate it.
