### ISSUE TITLE
maya plugin: export sub-frame sampling for motion blur

### ISSUE THREAD

**Issue by chadrik** [PixarAnimationStudios/USD#143]
Creating a ticket to track this issue.  

[This discussion](https://groups.google.com/forum/#!topic/usd-interest/P7FL9NmD4YA) on usd-interest covers the details.

@spiffmon I'm curious what you decided in terms of controls.  Our requirement is that we can sample at X-.25, X, X+.25 at each frame X.  That can be achieved with explicit float offsets (e.g. -0.25, 0.0, and 0.25), or an integer sampling rate *plus* a window scale (e.g. 3 & 0.5).

**Comment by spiffmon** [comment]
@sdao just implemented this internally, which should make it to the dev-branch shortly.  Here's the documentation (short answer: list of explicit float, per-frame offsets):

> -frameSample double (multi):  Specifies sample times used to multi-sample frames during animation export, where 0.0 refers to the integer frame time. For example, specifying frameSamples of -0.1 and 0.2 and a frameRange of [1, 3] will export animation at times 0.9, 1.2; 1.9, 2.2; 2.9, 3.2. Note that the integer frame is not itself included; if you specify frameSamples of -0.1, 0.0, and 0.2, and a frameRange of [1, 3], then you would get animation samples at times 0.9, 1.0, 1.2; 1.9, 2.0, 2.2; 2.9, 3.0, 3.2. Specifying only a frameSample of 0.0 is equivalent to not specifying any frameSamples, in which case you would only get integer frames in the frameRange, e.g. for a frameRange of [1, 3], you would just get 1.0; 2.0; 3.0.

**Comment by chadrik** [comment]
Perfect

**Comment by jtran56** [comment]
Filed as it internal issue #141640.

**Comment by sunyab** [comment]
I believe this has been addressed by commit 58be4b43cd14bbd77bc2463fa74618c739003e4d in the dev branch. Marking as pending release.

**Comment by sunyab** [comment]
This has been merged into release 0.7.3.
