### ISSUE TITLE
[usdview] Display selected prim's auto-applied API schemas

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1431]
Hello!!

In _usdview_, it would be useful to display the selected prim's auto-applied/built-in API schemas.  

Currently, we can visualize explicitly applied API schemas in the metadata panel but that does not include the built-in ones.

Original usd-interest thread:
https://groups.google.com/g/usd-interest/c/bCWeTL_jBC8/m/arkT7Np7DAAJ

**Comment by jilliene** [comment]
Filed as internal issue #USD-6547
