### ISSUE TITLE
blender to usd: lost mappings and fps low

### ISSUE THREAD

**Issue by uscyoyo** [PixarAnimationStudios/USD#1432]
Hi I'm new to usd, when I learn to use it I encounter some questions:

when I use Blender to export file as usd file, all image mapping are lost so the usd file doesn't show any image mappings.

the file in blender can get to 30fps but the converted usd file can only get around 23fps in usdview

when I export large blender file(around 13 million faces) to usd file, usdview failed to open the file. Another file with fewer faces(but still a lot) can be opened but rotated really slow. I'm wondering what's the maximum faces/vertices can usd handle? If converting blender file to usd file is not a good idea(may cause some potential problem), how/where can I find large usd source to try?

Thx a lot.

**Comment by uscyoyo** [comment]
Hi I'm new to usd, when I learn to use it I encounter some questions:

1. when I use Blender to export file as usd file, all image mapping are lost so the usd file doesn't show any image mappings.

2. the file in blender can get to 30fps but the converted usd file can only get around 23fps in usdview

3. when I export large blender file(around 13 million faces) to usd file, usdview failed to open the file. Another file with fewer faces(but still a lot) can be opened but rotated really slow. I'm wondering what's the maximum faces/vertices can usd handle? If converting blender file to usd file is not a good idea(may cause some potential problem), how/where can I find large usd source to try?

Thx a lot.

**Comment by meshula** [comment]
The import and export of USD in Blender is new, and there's still rough edges! (https://docs.blender.org/manual/en/latest/files/import_export/usd.html) It might be an idea to ask the question in the Blender developer forums to get direct feedback from the Blender developers ~ (https://devtalk.blender.org/)

If you do, maybe drop a link back here, because I'm sure many people will have the same questions as you!

**Comment by jilliene** [comment]
Filed as internal issue #USD-6548

**Comment by spiffmon** [comment]
Closing this Issue, as there's not much we can do about it here, but please do follow @meshula 's advice on updating if you get answers from the Blender folks, @uscyoyo !
