### ISSUE TITLE
[CHANGELOG] Small typo for enabling Ar 2.0

### ISSUE THREAD

**Issue by rlei-weta** [PixarAnimationStudios/USD#1433]
Hello,

In the [CHANGELOG.md on dev](https://github.com/PixarAnimationStudios/USD/blob/dev/CHANGELOG.md#usd), there is a small typo in the option for enabling Ar 2.0 as part of the build.

It should be `PXR_USE_AR_2=ON` instead of `PXR_USD_AR_2=ON`.

Thanks for putting together this release!

**Comment by c64kernal** [comment]
Thanks for catching that @rlei-weta !

**Comment by tallytalwar** [comment]
Thanks, this was included in the release.
