### ISSUE TITLE
usdview AOVs broken since 20.11

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1437]
### Description of Issue
AOVs other than Color do not work in usdview in 20.11 and 21.2:

Integers produce black (and GL errors in 20.11). The "show prim id" in Storm produces what I think is the desired image that has red shading. Previous patches pseudo-colored integer aov's by multiplying the index by a large number to get the 8r8g8b color. It would also be nice if the Storm "show prim id" and other renders primId were unified into the same menu item.

Single floating-point values produce red and have lost attempts to normalize the values. Storm's "depth" setting shows white instead. Ideally this should show a gray-scale image with some range containing the majority of the pixels scaled to 0-1.

Double-floating-piont values (such as uv) are no longer showing a pseudo-color blue channel for the integer portion, which was helpful for identifying UDIM tiles.

Three-floating-point values are not getting sRGB color correction (visible by using primvars:displayColor). This was useful in the common case where several AOV's are summed to get the color image in order to judge the contribution from each aov.

### Steps to Reproduce
Run usdview viewing the kitchen or some other simple scene, select the Embree renderer. Try all the entries in the AOV menu, also try "primvars:displayColor" to see a color AOV, and compare depth with the Storm renderer, and compare primId with "show prim Id" in Storm renderer.

### System Information (OS, Hardware)
Linux

### Package Versions
>= 20.11

**Comment by spitzak** [comment]
The colorization of integers I used in the previous patch for this:

```
            int32_t t = (idBuffer[i] + 1) * 0xb17223; // prime number near ln(2)*2^24
            dest[i*4+0] = (uint8_t)(t & 0xff);
￼           dest[i*4+1] = (uint8_t)((t >> 8) & 0xff);
￼           dest[i*4+2] = (uint8_t)((t >> 16) & 0xff);
```

**Comment by jilliene** [comment]
Filed as internal issue #USD-6553
