### ISSUE TITLE
UsdImagingPointInstancerAdapter::Get fails to return most non-primvar attributes

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1439]
### Description of Issue

Calling UsdImagingPointInstancerAdapter::Get to get a non-primvar attribute (such as velocities, acceleration, and that's ignoring custom attributes) fails to return a value.

The problem lies with this code:
https://github.com/PixarAnimationStudios/USD/blob/dc710925675f7f58f7a37f6c18d046a687b09271/pxr/usdImaging/usdImaging/pointInstancerAdapter.cpp#L1860

Which, unlike UsdImagingPrimAdapter::SamplePrimvar, does not fall back to grabbing the attribute as a regular attribute. Alternatively, at least the rest of the attributes in the pointinstancer schema (velocities, acceleration, and angularVelocities) should be handled as special cases like scale and other pointinstancre attributes are.

### Steps to Reproduce
1. In a render delegate's HdInstancer::Sync method, call: `GetDelegate()->Get(GetId(), HdTokens->velocities);`
2. Even if the point instancer has a velocities attribute, nothing will be returned by the above call.

### Package Versions
USD 21.02

**Comment by jilliene** [comment]
Filed as internal issue #USD-6555
