### ISSUE TITLE
USD can't write layers when executable launched from beneath a Windows junction

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1440]
### Description of Issue
Related to #1377, but with a somewhat different cause. When a USD executable is launched from within "D:/foo", where "D:/foo" is a symlink or junction to "F:/foo", and then tries to write to "D:/foo/bar.usda", it fails with a permission error (which isn't really a permission error).

### Steps to Reproduce
1. Create a junction on Windows from D:/foo to F:/foo.
2. In a command prompt, navigate to D:/foo, and launch python.
3. Run the following:
from pxr import Sdf
l = Sdf.Layer.CreateAnonymous()
l.Export("d:/foo/bar.usda")
4. The last line fails with `'Insufficient permissions to write to destination directory 'f:\foo\foo''`

### System Information (OS, Hardware)
Windows

### Package Versions
USD 20.08 and 21.02

**Comment by jilliene** [comment]
Filed as internal issue #USD-6556

**Comment by sunyab** [comment]
Closing old issue, this was addressed by #1441.
