### ISSUE TITLE
Incorrect rotations from UsdGeomPointInstancer::ComputeInstanceTransformsAtTime

### ISSUE THREAD

**Issue by cameronwhite** [PixarAnimationStudios/USD#1442]
### Steps to Reproduce
1. From the [attached archive](https://github.com/PixarAnimationStudios/USD/files/5919489/instancer_issue.tar.gz), open the scene with `usdview instancer.usda --camera camera1` 
2. In the interpreter, run `import instancer_test` and then `instancer_test.compute_transforms(usdviewApi.stage)`
3. From the printouts and the new prims being displayed in red, it should be noticeable that the transforms from `ComputeInstanceTransformsAtTime()` do not match the original rotations of the items in the point instancer

### Description of Issue
After some investigating, I think the issue is here: https://github.com/PixarAnimationStudios/USD/blob/dc710925675f7f58f7a37f6c18d046a687b09271/pxr/usd/usdGeom/pointInstancer.cpp#L960

`GfRotation::SetQuat` assumes that the input quaternion is already normalized when converting to axis-angle. This isn't the  case after the implicit conversion of the `GfQuath` to `GfQuatd`, which can be seen by adding the following debug output to the above code:
```
std::cerr << orientations[instanceId] << std::endl;
std::cerr << orientations[instanceId].GetLength() << std::endl;
GfQuatd orient = orientations[instanceId];
std::cerr << orient << std::endl;
std::cerr << orient.GetLength() << std::endl;
orient.Normalize();
std::cerr << orient << std::endl;
std::cerr << orient.GetLength() << std::endl;
```

I can submit a PR for this, but wanted to bring it up for discussion first. It's easy enough to explicitly normalize here, but perhaps this implicit conversion should be prevented since it's an easy trap to fall into?

### System Information (OS, Hardware)
Tested on USD 20.08 (Houdini 18.5) and also on a recent build from the `dev` branch

**Comment by jilliene** [comment]
Filed as internal issue #USD-6558

**Comment by spiffmon** [comment]
Hi @cameronwhite , sorry it took us some time to have a look.  GfRotation *does* renormalize the quaternion form which it is initialized, so the implicit conversion should not be a huge problem in this codepath.  We do note that the input quath's are not even themselves really unit length, however, and we're coming to the sinking conclusion that there may just be cases where 16 bits is not enough precision, even for numbers in the range of 0..1, if they are representing rotations of very long things.

We wouldn't rule out the possibility of adding an alternate, 32-bit quaternion encoding to the schema, which you could use when you hit precision issues (and the extra storage isn't a problem), but that would be a change we'd want to discuss with the community.

**Comment by cameronwhite** [comment]
With the changes in #1505 this is now behaving as expected, but this ticket could remain open for the suggestion of allowing 32-bit quaternions in the schema

**Comment by spiffmon** [comment]
@cameronwhite , it would actually make it easier to track to have a new Issue specifically with that request, which can reference this Issue for context.  Would also be good to then maybe use usd-interest to gouge how much interest there is in it?

**Comment by cameronwhite** [comment]
No problem, I'll close this one! Having 32-bit quaternions in the schema isn't a priority for us currently, as far as I know
