### ISSUE TITLE
LZ4 test functions exposed, causing linker errors

### ISSUE THREAD

**Issue by sybrenstuvel** [PixarAnimationStudios/USD#1447]
### Description of Issue

Blender cannot link against USD library version 21.02, because the latter exports the names `LZ4_compress_forceExtDict` and `LZ4_decompress_safe_forceExtDict`.

This issue was likely introduced in commit df4869230521cfb2c60701e7d531a1706495aee3. As you can see in the commit message of 4da033bd0778e2bd8a27f6e2d903bf7ac2ae51eb, the LZ4 symbols are supposed to be encapsulated in a C++ namespace. However, since df4869230521cfb2c60701e7d531a1706495aee3 these two symbols are marked as `export "C"` and thus collide with other libraries.

### Steps to Reproduce
1. Build USD as static library
2. Run `nm -C libusd_m.a | grep LZ4`
3. See that  `LZ4_compress_forceExtDict` and `LZ4_decompress_safe_forceExtDict` are listed.

### System Information (OS, Hardware)

Kubuntu Linux 20.04 and CentOS 7

### Package Versions

USD 21.02

### Build Flags

We build with these extra flags, to ensure that USD uses the correct precompiled libraries used to build Blender:
```
  -DBoost_COMPILER:STRING=${BOOST_COMPILER_STRING}
  -DBoost_USE_MULTITHREADED=ON
  -DBoost_USE_STATIC_LIBS=ON
  -DBoost_USE_STATIC_RUNTIME=OFF
  -DBOOST_ROOT=${LIBDIR}/boost
  -DBoost_NO_SYSTEM_PATHS=ON
  -DBoost_NO_BOOST_CMAKE=ON
  -DTBB_INCLUDE_DIRS=${LIBDIR}/tbb/include
  -DTBB_LIBRARIES=${LIBDIR}/tbb/lib/${LIBPREFIX}${TBB_LIBRARY}${LIBEXT}
  -DTbb_TBB_LIBRARY=${LIBDIR}/tbb/lib/${LIBPREFIX}${TBB_LIBRARY}${LIBEXT}
  # USD wants the tbb debug lib set even when you are doing a release build
  # Otherwise it will error out during the cmake configure phase.
  -DTBB_LIBRARIES_DEBUG=${LIBDIR}/tbb/lib/${LIBPREFIX}${TBB_LIBRARY}${LIBEXT}

  # This is a preventative measure that avoids possible conflicts when add-ons
  # try to load another USD library into the same process space.
  -DPXR_SET_INTERNAL_NAMESPACE=usdBlender

  -DPXR_ENABLE_PYTHON_SUPPORT=OFF
  -DPXR_BUILD_IMAGING=OFF
  -DPXR_BUILD_TESTS=OFF
  -DBUILD_SHARED_LIBS=OFF
  -DPYTHON_EXECUTABLE=${PYTHON_BINARY}
  -DPXR_BUILD_MONOLITHIC=ON
  -DPXR_BUILD_USD_TOOLS=OFF

  -DCMAKE_DEBUG_POSTFIX=_d
  # USD is hellbound on making a shared lib, unless you point this variable to a valid cmake file
  # doesn't have to make sense, but as long as it points somewhere valid it will skip the shared lib.
  -DPXR_MONOLITHIC_IMPORT=${BUILD_DIR}/usd/src/external_usd/cmake/defaults/Version.cmake
```

**Comment by jilliene** [comment]
Filed as internal issue #USD-6563

**Comment by gitamohr** [comment]
Oof.  Sorry for the trouble here.  I'll get it fixed up.
