### ISSUE TITLE
Segmentation fault when changing complexity in usdview

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1448]
### Description of Issue

When trying to ~~run the testUsdviewSkinning test~~ change the complexity, usdview crashes with a "Segmentation Fault" error.

### Steps to Reproduce
1. Build usd-21.02 or latest dev (82dd40ad)
2. Run `ctest -V -R testUsdviewSkinning`

OR 

2. Open any .usda (even a simple cube), then change complexity from Low to Medium

### System Information (OS, Hardware)
CentOS 7

### Package Versions
usd-21.02 or latest dev (82dd40ad)

**Comment by pmolodo** [comment]
So, thanks to the wonders of `git bisect run`, I've determined that the commit that introduces the crash is 5db17347 - the one which replaces GLEW.

I'm guessing it's something to do with the fact that I'm using a very old video card (GeForce GTX 680), and I'm not supporting some extension or another which you're relying on... and that's not being detected or checked for properly.  I'll see tomorrow if I can run the test on a machine with something newer, and see if it passes.

**Comment by pmolodo** [comment]
Unfortunately, the crash still happened when testing on a more modern RTX 2020...

**Comment by pmolodo** [comment]
So, realized the crash isn't even related to skinning or UsdSkel - but just changing complexity (so OpenSubDiv, maybe?).

It's just that this test happens to change the complexity...

I verified that this happens in normal usage, outside of tests, when just changing the complexity of a basic cube for us, so this definitely became more important to us.

**Comment by c64kernal** [comment]
Thanks for raising this @pmolodo -- unfortunately I haven't been able to reproduce here... do you have a stacktrace you can share or any other kind other kind of clue so that we can help get to the bottom of this?

**Comment by pmolodo** [comment]
Here's a stack-trace I extracted by running under gdb - definitely OpenSubdiv - related...

[usd_crash_opensubdiv_glew-ectemy.txt](https://github.com/PixarAnimationStudios/USD/files/5969213/usd_crash_opensubdiv_glew-ectemy.txt)

**Comment by pmolodo** [comment]
...and here's the output from TF_DEBUG:

[usdview_crash_opensubdiv_TF_DEBUG_output.txt](https://github.com/PixarAnimationStudios/USD/files/5969230/usdview_crash_opensubdiv_TF_DEBUG_output.txt)

**Comment by davidgyu** [comment]
Hi @pmolodo thanks for the stack trace output. It looks like your build is using OpenSubdiv v3.3.3 with USD v21.02 and the problem is that you are missing GLEW initialization required for this older version of OpenSubdiv.

Switching to OpenSubdiv v3.4.3 (first OpenSubdiv release which does not require GLEW) or later should fix this problem. If that's not possible, then you'll need to call glewInit() from somewhere before calling into usdImaging.

**Comment by pmolodo** [comment]
Ah - awesome, thanks for figuring that out so quickly!

Ideally we should put a comment/note about this in either BUILDING.md or VERSIONS.md at some point, since this is now a known hard minimum... but for now, thanks again, and I'll close the ticket!

**Comment by c64kernal** [comment]
Thanks @pmolodo! VERSIONS.md should already mention that we require a minimum of 3.4.3 for OpenSubdiv... was there something else you were thinking of there?

**Comment by pmolodo** [comment]
It notes OpenSubdiv as the "tested" version, but also has this note:

```
Note that not everything here is required, see README.md for more information about which are required and which are optional for the various subsystems.
```

...so I guess I'm just saying that since we now know 3.4.3 is REQUIRED, we should have stronger wording.    (Though, if I'm perfectly honest, I probably would have still missed this.  But hopefully someone paying more attention would notice!)
