### ISSUE TITLE
Material bindings are not honored on scenegraph instances inside of point instances

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#1449]
### Description of Issue
Materials bound to point instancer prototypes are not honored by scenegraph instances within those protoypes.

### Steps to Reproduce

[grass_scatter0.zip](https://github.com/PixarAnimationStudios/USD/files/5966452/grass_scatter0.zip)

1. Unzip the attached archive.
2. Open grass_scatter0/layout/grass_scatter_layout.usda in usdview
3. The spheres all draw with no materials.
4. Select /grass_plain/tree_instancer/Prototypes/tree_1/tree_1_geo/tree_1_leaves/obj_0 in the Browser
5. in the interpreter, usdviewApi.prim.SetInstanceable(False)
6. The spheres will turn blue, now honoring the bound UsdPreviewSurface

### System Information (OS, Hardware)

Windows
### Package Versions

current dev branch

### Build Flags

python build_scripts\build_usd.py _install

**Comment by jilliene** [comment]
Filed as internal issue #USD-6570
