### ISSUE TITLE
maya plugin: default readAnimData to True

### ISSUE THREAD

**Issue by nxkb** [PixarAnimationStudios/USD#145]
### Description of Issue
It seems like in most cases when importing a usd file that contains animation, you would want to also grab that animation. Importing an animated usd file without animation would be the exception rather than the rule.

Would it be a good idea to default this option to True? Unless there is a substantial cost when there is no animation in the file, I believe this would improve a user's experience and remove the potential pitfall of forgetting that flag/checkbox.

Let me know your thoughts, and if there are other considerations here...

**Comment by jtran56** [comment]
Filed as internal issue #141762.

**Comment by sunyab** [comment]
Wanted to note that commit e6004e64e4dee21d92ee00d964c0878ed006a018 makes the USD import UI default readAnimData to true, but it does not affect the script command. There is discussion about doing so in the referenced PR above, so I'm leaving this open for now.

**Comment by sunyab** [comment]
This was released in version 0.7.6, see commit cf7b562.
