### ISSUE TITLE
Storm - PointInstancer disappears and HdSt throws errors if the PointInstancer has 6+ primvars

### ISSUE THREAD

**Issue by ablev-dwa** [PixarAnimationStudios/USD#1452]
### Description of Issue

If a PointInstancer has 6 or more primvars, it will not display in Storm, and throws a ton of errors in the terminal, like:

```
ERROR: Usdview encountered an error while rendering.
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 247 in file /usr/pic1/usd/cmake/pxr/imaging/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /scatter/Geometry/triangles.proto0_triangle_id0.'
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 272 in file /usr/pic1/usd/cmake/pxr/imaging/hdSt/drawBatch.cpp : 'Failed verification: ' res ''
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_IndirectDrawBatch::ExecuteDraw' at line 1114 in file /usr/pic1/usd/cmake/pxr/imaging/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
Warning: in Link at line 342 of /usr/pic1/usd/cmake/pxr/imaging/hdSt/glslProgram.cpp -- Failed to link shader: Fragment info
-------------
0(462) : error C5058: no buffers available for bindable storage buffer 

Warning: in Link at line 342 of /usr/pic1/usd/cmake/pxr/imaging/hdSt/glslProgram.cpp -- Failed to link shader: Fragment info
-------------
0(462) : error C5058: no buffers available for bindable storage buffer 
```

If a PointInstancer has 5 or fewer primvars, everything seems to work fine.

This problem also significantly degrades playback performance. It feels like a regression of a previously fixed problem, https://github.com/PixarAnimationStudios/USD/issues/943 - that was solved for a while, but seems to have resurfaced in 21.02.

### Steps to Reproduce
1. Open pointinstancer_selection.usda in usdview from pointinstancer_selection.zip
2. Set purpose to "render"
3. Notice that the "/scatter/Geometry/triangles" PointInstancer does not display. 
4. Notice when tumbling in usdview, performance is degraded

### System Information (OS, Hardware)
CentOS7
NVidia Quadro M5000 Driver v418.43

### Package Versions
USD-21.02

### Build Flags
python build_scripts/build_usd.py /usr/pic1/usdtest --tests

**Comment by ablev-dwa** [comment]
[pointinstancer_selection.zip](https://github.com/PixarAnimationStudios/USD/files/5974355/pointinstancer_selection.zip)

**Comment by davidgyu** [comment]
Sorry for the regression!

We've checked in an updated fix for this bug and that fix is part of this week's dev push (See [faba5dd](https://github.com/PixarAnimationStudios/USD/commit/faba5dd1f0f276b16d3fb95fb9362ef179e5c76d)) We've also added a test to our local test suite, so hopefully the problem will stay fixed this time.

**Comment by ablev-dwa** [comment]
That's great news, thanks @davidgyu !

**Comment by ablev-dwa** [comment]
I have cherry-picked that change into our 21.02 build and it works great. Thanks again!
