### ISSUE TITLE
VULKAN: Build error on windows (and missing PCH)

### ISSUE THREAD

**Issue by furby-tm** [PixarAnimationStudios/USD#1456]
Vulkan does not build on windows, it is missing the optional library to build in `hgiInterop` here:
```cmake
if (PXR_ENABLE_METAL_SUPPORT)
    add_compile_options(-x objective-c++)
    FIND_LIBRARY(COREVIDEO_LIBRARY CoreVideo)
    list(APPEND optionalLibraries garch)
    list(APPEND optionalLibraries ${COREVIDEO_LIBRARY} hgiMetal)
    list(APPEND optionalCppFiles metal.mm)
    list(APPEND optionalPrivateHeaders metal.h)
else()
    list(APPEND optionalLibraries garch)
    list(APPEND optionalLibraries hgiGL)
    list(APPEND optionalCppFiles opengl.cpp)
    list(APPEND optionalPrivateHeaders opengl.h)
endif()

# Missing these
if (PXR_ENABLE_VULKAN_SUPPORT)
  list(APPEND optionalLibraries hgiVulkan)
  list(APPEND optionalCppFiles vulkan.cpp)
  list(APPEND optionalPrivateHeaders vulkan.h)
endif()
```

Additionally, when including the vulkan library to build above, it also does not have it's required `pch.h` file to build.

Attempting to create a custom `pch.h` so that the build can attempt results in the following error:
```bash
shaderCompiler.cpp(36,10): fatal error C1083: Cannot open include file: 'OGLCompilersDLL/InitializeDll.h': No such file or directory [C:\Users\tyler\dev\lib\win64_vc15\usd\build\USD\pxr\imaging\hgiVulkan\hgiVulkan.vcxproj]
```

![image](https://user-images.githubusercontent.com/18516968/108471471-acf6cf80-7248-11eb-81f0-7535c4fc30b0.png)

Additionally, the version also seems incorrect, as version `1.2.135.0` does not contain the required library `GenericCodeGen`.

Any thoughts? Thanks!

**Comment by davidgyu** [comment]
Sorry about the build breakage. It's still early days for our hgiVulkan
implementation, and you are correct about all of these:
  - we should add a pch.h file for hgiVulkan
  - when it's ready for use, we'll need to hook up vulkan to the build in
hgiInterop
  - we have a task open to support more recent versions of the Vulkan SDK
(including migrating our on-line shader compilation to shaderc).

These are several of the reasons why we haven't yet exposed vulkan support
in build_usd.py

We should be able to address some of these issues, but full support for
Vulkan is still a way off and we don't have a target date for when we
expect that to get pushed to the dev branch.

Thanks!
-David

**Comment by furby-tm** [comment]
No worries! Just excited to try this stuff out. Looking forward to vulkan support in a future update.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6578

**Comment by c64kernal** [comment]
Thanks for filing, like @davidgyu said, this is currently not supported, but we'll be sure to address Windows issues when we take on supporting Vulkan. Closing this for now.
