### ISSUE TITLE
[usdview] CompileShader error on Linux : extension `GL_ARB_bindless_texture' unsupported in vertex shader

### ISSUE THREAD

**Issue by johhnry** [PixarAnimationStudios/USD#1458]
### Description of Issue

Running `usdview cube.usda` gives me those errors : 

```shell
Warning: in CompileShader at line 262 of USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (GL_VERTEX_SHADER): 0:9(12): error: extension `GL_ARB_bindless_texture' unsupported in vertex shader

ERROR: Usdview encountered an error while rendering.
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_IndirectDrawBatch::_GPUFrustumNonInstanceCulling' at line 1526 in file USD/pxr/imaging/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 246 in file USD/pxr/imaging/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /Cube.'
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 272 in file USD/pxr/imaging/hdSt/drawBatch.cpp : 'Failed verification: ' res ''
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_IndirectDrawBatch::ExecuteDraw' at line 1114 in file USD/pxr/imaging/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
```

`cube.usda` being this file : 

```c
#usda 1.0

def Cube "Cube"
{
  color3f[] primvars:displayColor = [ (0.5, 0.5, 0.5) ]
}
```

Is this related to USD or my GPU is not supporting some some OpenGL extensions?

### Steps to Reproduce

1. Compile USD 21.02 : 
```bash
USD/build $ cmake \
  -DCMAKE_INSTALL_PREFIX=../install \
  -DBOOST_ROOT=../../boost_1_70_0 \
  -DPTEX_LOCATION=../../ptex/install \
  -DPTEX_INCLUDE_DIR=../../ptex/install/include \
  -DPTEX_LIBRARY=../../ptex/install/lib/libPtex.so \
  -DPYTHON_INCLUDE_DIR=/usr/include/python3.8 \
  -DTBB_ROOT_DIR=../../oneTBB/ \
  -DBOOST_ROOT=../../boost_1_70_0 \
  -DPXR_USE_PYTHON_3=ON \
  ..
``` 
2. Run usdview with `$ usdview cube.usda`

### System Information (OS, Hardware)

- OS : `Pop!_OS 20.04 LTS x86_64`
- CPU: `Intel i7-7500U (4) @ 3.500GHz`
- GPU: `Intel HD Graphics 620`
- OpenGL version string: `4.6 (Compatibility Profile) Mesa 20.3.2`

### Package Versions

- USD: `21.02`
- PyOpenGL: `3.1.5`
- PySide2: `5.15.2`

**Comment by davidgyu** [comment]
Hi Joseph,

Can you try running usdview after setting the environment variables:
    GLF_ENABLE_BINDLESS_TEXTURE=0
    GLF_ENABLE_BINDLESS_SHADOW_TEXTURES=0

The missing GL extension is the one mentioned in the error messages:
GL_ARB_bindless_texture which is an optional extension for GL versions 4.5
and 4.6 and which does not appear to be implemented by the Intel HD
graphics drivers.

Thanks!
-David

**Comment by johhnry** [comment]
Hi David,

Thanks for the answer!

This is the result of running `usdview` with the environment variables : 

```shell
$ env GLF_ENABLE_BINDLESS_TEXTURE=0 GLF_ENABLE_BINDLESS_SHADOW_TEXTURES=0 usdview files/cube.usda

###############################################################################
#  GLF_ENABLE_BINDLESS_TEXTURE is overridden to 'false'.  Default is 'true'.  #
###############################################################################
#######################################################################################
#  GLF_ENABLE_BINDLESS_SHADOW_TEXTURES is overridden to 'false'.  Default is 'true'.  #
#######################################################################################
Warning: in CompileShader at line 262 of USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (GL_GEOMETRY_SHADER): 0:537(2): error: only precision qualifiers may be applied to structure members
0:538(2): error: only precision qualifiers may be applied to structure members

Warning: in CompileShader at line 262 of USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (GL_GEOMETRY_SHADER): 0:537(2): error: only precision qualifiers may be applied to structure members
0:538(2): error: only precision qualifiers may be applied to structure members

ERROR: Usdview encountered an error while rendering.
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 246 in file USD/pxr/imaging/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /Cube.'
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 272 in file USD/pxr/imaging/hdSt/drawBatch.cpp : 'Failed verification: ' res ''
	Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_IndirectDrawBatch::ExecuteDraw' at line 1114 in file USD/pxr/imaging/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
Warning: in CompileShader at line 262 of USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (GL_GEOMETRY_SHADER): 0:537(2): error: only precision qualifiers may be applied to structure members
0:538(2): error: only precision qualifiers may be applied to structure members
```

Nothing show up in the window...

But it's strange because using the `displayColor` primvar attribute on a primitive is trivial to render with OpenGL using a vertex shader, am I right?

Thanks again

Joseph

**Comment by davidgyu** [comment]
For viewing simple scenes it might be sufficient to disable Hydra and use
the fixed function render engine, e.g.:
    $ usdview --renderer HydraDisabled cube.usd

As you can imagine, the Hydra Storm GL engine uses a more complicated
shader pipeline in order to support efficient instanced drawing, etc.

We think the error about precision qualifiers on struct members is a bug in
the Mesa GLSL shader compiler, and we have reports from other users hitting
the same error. Unfortunately, I'm not able to reproduce that error, but my
test system that is closest in configuration is running Windows and using
the Intel driver instead of the Mesa driver (Intel(R) HD Graphics 520,
4.5.0 - Build 24.20.100.6293).

Thanks!
-David

**Comment by johhnry** [comment]
Yes it works by disabling Hydra, didn't know that thanks!

However running `usdview` with a simple cube exported from Blender, the normals are producing weird results. 

This is the result : 

![Capture d’écran de 2021-02-21 20-32-35](https://user-images.githubusercontent.com/35373357/108636200-0b5bc200-7484-11eb-9939-4cd2bb62e001.png)

```c
#usda 1.0
(
    doc = "Blender v2.92.0 Alpha"
    metersPerUnit = 1
    upAxis = "Z"
)

def Xform "Cube"
{
    matrix4d xformOp:transform = ( (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1) )
    uniform token[] xformOpOrder = ["xformOp:transform"]

    def Mesh "Cube"
    {
        uniform bool doubleSided = 1
        int[] faceVertexCounts = [4, 4, 4, 4, 4, 4]
        int[] faceVertexIndices = [0, 4, 6, 2, 3, 2, 6, 7, 7, 6, 4, 5, 5, 1, 3, 7, 1, 0, 2, 3, 5, 4, 0, 1]
        rel material:binding = </_materials/Material>
        normal3f[] normals = [(0, -0, 1), (0, -0, 1), (0, -0, 1), (0, -0, 1), (0, -1, 0), (0, -1, 0), (0, -1, 0), (0, -1, 0), (-1, -0, 0), (-1, -0, 0), (-1, -0, 0), (-1, -0, 0), (0, 0, -1), (0, 0, -1), (0, 0, -1), (0, 0, -1), (1, -0, 0), (1, -0, 0), (1, -0, 0), (1, -0, 0), (0, 1, 0), (0, 1, 0), (0, 1, 0), (0, 1, 0)] (
            interpolation = "faceVarying"
        )
        point3f[] points = [(1, 1, 1), (1, 1, -1), (1, -1, 1), (1, -1, -1), (-1, 1, 1), (-1, 1, -1), (-1, -1, 1), (-1, -1, -1)]
        uniform token subdivisionScheme = "none"
    }
}

def "_materials"
{
    def Material "Material"
    {
        token outputs:surface.connect = </_materials/Material/previewShader.outputs:surface>

        def Shader "previewShader"
        {
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor = (0.8, 0, 0)
            float inputs:metallic = 0
            float inputs:roughness = 0.4
            token outputs:surface
        }
    }
}
```

I know that this is using a more complicated shader than the previous vertex shader but it means that I can't really visualize a simple mesh with usdview ;)

What features does the Hydra disabled mode can support?

Thanks for taking some time on this!

**Comment by davidgyu** [comment]
The funky rendering in this case is a result of the way that the HydraDisabled renderer deals with doubleSided geometry. The easiest way to work around this is to enable backface culling in the GL viewer, i.e.:
  - enable View>Cull Backfaces (GL) in usdview
or you can try changing the asset to be "doubleSided = 0"

The HydraDisabled renderer is very basic and doesn't support materials for example. It is mostly useful to get some visual feedback while inspecting scenes in usdview.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6580

**Comment by johhnry** [comment]
All right, thanks for the help!
