### ISSUE TITLE
[usdview] AlphaToCoverage broken in usdview since USD 21.02

### ISSUE THREAD

**Issue by jufrantz** [PixarAnimationStudios/USD#1460]
### Description of Issue

Hello,
We noticed that storm "alpha to coverage" transparency does not work anymore in usdview since 21.02.
I attached an usd scene [testAlphaToCoverage.tar.gz](https://github.com/PixarAnimationStudios/USD/files/6023982/testAlphaToCoverage.tar.gz). It defines geometries, and a glslfx material assigned to /all/tansp_red_cube. The glslfx impl is tagged as `defaultMaterialTag`, and a 0.5 opacity is authored. When viewing with usdview 21.02, transp_red_cube wrongly appears opaque.

### Steps to Reproduce
1. open the attached usd layer in usdview
2. In usdview ` 20.11` , tansp_red_cube appears half transparent thanks to alpha to coverage.
3. In usdview ` 21.02`, tansp_red_cube appears fully opaque. 

### System Information (OS, Hardware)

* Linux CentOS 7.4

### Package Versions

* USD 21.02

**Comment by jilliene** [comment]
Filed as internal issue #USD-6582

**Comment by clach** [comment]
Hi @jufrantz, in 21.02 ([commit here](https://github.com/PixarAnimationStudios/USD/commit/b0d356197610c2aa6569b04ef3043aca2a749691)) the `defaultMaterialTag` no longer enables "alpha to coverage" transparency. To get alpha to coverage behavior, you should use the `masked` material tag.

**Comment by jufrantz** [comment]
Hello Clach,
Thank you for the feedback.
I wrongly blamed usdview because I could still get alphaToCoverage transparency in another application. .. Actually this other app enables `GL_SAMPLE_ALPHA_TO_COVERAGE` on it's own and does not rely on this HdSt state.
We'll now use `masked` in place of `defaultMaterialTag` for these materials.
Cheers
Julien
