### ISSUE TITLE
usdview: tbb error on launching debug build of usdview / usdcat

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#147]
### Description of Issue

If you do a debug build, then attempt to launch usdview on Linux (we are using Fedora 19), we get this error:

    Assertion theMarket == this failed on line 162 of file ../../src/tbb/market.cpp
    Detailed description: Global market instance was destroyed prematurely?
    Aborted

The above was with tbb-4.3. Using tbb-2017 Update 3, we got:

    Assertion a->my_market == my_market failed on line 40 of file ../../src/tbb/arena.cpp
    Aborted

This also happens with some other tools, such as "usdcat -o" (see below).

Using "git bisect run", I tracked down the commit that introduced this issue to:

0a6fea843053d72c87885281a9f74a34aa07aaf6: Support for Windows in cmake files and related clean up.

...though I haven't yet had the chance to figure out which specific change in that commit was responsible

### Steps to Reproduce

1. make a debug build of USD (ie, use cmake -D CMAKE_BUILD_TYPE=Debug)
2. Make sure this debug build of usdcat is on the path
3. cd to: ${USD_SOURCE_ROOT}/extras/usd/tutorials/endToEnd/assets/Table
4. usdcat -o Table.maya.usda Table.maya.usd

This should generate the error shown above...

### System Information (OS, Hardware)

Linux, Fedora 19

### Package Versions

- maya-2016_5
- python-2.7
- openexr-2.2
- ptex-2.1
- opensubdiv-3.0
- double_conversion-1.1
- openimageio-1.5
- glew-1.10
- gcc-4.8.3
- alembic-1.5.8
- boost-1.55.0
- jemalloc-4.4
- tbb-4.3 (and tbb-2017.U3)

### Build Flags

    -D QT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4
    -D PXR_BUILD_ALEMBIC_PLUGIN=TRUE
    -D PXR_MAYA_TBB_BUG_WORKAROUND=TRUE
    -D ALEMBIC_DIR=${REZ_ALEMBIC_ROOT}
    -D PTEX_LOCATION=${REZ_PTEX_ROOT}
    -D PTEX_PREFER_STATIC=ON
    -D CMAKE_BUILD_TYPE=Debug
    -D PXR_BUILD_MAYA_PLUGIN=TRUE
    -D PXR_BUILD_KATANA_PLUGIN=FALSE
    -DPXR_MALLOC_LIBRARY:path=${JEMALLOC_DYNAMIC_LIBRARY}

**Comment by jtran56** [comment]
Filed as internal issue #141848.

**Comment by elrond79** [comment]
So, just figured out the exact change that introduced this issue - turning on the TBB_USE_DEBUG_BUILD cmake flag.  Specifically, if you make these changes:

```
diff --git a/cmake/defaults/Packages.cmake b/cmake/defaults/Packages.cmake
index 084cabb..b2bbeb4 100644
--- a/cmake/defaults/Packages.cmake
+++ b/cmake/defaults/Packages.cmake
@@ -42,7 +42,6 @@ find_package(DoubleConversion REQUIRED)
 
 # --TBB
 # Debug is the default in Release for some bizarro reason, turn it off.
-set(TBB_USE_DEBUG_BUILD OFF)
 find_package(TBB REQUIRED)
 
 # --OpenEXR
diff --git a/cmake/modules/FindTBB.cmake b/cmake/modules/FindTBB.cmake
index 7d6041f..baeabab 100644
--- a/cmake/modules/FindTBB.cmake
+++ b/cmake/modules/FindTBB.cmake
@@ -89,7 +89,7 @@ if(NOT TBB_FOUND)
   ##################################
   
   if(NOT DEFINED TBB_USE_DEBUG_BUILD)
-    if(CMAKE_BUILD_TYPE MATCHES "[Debug|DEBUG|debug|RelWithDebInfo|RELWITHDEBINFO|relwithdebinfo]")
+    if(CMAKE_BUILD_TYPE MATCHES "Debug|DEBUG|debug|RelWithDebInfo|RELWITHDEBINFO|relwithdebinfo")
       set(TBB_USE_DEBUG_BUILD TRUE)
     else()
       set(TBB_USE_DEBUG_BUILD FALSE)
```

...then the debug build will error.  This is a bit worrisome, as it probably means some threading objects are being cleaned up improperly, but for now, we'll just be manually setting this flag to FALSE for our internal builds...

**Comment by c64kernal** [comment]
Nice find @elrond79!  Yeah, we're going to try to track down what the underlying problem really is.  Your workaround should get you going (effectively what we used to have before the change).  Thanks again!

**Comment by elrond79** [comment]
This problem seems to have gone away for us - not sure if it's a change you guys made, the fact that we're using tbb-4.4 now (which would be odd, since I tested with a newer version, tbb-2017 Update 3 previously), or some other change in our system details over here... but since I can no longer reproduce, I'm going to close this issue.
