### ISSUE TITLE
projection not included in coordsys passed to renderer

### ISSUE THREAD

**Issue by glyphfx** [PixarAnimationStudios/USD#1474]
### Description of Issue
coordsys pointing to camera xformable does not pass perspective projection to renderer and therefore does not render paint projection as expected, according to https://graphics.pixar.com/usd/docs/Coordinate-Systems-in-USD-Proposal.html 

### Steps to Reproduce
1. set coordsys target path to camera xformable
2. add string coordsys parameter to PxrManifold3D
3. assign to prim, set perspective as projection type
4. render with pram, note the projection is not assigned correctly

### System Information (OS, Hardware)
USD 21.02, Windows, Prman 23.5

**Comment by jilliene** [comment]
Filed as internal issue #USD-6603

**Comment by spiffmon** [comment]
This is good timing, @glyphfx .  We are just gearing up to figure out how we really want to represent projections in USD, and once that’s done, it will be possible to update HdPrman to consume them properly. We’ll use this Issue to track at least the HdPrman side of things!

**Comment by spiffmon** [comment]
Per @blevin 's explanation on usd-interest, I'm going to close this per our new understanding that without a very tight set of constraints on the setup and functionality that would probably chafe the top-tier renderers, setting up projections must be done in the renderer-specific shading network, not as part of a coordinate system in the geometry.  Sorry it took us awhile to conclude this.
