### ISSUE TITLE
Pluggable file i/o for support of non-standard file systems 

### ISSUE THREAD

**Issue by tomfinegan** [PixarAnimationStudios/USD#1484]
Before I start I want to be clear that I consider this a feature request and not a bug. I've wiped out the template text since I believe USD to be working as intended at present.

USD uses a mix of C based FILE pointer I/O and C++ based stream file I/O, and for most purposes this is perfectly fine. However, this becomes an issue when dealing with non-standard filesystems that are not accessible to the standard library implementations of file I/O in C and C++ (and others, of course).

USD has wrapper functions such as [ArchOpenFile()](https://github.com/PixarAnimationStudios/USD/blob/dc710925675f7f58f7a37f6c18d046a687b09271/pxr/base/arch/fileSystem.cpp#L75) and [Tf_Stat()](https://github.com/PixarAnimationStudios/USD/blob/dc710925675f7f58f7a37f6c18d046a687b09271/pxr/base/tf/fileUtils.cpp#L117) to open files and check for their existence, respectively. 

To keep this brief, what I'm requesting is that USD move its file I/O behind an abstraction layer that allows for support of non-standard file systems. Something extremely basic would suit my purposes:

```
FileIOInterace {
  bool FileExists(string &path);
  bool ReadFileToBuffer(string &path, vector &buffer);
  bool WriteBufferToFile(string &path, vector &buffer);
}
```

I'm not very familiar with the inner workings of USD and the formats its supports-- this simple pseudocode interface design is almost certainly inadequate for all use cases. It's here only to convey what my use case needs. The above would solve the problem that I'm currently working around, and would hopefully be applicable to the use cases of other users. 

If this were to be accepted and added to USD code currently using functions like ArchOpenFile() and Tf_Stat() could be adjusted to use an internal implementation of the above interface, which would then just use the existing utility code underneath the interface implementation. 

In the event that I've just completely missed something here, and such a thing is already possible, a bit of guidance would be greatly appreciated as to how this type of situation could be handled given the current state of the USD codebase.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6630

**Comment by spiffmon** [comment]
Hi @tomfinegan ,
   Our answer to your FileIOInterface is called [ArAsset](https://graphics.pixar.com/usd/docs/api/class_ar_asset.html) for reading, and [ArWritableAsset](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/ar/writableAsset.h) for writing.  You would need to write a custom ArResolver plugin that hands out custom implementations of the two Asset classes that handles the special needs of your filesystem.

Do be warned, though, that the Ar interfaces are **right** i nthe middle of a major API transition (by default, currently, ArWritableAsset does not build, for example, you need to specify PXR_USE_AR_2=ON when running cmake, and not all of our software has yet been updated to use the newer ArAsset API's exclusively.  But this is our current focus, and the work should be completed in the coming months. 

If this answers your question, please feel free to close the Issue.

**Comment by tomfinegan** [comment]
Hi @spiffmon,

Thanks for the guidance! I'm going to close this as suggested. Looking forward to this being available by default when development is finished on the Ar interface API transition.
