### ISSUE TITLE
Incorrect behavior in Hydra when changing a variant on a shader

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#1487]
### Description of Issue
We found an incorrect behavior in Hydra when changing a variant on a shader, which makes the Arnold render delegate crash. (Autodesk/arnold-usd#717). Attaching a file to recreate the issue: [variant_crash.zip](https://github.com/PixarAnimationStudios/USD/files/6275694/variant_crash.zip).

arnold_vari_hang_modified.usda, where the variant is on the material, changing the variant will cause the following (this is the expected/correct behavior):

Calling HdRenderDelegate::DestroySPrim on the material
Calling HdRenderDelegate::CreateSPrim to create a new material (and syncing the material)
Calling HdMesh::Sync to let the polymesh know the material id has changed

arnold_vari_hang.usda, where the variant is on the material, changing the variant will cause the following:

Calling HdRenderDelegate::DestroySPrim on the material
Sync finishes, and the next iteration of the render pass is requested
Arnold crashes because the material has been destroyed, Arnold nodes deleted, and the polymeshes point to an invalid shader

### System Information (OS, Hardware)
CentOS 7

### Package Versions
USD 21.02 / #6be11aafc203cc97ffca3e934b92c9a497b5d103

**Comment by jilliene** [comment]
Filed as internal issue #USD-6647
