### ISSUE TITLE
MaterialX node inputs are sometimes added multiple times causing failures

### ISSUE THREAD

**Issue by laserallan** [PixarAnimationStudios/USD#1489]
### Description of Issue
When rendering the material standard_surface_marble_solid.mtlx from the MaterialX distribution I get the following error message:
```ERROR: Usdview encountered an error while rendering.Child name is not unique: bg```

### Steps to Reproduce
1. Reference in standard_surface_marble_solid.mtlx and assign it to an object
2. Open the scene in usdview

The issue happens in _GatherUpstreamNodes in the file materialXFilter.cpp. In some cases. When adding the input on mxCurrNode it will fail and throw an exception if the input already exist (I don't know what circumstances causes this). To work around it, check for the existence of the input before adding it (ideally with some kind of type check to make sure we are talking about the same input). My crude workaround looks like this:
```
mx::InputPtr mxInput = mxCurrNode->getInput(connName);
if (!mxInput) {
     mxInput = mxCurrNode->addInput(connName,
     mxNextNode->getType());
}

```
Sample scene attached: [materialx_issue.zip](https://github.com/PixarAnimationStudios/USD/files/6288962/materialx_issue.zip)
### System Information (OS, Hardware)
Windows 10, Amd64, NVIDIA GPU

### Package Versions
21.05 RC 1

### Build Flags
MaterialX enabled

**Comment by jilliene** [comment]
Filed as internal issue #USD-6654
