### ISSUE TITLE
USDSchemaGen semicolons

### ISSUE THREAD

**Issue by murphyeoin** [PixarAnimationStudios/USD#15]
Hello.. I'm going to submit this as an issue while we get our fork workflow up between the public github repo and our own internal one and can easily branch...

Running the usdGenSchema command creates header file class definitions that do not close the class declaration with a semicolon which  causes an error on compilation. The offending code is in the cmake file when reading in the usdGenSchema.py file to replace the pxrpythonsubst with the configured python executable before writing back out for install. Code is here: https://github.com/PixarAnimationStudios/USD/blob/2eb01f5cd4c2dae4e1ef9912ca27a93083bb6ef4/cmake/macros/Public.cmake#L34

Offending code is:
```
file(READ ${pyFile} contents)
string(REGEX REPLACE "/pxrpythonsubst" ${PXR_PYTHON_SHEBANG} contents "${contents}")
file(WRITE ${CMAKE_BINARY_DIR}/${pyFile} ${contents})
```

If we do a file read cmake operation and semicolons are found it is treated as a list, so the file write operation will remove all semicolons from the output. The fix is easy, wrap with quotes so it is treated as a string i.e.

```
file(WRITE ${CMAKE_BINARY_DIR}/${pyFile} "${contents}")
```

Thanks
Eoin

**Comment by amooty** [comment]
Filed as internal issue #135683.
