### ISSUE TITLE
MSVC: Debug Assertion while SdfLayer::TransferContent() 

### ISSUE THREAD

**Issue by ashwinbhat** [PixarAnimationStudios/USD#1501]
### Description of Issue
Use the USDMtlx Plugin to read in a MaterialX in Debug build of USD causes Debug Assertion Failed!

Microsoft Visual C++ Runtime Library
Debug Assertion Failed!
Program: Debug\usd_ms.dll
File: C:\MSVC19\VC\Tools\MSVC\14.27.29110\include\vector
Line: 183
Expression: vector iterators in range are from different containers

Seems to be relates to new changes in:
https://github.com/PixarAnimationStudios/USD/commit/1f053a258408f5ad6722b8d138b9cafb0dbb7746
```

    // Union them together, but retain order of dataList, since it influences
    // the output ordering in some file writers.
    auto dataListBegin = dataList.begin(), dataListEnd = dataList.end();
    bool mightAlloc = (dataList.size() + req.size()) > dataList.capacity();
    for (size_t reqIdx = 0, reqSz = req.size(); reqIdx != reqSz; ++reqIdx) {
        TfToken const &reqName = req[reqIdx];
        auto iter = std::find(dataListBegin, dataListEnd, reqName);
        if (iter == dataListEnd) {
            // If the required field name is not already present, append it.
            // Make sure we have capacity for all required fields so we do no
            // more than one additional allocation here.
            if (mightAlloc && dataList.size() == dataList.capacity()) {
                dataList.reserve(dataList.size() + (reqSz - reqIdx));
                dataListBegin = dataList.begin(), dataListEnd = dataList.end();
                mightAlloc = false;
            }
            dataList.push_back(reqName);
        }
    }
```

### Steps to Reproduce
auto mltxFileformat = pxr::SdfFileFormat::FindByExtension("mtlx");
assert(mltxFileformat);
bool canread = mltxFileformat->CanRead(R"(standard_surface_gold.mtlx)");
if (canread)
{
        pxr::UsdStageRefPtr tempstage = pxr::UsdStage::CreateNew("materialx_test_stage.usda");
        auto layer = pxr::SdfLayer::CreateAnonymous();
        mltxFileformat->Read(&*layer, "standard_surface_gold.mtlx", false);
}

### System Information (OS, Hardware)
Windows 10 x64. 
Microsoft Visual Studio Professional 2019
Version 16.7.9

### Build Flags
build_scripts\build_usd.py --debug --no-python --build-monolithic --materialx f:\source\USD-dev\install\

**Comment by laserallan** [comment]
I think I might have seen the same issue.
My way of reproducing it is load a scene with a materialx-file referenced in usdview do Reload All Layers.

This example causes the issue (don't forget to repath the reference in the usda file to your local filesystem)
[materialx_issue.zip](https://github.com/PixarAnimationStudios/USD/files/6352924/materialx_issue.zip)

I only experienced it on Windows, not sure if it exists on other platforms.

**Comment by spiffmon** [comment]
Thanks, @ashwinbhat !  We are aware of this issue from PR #1496 , and have a fix nearly ready to go.

**Comment by gitamohr** [comment]
I want to mention that the compiled code should function correctly under every implementation I'm aware of, despite the assertion failure.  It is correctly catching an error according to the C++ standard, but it shouldn't cause a practical problem.  As Spiff says, I have a fix coming soon.

**Comment by jtran56** [comment]
Filed as internal issue #USD-6668
