### ISSUE TITLE
HdStMaterial::Sync HdShaderTokens->fragmentShader old fragment source does not match the one assigned HdStMaterialNetwork::ProcessMaterialNetwork

### ISSUE THREAD

**Issue by perrauo-adsk** [PixarAnimationStudios/USD#1508]
I have noticed that the old fragment shader source retrieved does not match the source assigned inside HdStMaterialNetwork::ProcessMaterialNetwork.

The fragment source is assigned via the HioGlslfxTokens->volumeShader or the HioGlslfxTokens->surfaceShader token.
USD\pxr\imaging\hdSt\materialNetwork.cpp
```
void
HdStMaterialNetwork::ProcessMaterialNetwork(
    SdfPath const& materialId,
    HdMaterialNetworkMap const& hdNetworkMap,
    HdStResourceRegistry *resourceRegistry)
{
..........
        if (_surfaceGfx) {

            // If the glslfx file is not valid we skip parsing the network.
            // This produces no fragmentSource which means Storm's material
            // will use the fallback shader.
            if (_surfaceGfx->IsValid()) {
.....
                _fragmentSource = isVolume ? _surfaceGfx->GetVolumeSource() 
                                           : _surfaceGfx->GetSurfaceSource();
.....
            }
        }
    }
}
```

The old fragment is retrieved using the HdShaderTokens->fragmentShader token. This will always be an empty string.
I believe there was a misunderstanding about fragmentSource which does not refer to fragment shader source.
```
/* virtual */
void
HdStMaterial::Sync(HdSceneDelegate *sceneDelegate,
                 HdRenderParam   *renderParam,
                 HdDirtyBits     *dirtyBits)
{
....
    // If we're updating the fragment or geometry source, we need to rebatch
    // anything that uses this material.
    std::string const& oldFragmentSource = 
        _surfaceShader->GetSource(HdShaderTokens->fragmentShader);
....
}
```

**Comment by perrauo-adsk** [comment]
I have a related question. Is it possible with the current setup to define custom vertex and fragment shader for a given HdStMaterial material? It seems we are limited to only surface, volume, or displacement shader with the current API.

The way I see it now, the only way to create a non-surface shader material (vertex+fragment shader), is to create a new render delegate and override the CreateSprim method.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6679

**Comment by c64kernal** [comment]
Hi @perrauo-adsk  -- there's a brief discussion here: https://groups.google.com/g/usd-interest/c/n84yuFDeTxk/m/vnHb3RryBAAJ  about a similar question. The short answer is that Storm does not expose the ability to modify the vertex or fragment shaders.

As far as the original question, I'm not sure we fully understand the issue, do you mind explaining it a bit more what trouble you're running into?

**Comment by perrauo-adsk** [comment]
Hi, I started the discussion in the usd interest group. Please forget my comment above. While support for this feature would be great, the issue raised by this ticket is unrelated.

I have found that this is string will always be null. This is because we are checking for the existence of a fragment shader.
Instead should we not be looking for a surface shader?

`std::string const& oldFragmentSource = _surfaceShader->GetSource(HdShaderTokens->fragmentShader);`

Feel free to close this otherwise.

Best,
Olivier

**Comment by c64kernal** [comment]
Okay got it, thanks again @perrauo-adsk -- I'll go ahead and close this out, we think this is all working correctly. One thing that we can definitely do here to improve the situation by being better about how we name our variables. The confusion here is quite understandable. The oldFragmentSource variable should not be empty if a proper glslfx surface shader is assigned.
