### ISSUE TITLE
Modifying the purpose of a scenegraph instance doesn't trigger a sync of the instance prototype

### ISSUE THREAD

**Issue by williamkrick** [PixarAnimationStudios/USD#1515]
### Description of Issue
When the purpose of a scenegraph instanced prim is modified there is no call to sync for that prim.

### Steps to Reproduce
1. Unzip and open the attached file [instanceAndNot.zip](https://github.com/PixarAnimationStudios/USD/files/6435948/instanceAndNot.zip) in USD View. In the scene the 5 cubes (1 hidden) are scenegraph instances and the one capsule is not an instance.
2. View -> Display Purposes -> Uncheck proxy
3. Select Capsule1 and choose the purpose property in the property window. It's value should be "default".
4. In the python interpreter modify Capsule1's purpose to be proxy: `usdviewApi.property.Set('proxy')`
5. Capsule1 correctly disappears.
6. Select ball_01 and choose the purpose property.
7. Modify the purpose to be proxy in the same way: `usdviewApi.property.Set('proxy')`
8. ball_01 does not disappear.

When I try something similar in MayaUSD with the VP2RenderDelegate I get a similar result, the instance whose purpose changes does not disappear. Debugging in MayaUSD I found that there is no sync call for the instance prototype and so no opportunity for VP2RenderDelegate to change how it draws. When I force a sync (`ogs -reset` in Maya) and query the instancer I do find that 
the instancer only has 3 instances in it rather than 4, and I am able to draw correctly in that case.

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD v21.05

**Comment by jilliene** [comment]
Filed as internal issue #USD-6686
