### ISSUE TITLE
Nested light xformOp do not update if 1 or less timeSamples

### ISSUE THREAD

**Issue by DuncanHopkinsFoundry** [PixarAnimationStudios/USD#1524]
If you nest a light under an animated Xform, the light must have more than one timeSamples on its xform to animate with the parent transform.

Steps to Reproduce
* Load Scene into USDView
* Move time line slider. 
If all is working, all 3 lights will move together and the sphere will remain with a uniform grey lighting.
If any of the lights are not in sync then you will see colored areas.

[lighting.rect.2.usda.zip](https://github.com/PixarAnimationStudios/USD/files/6544457/lighting.rect.2.usda.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6707
