### ISSUE TITLE
hdMtlx: _GetMxNodeType should use the MaterialX library to find the node type.

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#1538]
### Description of Issue

- Local surface shaders (like a Lambert-like PBR surface for Maya export) are not recognized even though the definition file was read and the library contains the node definition.

### Steps to Reproduce
1. Copy the attached `maya_surfaces.mtlx` file to the local MaterialX library (I put it in libraries/bxdf of my MaterialX installation since hdSt does not declare an environment variable to define extra library paths to search). 
2. Load the attached `LambertSphere.usda` scene in usdView
3. Warning: Unsupported node type 'ND_MayaLambert_surfaceshader'

I can get a working Lambert by updating [_GetMxNodeType](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdMtlx/hdMtlx.cpp#L59) to fetch back `mxDoc->getNodeDef(hdNodeType.GetString())->getNodeString()`. Would that be a correct fix? 

[LambertSphere.zip](https://github.com/PixarAnimationStudios/USD/files/6656202/LambertSphere.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6734

**Comment by klucknav** [comment]
Thank you, initially we were only supporting UsdPreviewSurface and StandardSurface node types, but we have a fix coming.
