### ISSUE TITLE
Build USD CentOS7 (error: ‘enable_if_t’ in namespace ‘std’ ...)

### ISSUE THREAD

**Issue by shdwdln** [PixarAnimationStudios/USD#1540]
### Description of Issue
I am building USD21.05 w/python3 (PySide2, PyOpenGL, jinja2) and I ran the default script (to build TBB, Boost, OpenSubdiv and it all built fine until it got to USD)

The build error I am getting is:
**[ 39%] Building CXX object pxr/base/tf/CMakeFiles/tf.dir/mallocTag.cpp.o
In file included from /home/dillon/_DEV/_USD/USD-21.05/USD/pxr/base/tf/enum.h:33:0,
                 from /home/dillon/_DEV/_USD/USD-21.05/USD/pxr/base/tf/debug.h:34,
                 from /home/dillon/_DEV/_USD/USD-21.05/USD/pxr/base/tf/initConfig.cpp:26:
/home/dillon/_DEV/_USD/USD-21.05/USD/pxr/base/tf/hash.h:44:1: error: ‘enable_if_t’ in namespace ‘std’ does not name a type
 std::enable_if_t<std::is_integral<T>::value>
 ^**

### Steps to Reproduce
1. python3 build_scripts/build_usd.py /home/dillon/_DEV/_USD/USD-21.05/USD_BUILD

### System Information (OS, Hardware)
CentOS7 
GNOME Version 3.28.2

**Comment by shdwdln** [comment]
**gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)**

**Comment by sunyab** [comment]
Hi @shdwdln, this error is due to your gcc version. USD requires gcc 6 or greater for C++14 support.

**Comment by shdwdln** [comment]
I updated to devtoolset-7
(gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) )

Build and installed boost, TBB, OpenSubdiv successfully.

Then on USD I got this error:

[ 47%] Linking CXX shared library libgf.so
[ 49%] Built target gf
[ 49%] Building CXX object pxr/base/tf/CMakeFiles/_tf.dir/wrapType.cpp.o
[ 49%] Building CXX object pxr/base/tf/CMakeFiles/_tf.dir/wrapWarning.cpp.o
[ 49%] Linking CXX shared library _tf.so
[ 49%] Built target _tf
gmake: *** [Makefile:150: all] Error 2

This is the same this that the build/USD/log.txt shows.

Any thoughts what the problem is?

**Comment by shdwdln** [comment]
It also had this:

[ 45%] Building CXX object pxr/base/gf/CMakeFiles/gf.dir/vec4d.cpp.o
[ 45%] Building CXX object pxr/base/gf/CMakeFiles/gf.dir/vec4f.cpp.o
[ 45%] Building CXX object pxr/base/tf/CMakeFiles/_tf.dir/wrapError.cpp.o
[ 45%] Linking CXX shared library libgarch.so
/usr/lib/libXext.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
gmake[2]: *** [pxr/imaging/garch/CMakeFiles/garch.dir/build.make:233: pxr/imaging/garch/libgarch.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6026: pxr/imaging/garch/CMakeFiles/garch.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object pxr/base/tf/CMakeFiles/_tf.dir/wrapFileUtils.cpp.o
[ 45%] Linking CXX shared library libjs.so

**Comment by jilliene** [comment]
Filed as internal issue #USD-6759

**Comment by sunyab** [comment]
That looks like an issue with libXext.. can you make sure you have the libXext-devel.x86_64 package installed (and not the .i686 package)

**Comment by shdwdln** [comment]
It was not installed so I installed it (libXext-devel.x86_64, I feel foolish for not noticing that -__-)
It build fine now! Thanks.
