### ISSUE TITLE
Houdini -> USD (procedural controllers) 

### ISSUE THREAD

**Issue by alelordelo** [PixarAnimationStudios/USD#1541]
Is it possible to export a Houdini HDA to USD procedural controllers?

Ex: 
1- Have an Houdini  HDA with controllers for hair curves
2- Export that into USD. 
3- Then, open USD in other DCC (Maya, Multiverse for ex) and have the controllers there?

**Comment by marktucker** [comment]
This discussion might belong more on the Houdini forums... But a quick answer is that Houdini ships with an HDA "dynamic payload" plugin which allows you to treat an HDA as a payload, but also set HDA parameter values as metadata on the primitive that is payloading the HDA. In theory this mechanism would work in any DCC except you would need to compile the "HDA File Format" plugin against the USD library being used by that other DCC. Having done that, assuming that DCC allows editing of USD primitive metadata, you can effectively adjust the HDA parameters within that DCC. The code for the HDA dynamic file format plugin is available in the HoudiniUsdBridge repository (https://github.com/sideeffects/HoudiniUsdBridge/tree/houdini18.5/src/houdini/custom/USD). You shouldn't have to build that whole repository, just that one plugin directory.

**Comment by alelordelo** [comment]
Thanks @marktucker! I also posted on Houdini Solaris forum, in case you think its better to move the discussion there:
https://www.sidefx.com/forum/topic/79775/

Would this work like Unreal Engine then, which requires a Houdini plugin and its limited to viewport, not "runtime/playtime"?

My goal is to take an HDA to Xcode and build it on iOS with procedural controllers

**Comment by marktucker** [comment]
Moving this to the Houdini forums...

**Comment by jilliene** [comment]
Filed as internal issue #USD-6760

**Comment by sunyab** [comment]
Closing this out in favor of the discussion on the Houdini forums. Thanks!
