### ISSUE TITLE
Boost install fails when building

### ISSUE THREAD

**Issue by MATTJ0NES** [PixarAnimationStudios/USD#1542]
Hi, I'm running into an error on building at the installing Boost step. I've seen similar previous issues but all with much earlier versions of things and not seen a solution that applies here. I've added the relevant info below. Any help much appreciated, thanks.

### Description of Issue
Error when building, due to a failure on the Boost install:
_ERROR: Failed to run 'b2 --prefix="C:\USD" --build-dir="C:\USD\build" -j12 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-program_options --with-regex --with-python --user-config=python-config.jam toolset=msvc-14.1 install'_

### Steps to Reproduce
With all dependecies already installed, I'm running this command:
python USD-release/build_scripts/build_usd.py "C:\USD"

### System Information (OS, Hardware)
Windows 10, 64 bit on Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz

### Package Versions
Python 3.6
Latest USDpackage as of 21 Jun 2021 (v21.05)

### Build Flags
None. See command above

Log file text:

2021-06-22 14:29
b2 --prefix="C:\USD" --build-dir="C:\USD\build" -j12 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-program_options --with-regex --with-python --user-config=python-config.jam toolset=msvc-14.1 install
Performing configuration checks

    - default address-model    : 32-bit (cached)
    - default architecture     : x86 (cached)
    - has_icu builds           : no  (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : not building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : building
    - random                   : not building
    - regex                    : building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : not building
    - test                     : not building
    - thread                   : not building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...patience...
...patience...
...found 31927 targets...
...updating 6 targets...
common.copy C:\USD\include\boost-1_70\boost\version.hpp
C:\USD\src\boost_1_70_0\boost\version.hpp
        1 file(s) copied.
msvc.link.dll C:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi\boost_python36-vc141-mt-x64-1_70.dll
LINK : fatal error LNK1181: cannot open input file 'python36.lib'

        call "C:\USD\build\boost\bin.v2\standalone\msvc\msvc-14.1\address-model-64\architecture-x86\msvc-setup.bat"  >nul
 link /NOLOGO /INCREMENTAL:NO /DLL /MACHINE:X64 /MANIFEST /subsystem:console /out:"C:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi\boost_python36-vc141-mt-x64-1_70.dll" /IMPLIB:"C:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi\boost_python36-vc141-mt-x64-1_70.lib" /LIBPATH:"D:\Development\Python\usdenvp3\libs"   @"C:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi\boost_python36-vc141-mt-x64-1_70.dll.rsp"
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
    
...failed msvc.link.dll C:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi\boost_python36-vc141-mt-x64-1_70.dll C:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi\boost_python36-vc141-mt-x64-1_70.lib...
...skipped <pC:\USD\lib>boost_python36-vc141-mt-x64-1_70.dll for lack of <pC:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi>boost_python36-vc141-mt-x64-1_70.dll...
...skipped <pC:\USD\lib>boost_python36-vc141-mt-x64-1_70.lib for lack of <pC:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi>boost_python36-vc141-mt-x64-1_70.lib...
...skipped <pC:\USD\lib\cmake\boost_python-1.70.0>libboost_python-variant-vc141-mt-x64-1_70-shared.cmake for lack of <pC:\USD\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\python-3.6\threading-multi>boost_python36-vc141-mt-x64-1_70.lib...
...failed updating 2 targets...
...skipped 3 targets...
...updated 1 target...

**Comment by sunyab** [comment]
Hi @MATTJ0NES, can you double check a few things? 

- Are you in the x64 command prompt for MSVC?
- Where is your Python installation located? Is there a python36.lib in your Python installation? It would normally be in the libs\ directory beneath your Python install directory (on my machine it's in C:\Python36\libs\)
- Do you have the 64-bit version of Python installed? (The script should have told you if you didn't, but just to double-check..)

**Comment by MATTJ0NES** [comment]
Hi, thanks for the quick response!

Yes, I'm using the x64 Native Tools Command Prompt for VS 2017.

My Python install is att:
C:\Users\myusername\AppData\Local\Programs\Python\Python36

Yes, I do have a python36.lib in my libs folder.

And yes, I can confirm I have the 64 bit version of Python installed.

Thanks again!

**Comment by sunyab** [comment]
Ah, the linker command line has this argument:  /LIBPATH:"D:\Development\Python\usdenvp3\libs"

So boost is probably trying to find python36.lib in that directory, which differs from where your installation is. Can you check if this directory (or D:\Development\Python\usdenvp3) is in your %PATH%, remove it if so, and try to build again? You'll probably want to remove your C:\USD directory and rebuild from scratch.

**Comment by MATTJ0NES** [comment]
Thank you. I don't have that in my %PATH%. Would using virtualenv be an issue as that's what usdenvp3 in that path is?

Thanks again!

**Comment by sunyab** [comment]
Ah that seems possible, I have not tried to build USD with a venv on Windows. I just tried creating one now and noticed the libs directory doesn't get copied over, so that might be tripping up the boost installation. You could try copying that directory from your Python install to your venv and see if that helps?

**Comment by jilliene** [comment]
Filed as internal issue #USD-6761

**Comment by sunyab** [comment]
Just noting that I bumped into this while testing #1692 and can confirm that that PR fixes the issue with building in a Python 3 venv on Windows.

**Comment by sunyab** [comment]
This should be fixed in the latest dev branch now that #1692 has been merged. I'll mark this as pending release and close this out when 22.08 goes out the door.

**Comment by sunyab** [comment]
Closing out this issue, it should be resolved with #1692 in USD 22.08.
