### ISSUE TITLE
MaterialX: Referencing a MaterialX fails

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#1544]
### Description of Issue

Trying to reference a MaterialX document in a USD file to leverage the SdfFileFormat capabilities of usdMtlx:
```
def "MaterialX"
(
	references = @./standard_surface_jade.mtlx@
)
{
}
```
Fails with the following error:
```
Warning: in _ReportErrors at line 2825 of ...\USD\pxr\usd\usd\stage.cpp -- Unresolved reference path <defaultPrim> on prim @./UsdImportMaterialXSidecar.usda@,@anon:000002829ECFAAE0@</MaterialX>. (instantiating stage on stage @./UsdImportMaterialXSidecar.usda@ <000002829C48B470>)
```

Converting the file to USD using Python's `UsdMtlx._TestFile("standard_surface_jade.mtlx")` shows that the resulting stage is missing a `defaultPrim="MaterialX"` statement at the top level, which prevents referencing it.

Is this the expected behavior? Am I using the feature incorrectly?

**Comment by JGamache-autodesk** [comment]
Forgot the most important step. Try with the latest tip of usdMtlx. Closing since I see commits more recent that most probably fix this...

**Comment by JGamache-autodesk** [comment]
OK. Confirmed it still does not work on tip of dev branch, at commit 3fd536ae4 of June 14th.

**Comment by JGamache-autodesk** [comment]
It works if I use subLayers though. Here is a test scene.
[ReferencingTest.zip](https://github.com/PixarAnimationStudios/USD/files/6703947/ReferencingTest.zip)
The Jade material uses an edited `.usda` stage dump of the `.mtlx` where a default prim was added. The Gold material uses a subLayer.
It would be nice if I could reference standard_surface_gold.mtlx instead.

**Comment by spiffmon** [comment]
This is expected behavior, since we don't know which prim in the converted Mtlx document should be considered "the" canonical prim for the file.  You need to reference specific materials within the file.  If folks can make a reasonable argument that there's a knowable canonical prim to reference, we'd be happy to consider a PR that adds a setting of _defaultPrim_ .

**Comment by JGamache-autodesk** [comment]
Thank you.

For reference, the fix is:
```
def "MaterialX"
(
	references = @./standard_surface_jade.mtlx@</MaterialX>
)
{
}
```
Which works perfectly fine.

**Comment by spiffmon** [comment]
Ah - if we are always putting everything inside a </MaterialX> root (it's been awhile since I've looked at that code), then there's no reason we can't set _defaultPrim_ to that.  Please feel free to submit a PR, or reopen this Issue.
