### ISSUE TITLE
Windows: Referencing prims fails if file is opened from a parent directory (endToEnd example)

### ISSUE THREAD

**Issue by krzykli** [PixarAnimationStudios/USD#155]
### Description of Issue
A warning message about prim referencing is raised when opening a file using `usdview` from the file's parent directory. 
```
Warning: in UsdStage::_ReportErrors at line 2247 of O:\dev\krzysztof.klimczyk\workspace\usd_build\Projects\USD\pxr\usd\lib\usd\stage.cpp -- Instantiating stage:
    Could not open asset @./Ball.shadingVariants.usda@ for reference on prim @assets\Ball\Ball.usd@,@anon:00000000067266C0:Ball-session.usda@</Ball>.
    Could not open asset @./Ball.maya.usd@ for reference on prim @assets\Ball\Ball.usd@,@anon:00000000067266C0:Ball-session.usda@</Ball>.
```

If I first navigate to the directory where the file lives then I get no error and the geometry is displayed correctly.

Basing on the documentation of the example, this works fine on Linux, so it would be great to have it working on Windows as well :)

### Steps to Reproduce
1. Navigate to `%USD_INSTALL_ROOT%\share\usd\tutorials\endToEnd`.
2. Run `usdview assets\Ball\Ball.usd`, notice the geometry is not loaded.
3. Navigate now to `assets\Ball` directory and run `usdview Ball.usd` -> the geometry is loaded correctly.

### System Information (OS, Hardware)
Windows

**Comment by jtran56** [comment]
Filed as internal issue #142257.

**Comment by sunyab** [comment]
I've confirmed this is no longer an issue in release 0.7.5, so I'm closing this out. Please reopen if you still run into this. Thanks!
