### ISSUE TITLE
Verification error when setting prim instanceable to be false

### ISSUE THREAD

**Issue by csyshing** [PixarAnimationStudios/USD#1551]
### Description of Issue

Hi,

I was debugging an issue when setting prim instanceable to be false, USD is throwing verification exception, not sure if there is something I missed or maybe a bug in USD?

Thanks,
Zhicheng

### Steps to Reproduce
1. Load the problematic USD file "test_error_verification.usda" from attachment in usdview:
```
usdview /path/to/test_error_verification.usda
```
2. Run the code snippet below in usdview:
```
stage = usdviewApi.stage
groupedPrimPath = "/root/group/ball_01" # Change the prim path to /root/a_group/ball_01 if it's "test_no_error.usda"
# Modify translate of the first prim
prim01 = stage.GetPrimAtPath(groupedPrimPath)
translateOp01 = UsdGeom.Xformable(prim01).AddTranslateOp()
translateOp01.Set((1, 2, 3))
# Set instanceable to be false for the second prim
prim02 = stage.GetPrimAtPath("/root/ball_02")
prim02.SetInstanceable(False)                   # raise exception
```
OR execute from the Python shell in usdview:
```
execfile('/path/to/test_instanceable.py', globals(), locals())
```
The file "test_instanceable.py" is also in attachment.

3. Check the console output, usdview would print out the exception like this:
```
	Error in 'pxrInternal_v0_21__pxrReserved__::UsdImagingInstanceAdapter::_GetProtoPrim' at line 2159 in file /path/to/usd/source/pxr/usdImaging/usdImaging/instanceAdapter.cpp : 'Failed verification: ' r ' -- instancer = /root/group/ball_01, cachePath = /root/group/ball_01'
	Error in 'pxrInternal_v0_21__pxrReserved__::UsdImagingInstanceAdapter::ProcessPropertyChange' at line 1261 in file /path/to/usd/source/pxr/usdImaging/usdImaging/instanceAdapter.cpp : 'Failed verification: ' proto.adapter ' -- /root/group/ball_01'
	Error in 'pxrInternal_v0_21__pxrReserved__::UsdImagingInstanceAdapter::_GetProtoPrim' at line 2159 in file /path/to/usd/source/pxr/usdImaging/usdImaging/instanceAdapter.cpp : 'Failed verification: ' r ' -- instancer = /root/group/ball_01, cachePath = /root/group/ball_01'
	Error in 'pxrInternal_v0_21__pxrReserved__::UsdImagingInstanceAdapter::ProcessPropertyChange' at line 1261 in file /path/to/usd/source/pxr/usdImaging/usdImaging/instanceAdapter.cpp : 'Failed verification: ' proto.adapter ' -- /root/group/ball_01'
```

This is not a problem in usdview since usdview itself [catches the exception](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usdImaging/usdviewq/stageView.py#L1452), but it breaks our pipeline tools.

4. Strangely repeat the steps 1-3 with another USD file "test_no_error.usda", which has just one difference: the group name, does not trigger any exception.
```
# "test_error_verification.usda" file:
....
def Xform "group" {
....

# "test_no_error.usda" file:
....
def Xform "a_group" {
....
```

### System Information (OS, Hardware)

OS: CentOS 7.4

### Package Versions

Official USD-19.11 : Cannot reproduce the error above
Official USD-20.11/21.02/21.05:  Reproducible

### Build Flags
Standard flags as build script.

[usd_verification_error.zip](https://github.com/PixarAnimationStudios/USD/files/6768361/usd_verification_error.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6778
