### ISSUE TITLE
SdfCreateVariantInLayer is not consistent with UsdVariantSets .AddVariantSet

### ISSUE THREAD

**Issue by jpankalainen** [PixarAnimationStudios/USD#1552]
### Description of Issue
Currently the function [SdfCreateVariantInLayer](https://graphics.pixar.com/usd/docs/api/variant_spec_8h.html#ab233fcb528d4b8d35e8539dd94d49d8d) is not consistent with the default behavior of [UsdVariantSets.AddVariantSet](https://graphics.pixar.com/usd/docs/api/class_usd_variant_sets.html#afa72971becc14b53366f2913307b8164). The former currently adds the variant set name to the prim spec's list with the **add** verb, whereas the latter uses **prepend** by default and does not even have **add** as an option. 

### Steps to Reproduce
1. Create two prims to a stage with only one layer
2. Call SdfCreateVariantInLayer for a root layer prim spec for the first prim
3. Fetch the UsdVariantSets for the second prim and call AddVariantSet.
4. Export the layer as string and compare the results

### System Information (OS, Hardware)
Windows 10

### Package Versions
21.02

### Build Flags
--no-usdview --no-imaging --build-monolithic

**Comment by jilliene** [comment]
Filed as internal issue #USD-6779
