### ISSUE TITLE
Build USD for Renderman 24 plugin

### ISSUE THREAD

**Issue by swamiforlife** [PixarAnimationStudios/USD#1555]
I am trying to build the latest version of USD with the Renderman plugin using Renderman 24.
I am building on Windows using the build script that comes with USD
I am getting the below error:

CMake Error at CMakeLists.txt:54 (message):
  No RenderMan plugin available for RenderMan 24

Below is the command used to build USD
python C:\git\USD\build_scripts\build_usd.py "C:\build\USD" --prman --prman-location "C:\Program Files\Pixar\RenderManProServer-24.0"

**Comment by c64kernal** [comment]
Hi @swamiforlife  -- are you trying to build from release or the dev branch? Note that support for RenderMan 24 is only available in the dev branch which will then make it to the soon to be released 21.08.

**Comment by swamiforlife** [comment]
Hi @c64kernal  You are right. My problem is due to using the release branch. 
I tried using the dev branch on the latest release and it builds correctly with Renderman 24.
Thanks

**Comment by c64kernal** [comment]
Excellent, glad to hear, thanks for the update.
