### ISSUE TITLE
Resolution of UDIM texture paths inside USDZ archives fails

### ISSUE THREAD

**Issue by dalorin** [PixarAnimationStudios/USD#1558]
### Description of Issue
It is not possible to resolve paths to UDIM textures that are located inside a USDZ archive. This is because the utility function _ResolveAssetAttribute located in [materialParamUtils.cpp](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usdImaging/usdImaging/materialParamUtils.cpp#L156) does not account for the presence of usdz reference syntax e.g. /path/to/file.usdz[0/texture.png] when sanity checking the suffix post-resolution [here](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usdImaging/usdImaging/materialParamUtils.cpp#L187). As a result, the return SdfAssetPath object does not contain a resolved path and renderers will treat texture paths such as "0/texture.png" as absolute and fail.

### Steps to Reproduce
1. Create a USD file containing a model with attached texture using UDIMs.
2. Run usdzip with -a flag against the USD file to create a usdz archive containing the texture files.
3. Attempt to render the usdz archive with a hydra render delegate. In the case of arnold, the following output is produced:
00:00:00   535MB ERROR   |  [texturesys] could not read resolved image filename = "2/alien_Opacity.1007.tif"

### System Information (OS, Hardware)
CentOS 7, python 2.7.17

I have a patch for this issue that I will raise in a pull request if this issue is confirmed.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6786

**Comment by sunyab** [comment]
Hi @dalorin, I can confirm the issue is exactly as you've said. We have a fix internally pending review and testing but it'll be at least a week or so before we can push that up due to some office outages. I'll add some notes to the PR as well. Thanks!
