### ISSUE TITLE
UsdUVTexture sourceColorSpace acescg?

### ISSUE THREAD

**Issue by earlgeorg** [PixarAnimationStudios/USD#1562]
### Description of Issue
Currently the UsdUVTexture supports the sourceColorSpace auto, raw & sRGB.
Will there be any updates regarding the support of aces-cg as a color space?

In combination with maya_usd the viewport preview shaders are very dark and need a very bright light (intensity > 100) to even see the diffuse texture

### Steps to Reproduce
1. Create a aces-cg encoded diffuse texture
2. Create a usd preview shader with that diffuse texture plugged in
3. Create a simple geometry (e.g. sphere) and assign the shader to it
4. Load the usd in the Maya viewport (using the maya_usd-0.10.0 Autodesk plugin). The object is mostly black, where it should render diffuse textures without lights. Add a light and set the intensity to > 100 to see the diffuse texture.
5. Load the usd as a reference in Houdini 18.5. Enable Karma. There should be a diffuse texture rendered without any lights in the scene. Add a bright light to see the diffuse texture.

### System Information (OS, Hardware)
Linux CentOS 7.6
Maya 2019.3
Houdini 18.5

### Package Versions
usd-0.21.5
maya_usd-0.10.0 Autodesk plugin

**Comment by JGamache-autodesk** [comment]
There was an issue with the maya_usd Autodesk plugin that has been fixed, so this workflow should work correctly in the upcoming version 0.11.0.
If your working colorspace in Maya is ACEScg, using `sourceColorSpace = "raw"` is the USD way to specify that no color transformation is required when reading your ACEScg file textures.
For reference: https://github.com/Autodesk/maya-usd/pull/1508/

**Comment by earlgeorg** [comment]
Thanks. I will give it a go!
