### ISSUE TITLE
Questions for "USD, Hydra and OpenSubdiv: Pixar’s Open Source Meetup" SIGGRAPH 2021

### ISSUE THREAD

**Issue by c64kernal** [PixarAnimationStudios/USD#1563]
Post and upvote your favorite questions for SIGGRAPH 2021's "USD, Hydra and OpenSubdiv: Pixar’s Open Source Meetup" here! We'll try to answer as many as we can, live at the event, happening Wednesday, August 11th, 2021 from 2pm to 4pm PDT.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6798

**Comment by sunyab** [comment]
Hope everyone enjoyed the BoF at SIGGRAPH!
