### ISSUE TITLE
Version 21.08 Compile

### ISSUE THREAD

**Issue by dearyangyu** [PixarAnimationStudios/USD#1567]
### compile env
1. visual studio 2015
2. Python 2.7.15

### System Information (OS, Hardware)
1. windows10

### Package Versions
Version 21.08

### Build Flags
I would like to know. Whether such an environment can compile success!

I tried to compile many times, but I have no success. Is there a problem with my environment, and every time I'm different, I will not provide an error here.

**Comment by dearyangyu** [comment]
python build_script/build_usd.py "E:/USD"
This is my Command!!

**Comment by jilliene** [comment]
Filed as internal issue #USD-6802
