### ISSUE TITLE
UsdUtils.ExtractExternalReferences requires editable Layers

### ISSUE THREAD

**Issue by ColinKennedy** [PixarAnimationStudios/USD#1573]
### Description of Issue

A follow-up from this [usd-interest forum post](https://groups.google.com/g/usd-interest/c/z8LTo98TMJ8)

UsdUtils.ExtractExternalReferences requires the Layer to be editable which is seems odd since theoretically the function should only need to query things on the Layer.

This has caused issues for us in Houdini because Houdini frequently sets Layers to be un-editable if they are created by LOPs or even if it's an external Layer, brought in via sublayer / referencing. We're getting around the issue by using a Python context to temporarily call SetPermissionToEdit(True) and reverting but if UsdUtils could be improved to not require edit permissions, it'd remove a lot of our boilerplate code.

### Steps to Reproduce

1. Run this below

```python
referencee = Usd.Stage.CreateInMemory()
prim = referencee.DefinePrim("/root")
referencee.SetDefaultPrim(prim)
referencer = Usd.Stage.CreateInMemory()
prim = referencer.DefinePrim("/root")
prim.GetReferences().AddReference(referencee.GetRootLayer().identifier)
referencer.GetRootLayer().SetPermissionToEdit(False)

UsdUtils.ExtractExternalReferences(referencer.GetRootLayer().identifier)
```

Assuming file.usda is not empty and has at least one dependency, that code will error with 

```
Error in 'pxrInternal_v0_19__pxrReserved__::Sdf_ListOpListEditor<TypePolicy>::_UpdateListOp [with TypePolicy = pxrInternal_v0_19__pxrReserved__::SdfPayloadTypePolicy]' at line 118 in file /path/to/pxr/usd/lib/sdf/listOpListEditor.h : 'Layer is not editable.'
```

### System Information (OS, Hardware)
CentOS 7.4

### Package Versions
USD 19.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-6808
