### ISSUE TITLE
I've created a stage, but now that I have another usda file, I want to add some prims from this usda file to the stage, what do I do?

### ISSUE THREAD

**Issue by FeiLongXu** [PixarAnimationStudios/USD#1576]
I've created a stage, but now that I have another usda file, I want to add some prims from this usda file to the stage, what do I do?

**Comment by marktucker** [comment]
Is this using python or some application? If the latter, which one?

The very generic USD answer is that you can:
1. Sublayer the other USD file onto the stage
2. Reference/payload the other USD file onto the stage
3. Use an API like SdfCopySpec to selectively copy contents from that other layer onto an existing layer on the stage

This sort of general question is probably more appropriate on the usd-interest google group than as a github issue...

**Comment by FeiLongXu** [comment]
Oh, I found the ReLoad interface and it solved my problem perfectly.

**Comment by FeiLongXu** [comment]
UsdStage::Reload()
