### ISSUE TITLE
USDZ archive lookup is O(n^2)

### ISSUE THREAD

**Issue by marsupial** [PixarAnimationStudios/USD#1577]
### Description of Issue
USDZ is linearly traversing the archive for every lookup, which creates a huge bottleneck and is very noticeable once you pass ~10000 entries.

This was noticed by someone who is trying to use USD and Draco compression, which means every mesh will be referencing an external file.  While not the most common use-case, the issue will also be at play even in a **flat** USD scene that makes heavy use of unique textures, or for a heavily referenced scene that just wants to be bundled into one file.

### Steps to Reproduce
1. Generate a usdz file with around 25000 external references, and then Open the stage.  Even when those references are all nothing more than a single plane, load time will be above 15 seconds, while the original **usdc** takes under 3 seconds.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6816
