### ISSUE TITLE
MaterialX: Support multi-output nodes in hdMtlx

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#1581]
### Description of Issue

The code in [_GatherUpstreamNodes()](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/imaging/hdMtlx/hdMtlx.cpp#L312) is missing support for multi-output nodes and will fail to connect them.

To detect:
Need to call [isMultiOutputType](https://github.com/materialx/MaterialX/blob/main/source/MaterialXCore/Element.h#L877) on the Node. Nodes like [artistic_ior](https://github.com/materialx/MaterialX/blob/main/libraries/pbrlib/pbrlib_defs.mtlx#L390) should return true.

An example of using an artistic_ior node and connecting it can be found [here](https://github.com/materialx/MaterialX/blob/main/source/MaterialXCore/Document.cpp#L1196). It calls low-level versions of the mx::Input interface to set the node name and output name. If you look at the implementations of mx::Input::setConnectedNode() and mx::Input::setConnectedOutput() you will see the same low-level calls.

The resulting MaterialX document should contain input elements that connect like [usd_preview_surface](https://github.com/materialx/MaterialX/blob/main/libraries/bxdf/usd_preview_surface.mtlx#L190):
```
      <input name="ior" type="color3" nodename="artistic_ior" output="ior" />
```
or possibliy like the [dielectric Lama node](https://github.com/materialx/MaterialX/blob/main/libraries/bxdf/lama/lama_dielectric.mtlx#L49):
```
      <input name="in2" type="float" nodename="artistic_ior" output="ior" channels="r" />
```

### Steps to Reproduce
1.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6820
