### ISSUE TITLE
Execution example usdview 

### ISSUE THREAD

**Issue by SunHongFeng** [PixarAnimationStudios/USD#1583]
### Steps to Reproduce
1. USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda

### System Information (OS, Hardware)
MacOS
### Build Flags
State file not found, a new one will be created

**Comment by jilliene** [comment]
Filed as internal issue #USD-6822

**Comment by sunyab** [comment]
Closing this out due to a lack of information, please file a new issue with more details about the issue you're encountering.
