### ISSUE TITLE
Metal Hydra Storm renderer for iOS?

### ISSUE THREAD

**Issue by alelordelo** [PixarAnimationStudios/USD#1588]
Apple mentioned at wwdc21, that Pixar would open source a Metal Hydra Storm renderer for iOS:
https://developer.apple.com/wwdc21/10077

Is there a ETA for that?

thanks!

**Comment by c64kernal** [comment]
Hi @alelordelo, the work is on-going right now in the dev branch and we update it regularly. We hope the project will be closer to completion by the end of the year.

**Comment by alelordelo** [comment]
Great can’t wait to try it! Thanks for the update

**Comment by jilliene** [comment]
Filed as internal issue #USD-6829
