### ISSUE TITLE
Ubuntu 18.04 - unable to build usdview

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/USD#1589]
### Description of Issue
I see lots of the following when configuring but it does not detail what is missing so that I can try to address the issue

-- Skipping Python module tf, shared libraries required
-- Skipping Python module gf, shared libraries required
-- Skipping Python module trace, shared libraries required
-- Skipping Python module work, shared libraries required
-- Skipping Python module plug, shared libraries required
-- Skipping Python module vt, shared libraries required
-- Skipping Python module ar, shared libraries required
-- Skipping Python module kind, shared libraries required
-- Skipping Python module sdf, shared libraries required
-- Skipping Python module ndr, shared libraries required
-- Skipping Python module sdr, shared libraries required
-- Skipping Python module pcp, shared libraries required
-- Skipping Python module usd, shared libraries required
-- Skipping Python program usdGenSchema, Python modules required
-- Skipping Python module usdGeom, shared libraries required
-- Skipping Python module usdVol, shared libraries required
-- Skipping Python module usdMedia, shared libraries required
-- Skipping Python module usdShade, shared libraries required
-- Skipping Python module usdLux, shared libraries required
-- Skipping Python module usdRender, shared libraries required
-- Skipping Python module usdHydra, shared libraries required
-- Skipping Python module usdRi, shared libraries required
-- Skipping Python module usdSkel, shared libraries required
-- Skipping Python module usdUI, shared libraries required
-- Skipping Python module usdUtils, shared libraries required
-- Skipping Python module usdPhysics, shared libraries required
-- Skipping Python program usdcat, Python modules required
-- Skipping Python program usdchecker, Python modules required
-- Skipping Python program usddiff, Python modules required
-- Skipping Python program usddumpcrate, Python modules required
-- Skipping Python program usdgenschemafromsdr, Python modules required
-- Skipping Python program usdedit, Python modules required
-- Skipping Python program usdresolve, Python modules required
-- Skipping Python program usdstitch, Python modules required
-- Skipping Python program usdstitchclips, Python modules required
-- Skipping Python program usdzip, Python modules required
-- Skipping Python program usdtree, Python modules required
-- Skipping Python module garch, shared libraries required
-- Skipping Python module cameraUtil, shared libraries required
-- Skipping Python module pxOsd, shared libraries required
-- Skipping Python module glf, shared libraries required
-- Skipping Python module usdImagingGL, shared libraries required
-- Skipping Python module usdAppUtils, shared libraries required
-- Skipping Python module usdviewq, shared libraries required
-- Skipping Python program usdrecord, Python modules required
-- Skipping Python program usdview, Python modules required
-- Skipping Python program testusdview, Python modules required
-- Skipping Python program usdMakeFileVariantModelAsset, Python modules required

### Steps to Reproduce

export BOOST_ROOT=$HOME/data1/systems/boost/1.70.0-py37
export OPENSUBDIV_ROOT_DIR=$HOME/systems/OpenSubdiv/head
cmake \
	-D BUILD_SHARED_LIBS=OFF \
	-D PXR_ENABLE_PTEX_SUPPORT=OFF \
	-D PXR_USE_PYTHON_3=ON \
	-D CMAKE_BUILD_TYPE=Release \
	-D CMAKE_INSTALL_PREFIX=$HOME/systems/USD/head \
	-G "Ninja" \
	../USD_git

### System Information (OS, Hardware)
Ubuntu 18.04 with nvidia driver 

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 710/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 390.144
OpenGL core profile shading language version string: 4.60 NVIDIA

**Comment by sunyab** [comment]
Hi @nyue, usdview requires the USD Python bindings, but these bindings are disabled when building USD as static libraries (i.e., with BUILD_SHARED_LIBS=OFF). Hope that helps.

**Comment by nyue** [comment]
Thank you @sunyab , I have got past that issue and doing a clean build from scratch.
