### ISSUE TITLE
Transform being ignored for unloaded instance

### ISSUE THREAD

**Issue by csyshing** [PixarAnimationStudios/USD#1601]
### Description of Issue

Hi,

I was debugging a bounding box issue with Animal Logic's ALab scene (https://animallogic.com/usd-alab/), the problem is that when the instance prim is unloaded, the bounding box on viewport is at origin:

```
usdview --unloaded /path/to/alab/USD_ALab_0730/entry.usda
```

![unexpected_instance_bbox](https://user-images.githubusercontent.com/1593576/130535164-1d6dd5c1-ff82-40ea-8bcc-41c94f809baa.png)

If setting the instanceable to be False, the bounding box pops back to the expected location:

![expected_non-instance_bbox](https://user-images.githubusercontent.com/1593576/130535194-9b9a0ad0-2103-4631-893d-b453bb6fe60b.png)

![unloaded_instance_unexpected_bbox](https://user-images.githubusercontent.com/1593576/130535208-c3c026d4-2a44-452d-9467-d9a60491dd59.gif)

I found that there is a comment in [**UsdImagingGLDrawModeAdapter::GetTransform()**](https://github.com/PixarAnimationStudios/USD/blob/v21.08/pxr/usdImaging/usdImagingGL/drawModeAdapter.cpp#L1478-L1492):

> // If the draw mode is instantiated on an instance, prim will be
> // the instance prim, but we want to ignore transforms on that
> // prim since the instance adapter will handle them.

But looks like if the prim in **unloaded**, the instance adapter does not even initialize, thus unloaded instance prim is at origin.

### Steps to Reproduce
1. Open ALab scene or the attached zip file in usdview with unloaded:
```
usdview --unloaded /path/to/alab/USD_ALab_0730/entry.usda
```
2. Locate to the prim `/root/thelab01/workbench_grp/books_magazines01_0001` (ALab) or `/root/sphere01` (attachment)
3. Toggle the instanceable value to see the different:
```
usdviewApi.prim.SetInstanceable(False)
```

### System Information (OS, Hardware)

Centos 7.4

### Package Versions

Official USD version from 20.11 to 21.08

[unloaded_instance_bbox_test.zip](https://github.com/PixarAnimationStudios/USD/files/7035599/unloaded_instance_bbox_test.zip)

**Comment by marktucker** [comment]
In Houdini's draw mode adapter code (we use a custom draw mode adapter plugin), we have replaced the above condition with:
`if (prim.IsLoaded() && prim.IsInstance()) {`

**Comment by csyshing** [comment]
Thanks @marktucker , I did the same patch for our internal version, it's good to know how Houdini handle this case.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6858
