### ISSUE TITLE
The UsdNotice::ObjectsChanged message is broken after UsdStage::Reload

### ISSUE THREAD

**Issue by jpankalainen** [PixarAnimationStudios/USD#1605]
### Description of Issue
Currently when a stage is reloaded and an ObjectsChanged notice is sent, the sent message contains invalid data. The _infoChanges and _resyncChanges maps seem to be using deleted memory. For release builds this seems to work most of the time, since the memory is not yet reused for anything when accessing the message, but since debug builds (at least on windows) always clear the freed memory, the data is garbage and always causes a crash. 

Looks like the maps are broken as soon as the SdfChangeBlock in SdfLayer::ReloadLayers is out of scope, so they probably get references to some local variables related to the change block. 

### Steps to Reproduce
Run the gist here https://gist.github.com/jpankalainen/8385cfccce3b81fd0dfdb860e7461aa5 with a debug build

### System Information (OS, Hardware)
Windows 10, VS 2019

### Package Versions
USD 21.08

### Build Flags
--no-usdview --no-imaging --build-monolithic --debug

**Comment by jpankalainen** [comment]
Looks like wrapping the Reload request into another SdfChangeBlock keeps the references alive and is a good enough workaround for me at least for now.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6869

**Comment by sunyab** [comment]
Hi @jpankalainen, thanks for the report. I can reproduce this issue over here and I think I've identified how this is happening. I'm looking into fixes now and hope to have something pushed to dev soon. Thanks!
