### ISSUE TITLE
Failed to Build Boost

### ISSUE THREAD

**Issue by methot-ilya-3ds** [PixarAnimationStudios/USD#1612]
### Description of Issue

Boost build fails with `ERROR: Failed to run 'b2 --prefix="C:\USDInstall\build" --build-dir="C:\USDInstall\build\build" -j12 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-program_options --with-regex --with-python --user-config=python-config.jam toolset=msvc-14.1 install'
See C:\USDInstall\build\src\boost_1_70_0\log.txt for more details.`

log file here: 

[log.txt](https://github.com/PixarAnimationStudios/USD/files/7124690/log.txt)

### Steps to Reproduce
1. Launch the x64 Native Tools CMD
2. Run Build_usd.py

### System Information (OS, Hardware)

Windows

**Comment by sunyab** [comment]
Hi @methot-ilya-3ds, it looks like you're running into an issue with the boost build and the Windows limitation on the size of commands in .bat files. If you look at the file mentioned in the log:

 `C:\USDInstall\build\build\boost\bin.v2\standalone\msvc\msvc-14.1\address-model-64\msvc-setup.bat` 

You'll probably see a line that is extremely long (> 8k) . If you do see something like that, it's more than likely it'll be something to do with your PATH env variable having too many (or too long) entries. Reducing those entries in your Windows system configuration and then re-running the build script should help.

**Comment by methot-ilya-3ds** [comment]
@sunyab That was it! Thank you so much
