### ISSUE TITLE
OpenAsset called multiple times

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#1613]
### Description of Issue

I have a custom asset resolver that does some downloading of data during `_OpenAsset`.
However I see that for `.usd` and `.usdz' files, that USD calls OpenAsset twice before succeeding.
The only difference seems to be that one of the times it calls GetUnsafeFile from the resulting ArAsset (oddly the order seems reversed for `.usd` and `.usdz` files.

For more context, I have a custom resolver that is downloading data during OpenAsset, passing that data into a custom ArAsset that then in turn gives the data to USD. Subsequent calls to OpenAsset therefore cause a redownload of the data, and a regeneration of the Asset, even though the actual buffer that both Assets own is going to be byte-identical.

### Steps to Reproduce
1. Pick your method of seeing when a method is called (I'm just adding a `std::cout << "Opening Asset: " << resolvedPath.GetPathString() << std::endl;` to the head of `_OpenAsset`
2. Try and run `pxr.Usd.Stage.Open` on any `.usd` or `.usdz` file.
3. See that it gets called twice

### System Information (OS, Hardware)

macOS 11 on an x86 iMac Pro

### Package Versions

* USD 21.8
* Boost 1.72.0
* Python-3.7.5
* TBB 2020_U2

**Comment by jilliene** [comment]
Filed as internal issue #USD-6889
