### ISSUE TITLE
UsdImaging should be strict about case for the <UDIM> filename substitution

### ISSUE THREAD

**Issue by spiffmon** [PixarAnimationStudios/USD#1618]
### Description of Issue
See [this thread](https://groups.google.com/g/usd-interest/c/drIa_4jXaao/m/37wLIWtKCQAJ) . The claim is that for non-relative URI's, we honor `<udim>` as well as `<UDIM>`.  We should not.

### Steps to Reproduce
1.

**Comment by spitzak** [comment]
"The claim is that for non-relative URI's, we honor `<udim>` as well as `<UDIM>`. We should not."

**Comment by spiffmon** [comment]
But that's only in Moonray, right, @spitzak ?  Storm does not honor <udim>

**Comment by spitzak** [comment]
I was just trying to fix the issue description, the angle brackets broke it.

**Comment by spiffmon** [comment]
Ah thanks, @spitzak - I hadn't noticed!

**Comment by jilliene** [comment]
Filed as internal issue #USD-6896

**Comment by c64kernal** [comment]
The awesome @clach double checked that we should only honor all-caps <UDIM>, closing out.
