### ISSUE TITLE
Materials not showing up on point instancer prototypes marked as instanceable

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1626]
### Description of Issue
When a prototype of a point instancer is an instancebale reference, that prototype doesn't show its bound materials.
A variety of minor tweaks can be made to make the materials show up:
* bind the material to the instanceable prototype prim instead of to the prims inside
* Add a geometry subset to the mesh inside the prototype
* Turn off the instanceable flag on the prototype
This appears to be aregression since 20.08, but I've only tested with 21.05 and 21.08, and both fail, so I believe this broke sometime between 20.08 and 21.05. My suspicion is that it has to do with this change: https://github.com/PixarAnimationStudios/USD/commit/d9fa8e07b78592b43401fe38d1c13f35374a963d

### Steps to Reproduce
1. Open cuberef.usda and cubeinst.usda in usdview from the attached zip file:
[instancematerials.zip](https://github.com/PixarAnimationStudios/USD/files/7192864/instancematerials.zip)
2. Notice that cueref shows a blue cube (from the bound USD preview surface), but cubeinst shows a grey cube (no material).

### System Information (OS, Hardware)
Tested on Windows, almost certainly affects all.

### Package Versions
Broken in 21.05 and 21.08, issue does not exist in 20.08

**Comment by jilliene** [comment]
Filed as internal issue #USD-6907
