### ISSUE TITLE
Unicode characters do not properly roundtrip USDC/USDA with usdcat (causing crashes)

### ISSUE THREAD

**Issue by PixelPartner** [PixarAnimationStudios/USD#1639]
### Description of Issue
usdcat 20.08 does not properly handle multibyte unicode characters in string values.

### Steps to Reproduce
1. Encode a string and write to USDC (I used Apple RealityComposer):
   "Draußen im Freien"
2. Use usdcat to make it human readable:
    string content = "Drau\xc3\x9fen, im Freien"
    (This seems to be the proper UTF-8 multibyte encoding according to https://www.compart.com/de/unicode/U+00DF)
3. Use usdcat twice to go to USDC and back to USDA: 
    string content = "Drau\xc3\xfdn, im Freien"
    The encoding changed and the next "normal" character "e" is missing
4. The file sizes of .usdc before and after conversion to ASCII differ significantly:
    (208.489 to 208.757)
5. Re-Importing the USDC (usdzip-ed) into RealityComposer crashes it.

### System Information (OS, Hardware)
macOS Monterey, M1 using Rosetta2

### Package Versions
I'm using the Apple distribution of 20.08 (?)

### Attachments
[Archiv.zip](https://github.com/PixarAnimationStudios/USD/files/7276475/Archiv.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6943

**Comment by c64kernal** [comment]
Thanks for the report @PixelPartner -- this issue should be resolved in the upcoming release of USD (21.11). However, in order to truly address your issue, Apple will need to adopt the new version, so it would be a good idea to let them know about this as well. Thanks!
