### ISSUE TITLE
Maya To Hydra (MtoH) built with PixarUSD 21.08 or later: Selection issue on hdRPR and Arnold render delegates

### ISSUE THREAD

**Issue by Vsevolod1983** [PixarAnimationStudios/USD#1643]
### Description of Issue
Hello !
I use Pixar USD within Maya To Hydra (MtoH) project for rendering using hdRPR render delegate.
Actually the problem I'm going to share also gets reproduced on Arnold render delegate as well.

I have strange issue regarding selection. When I select any object in Maya, e.g. simple cube, all rendered picture suddenly disappears  in the viewport (for hdRPR or Arnold Hydra render delegate).
I made some investigation and figured out that PixarUSD 21.05 works ok, problem started to appear on PixarUSD 21.08

Some investigation regarding commits:
Pixar USD 21.05 (090ef0d) - works ok, selected mesh is fully filled with yellow color.

Starting from commit Apr 15
c1d846cb7e060d0387c1ab2a77713ca5eeb9e9e4 ([Hgi] Added buffer binding support for Hgi shader codegen)
 - selection works but selected mesh looks like just outlined (not fully filled with yellow color).

![image](https://user-images.githubusercontent.com/7079246/136051286-18790ac3-3855-460a-99df-a28361bba709.png)

commit Apr 27
36223b80d5bfb2d6c8d66efe2f452ed4591f80c3 (Do not restore framebuffer in HgiGLScopedStateHolder and HgiInterOpOpenGL.)   - selection does not work at all. If any of meshes is selected, the entire rendered image gets disappeared.

![image](https://user-images.githubusercontent.com/7079246/136051881-4915b8dc-7f0a-48c5-9245-6912b2c29841.png)

If disable ColorizeSelectionTask - image does not get disappeared but obviously selection does not work.

I see no issues while using the same render delegate hdRPR in USD Viewer application with any version of PixarUSD (21.05, 21.08, 21.11).  So it looks like something wrong with the way how Maya viewport interacts with graphics low level of PixarUSD. 
All commits I mentioned above have changes in things regarding textures, GL calls, etc.

Does anybody can help with that ?
Thank you!

### Steps to Reproduce
1. Use MtoH plugin with PixarUSD 21.08 or later
2. Select Hydra Render Delegate (Use Arnold render delegate for example)
3. Make a cube and select it
4. Notice that the entire image gets disappeared.

### System Information (OS, Hardware)
Win10, AMD 6900 XT or NVidia 2080 Supper
### Build Flags
--openimageio

**Comment by spiffmon** [comment]
Hi @Vsevolod1983 , Pixar does not develop the Maya USD or Hydra plugins, and I'm afraid we can't really debug them.  This report might better be made on the [MayaUSD gitHub](https://github.com/Autodesk/maya-usd/issues) or maybe even the primary Maya bug reporting system.

Thanks, and good luck!

**Comment by Vsevolod1983** [comment]
The idea of my message was: it works if built against PixarUSD 21.05 and does not work against PixarUSD 21.08. I shown commits in PixarUSD which breaks this. But yes I will post to mtoh as well.
Thank you.

**Comment by spiffmon** [comment]
I think your efforts will prove useful to the autodesk team!  We do not yet use the AD plugins extensively (we are working towards being able to adopt them more deeply), though all our imaging code is exercised extensively in Presto. While it is possible there are problems with the checkins you noted, they might also imply needed changes to the AD code, and it often takes vendors some time to adapt to and support more recent versions of USD. 

thanks again!
