### ISSUE TITLE
certificate issues with azure pipelines

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#1644]
### Description of Issue

You've likely already noticed, but the azure pipelines are breaking due to certificate issues (looks like the "Let's Encrypt" root certificate issue from https://github.com/PixarAnimationStudios/USD/commit/22853b19d5c8fe6aec775c1b1bbbbc2bc59b83cc).

ie:

https://dev.azure.com/PixarAnimationStudios/USD/_build/results?buildId=476&view=logs&j=634e1348-c499-5b94-89f2-337e64c005be&t=80442506-ce3d-5ef0-3fb6-749a4e47649d&l=251

### Steps to Reproduce
1. Trigger a PyPI_Packaging azue build

**Comment by sunyab** [comment]
Thanks @pmolodo, we're IP on a fix right now.

**Comment by sunyab** [comment]
Filed as internal issue #USD-6949
