### ISSUE TITLE
IsInert reports false on empty variant PrimSpecs since v0.21.5

### ISSUE THREAD

**Issue by jonjondev** [PixarAnimationStudios/USD#1652]
### Description of Issue
Pre-`v0.21.5`, `SdfSpec::IsInert` could be used to check whether a variant brought in any opinions on a variant `PrimSpec`, where an empty variant would be considered "inert".

Since including required fields as part of `SdfLayer::ListFields` in commit https://github.com/PixarAnimationStudios/USD/commit/b7648a669a8a6c7c63689541d581399c5097024c, this particular case will result in `IsInert` reporting that the variant is no longer inert (`False`).

@gitamohr [requested for this to be filed as an issue on the USD Interest Group](https://groups.google.com/g/usd-interest/c/_5h46ZhivT4).

### Steps to Reproduce
With the following file contents:

**test.usda**
```java
#usda 1.0

over "test"
{
    variantSet "vars" = {
        "off" {
        }
        "render" (
            payload = @...@
        ) {
        }
    }
}
```

**test.py**
```py
from pxr import Sdf
layer = Sdf.Layer.FindOrOpen("./test.usda")
layer.GetPrimAtPath("/test{vars=off}").isInert
```

`isInert` will report `False` under USD `v0.21.5+`, and `True` for any previous version.

**Comment by jilliene** [comment]
Filed as internal issue #USD-6960
