### ISSUE TITLE
Cmake can't find libraries

### ISSUE THREAD

**Issue by Animatect** [PixarAnimationStudios/USD#1655]
Hi I'm trying to install USDview using the script but can't seem to be able to get past cmake, as far as I can see it can't find pyside and other libraries that I have installed, I'm even specifying the python version to be used and nothing
Here is what the console provides
C:\Users\Equipo 1>C:\python27\python.exe USD\build_scripts\build_usd.py "C:\tmp\USD"

Building with settings:
  USD source directory          C:\Users\Equipo 1\USD
  USD install directory         C:\tmp\USD
  3rd-party source directory    C:\tmp\USD\src
  3rd-party install directory   C:\tmp\USD
  Build directory               C:\tmp\USD\build
  CMake generator               Default
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          Off
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  On
    Python support              On
      Python 3:                 Off
    Documentation               Off
    Tests                       Off
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  None
STATUS: Installing USD...
2021-10-12 20:49
cmake -DCMAKE_INSTALL_PREFIX="C:\tmp\USD" -DCMAKE_PREFIX_PATH="C:\tmp\USD" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 16 2019" -A x64  -DPXR_PREFER_SAFETY_OVER_SPEED=ON -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE="C:\python27\python.exe" -DPYTHON_LIBRARY="C:\python27\libs\python27.lib" -DPYTHON_INCLUDE_DIR="C:\python27\Include" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EXAMPLES=ON -DPXR_BUILD_TUTORIALS=ON -DPXR_BUILD_USD_TOOLS=ON -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_ENABLE_OPENVDB_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_ENABLE_MATERIALX_SUPPORT=OFF -DCMAKE_CXX_FLAGS="/Zm150" -DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True "C:\Users\Equipo 1\USD"
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30136.0
-- The CXX compiler identification is MSVC 19.29.30136.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/defaults/ProjectDefaults.cmake:34 (message):
  Building USD on Windows is currently experimental.
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found Boost: C:/tmp/USD/include/boost-1_70 (found version "1.70.0")
-- Disabling boost-provided cmake config
-- Found PythonInterp: C:/Python27/python.exe (found suitable version "2.7.16", minimum required is "2.7")
-- Found PythonLibs: C:/Python27/libs/python27.lib (found suitable version "2.7.16", minimum required is "2.7")
-- Found Boost: C:/tmp/USD/include/boost-1_70 (found version "1.70.0") found components: program_options
-- Found Boost: C:/tmp/USD/include/boost-1_70 (found version "1.70.0") found components: python27
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jinja2
-- Found TBB: C:/tmp/USD/include (found version "2018.0") found components: tbb
CMake Deprecation Warning at cmake/defaults/Packages.cmake:204 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include)

-- Found OpenGL: opengl32
-- Found OpenSubdiv: C:/tmp/USD/include (found suitable version "3.4.3", minimum required is "3")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named PySide2
-- Found PySide but NOT pyside-uic binary
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PySide (missing: PYSIDE_AVAILABLE PYSIDEUICBINARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPySide.cmake:75 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:273 (find_package)
  CMakeLists.txt:23 (include)

-- Configuring incomplete, errors occurred!
See also "C:/tmp/USD/build/USD/CMakeFiles/CMakeOutput.log".
See also "C:/tmp/USD/build/USD/CMakeFiles/CMakeError.log".
2021-10-12 22:05
cmake -DCMAKE_INSTALL_PREFIX="C:\tmp\USD" -DCMAKE_PREFIX_PATH="C:\tmp\USD" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 16 2019" -A x64  -DPXR_PREFER_SAFETY_OVER_SPEED=ON -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE="C:\python27\python.exe" -DPYTHON_LIBRARY="C:\python27\libs\python27.lib" -DPYTHON_INCLUDE_DIR="C:\python27\Include" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EXAMPLES=ON -DPXR_BUILD_TUTORIALS=ON -DPXR_BUILD_USD_TOOLS=ON -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_ENABLE_OPENVDB_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_ENABLE_MATERIALX_SUPPORT=OFF -DCMAKE_CXX_FLAGS="/Zm150" -DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True "C:\Users\Equipo 1\USD"
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Warning at cmake/defaults/ProjectDefaults.cmake:34 (message):
  Building USD on Windows is currently experimental.
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

-- Found Boost: C:/tmp/USD/include/boost-1_70 (found version "1.70.0")
-- Disabling boost-provided cmake config
-- Found Boost: C:/tmp/USD/include/boost-1_70 (found version "1.70.0") found components: program_options
-- Found Boost: C:/tmp/USD/include/boost-1_70 (found version "1.70.0") found components: python27
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jinja2
CMake Deprecation Warning at cmake/defaults/Packages.cmake:204 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named PySide2
-- Found PySide but NOT pyside-uic binary
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PySide (missing: PYSIDE_AVAILABLE PYSIDEUICBINARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPySide.cmake:75 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:273 (find_package)
  CMakeLists.txt:23 (include)

I know i'm probably doing something wrong but I'm inexperienced with CMake and it is not obvious to me, If someone has an idea or can point me to somewhere where I can keep looking I would really appreciate it.

**Comment by sunyab** [comment]
Hi @Animatect, from the log output it appears that the build can't find the pyside-uic program. You'll likely need to update your PATH environment variable so it includes the directory containing pyside-uic. I think that's typically found in "C:\Python27\Scripts", but that may differ depending on how you installed PySide.

**Comment by Animatect** [comment]
hey @sunyab, that was it!, thank you so much!
