### ISSUE TITLE
HdMtlx does not work with Houdini's mtlx UsdShade graphs

### ISSUE THREAD

**Issue by hshakula** [PixarAnimationStudios/USD#1658]
### Description of Issue
Using `HdMtlxCreateMtlxDocumentFromHdNetwork` on `HdNetwork` when `UsdShade` graph is constructed from Houdini's Mtlx nodes leaks `MaterialX::Exception` due to elements with duplicate names.

### Steps to Reproduce
1. Set up material with 2 or more Mtlx nodes in Houdini
2. Pass resulting `HdNetwork` to `MaterialX::Document` using `HdMtlxCreateMtlxDocumentFromHdNetwork`

**Comment by spiffmon** [comment]
Hi @hshakula , it would be helpful if you could attach a usda file that illustrates the problem, which would help identify whether it is actually a Solaris issue or an Hd issue.

Thanks!

**Comment by hshakula** [comment]
[mtlxTest.zip](https://github.com/PixarAnimationStudios/USD/files/7362857/mtlxTest.zip)

My proposed solution is #1659

**Comment by jilliene** [comment]
Filed as internal issue #USD-6972

**Comment by hshakula** [comment]
Fixed in #1659
