### ISSUE TITLE
can't find pxr.Usdviewq

### ISSUE THREAD

**Issue by Animatect** [PixarAnimationStudios/USD#1662]
Hi, I already was able to compile everything using the script, but when I try to run usd view I get this error:

C:\tmp\USD\bin>C:\python27\python.exe usdview
Traceback (most recent call last):
  File "usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
ImportError: No module named pxr.Usdviewq

I've tried this with 64bit dev console from VS and from regular console, my env variables on path are set up as follows:

C:\Python27\Scripts
C:\tmp\USD\lib\python
C:\tmp\USD\bin
C:\tmp\USD\lib
C:\Python27\Lib\site-packages
C:\Python27

It's worth mentioning that I also have pyenv, I don't know if this may be messing with the set up, the pxr.Usdviewq package is clearly there so I can't figure out what might be the issue.

I'm on windows using the latest package with the default flags on a Ryzen 9 with 64gb of ram and an RTX 3060

anyone has an idea of where I can looking for the issue?

thank you.

**Comment by meshula** [comment]
Is the usdviewq.dll (and all the other USD dll's of course) in both your PATH and your PYTHON_PATH? I'd start by checking that.

**Comment by Animatect** [comment]
I have a usdviewq.dll, it is on USD\lib, which is on my path file, but the error seems to be from a python file looking for the usdviewq library on the pxr folder, which is there, it just does not seems to find the path to it, maybe I assigned the path wrong, is there something I should do to force it to look inside the USD\lib\python directory?

the file that is giving me the error should be this one:
I don't know if it should be able to import a directory reading the path file


from __future__ import print_function
import sys
import pxr.Usdviewq as Usdviewq

if __name__ == '__main__':
    # Let Ctrl-C kill the app.
    import signal
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    try:
        Usdviewq.Launcher().Run()
    except Usdviewq.InvalidUsdviewOption as e:
        print("ERROR: " + e.message, file=sys.stderr)
        sys.exit(1)

**Comment by jilliene** [comment]
Filed as internal issue #USD-6976

**Comment by Animatect** [comment]
The problem was wit the assignation of the variables as user variables, sorry for the rookie mistake

**Comment by meshula** [comment]
Glad you worked it out!
