### ISSUE TITLE
Point Instancer Transform collapses when referenced under Instanceable Prim

### ISSUE THREAD

**Issue by caammann** [PixarAnimationStudios/USD#1663]
### Description of Issue
Transforms on PointInstancer prims get discarded when nested under a prim which gets referenced as Instanceable.
Possibly related to #1622 

### Steps to Reproduce
1. Load the following example in usdview: [nestedPointInstancerTransform.zip](https://github.com/PixarAnimationStudios/USD/files/7389666/nestedPointInstancerTransform.zip)
2. The "instancer1" PointInstance prim includes a translation in y.
3. That translation persist when referenced "non-instanceable" (/nonInstanceable prim), but gets lost when referenced "instanceable" (/Instanceable prim)

### System Information (OS, Hardware)
Windows

### Package Versions
21.08

**Comment by jilliene** [comment]
Filed as internal issue #USD-6979

**Comment by ZimuQin** [comment]
Any updates on this?

**Comment by spiffmon** [comment]
Coincidentally we have been working on other reported issues related to this (Issue #2359) , and think we should have a fix for this problem soon also - thanks for your patience!
