### ISSUE TITLE
Scene Index Emulation breaks some MaterialX features

### ISSUE THREAD

**Issue by vlasovi** [PixarAnimationStudios/USD#1665]
### Description of Issue

- Scene Index Emulation is enabled by default (HD_ENABLE_SCENE_INDEX_EMULATION), which makes use of HdSceneIndexAdapterSceneDelegate class 
- Inside HdSceneIndexAdapterSceneDelegate::GetMaterialResource we convert legacy HdMaterialNetworkSchema to HdMaterialNetworkMap, but this conversion is lossy because the legacy schema doesn't have primvars in it (TfTokenVector primvars).
- Those primvars are needed for MaterialX 'geompropvalue' nodes to work properly.

**- In my opinion, it would be ideal if HD_ENABLE_SCENE_INDEX_EMULATION was set to false by default** 

### Steps to Reproduce

1. Have a MaterialX file with 'geompropvalue' in it. Example:

```
 <?xml version="1.0"?>
 <materialx version="1.38">
   <UsdPreviewSurface name="SR_gold" type="surfaceshader">
     <input name="diffuseColor" type="color3" output="diffuseColor" nodegraph="ComputeDiffuseColor" />
     <input name="useSpecularWorkflow" type="integer" value="1" />
     <input name="specularColor" type="color3" value="0, 0, 0" />
     <input name="metallic" type="float" value="0.0" />
     <input name="roughness" type="float" value="0.00" />
     <input name="ior" type="float" value="50" />
   </UsdPreviewSurface>
   <surfacematerial name="USD_Gold" type="material">
     <input name="surfaceshader" type="surfaceshader" nodename="SR_gold" />
   </surfacematerial>
   <nodegraph name="ComputeDiffuseColor">
     <geompropvalue name="n1" type="color3">
       <input name="geomprop" type="string" value="vertexColor2" />
     </geompropvalue>	
     <output name="diffuseColor" type="color3" nodename="n1" />
   </nodegraph>
 </materialx>
 

```
2. Have a usda file with geometry that has this primvar specified. Example: 

```
 #usda 1.0
 
 def Scope "MaterialX"(
     references = [
 		@./surface_with_geomcolor.mtlx@</MaterialX>,
 	]
 )
 {
 }
 
 def Mesh "Mesh01"
 {
 	uniform bool doubleSided = 0
 	int[] faceVertexCounts = [4]
 	int[] faceVertexIndices = [0, 1, 2, 3]
 	rel material:binding = </MaterialX/Materials/USD_Gold>
 	point3f[] points = [(-3, -3, -3), (3, -3, -3), (3, 3, -3), (-3, 3, -3)]
 	matrix4d xformOp:transform = ( (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1) )
 	double3 xformOp:translate = (0, 0, -2)
 	uniform token[] xformOpOrder = ["xformOp:transform", "xformOp:translate"]
 	
 	color3f[] primvars:vertexColor2 = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)] (interpolation = "vertex")
 }
 

```
3. Open it in usdview and observe that the quad is black. This is the bug.
4. Now change the environment variable HD_ENABLE_SCENE_INDEX_EMULATION to false.
5. Repeat the step 3 and observe that now the quad is colored. 

### System Information (OS, Hardware)

Windows

### Package Versions

Latest dev

### Build Flags

--materialx

**Comment by jilliene** [comment]
Filed as internal issue #USD-6981

**Comment by c64kernal** [comment]
Thanks so much for flagging this @vlasovi -- we're investigating asap.
