### ISSUE TITLE
Hydra does not apply assigned material when missing at gprim populate time

### ISSUE THREAD

**Issue by aloysbaillet** [PixarAnimationStudios/USD#1669]
### Description of Issue
If a geometry has a material assignment which does not exist at load time, loading the materials after the stage has been rendered will not detect the new material and will not apply it.
This can happen with deactivating the parent prim of a Material being used by a mesh, then reactivating that parent prim.

The reason seems to be that material delegates only get created when a gprim is populated: https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usdImaging/usdImaging/gprimAdapter.cpp#L157
And if the Material prim does not exist then the dependency info is never generated for the missing material.

There could be quite a few ways to fix this issue, and I'm considering which way would be best. In order to maintain current performance I'm leaning towards adding a new `UsdImagingDelegate::_missingDependencyInfo` that would gather all missing material paths, and would be checked against when `_ResyncUsdPrim` is called.
Thoughts?

### Steps to Reproduce
1. Download the test file [simpleMatBind.usda.txt](https://github.com/PixarAnimationStudios/USD/files/7422944/simpleMatBind.usda.txt) (kindly prepared by @asluk !) and rename to simpleMatBind.usda
2. Open the file in usdview
3. Select the `/World/Looks` prim and right-click  menu : Deactivate
4. Blue cube becomes white: expected
5. With `/World/Looks` still selected, right click and select Activate
6. Cube stays white: unexpected, the cube should be back to blue as the material now exists in the stage

N.B. that the same thing happens if you save the stage with the `/World/Looks` prim unloaded, loading the prim does not make the re-attach the blue material to the cube.

N.B. that if the `/World/Looks/PreviewSurface` itself is unloaded the material reappears when the Material prim is loaded, the reason seems that the prim path still appears in the `_dependencyInfo` delegate cache.

### System Information (OS, Hardware)
Windows and Linux

### Package Versions
USD 20.08 to USD 21.11

### Build Flags
`--imaging`

**Comment by jtran56** [comment]
Filed as internal issue #USD-6991

**Comment by tcauchois** [comment]
Just for context, is there a particular way you're structuring your assets or workflows that is triggering this bug?

**Comment by aloysbaillet** [comment]
Sorry about the delayed answer, I don't think there is any particular way for the assets to be organized to trigger this. The attached usda file shows a very simple example but it wasn't much more complex in our case. I believe the same scenario can be triggered during the "redo" of a prim deletion as well.

**Comment by tallytalwar** [comment]
I believe this is addressed by change https://github.com/PixarAnimationStudios/OpenUSD/commit/161873983c86c24acf7953430a6277713cc0a202.

Thanks
