### ISSUE TITLE
Both Storm and Prman delegate have problems with UsdPrimvarReader_float3 fallback value

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#1683]
### Description of Issue
Prman gets black instead of fallback value. Storm just seems to mess up entirely, changing other settings and even leaving the fallback shading messed up.

### Steps to Reproduce
1. usdview the attached file. Try it in storm and prman, and turn the use of shaders on/off. This is the expected result
2. Remove the /World/primvars:displayColor attribute (I could not figure out how to do this other than to edit the usda file), and try again.
3. In prman it acts like the color is black (or at least very dark)
4. In Storm everything renders transparent.

### System Information (OS, Hardware)
Linux

### Package Versions
USD 20.11
[UsdPreviewSurface.usda.gz](https://github.com/PixarAnimationStudios/USD/files/7530943/UsdPreviewSurface.usda.gz)

**Comment by spitzak** [comment]
![previewprman](https://user-images.githubusercontent.com/1229073/141595601-c8d1401f-6b23-4ec0-8fc9-53a6e233994b.png)
![prmanpreview](https://user-images.githubusercontent.com/1229073/141595603-e8029cc5-c491-47fc-bc6f-f524cedd1964.png)

**Comment by spiffmon** [comment]
See also @spitzak 's [description of fallback behavior on usd-interest](https://groups.google.com/d/msgid/usd-interest/CAL-8oAjr1L1%3D%2B9488%3D_u%2BJS1182t0WzF8T%3D1AZRz_X83Dd8hTg%40mail.gmail.com?utm_medium=email&utm_source=footer) .

@spitzak , regarding your #2 above, that is what `UsdAttribute::Block()` is for.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7024

**Comment by spitzak** [comment]
Some clarification: storm appears to be ignoring the fallback value for the color, just like PrMan.

Storm has another problem: if the "fallback" shader is not run first then it seems to be left in a bad state and all the objects are transparent. This can be shown by rendering the above file (which has UsdPreviewSurface assigned to everything) in usdview with "use scene materials" set to on. Contrast to what you get if "use scene materials" is off when you start usdview and you turn it on, in which case I think it is rendering correctly (except the color is wrong).

**Comment by spitzak** [comment]
Although it is not really a fix, it might make sense to alter UsdPreviewSurface so the default color is (.5,.5,.5), so it matches the fallback shader whether or not this bug is fixed.
