### ISSUE TITLE
Tests fail to link because of unresolved Boost symbols when not building tools

### ISSUE THREAD

**Issue by bissonm** [PixarAnimationStudios/USD#1698]
### Description of Issue

When building USD with tests enabled (using `--tests`) without tools enabled (using `--no-tools`), some tests won't link.

The problematic tests are using Boost's `program_options`, but after commit 8c0380d6d424855e14a695bdf8e412e9f75fec0d (introduced by PR #1649) we no longer call `find_package` for this component.  Therefore, the tests that are using `Boost_PROGRAM_OPTIONS_LIBRARY` are using an empty variable and are not linking with the library, causing link errors.

See:

- testSdfPathThreading : https://github.com/PixarAnimationStudios/USD/blob/8c0380d6d424855e14a695bdf8e412e9f75fec0d/pxr/usd/sdf/CMakeLists.txt#L267
- testUsdStageThreading : https://github.com/PixarAnimationStudios/USD/blob/8c0380d6d424855e14a695bdf8e412e9f75fec0d/pxr/usd/usd/CMakeLists.txt#L382

### Steps to Reproduce

1. Check out the dev branch (commit 8c0380d6d424855e14a695bdf8e412e9f75fec0d at the time of this writing)
2. Build using the following command: `python build_scripts/build_usd.py ~/path/to/your/build/folder --tests --no-tools`
3. Noticed the unresolved symbols errors

`collect2: error: ld returned 1 exit status`

### System Information (OS, Hardware)

CentOS Linux release 7.9.2009 (Core)

### Package Versions

dev branch, tested on commit 53a6ed3fa45e003d7a61873f9d08c841bda0ac76

### Build Flags

`--tests --no-tools`

**Comment by bissonm** [comment]
@charlesfleche just pinging you to let you know commit 8c0380d6d424855e14a695bdf8e412e9f75fec0d seems to be the cause of this.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7046

**Comment by spiffmon** [comment]
@charlesfleche , do you think you might submit a PR for this?

**Comment by charlesfleche** [comment]
Sure, I'll try to take a look asap.

**Comment by sunyab** [comment]
Closing out old issue, this should have been addressed in the 22.03 release. Thanks!
