### ISSUE TITLE
Inconsistency with missing extension in usdResolverExample

### ISSUE THREAD

**Issue by JamesPedFoundry** [PixarAnimationStudios/USD#1699]
### Description of Issue

Hey, 
Just a small issue to raise here.
We encountered an issue of a missing `.cpp` in the CMakeLists.txt for usdResolverExample:
[extras\usd\examples\usdResolverExample\CMakeLists.txt](https://github.com/PixarAnimationStudios/USD/blob/release/extras/usd/examples/usdResolverExample/CMakeLists.txt#L26)

### Steps to Reproduce
1.  N/A

**Comment by jilliene** [comment]
Filed as internal issue #USD-7053
