### ISSUE TITLE
Locale assumptions in prettyPrint.py

### ISSUE THREAD

**Issue by PeterShinners** [PixarAnimationStudios/USD#17]
Line 32 of Usdviewq/prettyPrint.py sets a hardcoded locale.
```
import locale
locale.setlocale(locale.LC_ALL, 'en_US')
```

My home Linux system, which is not a Redhat or Centos derived platform fails on this line with
```
locale.Error: unsupported locale setting
```

My first thought is setting this locale required? It may impose restrictions on non-Linux platforms. If this call desirable I would wrap it with a `try: except locale.Error:` to allow usdview to work even when the locale is not available.

On my system, here is the output of `locale -a`
```
C
en_US.utf8
POSIX
```

**Comment by amooty** [comment]
Filed as internal issue #135688.

**Comment by spiffmon** [comment]
Resolved with [this commit](https://github.com/PixarAnimationStudios/USD/commit/d0250c341d27fdc3594c7a03af5593b4a510585e)
