### ISSUE TITLE
clang reports virtual destructor warning

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#171]
As far as I can tell this is not going to result in incorrect behavior, but it is warning noise from clang during a build that would be nice to clean up:

```
/extern/usd/pxr/base/vt/value.h:224:12: 'VtValue::_TypeInfo' has virtual functions but non-virtual destructor
```

**Comment by jtran56** [comment]
Filed as internal issue #143748.

**Comment by superfunc** [comment]
Note that this should be cleaned up by 599c71aea7922aada6c5c5e8fa43e6609f152abe

**Comment by meshula** [comment]
Thanks :)
