### ISSUE TITLE
HdRenderBufferDescriptor has no default constructor

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1714]
### Description of Issue
When building USD 21.11, my compiler reported:
F:\dev_tools\src\usd\usd-21.11\USD-py2.7\pxr\imaging\hd\sceneIndexAdapterSceneD
elegate.cpp(865): warning C4700: uninitialized local variable 'desc' used

I think the right solution here is to have a default constructor that initializes the HdRenderBufferDescriptor member variables. Settting format = HdFormatInvalid is obviously the most important, but I assume dimensions and multisampled should be zeroed out as well.

I can submit a PR for this if required, but figured it would be easier/faster for a Pixar employee to do this?

### Package Versions
21.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-7078

**Comment by tcauchois** [comment]
Fixed by https://github.com/PixarAnimationStudios/OpenUSD/commit/8e8ba110094ef2d2ac873e46641ef1136eeacc86
