### ISSUE TITLE
usd-core Python package doesn't include Apple Silicon support

### ISSUE THREAD

**Issue by sleroux** [PixarAnimationStudios/USD#1718]
### Description of Issue

I recently tried to setup the USD python tooling on a M1 Macbook pro by installing the `usd-core` package from PyPi but regardless of which version of Python I used I got:

```
ERROR: Could not find a version that satisfies the requirement usd-core==20.11 (from versions: none)
ERROR: No matching distribution found for usd-core==20.11
```

The only thing I can think of that would be causing this is that USD currently doesn't offer a build of the C++ bindings for the Python library on Apple Silicon.

### System Information (OS, Hardware)

MacOS Monterey 12.1, 2021 M1 Macbook Pro (Apple Silicon) 

### Package Versions

`usd-core` 21.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-7081

**Comment by sunyab** [comment]
Hi @sleroux, as you suspected we currently do not publish native M1 builds of the `usd-core` package on PyPI. However, you should be able to use the published packages via Rosetta on your MacBook. This worked for me on an M1 machine running macOS 12.2.1:

```
# Start a new shell under Rosetta and confirm we're in emulation mode
$ arch -x86_64 zsh
$ arch
i386

# Install usd-core from PyPI
$ python3 -m pip install usd-core
```

Closing this out, but please reopen if you encounter more issues with this. Thanks!

**Comment by sunyab** [comment]
Actually, let me leave this open to track potentially adding a native M1 `usd-core` package in the future. 

It seems like we should be able to set up a 'universal binary' build of the package on Azure and publish that to PyPI, but I'm not 100% certain that's possible or what that might look like. Maybe someone with more experience with this can chime in?

**Comment by jakedouglas** [comment]
It looks like this may be fixed by https://github.com/PixarAnimationStudios/USD/commit/56e59a8b4c6e4c58a813622958135f89f42e7ce3. Will the new universal2 package start being published when there is a new release?

**Comment by sunyab** [comment]
@jakedouglas Yes, it will be. The wheel for the current dev branch is available from Azure for testing if you'd like to give it a spin: https://dev.azure.com/PixarAnimationStudios/USD/_build/results?buildId=2248&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by jakedouglas** [comment]
Thank you!
