### ISSUE TITLE
Documentation: primitiveParams return value from HdMeshUtils::ComputeTriangleIndices is poorly explained

### ISSUE THREAD

**Issue by eliotsmyrl** [PixarAnimationStudios/USD#1720]
The doxygen documentation generated for `HdMeshUtils::ComputeTriangleIndices` says this about the `primitiveParams` return value:
```
 In order to access per-face signals (face color, face selection etc)
we need a mapping from primitiveID to authored face index domain.
This is stored in primitiveParams, and computed along with indices.
```
along with a mysterious ASCII art diagram if you actually look in the code.

This description doesn't explain how to use it at all, and in particular it leaves out the key fact that it's an *encoded* mapping so you'll never get the right answer by playing around with indices and using a debugger.  At the very least this description should say "encoded mapping" instead of just "mapping", and include a reference to the necessary `HdMeshUtils::DecodeFaceIndexFromCoarseFaceParam` - and a code snippet would be even better.

**Comment by zanazakaryaie** [comment]
Exactly. It was also confusing for me. Then I found the ```DecodeFaceIndexFromCoarseFaceParam``` function in the header file and used it to retrieve the face index of each triangle. The documentation should point to this static function

**Comment by jilliene** [comment]
Filed as internal issue #USD-7092

**Comment by davidgyu** [comment]
Hi Eliot!
Those are good suggestions! As you might have guessed, many of these low-level utility classes were originally intended just for use internally within Hydra Storm and we're open to considering what would be more useful in a higher level utility API.
But agree that we could improve the documentation of the existing interfaces.

**Comment by eliotsmyrl** [comment]
Hi @davidgyu!
I think the main thing I'd suggest is what @jcowles already said in #329 - I was really just trying to work around the lack of a high-level Triangulate since our engine requires pre-triangulated meshes.
