### ISSUE TITLE
Instance introspection

### ISSUE THREAD

**Issue by cedricp** [PixarAnimationStudios/USD#1722]
### Description of Issue
I'd like to inspect the primitives on the prototype of an instances UsdPrim ( if prim. IsInstance() ) but both:

**prim.GetPrototype();**

and

**prim.GetFilteredChildrenNames(UsdTraverseInstanceProxies(UsdPrimAllPrimsPredicate))**

incur a costly load of all prim data
is there a workaround - or does this indicate an issue in the API?

### System Information (OS, Hardware)
Linux CentOS7 - x86-64

### Package Versions
v21.05

**Comment by spiffmon** [comment]
Neither of the methods you indicate cause any data to be "loaded" in any sense of the term I can think of - they operate only on already cached data.  Can you please explain more what your concern is?

**Comment by hash-collision** [comment]
Hi thanks for the quick response.
A friend and work colleague posted this for me : I was cynical and did not believe the internet would help me.
But lo and behold I was wrong!
I have very limited knowledge of USD, please allow me to explain the issue, I am looking into it right now and hope you can shed some light on the subject
Pete

**Comment by hash-collision** [comment]
I am writing a USD loader. 
The 1st step loads the usd file, scans the contents and builds a data structure to populate the browser.
I open the file like so:
_usd = UsdStage::Open(filename, UsdStage::LoadNone);

Then I recursively visit all the children to store an array of UsdPrims : this is when a large amount of memory is used - I imagine the geometry is being loaded : something I want to avoid.

I only noted this when traversing to prototypes... and there could be an issue at my end.

Is it okay to store an array of UsdPrims - I assumed these were lightweight handles ( that do not force geo load ) ?

**Comment by hash-collision** [comment]
it seems in conclusion : the problem was at my end
merry christmas everyone

**Comment by spiffmon** [comment]
Glad you are sorted, @hash-collision .  Just to confirm: UsdPrim _is_ a pretty lightweight handle object; you can store them, but if you hand on to them for any length of time (i.e. through authoring/editing operations), make sure you test them for validity before using them, since authoring can make them go invalid.  E.g.
```
if (prims[i]) {
    // do stuff
}

```
Cheers!
