### ISSUE TITLE
How to merge multiple meshes?

### ISSUE THREAD

**Issue by zanazakaryaie** [PixarAnimationStudios/USD#1725]
### Description of Issue
I can decode the mesh and materials in a USD file. But some files contain multiple meshes. For example, a car might be saved with one mesh for the body and 4 other meshes each for one of the tires. How can I merge these 5 meshes into one single mesh?

### System Information (OS, Hardware)
Ubuntu 21 (PC, x64)

### Package Versions
Latest USD version

### Build Flags
Simple python command without enabling python API (I'm using C++)

**Comment by spiffmon** [comment]
Hi @zanazakaryaie , merging meshes robustly is a geometric utility operation that is above the concerns of USD, currently.  I think you'll find the majority of USD scenes contain multiple meshes, and merging meshes is not straightforward if you wish to preserve surface properties as dictated by the bound Materials.  You may find your task easier if you can generalize your app to iterate over multiple, independent meshes.
