### ISSUE TITLE
Debug assertion when a material has no parameters

### ISSUE THREAD

**Issue by williamkrick** [PixarAnimationStudios/USD#1733]
### Description of Issue
USD throws a debug assertion opening a USD file which has a Shader which has no parameters. In release builds this error is not detected and the scene appears to load correctly.

### Steps to Reproduce
```
#usda 1.0
(
    defaultPrim = "GEO"
    metersPerUnit = 0.01
    upAxis = "Y"
)

def Xform "GEO"
{
    def Mesh "BILLBOARD" (
        prepend apiSchemas = ["MaterialBindingAPI"]
        kind = "component"
    )
    {
        uniform bool doubleSided = 1
        float3[] extent = [(-1.5, 0, -1.5), (1.5, 0, 1.5)]
        int[] faceVertexCounts = [4]
        int[] faceVertexIndices = [0, 1, 3, 2]
        rel material:binding = </GEO/Looks/TEXTUREDA>
        point3f[] points = [(-1.5, 0, 1.5), (1.5, 0, 1.5), (-1.5, 0, -1.5), (1.5, 0, -1.5)]
        texCoord2f[] primvars:map1 = [(0, 0), (1, 0), (0, 1), (1, 1)] (
            interpolation = "faceVarying"
        )
        int[] primvars:map1:indices = [0, 1, 3, 2]
    }

	def Scope "Looks"
	{
		def Material "TEXTUREDA"
		{
			token inputs:file1:varname = "map1"
			token outputs:surface.connect = </GEO/Looks/TEXTUREDA/TEXTUREDA.outputs:surface>

			def Shader "TEXTUREDA"
			{
				uniform token info:id = "UsdPreviewSurface"
				token outputs:surface
			}
		}
	}
}
```

1. Open the attached usda file with a debug version of USDView. Debug assertion & crash!
2. If I modify the given scene to add `color3f inputs:specularColor = (1, 1, 1)` to TEXTUREDA then USDView can successfully open the file in debug mode.

The debug assertion occurs when trying to call front on an empty vector. The error occurs in _ConvertHdMaterialNetworkToHdDataSources in dataSourceLegacyPrim.cpp of USD.

### System Information (OS, Hardware)
Windows

### Package Versions
USD 21.11 debug build!

**Comment by spiffmon** [comment]
Nice find, @williamkrick !

**Comment by jilliene** [comment]
Filed as internal issue #USD-7111

**Comment by ikryukov** [comment]
Found similar issue, with MDL Shaders without parameters from omniverse. 
```
        def Material "OmniGlass"
        {
            token outputs:mdl:displacement.connect = </World/Looks/OmniGlass/Shader.outputs:out>
            token outputs:mdl:surface.connect = </World/Looks/OmniGlass/Shader.outputs:out>
            token outputs:mdl:volume.connect = </World/Looks/OmniGlass/Shader.outputs:out>

            def Shader "Shader"
            {
                uniform token info:implementationSource = "sourceAsset"
                uniform asset info:mdl:sourceAsset = @OmniGlass.mdl@
                uniform token info:mdl:sourceAsset:subIdentifier = "OmniGlass"
                token outputs:out
            }
        }
```

**Comment by FlorianZ** [comment]
@seando-adsk , would you mind filing a PR for the change you made on your fork? Thank you!!

**Comment by seando-adsk** [comment]
@FlorianZ Sorry I don't understand what you are asking. I have already created  PR #1791 which was merged.

**Comment by FlorianZ** [comment]
@seando-adsk Sorry, I got this mixed up with state from our internal tracking system. Should be all in sync now. Sorry for the confusion.
