### ISSUE TITLE
HdStorm fails to render a mesh with many material GeomSubsets

### ISSUE THREAD

**Issue by jufrantz** [PixarAnimationStudios/USD#1749]
### Description of Issue

When rendering a mesh with many material subsets in USD 21.11/HdStorm some subsets fail to render.
I attached a simple [usd file](https://github.com/PixarAnimationStudios/USD/files/7897362/manyGeomSubsets.usda.zip) that shows the issue; it contains a mesh with 100 material subsets; 41 last subsets fail to render on our side : 

![many subsets in usdview 21.11](https://user-images.githubusercontent.com/40573039/150141857-b5c55d42-664b-4107-9535-24864e36331d.png)

And we get bunch of errors, like these:
```
Warning: in _ValidateCompilation at line 182 of USD-21.11/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (GL_FRAGMENT_SHADER): 0(2299) : error C1008: undefined variable "HdGet_edgeIndices"

ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_21__pxrReserved__::HdBufferArrayRangeContainer::Set' at line 49 in file USD-21.11/pxr/imaging/hd/bufferArrayRange.cpp : 'Index negative in HdBufferArrayRangeContainer::Set()'
        Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 273 in file USD-21.11/pxr/imaging/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /World/Mesh.'
        Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 292 in file USD-21.11/pxr/imaging/hdSt/drawBatch.cpp : 'Failed verification: ' res ' -- Failed to compile with fallback material network'
        Error in 'pxrInternal_v0_21__pxrReserved__::HdSt_IndirectDrawBatch::ExecuteDraw' at line 1099 in file USD-21.11/pxr/imaging/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
```

### Steps to Reproduce

1. Open the [usd file](https://github.com/PixarAnimationStudios/USD/files/7897362/manyGeomSubsets.usda.zip) in usdview and select GL renderer.

### System Information (OS, Hardware)
- Linux CentOS
- GeForce GTX 1080, Driver Version: 390.87

### Package Versions
- USD 21.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-7150

**Comment by jufrantz** [comment]
I confirm this is fixed, i'm closing the issue. 
Many thanks
