### ISSUE TITLE
USD doesn't link against glibc >= 2.34

### ISSUE THREAD

**Issue by stilllman** [PixarAnimationStudios/USD#1756]
### Description of Issue

In glibc 2.34 the malloc hooks (that have been deprecated since 2.32) have been removed, so applications using them can no longer link. Since `mallocHook.h` relies on those, USD no longer links with newer glibc.

See https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html or https://developers.redhat.com/articles/2021/08/25/securing-malloc-glibc-why-malloc-hooks-had-go for more info.

### Steps to Reproduce

1. Update glibc to a version >= 2.34
2. Build USD
=> The linker produces the following errors:
> /usr/bin/ld: libusd_msd.so: undefined reference to `__malloc_hook'
>
> /usr/bin/ld: libusd_msd.so: undefined reference to `__memalign_hook'
>
> /usr/bin/ld: libusd_msd.so: undefined reference to `__free_hook'
>
> /usr/bin/ld: libusd_msd.so: undefined reference to `__realloc_hook'

### System Information (OS, Hardware)

I had the issue on an up-to-date Fedora 35.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7172

**Comment by stilllman** [comment]
Duplicate of https://github.com/PixarAnimationStudios/USD/issues/1592
