### ISSUE TITLE
Missing HDST_API on HdStTextureIdentifier

### ISSUE THREAD

**Issue by ennis** [PixarAnimationStudios/USD#1758]
### Description of Issue
The non-inline methods on `HdStTextureIdentifier` and the associated impl of `hash_value` seem to be missing the `HDST_API` macro and thus are not exported (at least on windows):

https://github.com/PixarAnimationStudios/USD/blob/faed18ce62c8736b02413635b584a2f637156bad/pxr/imaging/hdSt/textureIdentifier.h#L47-L97

They should probably be annotated with `HDST_API` like the other classes.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7174
