### ISSUE TITLE
Provide an option to turn off HdxSkydomeTask while keeping the UsdLuxDomeLight (IBL) effective

### ISSUE THREAD

**Issue by BlackMojito** [PixarAnimationStudios/USD#1769]
### Description of Issue
Per discussion in this thread (https://groups.google.com/g/usd-interest/c/yfH4MNj5MsQ). 

In our application, we hope to use the UsdLuxDomeLight just as a reflection probe and keep our own background color unmodified (including alpha channel). This means we need to hide the skydome geometry completely but keep the irradiance and radiance texture effective. This was the case in 21.05 as there was no HdxSkydomeTask but in 21.11, it is no longer possible.

### Steps to Reproduce
1. Just create a UsdLuxDomeLight.

### System Information (OS, Hardware)
N/A

### Package Versions
21.11

**Comment by jilliene** [comment]
Filed as internal issue #USD-7218
