### ISSUE TITLE
Error building against latest dev branch: 'GfHalf' was not declared in this scope

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#177]
### Description of Issue

When building against a USD built from the latest dev branch (as of https://github.com/PixarAnimationStudios/USD/commit/b8bd87c84defbb3a45679df10aa2432e137e92d1), you get this error:

```
include/pxr/base/vt/types.h:162:44 error: 'GfHalf' was not declared in this scope
```

From what I can tell, the root of the problem lies with the the pxr_shared_library / _install_headers CMake macros, which don't properly support installing PUBLIC_HEADERS into subdirectories.  As a result, `pxr/base/lib/gf/pxrHalf/half.h` is NOT installed into `pxr/base/gf/pxrHalf/half.h`, but into `pxr/base/gf/half.h` instead, thereby clobbering `pxr/base/lib/gf/half.h`, which is what defines GfHalf.

### Steps to Reproduce
1. Build USD, then inspect the output include dir's pxr/base/gf/pxrHalf/half.h (or try to build against it)

### System Information (OS, Hardware)

CentOS 7

### Package Versions

alembic-1.5.8
boost-1.55.0
gcc-4.8.3
ilmbase-2.2.0
maya-2016.53
ptex-2.1.28
python-2.7.4
qt-4.8.6
tbb-4.3.6

### Build Flags

-D PXR_BUILD_ALEMBIC_PLUGIN=TRUE
-D PXR_MAYA_TBB_BUG_WORKAROUND=TRUE
-D PXR_BUILD_MAYA_PLUGIN=FALSE
-D PXR_BUILD_KATANA_PLUGIN=FALSE
-D PXR_STRICT_BUILD_MODE=TRUE

**Comment by elrond79** [comment]
Also, the headers are "installed" in the build directory correctly (with the pxrHalf subdir) - it's only on install that they lose the pxrHalf subdir...

**Comment by sunyab** [comment]
Thanks for filing this @elrond79, we're looking at this now.

**Comment by jtran56** [comment]
Filed as internal issue #144103.
