### ISSUE TITLE
Is there a way to make C++ resolvers(.dll) work with the USD Python module?

### ISSUE THREAD

**Issue by tzungda** [PixarAnimationStudios/USD#1781]
Hello,

### Description of Issue:
I compiled the USD pacakge(v22.08) and set up the environment variables. Both of the usdcat and usdview work on my side.
However, my own C++ resolver never gets triggered(not even its constructor) through this Python command:
**from pxr import Usd
s = Usd.Stage.Open( "my_file_path" )**

Here is the detail:
I made a dynamic library, **myResolver.dll**, with **C++** by public inheriting the **ArResolver**. This myResolver.dll doesn't link to any dynamic libraries other than the USD ones. Next, I created a plugInfo.json and put it in my C:\USD\myPlugins\myResolver\resources. Also, I put the myResolver.dll in C:\USD\myPlugins\myResolver.

After that, I added this environment variable: PXR_PLUGINPATH_NAME=C:\USD\myPlugins\myResolver\resources.

However, the constructor of myResolver never gets called when I run this Python command:
s = Usd.Stage.Open( "C:\\test\\my_test.myFormat" )

It's very thankful if someone can let me know how to make it work. 
Or do I need to implement another Python module(pyd) and wrap myResolver into it?

This is the content of plugInfo.json:
{
    "Plugins": [
        {
            "Info": {
                "Types": {
                    "MyFormat" : {
                        "bases": ["SdfTextFileFormat"],
                        "displayName": "My Format",
						"extensions":["myFormat"],
						"formatId":"myFormat",
						"primary":true,
						"target":"usd"
                    },
					"myResolver":{
					    "bases":["ArResolver"]
					}
                },
            },
            "LibraryPath": "../myResolver.dll",
            "Name": "myResolver",
            "ResourcePath": "resources",
            "Root": "..",
            "Type": "library"
        }
    ]
}

### System Information (OS, Hardware)
Window 10

### Package Versions
USD v20.08
Python 3.9.7
Visual Studio 2022

### Build Flags
Default dynamic library setup of Visual Studio 2022

**Comment by jilliene** [comment]
Filed as internal issue #USD-7234

**Comment by tzungda** [comment]
I found it can't get the factory at this line of _CreateResolver in resolver_v1.cpp :
Ar_ResolverFactoryBase* factory = resolverType.GetFactory<Ar_ResolverFactoryBase>()

I did add this macro
AR_DEFINE_RESOLVER( myResolver, ArResolver )
But apparently it doesn't set the factory properly. Could someone point me a way to troubleshoot?

Thanks!

**Comment by sunyab** [comment]
@tzungda It sounds like you may be running into #1095. Can you try building your resolver library in debug mode or with `/Zc:inline-` and see if that helps?

**Comment by tzungda** [comment]
@sunyab 
Thank you for the reply. I gave the /Zc:inline- a try but it didn't work. At the moment I am not able to compile my resolver in Debug mode. Any other ideas? Is there another way to call the SetFactory properly through AR_DEFINE_RESOLVER( myResolver, ArResolver ) ?

**Comment by tzungda** [comment]
I dumped the exported symbols with this VS command: dumpbin /EXPORTS myResolver.dll
However, there is no exported symbols. Is it correct? Or should I call the other macros?

Thanks!

**Comment by tzungda** [comment]
After re-compiling with VS2019(not the vc142 in VS2022), everything worked.
