### ISSUE TITLE
usdview does not display auto-generated layer offsets

### ISSUE THREAD

**Issue by nvidia-jomiller** [PixarAnimationStudios/USD#1782]
### Description of Issue
Following up from a thread on [usd-interest](https://groups.google.com/g/usd-interest/c/uH2C6yk8BSo)

For stages that contain sublayers with different `TimeCodesPerSecond` usdview does not show the auto-generated LayerOffset stored in the stage's `PcpLayerStack`.

After following the steps below, the actual LayerOffset for the `./replacements.usda` has a `scale` of 0.8 (default `timeCodesPerSecond` from the root layer (24) / `timeCodesPerSecond` for the `./replacements.usda` sublayer (30) ). However, this information is not visible in the `Layer Stack` tab

### Steps to Reproduce
1. Download and extract [example.zip](https://github.com/PixarAnimationStudios/USD/files/8126547/example.zip)
2. Open `scene.usda` in usdview
3. Select `root` and switch to the `Layer Stack` tab
4. Notice that the `replacements.usda` sublayer does not display any LayerOffset

### System Information (OS, Hardware)
OS: Windows 10 Enterprise
CPU: AMD Ryzen 9 5950X 16-Core Processor
GPU: NVIDIA GeForce RTX 3080

### Package Versions
Tested against [dev](https://github.com/PixarAnimationStudios/USD/commit/0b0db2ebacaf82c8937278bbf650b6e737a558fb)

**Comment by jilliene** [comment]
Filed as internal issue #USD-7241
