### ISSUE TITLE
MaterialX: Two small issues with boolean inputs

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#1784]
### Description of Issue

We found two issues with boolean inputs while developing MaterialX node definitions for use with USD
 - Default values are not copied to SdrNode inputs. Boolean is not a Sdr type, but is recognized as a Sdf one, so the fix is to add a check where the [boolean type is handled](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/usdMtlx/parser.cpp#L142) by the parser: 
```
            type = converted.valueTypeName.GetAsToken();
+            if (type == SdfValueTypeNames->Bool) {
+                defaultValue = UsdMtlxGetUsdValue(element, isOutput);
+            }
```
 - Truth values are inversed when explicitly set. Can be fixed by [swapping "true" and "false"](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdMtlx/hdMtlx.cpp#L120) in hdMtlx.

### Steps to Reproduce

1. Extract the attached MaterialX node definition file [boolean_nodedef.zip](https://github.com/PixarAnimationStudios/USD/files/8135249/boolean_nodedef.zip) in a location that will be read by MaterialX/USD (either in the MaterialX install, or in a location read via the `PXR_MTLX_STDLIB_SEARCH_PATHS` env var).
2. Load the `boolean_nodedef_defaultvalue.usda` from these bundled scenes [boolean_nodedef_scenes.zip](https://github.com/PixarAnimationStudios/USD/files/8135288/boolean_nodedef_scenes.zip) and notice the capsule is green. It should be red because the default value of `use1` is `true`. 
3. Load the `boolean_nodedef_explicit.usda` scene from the scene bundle and notice the capsule is red. It should be green since we explicitly set `use1` to 0.

**Comment by tallytalwar** [comment]
Thanks @JGamache-autodesk for catching this.

For the first issue you found regarding `Boolean` not being a `Sdr` type and checking for `SdfValueTypeNames->Bool` could you do the following instead:

```
             type = converted.valueTypeName.GetAsToken();
+           // Do not use GetAsToken for comparison as recommended in the API
+           if (converted.valueTypeName == SdfValueTypeNames->Bool) {
+                defaultValue = UsdMtlxGetUsdValue(element, isOutput);
+                metadata.emplace(SdrPropertyMetadata->SdrUsdDefinitionType, 
+                          converted.valueTypeName.GetType().GetTypeName())
+           }
```

Without adding the `sdrUsdDefinitionType` metadata, a call to `GetDefaultValueAsSdfType` will incorrectly return the default of the `Bool` type, which is `True`.

Refer https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/sdr/shaderProperty.cpp#L536-L542 and https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/sdr/shaderProperty.cpp#L619 for more details.

A similar thing was recently done for `UsdShadeShaderDef`: https://github.com/PixarAnimationStudios/USD/commit/409b6e9c13153feb0660a7a7dcc3b70e5137dbb9

Please feel free to submit a PR with the fix and please include a test exhibiting this behavior.

Thanks

**Comment by jilliene** [comment]
Filed as internal issue #USD-7242

**Comment by JGamache-autodesk** [comment]
Hi @tallytalwar , thanks for the pre-review. The PR has been submitted.

**Comment by JGamache-autodesk** [comment]
PR has been accepted. Closing issue. Thanks!
