### ISSUE TITLE
MaterialX: Surface NodeDef not found if it has a vector3f input with a set value

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#1785]
### Description of Issue

There is an explicit list of vector3f names in the [_IsInputVector3()](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdMtlx/hdMtlx.cpp#L86) function. This means a new node definition with a vector3 input will only be recognized if the name is one form the list because the input will be created with a color3 type. Things like explicit light direction for NPR shading will not work.

### Steps to Fix

The parameter handling code found in [_AddMaterialXNode()](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdMtlx/hdMtlx.cpp#L215-L225) needs to be used in [_AddParameterInputsToTerminalNode()](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdMtlx/hdMtlx.cpp#L423-L463).

This should allow removing the _IsInputVector3() function.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7243

**Comment by FlorianZ** [comment]
@JGamache-autodesk do you mind creating a PR that implements the fix you outlined above? Thanks for your help!

**Comment by JGamache-autodesk** [comment]
@FlorianZ The PR #1790 that fixes this issue was submitted and accepted. Next release of USD should be fine.

**Comment by FlorianZ** [comment]
Thank you @JGamache-autodesk!
