### ISSUE TITLE
MaterialX: HdMtlx shader fails to compile when MaterialX nodedef has filename input

### ISSUE THREAD

**Issue by ashwinbhat** [PixarAnimationStudios/USD#1786]
### Description of Issue
If a MaterialX nodedef has a `filename` type input that is routed to an `image` node, HdMtlx ShaderGen ignores this input. 
I'm looking for some hints on where/how I could fix this. 

Here is a nodedef with filename input 
```
  <nodedef name="ND_diagimage" node="diagimage" version="1.0.0" isdefaultversion="true">
    <input name="extra_color" type="color3" value="0.6, 0, 0.6"/>
    <input name="diag_file" type="filename" value="diagnostic.png"/>
    <output name="out" type="surfaceshader" />
  </nodedef>

```  
Here is the corresponding nodegraph. 
The nodegraph maps the input filename to the image node.

```
<nodegraph name="IMPL_diagimage" nodedef="ND_diagimage">
    <texcoord name="texcoord" type="vector2" nodedef="ND_texcoord_vector2"/>
    <image name="image0" type="color3" nodedef="ND_image_color3">
      <input name="file" type="filename" interfacename="diag_file" />
      <input name="texcoord" type="vector2" nodename="texcoord" />
    </image>
    
    <add name="add1" type="color3" >
      <input name="in1" type="color3" interfacename="extra_color"  />
      <input name="in2" type="color3" nodename="image0"  />
    </add>
    <uniform_edf name="uniform_edf" type="EDF" >
      <input name="color" type="color3" nodename="add1" />
    </uniform_edf>
    <surface name="diag_shader" type="surfaceshader" >
      <input name="bsdf" type="BSDF" value="" />
      <input name="edf" type="EDF" nodename="uniform_edf" />
      <input name="opacity" type="float" value="1" />
    </surface>
    <output name="out" type="surfaceshader" nodename="diag_shader" />
</nodegraph>

```
Generates the following error:
```
Warning: in _ValidateCompilation at line 213 of pxr\imaging\hdSt\glslProgram.cpp -- Failed to compile shader (FRAGMENT_SHADER): 0(2436) : error C1503: undefined variable "diag_file"
ERROR: Usdview encountered an error while rendering.
```

Expected result from the referenced mtlx file loads in MaterialXVIew 
 ![mtlxview](https://user-images.githubusercontent.com/1727158/155665309-c04e10fe-7573-4106-a37b-6f314c5b5887.png)

### Steps to Reproduce
1.  Extract the files in the zip [mtlx_image_nodedef.zip](https://github.com/PixarAnimationStudios/USD/files/8138981/mtlx_image_nodedef.zip)
2. Copy diagtest_def.mtlx from libraries\bxdf to usd\install\debug|release\libraries\bxdf  (note this can be also be setup by using env variable)
3. open simplediag.usda 
4. Usdview reports error in console
Warning: in _ValidateCompilation at line 213 of  \pxr\imaging\hdSt\glslProgram.cpp -- Failed to compile shader (FRAGMENT_SHADER): 0(2436) : error C1503: undefined variable "diag_file"

### System Information (OS, Hardware)
Windows 10
### Package Versions
v22.03-rc2
### Build Flags
build_scripts\build_usd.py  --build-variant debug --materialx

**Comment by jilliene** [comment]
Filed as internal issue #USD-7244
