### ISSUE TITLE
Assertion failure in dataSourceLegacyPrim on windows in debug mode

### ISSUE THREAD

**Issue by ennis** [PixarAnimationStudios/USD#1794]
The following code:

https://github.com/PixarAnimationStudios/USD/blob/ff1e6fd7387a65fb56c05f2c1ee182bfdba689b9/pxr/imaging/hd/dataSourceLegacyPrim.cpp#L2526-L2529

Sometimes triggers a debug assertion on windows when compiled in debug mode:

```
Debug Assertion Failed!

Program: C:\vcpkg\installed\x64-windows\debug\bin\usd_hd.dll
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector
Line: 1603

Expression: front() called on empty vector
```

It's UB to call [`front`](https://en.cppreference.com/w/cpp/container/vector/front) on an empty vector, and the stdlib of MSVC in debug mode checks for that. I think `.data()` would be more appropriate here, if we have no guarantee that `paramsNames` contains at least one element.
The same pattern of `&container.front()` appears in other parts of the code, it might be a good thing to review them as well.

**Comment by spiffmon** [comment]
Hi @ennis , we have accepted PR #1791 to address this, thanks!
