### ISSUE TITLE
Custom camera attributes aren't considered in `UsdImagingCameraAdapter::TrackVariability`

### ISSUE THREAD

**Issue by robpieke** [PixarAnimationStudios/USD#1797]
### Description of Issue

If you apply a custom schema to a camera (for example to attach a background image) and populate the custom attribute(s) with time-sampled data, Hydra doesn't trigger the appropriate syncing on frame changes. This is due to `UsdImagingCameraAdapter::TrackVariability` having a hard-coded list of attributes to consider.

In contrast, `UsdImagingLightAdapter::TrackVariability` iterates over *all* attributes.

PR for consideration inbound ... basically just copying what the lightAdapter does, at the end of the cameraAdapter :)

**Comment by jilliene** [comment]
Filed as internal issue #USD-7258

**Comment by sunyab** [comment]
PR #1798 was merged and released with v22.08. Closing, thanks!
