### ISSUE TITLE
Have Qt4, but don't have PysideTools, build fails

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#18]
If one has Qt4 but not PysideTools (a likely scenario), the build will fail on usdviewq because it calls the PysideTools to wrap usdviewq. Could we add something like this to the usdviewq/CMakeLists.txt file? (Not sure if PYSIDEUICTOOLS_FOUND the right variable to key from, but you get the gist)

```
 if (NOT QT4_FOUND)
     message(WARNING "Not building ${PXR_PACKAGE} because of missing dependency: Qt4")
     return()
 endif()
 
+if (NOT PYSIDEUICTOOLS_FOUND)
+    message(WARNING "Not building ${PXR_PACKAGE} because of missing dependency: PysideTools")
+    return()
+endif()
+

```

**Comment by amooty** [comment]
Filed as internal issue #135882.
