### ISSUE TITLE
USD build fails with 'uninitialized const member' error

### ISSUE THREAD

**Issue by osiriswrecks** [PixarAnimationStudios/USD#1801]
### Description of Issue
When building from source on CentOS 7, I get an 'uninitialized const member' error when building timing.cpp. Full USD install log is attached.

### Steps to Reproduce
1. Run build command per installation instructions.

### System Information (OS, Hardware)
CentOS 7 64-bit
Intel Core i9-10900K CPU
32GB RAM
NVIDIA GeForce GTX 1080
Gnome 3.28.2

### Package Versions
Boost 1.66.0
Latest Jinja2, Pyside2, and PyOpenGL

### Build Flags
All defaults, nothing special

[log.txt](https://github.com/PixarAnimationStudios/USD/files/8217229/log.txt)
.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7267

**Comment by a1744633** [comment]
#1801
Hello there @osiriswrecks. I had this same issue but upgrading the gcc to gcc 6.3.1 as per [VERSIONS.md](https://github.com/PixarAnimationStudios/USD/blob/release/VERSIONS.md) fixes this. I hope that helps!

**Comment by osiriswrecks** [comment]
@a1744633 Ah, ok. I installed gcc 6.2 I think, which might explain why it didn't work. I had to revert back to the default gcc install though, because installing 6.2 broke other applications. I might spin up a VM to try this again with gcc 6.3.1. Thanks!

**Comment by sunyab** [comment]
Closing this out, please reopen or file a new issue if using gcc 6.3.1 doesn't help. Thanks all!
