### ISSUE TITLE
USD build fails with ''gbk' codec can't decode byte 0x82 in position 819: illegal multibyte sequence' error

### ISSUE THREAD

**Issue by MChenLiang** [PixarAnimationStudios/USD#1806]
### Description of Issue
when building with python

### Steps to Reproduce
1. run in Native Tools Command Prompt for VS 2017
![image](https://user-images.githubusercontent.com/22461466/159059120-726867bf-a79f-4bd6-b158-b576b8464da0.png)
2. python USD\build_scripts\build_usd.py "D:\software\mayaplugin\workspace\pixarUSD" --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"
![image](https://user-images.githubusercontent.com/22461466/159059396-ee45da08-bd45-488d-a2e1-c94fb28322bc.png)

### System Information (OS, Hardware)
window10 64bit
Intel Core i7-11700KF CPU
NVIDIA GeForce RTX 2070 SUPER

### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/USD/files/8306739/log.txt)

**Comment by spitzak** [comment]
Please fix all text handling so that encoding errors do not throw exceptions. Python has such codecs, for instance it turns 0x82 byte into U+DC82. You must use this everywhere.

**Comment by meshula** [comment]
@spitzak Are you meaning that the build_usd.py should open text files as ~

```py
f = open('foo', 'r', encoding = 'utf-8')
```

or is there more to it? Is there a lint of some sort that can identify the issue? Since this issue is not previously reported, and I don't have a repro, I'm not sure how we might proceed.

**Comment by spitzak** [comment]
I'm not sure but I think that error is being thrown by a python decode. It will complain about bad UTF-8. What you want is a different encoding (not sure what it is called) that translates errors to characters and does not throw an exception.

**Comment by MChenLiang** [comment]
@spitzak  thank you sir. I solved the problem. The reason for the problem is that the default code of my computer system is 936 (Simplified Chinese). When I used git clone, the coding changed.

**Comment by SleepingHairstyle0Liang** [comment]
How do you fix the problem sir? I met the same one.

**Comment by MChenLiang** [comment]
https://github.com/PixarAnimationStudios/USD/issues/1806#issuecomment-1081750822
> How do you fix the problem sir? I met the same one.
@SleepingHairstyle0Liang 
- open you project in pycharm, setting file encodings: UTF-8
![image](https://user-images.githubusercontent.com/22461466/160678550-89de4512-3501-4419-8d2f-8599b8291659.png)
- Set you pc  language code to utf8。（cause I use the Chinese system）
![image](https://user-images.githubusercontent.com/22461466/160678852-2de6d054-8f41-4aed-abc6-ad7d9fa092de.png)
![image](https://user-images.githubusercontent.com/22461466/160679077-f0351154-6408-4b3d-9743-fdc692529fb4.png)
- You can use "chcp" to to see what the pc code is.

**Comment by SleepingHairstyle0Liang** [comment]
Thank you very much, I've solved the problem by your advice, 非常感谢
