### ISSUE TITLE
[Building Error] Failed to build USD: std::function - Ubuntu 20.04

### ISSUE THREAD

**Issue by DuncanHopkinsFoundry** [PixarAnimationStudios/USD#1808]
Build fails on Ubuntu 20.04. GCC 9.4.0.
Repo checked out to dev branch (aaced34c44), have not regressed to find first commit.

Fails with the following error:
```
In file included from /hydra.local1/branches/usd.dev/usd/pxr/usd/ndr/wrapFilesystemDiscoveryHelpers.cpp:26:
/hydra.local1/branches/usd.dev/usd/pxr/usd/ndr/filesystemDiscoveryHelpers.h:50:35: error: ‘function’ in namespace ‘std’ does not name a template type
   50 | using NdrParseIdentifierFn = std::function<
      |                                   ^~~~~~~~

```

Seems to be a simple missing `#include <functional>`

**Comment by nvidia-jomiller** [comment]
Yep, ran into the same thing and submitted https://github.com/PixarAnimationStudios/USD/pull/1802

**Comment by jilliene** [comment]
Filed as internal issue #USD-7286

**Comment by pmolodo** [comment]
You can close this now that #1802 is merged...
