### ISSUE TITLE
Alembic 1.7.10 prevents debug builds with build_usd.py

### ISSUE THREAD

**Issue by nvidia-jomiller** [PixarAnimationStudios/USD#1812]
### Description of Issue
The [version of Alembic](https://github.com/PixarAnimationStudios/USD/blob/dev/build_scripts/build_usd.py#L1320) built by `build_usd.py` prevents debug builds of USD for Linux.

The problem seems to stem from treating [warnings as errors and not allowing implicit fallthrough](https://github.com/alembic/alembic/blob/1.7.10/CMakeLists.txt#L140). This problem seems to be fixed in [Alembic 1.7.14](https://github.com/alembic/alembic/blob/1.7.14/CMakeLists.txt#L141).

It would be good to at least upgrade to 1.7.16 of Alembic since USD is already pulling in 1.7.

### Steps to Reproduce
1. Make a debug build of USD using `build_usd.py` on Ubuntu

### System Information (OS, Hardware)
OS: Ubuntu 20.04.4 LTS
CPU: 11th Gen Intel® Core™ i7-11850H

**Comment by spiffmon** [comment]
Unless any observer can think of a reason not to, that seems fine, @nvidia-jomiller .  It'll take us a bit to get our internal platforms updated, but since we don't really rely on Alembic other than as transitory dependencies, should likely not be a big deal.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7289

**Comment by nvmkuruc** [comment]
Can this be closed?  OpenUSD is now on a 1.8 version of alembic.

@nvidia-jomiller and @jesschimein

**Comment by nvidia-jomiller** [comment]
Yep, this should no longer be an issue. Closing
