### ISSUE TITLE
Custom Asset Resolver V2.0 not manufactured if in a namespace

### ISSUE THREAD

**Issue by AlessBernardi** [PixarAnimationStudios/USD#1816]
### Description of Issue
When creating a custom asset resolver v2.0, the plugin layer cannot manufacture it if it is within a namespace

### Steps to Reproduce
1. Starting from a working resolver (with a working test script)
2. scope it in a custom c++ namespace
3. compile (ok)
4. run the previously working test and it returns:
```Error in 'pxrInternal_v0_21__pxrReserved__::`anonymous-namespace'::_PluginResolver<class pxrInternal_v0_21__pxrReserved__::ArResolver,class pxrInternal_v0_21__pxrReserved__::Ar_ResolverFactoryBase>::Create' at line 351 in file D:\Dev\ThirdParties\Pixar\USD\_Git\USD-22.03\pxr\usd\ar\resolver_v2.cpp : 'Failed to manufacture asset resolver XXXXResolver from plugin XXXXXResolver'```

### System Information (OS, Hardware)
Windows

### Package Versions
USD 22.03

**Comment by jilliene** [comment]
Filed as internal issue #USD-7295

**Comment by sunyab** [comment]
Hi @AlessBernardi, after scoping your resolver in your C++ namespace, make sure to update the typename of your resolver in your plugInfo.json file to match. For example, if you have a resolver named "MyResolver" in namespace "Testing", the plugInfo.json entry should look like:

```
"Testing::MyResolver": {
    "bases": ["ArResolver"],
    ...
}
```

Give that a try and let me know if that works out.

**Comment by AlessBernardi** [comment]
Hi Sunya
Thanks for your reply, the fix you proposed works well, but it means you 'expose' some implementation details on the json file.
That's not a big deal, and I'll cope with it.

Thanks a lot
Alex

**Comment by sunyab** [comment]
Good to hear, thanks! Closing this out.
