### ISSUE TITLE
Vt_DefaultValueFactory<VT_TYPE(elem)>::Invoke() is not implemented

### ISSUE THREAD

**Issue by helgemathee** [PixarAnimationStudios/USD#182]
### Description of Issue

Vt_DefaultValueFactory<VT_TYPE(elem)>::Invoke() is an inline function without a definition. Causes a build break on a static build environment

### Package Versions

This is on v0.7.4

**Comment by jtran56** [comment]
Filed as internal issue #144463.

**Comment by sunyab** [comment]
Hi @helgemathee, we expect that these template specializations should be instantiated here:

https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/lib/vt/value.cpp#L527

What compiler are you using to build? Could you post a build log showing the errors? Thanks!

**Comment by helgemathee** [comment]
This is in Windows, Visual Studio 2015.
