### ISSUE TITLE
Asset doc should mention @@@ syntax for assets

### ISSUE THREAD

**Issue by garyo** [PixarAnimationStudios/USD#1832]
### Description of Issue

In the doc for `Asset` at https://graphics.pixar.com/usd/release/glossary.html#asset it mentions that asset-valued strings are delimited by `@` signs rather than quotes. I commonly see asset strings delimited by pairs of `@@@`, but the doc does not say why that is or what it means. And in fact I don't think that `@@@` syntax is discussed anywhere in the doc that I can find.

The larger issue is that there is not yet any doc on the file syntax, but this small thing would help.

See discussion at https://groups.google.com/g/usd-interest/c/g579cJw5XgY/m/MSGdCmSPAQAJ; in that, Sebastian suggested I file this issue.

### Steps to Reproduce
1. Visit https://graphics.pixar.com/usd/release/glossary.html#asset
2. Look for mention of triple-@ delimiter syntax/semantics

**Comment by jilliene** [comment]
Filed as internal issue #USD-7331
