### ISSUE TITLE
File Extension Case Matching in Format Plugins

### ISSUE THREAD

**Issue by danecoffey** [PixarAnimationStudios/USD#1833]
### Description of Issue
When registering a file format plugin you register specific extensions, typically this a lowercase variant, i.e. ".obj".  The internal systems in USD used for matching against these extensions aren't case insensitive.  As such when you load a file that has a different case, e.g. ".OBJ", it will fail to match the registered plugin that used the lower case variant.  Ideally both the input file and the registered extensions would be checked against each other in a lower case version and successfully match.  This would allow all variants of letter case to successfully match against the registered extension.  This could happen in the SdfFileFormat::FindByExtension function.  Additionally this fix might be applied to Hio and OpenImageIO texture readers as well.  See the discussion on usd-interest related here: https://groups.google.com/g/usd-interest/c/GC9izpfsKIQ

### Steps to Reproduce
1. Register a file format as a lower case variant, i.e. "obj"
2. Call Load on a URI that uses a different variant, i.e. *.OBJ
3.  The file will fail to load as no plugin has registered "OBJ"

### System Information (OS, Hardware)
All

**Comment by jilliene** [comment]
Filed as internal issue #USD-7332
