### ISSUE TITLE
Everything in C++ is behind an internal namespace

### ISSUE THREAD

**Issue by W-Drew** [PixarAnimationStudios/USD#1847]
All of the C++ APIs are encapsulated in

```
PXR_NAMESPACE_OPEN_SCOPE
...
PXR_NAMESPACE_CLOSE_SCOPE
```

aka `PXR_INTERNAL_NS` aka `pxrInternal_v0_21__pxrReserved__`

Why are these all internal? How am I supposed to use the USD SDK without reaching into usd internals?

**Comment by gitamohr** [comment]
Hi W-Drew -- the internal namespace is just used to ensure that symbols from different software versions are distinct.  This way, a single process can link & run with multiple different USD versions simultaneously.  We do not expect you or anyone else to refer to these names in source code, generally speaking.  Rather, by default, there is a 'pxr' namespace which we generally expect folks to use.  This `pxr` namespace does a `using namespace <internal_namespace_name>` to make all the symbols available under this "public facing" namespace name.

All of the namespace names are configurable at build-time. There is some documentation regarding this topic in the "Advanced Build Configuration" area here: https://github.com/PixarAnimationStudios/USD/blob/release/BUILDING.md#usd-developer-options

And the nitty-gritty of how the namespaces get put together is here: https://github.com/PixarAnimationStudios/USD/blob/release/pxr/pxr.h.in#L45

HTH!

**Comment by W-Drew** [comment]
Ah, that makes much more sense. Thanks @gitamohr !
