### ISSUE TITLE
Overlapping GeomSubset material priorities

### ISSUE THREAD

**Issue by pellerington** [PixarAnimationStudios/USD#1853]
Hi,

When you have geom subsets which overlap each other, which material takes priority? I couldn't see anywhere which specified this.

I'm currently testing renderman and katana which can give slightly different results. Specifically, katana gives priority to subsets with assigned materials, where as renderman doesn't care if it is the fallback/default material or not.

Thanks!
Peter

**Comment by spiffmon** [comment]
Hi @pellerington , overlapping Subsets for the purpose of material bindings [is defined as invalid](https://graphics.pixar.com/usd/release/api/class_usd_shade_material_binding_a_p_i.html) (search down for `nonOverlapping`).  It is also defined that the Mesh's bound material serves as a fallback for any faces not covered by some Subset that has its own material binding.  If you have two Subsets with overlapping faces that specify different materials, it is currently undefined behavior which one wins.  If Katana or RenderMan (RenderMan within Katana, or hdPrman?) is not applying the fallback behavior, that would be bugs to file, I think?

**Comment by pellerington** [comment]
Ah great! Thank you @spiffmon I didn't check that file.

In my Renderman/hdPrman example, I had two subsets which overlapped. One had a material bound. The other did not. Renderman was choosing the subset which had no materials bound (and using the fallback material instead).

This would be correct behaviour as when you have overlapping subsets in the "materialBind" family, the result is invalid?

Wierdly if I change the family name to something other than "materialBind" it can still bind materials but I assume I should raise this with the Solaris team not here?

Thank you for your help.

**Comment by spiffmon** [comment]
I would expect you could still _bind_ materials to non-materialBind-family Subsets, but Hydra should only be consuming the materialBind subsets, and Solaris renders through Hydra.  But I think the behavior difference can be explained by the fact that we only brought Hydra up-to-spec in this regard just *after* the release of 21.08 (previously it read all Subsets), and Solaris is still shipping with 21.08.  I suspect the "weird" behavior will disappear with the next release of Solaris... Katana is another matter, as to the best of my knowledge Katana blindly imports all Subsets under a Mesh and processes them all equally.
