### ISSUE TITLE
Building with Python 3.10

### ISSUE THREAD

**Issue by eliemichel** [PixarAnimationStudios/USD#1857]
### Description of Issue

When trying to build using Python 3.10, boost compilation fails because Boost 1.70 uses the `_Py_fopen` function, which was internal to Python and has been removed.

### Steps to Reproduce

 1. Just run the install script from Python 3.10:

```
python3.10 USD/build_scripts/build_usd.py %USD_INSTALL%
```

### Suggested fix:

After running the script a first time and it failed while building boost, go to `%USD_INSTALL%\src\boost_1_70_0\libs\python\src\exec.cpp` and replace both occurrences of `_Py_fopen` with `fopen` (as suggested [here](https://github.com/boostorg/python/pull/344/files)).

Then run the script again, it should work.

**This is a bit hacky** and we should think of a better cleaner way, either applying a patch after downloading boost source code or upgrading boost.

### System Information (OS, Hardware)

Windows 10, tested on multiple hardware.

### Package Versions

USD [v22.05](https://github.com/PixarAnimationStudios/USD/commit/3b097e3ba8fabf1777a1256e241ea15df83f3065)

### Build Flags

Default

**Comment by meshula** [comment]
Note: this problem is addressed in boost 1.76, possibly earlier.

**Comment by eliemichel** [comment]
How safe is it to change the version of boost when building USD? hat consequences can it have on compatibility? FWIW version of Boost 1.70 corresponds to the CY2020 standard of the [VFX Reference Platform](https://vfxplatform.com/).

**Comment by meshula** [comment]
Vfx2020 also specifies Python 3.7, so you are already living in the future with Python 3.10 :)

**Comment by meshula** [comment]
Wee bit of context, the reason I mentioned that particular version is it's the minimum i've been able to find that works without patching for py310, vs2022, M1, and macos 12.x. I haven't done testing with that version for Linux, since 1.70 is fine there.

**Comment by eliemichel** [comment]
> Vfx2020 also specifies Python 3.7, so you are already living in the future with Python 3.10 :)

Yes indeed ^^

**Comment by jilliene** [comment]
Filed as internal issue #USD-7369

**Comment by utkarshani** [comment]
> Note: this problem is addressed in boost 1.76, possibly earlier.
Hi @meshula, I am using boost 1.76 still getting the same issue :(

**Comment by eliemichel** [comment]
Does the suggested fix in the original post work for you?

**Comment by utkarshani** [comment]
> Does the suggested fix in the original post work for you?
@eliemichel Yes, it fixed the issue. 

I am getting the new issue after this-
2022-05-17 10:43
cmake --build . --config Release --target install -- /M:12
Error: could not load cache

ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:12'
See C:\USD\build\USD\log.txt for more details.

**Comment by meshula** [comment]
@utkarshani There are a lot of reasons one can get that error message from cmake. Usually it means that CMakeCache.txt is not in the directory you are running cmake --build in, which you have indicated by the `.` argument to `--build`.

**Comment by meshula** [comment]
@eliemichel The fix to boost python for Python 3.10 compatibility is here ~ 

https://github.com/boostorg/python/commit/cbd2d9f033c61d29d0a1df14951f4ec91e7d05cd

It seems to make the same fix as in your original post. The commit log says that the fix is in boost 1.76.0 and greater.

**Comment by utkarshani** [comment]
> @utkarshani There are a lot of reasons one can get that error message from cmake. Usually it means that CMakeCache.txt is not in the directory you are running cmake --build in, which you have indicated by the `.` argument to `--build`.

@meshula Thanks, resolved the issue with the new release 22.05a

**Comment by sunyab** [comment]
Closing this out, support for Python 3.10 was added in the 23.02 release.
