### ISSUE TITLE
unable to build from build.py

### ISSUE THREAD

**Issue by utkarshani** [PixarAnimationStudios/USD#1864]
The system is: Windows - 10.0.19042 - AMD64

2022-05-13 16:02
cmake -DCMAKE_INSTALL_PREFIX="C:\USD" -DCMAKE_PREFIX_PATH="C:\USD" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 14 2015 Win64"   "C:\USD\src\zlib-1.2.11"
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version  to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:4 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 5/13/2022 4:02:37 PM.
    Project "C:\USD\build\zlib-1.2.11\CMakeFiles\3.23.1\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\USD\build\zlib-1.2.11\CMakeFiles\3.23.1\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
    Done Building Project "C:\USD\build\zlib-1.2.11\CMakeFiles\3.23.1\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "C:\USD\build\zlib-1.2.11\CMakeFiles\3.23.1\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\USD\build\zlib-1.2.11\CMakeFiles\3.23.1\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
    
        0 Warning(s)
        1 Error(s)
    
    Time Elapsed 00:00:00.02
    

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/USD/build/zlib-1.2.11/CMakeFiles/CMakeOutput.log".

**Comment by meshula** [comment]
I'm not sure what the exact problem is, but your command line is requesting "Visual Studio 14 2015 Win64", and the error is reporting a missing file in VS2019. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props"

Please note that vs2019 is known to work well for building USD, but I have not personally tested vs2015 for some time. For sure, there will be difficulties in attempting to mix them.

If you are running in a visual studio command shell, cmake should pick up the correct compiler automatically.  Perhaps you need to be running the vcvarsall.bat specifically for vs2015, or change your command line by omitting the -G argument completely.

**Comment by utkarshani** [comment]
I'm using Visual studio 2019
