### ISSUE TITLE
building usdgeom on windows fails

### ISSUE THREAD

**Issue by helgemathee** [PixarAnimationStudios/USD#187]
### Description of Issue

The changes in 7db7749e3306e8411511f0c9b01441defba9eec3 added use of the "and" keyword in primvar.cpp which is not supported on Windows

### Steps to Reproduce
1. build latest dev branch on windows

**Comment by helgemathee** [comment]
this also happens within usdShade (input.cpp) and other places. simply look for the " and " keyword / operator.

**Comment by helgemathee** [comment]
The offending commits there is 66300ecc76ec1d83435375d31bb54681b2ba2c9f

**Comment by helgemathee** [comment]
Another offending commit using the "not" keyword / operator is 10d510b14b1ec021214051dbf99f0b4aba100f33

**Comment by helgemathee** [comment]
this seems to be related to compiler flags. running cmake again resolved this - must have been using an old cmakecache

**Comment by helgemathee** [comment]
nope - sorry for the noise. this is still an issue. the /Za also doesn't help. 

So this needs to be fixed for a successful build on Visual Studio 2015.

**Comment by jtran56** [comment]
Filed as internal issue #144792.

**Comment by sunyab** [comment]
We've pushed out a couple of fixes to dev that should get the Windows build up and running again. Please let us know if dev is still broken for you after this. Thanks!

**Comment by helgemathee** [comment]
yep. these build errors are fixed. thanks! closing this issue.
