### ISSUE TITLE
[hdSt] Incorrect MaterialX shading without dome light

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#1877]
### Description of Issue

Rendering MaterialX materials in hdStorm without a dome light results in rendering artifacts:

<p>
<img src="https://user-images.githubusercontent.com/3663466/169981423-118ea6c7-5331-4a20-a7dc-f832509c5bd4.png" width="360" />
<img src="https://user-images.githubusercontent.com/3663466/169981480-83700b5b-35c6-453e-8a91-dd49b878fb7f.png" width="360" />
</p>

The background color should be used as a fallback for environment reflections if no dome light is active. One way of achieving this could be by creating a 1x1 dome light texture.

I've attached a [sample model from Cesium](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMilkTruck), licensed under [CC-BY](https://creativecommons.org/licenses/by/4.0/), converted to USD+MaterialX.

### Steps to Reproduce

1. open this model in usdview: [CesiumMilkTruck.zip](https://github.com/PixarAnimationStudios/USD/files/8760688/CesiumMilkTruck.zip)
2. deactivate the 'UsdPreviewSurface' prim
3. observe rendering artifacts
4. turn on dome light, see the artifacts disappear

### System Information (OS, Hardware)
Windows, RTX 2060

### Build Flags
OIIO and MaterialX

**Comment by jilliene** [comment]
Filed as internal issue #USD-7383
