### ISSUE TITLE
[hdSt] Missing normalization of world-space normal in MaterialX shader generator?

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#1879]
The normal is transformed to world-space by multiplication with the normal matrix in materialXShaderGen.cpp L67:

https://github.com/PixarAnimationStudios/USD/blob/7d637e466cfb83e235d3676a121a157d29123035/pxr/imaging/hdSt/materialXShaderGen.cpp#L65-L72

But I think it has to be normalized afterwards?

**Comment by jilliene** [comment]
Filed as internal issue #USD-7385

**Comment by klucknav** [comment]
The existing surface shaders implementations all normalized the normalWorld and tangentWorld vectors before using. So it felt unnecessary to add an additional normalization here. This does means that we expect future or additional implementations to follow that pattern of normalizing these two vectors before using them.

**Comment by pablode** [comment]
Makes sense - thank you very much for looking into this!
