### ISSUE TITLE
_close crashes on windows 10

### ISSUE THREAD

**Issue by helgemathee** [PixarAnimationStudios/USD#188]
### Description of Issue

When running USD on windows 10 there is a crash in atomicOfStreamWrapper and possibly other places calling _close on a temporary file. the use of _sopen_s and _close seems to be causing crashes on Windows 10, Visual Studio 2015.

I've tested using GetTempFileName instead (see attached patch) and that works. 
[fileSystem.cpp.txt](https://github.com/PixarAnimationStudios/USD/files/883493/fileSystem.cpp.txt)

### Steps to Reproduce
1. Build on Windows 10, Visual Studio 2015
2. try to create a stage in C++

### System Information (OS, Hardware)

Windows 10, Visual Studio 2015

### Package Versions

latest dev branch

**Comment by jtran56** [comment]
Filed as internal issue #144797.

**Comment by sunyab** [comment]
Hi @helgemathee, we haven't seen this in any of our local testing here -- any chance you could send us a stack trace of the crash? Thanks!

**Comment by helgemathee** [comment]
[helloworld.zip](https://github.com/PixarAnimationStudios/USD/files/884887/helloworld.zip)

here's a minimalistic repro - you can use scons or just build the arch into a dll and the main into an exe - it crashes during execution. 

I'll dig a bit deeper today and will keep you posted - also with a stacktrace.

**Comment by helgemathee** [comment]
so this was related to two runtimes fighting - linking with /MT on windows causes this issue. closing.
