### ISSUE TITLE
[hdSt] 'default' input of MaterialX geompropvalue node is ignored

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#1880]
When a `<geompropvalue>` node tries to read a geomprop that does not exist, a hardcoded value of `0.0` is returned:
https://github.com/PixarAnimationStudios/USD/blob/3b097e3ba8fabf1777a1256e241ea15df83f3065/pxr/imaging/hdSt/materialXShaderGen.cpp#L677-L688

But the [`<geompropvalue>` node has a `default` input](https://github.com/AcademySoftwareFoundation/MaterialX/blob/1dc3a938005182230b52f60d31600b0e2849975e/libraries/stdlib/stdlib_defs.mtlx#L1059), which should be returned instead (MaterialX 1.38 spec. p. 28 bottom).

**Comment by jilliene** [comment]
Filed as internal issue #USD-7386
