### ISSUE TITLE
HdCoordSys doesn't get dirtied when the target xform prim changes

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1889]
### Description of Issue
When hydra creates an HdCoordSys, it points to an xformable prim. If that xformable prim is animated or is edited, I would expect the HdCoordSys to receive a Sync call so that it can update its internal representation of the xform. But this does not happen. Unfortunately as far as I am aware, no standard render delegates support HdCoordSys, so it is only the upcoming release of Karma (which supports coordsys through MaterialX) which can clearly demonstrate this failure (though setting breakpoints in a debugger with any render delegate should make this problem clear).

### Steps to Reproduce
1. Open the attached file into usdview, and set the renderer to karma:
[coordsys_test.zip](https://github.com/PixarAnimationStudios/USD/files/8833341/coordsys_test.zip)
2. Move to another frame. The image re-renders, but is unchanged.
3. Switch to another render delegate and back to karma. See the effect of the changed coordsys.

### Package Versions
USD 22.05, error may only be visible with Houdini 19.5.

**Comment by spiffmon** [comment]
Hey @marktucker , I believe we added coordsys support specifically to get our HdPrman renders of internal Pixar assets working, and it [looks like we support it?](https://github.com/PixarAnimationStudios/USD/blob/release/third_party/renderman-24/plugin/hdPrman/coordSys.h#L40)?
Which is not to say invalidation and tracking is working properly... just speaking to your "lack of support" statement?

**Comment by jilliene** [comment]
Filed as internal issue #USD-7409

**Comment by marktucker** [comment]
Oh, cool. Very happy to be wrong on that point, especially if it means someone can validate that this does or doesn't work with hdprman.

**Comment by tcauchois** [comment]
Fixed by https://github.com/PixarAnimationStudios/OpenUSD/commit/1b74956bd37880a4fa48ec3d9ad4b705cc7d1eab
