### ISSUE TITLE
TextFileFormat not working correctly on windows

### ISSUE THREAD

**Issue by helgemathee** [PixarAnimationStudios/USD#189]
### Description of Issue

On windows you need to use the binary mode for files if you want to use fread for the complete content. I was getting premature end-of-file errors from the textFileFormat due to this.

here's the patch to fix this, on windows systems use the "rb" mode instead of "rt".

[textFileFormat.cpp.patch.txt](https://github.com/PixarAnimationStudios/USD/files/885250/textFileFormat.cpp.patch.txt)

**Comment by helgemathee** [comment]
This is on the latest dev branch btw.

**Comment by jtran56** [comment]
Filed as internal issue #144835.
