### ISSUE TITLE
Storm: Rendering issue with pointInstancer and subset material bindings

### ISSUE THREAD

**Issue by jufrantz** [PixarAnimationStudios/USD#1892]
### Description of Issue

When rendering in storm a pointInstancer with materials bound to prototype geomsubsets, some instances disappear/reappear inconsistently from frame to frame like this stage in usdview: https://user-images.githubusercontent.com/40573039/172204349-fdd4b056-79fe-41ec-abdb-85ab0e8788da.mp4

We noticed that the bug disappears when we disable instance frustum culling (HD_ENABLE_GPU_INSTANCE_FRUSTUM_CULLING=0).

### Steps to Reproduce

1. Open in usdview `pi_geomsubsets_vis_issue/instancer.usd` from [pi_geomsubsets_vis_issue.zip](https://github.com/PixarAnimationStudios/USD/files/8846112/pi_geomsubsets_vis_issue.zip)
2. Move the camera to trigger some viewport refreshs
3. Notice the instances disappearing/reappearing

### System Information (OS, Hardware)
- Linux CentOS
- GeForce RTX 3060 - Driver Version: 460.91.03

### Package Versions
- USD-21.11
- USD-22.05a

**Comment by jilliene** [comment]
Filed as internal issue #USD-7411
