### ISSUE TITLE
Hydra: Materials bound to geomsubsets are ignored with an "identified" UsdImagingDelegate

### ISSUE THREAD

**Issue by jufrantz** [PixarAnimationStudios/USD#1896]
### Description of Issue

When using an `UsdImagingDelegate` with a delegateID (diff than `/`), materials bound to geomsubsets are ignored, meshes are rendered with the fallback grey material.

I could reproduce the issue with usdview/Storm thanks to `USDIMAGINGGL_ENGINE_DEBUG_SCENE_DELEGATE_ID`

### Steps to Reproduce

1. Open attached usd scene [cube_with_geomsubsets.zip](https://github.com/PixarAnimationStudios/USD/files/8860501/cube_with_geomsubsets.zip) in usdview 
2. Notice we have a red and a green material assigned to cube faces, they are correctly rendered in Storm
3. Set `USDIMAGINGGL_ENGINE_DEBUG_SCENE_DELEGATE_ID` environment variable to any (non root) path, and open the same scene, for instance
        `USDIMAGINGGL_ENGINE_DEBUG_SCENE_DELEGATE_ID=/Foo usdview cube_with_geomsubsets.usd`
5.  Notice that the cube is now rendered without usd material bindings 

### Note

On our side we are considering patching UsdImagingMeshAdapter::GetTopology this way:

```diff
diff --git a/pxr/usdImaging/usdImaging/meshAdapter.cpp b/pxr/usdImaging/usdImaging/meshAdapter.cpp
index f95d0e14a..b1aca9951 100644
--- a/pxr/usdImaging/usdImaging/meshAdapter.cpp
+++ b/pxr/usdImaging/usdImaging/meshAdapter.cpp
@@ -397,7 +397,7 @@ UsdImagingMeshAdapter::GetTopology(UsdPrim const& prim,
                    HdGeomSubset {
                        HdGeomSubset::TypeFaceSet,
                        subset.GetPath(),
-                       GetMaterialUsdPath(subset.GetPrim()),
+                       _ConvertCachePathToIndexPath(_GetMaterialUsdPath(subset.GetPrim())),
                        indices });
             }
         }
```

Current meshAdapter code assigns an `usdPath` to HdGeomSubset.materialId, whereas clients in pxr render delegates seem to expect a SPrim path (e.g. HdStGetMaterialNetworkShader() HdPrman_ResolveMaterial())

### System Information (OS, Hardware)
- Linux CentOS

### Package Versions
- USD-21.11
- USD 22.05a

**Comment by sunyab** [comment]
Filed as internal issue #USD-7419

**Comment by tgvarik** [comment]
Shares an underlying cause with #1687

**Comment by jufrantz** [comment]
Thank you @tgvarik. The fix in USD 22.11 works for us as well; I'm closing the issue.

**Comment by jufrantz** [comment]
Hello, 

I'm reopening the issue as a similar problem has (re)surfaced.
I did notice it with USD-23.08 and didn't test earlier USD versions or 23.11. I will probably give them a try. 
It can be reproduced with the same steps as the original issue, using usview and `USDIMAGINGGL_ENGINE_DEBUG_SCENE_DELEGATE_ID` env.

-- Julien

**Comment by jufrantz** [comment]
The issue has been found to be on our side within our own USD build.
My apologies for this mix-up.
