### ISSUE TITLE
Saving files can fail on windows

### ISSUE THREAD

**Issue by helgemathee** [PixarAnimationStudios/USD#190]
### Description of Issue

The re-implemetation of ArchFileAccess fails for querying access for writing files if the file does not exist.

This is on the latest dev branch - I've attached the patch below which fixes the issue.

[fileSystem.cpp.patch.txt](https://github.com/PixarAnimationStudios/USD/files/885285/fileSystem.cpp.patch.txt)

**Comment by jtran56** [comment]
Filed as internal issue #144834.
