### ISSUE TITLE
Libtiff / openImageIO installation error on MacOS 

### ISSUE THREAD

**Issue by abrennec** [PixarAnimationStudios/USD#1901]
### Description of Issue

Hello everyone, I hope this is the right place to file this issue. I am trying to build USD using the python build script and the build fails with the following error message:

ERROR: Failed to extract archive libtiff-Release-v4-0-7.tar.gz: unrecognized archive file type

I investigated it a little and it seems that the download link (https://gitlab.com/libtiff/libtiff/-/archive/Release-v4-0-7/libtiff-Release-v4-0-7.tar.gz) is no longer working. I could only fix this issue w/o build flag "--openimagio" 

### Steps to Reproduce
1. Follow the installation instructions and run the build_scripts/build_usd.py

### System Information (OS, Hardware)

MacOS 12.3.1 Monterey

### Build Flags

python3 build_scripts/build_usd.py /opt/local/USD --ptex --openvdb --prman --openimageio --opencolorio --materialx --draco

**Comment by meshula** [comment]
@abrennec Thanks for the report! surprisingly, libtiff moved 😭 . We have a patch in preparation to point to the new location. In the mean time, while you are getting your build up and running, it's a good idea to `--openimageio` as you have noted.

**Comment by abrennec** [comment]
:) thank you

Nick Porcino ***@***.***> schrieb am So., 12. Juni 2022,
21:38:

**Comment by sunyab** [comment]
Filed as internal issue #USD-7423

**Comment by virokannas** [comment]
If anyone needs an interim mix, just modify line 954 (or nearby) of build_scripts/build_usd.py to reflect where the .tar.gz has moved:
`TIFF_URL = "https://gitlab.com/libtiff/libtiff/-/archive/v4.0.7/libtiff-v4.0.7.tar.gz"`

Worked for me.

**Comment by sunyab** [comment]
This fix has been pushed to the dev branch and to a new 22.05b patch release so that users on 22.05 won't run into this issue. Thanks again for the report!

**Comment by abrennec** [comment]
Super, thank you!

**Comment by Destop-Trang1801** [comment]
build_scripts/build_usd.py
