### ISSUE TITLE
Coding error in usdchecker when using internal references

### ISSUE THREAD

**Issue by hinton-mgi** [PixarAnimationStudios/USD#1902]
### Description of Issue
Instead of printing any compliance issues and gracefully exiting, usdchecker fails with an error for some usd files. I believe this particular problem occurs when the usd file contains internal references.

### Steps to Reproduce
1. Create `test.usda` with the following contents:
```
#usda 1.0

def Sphere "sphere"
{
}

def "clone" (
    prepend references = </sphere>
)
{
}
```
2. run `usdchecker test.usda`
3. My result was:
```
Traceback (most recent call last):
  File "D:\Testing\USD-sdk\bin\usdchecker", line 149, in <module>
    sys.exit(main())
  File "D:\Testing\USD-sdk\bin\usdchecker", line 118, in main
    checker.CheckCompliance(inputFile)
  File "D:\Testing\USD-sdk\lib\python\pxr\UsdUtils\complianceChecker.py", line 969, in CheckCompliance
    UsdUtils.ComputeAllDependencies(Sdf.AssetPath(inputFile))
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_22__pxrReserved__::SdfComputeAssetPathRelativeToLayer' at line 92 in file D:\Testing\USD\pxr\usd\sdf\layerUtils.cpp : 'Layer path is empty'
```

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD built from dev branch, HEAD at commit a470570c9492263ae8e973a91bd5800f998ef60b

### Build Flags
PXR_ENABLE_METAL_SUPPORT=FALSE
PXR_ENABLE_VULKAN_SUPPORT=FALSE
PXR_ENABLE_PTEX_SUPPORT=FALSE
PXR_USE_PYTHON_3=ON

**Comment by spiffmon** [comment]
Thanks for reporting, @hinton-mgi - I can't believe this has gone undetected so long!  For the fixer: I investigated, and think the culprit is `_FileAnalyzer::_ProcessReferences()`, though `_FileAnalyzer::_RemapRefOrPayload()` and `_FileAnalyzer::_ProcessPayloads()` are similarly unguarded against internal references.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7424
