### ISSUE TITLE
build break on osx

### ISSUE THREAD

**Issue by helgemathee** [PixarAnimationStudios/USD#192]
### Description of Issue

base/tf/fileUtils.cpp doesn't build due to use of  fstatat and AT_SYMLINK_NOFOLLOW, which are not defined on OSX.

Find the patch below which resolves the issue
[fileUtils.cpp.patch.txt](https://github.com/PixarAnimationStudios/USD/files/889891/fileUtils.cpp.patch.txt)

**Comment by jtran56** [comment]
Filed as internal issue #144883.

**Comment by asluk** [comment]
FWIW the dev branch builds ok for me on OSX 10.11.6, XCode 8.0 .

**Comment by c64kernal** [comment]
Helge, let us know if this works when you get a chance to try the newer XCode.

**Comment by sunyab** [comment]
Closing out this issue, see #139 for more details. Thanks!
