### ISSUE TITLE
Rendering Headless with prman

### ISSUE THREAD

**Issue by goetzmoritz** [PixarAnimationStudios/USD#1926]
I'm trying to headless render a usd-file with the prman plugin using usdrecord:
```
$ usdrecord --renderer Prman ~/Kitchen_set/Kitchen_set.usd ~/out.jpg
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

Is that even possible? And how could it be done?

**Comment by sunyab** [comment]
Filed as internal issue #USD-7462

**Comment by tcauchois** [comment]
usdrecord currently requires an OpenGL context to run, although we're close to removing that requirement (for non-GPU renderers like Prman).  I'm not sure what's going on with the "qt" error messages, but I'm guessing when we're initializing GL we're generating those errors when we fail to create a context?

**Comment by JoshkVFX** [comment]
Just ran into this myself, has there been any update since July?
