### ISSUE TITLE
DisplayMode no longer applies to component kind Prims without applying UsdGeomModelAPI to the component

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#1927]
### Description of Issue
When the UsdGeomModelAPI restrictions were added to force displayMode to only work on Prims with the API applied, it made it so that component kind Prims no longer automatically draw as the mode when a parent prim has the ModelAPI applied with a custom draw mode. In order to get the component to draw as the display mode, you must apply the ModelAPI to the component as well.

This is not something any of our legacy assets have, and as such even with a model kind hierarchy, they do not draw as the draw mode.

I made a post on the forum, and it seems that this isn't the expected behaviour : https://groups.google.com/g/usd-interest/c/o0Is5rPnJag

### Steps to Reproduce
1. Create a prim with kind component.
2. On a parent prim, set the displayMode and apply the ModelAPI
3. Component Prim will not draw as the display mode.
4. Apply ModelAPI to the component Prim. It will now draw as the display mode.

### System Information (OS, Hardware)
CentOs-7

### Package Versions
usd - 22.05

**Comment by sunyab** [comment]
Filed as internal issue #USD-7463

**Comment by marktucker** [comment]
I believe this was fixed by https://github.com/PixarAnimationStudios/USD/commit/9a2c1566ee4418ab8303d681049c2cd5145b4807 ?

**Comment by spiffmon** [comment]
Yes, thanks for pointing that out, @marktucker !  Closing, but please reopen @radon199 if you are still having issues.
