### ISSUE TITLE
Building Static USD lib in Win32 does not shut off plugin system

### ISSUE THREAD

**Issue by yosmo78** [PixarAnimationStudios/USD#1935]
### Description of Issue
Building a static lib doesn't work on win32, it still builds it as if it was a dynamic lib. 

I want to make a static lib for the USD library for a couple of reasons. One is that my project structure dictates that I not put .dll files at the .exe level, which when testing all the usd_*.lib require me to put all the .dll at the .exe level (my clients require a clean install directory with the .exe and since the library doesn't have a mechanism for manual loading the dll on windows (as I am aware of), this is the next best thing). Another issue is that I have a custom pooled memory allocator but the malloc hooks do not work on win32, so the calls with the standard library are mixing allocations between microsoft's allocator and mine which is causing tons of crashes. And .dll's technically on paper run slower than .lib on program startup (any extra performance boost I can get is a plus since I am in a high performance environment)

### Steps to Reproduce
0. run: `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"`
1.  In `build_usd.py` (I don't belive a build option exists for static libs, so I do the following) change:
```
        if context.buildShared:
            extraArgs.append('-DBUILD_SHARED_LIBS=ON')
        elif context.buildMonolithic:
            extraArgs.append('-DPXR_BUILD_MONOLITHIC=ON')
```
to
```
        extraArgs.append('-DBUILD_SHARED_LIBS=OFF')
        extraArgs.append('-DPXR_BUILD_MONOLITHIC=OFF')
        extraArgs.append('-DPXR_STATIC=ON')
```
2. create a `USD-install` folder in the USD folder cloned from github
3. run: `py C:\USD\build_scripts\build_usd.py C:\USD\USD-install --no-docs --no-embree --no-python --no-debug-python --no-draco --no-prman --no-materialx --no-alembic --no-hdf5 --no-opencolorio --no-openimageio --no-usdview --no-openvdb --no-ptex --no-imaging`
4. after installation copy lib folder, bin folder, and include folder to project (also copy over tbb.dll)
5. move `include/boost-1_70/boost` folder up to folder layer `include/boost`
6. link to the following windows libs `kernel32.lib user32.lib gdi32.lib shlwapi.lib dbghelp.lib Advapi32.lib Ws2_32.lib`
7. link to generated lib files `lib/tbb.lib lib/usd_tf.lib lib/usd_sdf.lib lib/usd_vt.lib lib/usd_usd.lib lib/usd_arch.lib lib/usd_ar.lib lib/usd_kind.lib lib/usd_ndr.lib lib/usd_pcp.lib lib/usd_work.lib lib/usd_gf.lib lib/usd_plug.lib lib/usd_sdr.lib lib/usd_js.lib lib/usd_trace.lib`
8. compile with `/DPXR_STATIC` and `/MD`
Result: `Coding Error: in _GetPluginForType at line 147 of C:\USD\pxr\usd\ar\resolver_v2.cpp -- Failed to find plugin for ArDefaultResolver`
### System Information (OS, Hardware)
win32

### Package Versions
latest

**Comment by yosmo78** [comment]
I was missing the `-WHOLEARCHIVE:` on each lib. my bad, so like the like the following:

```
-WHOLEARCHIVE:lib/usd_tf.lib -WHOLEARCHIVE:lib/usd_sdf.lib -WHOLEARCHIVE:lib/usd_vt.lib -WHOLEARCHIVE:lib/usd_usd.lib -WHOLEARCHIVE:lib/usd_arch.lib -WHOLEARCHIVE:lib/usd_ar.lib -WHOLEARCHIVE:lib/usd_kind.lib -WHOLEARCHIVE:lib/usd_ndr.lib -WHOLEARCHIVE:lib/usd_pcp.lib -WHOLEARCHIVE:lib/usd_work.lib -WHOLEARCHIVE:lib/usd_gf.lib -WHOLEARCHIVE:lib/usd_plug.lib -WHOLEARCHIVE:lib/usd_sdr.lib -WHOLEARCHIVE:lib/usd_js.lib -WHOLEARCHIVE:lib/usd_trace.lib
```

**Comment by meshula** [comment]
There's more than one reason why a fully static build might say it can't find the default resolver. One, is that the static initializers didn't run, and another, is that the plug system didn't find the pluginfo.json files, which are required, even when you are statically linking.

First, here's a cmake routine that does the business of making sure the static construction works:

```cmake
function(pxr_whole libs result)
    set(final "")
    foreach(lib ${libs})
        target_link_libraries(${lib} tbb)
        if(MSVC)
            # The syntax here is -WHOLEARCHIVE[:lib] but CMake will
            # treat that as a link flag and not "see" the library.
            # As a result it won't replace a target with the path
            # to the built target and it won't add a dependency.
            #
            # We can't simply link against the full path to the
            # library because we CMake will not add a dependency
            # and won't use interface link libraries and flags
            # from the targets.  Rather than trying to add those
            # things manually we instead link against the target
            # and link against the full path to the built target
            # with WHOLEARCHIVE.
            #
            # This ends up with the library on the link line twice.
            # That's okay, though, because the linker will read
            # the WHOLEARCHIVE one first and will use none of the
            # (duplicate) symbols from the second since they're
            # all provided by the first.  The order doesn't really
            # matter; we pull in the whole archive first.
            #
            list(APPEND final -WHOLEARCHIVE:$<TARGET_FILE:${lib}>)
            list(APPEND final ${lib})
        elseif(CMAKE_COMPILER_IS_GNUCXX)
            list(APPEND final -Wl,--whole-archive ${lib} -Wl,--no-whole-archive)
        elseif("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
            list(APPEND final -Wl,-force_load ${lib})
        else()
            # Unknown platform.
            list(APPEND final ${lib})
        endif()
    endforeach()
    set(${result} ${final} PARENT_SCOPE)
endfunction()
```
The way you'd use it is -
```cmake
set(usd_libs
    arch gf js plug tf trace vt ar work kind ndr pcp
    sdf sdr usd usdGeom usdHydra usdLux usdMedia usdPhysics
    usdRi usdShade usdSkel usdUI usdUtils usdVol)

set(usd_libs_resolved "")
pxr_whole("${usd_libs}" usd_libs_resolved)
```
then finally
```cmake
target_link_libraries(my_application
    tbb  ${usd_libs_resolved} ...other stuff...)
```

That resolves the static construction. The next thing you have to do is put the directory containing the pluginfo.json files where you want your application's associated data files. `PlugInitConfig` has a number of calls to _AppendPathList. If you have a look at how those are derived, you can either set things up to utilize one of the default paths, or you can patch the code with an _AppendPathList that does what you need.

**Comment by meshula** [comment]
I see you discovered the whole archive business while I was typing :)
