### ISSUE TITLE
Inverse transform op does not always inverse the transform

### ISSUE THREAD

**Issue by chloe5608** [PixarAnimationStudios/USD#194]
### Description of Issue
When loading a usda file in maya with the transform stack with the only inverted transformOp, loader will treat inverted transform as non-inverted transform.
e.g.
loading usda file with uniform token[] xformOpOrder = ["!invert!xformOp:translate"]

### Steps to Reproduce
1. Load the attached file (cube_test.usda )into Maya:
[cube_test.zip](https://github.com/PixarAnimationStudios/USD/files/894796/cube_test.zip)

2. Cube shows up at location (0,0,-3.849). If translation is indeed inverted, cube should show up at (0,0,3.849)

### System Information (OS, Hardware)
MacOS, MacPro

### Package Versions
Maya USD importer
### Build Flags

**Comment by chloe5608** [comment]
If I change the transform order into: uniform token[] xformOpOrder = ["translate","!invert!xformOp:translate"], the cube shows up at origin as expected.

**Comment by jtran56** [comment]
Filed as internal issue #145044.

**Comment by spiffmon** [comment]
Hi Chloe,
   Indeed, there's a bug here in the Maya importer.  usdview shows the expected result that for cuby_test.usda, the cube is positioned at (0, 0, 3.849), i.e. the authored translation is inverted and applied.  It's a somewhat odd construct, as the "!invert!" operator is primarily meant for applying robust pivots, used in conjunction with the non-inverted corresponding op, as you have in your first comment.

Cheers,
--spiff

**Comment by mattyjams** [comment]
Hi @chloe5608,

We have a fix for this issue that should be available in the dev branch soon. Thanks for reporting it, and for the test case!


-Matt
