### ISSUE TITLE
Is it possible to specify a tangent space?

### ISSUE THREAD

**Issue by hinton-mgi** [PixarAnimationStudios/USD#1941]
### Description of Issue
As far as I can tell, it is not possible to specify a tangent space on a UsdGeomMesh that will affect the normal mapping of a UsdPreviewSurface shader. Is that true?
One of the samples on [this page](https://graphics.pixar.com/usd/release/spec_usdpreviewsurface.html) contains the attributes:
```
string inputs:frame:tangentsPrimvarName = "tangents"
string inputs:frame:binormalsPrimvarName = "binormals"
string inputs:frame:stPrimvarName = "st"
```
But I can't find these mentioned anywhere else, and they don't seem to do anything. Am I missing something? Normal maps can't really be used without the correct tangent space.

**Comment by spiffmon** [comment]
Hi @hinton-mgi ,
    The specification could really use some clarification and updating in this respect.  A few lines below those you point at, we suggest authoring in Mikktspace for consistency, but in *fact*, what I think can be considered "the reference implementation" of UsdPreviewSurface, the [glsl implementation that ships with USD, computes screen-space tangents](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usdImaging/plugin/usdShaders/shaders/previewSurface.glslfx#L466-L467) and does not allow for alternative, primvar-driven tangent spaces.

**Comment by hinton-mgi** [comment]
I see. Thanks for the clarification @spiffmon, and for pointing out that glslfx file. I was not grepping for the right things. It is a bit surprising, but I guess we will just need to avoid workflows that need to see the extra detail in USD for now.

**Comment by spiffmon** [comment]
@hinton-mgi , UsdPreviewSurface was designed mostly as a "lowest common denominator" for interchange and basic PBR, to tide us over for "cross-renderer shading" until the much more general MaterialX was ready and pervasive.  Today, MaterialX is ready, _becoming_ pervasive, and is supported and incorporated into both of USD's shipping renderers, Storm and Prman.

The MaterialX support in USD/Hydra is still considered nascent, but will improve faster as more people use it and report issues.  So, depending on what your delivery targets are (i.e. Apple devices still do not support it yet, so you cannot use MaterialX for USDZ-AR), it may be a viable path for you to get the shading you need in USD.

**Comment by hinton-mgi** [comment]
I will keep that in mind. It looks like MaterialX would be a poor fit for our renderer, but perhaps it could be viable for the content creation side of the pipeline. Thanks.

**Comment by spiffmon** [comment]
Cool, @hinton-mgi .  Out of curiosity (which I know would be shared by others, here), could you share what in particular would make MaterialX a poor fit for your renderer?

**Comment by hinton-mgi** [comment]
@spiffmon I haven't done a deep dive into MaterialX, but from my understanding, there are two main factors.

First: we don't believe the shader graph approach is right for us. We have a small subset of materials that will be viewed from up close but disproportionately impact performance, and other materials are never viewed from up close. In both cases, we prefer to limit the complexity to a fixed set of inputs, for both workflow and performance. It seems other game development studios have been moving away from this approach... we haven't been compelled yet. If shader graphs were decoupled from the runtime, or if we had more engineers to work on a shader graph verifier / optimizer, perhaps it would be different.

Second (and I may be wrong about this): it looks like we would need to do quite a bit of work to generate shaders. MaterialX does not natively generate code for our target platforms, and it is unclear if the code it does generate would be suitable to be fed through a cross-compiler. In addition, there are hardware features that don't exactly fit into the vertex/pixel shader paradigm, e.g. mesh shaders and hardware-accelerated ray tracing.

If there is a MaterialX workflow that supports producing fixed topology materials with a fixed implementation, we may consider that... but clearly that is not proper support, and is only for interoperation with DCC tools.

And WRT my OP, it is not that UsdPreviewSurface would have been sufficient for all of our materials, but I was having trouble with normal maps when converting extant assets to USD.

**Comment by jstone-lucasfilm** [comment]
@hinton-mgi One option you might consider is to use custom shading code to represent your shading model in your real-time renderer, and a MaterialX Physically Based Shading graph to represent your shading model in USD/MaterialX workflows (e.g. in Maya, Houdini, Clarisse, or UsdView).

There's no requirement that you use generated code within your own real-time renderer to benefit from USD/MaterialX as an asset description, and you would always have the option of authoring a specialized MaterialX shader generator further in the future if that proved beneficial.
