### ISSUE TITLE
Is pxr::TfDiagnosticBase::GetPrettyPrintString meant to be public?

### ISSUE THREAD

**Issue by lpapp** [PixarAnimationStudios/USD#1942]
### Description of Issue
Currently, it is  not marked with TF_API, so the linker would fail on Windows when trying to use them. GetCommentary seems to do the same inline, so maybe we are meant to use that instead? But then, why is GetPrettyPrintString part of the public API documentation?

### Steps to Reproduce
1. std::cout << tfError.GetPrettyPrintString() << std::endl;

### System Information (OS, Hardware)

Windows 10

### Package Versions

22.05

**Comment by sunyab** [comment]
Filed as internal issue #USD-7481

**Comment by sunyab** [comment]
Hi @lpapp, that GetPrettyPrintString function is legacy code that should be removed in favor of GetCommentary. We'll fix that, along with adding TF_API to the other public functions in that class. Thanks for calling our attention to this!

**Comment by lpapp** [comment]
Yes, that is what we ended up using after I saw that issue. It is great to get feedback on this as it seems we took the same decision. So, we are on the same page, thank you so much!
