### ISSUE TITLE
[Hydra] Switching Point Instancer Variant Permanently Removes Child Proto Materials

### ISSUE THREAD

**Issue by trebconnell** [PixarAnimationStudios/USD#1960]
### Description of Issue
I did a bit of debugging and have a high-level idea of the issue.  When a variant on a point instancer is switched Hydra removes the point instancer and the material that is a child of the prototype.  When it goes to recreate the material, the material returns true for `IsPopulated` which causes the material to not be recreated.  Therefore, the material is never recreated.

Moving the material out of the point instancer resolves this issue, but this is difficult to achieve in our pipeline.  As we reference mesh that contain their own material definitions into the Protos.

### Steps to Reproduce
1. Open [attached zipped scene](https://github.com/PixarAnimationStudios/USD/files/9169887/PointInstanceVary.zip) in UsdView with any render delegate (I used hdArnold and hdStorm).
2. Change the variant selection on /pointInstancer from "A" to "B"
3. Even though variant has no effect, the material on the cube is removed.  If you switch back to "A" it will not come back.

### System Information (OS, Hardware)
Windows 11

### Package Versions
Reproduced on USD 21.11 and 22.08
It does not reproduce on USD 20.08
I am fairly certain the Hydra 2 adapter caused a regression here.

### Build Flags
Must build with usdimaging

**Comment by sunyab** [comment]
Filed as internal issue #USD-7518
