### ISSUE TITLE
Cannot run install script with python 3.10

### ISSUE THREAD

**Issue by jakkes** [PixarAnimationStudios/USD#1990]
### Description of Issue
Boost installation fails with Python 3.10 (linux) due to old version of Boost being installed, not compatible with Python 3.10. See https://bugzilla.redhat.com/show_bug.cgi?id=1912903

Modifying the installation script to use 1.76.0 (like used on Mac OS) fixes the issue.

### Steps to Reproduce
1. Run the python installation script using Python 3.10 on Linux.

### System Information (OS, Hardware)
Linux

### Package Versions
Latest from git

**Comment by sunyab** [comment]
Filed as internal issue #USD-7557

**Comment by FlorianZ** [comment]
We aren't officially supporting Python 3.10 yet; we currently support VFXPlatform CY2020. Even in CY2022 it is still only 3.9. However, we are currently working on supporting CY2022, which will bring the boost dependency to 1.76.0, and should make this issue go away. Stay tuned!

**Comment by sunyab** [comment]
This should be addressed in the recent 23.02 release: build_usd.py will now use boost 1.78.0 if building with Python 3.10. Closing this out, thanks!
