### ISSUE TITLE
HdxColorizeSelectionTask, _instanceId and _elementId are accessed without null checks

### ISSUE THREAD

**Issue by ShiraoShotaro** [PixarAnimationStudios/USD#1991]
### Description of Issue
I create a new HdRenderPlugin. Its render delegate has 3 aovs (color, depth, primId).
Open usdview, switch renderer, and usdview crashes when I pick an object.

I found a cause,
[pxr/imaging/hdx/colorizeSelectionTask.cpp, Line 286-287, in HdxColorizeSelectionTask::_ColorizeSelection()](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdx/colorizeSelectionTask.cpp#L286)

```
    int32_t *iiddata = reinterpret_cast<int32_t*>(_instanceId->Map());
    int32_t *eiddata = reinterpret_cast<int32_t*>(_elementId->Map());
```

`_instanceId` and `_elementId` are accessed without null checks. (My render delegate does not provide instanceId nor elementId aov.)

cf. In HdxPickFromRenderBufferTask, they are accessed with null checks.
[pxr/imaging/hdx/pickFromRenderBufferTask.cpp, Line 191-196, in HdxPickFromRenderBufferTask::Execute()](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/imaging/hdx/pickFromRenderBufferTask.cpp#L191)

```
    uint8_t *elementIdPtr = _elementId ? 
                            reinterpret_cast<uint8_t*>(_elementId->Map()) : 
                            nullptr;
    uint8_t *instanceIdPtr = _instanceId ? 
                             reinterpret_cast<uint8_t*>(_instanceId->Map()) : 
                             nullptr;
```

I fixed ColorizeSelectionTask in reference to PickFromRenderBufferTask in my local, and the issue is cleared.

### Steps to Reproduce
1. Implement a new render delegate provides color, depth and primId aovs.
2. Install plugin.
3. Open usdview.
4. Switch renderer; [View] -> [Hydra Renderer] -> [(Installed render plugin's name)]
5. Pick object via viewport.

### System Information (OS, Hardware)
OS: Windows 10 Pro (Version 21H2)
CPU: Intel&reg; Core&trade; i3-4170
RAM: 8GB
GPU: GeForce GTX 980Ti (6GB)

### Package Versions
USD 22.08 (with python 3.9)

### Build Flags
Built by python build script,
```
python build_scripts\build_usd.py^
    --build-variant release^
    --build-shared^
    install\py39
```

Sincerely,
Shotaro Shirao.
(Sorry for my bad English.)

**Comment by sunyab** [comment]
Filed as internal issue #USD-7558
