### ISSUE TITLE
Instructions suggest installing USD into a protected area in Windows

### ISSUE THREAD

**Issue by OldManMeta** [PixarAnimationStudios/USD#1994]
As per the instructions for installation on Windows:

Run this command -
python USD\build_scripts\build_usd.py "C:\Program Files\USD"

Program Files has a space in it, which breaks the installer, but the key issue here is that Program Files are a protected Windows folder.

Something to look at would be CPack or WiX mechanic in the scripts, which could possibly execute and elevated process - but that could be a nasty route of course. It may be far easier to just create some new instructions to install to a local c:\USD\Install directory?

Cheers

**Comment by sunyab** [comment]
Filed as internal issue #USD-7559
