### ISSUE TITLE
Mismatched Tags Warnings

### ISSUE THREAD

**Issue by superfunc** [PixarAnimationStudios/USD#2]
Platform: Mac OSX
Compiler: Apple LLVM version 7.3.0 (clang-703.0.31)

There are currently several occurrences of ```-Wmismatched-tags``` being triggered when building on newer compilers, such as relatively current clang. This comes from forward declarations of types not matching the way in which they were defined, i.e. one uses the keyword ```struct``` and another uses ```class```.  These should be cleaned up.

**Comment by amooty** [comment]
Filed as internal issue #135153.

**Comment by sunyab** [comment]
This should be addressed with b0f30efc. Closing!
