### ISSUE TITLE
Provide an AUR package for usd or usd22

### ISSUE THREAD

**Issue by Technetium1** [PixarAnimationStudios/USD#2001]
### Description of Issue
The [latest version](https://aur.archlinux.org/packages/usd21) of USD on the [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository) is an outdated version of 21.XX that doesn't build anymore. The developer previously created and maintained versions 19 and 20, but is unlikely to make a new package for 22 because they are helping out at the border of Ukraine and have no access to their machine.

To follow the naming scheme, `usd22` could be for version 22.XX, or just `usd` if it will always be at the latest version.

### System Information (OS, Hardware)
Arch Linux

### Package Versions
22.XX

**Comment by adro79** [comment]
I was just working on this, unfortunately I have some errors trying to build it in Arch Linux.
Once my issue's fixed I'll try to create the package.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7578

**Comment by Technetium1** [comment]
It would be nice to also have `usd-git` for people that want to be on the bleeding edge.

**Comment by FlorianZ** [comment]
Unfortunately, we are not the maintainers of this AUR package and aren't planning on taking on that responsibility, though we think it's cool. We would love to see the community help out here. Thank you!!
