### ISSUE TITLE
Hydra instance categories broken with nested instanceable references

### ISSUE THREAD

**Issue by dleex** [PixarAnimationStudios/USD#2002]
### Description of Issue
HdSceneDelegate::GetInstanceCategories() returns wrong number of entries (and seemingly bogus data when lightlinking is present) when used with nested instanceable references.

### Steps to Reproduce
1. Sublayer and render using provided .usda file
2. In Sync() of the inner prototype mesh, invoke HdSceneDelegate::GetInstanceCategories(), and note that the number of entries of the returned array is different from the actual number of instances. (the instance mapping from HdSceneDelegate::GetInstanceIndices() will map to out of bounds)

### Package Versions
Reproducible in 22.05 (haven't tested other versions)

[instancecategories.zip](https://github.com/PixarAnimationStudios/USD/files/9389575/instancecategories.zip)

**Comment by dleex** [comment]
Happens in 21.08 as well.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7579
