### ISSUE TITLE
Windows Builds in PRs Timing Out

### ISSUE THREAD

**Issue by creijon** [PixarAnimationStudios/USD#2005]
### Description of Issue

A lot of PRs are failing checks due to the Windows configuration timing out after 30 minutes. This appears to be pretty random, some single-line changes are hitting the issue while other extensive commits are going through without issue.

### Steps to Reproduce
1. Make a PR into dev here.
2. Frequently the Windows build fails.

**Comment by nvidia-jomiller** [comment]
It might be different but I was running into a similar issue with my [PR](https://github.com/PixarAnimationStudios/USD/pull/1987) (however it was always hanging / timing out). In [build_usd.py](https://github.com/PixarAnimationStudios/USD/pull/1987#discussion_r949641673) I needed to force UTF-8 for non-interactive terminals. After making that change I had no issues with Windows builds timing out on Azure.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7581

**Comment by creijon** [comment]
Thanks @davidgyu
