### ISSUE TITLE
Value Clips break if the stage layer stack is modified before reading values

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#2014]
### Description of Issue
When a value clip is loaded, a USD_Clip object is created per-clip. But the layer for that clip is not immediately loaded. Instead, the clip layer loading is deferred until a value is needed from that layer. Because of the way Usd_Clip stores the layer that owns the clip metadata, the calculation of the clip file path will be wrong if the stage's layer stack is modified after the Usd_Clip object is created, but before the value is read.

### Steps to Reproduce
1. Unzip this file: 
[cubeclip.zip](https://github.com/PixarAnimationStudios/USD/files/9437156/cubeclip.zip)
2. From the directory containing cube.usda, run this python script:
```
from pxr import Sdf, Usd
s = Usd.Stage.Open('cube.usda')
l = Sdf.Layer.CreateAnonymous()
s.GetSessionLayer().subLayerPaths.append(l.identifier)
p = s.GetPrimAtPath('/geo/cube')
a = p.GetAttribute('size')
print(a.Get(3))
```
3. The output value will be 2.0 instead of the correct value of 1.0833333. This is because the individual clip files are not being found.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7603
