### ISSUE TITLE
USD physics

### ISSUE THREAD

**Issue by alelordelo** [PixarAnimationStudios/USD#2021]
Hi USD team,

On this post NVIDIA mentions 

“Starting today, developers can create and share realistic simulations in a standard way. Apple, NVIDIA and Pixar Animation Studios have defined a common approach for expressing physically accurate models in Universal Scene Description (USD), the common language of virtual 3D worlds. “

And…

“Apple and NVIDIA were both independently working on ways to describe physics in simulations. As members of the SIGGRAPH community, we came together with Pixar to define a single approach as a new addition to USD. 

In the spirit of flexibility, the extension lets developers choose whatever solvers they prefer as they can all be driven from the same set of USD-data. This presents a unified set of data suitable for off-line simulation for film, to games, to augmented reality. 

That’s important because solvers for real-time uses like gaming prioritize speed over accuracy, while architects, for example, want solvers that put accuracy ahead of speed. “

My question…

What is the current state of this USD physics collaboration?

 Ex, if I need soft bodies I need to use Nvidia own physics solver.l which doesn’t support macOS.

 Is there a plan for a USD soft bodies like cloth for ex?

thanks

**Comment by tallytalwar** [comment]
Hello @alelordelo 

Thanks for bringing this up, I am posting a reply on behalf of David Eberle, here at Pixar:

> We are just getting started on a discussion for a schema for deformable simulation of strands, shells/cloth and volumes. There is far less standardization among commercially available deformable solvers than rigid bodies. This makes defining a common and useful schema for deformables much more difficult. Some solvers are FEM based, while others are PBD/XPBD. The material models can also vary greatly. The expectation of being able to export a deformable scene and simulate it elsewhere and get the "same" results isn't a reasonable goal in our opinion. Instead it is more a question of what information we should export via a base schema and then leave the interpretation to the individual solver implementations. Even when a schema is available for cloth, you'd need to choose a solver that can import it. It will be up to the DCCs like Marvelous Designer, Z-Emotion, Houdini, Maya, Qualoth, etc to adopt the schema. Due to NVidia's efforts on Omniverse, I'd think they would likely be an early adopter.

**Comment by alelordelo** [comment]
Thanks for the the elaborated answer @tallytalwar!

So the plan is to have a common schema (mechanical properties like friction, bending, etc) and not a built in solver )like XPBD)?

Ex, we now have rigid bodies physics built into USD, without the need to use an external engine. Is there a plan for Soft Bodies (like PBD or XPBD) built into USD?

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7611

**Comment by tallytalwar** [comment]
So to clarify USD codebase does not provide any physics engine. USDPhysics schema domain currently provides a scene description to represent rigid body physics. And there isn't a public generic scene description for soft bodies for the reasons mentioned [above](https://github.com/PixarAnimationStudios/USD/issues/2021#issuecomment-1238527366).

Omniverse however does provides a rigid body solver and soft body solution.

I am going to close the issue, but please reopen/create another if you need any further assistance.

Thanks
