### ISSUE TITLE
Error: double free or corruption

### ISSUE THREAD

**Issue by msercheli** [PixarAnimationStudios/USD#2032]
### Description of Issue
I am running into an error which I believe comes from MALLOC checking.
The error (in summary) is ```double free or corruption```. The full error message is at the end of this message.
The error occurs when, in Python, UsdImagingGL is imported without UsdMtlx being imported first.
The error actually only occurs once the Python process exits.

It was first noticed when running ```usdrecord``` (or ```usdview```) from the command line.
Since ```usdrecord``` import UsdAppUtils, which in turn depends on UsdImagingGL, the error occurs.
I believe usdview relies on UsdImagingGL as well. Both ```usdrecord``` and ```usdview``` runs fine.
The error happens when ```usdrecord``` exits (or ```usdview``` is closed).

The rest of USD works fine. It could be something in my environment or a faulty build.

### Steps to Reproduce
1. From a shell, run _**python3**_ (same Python used to build USD)
2. ```from pxr import UsdImagingGL```
3. ```exit()```
4. After exiting, the error message is printed.
5. To avoid the error, one can import UsdMtlx before importing UsdImagingGL

### Steps to Avoid the Error
1. From a shell, run _**python3**_ (same Python used to build USD)
2. ```from pxr import UsdMtlx```
3. ```from pxr import UsdImagingGL```
4. ```exit()```
5. After exiting, there should be no error.

### System Information (OS, Hardware)
- CentOS 7
- OpenGL info:
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 3080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 460.84
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 460.84
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 460.84
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

### Package Versions
- GCC 6.3.1
- USD 22.05
- TBB 2018.6
- Boost  1.70.0
- Python 3.9.7
- MaterialX 1.38.0
- OpenSubdiv 3.4.4
- PyOpenGL 3.1.6
- OCIO 1.1.0
- OIIO 2.1.16.0
- OpenEXR 2.3.0
- OpenVdb 6.1.0
- OSL 1.9.13
- Ptex 2.1.33
- PySide2-setup 5.14.1
- qtbase 5.14.1
- Alembic 1.7.10
- blosc 1.5.4
- hdf5 1.10.0
- libjpeg 9.2
- libpng 1.6.29
- libtiff 4.0.7
- numpy 1.23.1

### Build Flags
-DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True

### CMake Options
```
PXR_STRICT_BUILD_MODE OFF
PXR_VALIDATE_GENERATED_CODE OFF
PXR_HEADLESS_TEST_MODE OFF
PXR_BUILD_TESTS ON
PXR_BUILD_EXAMPLES ON
PXR_BUILD_TUTORIALS ON
PXR_BUILD_USD_TOOLS ON
PXR_BUILD_IMAGING ON
PXR_BUILD_EMBREE_PLUGIN OFF
PXR_BUILD_OPENIMAGEIO_PLUGIN ON
PXR_BUILD_OPENCOLORIO_PLUGIN ON
PXR_BUILD_USD_IMAGING ON
PXR_BUILD_USDVIEW ON
PXR_BUILD_ALEMBIC_PLUGIN ON
PXR_BUILD_DRACO_PLUGIN OFF
PXR_BUILD_PRMAN_PLUGIN OFF
PXR_ENABLE_MATERIALX_SUPPORT ON
PXR_BUILD_DOCUMENTATION OFF
PXR_ENABLE_PYTHON_SUPPORT ON
PXR_USE_PYTHON_3 ON
PXR_USE_DEBUG_PYTHON OFF
PXR_ENABLE_HDF5_SUPPORT ON
PXR_ENABLE_OSL_SUPPORT ON
PXR_ENABLE_PTEX_SUPPORT ON
PXR_ENABLE_OPENVDB_SUPPORT ON
PXR_ENABLE_NAMESPACES ON
PXR_PREFER_SAFETY_OVER_SPEED ON
PXR_USE_AR_2 ON
PXR_ENABLE_METAL_SUPPORT FF
PXR_ENABLE_VULKAN_SUPPORT OFF
PXR_ENABLE_GL_SUPPORT ON
```

## Full Error Message
Here is the complete error message (without the "======= Memory map: ========" dump information):
```
*** Error in `python': double free or corruption (!prev): 0x0000000001fad6e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7fecb2a9b329]
/mnt/rez/release/ext/usd/22.05.sse.1.0.0/platform-linux/arch-x86_64/os-centos-7/python-3.9.7/ptex-2.1.33/lib/python/pxr/UsdImagingGL/../../../libusd_hdSt.so(_ZNSt13unordered_mapISsPFSt10shared_ptrIN9MaterialX5ValueEERKSsESt4hashISsESt8equal_toISsESaISt4pairIS4_S7_EEED1Ev+0xbd)[0x7feca8d4eced]
/lib64/libc.so.6(+0x39ce9)[0x7fecb2a53ce9]
/lib64/libc.so.6(+0x39d37)[0x7fecb2a53d37]
/mnt/rez/release/ext/python/3.9.7/platform-linux/arch-x86_64/os-centos-7/lib/libpython3.9.so.1.0(+0x1f7579)[0x7fecb3b3b579]
/mnt/rez/release/ext/python/3.9.7/platform-linux/arch-x86_64/os-centos-7/lib/libpython3.9.so.1.0(+0x1fbaeb)[0x7fecb3b3faeb]
/mnt/rez/release/ext/python/3.9.7/platform-linux/arch-x86_64/os-centos-7/lib/libpython3.9.so.1.0(PyRun_InteractiveLoopFlags+0xbd)[0x7fecb3b4095d]
/mnt/rez/release/ext/python/3.9.7/platform-linux/arch-x86_64/os-centos-7/lib/libpython3.9.so.1.0(PyRun_AnyFileExFlags+0x3e)[0x7fecb3b4120e]
/mnt/rez/release/ext/python/3.9.7/platform-linux/arch-x86_64/os-centos-7/lib/libpython3.9.so.1.0(Py_RunMain+0x8be)[0x7fecb3b60a7e]
/mnt/rez/release/ext/python/3.9.7/platform-linux/arch-x86_64/os-centos-7/lib/libpython3.9.so.1.0(Py_BytesMain+0x47)[0x7fecb3b60dc7]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fecb2a3c555]
python[0x40065e]
```

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7631

**Comment by bfloch** [comment]
Been chasing this, as it is reproducible in the aswf-docker builds (Usd 22.05a, MaterialX 1.38.0).

I believe @sunyab found the cause here:
https://github.com/AcademySoftwareFoundation/MaterialX/issues/485

As such the solution might be to use a shared build of MaterialX.

I haven't been able to switch but I've suggested this in the past via:
https://github.com/AcademySoftwareFoundation/aswf-docker/issues/157 

EDIT:
Side-note: Shared builds require MaterialX 1.38.3 and as such USD 22.08 I believe)

**Comment by tallytalwar** [comment]
Hello As of change 034df39a78a5fc4cada49b545ad2a87fd6666e1d the minimum MaterialX version we test for USD internally is 1.38.4. 

As you already noted, since 22.08, using a shared library for materialx is a requirement which requires materialx version 1.38.3+.

Kindly let us know if you continue to see the double free crash when using shared mtlx library?
Thanks
