### ISSUE TITLE
Out of range memory access from Hydra texture loader

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#204]
GlfUVTextureData::_GetNumMipLevelsValid(const GlfImageSharedPtr image) const can generate an out of range array access in OIIO.

Larry just patched OIIO to safely enable the use pattern in _GetNumMipLevelsValid.

Please see https://github.com/OpenImageIO/oiio/issues/1670

**Comment by jtran56** [comment]
Filed as internal issue #145500.

**Comment by sunyab** [comment]
This is the same issue as #99, so I'm going to copy this info over and close this issue in favor of that one. Thanks!
