### ISSUE TITLE
Can't build on macOS Monterey

### ISSUE THREAD

**Issue by bhartsb** [PixarAnimationStudios/USD#2049]
### Description of Issue
Doesn't build on macOS Monterey.  
### Steps to Reproduce
1. 
Followed instructions given here:
https://developer.apple.com/documentation/metal/metal_sample_code_library/creating_a_3d_application_with_hydra_rendering

In terminal:
python3 build_scripts/build_usd.py --generator Xcode --no-python ./USDInstall                                                                                                                                                           

Building with settings:
  USD source directory          /Users/user/Desktop/USD
  USD install directory         /Users/user/Desktop/USD/USDInstall
  3rd-party source directory    /Users/user/Desktop/USD/USDInstall/src
  3rd-party install directory   /Users/user/Desktop/USD/USDInstall
  Build directory               /Users/user/Desktop/USD/USDInstall/build
  CMake generator               Xcode
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Variant                     Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          Off
      OpenImageIO support:      Off 
      OpenColorIO support:      Off 
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  Off
    Python support              Off
      Python Debug:             Off
      Python 3:                 On
    Documentation               Off
    Tests                       Off
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  zlib, boost, TBB, OpenSubdiv
STATUS: Installing zlib...
2022-09-25 22:19
cmake -DCMAKE_INSTALL_PREFIX="/Users/bhart/Desktop/USD/USDInstall" -DCMAKE_PREFIX_PATH="/Users/bhart/Desktop/USD/USDInstall" -DCMAKE_BUILD_TYPE=Release -DCMAKE_MACOSX_RPATH=ON -G "Xcode"   "/Users/user/Desktop/USD/USDInstall/src/zlib-1.2.11"
-- The C compiler identification is AppleClang 14.0.0.14000029
CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_C_COMPILER could be found.
### System Information (OS, Hardware)
macOS Monterey, Intel MBP

**Comment by meshula** [comment]
Hi there, this message

```
CMake Error at CMakeLists.txt:4 (project):
No CMAKE_C_COMPILER could be found.
```
generally means the xcode command line tools haven't been installed.

if you type `xcode-select -p` you should get this result ~
```
/Applications/Xcode.app/Contents/Developer
```

but you most likely won't get that. To fix it,

`xcode-select --install`

should set you up. After that has finished, please close the terminal window, and start a new one. `xcode-select -p` should verify the path, then you can try building USD again.

**Comment by bhartsb** [comment]
Hi @meshula ,
Xcode 14 and Xcode command line tools are installed.  I even reinstalled to make certain.
Same result.

**Comment by creijon** [comment]
Hi @bhartsb , there were issues with older versions of cmake and Xcode.  What version of cmake do you have installed, and the version string from Xcode (In Xcode, select Xcode -> About Xcode)?

**Comment by jonny-apple** [comment]
And there has been a fix in the latest beta release of Xcode 14.1:
- https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_14.1_beta_2/Xcode_14.1_beta_2.xip

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7656

**Comment by bhartsb** [comment]
@jonny-apple Xcode Version 14.0 (14A309), CMake 3.17.0

**Comment by creijon** [comment]
Hi @bhartsb , can you please upgrade to CMake 3.23.1 or later?  I think this will resolve your issues.

**Comment by petertretyakov** [comment]
Hi @bhartsb! I had the same issue even with the CMake 3.24. It was because of zlib installation. If you look at `%install_path%/zlib-%version%/CMakeFiles/CMakeError.log` you'll find the actual error there

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

It can be fixed in Xcode. Open Xcode > Preferences > Locations and Select Command Line Tools there. There will be only one option with the current Xcode version if you don't use additional toolchains.

**Comment by creijon** [comment]
Excellent information @petertretyakov

**Comment by spiffmon** [comment]
Closing, as it sounds like @bhartsb 's issues have solutions.
