### ISSUE TITLE
import pxr.Usd got error

### ISSUE THREAD

**Issue by ryannas** [PixarAnimationStudios/USD#2051]
### Description of Issue
After building usd successfully, I tried usdview command to check if usd works. but I got this error:
```
Traceback (most recent call last):
  File "/usr/local/USD/bin/usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "/usr/local/USD/lib/python/pxr/Usdviewq/__init__.py", line 27, in <module>
    from pxr import Tf
  File "/usr/local/USD/lib/python/pxr/Tf/__init__.py", line 163, in <module>
    PreparePythonModule()
  File "/usr/local/USD/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/USD/lib/python/pxr/Tf/_tf.so: undefined symbol: _ZN5boost6python15instance_holder8allocateEP7_objectmm
```
### Steps to Reproduce
1. Modify build_usd.sh BOOST_URL to https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.gz
    I do this because I'm using python 3.10, and I met the same problem with [USD/issues/2047](https://github.com/PixarAnimationStudios/USD/issues/2047), so I follow the instruction blow this issue.
2. run build script to build usd
3. try to exec usdview or run a python file including "import pxr.Usd"

### System Information (OS, Hardware)
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: NVIDIA GeForce RTX 3090
OS: Arch Linux x86_64
Kernel: 5.19.11-arch1-1

### Package Versions
22.08

**Comment by ryannas** [comment]
After switching to python3.8 and rebuilding with default build_usd.sh, the problem solved.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7665

**Comment by sunyab** [comment]
Thanks for letting us know, closing this out.
