### ISSUE TITLE
Unable to do install the USD

### ISSUE THREAD

**Issue by jernav09** [PixarAnimationStudios/USD#2056]
### Description of Issue
When I am running the > python USD/build_scripts/build_usd.py /usr/local/USD. I get the following error. 
<img width="1195" alt="Screen Shot 2022-10-05 at 4 03 08 PM" src="https://user-images.githubusercontent.com/115112997/194152386-b875f3f9-1d13-41cc-8951-e75d2c37e9f0.png">

**Comment by meshula** [comment]
Hi! Your error report shows `(missing: python310) (found version "1.70.0")` ~ Python 3.10 requires an upgrade to boost 1.78.0. If possible the easiest workaround is to use python 3.9. There's more discussion here: https://github.com/PixarAnimationStudios/USD/pull/2007

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7682

**Comment by sunyab** [comment]
The recent 23.02 release added support for Python 3.10. Please give that a try, if you run into other problems please file a new issue. Thanks!
