### ISSUE TITLE
Ar.GetResolver().GetAssetInfo() fails in Python - No to_python (by-value) converter found

### ISSUE THREAD

**Issue by ColinKennedy** [PixarAnimationStudios/USD#2065]
### Description of Issue
`pxr.Ar.GetAssetInfo()` fails to run, in Python. It errors with 

```
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    print(_RESOLVER.GetAssetInfo(uri, resolved))
TypeError: No to_python (by-value) converter found for C++ type: pxrInternal_v0_22__pxrReserved__::ArAssetInfo
```

I'm writing this page as a follow up to this usd-interest post: https://groups.google.com/g/usd-interest/c/gmWUJpu5pBM

### Steps to Reproduce
- Install USD (I was using 22.08, at the time of writing)

- Attempt to call Ar.GetAssetInfo()
```python
from pxr import Ar


_RESOLVER = Ar.GetResolver()
text = "/path/to.usda"
resolved = _RESOLVER.Resolve(text)
print(_RESOLVER.GetAssetInfo(text, resolved)) 
```

And you'll get the traceback, shown above

### System Information (OS, Hardware)
- CentOS 7

### Package Versions
- USD 22.08
- Python 3

### Build Flags
Vanilla `build_usd.py` settings

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7720
