### ISSUE TITLE
Test failures with debug build with alembic support

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#207]
### Description of Issue
Some of the tests fail if run using a debug build with alembic support - specifically, testUsdDiffToolVariousFormats3 - 5.  The error message that gets printed is:

```
------------------------ 'python2.7' is dying ------------------------
python2.7 crashed. FATAL ERROR: [TF_DEBUG_ENVIRONMENT_SYMBOL] multiple symbol definitions.  This is usually due to software misconfiguration.  Contact the build team for assistance. (duplicate 'USD_CHANGES')
in _Add at line 102 of /mnt/Samsung/luma/rez-build/usd/dev/src/pxr/base/lib/tf/debug.cpp

The stack can be found in ws-020.luma.la:/var/tmp/st_python2.7.19851
done.
------------------------------------------------------------------
```

### Steps to Reproduce
1. Build usd with debug mode (`-D CMAKE_BUILD_TYPE=Debug`) and alembic support (`-D PXR_BUILD_ALEMBIC_PLUGIN=TRUE`)
2. cd to the build dir
3. run `make test ARGS='-R testUsdDiffToolVariousFormats3'`

Alternatively, instead of 3, you can do this simpler procedure:
3a.
```
export PATH="/path/to/built/usd/bin:$PATH"
export PYTHONPATH="/path/to/built/usd/lib/python:$PYTHONPATH"
python -c "import pxr.Sdf; print pxr.Sdf.FileFormat.FindByExtension('abc')"
```

### System Information (OS, Hardware)
Linux (CentOS 7)

### Package Versions
usd - dev branch, 942c8623be49013d2eda195e72d7ae80abff6841
alembic-1.5.8

### Build Flags

    -D CMAKE_INSTALL_PREFIX=/path/to/built/usd
    -D QT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4
    -D PXR_MAYA_TBB_BUG_WORKAROUND=TRUE
    -D PXR_ENABLE_PTEX_SUPPORT=OFF
    -D PXR_BUILD_ALEMBIC_PLUGIN=TRUE
    -D ALEMBIC_DIR=/path/to/alembic
    -D TBB_ROOT_DIR=/path/to/tbb
    -D CMAKE_BUILD_TYPE=Debug
    -D PXR_BUILD_MAYA_PLUGIN=TRUE
    -D PXR_BUILD_KATANA_PLUGIN=%(build_katana)s
    -D PXR_MALLOC_LIBRARY:path=/path/to/jemalloc
    -D PXR_STRICT_BUILD_MODE=TRUE
    -D PXR_SYMLINK_HEADER_FILES:bool=TRUE
    -D CMAKE_CXX_COMPILER=/usr/lib64/ccache/g++
    -D CMAKE_C_COMPILER=/usr/lib64/ccache/gcc

**Comment by elrond79** [comment]
After dropping into the debugger, I was able to confirm that "USD_CHANGES" _is_ getting added to the registry twice - once when the "usdAbc" plugin loads (this happens first), and once when the "usd" plugin loads.

Can't copy in the full stack trace, unfortunately, due to internet restrictions on our workstations here...

**Comment by elrond79** [comment]
Ok, uploaded the stacktraces - these are the stacks at the points when "USD_CHANGES" is added to the registry, in the order they happen...

[usd_alembic_debug_crash__load_usdAbc.stacktrace.txt](https://github.com/PixarAnimationStudios/USD/files/971729/usd_alembic_debug_crash__load_usdAbc.stacktrace.txt)
[usd_alembic_debug_crash__load_libusd.stacktrace.txt](https://github.com/PixarAnimationStudios/USD/files/971730/usd_alembic_debug_crash__load_libusd.stacktrace.txt)

**Comment by jtran56** [comment]
Filed as internal issue #146045.

**Comment by pmolodo** [comment]
This is now confirmed to work as of 23.02 (though probably fixed long before). Closing.
