### ISSUE TITLE
MaterialX material with name "material" fails to render in HdStorm

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#2076]
### Description of Issue

Consider following USDA:
```
#usda 1.0

def Sphere "ball" (
    apiSchemas = ["MaterialBindingAPI"]
)
{
    rel material:binding = </Materials/material>
}

def Scope "Materials"
{
    def Material "material"
    {
        color3f inputs:base_color = (0.2, 0.4, 1)
        token outputs:mtlx:surface.connect = </Materials/material/SS.outputs:surface>

        def Shader "SS"
        {
            uniform token info:id = "ND_standard_surface_surfaceshader"
            color3f inputs:base_color.connect = </Materials/material.inputs:base_color>
            token outputs:surface
        }
    }
}
```

where a material has the name "material" (which is common).

It fails to render in HdStorm and other renderers using the `HdMtlxCreateMtlxDocumentFromHdNetwork` function with an exception thrown from the MaterialX library:
```
Child name is not unique: material
```

### Steps to Reproduce
Open above snippet with usdview

### System Information (OS, Hardware)
Windows, RTX 2060

### Package Versions
USD v22.11

### Build Flags
`--materialx --build-variant release --opencolorio --openimageio`

**Comment by sunyab** [comment]
Filed as internal issue #USD-7739
