### ISSUE TITLE
Build error due to C++17 feature used in OpenVDB 10

### ISSUE THREAD

**Issue by brechtvl** [PixarAnimationStudios/USD#2081]
### Description of Issue

USD sets `CMAKE_CXX_STANDARD` to 14, with no apparent build option to change it. The new OpenVDB 10 release is using C++17 features in its header files. This results in build errors, see AcademySoftwareFoundation/openvdb#1513.

The obvious solution seems changing `CMAKE_CXX_STANDARD` to 17 in USD, especially since the VFX reference platform 2021, 2022 and 2023 all use this. But I imagine such changes are not made lightly. 

### Steps to Reproduce

* Build USD with OpenVDB 10 on Windows.

### System Information (OS, Hardware)

Windows 10, Visual Studio 2019.

### Package Versions

USD 22.11
OpenVDB 10.0.0

### Build Flags

Default flags.

**Comment by meshula** [comment]
build_usd.py currently sets things up for vfx2020, and will migrate to a later year as development progresses of course. In the mean time, perhaps the best thing to do is to make the change to `CMAKE_CXX_STANDARD` locally?

**Comment by brechtvl** [comment]
I wanted to raise this issue because I expect other projects will run into the same problem as they upgrade to vfx2023. As far as I know latest USD builds fine with vfx2021 and vfx2022 libraries, but maybe by luck and not as an explicit goal of the USD project?

Certainly it's no big deal for us to patch it locally if needed.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7744

**Comment by ghost** [comment]
@brechtvl Brecht, 

stop making lies about real  Engineering. Stop being a wannabe. You'll never be an engineer, period.
You are not an engineer, never were, and never will be close. Engineering has nothing to do with sitting behind keyboard and writing code. There is no such thing as "software" "engineer". That is the stupidest, most pathetic & disrespectful lie ever. 
Stop being disrespectful to real engineering (mechanical engineering is the ONLY engineering).

Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. 
Software dev is easy and has absolutely nothing to do with engineering, you are just being stupid liars. 
You daft software kiddos will never be engineers, not even close. 

Mechanical Engineering is the ONLY engineering. Period.

**Comment by brechtvl** [comment]
This was solved in 0e4d360.
