### ISSUE TITLE
Example: Read USD animation and update mesh in world Space 

### ISSUE THREAD

**Issue by zihaoli8** [PixarAnimationStudios/USD#2094]
### read USD animation and update mesh in world Space Example
Hi guys, I'm trying to read prim with animation, is there a example to illustrate how to use skel position(joint local space) to update mesh point(world space) in each frame, please? Thanks

**Comment by Zihaoli-1** [comment]
![image](https://user-images.githubusercontent.com/108557117/202050861-22acbf07-2d52-4afa-a6e0-de1597ae207e.png)
For here, I can get joint position for each frame in joint local space and skeleton space, how can i update the bind the prims which skinned by this skeleton in each frame? Can any one helps?

**Comment by sunyab** [comment]
Filed as internal issue #USD-7779

**Comment by spiffmon** [comment]
Hi @zihaoli8 , I think that [this test](https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/usdSkel/testenv/testUsdSkelBakeSkinning.py) should show you what you need to do?

**Comment by FlorianZ** [comment]
Closing this, but feel free to re-open if the provided code example is not helpful. Thank you!
