### ISSUE TITLE
ComputeLocalToWorldTransform(Usd.TimeCode.Default()) return constant value

### ISSUE THREAD

**Issue by pedped** [PixarAnimationStudios/USD#2099]
### Description of Issue
I am using Nvidia Omniverse Isaac Sim, it is based on the USD, I am training a robot and during training, the position of the robotic head will change, I am using these method to get the transform

`UsdGeom.Xformable(primPath).ComputeLocalToWorldTransform(Usd.TimeCode.Default())`

it works well and the returned value is not the same ( as expected ), but when we are using headless=True which does not show the Omniverse Program or any view, the returned value of that method is not changing! it always send same value.

what can cause the problem? is there alternative to this method?

**Comment by asluk** [comment]
Hi @pedped , headless=True is specific to Isaac Sim, those forums are a better place to dive deeper into this, ideally with a full repro that the Isaac Sim developers can diagnose directly - https://forums.developer.nvidia.com/c/agx-autonomous-machines/isaac/simulation/69

Thanks~

**Comment by sunyab** [comment]
As @asluk said, this question is specific to Nvidia Omniverse and should be directed to Nvidia's support forum. Closing this out, thanks!
