### ISSUE TITLE
Need to forward declare struct _PathItemHeader;

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#21]
_PathItemHeader needs to be forward declared in crateFile.h. For whatever reason, MSVC takes the declaration in _ReadPathsRecursively to be declaring _PathItemHeader as a nested class, and so the compilation of crateFile.cpp fails. 

Adding
```
struct _PathItemHeader;
```

around line 67 of crateFile.h solves it.

**Comment by amooty** [comment]
Filed as internal issue #135884.

**Comment by c64kernal** [comment]
For what it's worth, we think this is resolved in future updates (It sounds like by Update 3, it's no longer necessary), but we'd like to support earlier versions if possible, so thanks for the report, Nick!
