### ISSUE TITLE
HGI Method name "MemoryBarrier" breaks building on Windows ARM64 platforms

### ISSUE THREAD

**Issue by anthony-linaro** [PixarAnimationStudios/USD#2105]
### Description of Issue
When building USD for Windows on ARM64 (currently as a part of blender), an error occurs, in where it states invalid arguments are given to the macro 'MemoryBarrier'.

After some digging, it appears that in the SDK header `winnt.h`, which is included by `windows.h` defines a macro, the functional equivalent of the x64 `_m_fence` intrinsic, named `MemoryBarrier` on ARM64 platforms (nopte, this is also true for other platforms, but only seems to be an issue on ARM64 - perhaps due to the fact intrinsics are required as opposed to using inline ASM).

It appears that the two definitions (the other one being in `hgi\blitcmds.h` and others) clash, which breaks the compilation.

### Steps to Reproduce
1. Apply attached diff file (this applies fix number 1 as specified below)
2. Attempt to compile for Windows ARM64.

### Possible fixes
Now, the fix for this is likely to be tricky to do cleanly, and essentially boils down to the following 2 options as far as I can tell:
1. In each of the affected header files (`blitCmds.h`, `computeCmds.h`, and `graphicsCmds.h` within HGI), add the snippet:
```c
#ifdef _M_ARM64
#undef MemoryBarrier
#endif
```
This option is the least amount of work, but future builds could break in the event of another header being added with the same prototype defined, etc. It's also directly undefining a System-level macro, which IMO is not particularly good practise.

2. `MemoryBarrier` is renamed within the HGI headers to something which does not conflict. Given I am not massively familiar with USD (I am working on this as a smaller part of Blender ARM64 enablement), I am unsure of the implications of this change, which would possibly have knock-on effects elsewhere.

### System Information (OS, Hardware)
Thinkpad X13s w/ Windows 11 Pro 22621 ARM64, and 22621 SDK.

### Attachments
Here is the required diff to add ARM64 support - note this is a work in progress, and is only tested as being compiled as part of blender - it also includes some of the blender-specific changes they make themselves.
[usd.zip](https://github.com/PixarAnimationStudios/USD/files/10057946/usd.zip)

**Comment by sunyab** [comment]
Filed as internal issue #USD-7788

**Comment by spiffmon** [comment]
Thanks for the report, @anthony-linaro . Always a bit disheartening to see cpp macros being abusive with identifier theft. But in this case I do think the Hgi method names could be changed to accommodate.

**Comment by anthony-linaro** [comment]
Thanks, @spiffmon - any particular preferences on what to rename to? I can do this as a part of my wider ARM64 support patches.

**Comment by FlorianZ** [comment]
This will be fixed in 23.02. Thank you!
