### ISSUE TITLE
install codegenTemplates

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#211]
### Description of Issue
the codegenTemplates directory is not installed in the bin dir, so any time "usdGenSchema" is run, it needs to be pointed at a source-code checkout (or the directory needs to be manually copied)

This issue is referenced in https://github.com/PixarAnimationStudios/USD/issues/158, but I felt it deserved it's own issue.

### Steps to Reproduce
1. Do a default / fresh usd build + install
2. `cd` to a directory with a valid `schema.usd` file
3. Run `usdGenSchema`
4. It will error if the "-t/--templates" arg is not set, because the default templates are not installed in `${USD_INSTALL_ROOT}/bin/codegenTemplates`

**Comment by meshula** [comment]
+1 This would for sure be a boon to people developing plugins, but relying on a distributed package.

**Comment by jtran56** [comment]
Filed as internal issue #146333.

**Comment by chadrik** [comment]
Are there any complicating factors to this issue or is it as simple as adding some `install` commands to cmake?
