### ISSUE TITLE
All dependencies installed when using build_usd.py

### ISSUE THREAD

**Issue by lijenicol** [PixarAnimationStudios/USD#2117]
### Description of Issue

Hey hey, I am using `build_usd.py` to build USD and I want to be able to tell the build process to skip downloading/building Boost as I already have my own custom build of it. From what I see, there is no way that I can specifically turn off building Boost/other dependencies when using the `build_usd` script - all dependencies are automatically downloaded/built. Are there any plans to add this feature in, or are there already ways to achieve the behaviour I describe?

Thanks!

**Comment by sunyab** [comment]
Hi @lijenicol, we currently do not have plans to add the ability to use externally-supplied dependencies to build_usd.py. The best way to do so is to configure and run your build via CMake directly.

**Comment by meshula** [comment]
To expand on that a little, if I find myself relying on the build script, but need to skip a step or pin a dependency to a particular version, I modify build_usd.py itself ~ it's a long and detailed script, but straight forward in execution and logically organized. Configuring cmake directly without relyiing on the script to suit your environment, and modifying the build script are two good tools for your toolbox.

**Comment by lijenicol** [comment]
@sunyab @meshula appreciate the fast replies! I guess running through cmake or modifying the build script are two ways I could achieve this (I already have been modifying the build script to do this). It makes me wonder though if it would be beneficial to others to have a concrete way to turn off dependencies though, maybe exposed as an argument - e.g. having `--no-boost` or `--no-OpenEXR` (and then it would be on the user to specify build args to point to external dependencies). On the flipside, I do understand though if this opens up too much complexity and customisability to that script which isn't desired for something that is intended as a quick way to build USD.

**Comment by meshula** [comment]
build_usd.py tries to sit in a sweet spot for onboarding new developers, and for developers that would like to kick the tires on a rather complete build. My personal philosophy, not to speak for the project, is that ideally build system improvements focussing on the cmake scripts offer the most bang for the buck. So, for the examples you give, I'd want to ask if there is something about the way USD finds boost that makes it prickly in your set up, or for eliding OpenEXR, are there improvements in OpenImageIO's build configuration (upstream at the OIIO repo) that would make things easier?

**Comment by lijenicol** [comment]
I reckon that philosophy makes perfect sense. In my environment, USD is not struggling to find my custom build of Boost (after I point it in the right direction using the `build-args` arg). I haven't attempted to build OpenEXR or OIIO myself yet, I have been relying on the `build_usd` script to do it for me. It probably wouldn't be too difficult to manage building all of the dependencies myself and then using CMake as Sunya suggested - in my case I probably should go down that route as my build configuration starts to get more complex.  

Appreciate the help guys, I'll close this one off 😄
