### ISSUE TITLE
Missing refresh after changing NodeGraph attribute value

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#2128]
### Description of Issue

Editing an attribute on a NodeGraph that is connected as source to a shader node will not cause a material sync.

### Steps to Reproduce
1. Load the following USD scene in usdview
2. Programmatically change the value of `/mtl/UsdPreviewSurface1/NodeGraph1.inputs:diffuseColor` to red
3. BUG: The viewport will not refresh

This one is actually a one line fix right here in [usdImaging/delegate.cpp](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usdImaging/usdImaging/delegate.cpp#L1520). The code in `UsdImagingDelegate::_RefreshUsdObject()` that refreshes on changes to UsdShadeShader attributes should also check for changes on UsdShadeNodeGraph attributes.

Scene:
```
#usda 1.0

def Capsule "Capsule1" (
    prepend apiSchemas = ["MaterialBindingAPI"]
)
{
    rel material:binding = </mtl/UsdPreviewSurface1>
}
def Scope "mtl"
{
    def Material "UsdPreviewSurface1" ()
    {
        token outputs:surface.connect = </mtl/UsdPreviewSurface1/NodeGraph1.outputs:surface>
        def NodeGraph "NodeGraph1" ()
        {
            color3f inputs:diffuseColor = (0.872, 0.5327, 0)
            token outputs:surface.connect = </mtl/UsdPreviewSurface1/NodeGraph1/UsdPreviewSurface1.outputs:surface>
            def Shader "UsdPreviewSurface1" ()
            {
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor.connect = </mtl/UsdPreviewSurface1/NodeGraph1.inputs:diffuseColor>
                token outputs:surface
            }
        }
    }
}
```

**Comment by sunyab** [comment]
Filed as internal issue #USD-7824

**Comment by ainaerco** [comment]
I encountered the same issue and found that usdImaging material adapter could be another place for the fix:
https://github.com/PixarAnimationStudios/OpenUSD/blob/v21.05/pxr/usdImaging/usdImaging/materialAdapter.cpp#L98
```
if (child.IsA<UsdShadeShader>()) {
    index->AddDependency(cachePath, child);
}
```
Where we can add NodeGraph as material sprim dependency:
```
if (child.IsA<UsdShadeShader>() || child.IsA<UsdShadeNodeGraph>()) {
    index->AddDependency(cachePath, child);
}
```
I'm wondering why this was unnoticed for so long time, don't studios use nested NodeGraphs with interactive rendering?
