### ISSUE TITLE
USD_STATIC

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#213]
````
AR_STATIC
ARCH_STATIC
CAMERAUTIL_STATIC
GF_STATIC
...
TF_STATIC
USDGEOM_STATIC
... etc.
````

Every module I have in my project that uses USD as a static library, and indeed every module within my static build of USD itself (modulo some modicum of common sense of course) has got to have every other static define mutually defined. When a new module is introduced, I have to touch upwards of a couple dozen projects to add NEWTHING_STATIC everywhere. If I miss even one the consequences are potentially trivial (build broken) to bad (symbols leaked). 

This is the reason we defined OPENEXR_DLL for the several dylibs in OpenEXR *; one define ensures correct linkages across the board.
````
#if defined(OPENEXR_DLL)
    #if defined(IMATH_EXPORTS)
	    #define IMATH_EXPORT __declspec(dllexport)
        #define IMATH_EXPORT_CONST extern __declspec(dllexport)
    #else
	    #define IMATH_EXPORT __declspec(dllimport)
	    #define IMATH_EXPORT_CONST extern __declspec(dllimport)
    #endif
#else
    #define IMATH_EXPORT
    #define IMATH_EXPORT_CONST extern const
#endif
````
* (poorly named, my fault, didn't know about visibility attributes back then!) 

Anyway, on ingesting a USD drop, I am now hacking the headers like this, because I keep getting stung by programmers unfamiliar with USD messing things up (and by forgetting to vet the defines myself on occasion). Consequently, I've set USD_STATIC up across all projects, and I can tell new participants to make sure USD_STATIC is set; that's far more robust than requesting they set the roughly two dozen existing STATIC defines.

I'd like to request considering replacing AR_STATIC, ARCH_STATIC, etc., with USD_STATIC.

Thanks

````
#if defined(USD_STATIC)
#   define PLUG_API
#   define PLUG_API_TEMPLATE_CLASS(...)
#   define PLUG_API_TEMPLATE_STRUCT(...)
#   define PLUG_LOCAL
#else
#   if defined(PLUG_EXPORTS)
#       define PLUG_API ARCH_EXPORT
#       define PLUG_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#       define PLUG_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#   else
#       define PLUG_API ARCH_IMPORT
#       define PLUG_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#       define PLUG_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#   endif
#   define PLUG_LOCAL ARCH_HIDDEN
#endif
````

**Comment by jtran56** [comment]
Filed as internal issue #146471.

**Comment by meshula** [comment]
Thanks!
