### ISSUE TITLE
usdzip duplicates files when the root layer references usdz files

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2134]
### Description of Issue

When using usdzip on a file that references USDZ files, they get duplicated within the resulting usdz file.

An example of the file is here. The attached zip has this plus the usdz files.

The resulting file should be ~29.5MB , but ends up being 59MB due to the duplicated contents.

### Steps to Reproduce
1. `usdzip combined.usdz -a ./combined.usda`

```
#usda 1.0
(
    metersPerUnit = 0.01
    upAxis = "Y"
)

over "guitar" (
    prepend references = @./fender_stratocaster.usdz@
)
{
}


over "gramophone" (
    prepend references = @./gramophone.usdz@
)
{
}
```

2. `usdzip --list combined.usdz`

```
usdzip --list /Users/dhruvgovil/Downloads/combined.usdz
combined.usda
fender_stratocaster.usdz
gramophone.usdz
0/fender_stratocaster.usdz
0/gramophone.usdz
```

### System Information (OS, Hardware)

macOS 13.1 / Intel+M1 macs (repro on both)

### Package Versions

USD 22.8 and 22.11

[Archive 2.zip](https://github.com/PixarAnimationStudios/USD/files/10240148/Archive.2.zip)

**Comment by dgovil** [comment]
This is quite odd,  if you do this, you don’t get the duplicates

```
#usda 1.0
(
    subLayers = [
        @gramophone.usdz@,
    ]
)
```

But if you do this you do get the file twice

```
#usda 1.0
(
    subLayers = [
        @./gramophone.usdz@,
    ]
)
```

**Comment by sunyab** [comment]
Filed as internal issue #USD-7833
