### ISSUE TITLE
Is it possible to communicate with/control a running usdview process?

### ISSUE THREAD

**Issue by ohmaya** [PixarAnimationStudios/USD#2137]
... to let it, for example, Reopen stage.

Thanks.

**Comment by meshula** [comment]
usdview doesn't have anything like that out of the box, so you'd have to add a mechanism.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7836

**Comment by spiffmon** [comment]
I don't think this is something we are likely to add native support for, so in the name of transparency, am going to close it.  But please reopen if you really want to advocate for it!

**Comment by silviapalara** [comment]
It would also be nice if there was a way to be able to pass to usdview a Usd.Stage object.

**Comment by sunyab** [comment]
Closing per earlier comment from @spiffmon
