### ISSUE TITLE
Setting doublesidedness to false for a prim is producing invisible triangle in HdStorm instead of unlit triangle

### ISSUE THREAD

**Issue by lanierd-adsk** [PixarAnimationStudios/USD#2142]
### Description of Issue
In HdStorm, when using a custom scene delegate, there seems to have a problem related to double sided and culling style.
1) My original goal was to get the backfaces rendered with a shadow/black color (no lighting) like this (not using hydra in this short video ) : https://www.screencast.com/t/mTY0gvaUeJ 

For the following videos, I am using a Hydra UsdPreviewSurface material in case that matters.

2) Same scene rendered with Hydra/HdStorm with :
return **true** in a subclass of HdSceneDelegate in bool HdSceneDelegate::GetDoubleSided(const SdfPath& id)
return **HdCullStyleDontCare** in a subclass of HdSceneDelegate in HdCullStyle HdSceneDelegate::GetCullStyle(const SdfPath& id)
Result is : https://www.screencast.com/t/YTr2Aoypc which is correct.

3) Same scene rendered with Hydra/HdStorm with :
return **false** in a subclass of HdSceneDelegate in bool HdSceneDelegate::GetDoubleSided(const SdfPath& id)
return **HdCullStyleDontCare** in a subclass of HdSceneDelegate in HdCullStyle HdSceneDelegate::GetCullStyle(const SdfPath& id)
Result is : https://www.screencast.com/t/D5OVKVofbbc , which, I think, is incorrect. I would expect the same as in 1). 
The backfaces are invisible instead of being ignored by the lighting and rendered with a shadow/black color.

Thank you.

### Steps to Reproduce
1. I am using a custom Hydra scene delegate
2. Create/Load a mesh where you can see the backface of triangles
3. Return false in a subclass of HdSceneDelegate in bool HdSceneDelegate::GetDoubleSided(const SdfPath& id)
4. Render with HdStorm

### System Information (OS, Hardware)
Windows 10

### Package Versions
Release 22.11

### Build Flags
Nothing special to reproduce this problem.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7842

**Comment by tcauchois** [comment]
HdCullStyleDontCare means you leave it up to the renderer to choose a behavior; Storm chooses backface culling (unless double-sided) by default.  I think to fix case 3, you want to return HdCullStyleNothing.  Can you try that and let me know if it fixes your issue?

Thanks!

**Comment by lanierd-adsk** [comment]
@tcauchois : thank you. Yes it works fine when using the combination you mentioned with HdCullStyleNothing.
So I am closing this as I think there is no bug.
Thank you.

**Comment by tcauchois** [comment]
Awesome! :)
