### ISSUE TITLE
NameError: name 'VisualStudio2022OrGreater' is not defined

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#2143]
### Description of Issue

`build_usd.py` has a typo where it tries to call `VisualStudio2022OrGreater()` instead of `IsVisualStudio2022OrGreater()`:

https://github.com/PixarAnimationStudios/USD/blob/6c2df0d9247c130aaf76f17a0882eb893b7b934c/build_scripts/build_usd.py#L710

Introduced here:

https://github.com/PixarAnimationStudios/USD/commit/55aa466b4de5858a8099eefea4993a7b66b1f8c8

### Steps to Reproduce
1. Run `build_usd.py` on windows with latest dev (6c2df0d9247c130aaf76f17a0882eb893b7b934c)

### System Information (OS, Hardware)

Windows

### Package Versions

USD, latest dev (6c2df0d9247c130aaf76f17a0882eb893b7b934c)

**Comment by meshula** [comment]
Thanks for the quick feedback!

**Comment by sunyab** [comment]
Filed as internal issue #USD-7843

**Comment by pmolodo** [comment]
Thanks @meshula for the quick fix!
