### ISSUE TITLE
Need ability to determine which SdfFileFormat plugins support reading, writing, editing

### ISSUE THREAD

**Issue by spiffmon** [PixarAnimationStudios/USD#2147]
### Description of Issue
When integrating USD into any DCC that wants to provide Import, Export, and/or Save functionality, it would be quite helpful for building format selector GUI to be able to determine, of the potentially many FF plugins known to USD, which ones support reading, which writing (by which we mean all-at-once-export), and which support interactive editing.  Otherwise, a user might, for example, select `.mtlx` for export, and have the operation fail mysteriously.

For vendors interested in this, do you have a strong opinion about whether asking the question should load all FF plugins (allowing the query to be answerable by the plugin code itself as part of the SdfFileFormat API), or whether it should be answerable without requiring any plugins to be loaded, requiring the plugin author to add the information to the plugin's  `plugInfo.json` file?

### Steps to Reproduce
1.

**Comment by guidoq** [comment]
I prefer having a way to specify this in the pluginInfo.json since that's where the extensions are registered. Also, this will allow UI widgets to be populated without loading all the plugins. Some of those plugins, if using 3rd party import/export libraries like TechSoft HOOPS, can be pretty big.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7850
