### ISSUE TITLE
Prefer `TfHash` to `boost::hash`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2172]
### Description of Issue

A large number of the non-python boost dependencies in the USD code base are dependencies on `boost/functional/hash`.  `pxr/base/tf` has its own hashing mechanism that has already been successfully integrated across the USD code base.  Switching to it reduces the number of dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by sunyab** [comment]
Filed as internal issue #USD-7883

**Comment by nvmkuruc** [comment]
This is done.

```grep -r boost::hash pxr/``` only returns references to comments about `hash_value` ADL.
