### ISSUE TITLE
`TfRefPtr<TfRefBase>` `expected unqualified-id before ‘)’ token` error when compiling with GCC 12.2.1 and `-std=gnu++20`

### ISSUE THREAD

**Issue by expenses** [PixarAnimationStudios/USD#2183]
### Description of Issue

```cpp
usd/include/pxr/base/tf/refPtr.h:1304:25: error: expected unqualified-id before ‘)’ token
 1304 |     TfRefPtr<TfRefBase>() {
      |                         ^
usd/include/pxr/base/tf/refPtr.h:1311:31: error: expected unqualified-id before ‘)’ token
 1311 |     TfRefPtr<const TfRefBase>() {
      |                               ^
```

### Steps to Reproduce
1. Compile USD on either the release (https://github.com/PixarAnimationStudios/USD/commit/0c7b9a95f155c221ff7df9270a39a52e3b23af8b) or dev (https://github.com/PixarAnimationStudios/USD/commit/59eaff4e29bd54b45c509f38dc294b9fcb7140f0) branch.
2. Try and include `pxr/usd/sdf/layer.h` using `cxx_std_20` as a cmake compile feature

### System Information (OS, Hardware)

- Arch Linux 6.1.7-arch1-1

If this is just a general case of 'USD doesn't compile with C++ 20' the  that's fine, but I wonder how much effort it would take to fix that.

**Comment by expenses** [comment]
I tried just commenting out these lines:
```cpp
/*
template <>
class TfRefPtr<TfRefBase> {
private:
    TfRefPtr<TfRefBase>() {
    }
};
template <>
class TfRefPtr<const TfRefBase> {
private:
    TfRefPtr<const TfRefBase>() {
    }
};
*/
```
and it now works fine on C++20 and C++23! Diff: https://github.com/PixarAnimationStudios/USD/compare/release...expenses:USD:cpp23

I presume these lines are there for a reason (`// Specialization: prevent construction of a TfRefPtr<TfRefBase>.`). Maybe we can use the preprocessor to only compile them for C++17 and below?

**Comment by dubois** [comment]
It looks to me like invalid C++17 that accidentally happens to compile; I suspect the `<TfRefBase>` should be removed from the ctor definition:
```
template<> class TfRefPtr<TfRefBase> {
  TfRefPtr() {}
}
```

**Comment by sunyab** [comment]
Filed as internal issue #USD-7903
