### ISSUE TITLE
Unnecessary sip import in usdviewq

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#22]
in MainWindow.reloadVaryingUI() - 

https://github.com/PixarAnimationStudios/USD/blob/2eb01f5cd4c2dae4e1ef9912ca27a93083bb6ef4/pxr/usdImaging/lib/usdviewq/mainWindow.py#L1283

I believe this can be removed. Thanks!

**Comment by amooty** [comment]
Filed as internal issue #135885.

**Comment by c64kernal** [comment]
Thanks for the report, Aaron!
