### ISSUE TITLE
How i can solve a TBB error on cmake?

### ISSUE THREAD

**Issue by andreagen0r** [PixarAnimationStudios/USD#220]
### Description of Issue
Here is the error in the cmake
https://snag.gy/m457SM.jpg

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TBB (missing: TBB_LIBRARIES tbb) (found version "2017.0")
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindTBB.cmake:212 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:43 (find_package)
  CMakeLists.txt:15 (include)

### Steps to Reproduce
1. Open CMake
2. Choose source code path
3. Choose build path
4. click Configure Button
5. Choose generator = Unix Makefiles
6. Click Done
7. Getting error

### System Information (OS, Hardware)
OSX Sierra 10.12.2
Intel Core i7 6700K
16GB Ram ddr4
VGA Nvidia GTX960

**Comment by sunyab** [comment]
Hi @andreagen0r, where is your TBB installation located? Our cmake system looks in /opt/intel/tbb by default, so it may not be picked up automatically if you've installed it somewhere else.

You can try adding an entry called TBB_ROOT_DIR and set it to where you've installed TBB to get cmake to explicitly check that location. Even if your TBB is already installed in /opt/intel/tbb, I think it's worth trying to set TBB_ROOT_DIR to that location to see if it helps.

Let us know if that works out, thanks!

**Comment by jtran56** [comment]
Filed as internal issue #147450.

**Comment by vivekverma080698** [comment]
I had the same issue I installed libtbb and it worked for me
link is below 
https://www.howtoinstall.co/en/ubuntu/xenial/libtbb-dev
thank you

**Comment by sunyab** [comment]
Closing this old issue out. Since this issue was filed, build_usd.py has become the simplest way to create a USD build and will download and install TBB as needed, which will hopefully help avoid issues like this. Thanks!

**Comment by bipul-mohanto** [comment]
> I had the same issue I installed libtbb and it worked for me link is below https://www.howtoinstall.co/en/ubuntu/xenial/libtbb-dev thank you

I am using Win10, also says `TBB_ROOT_PATH-NOTFOUND`. Is there any similar solution for Win?

**Comment by meshula** [comment]
The advice @sunyab gave about `build_usd.py`, and also, `TBB_ROOT_DIR` applies on WIndows as well. So if you built and installed tbb yourself, then when you invoke cmake, you can add `-DTBB_ROOT_DIR=c:/where/is/my/tbb/root`. If you don't know how to build and install tbb, or some of the other dependencies of USD, using build_usd.py is the recommended way to build usd on Windows.
