### ISSUE TITLE
Prefer `std::reverse_iterator` instead of `boost::reverse_iterator`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2202]
### Description of Issue

`std::reverse_iterator` is already used in several places in the USD code base.  Switching `boost::reverse_iterator` usage to this reduces the number of dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by sunyab** [comment]
Filed as internal issue #USD-7921

**Comment by nvmkuruc** [comment]
Closing as this was fixed in #2333
