### ISSUE TITLE
Prefer explicit deletion of copy constructor and assignment operator to `boost::noncopyable`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2203]
### Description of Issue
There are several usages of `boost::noncopyable` which could be replaced with expicit `Object(const Object& o) = delete;` and `Object& operator=(const Object& o) = delete;` statements. Switching to this would reduce the number of dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by sunyab** [comment]
Filed as internal issue #USD-7922

**Comment by nvmkuruc** [comment]
Closing, as this was addressed last year.
