### ISSUE TITLE
Use STL type_traits instead of boost traits

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2211]
### Description of Issue

C++{11,14} offers type traits that avoid the need to depend on boost.

### Steps to Reproduce

N/A

### System Information (OS, Hardware)

N/A

### Package Versions

N/A

### Build Flags

N/A

**Comment by nvmkuruc** [comment]
I have a fix for most of these (except for `has_left_shift`).

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7941

**Comment by nvmkuruc** [comment]
Closing, as this was addressed in changes made last year.
