### ISSUE TITLE
`TfIdentity` depends on `boost::call_traits` and is unused

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2217]
### Description of Issue
`TfIdentity` introduces a dependency on `boost::call_traits` and is unused in the rest of the `pxr` code base.  Removing it would reduce the number of dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7947
