### ISSUE TITLE
Update version of DoubleConversion used in tf

### ISSUE THREAD

**Issue by anthony-linaro** [PixarAnimationStudios/USD#2218]
### Description of Issue
Version 2 of DoubleConversion (the one currently in the tree within tf here: https://github.com/PixarAnimationStudios/USD/tree/release/pxr/base/tf/pxrDoubleConversion) is *very* old.

Support for MSVC ARM64 targets was added to it 4.5 years ago in 3.1.0 (https://github.com/google/double-conversion/pull/76)

Would be nice to have the new version with support added.

### System Information (OS, Hardware)
Thinkpad X13s w/ Windows 11 Pro 22621 ARM64, and 22621 SDK, MSVC compiler.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7948

**Comment by ilina-linaro** [comment]
@tallytalwar Could we check if there has been any updates on #USD-7948? Thanks!

**Comment by sunyab** [comment]
Hello @ilina-linaro, this task has been assigned internally and is in our queue but there are no updates otherwise. 

Is there a particular reason for wanting this update? Knowing that would provide us some context and help us prioritize the task accordingly.

**Comment by ilina-linaro** [comment]
Thanks @sunyab . We @ Linaro are helping build the Windows on Arm ecosystem of open source projects. One of the projects we are focussed on for our partners is Blender, which uses OpenUSD. Having the support for ARM64 in DoubleConversion will help mainline Blender support for Windows on ARM64.

**Comment by i-lina** [comment]
@sunyab could you help prioritize this ? Thanks!

**Comment by sunyab** [comment]
This is next in the queue for one of our team members, we hope to have this addressed soon. Thanks for your patience!
