### ISSUE TITLE
Update version of RapidJson used in base/js

### ISSUE THREAD

**Issue by anthony-linaro** [PixarAnimationStudios/USD#2219]
### Description of Issue
The version of RapidJSON (the one currently in the tree within tf here: https://github.com/PixarAnimationStudios/USD/tree/release/pxr/base/js/rapidjson) is *very* old.

Support for MSVC ARM64 targets was added to it 5 years ago (https://github.com/Tencent/rapidjson/commit/f91405801f88533c609d95f2fcc2d88811544d35)

Would be nice to have the new version with support added.

### System Information (OS, Hardware)
Thinkpad X13s w/ Windows 11 Pro 22621 ARM64, and 22621 SDK, MSVC compiler.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7949
