### ISSUE TITLE
`testVtCpp` can use `std::unique_ptr` instead of `boost::scoped_ptr`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2222]
### Description of Issue
`testVtCpp` uses `boost::scoped_ptr` which cannot be moved or copied.  A `const std::unique_ptr` could be used to the same effect, reducing the number of dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by sunyab** [comment]
Hey @nvmkuruc, FYI we just checked in a fix for this internally last week and it'll be hitting the dev branch with the next push.

**Comment by nvmkuruc** [comment]
Got it.  Thanks.
