### ISSUE TITLE
`std::unordered_map` can be used instead of `boost::unordered_map` in `layerStackRegistry.cpp`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2226]
### Description of Issue
`std::unordered_map` can be used as a drop in replacement for most of the usage of `boost::unordered_map` in `layerStackRegistry.cpp`.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7954

**Comment by nvmkuruc** [comment]
Closing, as this was addressed by #2227
