### ISSUE TITLE
Replace `boost::iterator_adaptor` usage with fully specified iterator classes

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2228]
### Description of Issue

Most usages of `boost::iterator_adaptor` in pxr can be replaced with fully specified iterator classes.  Addressing this would reduce USD's dependence on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7956

**Comment by nvmkuruc** [comment]
This was addressed by several PRs last year.
