### ISSUE TITLE
`boost::equality_comparable` can be replaced with explicit `operator!=` implementation

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2236]
### Description of Issue
`boost::equality_comparable` adds `operator!=` to any derived class.  Explicit implementation of `operator!=` would remove this dependency on `boost`.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7964

**Comment by nvmkuruc** [comment]
This was addressed by #2701 and #2237
