### ISSUE TITLE
`TF_PP_EAT_PARENS` can be made boost independent and moved to `preprocessorUtilsLite.h`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2240]
### Description of Issue

`TF_PP_EAT_PARENS` only depends on `BOOST_PP_CAT` for which an equivalent `TF_PP_CAT` already exists.  Making this change can reduce dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7968

**Comment by nvmkuruc** [comment]
This was addressed by #2241 and #2532
