### ISSUE TITLE
Some `boost` headers are unused

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2243]
### Description of Issue
The following headers are included but unused in `pxr`.

`boost/preprocessor/arithmetic/add.hpp`
`boost/preprocessor/tuple/eat.hpp`
`boost/preprocessor/seq/push_back.hpp`
`boost/assign.hpp`
`boost/mpl/or.hpp`
`boost/ptr_container/ptr_map.hpp`

Removing them reduces the number of dependencies on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7971

**Comment by nvmkuruc** [comment]
I think we can close this.  Any unused headers are now transitive through `tf/preprocessorUtils.h` and `vt/functions.h`
