### ISSUE TITLE
Fail to run the USD pxr library in AWS lambda containers

### ISSUE THREAD

**Issue by AadiMehta** [PixarAnimationStudios/USD#2245]
### Description of Issue
We are doing complex processing and are trying to run this via AWS lambda through docker containers. Since AWS lambda has restrictions on only /tmp being writable it is giving issues to run. 

Here are the logs for the same.
```
Error: 	Error in 'pxrInternal_v0_22__pxrReserved__::ArFilesystemWritableAsset::Create' at line 44 in file /opt/USD/pxr/usd/ar/filesystemWritableAsset.cpp : 'Could not create directory '/var/tmp/' for asset '/var/tmp/c85277fe-1b35-4656-a5c3-478fdc73a8ad-output.usdc''

Error: 	Error in 'pxrInternal_v0_22__pxrReserved__::Usd_CrateFile::CrateFile::StartPacking' at line 2506 in file /opt/USD/pxr/usd/usd/crateFile.cpp : 'Unable to open /var/tmp/c85277fe-1b35-4656-a5c3-478fdc73a8ad-output.usdc for write'

Error: 	Error in 'pxrInternal_v0_22__pxrReserved__::UsdZipFileWriter::AddFile' at line 931 in file /opt/USD/pxr/usd/usd/zipFile.cpp : 'Failed to map '/var/tmp/c85277fe-1b35-4656-a5c3-478fdc73a8ad-output.usdc': No such file or directory'
```

### Steps to Reproduce
1. I believe this is the line that is causing issues. https://github.com/PixarAnimationStudios/USD/blob/5c5ebddff35012461a2b0ba773c47f05730cbab4/pxr/base/arch/fileSystem.cpp#L756

### System Information (OS, Hardware)
AWS Lambda using ubuntu linux distro

### Package Versions
USD version: 22.05

**Comment by sunyab** [comment]
I believe USD will use the value of the TMPDIR environment variable as the temporary directory if it's set before falling back to /var/tmp. Can you set that env var to `/tmp` before running your process?

https://github.com/PixarAnimationStudios/USD/blob/5c5ebddff35012461a2b0ba773c47f05730cbab4/pxr/base/arch/fileSystem.cpp#L749

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7978

**Comment by AadiMehta** [comment]
> I believe USD will use the value of the TMPDIR environment variable as the temporary directory if it's set before falling back to /var/tmp. Can you set that env var to `/tmp` before running your process?
> 
> https://github.com/PixarAnimationStudios/USD/blob/5c5ebddff35012461a2b0ba773c47f05730cbab4/pxr/base/arch/fileSystem.cpp#L749

Thank you for quick answer. I have added the TMPDIR environment to my dockerfile and resolved this issue.

**Comment by spiffmon** [comment]
That's great, @AadiMehta .  Given that AWS is not a build architecture, it might be tricky trying to guess what its preferred tmp dir might be inside our code, and that's why we provide the env var.
