### ISSUE TITLE
`TF_PP_CAT` can be used to make some files not depend on `boost/preprocessor`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2247]
### Description of Issue

`pxr/usd/pcp/diagnostic.h` and `pxr/base/tf/pyModule.h` bring in the `boost/preprocessor` library solely for `BOOST_PP_CAT`.

Using `TF_PP_CAT` in these cases reduces the dependencies on `boost/preprocessor`.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7981

**Comment by nvmkuruc** [comment]
This was addressed by #2645 and #2249
