### ISSUE TITLE
build_scripts/build_usd.py build Fail

### ISSUE THREAD

**Issue by Chadt54** [PixarAnimationStudios/USD#225]
### Description of Issue
When building the "dev" branch using the python build script, it fails at the OpenImageIO section.

### Steps to Reproduce
1. Open Visual Studio 2015 developer cmd, and run "python <build_scripts/build_usd.py> <build_dir>", and it will fail.

### System Information (OS, Hardware)
Windows 10 64-bit, Visual Studio 2015 

### Package Versions
usd - dev branch v0.7.5

### Build Flags
No special build flags

-------------------------------- The Build Error ---------------------------------------
https://pastebin.com/KhuZP5dp

**Comment by sunyab** [comment]
Could you post the log.txt and CMakeCache.txt from D:\Scripts\USD\USD-master\build\build\oiio-Release-1.7.14\?

I'm wondering if the OpenImageIO build is picking up an old or unexpected version of Ptex from somewhere on your system. For instance, Maya ships with a Ptex library that is incompatible with newer versions of OpenImageIO; if Maya happens to be in your %PATH%, the OpenImageIO build might be picking it up through that. If that's the case, you might try temporarily removing Maya from your %PATH% and running the build again.

As another workaround, you could modify the build_usd.py script and add '-DUSE_PTEX=OFF' to the call to RunCMake in InstallOpenImageIO.

**Comment by Chadt54** [comment]
Here's the requested files, these generated files are before I make an attempt at changing the build_usd.py file. (I'll make the modification and try again right after this post)

[debug_attch.zip](https://github.com/PixarAnimationStudios/USD/files/1086975/debug_attch.zip)

**Comment by Chadt54** [comment]
Adding '-DUSE_PTEX=OFF' seems to have solved the issue. The project now builds successfully.


Although, I need to build with Maya and Alembic, so I will try that next.

**Comment by Chadt54** [comment]
After building, usdview is missing.

I check in the "D:\Scripts\USD\USD-master\build\bin" folder and can see usdcheck.cmd, usddiff.cmd, etc. but not usdview.cmd or usdview

**Comment by meshula** [comment]
if you run python, and try

```
import PySide
```
does it complain, or succeed? Usually if usdview doesn't build it's because Qt isn't in the environment.

**Comment by Chadt54** [comment]
`import PySide`

Works ok

**Comment by Chadt54** [comment]
Just tried recompiling making sure "C:\Qt\4.8.6\bin" was in the window's PATH. Rebuilt, but still no usdview.

**Comment by Chadt54** [comment]
Figured it out, pyside-uic wasn't being found. Added it to PATH and then usdview built properly.

Thanks for the help!

**Comment by sunyab** [comment]
Glad you're up and running! Regarding your earlier Ptex issues, from looking at your CMakeCache.txt the OpenImageIO build was picking up Ptex from C:\Program Files\ptex, so it's possible there's an issue with the version you have installed there, or it just might be an older version that OpenImageIO doesn't support.

Based on this, I think there's a couple of things the script can do better:
- If Ptex support is turned when running the script (which is the default), we should tell OpenImageIO to disable Ptex as well. This gives us better isolation from libraries that may be hanging around elsewhere on someone's system.

- The script should check for pyside-uic and issue an error if it can't find it.

Thanks for the feedback!

**Comment by jtran56** [comment]
Filed as internal issue #147817.
