### ISSUE TITLE
`boost::totally_ordered` can be replaced with explicit operator overloads

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2250]
### Description of Issue

`boost::totally_ordered` adds `operator!=`, `operator>`, `operator<=`, and `operator>=` to any derived class.  Explicit implementation of these operators would remove this dependency on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7984

**Comment by nvmkuruc** [comment]
This was addressed by several PRs last year.
