### ISSUE TITLE
usdview: Error with Color Management when choosing displays

### ISSUE THREAD

**Issue by mdecaria** [PixarAnimationStudios/USD#2254]
### Description of Issue
When using usdview if a Display space is chosen with the new OCIO Config menu, it fails to switch and a python traceback error appears

### Steps to Reproduce
1.  Ensure OCIO environment is set to a config that contains Displays
2.  Open USDView and switch Color Management to OCIO
3. Choose one of the displays listed up the Displays section.
4.  See following traceback in terminal:
```
Traceback (most recent call last):
  File "/path/to/usd/usdView/23.02/lib/python/pxr/Usdviewq/appController.py", line 1752, in setOcioConfig
    if config.hasattr('getDisplayViewColorSpaceName'):
AttributeError: 'PyOpenColorIO.Config' object has no attribute 'hasattr'
```

`hasattr` is a python built-in - I would expect the line to be `if hasattr(config, "getDisplayViewColorSpaceName"):`
### Package Versions
23.02

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7988
