### ISSUE TITLE
Storm: Rendering issues on OpenChessSet MaterialX test asset.

### ISSUE THREAD

**Issue by creijon** [PixarAnimationStudios/USD#2255]
### Description of Issue

With the MaterialX Chess Set test scene:

https://github.com/usd-wg/assets/tree/main/full_assets/OpenChessSet

The board flickers with what appears to be z-fighting when rendering with the Hydra Storm delegate.

Normal maps also appear to be reverse, see the attached image.  The sun reflection is coming from 180º out.

It could be an issue with the asset itself, but this does not happen with other renderers.

Tested on Linux with latest dev at 1d2f18b540079dececa879c8515ccaac5c4161c6

### Steps to Reproduce
1. Download OpenChessSet from link above.
2. Build USD with MaterialX enabled.
3. Load in USDview with Hydra Storm renderer
4. Orbit camera and observe flickering on the chess board.

### System Information (OS, Hardware)

Ubuntu Linux 20.04.S LTS
RazerBlade 15 with GTX 2060

### Build Flags

--materialx

![Chessboard2](https://user-images.githubusercontent.com/65668160/217541934-95a2d5f1-b3b9-40d9-89df-a8f3fec40a51.png)

![Chessboard1](https://user-images.githubusercontent.com/65668160/217543629-a0515870-f724-42fc-9714-607f516e3147.png)

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7989

**Comment by creijon** [comment]
From @pablode:

Hey, unfortunately I don't have time right now to debug this further, but I believe that the normal map may be interpreted as sRGB because image colorspaces are not translated from Hydra to MaterialX. There are two open issues:

https://github.com/PixarAnimationStudios/USD/issues/1523
https://github.com/PixarAnimationStudios/USD/issues/1878

Afaik it should render fine in Karma because there only <image>s of type color3 are sRGB-decoded, and <image>s of type vector3 (which are used for normal maps) are not.

**Comment by pablode** [comment]
Perhaps worth noting: in the MaterialX backend, the [normal map node](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/libraries/stdlib/genglsl/mx_normalmap.glsl) performs the normal perturbation based on the tangent: https://github.com/PixarAnimationStudios/USD/blob/5c5ebddff35012461a2b0ba773c47f05730cbab4/pxr/imaging/hdSt/materialXShaderGen.cpp#L66-L71

Which, I believe, does not respect the orientation of the surface (it is not aligned to the UV space). However, for preview surfaces, a sophisticated algorithm is employed:
https://github.com/PixarAnimationStudios/USD/blob/5c5ebddff35012461a2b0ba773c47f05730cbab4/pxr/usdImaging/plugin/usdShaders/shaders/previewSurface.glslfx#L460-L505

**Comment by creijon** [comment]
Now fixed.
