### ISSUE TITLE
`boost::compressed_pair` can be replaced with explicit empty base optimization

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2257]
### Description of Issue

`boost::compressed_pair` is being leveraged in `TfDense{Map,Set}` to take advantage of the empty base optimization for the Hashing and Equality types.  This can be done explicitly with private inheritance on the containers.

Longer term, the `[[no_unique_address]]` attribute should be considered when `C++20` is an option.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7991

**Comment by nvmkuruc** [comment]
This was addressed by #2522 and #2257
