### ISSUE TITLE
UsdCollectionAPI explicitOnly includeRoot rendering error

### ISSUE THREAD

**Issue by miguelh-nvidia** [PixarAnimationStudios/USD#2258]
### UsdCollectionAPI explicitOnly includeRoot logs error

Hi!,
We run into an unexpected warning, I can easily reproduce doing the following in Interpreter in `usdview`. 

```python
UsdLux.SphereLight.Define(usdviewApi.stage, "/hello/light")
light = usdviewApi.stage.GetPrimAtPath("/hello/light")
collection = Usd.CollectionAPI.Get(light, "lightLink")
collection.GetExpansionRuleAttr().Set(Usd.Tokens.explicitOnly)
```

Will produce:
```text
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_20__pxrReserved__::`anonymous-namespace'::_ComputeIncludedImpl' at line 142 in file C:\sources\usd-build\USD\pxr\usd\usd\collectionMembershipQuery.cpp : 'Unknown path type in membership-map.'
        Error in 'pxrInternal_v0_20__pxrReserved__::`anonymous-namespace'::_ComputeIncludedImpl' at line 142 in file C:\sources\usd-build\USD\pxr\usd\usd\collectionMembershipQuery.cpp : 'Unknown path type in membership-map.'
        Error in 'pxrInternal_v0_20__pxrReserved__::`anonymous-namespace'::_ComputeIncludedImpl' at line 142 in file C:\sources\usd-build\USD\pxr\usd\usd\collectionMembershipQuery.cpp : 'Unknown path type in membership-map.'
```

What seems to happen is when creating this light (or any collection), includeRoot will be True, and expansionRule will be expandPrims. If we change expansionRule to explicitOnly (while keeping includeRoot, True), it throws that message.

Looking at the code here: https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/usd/collectionMembershipQuery.cpp#L110, there seems to be missing a case for when `IsAbsoluteRootPath` is true. Is that the case? or am I missing something else?

Further discussion: https://groups.google.com/g/usd-interest/c/nNppu_TcT6c

### Steps to Reproduce
1. Open `usdview`
2. Make sure the Demo is there (i.e. blue ball)
3. Open script editor, copy paste this:
```python
UsdLux.SphereLight.Define(usdviewApi.stage, "/hello/light")
light = usdviewApi.stage.GetPrimAtPath("/hello/light")
collection = Usd.CollectionAPI.Get(light, "lightLink")
collection.GetExpansionRuleAttr().Set(Usd.Tokens.explicitOnly)
```
5. Console errors will appear:
```text
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_20__pxrReserved__::`anonymous-namespace'::_ComputeIncludedImpl' at line 142 in file C:\sources\usd-build\USD\pxr\usd\usd\collectionMembershipQuery.cpp : 'Unknown path type in membership-map.'
        Error in 'pxrInternal_v0_20__pxrReserved__::`anonymous-namespace'::_ComputeIncludedImpl' at line 142 in file C:\sources\usd-build\USD\pxr\usd\usd\collectionMembershipQuery.cpp : 'Unknown path type in membership-map.'
        Error in 'pxrInternal_v0_20__pxrReserved__::`anonymous-namespace'::_ComputeIncludedImpl' at line 142 in file C:\sources\usd-build\USD\pxr\usd\usd\collectionMembershipQuery.cpp : 'Unknown path type in membership-map.'
```

### System Information (OS, Hardware)

- Windows x86, Linux x86 (Ubuntu)

### Package Versions

- Appears in 20 and 22.11, but looking at the code (https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usd/usd/collectionMembershipQuery.cpp#L110) the missing condition is still there.

### Build Flags

- NA

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7992

**Comment by blevin** [comment]
Hi Miguel.  Your steps mention "Make sure the Demo is there (i.e. blue ball)" -- do you have a particular USD file meant to be used here?  Thanks.

**Comment by blevin** [comment]
Here is a repro that does not require a starting USD file or usdview:
```
from pixar import Usd, UsdLux
stage = Usd.Stage.CreateInMemory()
UsdLux.SphereLight.Define(stage, "/hello/light")
light = stage.GetPrimAtPath("/hello/light")
collection = Usd.CollectionAPI.Get(light, "lightLink")
collection.GetExpansionRuleAttr().Set(Usd.Tokens.explicitOnly)
query = collection.ComputeMembershipQuery()
paths = Usd.ComputeIncludedPathsFromCollection(query, stage)
print(paths)
```
