### ISSUE TITLE
`boost::begin` and `boost::end` can be replaced with `std::begin` and `std::end`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2260]
### Description of Issue

The `begin` and `end` functions are generic ways to construct iterators on ranges which may or not have expliclit `.begin` or `.end` methods.  The STL introduced these with C++11 and can replace the boost versions.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7994

**Comment by nvmkuruc** [comment]
This was addressed by another change last year and can be closed.

```
grep -r "boost::begin" pxr/
grep -r "boost::end" pxr/
```
