### ISSUE TITLE
UsdMtlxSplitStringArray Parses Spaces Incorrectly

### ISSUE THREAD

**Issue by feldstj** [PixarAnimationStudios/USD#2268]
### Description of Issue

UsdMtlxSplitStringArray splits strings currently based on commas and spaces. Certain enums such as ND_lama_sss's sssMode assume that the spaces in the enum labels will not be used to split the enum labels. The fix is to only split on commas and to remove leading and trailing whitespace from the results.

### Steps to Reproduce
```
from pxr import Sdr
r = Sdr.Registry()
n = r.GetShaderNodeByIdentifier("ND_lama_sss")
t = n.GetShaderInput("sssMode")
print(t.GetOptions())

Result: [('Path-traced', ''), ('Davis', ''), ('Path-traced', ''), ('exponential', ''), ('Diffusion', ''), ('Burley', ''), ('Diffusion', ''), ('Burley', ''), ('(mean', ''), ('free', ''), ('path)', '')]
```

`Expected: [('Path-traced Davis', '0'), ('Path-traced exponential', '1'), ('Diffusion Burley', '2'), ('Diffusion Burley (mean free path)', '3')] 
`

### Build Flags
Enable MaterialX.

**Comment by feldstj** [comment]
#USD-42

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8006
