### ISSUE TITLE
`boost::transform_iterator` can be replaced

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2272]
### Description of Issue
There are currently two usages of `boost::transform_iterator` in USD.

In `UsdProperty`, it's used as the input to `SdfPathFindLongestPrefix`.  However, `SdfPathFindLongestPrefix` also takes a function argument that is applied to the iterator. This argument can be used in `transform_iterator`'s stead.

In `stage.cpp`, it's used twice.  In `_Stringify`, an intermediate `SdfPathVector` is currently already created and so `std::transform` can be used without additional overhead. The other usage transforms the inputs for usage in a private internal helper function.  However, the helper function is only used once in the file so the contract can be easily modified and the transformation moved inside of the helper.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8010

**Comment by nvmkuruc** [comment]
This was addressed last year and can be closed.
