### ISSUE TITLE
`boost::iterator_range` can be replaced with explicit range types

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2276]
### Description of Issue
`boost::iterator_range` is used in `prim.h` and `primData.h`.

The typedefs, functions, and methods which use in `primData.h` are all private, unused, and be removed.

`UsdPrim{SiblingRange,SubtreeRange}` already have a skeleton interface for doxygen. Fleshing this out will allow for the removal of `iterator_range` as a core dependency.

This issue addresses usage in the core only and does not address the usage in `examples`.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8014

**Comment by nvmkuruc** [comment]
Closing as this was addressed last year.
