### ISSUE TITLE
Adding a reference to an animation primitive results in the saved usda saving the entire model hierarchy instead of just a one-line text reference.

### ISSUE THREAD

**Issue by digitalmonkey** [PixarAnimationStudios/USD#2279]
### Steps to Reproduce
1.  When I call:
     motionPrim.GetReferences().AddReference(modelPath)
     
     on my animation primitive with a model, the entire model is included in my saved usda. Instead I only wish to have a one
     line reference like:
 
    def "osim_motion_Group" (
    prepend apiSchemas = ["SkelBindingAPI"]
    prepend references = @./LaiArnoldModified2017_poly_withArms_weldHand_scaled_adjusted.usda@
   )

I'm using the Python API. How can I prevent the entire model being included and only have the simple reference to the usda file in the prepend references?

**Comment by sunyab** [comment]
Hi @digitalmonkey, how are you saving your .usda file? If you are calling Usd.Stage.Export, try using Usd.Stage.Save instead. Export will save a single .usda with the "flattened" contents of the stage, which will include the entire model. Calling Save will save each layer in the stage individually and maintain the reference statement as in your example.

**Comment by digitalmonkey** [comment]
Thank you! That was it! Changing to save instead of export fixed things for me.

**Comment by sunyab** [comment]
Great, glad that helped! Closing this out.
