### ISSUE TITLE
Hang in testUsdThreadedAuthoring with 23.02 on Windows

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#2282]
### Description of Issue

We're seeing semi-frequent hangs of `testUsdThreadedAuthoring` with 23.02 windows builds.

I'm attaching a minidump, and printout of the call stacks for all the threads, and a summary of where all the threads are blocking.

[testUsdThreadedAuthoring.noHeap.dmp.zip](https://github.com/PixarAnimationStudios/USD/files/10753107/testUsdThreadedAuthoring.noHeap.dmp.zip)
[testUsdThreadedAuthoring.threadCallStacks.txt](https://github.com/PixarAnimationStudios/USD/files/10753086/testUsdThreadedAuthoring.threadCallStacks.txt)
[testUsdThreadedAuthoring.threadCallStacks.summary.txt](https://github.com/PixarAnimationStudios/USD/files/10753085/testUsdThreadedAuthoring.threadCallStacks.summary.txt)

It looks like there’s an issue with the `TfBigRWMutex` on the `Tf_TypeRegistry` - it hangs trying to get a write lock, in `_WaitForReaders`.  I could see in the debugger that on the `TfBigRWMutex` , `_states[2].mutex._lockState == 3`, which meant it had already acquired the write lock, but there was one read lock that wouldn’t free.  No other threads had a read lock that I could see, though - so I'm not precisely sure what's going on.

### Steps to Reproduce
1. Build v23.02 on windows
2. Keep running `testUsdThreadedAuthoring` until it hangs.

### System Information (OS, Hardware)
Windows

### Package Versions
v23.02 (tagged release)

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8020
