### ISSUE TITLE
Build script errors out without useful message if Boost fails to download

### ISSUE THREAD

**Issue by d3fc0n1** [PixarAnimationStudios/USD#2283]
### Description of Issue
If boost fails to install, the build script returns a less than useful error message because ```BOOST_VERSION_FILE``` isn't defined but referenced in the except block.

https://github.com/PixarAnimationStudios/USD/blob/release/build_scripts/build_usd.py#L885

### Steps to Reproduce
1. Disable outgoing connections so curl fails to download dependencies
2. run ```build_scripts/build_usd.py```

### System Information (OS, Hardware)
Ubuntu 20.04

### Package Versions
v23.02 (tagged release)

**Comment by robpieke** [comment]
I think this was introduced with https://github.com/PixarAnimationStudios/USD/commit/59eaff4e29bd54b45c509f38dc294b9fcb7140f0

**Comment by meshula** [comment]
Thanks for the report, that was me :anime-sweat-drop-face: !

**Comment by tallytalwar** [comment]
Thanks a fix for the same was just pushed to the dev branch. https://github.com/PixarAnimationStudios/USD/commit/fbc55dfa2ecce35afa840607ec2dcafc16b14bbd
