### ISSUE TITLE
`boost::in_place` can be replaced by `emplace` methods

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2290]
### Description of Issue

`TfType` and `UsdStage` use `boost::in_place` to initialize `boost::optional` instances.  The STL has introduced `emplace` as the standard way to do `in_place` initialization. As recent versions of `boost::optional` support `emplace`, `boost::in_place` usage can be removed. Doing so will make it easier to swap out `boost::optional` for `std::optional` in the future and removes another boost dependency.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8027
