### ISSUE TITLE
`pxr/usd/usd/crateFile.{h,cpp}` can use `robin_map` instead of `boost::container::flat_map`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2296]
### Description of Issue

`CrateFile` uses `boost::flat_map` to record a registry of type specific functions and a time code ordered list of values.

The first usage does not rely on the order of `boost::flat_map` and be replaced directly with `robin_map`.

The second usage requires an addition sort of the keys / iterators after the map has been populated.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8037

**Comment by nvmkuruc** [comment]
This was addressed by #2297 and can be closed.
