### ISSUE TITLE
usdview executable not built when using build_scripts/build_usd.py on Mac OS

### ISSUE THREAD

**Issue by CreateTheImaginable** [PixarAnimationStudios/USD#230]
### Description of Issue

When building the "dev" branch using the python build script build_usd.py, the executable usdview is not built on MacOS

### Steps to Reproduce

1. Install Pyside using https://www.macports.org as the build script recommends ( port install py27-pyside-tools ).

2. git clone https://github.com/PixarAnimationStudios/USD
3. cd USD
4. git checkout dev
5. cd ..
6. python USD/build_scripts/build_usd.py -v $HOME/Projects/Pixar/BUILD/USD

When the build completes successfully, usdview is not built and also usdview does not exist in the bin directory with the other tools ( i.e. usdcat, usddiff, usdedit, etc )

### System Information (OS, Hardware)

MacOS 10.12.5 using Xcode 8.3.3, Mac Pro ( 2013 )

### Package Versions

usd - dev branch v0.7.5

### Build Flags

No special build flags

**Comment by sunyab** [comment]
I think this is similar to issue #225 -- is pyside-uic (or pyside-uic-2.7) available in your PATH? Installing Pyside via MacPorts should put pyside-uic-2.7 in /opt/local/bin by default, so adding that to your PATH should get usdview building.

**Comment by jtran56** [comment]
Filed as internal issue #147963.

**Comment by CreateTheImaginable** [comment]
@sunyab thanks for your work on this build script - /opt/local/bin/pyside-uic-2.7 is in my path and looks like the build script is finding it, I am getting another error...

**I turned on verbose level 3 -v -v -v and I get the following...**

**-- Found PySide: with /opt/local/bin/python2.7, will use /opt/local/bin/pyside-uic-2.7 for pyside-uic binary**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named OpenGL
-- C++ namespace configured to (external) pxr, (internal) pxrInternal_v0_7
-- Skipping validation of gf generated code because PXR_VALIDATE_GENERATED_CODE=OFF
-- Skipping validation of sdf generated code because PXR_VALIDATE_GENERATED_CODE=OFF
CMake Warning at pxr/usd/lib/usd/CMakeLists.txt:126 (message):
  Skipping building usdGenSchema due to missing dependency: Jinja2

-- Skipping alembic-based usddiff tests because PXR_BUILD_ALEMBIC_PLUGIN=OFF
CMake Warning at pxr/usdImaging/lib/usdviewq/CMakeLists.txt:8 (message):
   **Not building usdviewq because of missing dependency: PyOpenGL**

CMake Warning at pxr/usdImaging/bin/usdview/CMakeLists.txt:5 (message):
   **Not building usdview because of missing dependency: usdviewq**

**Earlier in the build output I get this for OpenGL...**

STATUS: Installing PyOpenGL...
STATUS: Installing PyOpenGL...
INFO: Running "pip install PyOpenGL"
Requirement already satisfied: PyOpenGL in /Library/Python/2.7/site-packages
STATUS: Installing USD...

**Comment by meshula** [comment]
/opt/local/bin/python2.7 is a MacPorts build of Python, and /Library/Python/2.7/ is for the os supplied system python. cmake is trying to cross-wire them together.

@sunyab The reason I used homebrew to install PySide was that it uses system Python. I'm not sure if MacPorts also has a way to prefer system python? Having two pythons in the path can be a bit spooky.

**Comment by CreateTheImaginable** [comment]
@sunyab @meshula - Yes there are two pythons...

/usr/bin/python2.7 Apple's python
/opt/local/bin/python installed by MacPorts

**MacPorts also creates a .profile file to put its python first in the system PATH**

```
# MacPorts Installer addition on 2017-06-22_at_02:51:22: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
```

**So to successfully run the build_usd.py script I need to use:**

/usr/bin/python2.7 USD/build_scripts/build_usd.py -v -v -v $HOME/Projects/Pixar/BUILD/USD

**If I try to use MacPorts /opt/local/bin/python which is now first in the system path to run the build_usd.py script I get an SSL error when downloading the zlib dependency**

python USD/build_scripts/build_usd.py -v -v -v $HOME/Projects/Pixar/BUILD/USD

STATUS: Installing zlib...
INFO: Downloading https://github.com/madler/zlib/archive/v1.2.11.zip to /Users/wilhoitm/Projects/Pixar/BUILD/USD/src/v1.2.11.zip
ERROR: Failed to download https://github.com/madler/zlib/archive/v1.2.11.zip: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

**Comment by meshula** [comment]
Googling

    urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

suggests this happens to people using macports from time to time. Sorry I haven't got anything more useful than that.

**Comment by sunyab** [comment]
@CreateTheImaginable - sorry you're running into these issues! Do you get the urlopen error if you rerun the build script using MacPorts' python? I've seen SSL errors from urlopen before, but they seem to be something server side and usually go away if I run the script again. If that's the case, I need to make the script more resilient to those errors.

From your earlier post, my guess is that the build script used system python/pip to install PyOpenGL but then used MacPorts' python to build USD, which couldn't find PyOpenGL in its site-packages. I think if pip was installed from MacPorts as well well via:

```
port install py27-pip
port select --set pip pip27
```

the build script would do the right thing -- it would find MacPorts' pip via $PATH and use it to install PyOpenGL in MacPorts' site-packages. 

Ideally, the build script should at least warn users about this problem, though I'm not 100% sure how to go about that yet.

@meshula - I don't think MacPorts has an option to use system python -- it seems like it wants to create its own isolated area for packages and dependencies. I had thought brew didn't support installing PySide on MacOS Sierra without some patches to the Qt source code, which we're not at liberty to do -- that's why the script asks users to use MacPorts instead. In theory, we should be able to change that when we're able to move usdview to PySide2/Qt5.

**Comment by sunyab** [comment]
Scratch my question about the urlopen SSL errors with MacPorts, I can reproduce those locally and they're different from what I had run into before. I see a bunch of pages about needing to install curl-ca-bundle from MacPorts for other SSL issues, and I wonder if that would help.

**Comment by meshula** [comment]
@sunyab - the brew version of PyQt definitely doesn't work out of the box as you note.

I've been using cartr's patched version, which gets installed such that system Python can see it. I'm careful not to let brew spider in any other dependencies though.

````
brew install cartr/qt4/qt
brew install cartr/qt4/pyside
brew install cartr/qt4/pyside-tools
````

**Comment by CreateTheImaginable** [comment]
**@sunyab @meshula - That worked like a charm!   I now have usdview running on MacOS!**  

I uninstalled MacPorts using these instructions - https://guide.macports.org/chunked/installing.macports.uninstalling.html

** Did the git set up**

mkdir Projects
git clone https://github.com/PixarAnimationStudios/USD
cd USD
git checkout dev
cd ..

**I then  did brew install of qt4 & pyside**

brew install cartr/qt4/qt
brew install cartr/qt4/pyside
brew install cartr/qt4/pyside-tools

**Set my PYTHONPATH environment variable**

export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages

**Ran the build_usd.py build script**

python USD/build_scripts/build_usd.py -v -v -v $HOME/Projects/Pixar/BUILD/USD

**And it works!   :-)**

usdview ./USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda

**Comment by meshula** [comment]
@CreateTheImaginable  I've documented the homebrew variant on the build-club wiki, thanks for posting your steps. https://github.com/vfxpro99/usd-build-club/wiki/USD-on-macOS

**Comment by PixelPartner** [comment]
I followed @CreateTheImaginable steps in @meshula repo for macOS, but at the end usdview can be launched, but fails with `ImportError: No module named pxr.Usdviewq`.
Where do I have to install the optional python package(s) and where to get them?

**Comment by carmandale** [comment]
I get this error when I try to build...

Traceback (most recent call last):
  File "USD/build_scripts/build_usd.py", line 1674, in <module>
    import maya
ImportError: No module named maya
ERROR: CMake not found -- please install it and adjust your PATH

I don't use Maya. Can I do the build without it?

thanks,
Dale

**Comment by johndpope** [comment]
@carmandale  brew install cmake
