### ISSUE TITLE
Storm renders joints as geometry

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2300]
### Description of Issue

Storm seems to render joints in a UsdSkelSeleton as geometry.
This seems like it should not be the default behaviour, as most users would probably expect joints to be invisible or a guide by default. Otherwise, the default view makes reviewing animation of assets more difficult, especially if the joints extend outside of the character geometry itself.

DCC's like Maya export skeletons without defining a display purpose, so all exports end up showing joints in Storm. 

Perhaps it would be better if UsdSkel defaulted to the `guide` purpose instead for skeletons, at the schema/usd level? I can imagine some people do want to see the joints, but I don't think the default should have them render at the same priority as geometry. 

I think changing the default render purpose for a skeleton would make it easier for adopters of USD (both artists and developers) to not have to special case their handling of joints, while still providing the flexibility to allow people who want to see the joints to see them by turning on guide geometry.

### Steps to Reproduce
1. Open the attached USD file in usdview
2. The only geometry in the file is the cube, yet Storm renders the joints as well

### System Information (OS, Hardware)

Tested on macOS 13.2 and Linux 

### Package Versions

USD 23.2 and prior versions

<img width="620" alt="image" src="https://user-images.githubusercontent.com/4443090/220176441-3a4e236f-1caa-4405-9a66-85eb51398de6.png">
[skelTest.usdc.zip](https://github.com/PixarAnimationStudios/USD/files/10786973/skelTest.usdc.zip)

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8041
