### ISSUE TITLE
Add documentation for `NO_GLFW` flag to CMake config docs

### ISSUE THREAD

**Issue by virtualritz** [PixarAnimationStudios/USD#2302]
The [CMake config docs](https://graphics.pixar.com/opensubdiv/docs/cmake_build.html#step-2-configuring-cmake) miss listing the `NO_GLFW` which e.g. can help with #261.

**Comment by sunyab** [comment]
Could you please file this issue on the OpenSubdiv repo at https://github.com/PixarAnimationStudios/OpenSubdiv? This is an issue specific to the OpenSubdiv build, USD does not have a NO_GLFW flag itself. Thanks!
