### ISSUE TITLE
Replace `boost::iterator_facade` usage with fully specified iterator classes

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2305]
### Description of Issue

Most usages of `boost::iterator_facade` in pxr can be replaced with fully specified iterator classes. Addressing this would reduce USD's dependence on boost.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8045

**Comment by nvmkuruc** [comment]
This was addressed by several PRs last year.
