### ISSUE TITLE
Replace `boost::filter_iterator` usage with fully specified iterator class

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2311]
### Description of Issue

`pxr/usd/sdf/childrenView.h` uses `boost::filter_iterator` to apply a filtering predicate to another iterator. This can be explicitly specified to remove another boost dependency.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8055

**Comment by nvmkuruc** [comment]
Closing, as #2312 addressed this.
