### ISSUE TITLE
Error when building - installing boost

### ISSUE THREAD

**Issue by thomasjaggard** [PixarAnimationStudios/USD#2316]
Hi when trying to run the script (just running from C:\USD and installing to C:\USD\Program Files), when it gets to the stage of installing boost I get the following - 

```
Building Boost.Build engine
=C:\Program was unexpected at this time.

ERROR: Failed to run 'bootstrap.bat --prefix="C:\Program Files\USD"'
See C:\Program Files\USD\src\boost_1_70_0\log.txt for more details.
```

If I execute bootstrap.bat on it's own it works fine.

This is running under win10, with VS2019 installed, and NASM, CMake and Python installed.

**Comment by meshula** [comment]
Could you try installing to a path that does not include spaces? That would provide a useful clue.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8062

**Comment by thomasjaggard** [comment]
I've gotten around this by using the Nvidia prebuilt libraries.
