### ISSUE TITLE
Preprocessor usage can be reduced in pxr/base/tf

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2318]
### Description of Issue

Both `pxr/base/tf/enum.h` and `pxr/base/tf/scopeDescription.h` provide macros which use the boost preprocessor.

The `enum.h` usage can be removed in favor of always passing a string since the default argument is an empty string.
The `scopeDescription.h` usage can be removed in favor of variadic templates.  Specific forwarding overloads can be provided to avoid unnecessarily creating new strings if no formatting is needed.

### Steps to Reproduce
N/A

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by nvmkuruc** [comment]
I have a fix.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8066

**Comment by nvmkuruc** [comment]
This was addressed by #2320.  Closing.
