### ISSUE TITLE
MaterialX: Storm fails to reuse GLSL shaders for networks differing only on node names

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#2330]
### Description of Issue

The function `HdSt_MaterialNetworkShader::CanAggregate()` will compare the hash of the GLSL shader text to know if it can aggregate two material networks.

MaterialX will use the node names when generating a uniform variable name when there are connected ancillary nodes. If these node names vary, the hash will differ and the merging will fail.

### Steps to Reproduce
1. Load attached scene in USDView [goldRamp.zip](https://github.com/PixarAnimationStudios/USD/files/10961755/goldRamp.zip)
[BUG] compiles 11 GLSL shaders where only one would be needed

The scene was designed to show the issue by having a `ND_dot_float` with a varying name connected in exactly the same way on each surface.

### Potential fix

One option would be to anonymize the node names in the network so they follow a consistent scheme. This will harmonize the uniform parameter names and allow more material networks to reuse the same shader.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8091
