### ISSUE TITLE
UsdPrim.GetAppliedSchemas will return same single apply-schemas multiple times if authored schemas share the same built-in schemas

### ISSUE THREAD

**Issue by jpankalainen** [PixarAnimationStudios/USD#2336]
### Description of Issue
If a prim has authored API schemas that share the same built-in schemas, UsdPrim.GetAppliedSchemas will report the same built-in schemas multiple times even when the built-in schemas are supposed to be singleApplyAPIs. I would only expect the prim to only have applied the schema once since it's supposed to be a single apply schema.

### Steps to Reproduce
1. Create an applied API schema with a built-in API
2. Create another applied API schema with the same built-in API
3. Apply both to the same Prim
4. Call GetAppliedSchemas for the prim
-> The built-in API gets listed twice

### System Information (OS, Hardware)
Windows 10, 64bit

### Package Versions
23.02

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8125
