### ISSUE TITLE
build_scripts GLEW build error

### ISSUE THREAD

**Issue by iceprincefounder** [PixarAnimationStudios/USD#234]
### Description of Issue
Hi,I tried to build USD with build_scripts,but when it built dependences of GLEW,there was a error.By the way,I have built USD v0.7.6 successfully in old way.
### Steps to Reproduce
1. python build_scripts/build_usd.py --build --install_dir /home/xukai/usd_temp/ --inst /home/xukai/usd_temp/deps
2.wait...
### System Information (OS, Hardware)
Centos 6.8 but built usd with centos devtoolset-2(gcc 4.8) and python27
### Package Versions
USD-master tag V0.7.6
### Build Flags
GLEW log.txt
[log.txt](https://github.com/PixarAnimationStudios/USD/files/1118864/log.txt)

**Comment by jtran56** [comment]
Filed as internal issue #148277.

**Comment by sunyab** [comment]
From the log, it looks like this is an error in the GLEW build during its code generation step and not a direct problem in the build script. However, the maintainers actually recommend pulling the GLEW source distribution from sourceforge to avoid having to do this code generation step. I'll look at updating the build script to do this. Thanks for the report!
