### ISSUE TITLE
DLL load failed while importing _tf

### ISSUE THREAD

**Issue by dreisicht** [PixarAnimationStudios/USD#2344]
### Description of Issue
When using any USD functionality or importing the package, I run into the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\peter\Documents\Programme\usd\lib\python\pxr\Tf\__init__.py", line 164, in <module>
    PreparePythonModule()
  File "C:\Users\peter\Documents\Programme\usd\lib\python\pxr\Tf\__init__.py", line 89, in PreparePythonModule
    module = importlib.import_module(
  File "C:\Users\peter\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _tf: The specified module could not be found.
```
I stumbled upon other folks having the same issue, like in #1602, but all solutions were not successful.

### Steps to Reproduce
1. Download and extract the pre-built USD package from Nvidia.
2. Add the usd/bin to the path variable.
3. Add the usd/lib/python path to the pythonpath variable.
4. Update pyside 2, importlib to the newest version.
5. Run `usdcat test.usd` in a terminal.

### System Information (OS, Hardware)
Windows 11, tested Python version 3.7, 3.8, 3.10 and 3.11.

**Comment by meshula** [comment]
Your steps all look reasonable. Have you asked in 

https://forums.developer.nvidia.com/c/omniverse/

Since they provide the download, they might be able to help identify differences between your system set up and their expectations for the build?

**Comment by dreisicht** [comment]
For future reference, these are the steps provided by mati-nvidia at the forums, that resolved it:

- You also need to add usd/lib to your PATH variable.
- This pre-built binary is built against Python 3.7 so you must make sure you are using that version of Python. The traceback you shared shows Python38.

**Comment by meshula** [comment]
Ah, great! I'm glad they were able to help so quickly :)
