### ISSUE TITLE
(Linux) Maya plugin not building

### ISSUE THREAD

**Issue by timlehr** [PixarAnimationStudios/USD#236]
### Description of Issue

Hey guys,

I tried to build USD 0.7.6 using the awesome new build script and got a successful build in almost no time compared to the past. Big thanks for that! However, the Maya plugin isn't loading for me, throwing an error:

```
// Error: line 1: Unable to dynamically load : /opt/USD/third_party/maya/plugin/pxrUsd.so
/opt/USD/third_party/maya/plugin/../lib/libpx_vp20.so: undefined symbol: _ZN31pxrInternal_v0_7__pxrReserved__9TfRefBase22_uniqueChangedListenerE // 
// Error: line 1: /opt/USD/third_party/maya/plugin/../lib/libpx_vp20.so: undefined symbol: _ZN31pxrInternal_v0_7__pxrReserved__9TfRefBase22_uniqueChangedListenerE (pxrUsd) // 
```

### Steps to Reproduce
1. Build USD 0.7.6 and the dependency using the new python build script.
2. Set environment variables for USD.
3. Run Maya 2017 and try to load the plugin. 

### System Information (OS, Hardware)

Fedora 25: `Linux 4.10.15-200.fc25.x86_64 #1 SMP Mon May 8 18:46:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Autodesk Maya 2017 (Linux, vanilla / no service packs)

CPU: Intel® Xeon(R) CPU E5-2690 v4 @ 2.60GHz × 56 
RAM: 64GB
GPU: GeForce GTX 1080/PCIe/SSE2

### Package Versions

USD: 95eef7c9a6662a5362dfc312a186f50c58e27ecd

### Build Flags

Building with settings:
  USD source directory          /home/tim/dev/USD
  USD install directory         /opt/USD
  3rd-party source directory    /opt/USD/src
  3rd-party install directory   /opt/USD
  Build directory               /opt/USD/build

Building
    Imaging                     On
    Ptex support:             Off
    UsdImaging               On
    Documentation          On
    Tests                         Off
    Alembic Plugin           On
    HDF5 support:           Off
    Maya Plugin               On
    Katana Plugin            Off
    Houdini Plugin           Off

Build script flags: `--maya --maya-location /usr/autodesk/maya2017 --alembic --docs`

Enviroment variables:
```
export PYTHONPATH=$PYTHONPATH:/opt/USD/lib/python
export USD_ROOT=/opt/USD
export MAYA_SCRIPT_PATH=$MAYA_SCRIPT_PATH:$USD_ROOT/third_party/maya/share/usd/plugins/usdMaya/resources/
export MAYA_PLUG_IN_PATH=$MAYA_PLUG_IN_PATH:$USD_ROOT/third_party/maya/plugin/
```

**Comment by jtran56** [comment]
Filed as internal issue #148583.

**Comment by timlehr** [comment]
Sorry guys, the issue was on my end. After I cleaned my system as much as possible and completely rebuild USD with all dependencies - it is loaded by Maya! :+1:
