### ISSUE TITLE
failed to save on a network SMB folder 

### ISSUE THREAD

**Issue by kimuss** [PixarAnimationStudios/USD#2370]
### Description of Issue
hello everyone, is there any chance that you guys will look into this issue that probably comes from USD core code?

https://github.com/Autodesk/maya-usd/issues/2745#issuecomment-1489639979

thank you for your time

**Comment by sunyab** [comment]
Filed as internal issue #USD-8177

**Comment by FlorianZ** [comment]
We're currently looking at #849, which we think describes the same basic issue. Please, let us know if you disagree @kimuss. Thank you!

**Comment by kimuss** [comment]
ok, seems the same issue, except for this:

 "Notably, it does NOT occur when using the built-in usdExport command in Maya -- that works fine and will write the file."
 
 Maya does not able to write to a SMB share (ONLY on Windows)
 
 thank you for your time @FlorianZ , I'll follow that issue and next release

**Comment by kimuss** [comment]
> We're currently looking at #849, which we think describes the same basic issue. Please, let us know if you disagree @kimuss. Thank you!

Hi there, Pixar seems to finally closed that ticket, when can we have it on maya plugin?
thank you
