### ISSUE TITLE
USD-MaterialX Rendering Inconsistency in USDView

### ISSUE THREAD

**Issue by RogerDass** [PixarAnimationStudios/USD#2376]
### Steps to Reproduce
1. Open `scene.usda` from the attached project in usdview
2. observe that the 2nd 'shaderball' object from the front doesn't have correct UV scaling
3. also observe that the fabric under it also doesn't have correct UV scaling
4. please see: https://github.com/RogerDass/Usd-Mtlx-Example/blob/main/README.md for comparison images

### System Information (OS, Hardware)
Windows 11, Linux (Ubuntu), Mac - NVidia 3090RTX
### Package Versions
23.02
### Build Flags
--materialx --opencolorio --openimageio --openvdb
[Usd-Mtlx-Example-main.zip](https://github.com/PixarAnimationStudios/USD/files/11154127/Usd-Mtlx-Example-main.zip)

**Comment by sunyab** [comment]
Filed as internal issue #USD-8201

**Comment by FlorianZ** [comment]
@RogerDass, it looks like @klucknav was able to help you on the usd-interest thread. Please feel free to reopen if this is still an issue, though!
