### ISSUE TITLE
[usdGeom] PrimVar::ComputeFlattened not working for time-sampled faceVarying attributes

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#238]
### Description of Issue

If you create a time-sampled faceVarying primvar (ie, uv/st), then when you call ComputeFlattened() on it, it just returns the "raw" samples, not the expanded per-face-vert ones.

ie, if you have:

```
float2[] primvars:st (
    interpolation = "faceVarying"
    unauthoredValuesIndex = 0
)
float2[] primvars:st.timeSamples = {
    0: [ (50 entries) ],
    1: [ (50 entries) ],
    ...
}
int[] primvars:st:indices.timeSamples = {
    0: [ (200 entries) ],
    1: [ (200 entries) ],
    ...
}
```

...and you have a primvar for st, ComputeFlattened will return an array with 50 entries, not 200, as you should get.

The reason is that PrimVar::IsIndexed() returns False, where I think it should return True. The culprit is that it's using  `indexAttr.Get()` - ie, using the default time, which for a time-sampled attribute, returns nothing.

A possible (and easy) fix would be to change `PrimVar::IsIndexed()` to call `Get` with some arbitrary time (other than the `UsdTimeCode::Default()`) - 0, or `UsdTimeCode::EarliestTime()` perhaps.

### Steps to Reproduce
1. Create a usd with a faceVarying time-sampled primvar.
2. call ComputeFlattened() on it - it will be the simple, non-indexed version.
3. call IsIndexed() on it - it will return False

**Comment by spiffmon** [comment]
Ah, nice find, Paul. I suspect we changed from HasAuthoredValue() to Get() when we added attribute blocking (since a block *is* an authored value), and did so a little hastily. EarliestTime() is for just these kinds of queries. Should be able to fix quickly!

--SpiffiPhone

**Comment by jtran56** [comment]
Filed as internal issue #148740.

**Comment by elrond79** [comment]
Saw that this was addressed (in https://github.com/PixarAnimationStudios/USD/commit/27461174676ca5ef7972f325f12707abe98c0c9b) , so I'm closing this issue. Thanks!
