### ISSUE TITLE
Typo in USD documentation

### ISSUE THREAD

**Issue by erich666** [PixarAnimationStudios/USD#2386]
### Description of Issue
Typo "faveVarying" in docs. Should be "faceVarying". "faveVarying" is what Logan Roy does in "Succession."

### Steps to Reproduce
1. Go to https://www.openusd.org/release/api/class_usd_geom_primvar.html#Usd_InterpolationVals
2. Search on "faveVarying"

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A

**Comment by sunyab** [comment]
Filed as internal issue #USD-8232
