### ISSUE TITLE
Sample USD meshes for stress-testing downstream applications

### ISSUE THREAD

**Issue by shumash** [PixarAnimationStudios/USD#2399]
We use USD API extensively in [Kaolin Library](https://github.com/NVIDIAGameWorks/kaolin) to support importing geometric and material data for Deep Learning applications. However, we are not sure how to test the robustness of our importers against a range of geometric data (particularly, meshes). 

Is there a public diverse set of sample USD meshes covering a range of the format specs? For example, covering different normal and uv interpolation policies, mesh subsets, and  similar attributes. A toy dataset like this would be very helpful to stress test downstream applications.

**Comment by meshula** [comment]
The Academy Software Foundation has got an effort underway on this front, I recommend heading over there to see what's going on! Here's how to find the Slack:

https://join.slack.com/t/academysoftwarefdn/shared_invite/zt-1ty2w4s7k-DQ0fn85unhNDc~7XnczYbQ

Look for #wg-usd-assets

There are regular zoom meetings, there was one this morning.

Here's the associated repository which contains a variety of format checks and comparisons:

https://github.com/usd-wg/assets

and a number of community contributions in progress:

https://github.com/usd-wg/assets/pulls

**Comment by shumash** [comment]
Thank you. This is really helpful.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8263

**Comment by FlorianZ** [comment]
@shumash, we are closing this given the pointers @meshula provided, but please feel free to reopen or file a new issue if you need additional help. Thanks!
