### ISSUE TITLE
Katana test env

### ISSUE THREAD

**Issue by chadrik** [PixarAnimationStudios/USD#240]
Hi all, I know that this is on the docket as we've talked about this before, but I wanted to make an official ticket.  It would be a huge help for us to avoid broken deployments due regressions and/or basic build bugs, as well as provide a home for contributing new tests.

thanks!

**Comment by jtran56** [comment]
Filed as internal issue #148742.

**Comment by spiffmon** [comment]
Hi Chad,
   Just wanted to note this has been on the books for awhile, and is actively being worked on right now.

**Comment by chadrik** [comment]
Glad to hear it!  Thanks for the update.
