### ISSUE TITLE
Major artifacts rendering untextured meshes in Hydra/PRman. Verified in 23.05

### ISSUE THREAD

**Issue by guidoq** [PixarAnimationStudios/USD#2403]
### Description of Issue
Untextured meshes are broken when rendered in RenderMan. If you have a textured object, the untextured one also works but in isolation, you get artifacts.
Please take a look at the attached USD files one with one plane with untextured previewsurface and one with two but one textured and one not.
Of there is no bound material, the artifact goes away.
[RMAN_USD_TEX_BUG.zip](https://github.com/PixarAnimationStudios/USD/files/11302549/RMAN_USD_TEX_BUG.zip)

**Comment by sunyab** [comment]
Filed as internal issue #USD-8267

**Comment by klucknav** [comment]
I wasn't able to see any artifacts when opening the attached USD files in usdview using 24.08. Are you still seeing this issue?

**Comment by klucknav** [comment]
It seems like this might be fixed, but if you run into it again please let us know!
