### ISSUE TITLE
  No RenderMan plugin available for RenderMan 25

### ISSUE THREAD

**Issue by samhodge** [PixarAnimationStudios/USD#2405]
### Description of Issue

Cannot build USD against current version of NCR Renderman, only NCR 25.0 can be downloaded.

### Steps to Reproduce
1. clone repository, checkout dev branch
2. install miniconda Python 3.9
3. install PySide6 via pip install
4. install PyOpenGL via pip install
5. Install Renderman 25 NCR via alien
6. Build USD as follows
7. 
```
python USD/build_scripts/build_usd.py \
 $PWD/build/USD \
--prman --prman-location /opt/pixar/RenderManProServer-25.0/ \
--opencolorio --openimageio \
--use-cxx11-abi=0 \
--build-python-info \
$PWD/prman-conda/bin/python3.9 \
$PWD/prman-conda/include/python3.9 \
$PWD/prman-conda/lib/libpython.so.3.9 \
3.9 \
--build-args USD,"-DRENDERMAN_LOCATION=/opt/pixar/RenderManProServer-25.0/"
```

Error
`No RenderMan plugin available for RenderMan 25`

### System Information (OS, Hardware)

Unbuntu 20.04
gcc 9.4
Python 3.9 (via miniconda)

EPYC Rome CPU 7402P
128Gb RAM
NVIDIA RTX 3090

### Package Versions
USD v23.05

### Build Flags
```python USD/build_scripts/build_usd.py \
 $PWD/build/USD \
--prman --prman-location /opt/pixar/RenderManProServer-25.0/ \
--opencolorio --openimageio \
--use-cxx11-abi=0 \
--build-python-info \
$PWD/prman-conda/bin/python3.9 \
$PWD/prman-conda/include/python3.9 \
$PWD/prman-conda/lib/python3.9 \
3.9 \
--build-args USD,"-DRENDERMAN_LOCATION=/opt/pixar/RenderManProServer-25.0/"
```

**Comment by samhodge** [comment]
Have moved to Ubuntu 20.04 in hope that Renderman 25 Hydra Delegate will arrive soon.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8268

**Comment by FlorianZ** [comment]
Hi @samhodge, we weren't able to make the change for the 23.05 release, but it's a priority for the next release and should appear in dev sooner. Thanks for your patience!

**Comment by samhodge** [comment]
No worries mate, just needed to let you know there is a user out there that cares enough to use the new software

**Comment by samhodge** [comment]
I did confirm that I had a build of everything else that was OK. Using a non system Python through a conda context turns out to be hard, even though I swear I have done it in the past with success. As Material X and others need to link against X11 and OpenGL which are in the system path and other parts of the build system are under conda control I was forced to not use conda which is my preference to use that or Docker to stop pollution of my OS with project specific soft requirements. Anyway after too many false starts I got to a version of usdview that loaded the target scene that I want to test with HdPRMan. That day will come...

**Comment by sunyab** [comment]
Support for RenderMan 25 is now in the `dev` branch as of `eeb18f09c421d9c2b22a4cce46f19fdffb39678e` and will be part of the upcoming 23.08 release.

**Comment by samhodge** [comment]
Thanks a million for that

**Comment by sunyab** [comment]
Closing this out now that USD 23.08 (which includes support for RMan 25) is out the door.
