### ISSUE TITLE
MaterialX lighting integration broken

### ISSUE THREAD

**Issue by rakroo** [PixarAnimationStudios/USD#2411]
### Description of Issue

We ran into an issue with lighting when a MaterialX material is bound. I have attached the repro scene file. The file contains two materials - UsdPreviewSurface and MaterialX. You can switch between the binding on lines:14/15. The scene has a single distant light.

### Steps to Reproduce
1. Open the attached usd file.
2. Switch between material bindings on line 14/15
3. When in MaterialX binding mode ensure you are using Scene Lights to reproduce the issue.
4. When you switch to default lighting the issue no longer manifests

usdview with UsdPreviewSurface and Scene Light
![usdpreviewlighting](https://user-images.githubusercontent.com/129088650/234721563-67553122-1937-4bd4-a819-d9c85783177c.png)
usdview with MaterialX and Scene Light
![materialXlighting](https://user-images.githubusercontent.com/129088650/234721565-e32e6b4e-c084-42b7-86e7-3613146e0552.png)
usdview with Default Light
![materialxdefault](https://user-images.githubusercontent.com/129088650/234721564-fd6af00f-5d50-441e-8236-e8d6cf36a01c.png)

[materialxLightingBroken.zip](https://github.com/PixarAnimationStudios/USD/files/11337960/materialxLightingBroken.zip)

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD 23.02

### Build Flags
Default flags

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8282
