### ISSUE TITLE
install USD arise ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:8'

### ISSUE THREAD

**Issue by Su970315** [PixarAnimationStudios/USD#2413]
### Description of Issue
install USD arise ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:8'
### Steps to Reproduce
  arch.vcxproj -> C:\USD\build\USD-23.05\pxr\base\arch\Release\usd_arch.dll
  bigRWMutex.cpp
  mallocTag.cpp
  type.cpp
D:/USD-23.05/pxr/base/tf/bigRWMutex.h(232): error C2327: 'pxrInternal_v0_23__pxrReserved__::TfBigRWMutex::_LockState::mutex': is not a type name, static, or enumerator (compiling source file D:\USD-23.05\pxr\base\tf\bigRWMutex.cpp) [C:\USD\build\USD-23.05\pxr\base\tf\tf.vcxproj]
D:/USD-23.05/pxr/base/tf/bigRWMutex.h(232): error C2065: 'mutex': undeclared identifier (compiling source file D:\USD-23.05\pxr\base\tf\bigRWMutex.cpp) [C:\USD\build\USD-23.05\pxr\base\tf\tf.vcxproj]
D:/USD-23.05/pxr/base/tf/bigRWMutex.h(232): error C2327: 'pxrInternal_v0_23__pxrReserved__::TfBigRWMutex::_LockState::mutex': is not a type name, static, or enumerator (compiling source file D:\USD-23.05\pxr\base\tf\mallocTag.cpp) [C:\USD\build\USD-23.05\pxr\base\tf\tf.vcxproj]
D:/USD-23.05/pxr/base/tf/bigRWMutex.h(232): error C2065: 'mutex': undeclared identifier (compiling source file D:\USD-23.05\pxr\base\tf\mallocTag.cpp) [C:\USD\build\USD-23.05\pxr\base\tf\tf.vcxproj]
D:/USD-23.05/pxr/base/tf/bigRWMutex.h(232): error C2327: 'pxrInternal_v0_23__pxrReserved__::TfBigRWMutex::_LockState::mutex': is not a type name, static, or enumerator (compiling source file D:\USD-23.05\pxr\base\tf\type.cpp) [C:\USD\build\USD-23.05\pxr\base\tf\tf.vcxproj]
D:/USD-23.05/pxr/base/tf/bigRWMutex.h(232): error C2065: 'mutex': undeclared identifier (compiling source file D:\USD-23.05\pxr\base\tf\type.cpp) [C:\USD\build\USD-23.05\pxr\base\tf\tf.vcxproj]

ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:8'
See C:\USD\build\USD-23.05\log.txt for more details.

### System Information (OS, Hardware)
windows 10 
### Package Versions
23.05
### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/USD/files/11350359/log.txt)

**Comment by sunyab** [comment]
Hi @Su970315, this error is due to a bug in your version of MSVC:
https://developercommunity.visualstudio.com/t/sizeof-fails-for-struct-members-if-used-as-array-s/255205

This was fixed in later versions of VS2017. Updating your installation should fix this issue.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8284

**Comment by FlorianZ** [comment]
Closing this given @sunyab 's suggestion. @Su970315 please feel free to reopen if this doesn't address your issue. Thank you!

**Comment by contentproplus** [comment]
I'm trying to build 23.08 with renderman plugin on macOS (Apple Silicon)  
ERROR: Failed to run 'cmake --build . --config Release --target install -- -j 8'

Everything builds fine without the renderman  flag
