### ISSUE TITLE
Can't copy from usdview interpreter on MS Windows

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#242]
### Description of Issue
since CTRL+C doesn't work and there is no magic linux "select to copy", you basically can't copy anything from the interpreter window.

### Steps to Reproduce
1.  Try to copy anything from the interpreter window

### System Information (OS, Hardware)
Windows.
### Package Versions
0.75 (ish)

### Build Flags
Release

**Comment by jtran56** [comment]
Filed as internal issue #148913.
