### ISSUE TITLE
usdview: SpatialAudio only plays in nonSpatial mode

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2428]
### Description of Issue

Seems that while usdview in general supports https://openusd.org/release/wp_usdaudio.html, (a pleasant surprise!), it does not play spatial audio. The expectation would be that the camera orbit + camera position in the view contribute to the spatial audio effect.

### Steps to Reproduce
1. Download [Needle-MadeWithNeedle-20230509-230444.zip](https://github.com/PixarAnimationStudios/USD/files/11436191/Needle-MadeWithNeedle-20230509-230444.zip)
2. Drop it in usdview
3. Play the animation

Expected: can hear audio, each of the instruments has its own AudioSource which is set to spatial
Actual: no audio.

If you change the attribute to "nonSpatial" in the file, all three audio sources will play.

### System Information (OS, Hardware)
Windows 11

### Package Versions
0.23.2 from Omniverse Launcher

**Comment by spiffmon** [comment]
Wow, that is a surprise to me, too, @hybridherbst !  I suspect that our friends at NVidia put in that special easter egg into the version of usdview that they ship, because there is no such audio support in our stock usdview.  We are eager to get cross-platform support for audio in usdview, but for now, enhancements to the existing feature you found need to go through NVidia, I think.

**Comment by hybridherbst** [comment]
Ha! Yet another layer for new bugs / undocumented behaviours 🥲

I'll hunt for way to report bugs to them directly for USD-related things. Not sure how I would detect/know if a bug is from their end or this repo here though, so I may have to continue opening issues here and rely on your guidance. Thanks!

**Comment by spiffmon** [comment]
No worries, @hybridherbst !  I’ll close this one out, for now.

**Comment by asluk** [comment]
The usdview packges on OV Launcher use the same build recipes and code as in tagged GitHub releases. I'll look to see if something went awry in the packaging pipeline. There is no NV-specific audio support in any of our USD builds AFAIK, as OV audio backends are implemented elsewhere. Will definitely be interesting to dig further into this mystery feature.

**Comment by pmolodo** [comment]
Hi @spiffmon - when you said "Easter egg", were you referring to [spatial audio](https://openusd.org/release/api/class_usd_media_spatial_audio.html) support in usdview?

**Comment by pmolodo** [comment]
Also, @hybridherbst - is what you were testing a "usdview" app from omniverse?  Or did you manually set some environment variables and then launch usdview from some other app?

**Comment by asluk** [comment]
I can't repro this in usdview-- my instincts are the same as @pmolodo -- is it possible that @hybridherbst has other env vars at play that end up registering additional plugins to USD when usdview is launched?

**Comment by hybridherbst** [comment]
I'm baffled - trying to reproduce what I originally experienced and I'm not able to.
I mean, if both of you say that there's no code to play audio anywhere then I must have tricked myself (e.g. audio playing somewhere in the background)...

I was using usdview started from Omniverse Launcher, with no extra environment variables.

**Comment by asluk** [comment]
Thanks for checking, @hybridherbst ! (I seemed to have missed the notification when you updated this a couple weeks ago; apologies!)
