### ISSUE TITLE
LZ4_decompress_safe errors when running stage.Export on a stage with heavy assets

### ISSUE THREAD

**Issue by NickWu** [PixarAnimationStudios/USD#2434]
### Description of Issue
Hi, we are having a `LZ4_decompress_safe` error at https://github.com/PixarAnimationStudios/USD/blob/release/pxr/base/tf/fastCompression.cpp#L116 
when calling `stage.Export()` on a stage with heavy assets. I found the issue was due to not enough output buffer size for decompression. I have found a fix and I'll be submitting a PR for this issue later. 

### System Information (OS, Hardware)
OS: CentOS 7.8

### Package Versions
Tested in USD-v21.8, v22.11

**Comment by NickWu** [comment]
I have submitted a PR for this issue https://github.com/PixarAnimationStudios/USD/pull/2435.

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8318

**Comment by NickWu** [comment]
Closed this issue as it's been addressed in https://github.com/PixarAnimationStudios/OpenUSD/commit/04786240f90ababeb203349fa910f9e5f3e81d92
