### ISSUE TITLE
how to learn hydra?

### ISSUE THREAD

**Issue by chongxian** [PixarAnimationStudios/USD#2443]
hello, I am a beginner of pixar USD, and I am looking forward to learning hydra, but I can't find the related tutorial, only saw the ppt on the official website. would you please provide the related tutorial? 
Thanks for your help.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8357

**Comment by Cewein** [comment]
This link should get you what you need to start with hydra :
https://openusd.org/release/api/_page__hydra__getting__started__guide.html

**Comment by meshula** [comment]
Thanks for linking the new documentation @Cewein!
