### ISSUE TITLE
Pinned CatmullRom curve not rendering correctly in usdview

### ISSUE THREAD

**Issue by SonnyCampbellUnity** [PixarAnimationStudios/USD#2445]
### Description of Issue
I am working on the USD exporter for Blender, and am investigating an issue when exporting a catmull-rom curve. In Blender the first and last points of a catmullRom curve are treated as endpoints, so I believe I need to set the `pinned` attribute on the usd export to ensure that the "phantom" points are created in the client.

This is the file that gets exported from Blender (I added the .txt extension because github complained about the .usda extension):
[usd_catmull_test.usda.txt](https://github.com/PixarAnimationStudios/USD/files/11543810/usd_catmull_test.usda.txt)

When I open that file in `usdview` I see the three curves hovering above the cube:
![image](https://github.com/PixarAnimationStudios/USD/assets/68228653/edcdbb48-a2ce-4e3c-b93c-b6b94b8e60b3)

However the curves should be attached to the cube (screenshot from Blender):
![image](https://github.com/PixarAnimationStudios/USD/assets/68228653/2734002c-9139-4c9a-81e3-cec6de90ece0)

### Version
I am using version 23.05, and built everything from source with the standard build steps outlined in the readme.

### OS
I'm on Windows 10 Enterprise edition.

### Other
A (possibily unrelated) issue is when I set the complexity to anything higher than Low, I get weird visual behaviour of the curves:
Complexity = Medium
![image](https://github.com/PixarAnimationStudios/USD/assets/68228653/eb8c803c-ff0b-463a-b4bc-fc172efbc83b)

Complexity = Very High
![image](https://github.com/PixarAnimationStudios/USD/assets/68228653/ff6ccd8c-f57a-4e4e-9e60-84499c1335d3)

I'm not sure if that is signifying that I have done something wrong in the curve export code, or if there's something that I need to set on the curves in the usd file, or if it's a visual issue with `usdview`, but I thought I would ask here.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8359

**Comment by rajabala** [comment]
Thanks for filing! Storm renders curves as thin line segments when using a complexity of Low. The behavior you see stems from the first and last segments of catRom curves being skipped and doesn't seem desirable. We're looking into it and should address it soon.
As for the widths, we default to 1.0 (world space unit) when unauthored, which is why you see the large half tubes.

**Comment by spiffmon** [comment]
Also note that, per [this thread](https://groups.google.com/g/usd-interest/c/iiJl1OxgH8o/m/jBKiigk6AgAJ) we'll be trimming the fallback width from 1.0 to 0.1 in future, so the tessellated tubes will be more "curve like" with respect to the cube.  Which of course doesn't obviate the desire for Blender export to explicitly set curve width when it has an idea of what it should be!
