### ISSUE TITLE
Build Failed While Installing USD (DLL load failed while importing _usdResolverExample)

### ISSUE THREAD

**Issue by dinelanthony** [PixarAnimationStudios/USD#2447]
### Description of Issue

I am able to successfully install all dependencies however when it finally comes to installing USD I get the error:

```
Converting Doxygen comments to Docstring format...
EXEC : error : DLL load failed while importing _usdResolverExample: The specified module could not be found. [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
EXEC : error : Could not import UsdResolverExample [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
  -- Installing: C:/Users/DinelAnthony/RenderingProj/USD/lib/usd/plugInfo.json
  -- Installing: C:/Users/DinelAnthony/RenderingProj/USD/plugin/usd/plugInfo.json
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1 [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code -1. [C:\Users\DinelAnthony\RenderingProj\USD\build\USD\install.vcxproj]

ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:8'
```

Which makes it seem as though Doxygen is not happy somewhere along the line?

### Steps to Reproduce
1. clone this repo
2. Open x64 Native Tools Command Prompt
3. python C:\Users\DinelAnthony\source\repos\USD\build_scripts\build_usd.py --build-monolithic --tests --docs --python-docs --debug-python --ptex --openvdb --embree --no-prman --openimageio --alembic --hdf5 --no-draco --materialx  --opencolorio "C:\Users\DinelAnthony\RenderingProj\USD"

### System Information (OS, Hardware)

Windows 10

### Package Versions

Python 3.8.10
VS 2017 15.9
CMake 3.26.4
Doxygen 1.9.7

### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/USD/files/11568959/log.txt)

### Steps I Have Taken

As suggested in #1361 I installed Dependencies.exe and at first had an issue with usdResolverExample.dll not being found but then I added it to PATH and that error cleared up. Therefore, I'm not sure why this error is still coming up.

One solution that has apparently worked for other people was downgrading to Python 3.7 but that does not work for my project as I ultimately need to use Python 3.9 but was testing with Python 3.8 since OpenColorIO seems to be broken on 3.9

Any help would be appreciated!

### Update

This has been fixed: tl;dr:
1. Examples don't seem to work just yet, use --no-examples when building
2. When you change your Python version or PATH sometimes you might need to perform a fresh build of USD by either deleting the partially built folder or changing the build location

**Comment by sunyab** [comment]
Hi @dinelanthony, this is probably something weird going on with the build system not setting up %PATH% correctly before Python doc generation. We'll take a look at this, but in the interim one workaround would be to turn off building the examples by adding `--no-examples` to your build_usd.py command line.

**Comment by dinelanthony** [comment]
Hi @sunyab,

Thanks for the quick reply! I'll try it out and come back if I have any issues!

**Comment by dinelanthony** [comment]
The new build just finished and now I am getting a completely different error which I don't think I can fully understand. I switched back over to Python 3.9 since that is what I need the project to be built in regardless (I just ignored OpenColorIO for now until that gets patched) but it seems that a lot of the libs contain functions that were deprecated in Python 3.9, causing the program to fail although I could be misinterpreting. Here is the log file to see the entire error message:

[log.txt](https://github.com/PixarAnimationStudios/USD/files/11570042/log.txt)

**Comment by sunyab** [comment]
Ah, it looks like those Python 3.9 messages are just warnings, and the actual error is here:

```
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "C:\Users\DinelAnthony\AppData\Local\Programs\Python\Python311\Scripts\pyside6-uic.exe\__main__.py", line 7, in <module>
    File "C:\Users\DinelAnthony\AppData\Local\Programs\Python\Python311\Lib\site-packages\PySide6\scripts\pyside_tool.py", line 83, in uic
      qt_tool_wrapper("uic", ['-g', 'python'] + sys.argv[1:], True)
    File "C:\Users\DinelAnthony\AppData\Local\Programs\Python\Python311\Lib\site-packages\PySide6\scripts\pyside_tool.py", line 42, in qt_tool_wrapper
      pyside_dir = Path(ref_mod.__file__).resolve().parent
                   ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\DinelAnthony\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 871, in __new__
      self = cls._from_parts(args)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\DinelAnthony\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 509, in _from_parts
      drv, root, parts = self._parse_args(args)
                         ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\DinelAnthony\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 493, in _parse_args
      a = os.fspath(a)
          ^^^^^^^^^^^^
  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This looks like it's picking up PySide6 from a Python 3.11 installation instead of the Python 3.9 installation. Maybe PYTHONPATH wasn't updated properly when you downgraded to 3.9?

**Comment by dinelanthony** [comment]
Thanks for catching that! I have uninstalled Python 3.8 and 3.11 from my PC, and installed PySide6 on 3.9. According to the log, it detects that I have PySide6 installed on 3.9 but defaults to using one in a non-existent Python311 folder.

![image](https://github.com/PixarAnimationStudios/USD/assets/40641138/93ed39cc-2106-4e78-a1a3-a25180eb4ea9)

And my user environment PATH only contains Python3.9

![image](https://github.com/PixarAnimationStudios/USD/assets/40641138/3aee1a5a-2ab8-4a87-b5cc-fd47b3bbd3b3)

While my system environment variable PATH does not have any references to Python

![image](https://github.com/PixarAnimationStudios/USD/assets/40641138/409d1235-a0b4-41b5-ad98-d0826df67640)

Finally, I had to create a system environment variable "PYTHONPATH" since it did not exist

![image](https://github.com/PixarAnimationStudios/USD/assets/40641138/fe5a6a43-371b-49b9-9e7c-b2b9a0059a62)

However even with all of these changes, I still get the issue of the script using a non-existent Python311 folder...
[log.txt](https://github.com/PixarAnimationStudios/USD/files/11578799/log.txt)

Sorry about all this I just can't wrap my head around why its failing the way it is.

**Comment by dinelanthony** [comment]
Update:

I did a fresh install of USD following everything and was able to get it to build properly! Thank you @sunyab for all the help!

**Comment by meshula** [comment]
One possibility is that the package manager (pip?) you used to install pyside6 might be confusing matters, or that some other environment variable has been set pointing at the deleted pyside_uic. Maybe uninstall it, and see if the nonexistent one is still detected, and if so, attempt to uninstall it again?
