### ISSUE TITLE
Documentation - Broken Link

### ISSUE THREAD

**Issue by kkh3049** [PixarAnimationStudios/USD#2450]
### Description of Issue
Link to USD FAQ resolves incorrectly, dropping "/usd" in url.

### Steps to Reproduce
1.  Go to https://openusd.org/release/api/_usd__page__properties_of_scene_description.html#Usd_PrimSpecifiers
2. Under "Defs, Overs, Classes, and Prim Types" click the see also link labeled "What's the difference between an "over" and a "typeless def"?"
3. A 404 error is reported.

Link is given as "http://openusd.org/docs/USD-Frequently-Asked-Questions.html#USDFrequentlyAskedQuestions-What'sthedifferencebetweenan%22over%22anda%22typelessdef%22?"  which resolves to "https://openusd.org/releasefaq.html#USDFrequentlyAskedQuestions-What'sthedifferencebetweenan%22over%22anda%22typelessdef%22?"
But intended location is: "https://openusd.org/release/usdfaq.html#what-s-the-difference-between-an-over-and-a-typeless-def"

### System Information (OS, Hardware)
Using Microsoft Edge (Version 113.0.1774.50 (Official build) (64-bit)) on Windows 11

**Comment by sunyab** [comment]
Filed as internal issue #USD-8366
