### ISSUE TITLE
Can't play animation from file after opening

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2452]
### Steps to Reproduce
1. Open the attached file (from [Apple's WWDC event page](https://www.apple.com/apple-events/)) in usdview
2. [apple_event.zip](https://github.com/PixarAnimationStudios/USD/files/11606404/apple_event.zip)
3. Note that you can't play an animation in usdview
4. Open the file elsewhere, e.g. Blender-usd branch
5. Note you _can_ play an animation there, there's timeSamples on all these objects

Note: the animation seems to be detected in usdview too, but it sets start frame = end frame = 4800 at startup, so at a curious glance it looks like there wouldn't be any animation.

### System Information (OS, Hardware)
Windows 11, RTX2070

### Package Versions
Latest from Omniverse Launcher

**Comment by drwave** [comment]
The start and end time codes are the same - 

#usda 1.0
(
    customLayerData = {
        string copyright = "Copyright (c) 2023 Apple Inc. All rights reserved."
    }
    defaultPrim = "Root"
    doc = """Generated from Composed Stage of root layer
"""
    endTimeCode = 4800
    framesPerSecond = 600
    metersPerUnit = 1
    startTimeCode = 4800
    timeCodesPerSecond = 600
    upAxis = "Y"
)

**Comment by spiffmon** [comment]
That would be it, @drwave !  Curious that all those other packages seem to ignore the editorial information, which usdview uses to configure the playback range.

**Comment by hybridherbst** [comment]
I see! I believe the reason why it works in QuickLook at least then is that the animation is actually started by the preliminary actions in the file, not from the stage.

I think the issue here is then more a small UI issue - the visual states for "this file has no animation" and "this file has animation but you can't play the current playing range" are awefully similar, especially as I've "learned" that a greyed-out Play button means the file has no animation, which now turns out to have been the wrong thing to learn:

_Without any animation:_ 
![image](https://github.com/PixarAnimationStudios/USD/assets/2693840/627fc5da-c18a-4e13-b2d4-1e25737010cf)

_With animation but a default timerange that prevents playing:_
![image](https://github.com/PixarAnimationStudios/USD/assets/2693840/6fe1a02b-0503-4efd-ba5e-125d9051b056)

Knowing that now and comparing side-by-side I can see that without animation, the time ranges are empty, which is probably a better indicator than the Play button being disabled then.

**Comment by sunyab** [comment]
Filed as internal issue #USD-8368

**Comment by drwave** [comment]
You can also look at the metadata tab on the Root prim and notice that the startTimeCode and endTimeCode are the same value - 4800

**Comment by FlorianZ** [comment]
Recognizing that there are improvements we can make to usdview to better highlight the erroneous data, we're closing this particular issue now that the issue has been addressed.
