### ISSUE TITLE
`usdGenSchema` collapses the authority component of URI asset paths when the associated path resolver is not registered

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2480]
### Description of Issue

Consider the following `schema.usda`.

```
#usda 1.0
(
    subLayers = [
        @usd/schema.usda@
    ]
)

over "GLOBAL" (
    customData = {
        string libraryName = "mySchema"
        string libraryPath = "./"
        string libraryPrefix = "MySchema"
        bool skipCodeGeneration = true
    }
)
{
}

class "MyAPI"
(
    customData = {
        token apiSchemaType = "singleApply"
        string className = "MyAPI"
    }
    doc = "A test asset reference."
    inherits = </APISchemaBase>
)
{
    asset myApi:assetReference= @omni://1.2.3.4/path/to/file.txt@) (
        doc = """"""
    )
}
```

`usdGenSchema` uses `UsdStage::Flatten` and will try to anchor all asset paths. If an asset path refers to a URI resolver that isn't registered, the default resolver will treat the path like a file path and "normalize" away the `//`.  For URIs, this effectively shifts the "authority" component into the "path" component of identifier.

There may be practical reasons why during `usdGenSchema` the asset and resolver may not be available. `usdGenSchema` depending on the availability of the resources required to run the resolvers used by attribute values may be unexpected.

If I suppress running `SdfComputeAssetPathRelativeToLayer` just for the `omni:` URI prefix in `_AnchorAssetPathRelativeToLayer`, the `//` is preserved.

Curiously, if I try to take advantage of "anchored paths" in my `schema.usda` file, it effectively resolves relative to the source directory. It doesn't seem like there's a use case for for the current anchoring behavior in `usdGenSchema`.

### Steps to Reproduce
1.  Save the above layer to `schema.usda`
2.  Run the following code
```
>>> from pxr import Usd
>>> Usd.Stage.Open("./schema.usda").Flatten().ExportToString()
```
3. You should see `//` collapsed into `/` for `myApi:assetReference`, effectively erasing the "authority" component.

 
### System Information (OS, Hardware)
Observed on both Linux and Windows

### Build Flags
`--tests -no-imaging --no-materialx`

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8410
