### ISSUE TITLE
Not  able to Launch USD view. Getting error for QT Platform plugin

### ISSUE THREAD

**Issue by Prachitbooks** [PixarAnimationStudios/USD#2487]
### Not  able to Launch USD view. Getting error for QT Platform plugin
```
 >usdview sphere.usda 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, wayland, vkkhrdisplay, minimal, vnc, minimalegl, wayland-egl, offscreen, linuxfb, xcb.

[1]    3647995 IOT instruction  /usr/local/google/home/prachitraorane/prachit/code/USD/bin/usdview sphere.usd
```
### Steps to Reproduce
1. Build USD 
2. Launch usdview

### System Information (OS, Hardware)
1. OS - Debian Linux

### Package Versions
|package|version|
|--------|-------|
| python |3.9.13|
| pyside |6.5.1.1|
| PyOpenGL |3.1.7|
|USD |  release branch|

### Build Flags
none

**Comment by asluk** [comment]
https://groups.google.com/g/usd-interest/c/S3_XFjBTC-8/m/ZpOyeju2AQAJ

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8417

**Comment by spiffmon** [comment]
Thanks, @asluk !  Closing, please let us know if Aaron's advice doesn't do the trick, @Prachitbooks
