### ISSUE TITLE
Need QPlainTextEdit to retain focus in USDView plug-ins

### ISSUE THREAD

**Issue by mromeoinbibo** [PixarAnimationStudios/USD#2489]
### Description of Issue
I have created a plugin for USDView which uses a QPlainTextEdit widget.
Unfortunately the widget cannot retain focus in USDView.
This issue is due to the `AppEventFilter` not listing QPlainTextEdit in the `JealousFocus` method [code](https://github.com/PixarAnimationStudios/USD/blob/b53573ea2a6b29bc4a6b129f604bbb342c35df5c/pxr/usdImaging/usdviewq/appEventFilter.py#L93)

### Steps to Reproduce
1. Create a USDView plug-in containing using a QPlainTextEdit widget
2. Launch the plug-in in USDView
3. Set the focus on the QPlainTextEdit widget by clicking with the mouse
4. Write something inside the widget
5. While the focus is still on the QPlainTextEdit widget, move the mouse
6. The focus will return to the main USDView window

**Comment by sunyab** [comment]
Filed as internal issue #USD-8230

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8419

**Comment by spiffmon** [comment]
COuld you let us know what platform you're on, @mromeoinbibo ?  We're having trouble reproducing.
