### ISSUE TITLE
`SdfMapEditProxy` has inconsistent comparison operator overloads

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#2502]
### Description of Issue
While removing the dependency on `boost::totally_ordered`, it was observed many of the comparison operator overloads (`==`, `<`, `>`, etc.) return `false` if a `_Validate` method fails.  This could lead to situations where (for example) `==` and `!=` both return `false` for the same values.

However, the operators that are inherited from `boost::totally_ordered` cannot know about this `_Validate` method, leading to inconsistent behavior depending on the value types being compared and which operators are being exercised. The boost removal effort intends to preserve the existing behavior. It was requested that this be filed as a reminder to examine after `boost::totally_ordered` has been removed.

### Steps to Reproduce
N/A

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8441
