### ISSUE TITLE
PointInstancer has to support full precision orientation.

### ISSUE THREAD

**Issue by YKZDY** [PixarAnimationStudios/USD#2529]
### Reference
https://groups.google.com/g/usd-interest/c/ID-9MQKktWc

### Description of Issue
As discussed with Spiff in the attached thread, the half-precision orientation is not accurate enough to layout assets in a big world, like every window, door, and brick in the modern city, especially when they have a 90/180/270 rotation.

Spiff was purposed to have an updated schema that supports "orientationsf" as an optional attribute. I believe it will relieve the inaccuracy, and even maybe having an optional "orientationsd" as well sounds like a good idea to me :)

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8486

**Comment by asluk** [comment]
The original thread in https://groups.google.com/g/usd-interest/c/ID-9MQKktWc mentioned versioning the PointInstancer schema for this; is that still worth doing? 🙏🏼

**Comment by YKZDY** [comment]
Hey Aaron, nice to meet you here.
As far as our practice, it really depends on the way you are using PointInstancer. It would be fine if you are scattering trees, sand, or rocks, but you will find the artifacts if you are trying to assemble a building from bricks far from the origin.

By the way, the Large World Coordinates feature of UE5 makes this a priority for us.

**Comment by asluk** [comment]
Hi @YKZDY , yes I meant that is it worth using schema versioning, e.g., PointInstancer_01, to make it clear that point instancer content that has the new `orientationsf` attribute are not honored in older releases of OpenUSD < v24.03 .

**Comment by spiffmon** [comment]
We discussed it internally, @asluk , and according to the guidelines laid out in the proposal, it did not warrant a version bump and the larger code changes that would have required.  Maybe we use this as a test-case for those guidelines, along with the recent changes to DomeLight that _did_ warrant a version bump?

**Comment by asluk** [comment]
sounds fair; thanks @spiffmon
