### ISSUE TITLE
Exception throws in UsdStage::Open() for fuzzed usd model

### ISSUE THREAD

**Issue by Hongyuan-Li** [PixarAnimationStudios/USD#2537]
### Description of Issue
Exception throws in UsdStage::Open() for fuzzed usd model
### Steps to Reproduce
1. unzip the package
2. when open usd file
3. exception throws as below
[AnimationWithDifferentTangents---!6iyg1lvyfzp6u-a9fp82b9a18.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/12035715/AnimationWithDifferentTangents---.6iyg1lvyfzp6u-a9fp82b9a18.zip)
![Exception](https://github.com/PixarAnimationStudios/OpenUSD/assets/26539746/319a7cbc-e524-4153-942e-6fb26f9c77df)

### System Information (OS, Hardware)
Windows 10

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8504

**Comment by syoyo** [comment]
FYI the usd model contains too many tokens in TOKEN section.

```
./tusdcat ../data/AnimationWithDifferentTangents---\!6iyg1lvyfzp6u-a9fp82b9a18.usd         ERR : [error]/home/syoyo/work/tinyusdz/src/crate-reader.cc[Crate]:ReadTokens():4511 Too many Tokens.
```

**Comment by Hongyuan-Li** [comment]
@syoyo right, this is a Fuzzed USD model and I want to know if there will be a fix in future to avoid this exception  ?

**Comment by spiffmon** [comment]
So the exception here is a `std::bad_alloc` exception that USD is just not catching, by design, right now.  We have recently been reconsidering our use of and policy for exceptions, and will have another look at this one in light of that.  We will update when we have more info!

**Comment by spiffmon** [comment]
We've recently been thinking about this again, and while we think that there are potentially many legit files that could also throw that exception (e.g. on resource-limited platforms), we do think it prudent to try to catch and error/recover from exceptions thrown from inside **plugin code** in as many of OpenUSD's plugin API's as possible, so we intend to work our way through those API's.  For non-virtual-interface API's like SdfLayer and ArResolver, this will be relatively straightforward, and, inspired by this report, will first tackle `SdfLayer::FindOrOpen()`, which already returns a NULL SdfLayerRefPtr in error cases we can identify ourselves.  In general, exceptions will be turned into `TF_RUNTIME_ERROR`, which clients can handle on an opt-in basis, and which turn into python exceptions if not handled in C++ client code.
