### ISSUE TITLE
Documentation improvement for blendshapes UsdSkel

### ISSUE THREAD

**Issue by alankent** [PixarAnimationStudios/USD#2538]
### Description of Issue
I think there is a minor error in the documentation describing blendshapes for skeletons. The text currently says

```
From the example above, shape </Mesh/Foo> is using shapes ['B’, 'A'] (in that order).
```

Maybe it meant to say `mesh </Mesh>` instead of `shape </Mesh/Foo>`. Foo does not reference A and B - "B" is bound to "Foo" and "A" is bound to "Bar" via the `skel:blendShapes` and `skel:blendShapeTargets` attributes of `/Mesh` in the example above.

https://github.com/PixarAnimationStudios/OpenUSD/blob/b53573ea2a6b29bc4a6b129f604bbb342c35df5c/pxr/usd/usdSkel/doxygen/schemas.dox#L731C1-L732C5

### Steps to Reproduce
1. Go to https://openusd.org/dev/api/_usd_skel__schemas.html#UsdSkel_BindingAPI_BlendShapes
2. Look for the text `From the example above, shape </Mesh/Foo> is using shapes ['B’, 'A'] (in that order). `
3. Compare it to the example above. The first sentence does not make sense to me (the rest of the paragraph is fine).

### System Information (OS, Hardware)
N/A

### Package Versions
N/A

### Build Flags
N/A.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8498
