### ISSUE TITLE
Building with the embree plugin and strict mode enabled breaks the build

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#254]
### Description of Issue
When the new embree plugin is enabled, and strict build mode is turned on, the build breaks. Warnings are interpreted as errors.

Something like this
/luma/soft/rez/packages/embree/2.16.4/platform-linux/include/embree2/rtcore_geometry.h:30:0: error: "RTC_MAX_USER_VERTEX_BUFFERS" redefined [-Werror]
 #define RTC_MAX_USER_VERTEX_BUFFERS 16
 ^
In file included from /ssd/rez-build/usd/dev/src/pxr/imaging/plugin/hdEmbree/mesh.h:33:0,
                 from /ssd/rez-build/usd/dev/src/pxr/imaging/plugin/hdEmbree/mesh.cpp:24:
/ssd/rez-build/usd/dev/src/pxr/imaging/plugin/hdEmbree/meshSamplers.h:29:0:0: note: this is the location of the previous definition
 #define RTC_MAX_USER_VERTEX_BUFFERS 2

Based on the comments, the redefinition of RTC_MAX_USER_VERTEX_BUFFERS could either be removed, and the minimum required embree version increased to a version where it's properly defined, or we could change FindEmbree.cmake to grab the version number, and using that information enable / disable this define.

### Steps to Reproduce
1. Build with -D PXR_STRICT_BUILD_MODE=TRUE and -D PXR_BUILD_EMBREE_PLUGIN=TRUE

### System Information (OS, Hardware)
Centos 7.

### Package Versions
gcc-4.8.3, latest commit from dev, embree-2.16.4.

**Comment by jtran56** [comment]
Filed as internal issue #149264.
