### ISSUE TITLE
Build script is not discussed in BUILDING.md

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#255]
### Description of Issue
The new build script is not discussed in BUILDING.md:
https://github.com/PixarAnimationStudios/USD/blob/master/BUILDING.md

**Comment by jtran56** [comment]
Filed as internal issue #149442.

**Comment by meshula** [comment]
Although the use of the build script is detailed on the main readme,

https://github.com/PixarAnimationStudios/USD/#3-run-the-script

There is some fussiness on the installation of the prerequisites on Windows in particular. Python set up is a bit fussy, and there are a few extra things that should be installed, such as pyopengl. Path variable set up also requires a bit of attention. Perhaps some subset of the information here could make it to BUILDING.md.

https://github.com/vfxpro99/usd-build-club/wiki/USD-on-Windows
