### ISSUE TITLE
Missing HD_API on some functions

### ISSUE THREAD

**Issue by lanierd-adsk** [PixarAnimationStudios/USD#2569]
### Description of Issue
Following the discussion on https://groups.google.com/g/usd-interest/c/uHxU9MrFgYg
There are some functions from classes not exported. Please see the thread above.

### Steps to Reproduce
1. There is a code snippet to use to validate this.

### System Information (OS, Hardware)
Any

### Package Versions
Any

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8564

**Comment by tcauchois** [comment]
Hi David,

I'm trying to recapture what we were talking about with regards to linking.  HdRetainedSceneIndex has had HD_API (external linkage on windows) since 23.05.  Were there any other classes you noticed it missing on?  Thanks!

**Comment by lanierd-adsk** [comment]
Hi Tom,
I know it was not possible to create a custom HdTask because an HD_API was missing I think, but that was in 22.x,. I haven't retried with newer versions.
Thank you.
Regards,
David

**Comment by tcauchois** [comment]
Hi David,

Cross-referencing things, I think we've API-tagged everything you need, so I'm going to close this out.  But if you find anything we missed, please let us know!

Thanks,
Tom
