### ISSUE TITLE
Storm exhibits incorrect interpretation of PointInstancer instances motion

### ISSUE THREAD

**Issue by jjeziorski** [PixarAnimationStudios/USD#2571]
### Description of Issue

Motion of PointInstancer instances in Storm delegate is inconsistent with one outlined here: https://openusd.org/dev/api/usd_geom_page_front.html#UsdGeom_VelocityInterpolation
and computed with `UsdGeomPointInstancer::ComputeInstanceTransformsAtTimes`

### Steps to Reproduce
1. Open [point_instancer_motion_types.usda.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/12288954/point_instancer_motion_types.usda.txt) in `usdView` with Storm delegate and inspect sub frame samples e.g. step = 0.1

This is what we get:
![hydra](https://github.com/PixarAnimationStudios/OpenUSD/assets/715638/450c99ca-f361-49c4-8370-37671cfa91b2)

When expected something consistent with:
<img width="507" alt="render" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/715638/871c8483-2c25-43aa-9552-60ac99f44ab3">

### System Information (OS, Hardware)

CentOS-7.8

### Package Versions

This was tested with USD-21.8 and 23.5

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8566
