### ISSUE TITLE
Windows monolithic build fails on OIIO

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#258]
### Description of Issue
C:\src\usd\USD-v0.8>python build_scripts\build_usd.py --alembic --embree --build-monolithic build_monolithic

Building with settings:
  USD source directory          C:\src\usd\USD-v0.8
  USD install directory         C:\src\usd\USD-v0.8\build_monolithic
  3rd-party source directory    C:\src\usd\USD-v0.8\build_monolithic\src
  3rd-party install directory   C:\src\usd\USD-v0.8\build_monolithic
  Build directory               C:\src\usd\USD-v0.8\build_monolithic\build

  Building                      Monolithic shared library
    Imaging                     On
      Ptex support:             Off
    UsdImaging                  On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              On
      HDF5 support:             Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off

    Dependencies                zlib, boost, TBB, OpenEXR, Alembic, JPEG, TIFF, PNG, GLEW, OpenImageIO, OpenSubdiv

STATUS: Installing zlib...
STATUS: Installing boost...
STATUS: Installing TBB...
STATUS: Installing OpenEXR...
STATUS: Installing Alembic...
STATUS: Installing JPEG...
STATUS: Installing TIFF...
STATUS: Installing PNG...
STATUS: Installing GLEW...
STATUS: Installing OpenImageIO...
ERROR: Failed to download https://github.com/OpenImageIO/oiio/archive/Release-1.7.14.zip: <urlopen error [Errno 11001] getaddrinfo failed>

C:\src\usd\USD-v0.8>python build_scripts\build_usd.py --alembic --embree --build-monolithic build_monolithic

Building with settings:
  USD source directory          C:\src\usd\USD-v0.8
  USD install directory         C:\src\usd\USD-v0.8\build_monolithic
  3rd-party source directory    C:\src\usd\USD-v0.8\build_monolithic\src
  3rd-party install directory   C:\src\usd\USD-v0.8\build_monolithic
  Build directory               C:\src\usd\USD-v0.8\build_monolithic\build

  Building                      Monolithic shared library
    Imaging                     On
      Ptex support:             Off
    UsdImaging                  On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              On
      HDF5 support:             Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off

    Dependencies                OpenImageIO, OpenSubdiv

STATUS: Installing OpenImageIO...
ERROR: Failed to extract archive Release-1.7.14.zip: unrecognized archive file type

**Comment by jcowles** [comment]
Seems like this may have been a network hiccup, however once the download fails, it's unclear how to proceed, since it will not attempt to re-download the dependency after failure.

By reading the build script, I found "--force", which seems to be working now.

In a perfect world, after download failure, it would clear out all associated files and leave the tree in a clean state.

**Comment by jcowles** [comment]
Also, the loop of 5 download attempts in the build script is curious -- why is it so prone to download failure? Was it failing even during development?

**Comment by sunyab** [comment]
Thanks @jcowles, cleaning out files on download or extraction failure seems like a good idea to me. During development, it was more useful to see what was left behind.

The download retries were an attempt to work around SSL certificate validation errors that would sometimes happen when trying to download dependencies (generally from sourceforge -- something to do with their redirects?). It was infrequent but annoying, and I couldn't find a good 'real' fix for it so I just put that retry loop in.

**Comment by jcowles** [comment]
Ah, sourceforge! If it happens frequently on more than just sourceforge, I would be suspicious that maybe the problem is actually local somehow.

I would be fine with partial state too actually, as long as it's easy to pick up where you left off, rather than having to know to use "--force".

**Comment by jtran56** [comment]
Filed as internal issue #149465.
