### ISSUE TITLE
Windows: Build script assumes Boost is in the environment

### ISSUE THREAD

**Issue by krzykli** [PixarAnimationStudios/USD#259]
### Description of Issue
Running the build script will fail unless you manually set your BOOST_ROOT.

### Steps to Reproduce
1. In a clean environment run `python build_scripts\build_usd.py "C:\Program Files\USD"`
2. Wait couple of minutes and you'll get the following error when compiling OIIO:
```
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:134 (find_package)
  CMakeLists.txt:363 (include)
```

### System Information (OS, Hardware)
Windows 7

### Version
USD 0.8.0

**Comment by jtran56** [comment]
Filed as internal issue #149466.

**Comment by sunyab** [comment]
Hi @krzykli, I haven't been able to reproduce this issue yet, even in a clean environment. What versions of MSVC and cmake are you using? If you're using MSVC 2017, I recently discovered that cmake 3.8 or later is required to avoid an issue where cmake looks for the boost DLLs with the wrong names.

**Comment by krzykli** [comment]
Thanks @sunyab. I'm compiling using Visual Studio 2015 and CMake 3.1.1. If I find time I'll do some additional testing and get back to you, otherwise if no one else complains about it then feel free to close the ticket.

**Comment by flt35** [comment]
Hi @sunyab and @krzykli. I encounter the same exact issue with dev branch, VS2015, CMake 3.1.1 which installed properly boost 1.61...
My log is exactly the same than the one posted in the description above...
I will try the workaround to set BOOST env vars externally, but out of the box, it should work, no?
Thanks.

**Comment by flt35** [comment]
I had to patch "build_usd.py" adding those lines in both methods: _InstallOpenImageIO_ and _InstallUSD_

```
   # First line may be useless?
   extraArgs.append('-DBoost_NO_SYSTEM_PATHS=ON')
   extraArgs.append('-DBOOST_INCLUDEDIR="C:/Program Files/USD/include/boost-1_61"')
   extraArgs.append('-DBOOST_LIBRARYDIR="C:/Program Files/USD/lib"')
```

**Comment by flt35** [comment]
I replaced this patch by this one to take into account install dir:

```
        if Windows():
            extraArgs.append('-DBoost_NO_SYSTEM_PATHS=ON')
            extraArgs.append('-DBOOST_INCLUDEDIR="{instDir}/include/boost-1_61"'
                             .format(instDir=context.instDir))
            extraArgs.append('-DBOOST_LIBRARYDIR="{instDir}/lib"'
                             .format(instDir=context.instDir))
```

**Comment by sunyab** [comment]
Going to close this old issue out. This situation should be much improved -- there were a fair number of changes in USD 20.05 to ensure the correct version of boost would be found. This includes setting Boost_NO_SYSTEM_PATHS and Boost_NO_BOOST_CMAKE in build_usd.py.

Also, note that CMake 3.14+ is required on Windows. See dd68031 for more details.
