### ISSUE TITLE
usdview: warn when trying to use an EXR texture and build doesn't support it

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2591]
### Description of Issue

I just spent a while debugging DomeLight issues, only to realize that no EXR file I was trying to use as DomeLight texture worked at all, they just resulted in black. HDR files work fine. My guess is that I've built USD without OIIO enabled, but it would have been great to get some sort of warning or hint that this won't work.

### Steps to Reproduce
1. Build USD without OIIO (the default?)
2. Open any USD file with an EXR texture referenced, e.g. in a DomeLight
3. Get a black result (e.g. from a metallic sphere)

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8590

**Comment by meshula** [comment]
Hi Felix, the goal is for OpenEXR files to be always available, no matter your plugin choices, as of 23.11.

**Comment by FlorianZ** [comment]
This should no longer be an issue as of 23.11, but please feel free to reopen if your experience is different.
