### ISSUE TITLE
Build script dies on OpenSubdiv/GLFW on Ubuntu

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#261]
### Description of Issue
Building on Ubuntu

### Steps to Reproduce
0. mkdir build
1. python build_scripts/build_usd.py build

Error:
CMake Error at cmake/FindGLFW.cmake:146 (message):
  Xrandr library not found - required for GLFW
Call Stack (most recent call first):
  CMakeLists.txt:316 (find_package)

### System Information (OS, Hardware)
Ubuntu 13

**Comment by jcowles** [comment]
Oh! This is xrandar, not glfw

**Comment by sunyab** [comment]
The GLFW dependency is a known issue -- if GLFW isn't installed on your system, you'll eventually run into issues with the OpenSubdiv build. I'm thinking I'll need to add GLFW to the build script, at least until https://github.com/PixarAnimationStudios/OpenSubdiv/issues/903 is resolved.

**Comment by jcowles** [comment]
Ah, yeah -- I fixed the xrandr dependency, did a clean build and it still failed:

-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR GLFW_LIBRARIES) (Required is at least version "3.0.0")
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find GLEW (missing: GLEW_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGLEW.cmake:124 (find_package_handle_standard_args)
  CMakeLists.txt:329 (find_package)

**Comment by jcowles** [comment]
Any workaround? Just install GLFW?

**Comment by sunyab** [comment]
Yeah, unfortunately that's the only workaround at the moment.

**Comment by jcowles** [comment]
FYI, I had to install both GLFW and GLEW.

For anyone else hitting this:
GLFW, I just cloned from GitHub and did the CMake dance (cmake, make, make install).
GLEW, I downloaded the source zip and ran make, make install.

**Comment by jtran56** [comment]
Filed as internal issue #149508.

**Comment by dboogert** [comment]
On my Ubuntu based distro running build_usd.py resulted in  glew being installed to *lib64* instead of *lib*

**Comment by Mockermockery** [comment]
installing Xrandr is not trivial how did you resolve the issue.
I am having the same issue using ubuntu.

**Comment by meshula** [comment]
to build glfw on ubuntu, I first had to:

```sh
sudo apt install libxrandr-dev
sudo apt install libxinerama-dev
sudo apt install libxcursor-dev
```

**Comment by drwave** [comment]
Hey folks. So this has moved me along, but now the configure is dying with:

-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
CMake Error at cmake/FindGLFW.cmake:174 (message):
  Xi library not found - required for GLFW
Call Stack (most recent call first):
  CMakeLists.txt:341 (find_package)

I've got (via apt) libglfw3 and libglfw-dev, so I was hoping I would be clear. 

Thanks for any tips.

**Comment by drwave** [comment]
sorry, forgot to mention: when I tried to install glfw from github myself, I got:

-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
CMake Error at CMakeLists.txt:230 (message):
  The XInput headers were not found

**Comment by meshula** [comment]
not at a computer atm, but I believe

sudo apt install libxi-dev

afaicr, libXi is the last of the weird build dependencies.

will get you past this. I wish installing the x11 dev libraries wasn't this random bag of mixed nuts! I'm not aware of an umbrella install that gets all the pieces in one go. Would be happy to learn of one, if anyone knows.

**Comment by drwave** [comment]
well, that got me further, now, even though I've installed GLEW via apt, it's complaining it can't find it.

-- Found GLFW: /usr/local/include (found suitable version "3.4.0", minimum required is "3.0.0") 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GLEW (missing: GLEW_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGLEW.cmake:124 (find_package_handle_standard_args)
  CMakeLists.txt:329 (find_package)

**Comment by sunyab** [comment]
@drwave Are you running your builds manually or are you using build_usd.py? And is the error coming from building USD itself, or from building OpenSubdiv or one of the other dependencies? My wild guess is that the GLEW .so is being installed into lib64 instead of lib, and that's causing issues.

**Comment by drwave** [comment]
I (re?)installed glew with apt, ran the build script again, and it all worked. Thanks for all help, everyone. Not sure I have a totally repeatable set of steps to build on a fresh machine, but at least for this machine I'm up and working, which is great.

**Comment by virtualritz** [comment]
I have the same issue on Ubuntu 22.04 trying to build 3.5.0. What I do not get is that the [deps section of the OSD CMake docs](https://graphics.pixar.com/opensubdiv/docs/cmake_build.html#step-1-dependencies) says:

> **Optional**
> * [GLFW](https://github.com/glfw/glfw) (required for standalone examples and some regression tests)

I run `cmake` with `-DNO_EXAMPLES=1` and `-DNO_REGRESSION=1` which would make me think GLFW would *not* be required as a dependency any more. Are the OSD docs outdated/wrong here or is the OSD `cmake` config buggy?

Specificyally, this is the relevant section from my build faling:
```
  running: cd "/home/moritz/code/crates/opensubdiv-petite/target/debug/build/opensubdiv-petite-sys-0eb04167d86efd39/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/moritz/code/crates/opensubdiv-petite/opensubdiv-petite-sys/OpenSubdiv" "-DNO_EXAMPLES=1" "-DNO_TUTORIALS=1" "-DNO_REGRESSION=1" "-DNO_PTEX=1" "-DNO_DOC=1" "-DNO_OPENCL=1" "-DNO_CLEW=1" "-DNO_TBB=1" "-DNO_CUDA=1" "-DNO_OMP=1" "-DNO_METAL=1" "-DCMAKE_INSTALL_PREFIX=/home/moritz/code/crates/opensubdiv-petite/target/debug/build/opensubdiv-petite-sys-0eb04167d86efd39/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Compiling OpenSubdiv version v3_5_0
  -- Using cmake version 3.22.1
  -- Configuring incomplete, errors occurred!
  See also "/home/moritz/code/crates/opensubdiv-petite/target/debug/build/opensubdiv-petite-sys-0eb04167d86efd39/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at cmake/FindGLFW.cmake:162 (message):
    xf86vmode library not found - required for GLFW
  Call Stack (most recent call first):
    CMakeLists.txt:359 (find_package)
```

**Comment by virtualritz** [comment]
I found the `NO_GLFW` flag which is undocumented though (see #2302).

**Comment by virtualritz** [comment]
In any case, if the docs are right `-DNO_EXAMPLES=1` and `-DNO_REGRESSION=1` should imply `-DNO_GLFW=1`, I guess.
