### ISSUE TITLE
Storm should have a broken shader visual representation

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2613]
Now that USD has growing support for MaterialX (awesome!), it's more likely for folks to encounter a broken shader state.
Unfortunately, it seems that when a shader compilation error happens, Storm defaults to a grey shaded shader.

This isn't always immediately obvious that it's a broken shader, unless people look at stderr. Sometimes these errors are on very small parts of an object that can be missed.

It would be great if Storm had a fallback shader that was obnoxiously obvious that a shader compilation had failed. In RealityKit this is often a striped magenta shader, Maya does a very vibrant green. 

Something along those lines would be valuable for quickly noticing that something is broken.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8613

**Comment by tcauchois** [comment]
Experience tells me that this is something that the application will want to be able to customize.  My first inclination is to define an "error" shader in hydra that gets used if the correct material fails to compile; and then if the error shader fails to compile, we draw grey or don't draw.  But yeah, this is a fantastic suggestion!

Do you have a sense of when we would need this?

**Comment by dgovil** [comment]
No real "need by date". It was more of a thing that was coming up as we introduced MaterialX support and of course that means people will author potentially broken shaders at a higher rate.
