### ISSUE TITLE
GetAttr inconsistently returning by copy or by const reference

### ISSUE THREAD

**Issue by ShaddyDC** [PixarAnimationStudios/USD#2617]
### Description of Issue

I'm working on wrapping some of OpenUSD with Rust, and I ran into the issue that some types return UsdAttribute either by const reference or by value.
Specifically, [UsdGeomPrimvar](https://openusd.org/dev/api/class_usd_geom_primvar.html#abac0d0d04c1631b1a53fe29554cc3a18) has the signature `UsdAttribute const & UsdGeomPrimvar::GetAttr()const`, as does [UsdShadeInput](https://openusd.org/dev/api/class_usd_shade_input.html#a6a14df45b2b781b98301c6e6cf204547), but [UsdShadeOutput](https://openusd.org/dev/api/class_usd_shade_output.html#af636996ac4631cd1ee6f37a1e64eeb74) has `UsdAttribute UsdShadeOutput::GetAttr() const`.
Unless that causes other issues, it would be convenient for me if they could all return a constant reference, or if necessary, by value.
Or is there maybe a reason for this I've missed?

I have not checked where else this may be applied inconsistently.

### Steps to Reproduce
1. NA

### System Information (OS, Hardware)
NA

### Package Versions

23.08

### Build Flags
NA

**Comment by spiffmon** [comment]
Sounds unintentional to me.

**Comment by ShaddyDC** [comment]
Here is a more thorough list then:
```
> rg 'UsdAttribute( const)? ?& ?GetAttr'
pxr/usd/usdUtils/sparseValueWriter.h
139:    const UsdAttribute & GetAttr() const {

pxr/usd/usdGeom/xformOp.h
331:    UsdAttribute const &GetAttr() const { 

pxr/usd/usdGeom/primvar.h
400:    UsdAttribute const &GetAttr() const { return _attr; }

pxr/usd/usdGeom/constraintTarget.h
111:    UsdAttribute const &GetAttr() const { return _attr; }

pxr/usd/usdShade/input.h
229:    const UsdAttribute &GetAttr() const { return _attr; }

pxr/usd/usd/attributeQuery.h
124:    const UsdAttribute& GetAttribute() const;

pxr/usd/usdSkel/inbetweenShape.h
128:    UsdAttribute const &GetAttr() const { return _attr; }
```

```
> rg 'UsdAttribute( const)? ?GetAttr'
pxr/usd/usd/prim.h
1569:    USD_API UsdAttribute GetAttributeAtPath(const SdfPath& path) const;
1709:    UsdAttribute GetAttribute(const TfToken& attrName) const;

pxr/usd/usd/stage.h
813:    UsdAttribute GetAttributeAtPath(const SdfPath &path) const;

pxr/usd/usdShade/output.h
213:    UsdAttribute GetAttr() const { return _attr; }
```

This makes me think like that instance may be the only `GetAttr` call then, though I'm not sure what the preffered way for the others would be.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8617

**Comment by spiffmon** [comment]
stage.h and prim.h must return by value, because the objects are not retained by UsdStage or UsdPrim.  SO it does look like output.h is the only site that can and should change.
