### ISSUE TITLE
Basic UsdSkel doesn't animate in usdview-23.08

### ISSUE THREAD

**Issue by mati-nvidia** [PixarAnimationStudios/USD#2621]
### Description of Issue
usdview-23.08 viewport does not show the animation from this basic UsdSkel example: https://openusd.org/release/api/_usd_skel__schema_overview.html

### Steps to Reproduce
1. Save the USDA from *Skinning an Arm* example: https://openusd.org/release/api/_usd_skel__schema_overview.html
2. Open the USDA file with usdview (23.08)
3. Press play or scrub through the timeline
4. RESULT: The interpolated values for `/Model/Skel/Anim.rotations` are displayed in the Properties window, but it does not animate in the viewport.

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD-23.08, Python 3.10

### Build Flags
Default

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8624

**Comment by spiffmon** [comment]
Oh Shazam, @mati-nvidia - good find, and reinforcement that we need to find time to turn all of our doc examples into unit tests.  It looks like when we made the changes to "strictify" the application of SkelBindingAPI, the bindings discovery process lost the ability to find animation bindings inside/under Skeleton prims.  If I simply move the `skel:animation` binding up onto `</Model>` then all works as expected.  We'll get this fixed for 23.11... give a shout if this is a pattern that's being used commonly - looks like _we_ do not use it anywhere except in this example!

**Comment by mati-nvidia** [comment]
I checked around and, for example, currently our Blender exporter sets the `skel:animationSource` on the Skeleton prim, but also correctly applies the `SkelBindingAPI` on the Skeleton prim so it plays fine in usdview.

@spiffmon is there some code change you were planning on making for this issue? If it's just a matter of fixing the example by moving `skel:animationSource` to the SkelRoot, I can include that in some other doc improvements I'm working on.

**Comment by spiffmon** [comment]
Oh hah!  I *totally* missed that the Skeleton was lacking the schema
application.. but sure enough:
a) usdchecker complains about it - yay!
b) adding it fixes the example.

Sure, @mati-nvidia, if you were already making a PR, this would be an
appreciated fix.

--spiff

**Comment by tallytalwar** [comment]
usdfixbrokenpixarschemas should also fix the application of UsdSkelBindingAPI: https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usd/bin/usdfixbrokenpixarschemas/usdfixbrokenpixarschemas.py#L51
