### ISSUE TITLE
Warning C4003

### ISSUE THREAD

**Issue by erikaharrison-adsk** [PixarAnimationStudios/USD#2624]
### Description of Issue

In a recent pull from dev, we are now see a number of warnings - C4003 - when compiling with Visual Studios on Windows. Eg:

1>D:/Source/usd-adsk3/pxr/imaging/glf/texture.h(51,1): warning C4003: not enough arguments for function-like macro invocation '_TF_PP_IS_PARENS'
1>D:/Source/usd-adsk3/pxr/imaging/glf/texture.h(51,1): warning C4003: not enough arguments for function-like macro invocation 'BOOST_PP_SEQ_DETAIL_IS_NOT_EMPTY'
1>D:/Source/usd-adsk3/pxr/imaging/glf/texture.h(51,1): warning C4003: not enough arguments for function-like macro invocation 'BOOST_PP_SEQ_DETAIL_EMPTY_SIZE'
1>D:/Source/usd-adsk3/pxr/imaging/glf/texture.h(51,1): warning C4003: not enough arguments for function-like macro invocation 'BOOST_PP_TUPLE_SIZE'

I'm seeing it in texture.h above, but also imaging/hd/tokens.h, usd/sdf/tokens.h, imagining/pxOsd/tokens.h, etc. Generally where the TF_DECLARE_PUBLIC_TOKENS and TF_DEFINE_PUBLIC_TOKENS macros are being called. 

Implementation Notes:
I've a hunch it might be related to the recent preprocessorUtils.h / preprocessorUtilsLite.h changes (eg. https://github.com/PixarAnimationStudios/OpenUSD/pull/2584, https://github.com/PixarAnimationStudios/OpenUSD/pull/2535 ?  and others) but I haven't rolled back to confirm. For base\tf\staticTokens.h, I suspect because we're no longer including preprocessorUtil.h, and therefore no longer silencing these warnings with ARCH_PRAGMA_MACRO_TOO_FEW_ARGUMENTS they're cropping up. Not sure about the sdf/fileFormat.h, sdf/schema.h, sdf/abstractData.h as I haven't had time to dig yet.

cc @nvmkuruc 

### Steps to Reproduce
1. Compile USD using msvc 

### System Information (OS, Hardware)

* Windows, Visual Studio 19

**Comment by sunyab** [comment]
Thanks for the report @erikaharrison-adsk, @nvmkuruc noticed this as well and we've checked in a fix for this internally.  It'll be part of the next dev update which should happen within the next few days.

Just to confirm, these warnings are indeed due to us no longer include preprocessorUtil.h in a number of places. Our fix disables the C4003 warning for the entire build rather than scatter the pragma in all of those locations.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8627

**Comment by hodoulp** [comment]
If I understand correctly your proposal, `Autodesk` (and others) tools/libraries will still have compilation warnings triggered by the `USD` include files. Ideally, the fix should be to not trigger any warning (i.e., fix the code) when the `USD` include files are used outside the `USD` project.

**Comment by sunyab** [comment]
We're in the process of removing the use of boost's preprocessor library which is where many of these warnings originate. I'm hopeful that these warnings will go away (or at least be greatly reduced) once that's completed, at which point it'll be easier to figure out a code fix as you suggest.

**Comment by nvmkuruc** [comment]
We could add `ARCH_PRAGMA_MACRO_TOO_FEW_ARGUMENTS` to `preprocessorUtilsLite.h` since it's now included in the places the suppressing `preprocessorUtils.h` was previously.

**Comment by erikaharrison-adsk** [comment]
For notes, this is the commit related to the Pixar internal fix: https://github.com/PixarAnimationStudios/OpenUSD/commit/fbf578ac8a8719ed09c1276f4e1cd668a4e214ea

**Comment by spiffmon** [comment]
How does this look in 24.03, @erikaharrison-adsk ?

**Comment by FlorianZ** [comment]
We assume this is fixed so closing this for now. Please, let us know if this is wrong and in that case feel free to reopen. Thank you!

**Comment by GreatWhite2023** [comment]
I can still find this warning when using USD 24.03 in Visual Studios, for example:
Warning	C4003	not enough arguments for function-like macro invocation '_TF_PP_SEQ_PARTITION_HEAD'	inc\pxr\usd\sdf\types.h	262
Warning	C4003	not enough arguments for function-like macro invocation '_TF_PP_IS_PARENS'	inc\pxr\usd\sdf\types.h	433
Warning	C4003	not enough arguments for function-like macro invocation 'BOOST_PP_SEQ_DETAIL_IS_NOT_EMPTY' inc\pxr\usd\sdf\types.h	433	
Warning	C4003	not enough arguments for function-like macro invocation 'BOOST_PP_SEQ_DETAIL_EMPTY_SIZE' inc\pxr\usd\sdf\types.h	433

**Comment by robp-sidefx** [comment]
We're just discovering this now too (in the context of custom code using USD 24.03), sorry :(

**Comment by sunyab** [comment]
The C4003 warnings are greatly reduced in the dev branch as I'd hoped, and it now looks like there's a simple fix we can put in place that should ensure this warning doesn't show up in downstream projects. I'm testing that now and will hopefully get this in for the upcoming 24.05 release.

**Comment by robp-sidefx** [comment]
Okay, thanks ... if you can cite this issue with those commits, it'd be great for us to track the progress.
