### ISSUE TITLE
UsdImagingAdapterRegistry error using usdrecord

### ISSUE THREAD

**Issue by adro79** [PixarAnimationStudios/USD#2627]
### Description of Issue

I'm getting this error whenever I use usdrecord. Building with lines 133-140 from [adapterRegistry.cpp](https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usdImaging/usdImaging/adapterRegistry.cpp) commented/deleted works. I haven't tried it with older versions of USD.

```
Traceback (most recent call last):
  File "/usr/share/usd/bin/usdrecord", line 216, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/usd/bin/usdrecord", line 190, in main
    frameRecorder = UsdAppUtils.FrameRecorder(rendererPluginId, args.gpuEnabled)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pxr.Tf.ErrorException:
	Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 134 in file /mnt/data/Applications/AUR/usd/src/OpenUSD/pxr/usdImaging/usdImaging/adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'GeometryLight' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (GeometryLightAdapter) will be used. The previously discovered adapter (UsdImagingGeometryLightAdapter) will be discarded.'
```

### Steps to Reproduce
1. Build USD 23.08 on Arch Linux (AUR package)
2. Open your terminal
3. Type `usdrecord --renderer GL file.usd file.png`

### System Information (OS, Hardware)

- Arch Linux
- Linux 6.4.12
- AMD CPU
- Nvidia GPU

### Package Versions

USD 23.08

### Build Flags

    -DCMAKE_INSTALL_PREFIX:PATH=/usr/share/usd
    -DCMAKE_PREFIX_PATH:PATH=/usr/share/usd
    -DPXR_BUILD_TESTS=OFF
    -DPXR_BUILD_DOCUMENTATION=OFF
    -DTBB_ROOT=/opt/tbb2019
    -DBoost_NO_BOOST_CMAKE=ON
    -DBUILD_SHARED_LIBS=ON
    -DPXR_MALLOC_LIBRARY:path=/usr/lib/libjemalloc.so
    -DPYSIDEUICBINARY=/usr/bin/uic
    -DPXR_VALIDATE_GENERATED_CODE=ON

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8629

**Comment by wangluo2028** [comment]
is it solved, I've also encountered this problem.
