### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'CreatePrimvar'

### ISSUE THREAD

**Issue by julienbfabre** [PixarAnimationStudios/USD#2628]
I'm trying to run the Apple command line tool `usdzconvert` (https://developer.apple.com/augmented-reality/tools/) on Ubuntu to convert GLBs to USDZs.

I have two different VPSs, one with Ubuntu 18 and one with 20. 
I've compiled USD from source as instructed as well as all the dependencies, everything went fine, but running `usdzconvert` only works on Ubuntu 18, on 20 i get the following error:

```
Traceback (most recent call last):
  File "./usdzconvert", line 859, in <module>
    errorValue = main()
  File "./usdzconvert", line 854, in main
    return tryProcess(sys.argv[1:])
  File "./usdzconvert", line 809, in tryProcess
    ret = process(argumentList)
  File "./usdzconvert", line 649, in process
    usdStage = usdStageWithGlTF_module.usdStageWithGlTF(srcPath, tmpPath, legacyModifier, openParameters)
  File "/home/julien/usdzconvert/usdStageWithGlTF.py", line 1529, in usdStageWithGlTF
    return converter.makeUsdStage()
  File "/home/julien/usdzconvert/usdStageWithGlTF.py", line 1515, in makeUsdStage
    self.processSkinnedMeshes()
  File "/home/julien/usdzconvert/usdStageWithGlTF.py", line 1481, in processSkinnedMeshes
    usdGeom = self.processMesh(nodeIdx, newPath, skeleton)
  File "/home/julien/usdzconvert/usdStageWithGlTF.py", line 1316, in processMesh
    usdGeom = self.processPrimitive(nodeIdx, gltfPrimitives[0], path, skinIdx, underSkeleton)
  File "/home/julien/usdzconvert/usdStageWithGlTF.py", line 1142, in processPrimitive
    normalPrimvar = usdGeom.CreatePrimvar('normals', Sdf.ValueTypeNames.Normal3fArray, UsdGeom.Tokens.vertex)
AttributeError: 'Mesh' object has no attribute 'CreatePrimvar'
```

I have tried to mirror dependencies on both servers as best as i could so they both use the same Python version (3.6.9), the same input file, what could be causing this error? 
i've been debugging this thing for ages and i can't figure out why it works on one server and not the other, i've even tried to copy the compiled USD from the working server to the non working server just in case and still i get the same result.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8630

**Comment by julienbfabre** [comment]
> Filed as internal issue #USD-8630

Hi @jesschimein , does this mean that this is a bug in the lib and i should wait for a new version that will fix it or is there something i can do on my side to fix this?

**Comment by dgovil** [comment]
@julienbfabre pixar track bug reports internally , and post their tracking number here. It doesn't mean much for whether it's classified as a bug or not and in general we can ignore the tracking numbers as external people. 

As for your main issue, what version of USD are you using? The conversion tools were written for an older version of USD and I believe the primvars api has changed since then. I imagine the discrepancy you're seeing is that your instances are running different versions of the library.

**Comment by julienbfabre** [comment]
> @julienbfabre pixar track bug reports internally , and post their tracking number here. It doesn't mean much for whether it's classified as a bug or not and in general we can ignore the tracking numbers as external people.
> 
> As for your main issue, what version of USD are you using? The conversion tools were written for an older version of USD and I believe the primvars api has changed since then. I imagine the discrepancy you're seeing is that your instances are running different versions of the library.

@dgovil how can i check the version? i''ve tried even copying the compiled lib from one server to the other and i was still having the issue, but i'd be curious to check the version and make sure i recompile the exact same one to be sure.

**Comment by julienbfabre** [comment]
ok i found the version in the `pxrConfig.cmake` file, `0.22.5 (2205)`, i will try to recompile the same version on ubuntu 20 and report my results here.

**Comment by dgovil** [comment]
I would also encourage trying to make sure you don't have USD installed via PyPi either. You may accidentally be picking up a version you didn't compile.

To check, I'd recommend adding this to the top of the usdzconvert script:

```
from pxr import Usd
print("Sourcing USD from: ", Usd.__version__)
print("USD version is: ", Usd.GetVersion())
```

**Comment by dgovil** [comment]
Also just to help you workaround this issue in newer versions of USD.
You can replace uses of 

`normalPrimvar = usdGeom.CreatePrimvar('normals', Sdf.ValueTypeNames.Normal3fArray, UsdGeom.Tokens.vertex)`

with the following 

```
primvar_api = UsdGeom.PrimvarsAPI(usdGeom.GetPrim())
primvar_api.CreatePrimvar("normals", Sdf.ValueTypeNames.Normal3fArray, UsdGeom.Tokens.vertex)
```

The `CreatePrimvar` api was moved from UsdGeomImageable (which all meshes inherit from) to its own API class in USD USD 19.03, and the old deprecated methods were removed in USD 22.8

That information, combined with the difference in behaviour between your instances, makes me think you're resolving different USD versions on one of them accidentally.

**Comment by julienbfabre** [comment]
Yep that was it, compiling the exact same version fixed the issues! 
i guess all the versions i had tried on the newer server were after 22.8, thanks for pointing me int he right direction @dgovil !

**Comment by dgovil** [comment]
Happy to help. Glad that got you unblocked.

**Comment by mudworker** [comment]
> Also just to help you workaround this issue in newer versions of USD. You can replace uses of
> 
> `normalPrimvar = usdGeom.CreatePrimvar('normals', Sdf.ValueTypeNames.Normal3fArray, UsdGeom.Tokens.vertex)`
> 
> with the following
> 
> ```
> primvar_api = UsdGeom.PrimvarsAPI(usdGeom.GetPrim())
> primvar_api.CreatePrimvar("normals", Sdf.ValueTypeNames.Normal3fArray, UsdGeom.Tokens.vertex)
> ```
> 
> The `CreatePrimvar` api was moved from UsdGeomImageable (which all meshes inherit from) to its own API class in USD USD 19.03, and the old deprecated methods were removed in USD 22.8
> 
> That information, combined with the difference in behaviour between your instances, makes me think you're resolving different USD versions on one of them accidentally.

I encountered the same problem, how can I modify the `.Set` method (I commented it out directly, and the texture of the exported usdz file was messed up and `primvar_api` does not have a Set method)

![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/1ff6f276-d6d3-4fed-b927-170c7778fad4)

**Comment by mudworker** [comment]
@dgovil 
Hello, I tried to modify the code using the method you provided, and usdzconvert can run normally. 
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/3ed628b0-ff2a-4c0f-8253-a06498b59dfe)

However, there is a problem with the texture of the converted usdz file. It should be caused by the `.set` method. If I use the following writing method, an error will be reported. 
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/69da8c5b-a21c-4130-8590-45a1dde2ecd9)

![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/2236dd08-2203-4f02-97dc-5a88aff6a700)

Could you tell me how to modify the `.set` method in higher versions of USD?

**Comment by spiffmon** [comment]
Hi @mudworker,
   First thing to notice is that you copied the incorrect `CreatePrimvar` body - you copied normals, which is a Vec3fArray, rather than (from the commented out line) a `TexCoord2fArray`

  I _think_ fixing that should be enough - let me know how that goes?

**Comment by mudworker** [comment]
> Hi @mudworker, First thing to notice is that you copied the incorrect `CreatePrimvar` body - you copied normals, which is a Vec3fArray, rather than (from the commented out line) a `TexCoord2fArray`
> 
> I _think_ fixing that should be enough - let me know how that goes?

I copied the wrong code when I copied it, LOl. It was indeed the error caused by this. It has been fixed. Thank you very much for your reply.

**Comment by msf567** [comment]
How can this work with c++? I'm getting identical issues with GetPrimvar

**Comment by spiffmon** [comment]
As @dgovil mentioned above for `CreatePrimvar()`, [`GetPrimvar()`](https://openusd.org/release/api/class_usd_geom_primvars_a_p_i.html#a31461d541ad7dec79af013e6d3070f59) has moved to `UsdGeomPrimvarsAPI` .

@msf567 , what tutorial or code are you encountering the old API's in?
