### ISSUE TITLE
Get a UsdStage from c++ istream or something instead of a filepath

### ISSUE THREAD

**Issue by gunjo7** [PixarAnimationStudios/USD#2629]
Hi,
I need to develop an usd asset Importor for our render.
Now,  i use the UsdStage::Open(std::string const& filepath) to get a UsdStage and use it do something.
However, thirdparty library is not allowed to use the filepath directly in our renderer.
I now need to get C++ istream data from our renderer's filesystem for use by the thirdpary library.  But, i don't seem to see such an interface like UsdStaget::Open(std::istream const&)  in pixar usd.
I also attempt to use the SdfLayer->ImportFromString(std::string const& str), but it doesn't seem to support the string comes from .usdc format. And why does it print the parameters when it's called?
The version is USD22.03

**Comment by meshula** [comment]
It sounds like you might be interested in the Ar system. 

> The Ar (Asset Resolution) library is responsible for querying, reading, and writing asset data. It provides several interfaces that allow USD to access an asset without knowing how that asset is physically stored.
> Ar ships with implementations based on a traditional filesystem. However, users can provide custom implementations to integrate their own asset storage system and behaviors with USD.

ArAsset is the means by which you can provide reading and writing functionality via your own systems, and ArResolver is the means by which you can resolve an identifier yourself. 

https://openusd.org/release/api/ar_page_front.html
https://openusd.org/release/api/class_ar_asset.html

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8631

**Comment by spiffmon** [comment]
Closing, given @meshula 's advice.  Please reopen if further issues arise - thank you!
