### ISSUE TITLE
Build failed without uic-binary

### ISSUE THREAD

**Issue by SathishKannaa-HexrFactory** [PixarAnimationStudios/USD#2632]
### Description of Issue
Found PySide6 but NOT pyside-uic binary
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PySide (missing: PYSIDE_AVAILABLE PYSIDEUICBINARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPySide.cmake:74 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:295 (find_package)
  CMakeLists.txt:23 (include)

-- Configuring incomplete, errors occurred!
See also "D:/python/version2/build/USD/CMakeFiles/CMakeOutput.log".
See also "D:/python/version2/build/USD/CMakeFiles/CMakeError.log".

ERROR: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="D:\python\version2" -DCMAKE_PREFIX_PATH="D:\python\version2" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 15 2017 Win64"  -DPXR_PREFER_SAFETY_OVER_SPEED=ON -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPXR_USE_DEBUG_PYTHON=OFF -DPython3_EXECUTABLE="C:\Program Files\Python38\python.exe" -DPython3_LIBRARY="C:\Program Files\Python38\libs\python38.lib" -DPython3_INCLUDE_DIR="C:\Program Files\Python38\Include" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EXAMPLES=ON -DPXR_BUILD_TUTORIALS=ON -DPXR_BUILD_USD_TOOLS=ON -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_ENABLE_OPENVDB_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_ENABLE_MATERIALX_SUPPORT=ON -DPXR_BUILD_PYTHON_DOCUMENTATION=OFF -DCMAKE_CXX_FLAGS="/Zm150" -DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True "D:\python\USD"'
See D:\python\version2\build\USD\log.txt for more details.
### Steps to Reproduce
while trying the 3rd step on the build

### System Information (OS, Hardware)

Windows 10

### Package Versions

pip                            21.1.1
PyOpenGL                3.1.5
PySide6                    6.5.2
PySide6-Addons      6.5.2
PySide6-Essentials   6.5.2
cmake                      3.16.5
Python                     3.8.10

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8635

**Comment by pattersone** [comment]
I have this same issue attempting to build on MacOS 14.1.1.

**Comment by meshula** [comment]
Please see this other thread, and try the steps there ~ the general steps of using pip to install PySide6 and so on apply to all platforms. https://github.com/PixarAnimationStudios/OpenUSD/issues/2582

**Comment by pixar-oss** [comment]
Closing this issue as a duplicate -- please see the discussion in https://github.com/PixarAnimationStudios/OpenUSD/issues/2582
