### ISSUE TITLE
UsdUtils.ComputeAllDependencies does not catch missing thumbnails in USDZ files

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2636]
### Description of Issue

UsdUtils.ComputeAllDependencies appears to work differently for USDZ and USD files in that the checker seems to miss that the assetInfo dictionary is pointing to an invalid asset path when the file is a USDZ, but It works correctly when you unzip the same file

This is with USD 23.8.

The attached script will run over the two files and print when it misses the check

### Steps to Reproduce
1. Download [Test.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/12501259/Test.zip)
2. Run the included Python script

**Comment by dgovil** [comment]
Ah this seems to be because `UsdUtils_FileAnalyzer` has this bit to mention. 

```
// If the newly opened layer is a package, it we do not need to traverse
// into it as the entire package will be included as a dependency.
if (_layer->GetFileFormat()->IsPackage()) {
        return;
}
```

So at least the cause is clear, though I think maybe the assumption in the code isn't accurate, because a USDZ may have external references that are unresolvable (per our previous discussions)

I'll submit a PR with that removed. I don't believe there are any side effects to the removal in my testing

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8640
