### ISSUE TITLE
usdview: `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

### ISSUE THREAD

**Issue by expenses** [PixarAnimationStudios/USD#2638]
### Description of Issue

I recently installed USD via the [Arch Linux AUR package](https://aur.archlinux.org/packages/usd) and tried to run usdview as suggested in comments via
```
PYTHONPATH=/usr/share/usd/lib/python LD_PRELOAD=/usr/lib/libjemalloc.so.2 /usr/share/usd/bin/usdview <model>
```

This displays the navigation panel but the render just shows my desktop background, emitting `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()` to the console.

![20230904_01h49m54s_grim](https://github.com/PixarAnimationStudios/OpenUSD/assets/13566135/64545e48-5f49-4eb8-a82e-c2161eef188a)

I'm using Wayland as a display server via the sway WM. 

On X11 usdview runs fine with the same command.

### System Information (OS, Hardware)

OS: Arch Linux x86_64
Kernel: 6.4.12-arch1-1
`sway -v`: sway version 1.8.1
USD version: 23.08
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
xorg-xwayland version: 23.2.0-1

**Comment by dgovil** [comment]
What PySide version are you using?

**Comment by expenses** [comment]
I found that forcing QT to use X11 fixes this on Wayland! See https://wiki.archlinux.org/title/Wayland#Qt for more details.

The full command I'm using now is `PYTHONPATH=/usr/share/usd/lib/python LD_PRELOAD=/usr/lib/libjemalloc.so.2 QT_QPA_PLATFORM=xcb  /usr/share/usd/bin/usdview <model>`.

> What PySide version are you using?

pyside2: 5.15.10-2
pyside6: 6.5.2-2

**Comment by dgovil** [comment]
Yeah, Wayland support in Qt is still hit and miss in my experience. It's better in newer versions, but for GL I haven't found anything that worked well other than what you did with setting the xcb. 

I was going to suggest Qt 6.5 because I thought it might be better now but guess not. 

It probably makes sense to make the xcb variable set at usdview launch for safety, but I'll defer to folks who are actively on Linux.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8642

**Comment by expenses** [comment]
Just FYI I'm happy to close this now that I have a solution for running usdview on wayland. This seems more like a Qt problem than a USD one. Up to you guys.

**Comment by expenses** [comment]
I just built the `dev` branch and `usdview` from there works fine on Wayland! I'll close this for now.
