### ISSUE TITLE
Execute path prepended to --cmake-build-args in build_usd.py

### ISSUE THREAD

**Issue by keithlostracco** [PixarAnimationStudios/USD#2639]
### Description of Issue
The Python build script prepends the path it executes from to the --cmake-build-args argument. 

For example:
`--cmake-build-args DPXR_ENABLE_VULKAN_SUPPORT=TRUE`

will result in:
`C:\users\...\...\OpenUSD\DPXR_ENABLE_VULKAN_SUPPORT=TRUE`

being passed to CMake, after which it will notify you that the argument is being ignored... 

I did a quick hack to fix the issue by modifying the function RunCMake() with this:

```
    buildsArgs = "-" + context.cmakeBuildArgs.split('/')[-1]
    print("cmake extra build args: ", buildsArgs)
    if context.cmakeBuildArgs:
        extraArgs.insert(0, buildsArgs)

    # if context.cmakeBuildArgs:
    #     extraArgs.insert(0, context.cmakeBuildArgs)
```
It's not a proper fix since it will only work for one argument, but it resolved the issue. Also, note I had to prepend the argument with "-" which the script wasn't doing. 

### Steps to Reproduce
1.  Pass --cmake-build-args argument via command line

### System Information (OS, Hardware)
Windows 11

### Package Versions
OpenUSD-23.08

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8643
