### ISSUE TITLE
Build script fails to install PyOpenGL

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#264]
### Description of Issue
Build script attempts to run PyOpenGL (pip install PyOpenGL), which fails because it's not running as sudo.

As a user, this was surprising since I didn't expect the build script to modify my system. I know the script is "installing" but when using it to produce a local build, no admin rights are required and there is a sense of safety that you aren't installing anything at the system level.

Would be nice (extra user-friendly) if:
1) the build script checked for pyopengl early (currently it fails late)
2) asked/notified the user that it's about to modify the system before attempting to pip-install
3) if the script doesn't have sudo, fail gracefully and tell the user that it needs to be run that way

Also odd that it attempts to automatically install PyOpenGL but not PySide.

**Comment by jtran56** [comment]
Filed as internal issue #149507.

**Comment by sunyab** [comment]
The point about the build script not modifying your system is a good one -- that was one of the goals of the script, but we thought installing as many dependencies as possible was more user-friendly.

I'm thinking we may just want to treat PyOpenGL like PySide and ask the user to install it manually. It'd simplify the build script and force users to be aware that they are modifying their system. What do you think?

**Comment by meshula** [comment]
Early bail out, with a note on how to proceed if PySide and PyOpenGL are not detected is my preference.
