### ISSUE TITLE
Unable to build USD on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by wolzjohannes** [PixarAnimationStudios/USD#2642]
### Description of Issue
Whenver i try to build USD with the build_usd.py it crashes after 60% done.

### Steps to Reproduce
1.  use the build_script.py

### System Information (OS, Hardware)
Ubuntu 22.04.3 LTS
HUAWEI WRT-WX9
Intel® Core™ i5-8265U CPU @ 1.60GHz × 8
Mesa Intel® UHD Graphics 620 (WHL GT2)

### Package Versions
latest release

### Build Flags
None
[log.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/12520620/log.txt)

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8646

**Comment by FlorianZ** [comment]
@wolzjohannes we don't officially build and test with Ubuntu, but you might want head over to forum.aousd.org and ask for help under the "Build and Deployment" topic. Good luck!
