### ISSUE TITLE
UsdPreviewSurface: clarify clearcoat layering

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2659]
### Description of Issue

Clearcoat and clearcoatRoughness are described here: https://openusd.org/release/spec_usdpreviewsurface.html
However, it's not immediately clear (pun intended) if clearcoat is to be applied as separate layer outside the normal map (a coating) or as a layer directly on top of the already provided normal. I think it's intended as the latter, which the description "second specular lobe" is probably meant to convey, but it could be more apparent.

For reference, glTF provides a separate clearcoatNormalMap to better define the intended effect (when both normals are the same the behaviour is the same as in UsdPreviewSurface right now).

.glb and .usdz files for comparison:
[ClearCoatTest.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/12543124/ClearCoatTest.zip)

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8665
