### ISSUE TITLE
Generalize Katana PxrUsdIn to support multiple renderers

### ISSUE THREAD

**Issue by spiffmon** [PixarAnimationStudios/USD#268]
Currently, Renderman-specific import logic is sprinkled throughout PxrUsdIn code, and in particular when  importing shading.

We think a likely approach to addressing this issue is to extend the existing per-location plugin mechanism to allow any plugin code to register lightweight processing functions (not ops) that get a chance to fire on all locations during import.

**Comment by jtran56** [comment]
Filed as internal issue #149961.

**Comment by c64kernal** [comment]
Closing this as we are in the process of deprecating the Katana plugins from the USD repo.
