### ISSUE TITLE
Trouble UV Mapping Image Texture to Mesh

### ISSUE THREAD

**Issue by abhihjoshi** [PixarAnimationStudios/USD#2683]
I am currently having some trouble mapping an image texture onto a mesh. The cube in my particular case is such that its faces are of 3 vertices, not 4. I have the face vertex indices, the vertices (i.e. their coordinate points), and also the texture coordinates. I also have a list of the texture coordinates that correspond to each face. I am confused how to put these together or if I need more information to properly UV map the textures onto the meshes. 

Also, I am currently using the Python APIs to convert the mesh to USD. I would really appreciate any help on this matter and I am also happy to share my .obj/.mtl and .png files for the mesh I am trying to convert.

Could someone provide an example of the code of how I might go about accomplishing this. I am still a little new to USD, so any explanation of how this works is much appreciated!

The current methods I am using are `GetPointsAttr`, `GetFaceVertexCountsAttr`, `GetFaceVertexIndicesAttr`. Also, to set my texture coordinates, I use 

```
self.texcoords = UsdGeom.PrimvarsAPI(self.prim).CreatePrimvar("st",
                                    Sdf.ValueTypeNames.TexCoord2fArray,
                                    UsdGeom.Tokens.varying)
self.texcoords.Set(texcoords)
```
Thanks!

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8698

**Comment by spiffmon** [comment]
Hi @awesome-aj0123 , I think this question might be more appropriate for the ASWF #wg-usd-assets or #wg-usd slack channels?

**Comment by abhihjoshi** [comment]
Where can I join these channels?

**Comment by jesschimein** [comment]
Hi Abhishek,
You can find the #wg-usd-assets or #wg-usd slack channels in the ASWF slack
instance! Here's an invite to the Slack instance.  (Note: the link expires
in 30 days)
https://join.slack.com/t/academysoftwarefdn/shared_invite/zt-23cgkn377-yoUK4SZDDo1bVeoQqUOy3Q

**Comment by spiffmon** [comment]
Closing this, hoping you found useful advice on ASWF, @awesome-aj0123 .
