### ISSUE TITLE
Storm not drawing unloaded payload boxes

### ISSUE THREAD

**Issue by crydalch** [PixarAnimationStudios/USD#2720]
### Description of Issue
Storm is not drawing unloaded payloads anymore. It would be good to have that behavior back, but also support `origin` and `cards` modes, as well as `drawModeColor`, on unloaded payloads.

### Steps to Reproduce
1. Download *Teapots_DrawModes.zip*
2. Open the file with `usdview --unloaded DrawModes.usd`
3. There won't be any boxes in the viewport. 

### System Information (OS, Hardware)
Ubuntu 22.04

### Package Versions
23.08, 23.11(dev)

### Build Flags
Just the regular build 

[Teapots_DrawModes.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/12717463/Teapots_DrawModes.zip)
script, nothing special.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8743

**Comment by klucknav** [comment]
Unfortunately, I have been unable to repro this. Are you still seeing this issue? Or do you have another repro case?

**Comment by chrizzFTD** [comment]
Hi @crydalch , do you have a last working version for this on Windows? I've not been able to get a last-working version where unloaded prims draw their boxes on windows. Internally at AL (CentOS-7), this issue starts with USD-23.8+

I've started a related thread to this on the `#wg-usd-assets` channel in Slack regarding draw mode. 

@klucknav, this is a subset of our ALab assets that showcase the issue too:

[lab_inspiration01_06.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13936279/lab_inspiration01_06.zip)

This is what I see when running:
```
usdview --unloaded /path/to/downloaded/lab_inspiration01_06.usdz
```

| USD-23.8+ | USD-23.5 |
|---|---|
| ![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/8294116/329468e9-d9f2-4084-8edf-8c45e31a510d) | ![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/8294116/bd5f180d-9446-4885-967b-10d0264de180) |


Starting 23.8+ there are no boxes. Even when switching `Draw Mode` to `bounds`:

![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/8294116/28608a5e-8514-48ad-a760-d4e3a04dfae8)

It is only when selecting some prims that we get to see a bounding box (one for all the selection):

![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/8294116/2b662976-8ae2-4fb9-b230-09849db1143f)

but we'd expect for boxes to appear at all times.

Hope this helps! :P

**Comment by crydalch** [comment]
@klucknav I will try rebuilding and testing, or see if I can find another repro case (though it seems that @chrizzFTD has a case that has issues as well)

**Comment by jesschimein** [comment]
Hi @crydalch @chrizzFTD -- are you both still running into this issue?  We're still having some trouble repro-ing and were wondering if this is still a priority.  Please let me know!

**Comment by crydalch** [comment]
Hi @jesschimein, @klucknav I just tried the latest dev branch, am still not seeing draw mode apply to unloaded payloads.

Are there any environment variables, or flags to the build script, that could be affecting the reproducibility?

**Comment by asluk** [comment]
@chrizzFTD I think the assets in this Issue, or further simplified versions of them, are worth submitting to https://github.com/usd-wg/assets/ -- thanks!

**Comment by chrizzFTD** [comment]
> @chrizzFTD I think the assets in this Issue, or further simplified versions of them, are worth submitting to https://github.com/usd-wg/assets/

Good call, I'll look into that in the coming days; thanks!
