### ISSUE TITLE
UsdEditContext ctor crashes with expired stage pointer

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#2721]
### Description of Issue

Constructing a UsdEditContext with an expired stage will crash. It'd be great to make this facility more defensive in https://github.com/PixarAnimationStudios/OpenUSD/blob/dev/pxr/usd/usd/editContext.cpp

### Steps to Reproduce

with Usd.EditContext(None):
    print('hello')

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8750

**Comment by asluk** [comment]
@jesschimein I'm happy to scratch out time to make a PR for this, if no one else is available in the next month or so. Thanks!

**Comment by jesschimein** [comment]
Hi Aaron!  Thank you for the offer!  I think we can cover this one; we've
assigned this to someone internally and expect to be able to take a look
within the next month.
