### ISSUE TITLE
HdxFullscreenShader can't be used by OpenUSD clients due to a function not being exported

### ISSUE THREAD

**Issue by pixnblox** [PixarAnimationStudios/USD#2727]
The class `HdxFullscreenShader` has a private function called `GetFullScreenVertexDesc` that is called by a public function SetProgram as a default argument. However, this private function is not exported with `HDX_API` so any attempt to use the class outside OpenUSD will result in a linker error. This is believed to be an oversight because the header file is available in the `include` directory of an OpenUSD installation, i.e. it is expected to be available to OpenUSD clients.

A solution would be to simply export `GetFullScreenVertexDesc` by adding `HDX_API` to it. This will be done in the Autodesk fork of OpenUSD and likely contributed in a future pull request.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8818

**Comment by pixnblox** [comment]
This is no longer relevant due to a recent change to `HdxFullscreenShader`, i.e. the `SetProgram` function has changed. See the commit linked below. We are successfully using the new version without modification, so this issue can be closed.

https://github.com/PixarAnimationStudios/OpenUSD/commit/24acf5a6d26df999ad4f3792f862976107107243
