### ISSUE TITLE
usdchecker should check for attribute types on shaders

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2729]
### Description of Issue

We recently discovered a bug in Blender where it was exporting the color3f attributes as float3. We'll resolve it in a PR to them, but it would be great if the usdchecker had code to check for such inconsistencies. usdview won't catch it since color3f is an alias for float3, but it does mean the files are slightly out of spec.

I've already set up Blenders unit tests to use usdchecker to verify exports, but it doesn't seem like usdchecker currently catches this particular case. 

### Steps to Reproduce
1. Open Blender 3.6 and add a material to the default cube
2. Export to a usda
3. Notice that diffuse colours and emissive are float3 instead of color3f

**Comment by spiffmon** [comment]
Great sug, @dgovil !

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8826
