### ISSUE TITLE
usdPreviewSurface spec for reading alpha channel from grayscale image has inconsistent adoption

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2731]
The [usdPreviewSurface spec](https://openusd.org/release/spec_usdpreviewsurface.html) specifies that reading alpha channel of a grayscale texture should return 1:

 `“If a single-channel texture is fed into a UsdUVTexture, the r, g , and b components of the rgb output will repeat the channel’s value, while the single a output will be set to 1.0.”`

However, in `usdview`, the alpha channel returns the image. In other contexts (RealityKit, Maya, Houdini) the alpha channel returns 1 per the spec

Steps To Reproduce:
* View attached usdz in various renderers. 
* See `usdview` is an outlier 

[vistest_texture_format_grayscale_alpha.usdz.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/12884881/vistest_texture_format_grayscale_alpha.usdz.zip)

<img width="828" alt="Screenshot 2023-10-11 at 11 44 49 PM" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/15f6b486-3ec8-479a-b238-8ef2399c3312">

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8828

**Comment by klucknav** [comment]
I tested the attached usdz file and was unable to repro the issue you are seeing here. Are you still seeing this issue? Do you have another repro case? Or more information about when you are seeing this?

**Comment by dgovil** [comment]
@klucknav Unfortunately I'm still seeing this with USD 23.11. 

Would you be able to share a screenshot of what you're seeing on your end with the attached file in USD 23.11? I assume you're checking on a Linux machine with an NVIDIA gpu using OpenGL?

I'm curious if it may be a difference between graphics backends that hasn't been accounted for. I'm on a Mac with a Metal on an Apple GPU.

**Comment by klucknav** [comment]
Ok, it does seem to be a Metal specific issue. Thank you for clarifying your setup for where you are seeing the problem.

**Comment by dgovil** [comment]
Ah great, I'm glad you were able to repro on a Mac. Apologies, I should have mentioned that earlier.
