### ISSUE TITLE
Storm shader compilation errors on Intel Arc GPUs

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#2743]
### Description of Issue
Storm does not render anything and throws shader compilation errors on Intel Arc GPUs:

Warning: in _ValidateCompilation at line 228 of F:\USD-dev\pxr\imaging\hdSt\glslProgram.cpp -- Failed to compile shader (VERTEX_SHADER): ERROR: 0:683: '[' :  built-in array must be redeclared with a size before being indexed with a variable

Full log with HDST_DUMP_FAILING_SHADER_SOURCE here: [log.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/13005738/log.txt)

According to the source and error message, following snippet seems to be the problem:
```glsl
void ApplyClipPlanes(vec4 Peye)
{
#if defined(HD_HAS_numClipPlanes)
#if defined(HD_HAS_clipPlanes)
    for (int i=0; i<HdGet_numClipPlanes(); ++i) {
        gl_ClipDistance[i] = dot(HdGet_clipPlanes(i), Peye);
    }
#endif
#endif
}
```
where `gl_ClipDistance` needs to be redeclared according to GLSL spec 4.60 chapter 7.1.1:
> The gl_ClipDistance array is predeclared as unsized and must be explicitly sized by the shader
either redeclaring it with a size or implicitly sized by indexing it only with constant integral
expressions.

### System Information (OS, Hardware)
OS: Windows 10
GPU: Intel(R) Arc(TM) A770 Graphics

### Package Versions
v23.11-rc1

### Build Flags
`python build_scripts/build_usd.py --materialx --build-variant release --opencolorio --openimageio --tests INSTALL`

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8844

**Comment by erikaharrison-adsk** [comment]
Note: A couple of us also experienced this issue. We added the following to renderPass.glslfx, which removed the warnings, but **it still doesn't show the model** so it doesn't seem quite enough to address the problem. Switching to a different GPU is a workaround for now.

```
out gl_PerVertex
{
  vec4 gl_Position;
  float gl_PointSize;
  float gl_ClipDistance[HD_HAS_numClipPlanes];
};

void ApplyClipPlanes(vec4 Peye)
{
#if defined(HD_HAS_numClipPlanes)
#if defined(HD_HAS_clipPlanes)
    for (int i=0; i<HD_HAS_numClipPlanes; ++i) {
        // For Hgi backends like Metal, we declare a shader stage output of 
        // gl_ClipDistance[HD_HAS_numClipPlanes], since we need to know the array 
        // size at compile time. To avoid having any uninitialized values in 
        // that array, we initialize them all to zero first.
        gl_ClipDistance[i] = 0;
        if (i < HdGet_numClipPlanes()) {
            gl_ClipDistance[i] = dot(HdGet_clipPlanes(i), Peye);
        }
    }
#endif
#endif
}
```

**Comment by pablode** [comment]
Ah, it seems like I was on a previous commit and not actually v23.11-rc1, which is why the code snippet differs.

However, the snippet you posted is also a bit confusing, as it uses `HD_HAS_numClipPlanes` and not `HD_NUM_clipPlanes` for the loop bounds. I still get the error with the latest revision, which might hint at a compiler bug because the spec says `[..] or implicitly sized by indexing it only with constant integral expressions.`.

The following should be the correct fix:
```diff
--- a/pxr/imaging/hdSt/shaders/renderPass.glslfx
+++ b/pxr/imaging/hdSt/shaders/renderPass.glslfx
@@ -168,6 +168,12 @@ vec2 HorizontallyNormalizedFilmbackCoordinates()

 -- glsl RenderPass.ApplyClipPlanes

+#if defined(HD_HAS_numClipPlanes)
+#if defined(HD_HAS_clipPlanes)
+out float gl_ClipDistance[HD_NUM_clipPlanes];
+#endif
+#endif
+
 void ApplyClipPlanes(vec4 Peye)
 {
 #if defined(HD_HAS_numClipPlanes)
```

**Comment by sunyab** [comment]
Just wanted to mention we're IP on fixes for this and #2745. Our plan is to push out a new release candidate in the next day or so, with an official release following a few days afterwards. We'll keep folks posted about the release plans on the AOUSD forum. Thanks!

**Comment by pixnblox** [comment]
FWIW, another data point: I also see this on an AMD Radeon 780M integrated GPU. It is strange that what should be a general compile failure somehow passes on certain GPUs.

**Comment by davidgyu** [comment]
Thanks @pixnblox! We also have been able to reproduce this on Intel and AMD GPUs. Some GLSL shader compilers are more permissive than others, and the compilers that are raising an error in this case are correct.

We have merged a fix for this internally and as Sunya mentioned we plan to incorporate that fix in the next release candidate.
