### ISSUE TITLE
Segfaults in HgiMetal on USD 23.11 when using DomeLights + Depth AOV

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#2745]
Reporting on behalf of others
### Description of Issue

On the OpenUSD "dev" branch, I am getting a crash in Storm when rendering depth when there is a Dome light with a texture in the scene. This happens on macOS (both x86 and arm64). I have not tested on other OS's. The easiest way to see this is to load a scene in usdview and ask it to show the AOV "depth". It does not happen on the release 23.08 branch.

### Steps to Reproduce
1. Create a scene with a dome light with a texture. The scene doesn't need any other objects. I've tried both a PNG and EXR file as the dome texture.
2. Open the scene in usdview.
3. Make sure Display->Show Dome Light Texture is ON.
4. Select Renderer->Hydra AOVs->depth.
usdview will crash. The log indicates the crash is in HgiMetalGraphicsCmds::HgiMetalGraphicsCmds

### System Information (OS, Hardware)
macOS 14.0 with Python 3.8

[crashlog.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/13031645/crashlog.txt)

[SampleAsset.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13031646/SampleAsset.zip)

**Comment by drwave** [comment]
This also happens in main, 23.11 rc1

**Comment by drwave** [comment]
The commit ID which introduced the crash is 24acf5a6d

the PR which causes this is primarily about adding effectsShaders. But there is a small change to skydomeTask.cpp, and this  likely is the issue. The change is:
    // Bind the skydome texture
-   _compositor->BindTextures( {_tokens->skydomeTexture}, {_skydomeTexture} );
+   _compositor->BindTextures({_skydomeTexture});

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8845

**Comment by sunyab** [comment]
Thanks for the report, we're digging into this now!

**Comment by jonogibbs** [comment]
Awesome, thank you!
