### ISSUE TITLE
Cannot build debug with imaging tests in v23.11-rc1

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#2749]
### Description of Issue
Building v23.11-rc1 debug with imaging tests fails due to changes in OpenImageIO

### Steps to Reproduce
1. python.exe build_scripts\build_usd.py --tests --build-variant=debug _install

### System Information (OS, Hardware)
Windows 10,  Ubuntu 18.04.5 LTS

### Package Versions
USD v23.11-rc1

### Build Flags
--tests --build-variant=debug 

This is because newer releases of OpenImageIO suffix debug binaries with "_d" -- https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/master/CHANGES.md

CMake Error at C:/packman-repo/chk/cmake/3.24.1+nv3-windows-x86_64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenImageIO (missing: OIIO_LIBRARIES) (found version
  "2.3.21")
Call Stack (most recent call first):
  C:/packman-repo/chk/cmake/3.24.1+nv3-windows-x86_64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindOpenImageIO.cmake:150 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:211 (find_package)
  CMakeLists.txt:23 (include)

**Comment by asluk** [comment]
Semi-related-- I missed this for a while because I was using `--debug` instead of `--build-variant=debug` for debug builds. Does `--debug` mean anything to build_usd.py, and if not, could build_usd.py error out when it encounters command-line options that it doesn't understand? Thanks!

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8858

**Comment by sunyab** [comment]
I'm looking into a fix for this for inclusion in the 23.11 release.

Also, I had no idea this was a thing but apparently `argparse` allows users to abbreviate arguments at the command-line as long as the abbreviation uniquely identifies an option. I'll file something internally to disable that, that will *not* be included in 23.11.
