### ISSUE TITLE
--no-embree seems to *cause* CMake to look for embree

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#276]
### Description of Issue
When running build_usd.py with --no-embree, I get CMake config failures about not being able to find embree. When I remove this flag, it configures fine.

### Steps to Reproduce
Make sure embree is not on your path, then run:

python build_scripts\build_usd.py --build-monolithic --no-ptex --no-embree  --no-alembic build_monolithic\

Once prereq's are finished, it will fail on CMake config, complaining about embree.

Remove --no-embree, then it configures USD fine.

### System Information (OS, Hardware)
Windows

**Comment by jtran56** [comment]
Filed as internal issue #150563.
