### ISSUE TITLE
Nothing displayed for file in usdview

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2769]
### Description of Issue

The attached file renders fine in some viewers (e.g. QuickLook on iOS/MacOS) but not in usdview. I can see some bounds/outlines but no geometry.

### Steps to Reproduce
1. Download the attached usda/usdz file(s) 
[boneMovement.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13198652/boneMovement.zip)

2. Test in usdview
3. Test in other viewers (some may show it correctly)
4. Compare to reference GLB/.blend (also in the attached archive)

Reference:
https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/c241354f-c12c-48e2-b3c5-9ea643159461

https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/c241354f-c12c-48e2-b3c5-9ea643159461

usdview:

https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/8d967172-ca73-4012-9650-97707d067d75

### System Information (OS, Hardware)
Windows 11

### Package Versions
0.23.11 (Omniverse Launcher)

**Comment by drwave** [comment]
running usdview on macOS built with RC1 of 23.11, it looks fine to me:

https://github.com/PixarAnimationStudios/OpenUSD/assets/1679418/7aee1656-f015-4ac8-b5aa-35a51acee639

**Comment by hybridherbst** [comment]
Thanks for verifying. I also just tried another version of usdview (not the Omniverse one) and there it looks fine. I'll close this issue and investigate further what's wrong with that other build.
