### ISSUE TITLE
Monolithic pxr headers not installed correctly

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#277]
### Description of Issue
After a successful build, I have no headers in my build/include/pxr directory other than pxr.h

### Steps to Reproduce
python build_scripts\build_usd.py --build-monolithic --no-ptex --no-alembic build_monolithic\

After successful build, I have other headers, but the pxr headers are missing (aside from pxr.h).

### System Information (OS, Hardware)
Windows

**Comment by jtran56** [comment]
Filed as internal issue #150565.

**Comment by jcowles** [comment]
Still true with release 0.8.1

**Comment by giuliom95** [comment]
Same issue on CentOS 7 with USD 0.8.1.
I've built it by launching "python build_scripts/build_usd.py --build-monolithic --ptex install/"

**Comment by ix-dcourtois** [comment]
Hi, this is happening also on Windows when manually building using CMake (with -DPXR_BUILD_MONOLITHIC=On)

**Comment by ix-dcourtois** [comment]
Hi again,

I'm not sure it's the right place for this, but I have a quick fix for this problem.
In the _copy_headers function (Private.cmake) I set a target property to store the headers in the target:

```
    set_target_properties(${LIBRARY_NAME}_headerfiles
        PROPERTIES
            FOLDER "headerfiles"
            INSTALL_HEADERS "${files_copied}"           # this line is the new one
    )
```

and in the same file, near the end of the _pxr_library function, I do this :

```
    if(NOT isObject)
        # the usual code...

    elseif(PXR_BUILD_MONOLITHIC)
        # this elseif is what installs the headers. Problem was when monolithic build is
        # selected, every target is built as an object, so the previous code was never doing
        # anything.
        get_target_property(install_headers ${NAME}_headerfiles INSTALL_HEADERS)
        if(install_headers)
            install(FILES ${install_headers} DESTINATION ${headerInstallPrefix})
        endif()
    endif()
```

**Comment by sunyab** [comment]
Thanks for the tip @ix-dcourtois! I tweaked your fix a bit to ensure that only public headers would be installed.

**Comment by dcourtois** [comment]
@sunyab Yep I noticed the commit, glad I could be of help :)
