### ISSUE TITLE
Need strict definition of `black` border color in UsdPreviewSurface Texture Reader

### ISSUE THREAD

**Issue by syoyo** [PixarAnimationStudios/USD#2770]
### Description of Issue

https://openusd.org/release/spec_usdpreviewsurface.html#version-2-5-current-head

The spec says

```
Wrap mode when reading this texture.Possible Values:

        black : Reader returns black outside unit square
```

But not sure what actual black color should be. 

Possible value is either transparent black (0, 0, 0, 0) or opaque black (0, 0, 0, 1)

We need strict definition of black border color.
(NOTE:  Currently TinyUSDZ Tydra uses transparent black)

I'm not sure how Storm interprets `black` border color, but it seems Storm uses TransparentBlack as a default border color: https://github.com/PixarAnimationStudios/OpenUSD/blob/0b18ad3f840c24eb25e16b795a5b0821cf05126e/pxr/imaging/hgi/sampler.h#L73C18-L73C18

cc @dgovil

### Steps to Reproduce

N/A

### System Information (OS, Hardware)

N/A

### Package Versions

23.08

### Build Flags

N/A

**Comment by sunyab** [comment]
Filed as internal issue #USD-8890
