### ISSUE TITLE
The USDC File Format does not use the AR system unless USDC_USE_ASSET is enabled

### ISSUE THREAD

**Issue by alasdair-foundry** [PixarAnimationStudios/USD#2773]
### Description of Issue
The `USD_USE_ASSET` environment variable has to be explicitly enabled to allow the USDC file format to use the Asset Resolver system when saving/loading files. A commit message for the commit that adds this environment variable mentions that enabling `USDC_USE_ASSET` causes issues on Windows:
```
The new testUsdFileFormats_asset test exposed a pre-existing issue with saving .usdc files when
using the ArAsset-based codepath and an ArFilesystemAsset to read .usdc files on Windows. This
codepath isn't typically used; it's meant to handle non-file backed .usdc assets so we hadn't seen
it until now. The test is disabled for now while we look into a fix.
```
[Commit](https://github.com/PixarAnimationStudios/OpenUSD/commit/ccec62d2ff07c423ff1651743d44457e1fb76bc0)

The behaviour when `USD_USE_ASSET` is enabled should be the default to allow USDC files to be used with the AR system as users would expect.

### Steps to Reproduce
1. Create an `AssetResolver` & associated `ArWritableAsset` & `ArAsset` which handles a given asset path format
2. Export a USD stage using the `.usdc` file format with the asset path format
3. Observe the export does not call into the Asset Resolver unless `USD_USE_ASSET` is explicitly enabled, and will instead try to save to the file system

### System Information (OS, Hardware)
- Windows, but I can't see why this wouldn't also affect other OSs.

### Package Versions
OpenUSD 23.05 - VFX Platform 2023

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8897
