### ISSUE TITLE
Regressions in skeletal animation display in usdview

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2774]
### Description of Issue

A file that previously worked fine (at least in 23.05) now don't display correctly anymore in 23.11 (no skeletal animation is played at all).

Problematic file: 
[CarbonFrameBike.usdz.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13225981/CarbonFrameBike.usdz.zip)

https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/bf651f82-0626-41c1-a33d-4da823bf67a3

The wires should animate, but instead they are (posed in rest pose I guess) stuck somewhere at the floor.
I'm also not sure where the z-fighting comes from – looks like the beam is rendered twice? – but maybe that is a wrong view setting on my end.

It continues to work fine in Apple QuickLook. I can't get it to open correctly in some other viewers either but I've got mixed results with skeletal animation in general – usdview so far was fine :)

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8898

**Comment by spiffmon** [comment]
@hybridherbst , could you please try running `usdfixbrokenpixarschemas` on the `.usdz` file?  We tightened up enforcement of the object model for UsdSkel, which leaves some older assets in a broken state, but the fixup script should correct them.

**Comment by hybridherbst** [comment]
Thanks again, that actually brings the wires back to live!

`usdfixbrokenpixarschemas` still returns errors after running, so I guess there are more problems that would need to be fixed by hand (?).

Do you maybe also have an idea for why there's z-fighting on the bike beam? It seems to be a single piece and didn't do that before.

**Comment by spiffmon** [comment]
Just to relay results of our internal investigation, thanks to @rajabala ... we did not reproduce the z-fighting on linux in Storm in the dev branch.  @hybridherbst , Raja also provided the output of `usdchecker`, and there were:
a) Some "non-conformant" normal-map scalings - are those legit, per the other Issue we've been discussing?
b) There was illegal shading network structure like Maya used to produce years ago.  Do you know what DCC or conversion script produced this asset, and is it still producing this style of network?  If so, is there a path to fixing it?

**Comment by hybridherbst** [comment]
Thanks –

I'll have to look at a) again.

Regarding b), is the information in usdchecker enough to understand what's "illegal" here, or are there docs about it?
The file has been exported with an older version of USD-for-Unity.

**Comment by spiffmon** [comment]
Here's one of the errors:
```
Connectable Shader </CarbonFrameBike/Materials/Sattel_47646/PreviewSurface/uvReader> cannot reside 
under a non-Container Connectable Shader (fails 'PrimEncapsulationChecker')
```
which is saying that a SHader prim can't be defined inside another Shader prim, but [here is an explanation of the what and why](https://openusd.org/release/api/usd_shade_page_front.html#UsdShadeEncapsulation) as it appears in our developer documentation (user-docs are IP).
