### ISSUE TITLE
MSVC unresolved external symbol: TfDiagnosticMgr::Delegate::~Delegate

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#278]
### Description of Issue
Pure virtual dtor's must be declared and defined (at least according to Herb Sutter's argument here: http://www.gotw.ca/gotw/031.htm

Correct or incorrect, MSVC requires it.

### Steps to Reproduce
1. Attempt to compile client code with MSVC which derives from TfDiagnosticMgr::Delegate

class MyDiagDelegate : public TfDiagnosticMgr::Delegate {
...
}

Error:

error LNK2001: unresolved external symbol "public: virtual __cdecl pxrInternal_v0_8__pxrReserved__::TfDiagnosticMgr::Delegate::~Delegate(void)" (??1Delegate@TfDiagnosticMgr@pxrInternal_v0_8__pxrReserved__@@UEAA@XZ)
1>C:\src\usd\UsdBindings\vs2015\USD.NET\x64\ReleaseMonolithic\UsdCs.dll : fatal error LNK1120: 1 unresolved externals

Adding this resolves the error:

__cdecl pxrInternal_v0_8__pxrReserved__::TfDiagnosticMgr::Delegate::~Delegate(void) {
}

### System Information (OS, Hardware)
Windows / MSVC 2015

**Comment by jtran56** [comment]
Filed as internal issue #150566.

**Comment by gitamohr** [comment]
It's declared in the header and defined here: https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/lib/tf/diagnosticMgr.cpp#L105

**Comment by jcowles** [comment]
Doh. The bug was in my code, though I don't fully understand why the message was complaining about the Tf base class and why adding that line fixed it...

Sorry for the noise.

(closing, not a bug)

**Comment by ZeroCrunch** [comment]
It is declared and defined, but MSVC requires it be exported to, i.e., add `class TF_API Delegate`

**Comment by jcowles** [comment]
Yeah, I think that's right -- I'm actually seeing inconsistent behavior, like it works when something in USD is using a delegate, but depending on my compile options, it may get optimized out.

Even if that's wrong, I think it's correct that it needs the export decl.
