### ISSUE TITLE
usdview: blend shapes are not applied

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#2787]
### Description of Issue

Only the base shape is displayed, not the result of applying the blend shapes. The weights seem to show up properly.

### Steps to Reproduce
1. Download  [blendStudy_01.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13271870/blendStudy_01.zip)
2. Drop into usdview
3. Note it's just a cube, but actually there's blend shape weights specified
4. Drop elsewhere (e.g. Omniverse) and see the correct result

| Blender | usdview | Omniverse |
| - | - | - |
| ![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/ac745f89-ca08-4591-9195-c7b19eafddfd) | ![Screenshot 2023-11-06 204312](https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/1d40eb53-ef17-4dd1-8edf-d1f4d53f3770) | ![Screenshot 2023-11-06 204400](https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/850e2d5c-f318-41ab-84a4-3c90c4d3281f)

### System Information (OS, Hardware)
Windows 11

### Package Versions
23.11

### Build Flags
Omniverse usdview

**Comment by hybridherbst** [comment]
A file with timeSamples doesn't work either.
I can see the timeSamples in the usda, but I can't find them inside usdview, and the blend shapes don't play:
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/99197d9a-27cd-4eaf-ba4b-da3ad9f0a55e)
[blendStudy_02.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13272152/blendStudy_02.zip)

The animation plays fine in Nvidia Omniverse and in MacOS QuickLook in Finder.

**Comment by hybridherbst** [comment]
Ah, gosh, maybe the same issue as https://github.com/PixarAnimationStudios/OpenUSD/issues/2774, the SkelBindingAPI is missing...

I would really welcome if usdview would show me validation errors 🥹

**Comment by spiffmon** [comment]
Also, the timeSamples are there - you need to select the `blendShapeWeights` property in the Property inspector below the browser.  It's not the greatest GUI, but it's what we have for now!

**Comment by hybridherbst** [comment]
Thank you, I found it!
<img width="1146" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/a90bc766-fb4e-4526-b1fa-298b61ea323d">

Does "green text" mean: it has timeSamples? And why is it sometimes italic and sometimes not?

**Comment by spiffmon** [comment]
Yes on green == timeSamples.  Try poking the "?" button at the bottom of the inspector; it will give you a legend for what all the formatting means.

**Comment by hybridherbst** [comment]
Thanks a lot for the help to self-help!

For others strolling by:
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/2693840/8af0dc98-8190-4607-9b32-cc5640b1e7ed)
