### ISSUE TITLE
Does usd support save and convert between units?

### ISSUE THREAD

**Issue by kybin** [PixarAnimationStudios/USD#279]
Sorry it is not an issue, but a question.

In Maya the default unit for length is cm.
In Houdini or Katana, the default unit is meter.

Conversion between tool with existing data exchange format is very unpleasure.
USD seems to be next generation data exchange format.

So, I guess it supports save/convert unit during import or export.
Does it?

Sorry, I know it is a development place, but a forum. But I don't know where is better place of asking it.

**Comment by spiffmon** [comment]
Hi Yongbin,
     We actually have a google group, usd-interest, that is perfect for these 
kinds of questions!  I just added a post there that explores this issue, 
which has come up several times already.  It will, of course, be up to the 
plugins for each particular package, to either make an adjustment to their 
own state to refelct the units in the imported USD, or perform a conversion 
to their desired units.

     Here is the post: 
https://groups.google.com/d/msg/usd-interest/y7bUOv58H3c/EgKKHEzoAAAJ

Cheers,
--spiff

**Comment by kybin** [comment]
Thank you for letting me know the forum and the answer, @spiffmon !

I will check there and close this.
