### ISSUE TITLE
Selected hydra renderer doesn’t support prim type ‘RenderSettings’

### ISSUE THREAD

**Issue by dinelanthony** [PixarAnimationStudios/USD#2793]
### Description of Issue

I have set up a Frame Recorder, some basic render settings as well as a render product and tried to render an image using the Frame Recorder, but when I run my script, I get the warnings:

Warning: in _AdapterLookup at line 279 of C:\Users\DinelAnthony\Source\Repos\PixarAnimationStudios\USD\pxr\usdImaging\usdImaging\delegate.cpp – Selected hydra renderer doesn’t support prim type ‘RenderSettings’

Warning: in _AdapterLookup at line 279 of C:\Users\DinelAnthony\Source\Repos\PixarAnimationStudios\USD\pxr\usdImaging\usdImaging\delegate.cpp – Selected hydra renderer doesn’t support prim type ‘RenderProduct’

This is then followed by plenty of “GL error : invalid operation”.

An image is output, however none of my render settings seem to come into effect. This happens no matter which renderer I choose (my system only has GL and Embree).

The post with the code can be found [here](https://forum.aousd.org/t/renderers-do-not-support-rendersettings-or-renderproducts-prims/895)

### Steps to Reproduce
1. Set up frame recprder, render settings, and render product
2. Add a camera rel to the render product and a product rel to the render settings
3. Define a custom resolution for the render settings
4. Run the frame recorder on the stage with the given camera

### System Information (OS, Hardware)
Windows 10
Custom (basic) OpenGL Context

### Package Versions
USD 23.08
Pyside6 6.5.1
PyOpenGL 3.1.7

### Build Flags
–build-monolithic --tests --docs --python-docs --debug-python --ptex --openvdb --embree --no-prman --openimageio --alembic --hdf5 --no-draco --materialx --opencolorio

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8918

**Comment by spiffmon** [comment]
Hi @dinelanthony, in due time we want all of the renderers that Pixar ships to support RenderSettings configuration.  However, with limited resources, our priority has been hdPrman, which is the only renderer that currently supports it.

**Comment by dinelanthony** [comment]
@spiffmon Thanks for the quick reply! That makes sense, then, but could I ask a follow-up? Since the GL and Embree renderers don't support render settings, unless I build my own render delegate using I'd assume UsdImgaingGLEngine, I would like to at least have some more control over the output image size, though just adjusting the width maintains the aspect ratio. So is there any way to adjust the camera's aspect ratio? The only control I can find in UsdCamera is the horizontal and vertical apertures but those don't directly translate to aspect ratio and I can't seem to find where the image height calculation or the image aspect ratio calculation happens.

**Comment by dinelanthony** [comment]
I was able to figure out the aspect ratio after a lot of trial and error:

Get the horizontal aperture, set the vertical aperture to be the horizontal aperture / aspect ratio

That was probably well-known to some, but it could possibly help others.
