### ISSUE TITLE
_usdAbc fails to build on OSX

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#28]
Compilation of boost::python bindings on OSX is sensitive to the order of #includes, in particular, pyport.h overriding symbols defined in cctypes. This is due to a bug in Python, that was fixed in 2.7.13 - https://bugs.python.org/issue10910

in _usdAbc, the #include of wrapAlembicTest.h before def.hpp triggers this bug, but can be worked around by switching the order of #includes, as it is in a few other wrap*cpp files in the USD codebase, making it an exception to the general coding convention of #include'ing higher-level headers first.

I'm happy to reorder the #includes in wrapAlembicTest.cpp in dev for now, and will make a pull request against this issue.

---

In file included from /Users/asluk/Desktop/bin/usd-dev/USD/pxr/usd/plugin/usdAbc/wrapAlembicTest.cpp:26:
In file included from /usr/local/include/boost/python/def.hpp:11:
In file included from /usr/local/include/boost/python/make_function.hpp:10:
In file included from /usr/local/include/boost/python/default_call_policies.hpp:10:
In file included from /usr/local/include/boost/python/to_python_value.hpp:12:
In file included from /usr/local/include/boost/python/handle.hpp:11:
In file included from /usr/local/include/boost/python/errors.hpp:13:
In file included from /usr/local/include/boost/function/function0.hpp:11:
In file included from /usr/local/include/boost/function/detail/maybe_include.hpp:13:
In file included from /usr/local/include/boost/function/function_template.hpp:13:
In file included from /usr/local/include/boost/function/detail/prologue.hpp:17:
In file included from /usr/local/include/boost/function/function_base.hpp:20:
In file included from /usr/local/include/boost/assert.hpp:84:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:466:15: error: C++ requires a type specifier for all declarations
    char_type toupper(char_type __c) const
              ^

**Comment by jtran56** [comment]
Filed as internal issue #136351.

**Comment by sunyab** [comment]
Closing this issue out, this fix is in v0.7.1. Thanks!
