### ISSUE TITLE
Hio module does not support Monochrome EXR images

### ISSUE THREAD

**Issue by JGamache-autodesk** [PixarAnimationStudios/USD#2800]
### Description of Issue

We have a unit test in MayaUSD that reads OpenEXR images with 1, 2, and 4 channels in both half and float format to make sure every image type loads correctly.

The unit test failed on Linux with 2 channel images and crashes on Windows with 1 and 2 channel images.
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/56274617/339d49dd-535c-494f-9bc6-21a993dab1aa)

### Steps to Reproduce
1. Extract these test scene files and try them all in usdview. The RGBA ones will succeed (albeit with a warning) and the RG ones will fail. The status of the R ones depend on the platform. 
 
These images used to load correctly in USD 23.8.
[OpenEXRFormats.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13312854/OpenEXRFormats.zip)

### System Information (OS, Hardware)

Windows: heap corruption crash before the scene shows
Linux: Corrupted images

### Package Versions

USD 23.11 with MaterialX 1.38.8

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8927

**Comment by meshula** [comment]
Thanks for the report, and posting test data.

**Comment by meshula** [comment]
Hmmm, the previous version of Hio does not treat your images properly. For example, the test file RG16F is loaded by Hio as the file name implies, the first channel treated as red, the second as green. See screenshot below. However, opening your image to inspect it's layer attributes, RG16F has two channels, one labeled "Y" for luminance, and one labels "A" for alpha. It should look as the second screenshot.

R16F however works as expected, in the previous version.

<img width="509" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/501238/a71858d3-6f91-4abe-b2db-1ea8dc4c1941">

<img width="99" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/501238/65afb2aa-d0ac-4b62-aad7-28264669d6f8">

**Comment by JGamache-autodesk** [comment]
In MayaUSD we expand [vec2 YA image to vec4 YYYA](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/render/vp2RenderDelegate/material.cpp#L1874) (RGB greyscale + alpha) so they render like this in our unit test:
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/56274617/59fb9a6e-f003-4a5e-b972-77dd003b7d0e)

Might be an option for the HIO image loader as well.

**Comment by meshula** [comment]
Great, that's what's intended in Hio as well, but not happening due to an error. Thanks for the confirmation of what you'd expect!

**Comment by JGamache-autodesk** [comment]
Dec 11th commit fixes the issue. Thanks!
