### ISSUE TITLE
hdPrman not loading on AlmaLinux 8 with 23.08 and 23.11

### ISSUE THREAD

**Issue by eric-with-a-c** [PixarAnimationStudios/USD#2805]
### Description of Issue
Building USD with RenderMan on AlamLinux 8 completes without any errors. However, trying to switch the renderer in USDView to RenderMan results in RenderMan not rendering and the following output:

```
Warning: in Load at line 112 of /src/OpenUSD-23.11/pxr/imaging/plugin/hdPrmanLoader/rendererPlugin.cpp -- Could not load versioned hdPrman backend: /opt/local/USD-23.11/plugin/usd/hdPrman.so: undefined symbol: _ZN5stats27SetListenerPluginSearchPathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Traceback (most recent call last):
  File "/opt/local/USD-23.11/lib/python/pxr/Usdviewq/appController.py", line 1453, in <lambda>
    self._rendererPluginChanged(pluginType))
  File "/opt/local/USD-23.11/lib/python/pxr/Usdviewq/appController.py", line 1414, in _rendererPluginChanged
    if not self._stageView.SetRendererPlugin(plugin):
  File "/opt/local/USD-23.11/lib/python/pxr/Usdviewq/stageView.py", line 988, in SetRendererPlugin
    if self._renderer.SetRendererPlugin(plugId):
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingGLEngine::SetRendererPlugin' at line 969 in file /src/OpenUSD-23.11/pxr/usdImaging/usdImagingGL/engine.cpp : 'Invalid plugin id or plugin is unsupported: HdPrmanLoaderRendererPlugin'

```
The GL renderer and Embree both work as expected. RenderMan is working on the system through Maya. USD-23.08 and USD-23.11 produce the same error.

This is how USDView is being launched:

```
PATH=$PATH:/opt/local/USD-23.11/bin PYTHONPATH=$PYTHONPATH:/opt/local/USD-23.11/lib/python:/opt/local/USD-23.11/site-packages RMANTREE=/opt/pixar/RenderManProServer-25.2 RMAN_SHADER_PATH=$RMANTREE/lib/shaders:/opt/local/USD-23.11/plugin/usd/resources/shaders RMAN_RIXPLUGINPATH=$RMANTREE/lib/plugins RMAN_TEXTUREPATH=$RMANTREE/lib/textures:$RMANTREE/lib/plugins:/opt/local/USD-23.11/plugin/usd /opt/local/USD-23.11/bin/usdview Kitchen_set.usd
```

### Steps to Reproduce
1. Build USD on AlmaLinux 8
2. Run USD view
3. Switch to Prman

### System Information (OS, Hardware)
AlamaLinux 8
GNOME-Classic

### Package Versions
RenderMan 25.2
### Build Flags
Tried with
```
build_usd.py -v --ptex --openvdb --prman --prman-location /opt/pixar/RenderManProServer-25.2 --openimageio --opencolorio --alembic --materialx --embree /opt/local/USD-23.11
```
and
```
build_usd.py -v --ptex --openvdb --prman --prman-location /opt/pixar/RenderManProServer-25.2 --openimageio --opencolorio --alembic --materialx --embree --use-cxx11-abi=1 /opt/local/USD-23.11
```

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8942

**Comment by eric-with-a-c** [comment]
The command below produced a working USD build with RenderMan support on AlmaLinux 8.

```
build_usd.py -v --ptex --openvdb --prman --prman-location /opt/pixar/RenderManProServer-25.2 \
--openimageio --alembic --materialx --embree --use-cxx11-abi=0 /opt/local/USD-23.11
```
The solve was to build with `--use-cxx11-abi=0` and to omit `--opencolorio`. Trying to build USD with OpenColorIO support while passing `--use-cxx11-abi=0` as an argument results in a non-working build. But `--use-cxx11-abi=0` is required to get a working USD build with Prman support. 

This would seem to indicate that creating a USD build on AlmaLinux 8 with support for both RenderMan and OpenColorIO is not supported at this time.

**Comment by hyc0612** [comment]
can you show the result {install_dir}/plugin/usd, I encounter the same error

**Comment by hyc0612** [comment]
> The command below produced a working USD build with RenderMan support on AlmaLinux 8.
> 
> ```
> build_usd.py -v --ptex --openvdb --prman --prman-location /opt/pixar/RenderManProServer-25.2 \
> --openimageio --alembic --materialx --embree --use-cxx11-abi=0 /opt/local/USD-23.11
> ```
> 
> The solve was to build with `--use-cxx11-abi=0` and to omit `--opencolorio`. Trying to build USD with OpenColorIO support while passing `--use-cxx11-abi=0` as an argument results in a non-working build. But `--use-cxx11-abi=0` is required to get a working USD build with Prman support.
> 
> This would seem to indicate that creating a USD build on AlmaLinux 8 with support for both RenderMan and OpenColorIO is not supported at this time.

can you show the result {install_dir}/plugin/usd, I encounter the same error

**Comment by FlorianZ** [comment]
Fwiw, we got guidance from the RenderMan team and they mentioned that having to build with `--use-cxx11-abi=0` on EL8 is consistent with their understanding to make the build compatible with RenderMan 25.

**Comment by hyc0612** [comment]
I got the same error but on windows pc

FlorianZ ***@***.***> 于2024年1月9日周二 07:16写道：
