### ISSUE TITLE
Failed to run helloWorld.py after freshly building and installing OpenUSD

### ISSUE THREAD

**Issue by Annazhang** [PixarAnimationStudios/USD#2813]
### Description of Issue

I got the following error when running helloWorld.py after successfully building OpenUSD by build_usd.py. Please help!

> (venv) ******* OpenUSD % python3 extras/usd/tutorials/helloWorld/helloWorld.py

> Traceback (most recent call last):
>   File "/Users/dev/OpenUSD/extras/usd/tutorials/helloWorld/helloWorld.py", line 26, in <module>
>     from pxr import Usd, UsdGeom
>   File "/Users/dev/OpenUSD/dist/lib/python/pxr/Usd/__init__.py", line 25, in <module>
>     Tf.PreparePythonModule()
>   File "/Users/dev/OpenUSD/dist/lib/python/pxr/Tf/__init__.py", line 89, in PreparePythonModule
>     module = importlib.import_module(
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function

### Steps to Reproduce
1. git clone https://github.com/PixarAnimationStudios/OpenUSD
2. Enter into OpenUSD folder
3. Build and install by running "python build_scripts/build_usd.py ./dist"
4. Add the following paths to PYTHONPATH and PATH respectively:
    /Users/dev/OpenUSD/dist/lib/python
    /Users/dev/OpenUSD/dist/bin
5. Run "python3 extras/usd/tutorials/helloWorld/helloWorld.py"

You will see above error.

### System Information (OS, Hardware)
OS: macOS Ventura 13.5.2
Hardware: MacBook Pro 2019, 16-inch

### Build Flags
python build_scripts/build_usd.py ./dist

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8956

**Comment by Annazhang** [comment]
When can this be fixed? I am sure this blocks a lot of people from using python module. @jesschimein 
Do you have any hint for fixing it myself? Thank you!

**Comment by nvmkuruc** [comment]
@dgovil has submitted this PR https://github.com/PixarAnimationStudios/OpenUSD/pull/2742 to support Python 3.11.  It might be worth seeing if that fixes your issue locally.

You might have to manually remove your `./dist` directory to ensure that the right version of `boost` is retrieved.

**Comment by FlorianZ** [comment]
@Annazhang, we are tied to https://vfxplatform.com/, and currently support CY2022. We understand that Python 3.11 is part of CY2024 of the reference platform, but a lot of software vendors have not yet upgraded to it. In the meantime, we hope that @dgovil's PR will help you get set up, and we are considering it for inclusion. Thank you!
