### ISSUE TITLE
build_usd.py script fails with Python 3.12

### ISSUE THREAD

**Issue by TheMostDiligent** [PixarAnimationStudios/USD#2817]
### Description of Issue

When running the build script, the following error is displayed:

```
Traceback (most recent call last):
  File "d:\GitHub\USD\build_scripts\build_usd.py", line 37, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
```

The reason is that [distutils package was removed](https://docs.python.org/3.10/install/index.html#install-index) in python 3.12

### System Information (OS, Hardware)
Windows

Commit: v23.11

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8961

**Comment by FlorianZ** [comment]
Hi @TheMostDiligent. We are tied to the [vfx](https://vfxplatform.com/), and won't be switching to Python 3.12 before calendar year 2025 at the earliest. OpenUSD 23.11 is tested with Python 3.9. Thank you for the heads up on distutils removal, though! This is something that we will have to deal with before then.
