### ISSUE TITLE
pdb's need to be in the path for Visual Studio to see the symbols.

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#282]
At the moment, after a visual studio build, all the pdb files are in the build directories, e.g.:

    C:\projects\Pixar\USD-build\build\USD\pxr\usd\lib\usdGeom\Release

In order for visual studio to actual find the symbols in a debug session, the pdb files need to be in the path. So in this case, when the lib and dll are copied to c:\projects\Pixar\USD-build\lib, the pdb should be copied as well.

Maybe this extra copy could be an option in the cmake configuration?

**Comment by jtran56** [comment]
Filed as internal issue #150707.

**Comment by sunyab** [comment]
This should be addressed by the changes in #502, which was included in the 19.05 release. Closing this out, thanks!
