### ISSUE TITLE
error LNK2019 when trying to compile 3ds Max plugin

### ISSUE THREAD

**Issue by KomodoDev** [PixarAnimationStudios/USD#2840]
### Description of Issue
Link errors when trying to use with own C++ 3ds Max plugin project.

### Steps to Reproduce
1. Download and build as usual (I've tried regular and monolithic, both experience the same issue)
2. In Visual Studio (in this case I am creating a 3ds Max plugin) add 
 #include "pxr/usd/usd/stage.h"
3. Add USD headers and lib directories
4.  Build...

Note that this error doesn't occur with some other #includes, for example layers.h and path.h. 

### System Information (OS, Hardware)
Windows

### Package Versions
Tried with USD v23, v22 and v21
Using Visual Studio 2019

### Build Flags

ERRORS:

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: void __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PathNode::_RemovePathTokenFromTable(void)const " (__imp_?_RemovePathTokenFromTable@Sdf_PathNode@pxrInternal_v0_22__pxrReserved__@@IEBAXXZ) referenced in function "protected: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PathNode::~Sdf_PathNode(void)" (??1Sdf_PathNode@pxrInternal_v0_22__pxrReserved__@@IEAA@XZ)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PrimPartPathNode::operator delete(void *)" (__imp_??3Sdf_PrimPartPathNode@pxrInternal_v0_22__pxrReserved__@@SAXPEAX@Z) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PropPartPathNode::operator delete(void *)" (__imp_??3Sdf_PropPartPathNode@pxrInternal_v0_22__pxrReserved__@@SAXPEAX@Z) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PrimPathNode::~Sdf_PrimPathNode(void)" (__imp_??1Sdf_PrimPathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PrimPropertyPathNode::~Sdf_PrimPropertyPathNode(void)" (__imp_??1Sdf_PrimPropertyPathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PrimVariantSelectionNode::~Sdf_PrimVariantSelectionNode(void)" (__imp_??1Sdf_PrimVariantSelectionNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_TargetPathNode::~Sdf_TargetPathNode(void)" (__imp_??1Sdf_TargetPathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_RelationalAttributePathNode::~Sdf_RelationalAttributePathNode(void)" (__imp_??1Sdf_RelationalAttributePathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_MapperPathNode::~Sdf_MapperPathNode(void)" (__imp_??1Sdf_MapperPathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_MapperArgPathNode::~Sdf_MapperArgPathNode(void)" (__imp_??1Sdf_MapperArgPathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_ExpressionPathNode::~Sdf_ExpressionPathNode(void)" (__imp_??1Sdf_ExpressionPathNode@pxrInternal_v0_22__pxrReserved__@@AEAA@XZ) referenced in function "void __cdecl pxrInternal_v0_22__pxrReserved__::intrusive_ptr_release(class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const *)" (?intrusive_ptr_release@pxrInternal_v0_22__pxrReserved__@@YAXPEBVSdf_PathNode@1@@Z)

1>UsdInterface.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) private: static char * * pxrInternal_v0_22__pxrReserved__::Sdf_Pool<struct pxrInternal_v0_22__pxrReserved__::Sdf_PathPrimTag,24,8,16384>::_regionStarts" (__imp_?_regionStarts@?$Sdf_Pool@USdf_PathPrimTag@pxrInternal_v0_22__pxrReserved__@@$0BI@$07$0EAAA@@pxrInternal_v0_22__pxrReserved__@@0PAPEADA) referenced in function "public: __cdecl pxrInternal_v0_22__pxrReserved__::Sdf_PathNodeHandleImpl<struct pxrInternal_v0_22__pxrReserved__::Sdf_Pool<struct pxrInternal_v0_22__pxrReserved__::Sdf_PathPrimTag,24,8,16384>::Handle,1,class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const >::~Sdf_PathNodeHandleImpl<struct pxrInternal_v0_22__pxrReserved__::Sdf_Pool<struct pxrInternal_v0_22__pxrReserved__::Sdf_PathPrimTag,24,8,16384>::Handle,1,class pxrInternal_v0_22__pxrReserved__::Sdf_PathNode const >(void)" (??1?$Sdf_PathNodeHandleImpl@UHandle@?$Sdf_Pool@USdf_PathPrimTag@pxrInternal_v0_22__pxrReserved__@@$0BI@$07$0EAAA@@pxrInternal_v0_22__pxrReserved__@@$00$$CBVSdf_PathNode@3@@pxrInternal_v0_22__pxrReserved__@@QEAA@XZ)

1>UsdInterface.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) private: static char * * pxrInternal_v0_22__pxrReserved__::Sdf_Pool<struct pxrInternal_v0_22__pxrReserved__::Sdf_PathPropTag,24,8,16384>::_regionStarts" (__imp_?_regionStarts@?$Sdf_Pool@USdf_PathPropTag@pxrInternal_v0_22__pxrReserved__@@$0BI@$07$0EAAA@@pxrInternal_v0_22__pxrReserved__@@0PAPEADA)

1>C:\Program Files\Autodesk\3ds Max 2023\Plugins\ThiagoUsdUtilities.dlu : fatal error LNK1120: 13 unresolved externals

1>    41 Warning(s)

1>    14 Error(s)

1>

1>Time Elapsed 00:00:04.17

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9009

**Comment by KomodoDev** [comment]
I seem to have fixed it...
It seems to compile fine anyway.

In Visual Studio go to

Project -> Properties 
Linker -> Input -> Additional Dependencies
Add "usd_ms.lib" to the list. 

Was I stuck with this because my C++ experience is limited or this is something unexpected?

**Comment by FlorianZ** [comment]
@KomodoDev, gald you were able to fix your problem. This could be an issue with the 3DS Max plugin, but we don't maintain it. We are wondering if there is perhaps someone at Autodesk who has additional information to share?

Closing this for now, but feel free to reopen if you run into this again.

**Comment by aaron-m-source** [comment]
Hi
I have the same issue, but i can't find usd_ms.lib anywhere, can you direct me please how to get that file?

thanks
