### ISSUE TITLE
Houdini: usdunpack SOP clamps between startTimeCode/endTimeCode

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#285]
### Description of Issue

The usdunpack SOP currently clamps incoming time samples to the stage's `startTimeCode` and `endTimeCode` metadata.  This was originally [reported on usd-interest](https://groups.google.com/d/msg/usd-interest/zjX5a7R_D4k/WJHqm4dBBQAJ) and acknowledged by Michael Rice with the following note:

> We do consider this a bug. We think it should unpack without clamping to the startTimeCode and endTimeCode metadata.
> This should be fixed with some larger caching work that's in progress, but if that doesn't make it to our next push to github we can make another fix for the time being.
> Feel free to open an issue on github if you'd like to track it.

### Package Versions

Houdini 16.0.705, USD 0.8.0+ (2763a843b9)

**Comment by jtran56** [comment]
Filed as internal issue #151052.

**Comment by sunyab** [comment]
This was addressed as part of commit dd892598b85c886b33576f0e2e34da0978804c85 in 0.8.1. Closing this out, thanks!
