### ISSUE TITLE
Maya Plugin crashes

### ISSUE THREAD

**Issue by sanlwy** [PixarAnimationStudios/USD#288]
### Steps to Reproduce
1. Create a ReferenceAssembly node and load File Path testParent.usda file 
[cube.usda.zip](https://github.com/PixarAnimationStudios/USD/files/1318554/cube.usda.zip)
2. Set Prim Path /set_devusdpublicwashroom_master
3. Refresh GUI and select variants old_style and static (can be any variants)
4. Select "Scene Assembly->Expanded"
5 Expand to the leaf
6 Select "Scene Assembly->Expanded" and maya will crash.

Seems like the issue is if we have a variantSet in a parent and we try to expand a child with different variantSet causes the plugin to crash

**Comment by jtran56** [comment]
Filed as internal issue #151232.
