### ISSUE TITLE
Asset Resolver can't use ? in paths

### ISSUE THREAD

**Issue by dgovil** [PixarAnimationStudios/USD#289]
### Description of Issue

Hi there, 
It appears the asset resolver system doesn't allow for `?` in the path.
Unfortunately our asset resolution system uses URIs to resolve asset paths so there are a lot of uses of `?` and this limitation was causing issues the plugin I was writing.

In the meantime I'm going to use a different character and  do an internal replacement before passing to our internal resolver, but it would be great to have a way to support the `?` since they're a common token in the URI spec.

Also if possible, I'd ask if it could be documented in the doxygen docs in the interim to a solution?

Some discussion here where spiff asked me to file a ticket for this.
https://groups.google.com/forum/?fromgroups=#!topic/usd-interest/29BSF217glE

**USD Version**: 0.8.0

Thank you all very much!

**Comment by jtran56** [comment]
Filed as internal issue #151233.
