### ISSUE TITLE
Error trying to build USD

### ISSUE THREAD

**Issue by CraigLaMorte** [PixarAnimationStudios/USD#2912]
### Description of Issue
Tried building USD from visual studio 2022 command prompt and receieved error
### Steps to Reproduce
1.  ran C:\OpenUSD\build_scripts>python build_usd.py "C:\USD"

error
MSBUILD : error MSB4166: Child node "11" exited prematurely. Shutting down.

ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:12'
See C:\USD\build\MaterialX-1.38.7\log.txt for more details.

### System Information (OS, Hardware)
Windows 10
### Package Versions
23.11
### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/13992046/log.txt)

[MSBuild_pid-44440_537c2f4b6f0b4762b05a1b8c2bab322e.failure.txt](https://github.com/PixarAnimationStudios/OpenUSD/files/13992095/MSBuild_pid-44440_537c2f4b6f0b4762b05a1b8c2bab322e.failure.txt)

**Comment by sunyab** [comment]
@CraigLaMorte Your log files indicate your system ran out of memory trying to compile MaterialX. The build script will try to use all of the CPUs on your machine to build, but if there's not enough memory for all of the compile tasks to run at the same time you can run into problems. I've typically seen this on resource-constrained environments like VMs.

One thing you can try is to use the '-j' argument to set the number of parallel jobs to a lower value. If you run build_usd.py with no parameters, the help output for the argument will tell you the value it's using by default -- try using a lower value.

**Comment by CraigLaMorte** [comment]
Thanks I tried closing everything else and running it and looks like it worked
