### ISSUE TITLE
Boost error in Cmake configure

### ISSUE THREAD

**Issue by CraigLaMorte** [PixarAnimationStudios/USD#2916]
### Description of Issue
Cloned the latest USD repository, tried to load it up on Cmake.  Clicked configure and an error shows up

CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: python310) (found version "1.78.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindBoost.cmake:2392 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:132 (find_package)
  CMakeLists.txt:23 (include)

### Steps to Reproduce
1. Opened up Cmake and pointed it to repository, and new build folder

### System Information (OS, Hardware)
Windows 10
### Package Versions
23.11

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9203

**Comment by nvmkuruc** [comment]
@CraigLaMorte Do you know if this is still an issue for you?  We've been able to build OpenUSD (including 23.11) on windows with `cmake` version 3.28.1.

**Comment by CraigLaMorte** [comment]
I was able to build USD. thanks

**Comment by nvmkuruc** [comment]
@jesschimein Sounds like this might be able to be closed.
