### ISSUE TITLE
Katana: wrong materialAssign value for assignments within instances

### ISSUE THREAD

**Issue by nxkb** [PixarAnimationStudios/USD#292]
### Description of Issue
Material assignment breaks in katana for instanced assets due to the materialAssign attribute being set to a non-existent path.

Instead of getting a path that starts like `/root/Masters/primName/` the path starts with `/root/__Master_4`. The rest of the path is correct, but the prefix is wrong. 

### Steps to Reproduce
1. Create a Usd file that has some material assignment and set the top prim to be instanceable. Then reference that file into a stage a couple times.
2. Create a PxrUsdIn node to read the parent file and set instanceMode="as sources and instances"
3. Check out the value of the materialAssign attribute on the scene graph location with the assignment. (somewhere under /root/Masters/...)

### System Information (OS, Hardware)
Linux

### Package Versions
tested on usd-0.7.6 and usd-0.8.0

**Comment by jtran56** [comment]
Filed as internal issue #151546.
