### ISSUE TITLE
Converting Mesh Sequence to USD

### ISSUE THREAD

**Issue by sunshineatnoon** [PixarAnimationStudios/USD#2921]
Is it possible to convert a sequence of meshes into a USD file? I tried to use Blender [add-on](https://github.com/neverhood311/Stop-motion-OBJ) to import a mesh sequence and then exported as an USD file, but the exported USD overlaps meshes from different timesteps.

**Comment by dgovil** [comment]
usdstitchclips should do the trick I think 

https://openusd.org/release/toolset.html

**Comment by meshula** [comment]
That's quite a cool topic to investigate! There's nothing to modify or fix in OpenUSD though, so I'm closing this issue. Please feel free to continue discussion here, or to bring the conversation over to the AOUSD forum (https://forum.aousd.org) or to the Academy Software Foundation slack (https://join.slack.com/t/academysoftwarefdn/shared_invite/zt-2at1248ps-UzGbBrikPTGS6TsODfYphg); both forums have people with a lot of experience with this sort of thing!
