### ISSUE TITLE
Document USD_DEFAULT_FILE_FORMAT Usage

### ISSUE THREAD

**Issue by mati-nvidia** [PixarAnimationStudios/USD#2922]
### Description of Issue
The USD_DEFAULT_FILE_FORMAT environment variable is currently only documented in the `usdcat` help: https://openusd.org/release/toolset.html#usdcat and the accepted values are only discoverable by looking at the source code. We should make this easier to discover.

One possible place for this information is here: https://openusd.org/release/usdfaq.html#what-file-format-is-my-usd-file I can create a PR for this issue if we like that solution.

**Comment by mati-nvidia** [comment]
See linked PR for the proposed improvement. We would like to try to squeeze this in for this upcoming release so that we can link to it from our Omniverse developer docs.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9212

**Comment by jesschimein** [comment]
Closing as completed; see #2924
