### ISSUE TITLE
Small fixes in the UsdSkel documentation

### ISSUE THREAD

**Issue by koen-v** [PixarAnimationStudios/USD#2923]
Hello all,

I was looking at the example code for writing an animated skeleton:
[Universal Scene Description: API Introduction (openusd.org) 1](https://openusd.org/release/api/_usd_skel__a_p_i__intro.html#UsdSkel_API_WritingSkels)

the example mentions:

binding = UsdSkel.BindingAPI.Apply(skel.GetPrim())
binding.CreateSkeletonRel().SetTargets([anim.GetPrim().GetPath()])

I believe this second line should instead read:
binding.CreateAnimationSourceRel().SetTargets([anim.GetPrim().GetPath()])

and a small mistake appearing twice:

valid,whyNot = topo.Validate()
if not valid:
Tf.Warn(“Invalid topology: %s”%reason)
return False

here I think reason  should be whyNot?

Thanks,
Koen

**Comment by matiascodesal** [comment]
Hey @koen-v. I recently addressed this in another issue and it should hopefully be in the next release. For now, please take a look at the "dev" branch docs to confirm that this issue has been addressed: https://openusd.org/dev/api/_usd_skel__a_p_i__intro.html#UsdSkel_API_WritingSkels

**Comment by spiffmon** [comment]
Sorry I forgot about that, @matiascodesal ! And once again, thanks - closing.

**Comment by koen-v** [comment]
Perfect, thanks both!
