### ISSUE TITLE
Maya 2018 - Geometry not being shown in Viewport

### ISSUE THREAD

**Issue by dalgos-adsk** [PixarAnimationStudios/USD#293]
### Description of Issue
Hi there,

I'm trying to use the usdmaya plugin with maya 2018. The seems to be loading fine but it is generating some errors in the background.

When **loading the plug**, I get these errors :

```
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 30 of c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/fallbackSurface.glslfx. Unknown section tag "configuration
"
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 33 of c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/simpleLightingShader.glslfx. Unknown section tag "configuration
"
```

When **creating a UsdReferenceAssembly:**

> API error detected in C:\USD-DEV\USD\third_party\maya\lib\usdMaya\referenceAssembly.cpp at line 715
> : (kFailure): Unexpected Internal Failure
> 
> API error detected in C:\USD-DEV\USD\third_party\maya\lib\usdMaya\referenceAssembly.cpp at line 564
> : (kFailure): Unexpected Internal Failure

*These were there as well in the 2017 Update 4 as well, and there didn't seem to be any side effects, I am not too concern about these ones..

Adding File Path to the endToEnd Ball.usd and changing the representation to Collapsed:

 ```
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 33 of c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/renderPassShader.glslfx. Unknown section tag "configuration"
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 33 of c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/renderPassIdShader.glslfx. Unknown section tag "configuration
"
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 32 of c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/fallbackLightingShader.glslfx. Unknown section tag "configuration
"
Runtime Error: in _ParseVersionLine at line 441 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Version mismatch. istream specifies 0.10, but c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/mesh.glslfx specifies 0.00
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 30 of c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/compute.glslfx. Unknown section tag "configuration
"
Warning: in Link at line 180 of C:\USD-DEV\USD\pxr\imaging\lib\hd\glslProgram.cpp -- Failed to link shader: 
Compute info
------------
(0) : error C7006: no work group size specified

Coding Error: in GetComputeProgram at line 268 of C:\USD-DEV\USD\pxr\imaging\lib\hd\glslProgram.cpp -- Fail to link smoothNormalsFloatToPacked
Runtime Error: in _ParseVersionLine at line 441 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Version mismatch. istream specifies 0.10, but c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/frustumCull.glslfx specifies 0.00
Coding Error: in _GPUFrustumCullingXFB at line 1357 of C:\USD-DEV\USD\pxr\imaging\lib\hd\indirectDrawBatch.cpp -- Failed verification: ' glslProgram '
Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 30 of c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/fallbackSurface.glslfx. Unknown section tag "configuration
"
Coding Error: in _GetDrawingProgram at line 241 of C:\USD-DEV\USD\pxr\imaging\lib\hd\drawBatch.cpp -- Failed verification: ' res '
Coding Error: in ExecuteDraw at line 1020 of C:\USD-DEV\USD\pxr\imaging\lib\hd\indirectDrawBatch.cpp -- Failed verification: ' glslProgram '
```

### Steps to Reproduce
1. Load the plugin with Maya 2018
2. Create UsdReferenceAssembly
3. Change attribute File Path to EndToEnd asset Ball.usd
4. No geometry is being shown in the VP2

### System Information (OS, Hardware)

Win7
Quadro K2200 with latest update

### Package Versions
Maya 2018 Update 1
USD master branch (V0.8.0)

### Build Flags

None specifically

I saw in the dev branch you guys made the changes to make it work with the Namespaced API ( I did these as well). 
Any other changes were made to make it work with Maya 2018 ?

**Comment by jtran56** [comment]
Filed as internal issue #151544.

**Comment by spiffmon** [comment]
Hi Sebastien,
    We are currently unable to test Maya 2018, as we haven't quite finished our internal upgrade to Qt 5 (we're **almost** there). So we can't yet provide any feedback on issues there.  We're tracking this bug, though, and when we'll take a look when we get there.

**Comment by sunyab** [comment]
Hi @dalgos-adsk, 

I'm wondering if the errors are due to Windows line ending differences. What compiler are you using? Do you have the 'core.autocrlf' set in git to convert line endings to Windows CRLFs? If you convert the .glslfx files in:

c:/USD-DEV/build/share/usd/plugins/hd/resources/shaders/
 c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/

To Unix line endings, do the errors go away?

**Comment by dalgos-adsk** [comment]
Hey @spiffmon thanks for the update. I seem to be very close to make this work, well I think :P. Will let you know if there's something I find here

@sunyab thanks for the response. I  gave this a shot and am getting new errors now : 

> Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 33 of c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/simpleLightingShader.glslfx. Unknown section tag "configuration
> "
> Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 33 of c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/renderPassShader.glslfx. Unknown section tag "configuration
> "
> Runtime Error: in _ParseSectionLine at line 378 of C:\USD-DEV\USD\pxr\imaging\lib\glf\glslfx.cpp -- Syntax Error on line 33 of c:/USD-DEV/build/share/usd/plugins/hdx/resources/shaders/renderPassIdShader.glslfx. Unknown section tag "configuration
> "
> Warning: in CompileShader at line 137 of C:\USD-DEV\USD\pxr\imaging\lib\hd\glslProgram.cpp -- Failed to compile shader (GL_VERTEX_SHADER): 
> 0(385) : error C1008: undefined variable "GetWorldToViewMatrix"
> 0(387) : error C1008: undefined variable "GetWorldToViewInverseMatrix"
> 0(397) : error C1008: undefined variable "GetProjectionMatrix"
> 0(398) : error C1008: undefined variable "GetPointSize"
> 0(399) : error C1008: undefined variable "ApplyClipPlanes"
> 
> Coding Error: in _GetDrawingProgram at line 241 of C:\USD-DEV\USD\pxr\imaging\lib\hd\drawBatch.cpp -- Failed verification: ' res '
> Coding Error: in ExecuteDraw at line 1020 of C:\USD-DEV\USD\pxr\imaging\lib\hd\indirectDrawBatch.cpp -- Failed verification: ' glslProgram '
> Coding Error: in _GetDrawingProgram at line 241 of C:\USD-DEV\USD\pxr\imaging\lib\hd\drawBatch.cpp -- Failed verification: ' res '
> Coding Error: in ExecuteDraw at line 1020 of C:\USD-DEV\USD\pxr\imaging\lib\hd\indirectDrawBatch.cpp -- Failed verification: ' glslProgram '
> Coding Error: in _GetDrawingProgram at line 241 of C:\USD-DEV\USD\pxr\imaging\lib\hd\drawBatch.cpp -- Failed verification: ' res '
> Coding Error: in ExecuteDraw at line 1020 of C:\USD-DEV\USD\pxr\imaging\lib\hd\indirectDrawBatch.cpp -- Failed verification: ' glslProgram '

This is weird though because I can make the exact same repo with 2017 Update 4 (Without having to change the \r\n to \n )

**Comment by dalgos-adsk** [comment]
Hello, This is not an issue in the dev branch. Everything working fine on my side. We can close this
