### ISSUE TITLE
Disabling default camera light during rendering

### ISSUE THREAD

**Issue by kaigg96** [PixarAnimationStudios/USD#2941]
### Description of Issue
I’ve created an animation and now I want to download images representing each frame. I’ve tried using both the usdrecord command line prompt and the FrameRecorder.Record() function in a script, but in both cases there’s an extra light source that I can’t figure out how to remove (GL renderer). In usdview, it can be turned off by deselecting the default camera light, but I don’t see a way to disable that light in either record function.

Per Tom C on the OpenUSD forums - It should only affect renderers that support simple lights, i.e. Storm, but it doesn’t look like there’s a way to disable that right now. If you want to file a github issue, we can use that to let you know when we fix it up; it’s definitely something we’d like to address.

**Comment by pablode** [comment]
See also PR #2762

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9284

**Comment by tcauchois** [comment]
Closing this as completed in light of the referenced fix that went in Feb 29th.
