### ISSUE TITLE
compiled version for windows

### ISSUE THREAD

**Issue by yogiyog** [PixarAnimationStudios/USD#295]
hello, can anyone provide me a prebuilt version of USD viewer? i have tried a lot of time to build it but it fails with boost libraries not found.

thanks in advance

**Comment by jtran56** [comment]
Filed as internal issue #151709.

**Comment by sunyab** [comment]
Hi @yogiyog, sorry you're having trouble building USD! If you're trying to build using Visual Studio 2017, this post might help you out: https://github.com/PixarAnimationStudios/USD/issues/294#issuecomment-334287432.

We currently don't supply prebuilt binaries for USD in this repository. I'd recommend posting to the [usd-interest forum](https://groups.google.com/forum/#!forum/usd-interest) to see if anyone there can help, but you may have better luck trying to get a successful build instead.

**Comment by sunyab** [comment]
I saw you posted to the usd-interest forum, so I'm going to close this issue out. Thanks!
