### ISSUE TITLE
Allow non-root level prims as default prims

### ISSUE THREAD

**Issue by dlarsson-adobe** [PixarAnimationStudios/USD#2951]
### Description of Issue
In some situations it would be very useful to have a non-rootlevel prim as a default prim.

A typical example would be a materialx document. It can serve both as a library in which you might have multiple materials in a hierarchy which you can reference or sublayer in preserving that hierarchy. On the flipside, a large percentage of situation there is only a single material in the document. If someone just wanti to assign the materialx file as a material on a prim the notion of a default prim would point to a specific material being the one to assign.

At the moment the document has to either pick putting materials in the root of the namespace so it can be a default material or in a hierarchy that looks like a nice material library. Allowing a non-root level prim to be the default prim can give you both these behaviors in a convenient way where you point the default prim to a specific material in the hierarchy and if you sublayer or reference in / you'll get the material library behavior.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9314
