### ISSUE TITLE
usdview cannot be opened on a specific frame whilst preserving full timeline range

### ISSUE THREAD

**Issue by kfawcett-shell** [PixarAnimationStudios/USD#296]
### Description of Issue
There is no method to launch usdview at a specific frame in a sequence whilst also preserving the full timeline range specified by the --ff and --lf flags.

Proposing to add an additional command line argument, `--cf --currentFrame CURRENTFRAME`  that would work in conjunction with the existing ff and lf arguments to allow this.

**Comment by jtran56** [comment]
Filed as internal issue #151710.

**Comment by ianlawson1234** [comment]
We are currently adding this functionality over at ILM - can I be assigned please? :smile:

**Comment by sunyab** [comment]
This was addressed with @ianlawson's work and has been released in 19.07. Closing this out, thanks!
