### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'CreatePrimvar' and .Set parameter error

### ISSUE THREAD

**Issue by mudworker** [PixarAnimationStudios/USD#2963]
I tried to use the `usdzconvert `command on Windows to convert the glb file into a usdz file.

An exception is thrown at the beginning: AttributeError: 'Mesh' object has no attribute 'CreatePrimvar',
I referred to the method provided by this connection（https://github.com/PixarAnimationStudios/OpenUSD/issues/2628） and put
`uvs = usdGeom.CreatePrimvar(primvarName, Sdf.ValueTypeNames.TexCoord2fArray, UsdGeom.Tokens.vertex)`
Converted to
`primvar_api = UsdGeom.PrimvarsAPI(usdGeom.GetPrim())`
`uvs = primvar_api.CreatePrimvar("normals", Sdf.ValueTypeNames.Normal3fArray, UsdGeom.Tokens.vertex)`
This issue was initially resolved.

But a new problem arises:
I use `uvs.Set(newData)`, but an error was thrown:
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/bf29ce5b-5a3b-4779-b22f-9f92cc938263)
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/9eb907ad-1d26-4bb0-9612-be6013d8c772)

and I tried commenting out this code (`uvs.Set(newData)`), which caused the texture of the generated usdz file to be messed up (usdzARKitCheck Fail):
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/a735422b-cf09-43c8-b8d2-79ecd8cd0192)

How can I modify the `.Set()` method or `newData` parameters to run `usdzconvert` correctly?

BTW, my USD version is 23.11
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/23652911/11538eb9-6d05-4490-a739-ee63c3eca7e4)

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9345

**Comment by lanxinger** [comment]
we are also facing this issue with the latest release (24.03)

**Comment by mudworker** [comment]
This issue has been resolved, thanks for spiffmon's reply in https://github.com/PixarAnimationStudios/OpenUSD/issues/2628

**Comment by pixar-oss** [comment]
Resolved in https://github.com/PixarAnimationStudios/OpenUSD/issues/2628
