### ISSUE TITLE
USD compilation failed

### ISSUE THREAD

**Issue by orion160** [PixarAnimationStudios/USD#2968]
Hi I am getting hands on USD and this is the basic setup I have. `pxr_ROOT` is already set

Environment info:

```
Edition	Windows 11 Pro
Version	23H2
Installed on	‎2/‎5/‎2024
OS build	22631.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0
#
OpenUSD 24.03
#
MSVC 19.39.33520
```

```cpp
cmake_minimum_required(VERSION 3.28)
project("USD Example" LANGUAGES C CXX)

find_package(pxr CONFIG REQUIRED)

include_directories(${PXR_INCLUDE_DIRS})
link_libraries(${PXR_LIBRARIES})    

add_executable(main)
set_target_properties(main PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED YES
    CXX_EXTENSIONS NO
)
target_sources(main PRIVATE main.cpp)
target_link_libraries(main PRIVATE usdGeom)
```

On the build I get

[build.log](https://github.com/PixarAnimationStudios/OpenUSD/files/14393307/build.log)

**Comment by orion160** [comment]
It seems that with only `pxrConfig.cmake` and `target_link_libraries(<tgt> usdGeom)` should work.
I think the issue is on MSVC version. I'll try Linux setup

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9354

**Comment by orion160** [comment]
Oh, the problem is with `MIN` and `MAX` macro from `Windows.h`

It should be solved with `#define NOMINMAX`
