### ISSUE TITLE
The tutorialPlugin is not displayed in the usdview

### ISSUE THREAD

**Issue by Garfield9986** [PixarAnimationStudios/USD#2973]
### Description of Issue
I followed the official tutorial to add the tutorialplugin to the usdview, but I didn't find the plugin in the usdview window.
### Steps to Reproduce
1. Following the official tutorial（https://openusd.org/release/tut_usdview_plugin.html）
2.  I put the __init__. py file and plugInfo.json file into the tutorialPlugin folder, and the tutorialPlugin folder into the usdviewPlugins folder, Also set the environment variable PYTHONPATH to F:\OpenUSD\ openUSd-23.08 \ openUSd-23.08 \usdviewPlugins, The environment variable PXR_PLUGINPATH_NAME is set to F:\OpenUSD\ openUSd-23.08 \ openUSd-23.08 \usdviewPlugins\tutorialPlugin.
When I used the "usdview HelloWorld.usda" command in anaconda prompt to open the scene, I didn't see usdview loading the usdviewPlugins into the top menu.

Contents of __init__. py file:

    from pxr import Tf
    from pxr.Usdviewq.plugin import PluginContainer

    def printMessage(usdviewApi):
    print("Hello, World!")

    class TutorialPluginContainer(PluginContainer):

    def registerPlugins(self, plugRegistry, usdviewApi):

        self._printMessage = plugRegistry.registerCommandPlugin(
            "TutorialPluginContainer.printMessage",
            "Print Message",
            printMessage)

    def configureView(self, plugRegistry, plugUIBuilder):

        tutMenu = plugUIBuilder.findOrCreateMenu("Tutorial")
        tutMenu.addItem(self._printMessage)

    Tf.Type.Define(TutorialPluginContainer)

plugInfo.json file contents:

        {
          "Plugins": [
            {
              "Type": "python",
              "Name": "tutorialPlugin",
              "Info": {
                "Types": {
                  "tutorialPlugin.TutorialPluginContainer": {
                    "bases": [ "pxr.Usdviewq.plugin.PluginContainer" ],
                    "displayName": "Tutorial plugin"
                  }
                }
              }
            }
          ]
        }

One notable detail is that when I set the environment variable, when PYTHONPATH is the user variable, its value is F:\OpenUSD\ openUSd-23.08 \ openUSd-23.08 \install\lib\python, when PYTHONPATH is the system variable, Its value is F:\OpenUSD\ openUSd-23.08 \ openUSd-23.08 \usdviewPlugins, do not know whether this has an impact?
### System Information (OS, Hardware)
The operating system of my computer is windows10, and the openusd version is 23.08.
### Build Flags
Strangely, after making the changes in the environment variables, I could only open usdview on the command line, and when I opened the usdview window with omniverse, it would blink.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9364

**Comment by Garfield9986** [comment]
> 作为内部问题提交 #USD-9364

It seems that because I have both omniverse and manually compiled openusd on my computer, when I removed manually compiled openusd (clearing environment variables) and re-opened usdview in omniverse, the plugin correctly reflected in the usdview interface.
In addition, if I do not delete the manually compiled openusd library, only delete the openusd environment variable (PYTHONPATH) set during manual compilation, and re-open usdview in omniverse to see the loaded plug-in. But when I add back the openusd environment variable (PYTHONPATH) that I set during manual compilation, opening usdview on the command line results in the following error: ModuleNotFoundError: No module named 'pxr.Usdviewq'

**Comment by FlorianZ** [comment]
Thanks for the update, @Garfield9986 . Looks like you're unblocked, but feel free to reopen if you still think this is an OpenUSD issue. Thank you!
