### ISSUE TITLE
HDF5 download URL raise 404 Not Found

### ISSUE THREAD

**Issue by davidlatwe** [PixarAnimationStudios/USD#298]
### Description of Issue
[HDF5 download URL](https://github.com/PixarAnimationStudios/USD/blob/496775539c324af7cb2ea12ddbb80720865b6cb2/build_scripts/build_usd.py#L745) raise "404 Not Found".

#### Fix :

* Change the protocol from `http` to `https` can fix this for me.

### Steps to Reproduce
1. run `build_usd.py` with `hdf5` flag
2. wait for the download action

### System Information (OS, Hardware)
windows 10 (Hyper-V VM)
python 2.7.14

### Package Versions
`USD 0.8.0`

### Build Flags
`--alembic --hdf5`

**Comment by jtran56** [comment]
Filed as internal issue #151979.
