### ISSUE TITLE
Building with Ninja on Windows fails saying it does not know about x64 configuration

### ISSUE THREAD

**Issue by ggarra13** [PixarAnimationStudios/USD#2993]
### Description of Issue

Title says it all.

### Steps to Reproduce
1. Call python script with --cmake-args "-G Ninja"

### System Information (OS, Hardware)
Windows

**Comment by sunyab** [comment]
Does this work if you call the script with "--generator Ninja" instead of passing in a special cmake arg?

**Comment by ggarra13** [comment]
Yes, that fixed it.  Thanks!
