### ISSUE TITLE
Inconsistent opensubdiv3 headers

### ISSUE THREAD

**Issue by PeterShinners** [PixarAnimationStudios/USD#3]
The build system in `FindOpenSubdiv.cmake` looks for `${OPENSUBDIV_INCLUDE_DIR}/opensubdiv/version.h`, but the source code in pxOsd is referencing `#include <opensubdiv3/far/topologyRefiner.h>`. I'm not sure if `opensubdiv` or `opensubdiv3` is the preferred include path, but on my Arch Linux system the [opensubdiv package](https://www.archlinux.org/packages/community/x86_64/opensubdiv) put them under `/usr/include/opensubdiv`

**Comment by waywardmonkeys** [comment]
Building and installing the `opensubdiv` code on Mac OS X also put them in `.../opensubdiv`

**Comment by meshula** [comment]
Similar issue exists for ubuntu.

**Comment by ZeroCrunch** [comment]
And for Windows.

**Comment by amooty** [comment]
Filed as internal issue #135155.

**Comment by mont29** [comment]
erf… just saw that one, fwiw fixed this in [own fork](https://github.com/mont29/USD), and created a [pull request](https://github.com/PixarAnimationStudios/USD/pull/20)

**Comment by sunyab** [comment]
This should be fixed with 259a55f. Closing!
