### ISSUE TITLE
In sceneDelegate.h displacement defaults to true but a comment says the oppposite

### ISSUE THREAD

**Issue by lanierd-adsk** [PixarAnimationStudios/USD#3033]
### Description of Issue
https://github.com/PixarAnimationStudios/OpenUSD/blob/f941bce34505c88eaf32dc79f36eab2659b2b1ee/pxr/imaging/hd/sceneDelegate.h#L122
This line says displacement defaults to false but it seems that the default is true everywhere in this file.

### Steps to Reproduce
1.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9525
