### ISSUE TITLE
How do you silence TBB warnings during compiling?

### ISSUE THREAD

**Issue by ColinKennedy** [PixarAnimationStudios/USD#3035]
While working with USD, for as long as I can remember back to USD 19.11, there are warnings when including USD headers. I'd like to ideally have "warnings as errors" `-Werror` enabled but warnings like these would false positive and prevent builds. I'd like to completely silence them, how can I do that?

```
.../USD-v24.03-python-3.10.12/include/tbb/task.h|21 col 139| note: ‘#pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.’
||    21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
```

I tried...

1. Using preprocessor pragmas to quiet the warning

```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#include <pxr/usd/sdf/layer.h>
#pragma GCC diagnostic pop
```

2. Defining `#define message(ignore)` so calls to `#pragma message` will do nothing instead

Neither approach as worked so far.

Secondarily if the code can be updated to not have these warnings, that'd be also great (hence this GitHub issue to track it).

**Comment by spiffmon** [comment]
Hi Colin,
    That warning will go away when building OpenUSD with OneTBB, which we
will be delivering support for soon.  It will remain for those (like us)
who still need to use <OneTBB for awhile.

--spiff

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9546

**Comment by dillondf** [comment]
I was able to suppress this with:
`#define TBB_SUPPRESS_DEPRECATED_MESSAGES 1`

**Comment by nvmkuruc** [comment]
Now that oneTBB is available as an option, do you think this can be closed @jesschimein and @spiffmon?
