### ISSUE TITLE
Is there a way to perform asset resolution?

### ISSUE THREAD

**Issue by MootoolsSoftware** [PixarAnimationStudios/USD#3037]
We are using TinyUSD and we currently have difficulties with asset identifier.

`
tinyusdz::tydra::RenderSceneConverter converter;
tinyusdz::tydra::RenderScene renderScene;
ret = converter.ConvertToRenderScene(stage, &renderScene);
`

After calling ConvertToRenderScene, your lib returns textures/images containing only asset_identifier.

So the question is : **how to get the full file path on disk or to get access to the unpack texture embed in the usdz file?**

We have noticed that all asset_identifiers were starting by 0 (0/TheTexture.jpg).

* Does the 0 is related to a folder name "0" or is it an internal tag?
* The patch seems to correspond to a ressource which is in the usd file? If so, how to get access to the ressource through the lib?
* What is the way to perform asset resolution in a general an universal way (whatever the file is, usdz or not)?

Thanks for your help!

**Comment by dgovil** [comment]
Hi @MootoolsSoftware ,
Since you're using TinyUSDZ, I would recommend asking on that project instead https://github.com/syoyo/tinyusdz/issues
The projects do not share the same API or maintainers so we'd be unable to help answer this here.
