### ISSUE TITLE
Consider changing jfrog boost repository to sourceforge's.

### ISSUE THREAD

**Issue by ggarra13** [PixarAnimationStudios/USD#3040]
### Description of Issue

This is a minor but annoying issue.

Currently, boost is fetched from the repository jfrog.com.  Unfortunately, this repository fails quite often on Github Actions runs.
The mirror at sourceforge, is hardly ever used and it does not seem to suffer from those problems.
The biggest problem is with macOS 12 machines.
Consider switching to sourceforge or use sourceforge as a backup repository in case jfrog fails a number of times.

### Steps to Reproduce
1. Send a GitHub Actions job compiling OpenUSD on macOS 12 and you will likely see it fail.

Here's a sample run of a failing workflow run:

https://github.com/ggarra13/mrv2/actions/runs/8665138526/job/23763139264

### System Information (OS, Hardware)

Affects all platforms, but on GitHub Actions mainly macOS 12.

### Package Versions

Any.

### Build Flags

Default.  It does not get to build, it fails on fetching.

**Comment by spiffmon** [comment]
Just a heads-up that we are hoping to be boost-free this year (with 24.05 we are _almost_ free in a no-python build).

**Comment by ggarra13** [comment]
Hurrah!!! Now if I could only convince you to drop Qt, for a lighter and faster to compile toolkit like ImGui, GLFW or FLTK, I would be in heaven 🥇

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9551

**Comment by pixar-oss** [comment]
Hi! Our understanding is that concerns around the jfrog repo have been resolved and that it remains the authoritative host of boost, so I'm going to close this issue.  Feel free to reopen if you have further concerns!
