### ISSUE TITLE
MaterialX texcoord-related regression in v24.03

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#3048]
### Description of Issue

Following asset looks different after upgrading USD: [Buffer_Interleaved_01.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/15049394/Buffer_Interleaved_01.zip)

v23.08
![bug_2308](https://github.com/PixarAnimationStudios/OpenUSD/assets/3663466/a24f512c-47f2-4ee2-9ad4-13bf3bbc54cd)

v24.03
![bug_2403](https://github.com/PixarAnimationStudios/OpenUSD/assets/3663466/3676f271-46f2-4d7f-8c46-bf5e014a9fc8)

(see comment below for an explanation)

### Steps to Reproduce
1. open the asset in usdview

### System Information (OS, Hardware)
Occurs on both Windows (OpenGL) and macOS (Metal)

### Package Versions
v24.03 and v24.05 are affected

### Build Flags
`--openimageio --opencolorio`

**Comment by pablode** [comment]
I've tracked down the issue to some faulty texture coordinates in the asset:
```
texCoord2f[] primvars:st0 = [(0, 1), (1, 0), (5.831554e-39, 1), (0, 1), (5.831554e-39, 1), (0, 1)] (
    interpolation = "vertex"
)
```
Not sure why it rendered correctly in the first place or why the behavior changed, but closing this for now.

**Comment by pablode** [comment]
I believe to have found the cause. First, the texture coordinates are faulty:
```
texCoord2f[] primvars:st0 = [(0, 1), (1, 0), (5.831554e-39, 1), (0, 1), (5.831554e-39, 1), (0, 1)] (
    interpolation = "vertex"
)
```

However, they are irrelevant because the _BaseColor_Grey.png_ texture that is being sampled is 100% grey and is defined with the `periodic` address mode in both _u_ and _v_ directions. Hence, regardless of UV values, grey should be returned and not black.

Although on macOS the color is solid black, I have observed flickering of the correct colors with the OpenGL backend. Perhaps this is somehow related to the newly-introduced tangent frame computation?

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9565

**Comment by pablode** [comment]
On macOS, I can't reproduce this anymore with usdview, but it's 100% reproducible with usdrecord.
`usdrecord Buffer_Interleaved_01/Buffer_Interleaved_01.usda bug.png` to get above render.

**Comment by pablode** [comment]
Can't reproduce with USD v24.11.
