### ISSUE TITLE
Storm MaterialX 'edf' shader compilation error on Metal

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#3049]
### Description of Issue

This is an isolated bug report for the issue mentioned in #2479.

The scene [VeachAjar.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/15049436/VeachAjar.zip) throws multiple error messages and renders incorrectly with Storm's metal backend:
```
Warning: in _ValidateCompilation at line 229 of /Users/pablode/USD/pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (FRAGMENT_SHADER): program_source:2600:5: error: unknown type name 'EDF'
    EDF edf;
    ^
```

### Steps to Reproduce
1. open the attached file with usdview on macOS

### System Information (OS, Hardware)
MacBook Air M3, Sonoma 14.4.1

### Package Versions
v24.05

### Build Flags
`--openimageio --opencolorio`

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9566
