### ISSUE TITLE
Seperated UVs in Maya

### ISSUE THREAD

**Issue by sanlwy** [PixarAnimationStudios/USD#305]
### Description of Issue
When importing a mesh with UVs in Maya, in the UV editor all the UVs are separated per polygon(face)

### Steps to Reproduce
1. Create a box with UVs in maya
2. Export to usd
3. Import usd file in maya and change Scene Assembly -> Full
4. Go to the UV Editor
5. Right click and select UV Shell

Expected behavior is that there is only 1 UV Shell, but right now it is 1 UV Shell per face

**Comment by spiffmon** [comment]
See also the discussion in https://groups.google.com/d/msg/usd-interest/dtjmEGJoEZ8/TCl17r__AQAJ in which Sandy notes that assigning the original data to uCoords, vCoords and assignmentIndices fixes the issue.

**Comment by jtran56** [comment]
Filed as internal issue #152349.

**Comment by sunyab** [comment]
Closing out old issue, the Maya plugin has been retired for some time in favor of Autodesk's [maya-usd](https://github.com/Autodesk/maya-usd) plugin
