### ISSUE TITLE
Querying USD version from a python session

### ISSUE THREAD

**Issue by kshimano** [PixarAnimationStudios/USD#306]
### Description of Issue

It would be helpful if the python API for Usd supported a function or other value that made it easy to determine which version of the Usd plugin was currently in use.

For example, I'd just like to be able to run something like:

import pxr
print pxr.GetUsdVersion()

To display which version is currently being used.

**Comment by jtran56** [comment]
Filed as internal issue #152369.

**Comment by enzyme69** [comment]
@sunyab Can we easily print USD version now?

**Comment by jcowles** [comment]
Would be nice if `pxr.__version__`  returned this value
