### ISSUE TITLE
UsdUtils.ModifyAssetPaths strips empty paths from asset array attributes

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#3060]
### Description of Issue
UsdUtils.ModifyAssetPaths strips empty asset paths from asset array attributes. This makes sense for composition arcs, but for attributes/primvars, this kind of arbitrary manipulation of array contents (and lengths!) is likely to break things. This change appears to be new, probably cause when ModifyAssetPaths moved over to the AssetLocalization framework.

### Steps to Reproduce
1. Extract the attached asset_array.usda: 
[asset_array.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/15132812/asset_array.zip)
2. Run the following script in python:
```
def cb(asset):
    return asset

from pxr import Usd, UsdUtils, Sdf
l = Sdf.Layer.FindOrOpen("asset_array.usda")
print(l.ExportToString())
UsdUtils.ModifyAssetPaths(l, cb)
print(l.ExportToString())
```
4. The result should be completely unchanged (since the callback doesn't change any asset paths), but instead the empty asset paths have been stripped from the asset array.

### Package Versions
24.03

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9595

**Comment by spiffmon** [comment]
Thanks, @marktucker - agreed and we'll try to get this addressed for the next release.

**Comment by marktucker** [comment]
Thanks. I have a PR that I just need to do a little more testing on before I submit it for your approval (hopefully).
