### ISSUE TITLE
Support for interactions in quicklook with openusd in python 

### ISSUE THREAD

**Issue by KevinAquino** [PixarAnimationStudios/USD#3081]
### Description of Issue

I would like add an interaction  from quicklook actions, is there a way to do this within the python tools? (sorry if this is the wrong place).

### System Information (OS, Hardware)
Python (MacOS)

### Package Versions
usd-core 23.8

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9658

**Comment by dgovil** [comment]
@KevinAquino Apologies for the delayed response here but I see you asked on the forum too https://forum.aousd.org/t/interactions-with-quicklook-using-python-tools/1508

I'll close this one out then.
