### ISSUE TITLE
Hang can occur during Python threading

### ISSUE THREAD

**Issue by lbiasco-sie** [PixarAnimationStudios/USD#3087]
### Description of Issue

A hang can occur in particular uses of USD with the Python [threading library](https://docs.python.org/3/library/threading.html). I debugged it a bit and narrowed my particular case down to the `UsdSchemaRegistry` singleton's initialization, and it can be worked around by pre-initializing the registry before starting the threads. 

That said, I wouldn't be surprised if this was a more pervasive issue with other singletons or atomic C++ operations.

### Steps to Reproduce
1. Unzip [python_threading_hang_repro.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/15328595/python_threading_hang_repro.zip) and run `python_threading_hang_repro.py`.
2. Uncomment the registry initializiation (line 16) to not hit the hang.

### System Information (OS, Hardware)

Windows 11

### Package Versions

USD-24.05

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9679

**Comment by spiffmon** [comment]
That's weird, @lbiasco-sie - I'm not that familiar with python's threading library, but I'm really curious why we wouldn't run into this when multi-threading in C++.  In any case, we'll have a look, and thanks for the repro.

**Comment by lbiasco-sie** [comment]
I'm also curious about that. I forgot to mention this in the issue description but I tested the same underlying functions with a simple C++ script, and like you said it worked fine.
