### ISSUE TITLE
[katana] resetting transform stack is disregarded

### ISSUE THREAD

**Issue by nxkb** [PixarAnimationStudios/USD#311]
### Description of Issue
When a usd file is read into katana if a prim has an resetXformStack op, it still inherits the transforms of its parent.

A believe a good solution would be to add an xform.origin attribute set to 1 to locations corresponding to prims with the resetXformStack. Then you could add the additional xform ops after that reset to get very similar behavior that is easy to inspect.  

### Steps to Reproduce
1. Create a usd file with 2 prims: /world and /world/test (and some simple geo underneath so you can see)
2. Translate /world by some amount and add a reset op to /world/test
```
uniform token[] xformOpOrder = ["!resetXformStack!"]
```
3. read in usd with a pxrUsdIn node into katana and check the world position of /world/test. It will be offset by the same /world translation.

### System Information (OS, Hardware)
Linux
### Package Versions
usd-0.8.1

**Comment by jtran56** [comment]
Filed as internal issue #152903.

**Comment by sunyab** [comment]
Cleaning up old issue, USD no longer ships with a Katana plugin so this is no longer relevant.
