### ISSUE TITLE
Can usd-core support python 3.12.3?

### ISSUE THREAD

**Issue by marcodiiga** [PixarAnimationStudios/USD#3116]
Is there any chance https://pypi.org/project/usd-core/#description can be upgraded to support python 3.12.3?
Ubuntu24 ships with python 3.12.3 and projects using the default system distro cannot use it without downgrading or installing other versions alongside the system one.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9745

**Comment by sunyab** [comment]
Hi @marcodiiga, usd-core support for Python 3.12 should be available in the upcoming USD 24.08 release slated for next month. Thanks for filing!
