### ISSUE TITLE
Houdini: Crash with instanceable prim referenced under variant set

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#312]
### Description of Issue

Particular stage compositions involving an `instanceable` prim referenced under a prim that has a variant set authored will crash Houdini.

The crash originates from the parallel stage traversal that is spawned by `UsdPrim::FindAllRelationshipTargetPaths`, and seems to occur [here](https://github.com/PixarAnimationStudios/USD/blob/v0.8.1/pxr/usd/lib/usd/primData.h#L605), where `Usd_PrimData::GetFirstChild()` is being called on a null pointer. My guess is that the `src = src->GetMaster();` reassignment immediately above that is the culprit.

### Steps to Reproduce

1. Unpack the [attached .zip file](https://github.com/PixarAnimationStudios/USD/files/1412231/usd_instance_crash.zip).
2. Open the contained .hip file, which should open in Manual update mode.
3. Force a scene update.

### Package Versions

CentOS 7.3.1611
USD 0.8.1
Houdini 16.0.633

**Comment by jtran56** [comment]
Filed as internal issue #152904.
