### ISSUE TITLE
Missing boost_python310-vc142-mt-x64-1_76.lib

### ISSUE THREAD

**Issue by msf567** [PixarAnimationStudios/USD#3128]
### Description of Issue
I am struggling to build a basic DLL that links against a fresh USD install. My linker is looking for the above file (boost_python310-vc142-mt-x64-1_76.lib) and I don't even have it anywhere on disk. I have the dll version in some packman repos but since I am trying to make a DLL, I need to link against the static lib (correct me if I'm wrong). Also, I don't even know how I would change what the linker is looking for to link against the DLL anyways...

### Steps to Reproduce
1. Make a fresh install of USD
2. Create a blank C++ DLL project and include the USD stage.h file somewhere in the code.
3. Ensure your library and include paths are configured and eventually you will hit this linker error.

**Comment by msf567** [comment]
Could it be because I'm using Python 3.10 when I should be using 3.7?

**Comment by meshula** [comment]
How did you install USD?

**Comment by msf567** [comment]
I was able to resolve it by switching my active python version to what was included in the USD install. In this case it was 3.7. I was confused because when you download the Connect Sample from Omniverse, it has python version 3.10 in the packman repo, which led me to believe that was what I should have been using...

**Comment by meshula** [comment]
Glad you sorted it out :) Hopefully your notes will help people encountering this problem in the future.
