### ISSUE TITLE
Misleading docstring (HdSceneDelegate::GetExtent, HdRprim::GetExtent)

### ISSUE THREAD

**Issue by christianaguilera-foundry** [PixarAnimationStudios/USD#313]
### Description of Issue
The docstrings for these two methods are inconsistent. One states that the extent should be in world space, whilst the other states that it should be in local space. Notice that the latter in implemented in terms of the former.

**HdSceneDelegate:**
```
/// Returns the prim extent in world space (completely untransformed)
HD_API
virtual GfRange3d GetExtent(SdfPath const & id);
```
**HdRprim:**
```
/// Returns the bounds of the rprim in local, untransformed space.
inline GfRange3d GetExtent(HdSceneDelegate* delegate) const;
```

**Comment by jtran56** [comment]
Filed as internal issue #152908.
