### ISSUE TITLE
Duplicated fragment code in BasisCurves.glslfx

### ISSUE THREAD

**Issue by PierreWang** [PixarAnimationStudios/USD#3132]
### Description of Issue
In change 56e3997c, some common shading code are moved to terminals.glslfx. But he forgot to remove the corresponding snippets in BasisCurves.Fragment of BasisCurves.glslfx. And then in the following change, the removed snippets for Curves.Fragment.Wire is incorrectly returned back at change b3e6feeb.

So now, ApplyColorOverrides and LightingBlend are firstly called in the Curves.Fragment.Wire and Curves.Fragment.Patch shader code, and then called again in the ShadingTerminal code. This should be a duplication.

We have created a PR [3124](https://github.com/PixarAnimationStudios/OpenUSD/pull/3124) for this issue.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9781

**Comment by dgovil** [comment]
Closing because https://github.com/PixarAnimationStudios/OpenUSD/pull/3124 has been merged.
