### ISSUE TITLE
 from . import _usdImagingGL ImportError: /opt/local/USD/lib/python/pxr/UsdImagingGL/../../../libOpenImageIO.so.1.7: undefined symbol: _ZTIN3Iex7BaseExcE

### ISSUE THREAD

**Issue by hickb** [PixarAnimationStudios/USD#315]
### Description of Issue
After compile USD, I'm getting error related to usdImaging. 

# usdview ../USD/extras/usd/tutorials/helloWorld/HelloWorld.usda 
Traceback (most recent call last):
  File "/opt/local/USD/bin/usdview", line 28, in <module>
    Usdviewq.Launcher().Run()
  File "/opt/local/USD/lib/python/pxr/Usdviewq/__init__.py", line 56, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/opt/local/USD/lib/python/pxr/Usdviewq/__init__.py", line 208, in __LaunchProcess
    from mainWindow import MainWindow
  File "/opt/local/USD/lib/python/pxr/Usdviewq/mainWindow.py", line 33, in <module>
    from pxr import Usd, UsdGeom, UsdUtils, UsdImagingGL, Glf, Sdf, Tf
  File "/opt/local/USD/lib/python/pxr/UsdImagingGL/__init__.py", line 24, in <module>
    from . import _usdImagingGL
ImportError: /opt/local/USD/lib/python/pxr/UsdImagingGL/../../../libOpenImageIO.so.1.7: undefined symbol: _ZTIN3Iex7BaseExcE

### Steps to Reproduce
1. open python shell
from pxr import usdImagingGL(will give same error from usdview)

### System Information (OS, Hardware)
CentOS Linux release 7.3.1611 (Core)

### Build Flags
default installation process from documentation.

**Comment by jtran56** [comment]
Filed as internal issue #152910.

**Comment by sunyab** [comment]
I think this may be the same issue as in issue #325 and should hopefully be addressed by commit 455ea05. Please see the other issue for more details, thanks!

**Comment by asisudai** [comment]
Hi @sunyab I'm getting the same error. Even with 0.8.4/dev which has the fix.
Attaching logs that might be relevant:
[USD_log.txt](https://github.com/PixarAnimationStudios/USD/files/1790211/USD_log.txt)
[OpenEXR_log.txt](https://github.com/PixarAnimationStudios/USD/files/1790212/OpenEXR_log.txt)
[oiio-Release-1.7.14_log.txt](https://github.com/PixarAnimationStudios/USD/files/1790213/oiio-Release-1.7.14_log.txt)

## Error
Traceback (most recent call last):
  File "./usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "/net/pipeline/USD/lib/python/pxr/Usdviewq/__init__.py", line 28, in <module>
    from appController import AppController
  File "/net/pipeline/USD/lib/python/pxr/Usdviewq/appController.py", line 34, in <module>
    from pxr import Usd, UsdGeom, UsdUtils, UsdImagingGL, Glf, Sdf, Tf, Ar
  File "/net/pipeline/USD/lib/python/pxr/UsdImagingGL/__init__.py", line 24, in <module>
    from . import _usdImagingGL
ImportError: /net/pipeline/USD/lib/python/pxr/UsdImagingGL/../../../libOpenImageIO.so.1.7: undefined symbol: _ZTIN3Iex7BaseExcE


## Steps to Reproduce (same as @hickb )
1. from the shell, run: `usdview`
2. from python: `from pxr import usdImagingGL`

## System Information (OS, Hardware)
- CentOS Linux release 7.4.1708 (Core)

## Package Versions
[dev/0.8.4] - same issue, even with 455ea05 patch
[0.8.3] - same issue
[0.8.2] - same issue

## Build Flags
/bin/python USD/build_scripts/build_usd.py --docs --maya --maya-location=/usr/autodesk/maya2018 --docs /usr/local/USD
