### ISSUE TITLE
Incorrect location of third-party source folder with --build option

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#3164]
### Description of Issue

When USD is built using an explicit build directory:
```
python3 build_scripts/build_usd.py \
  --build BUILD \
  --openimageio \
  INSTALL
```
the 'src' folder for third-party libs resides in INSTALL/src and not in BUILD/src.

Since the downloaded sources are only relevant for the build process, I would expect them to reside in BUILD.

### Steps to Reproduce
1. Build USD with above arguments
2. Observe location of 'src' folder

### System Information (OS, Hardware)
MacBook Air M3, Sonoma 14.4.1

### Package Versions
v24.05

### Build Flags
See above.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9846

**Comment by pablode** [comment]
Ah, I just stumbled across `--src SRC Directory where dependencies will be downloaded (default: <install_dir>/src)`. Sorry for the noise.
