### ISSUE TITLE
usdview: Truncated playback range after changing sub-frame step size

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#321]
### Description of Issue

As of USD 0.8.1, changing the frame step size in `usdview` causes the application to no longer play back the stage's complete frame range.

### Steps to Reproduce
1. Open a USD stage in `usdview`. I've reproduced this with a simple stage containing only:

```
#usda 1.0
(
    endFrame = 1052
    startFrame = 1001
    upAxis = "Y"
)
```

2. Change the step size to 0.1 and press play. Using the above stage, `usdview` will only play up to frame 1006.1.

The number of frames you are able to play seems to scale with the original duration of the stage's timeline. For instance, using an `endFrame` value of 1152 in the stage above, I can play to frame 1016.1 after the step size has been changed to 0.1.

### Package Versions

CentOS 7.3.1611
USD 0.8.1 (also reproduced using a build based on `dev` at 13301652d1375be05a5f58a9eed2db4788b27f53)

**Comment by jtran56** [comment]
Filed as internal issue number #153301.
