### ISSUE TITLE
Katana: pxr.UsdKatana cannot be imported due to `pixar` dependency

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#323]
### Description of Issue

The `pxr.UsdKatana` Python package cannot be imported due to its `__init__.py` attempting to import a function from a `pixar` package.

### Steps to Reproduce
1. Launch Katana
2. In a Python tab, run `import pxr.UsdKatana`

**Comment by jtran56** [comment]
Filed as internal issue #153628.

**Comment by sanlwy** [comment]
In usd-0.8.1 it is also missing wrapCache.cpp in 
../third_party/katana/lib/usdKatana/CMakeLists.txt causing it to error out
