### ISSUE TITLE
Not able to Import Semantics from pxr

### ISSUE THREAD

**Issue by abhihjoshi** [PixarAnimationStudios/USD#3240]
Hello, I am currently trying to import Semantics as such (using Python 3.10):
`from pxr import Semantics`

However, I am not able to as the Semantics module is not present. This is what terminal reads when I try to import Semantics:
`ImportError: cannot import name 'Semantics' from 'pxr'`

I use `pip install usd-core` to install openusd. I was curious if there was a solution to this issue. Any help is much appreciated!

**Comment by nvmkuruc** [comment]
Hello!  `Semantics` is not a part of OpenUSD.  We know that there's a library called `Semantics` inside the `pxr` package inside of Omniverse so perhaps you might have seen an example script which references that?

We're hoping that OpenUSD accepts this PR (https://github.com/PixarAnimationStudios/OpenUSD/pull/3103) for inclusion into 24.11 to standardize support for semantic labeling.  The schema domain will be called `UsdSemantics` and the schema will be called `SemanticsLabelsAPI`.
