### ISSUE TITLE
Add unique identifiers to `UsdValidatorError`

### ISSUE THREAD

**Issue by nvmkuruc** [PixarAnimationStudios/USD#3241]
### Description of Issue

See the discussion here for more information.
https://forum.aousd.org/t/identifiers-for-validation-errors

As one validator may generate multiple distinct error kinds (for example, the `usdGeom` stage metadata checker validates both the `upAxis` and `metersPerUnit` field), the request is that errors get an `identifier` or `name` field that can uniquely group or categorize them for downstream post processing, filtering, and organization without relying on error prone matching of the error message string.

### Steps to Reproduce
1.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9999

**Comment by nvmkuruc** [comment]
@jesschimein @tallytalwar I think we can close this?

**Comment by tallytalwar** [comment]
I think once the change is in release branch it should close automatically. But yes can be closed. Thanks for being on top of things @nvmkuruc
