### ISSUE TITLE
Displacement in Storm leads to cracked surface

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#3248]
### Description of Issue
I believe this is a regression if this related issue actually was fixed in the past:

- https://github.com/PixarAnimationStudios/OpenUSD/issues/922

When using a file with displacement, while the result looks correct when tesselation is set to "Low", the result does not look correct anymore when tesselation is set to "Medium", "High", "Very High".

| Complexity | Result | 
| - | – |
| Low | <img width="669" alt="image" src="https://github.com/user-attachments/assets/13a6c753-bb99-403d-a3ab-3106f367ac8e"> | 
| High | <img width="674" alt="image" src="https://github.com/user-attachments/assets/bf3d82b8-64cb-4edf-8d93-5e986ab8fea5"> |

### Steps to Reproduce
1. Download [displacement_plane.zip](https://github.com/user-attachments/files/16729207/displacement_plane.zip) (extracted from the other issue)
2. Open in usdview
3. Set viewport complexity to "Low" or "High"
4. Note on "High" the individual faces crack apart

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10020

**Comment by davidgyu** [comment]
@hybridherbst You're correct that we did fix this for HgiGL (and it still works correctly there), but there are additional fixes needed for HgiMetal which has a different shading pipeline than GL and Vulkan.
