### ISSUE TITLE
Build issue on OSX - OIIO can't link against OpenEXR

### ISSUE THREAD

**Issue by robpieke** [PixarAnimationStudios/USD#325]
This looks (to me) quite possibly like a mismatch of headers/libs (i.e., headers picked up from one source location libs from another), but I'm getting an issue similar to #315 - but at compile-time.

This is using the convenience build-script. I haven't figured out how to make the script show me the exact compiler execution (i.e., the arguments being used).

[ 92%] Linking CXX shared library libOpenImageIO.dylib
Undefined symbols for architecture x86_64:
  "Iex::throwErrnoExc()", referenced from:
      OpenImageIO::v1_7::OpenEXRInputStream::OpenEXRInputStream(char const*) in exrinput.cpp.o
      OpenImageIO::v1_7::OpenEXRInputStream::read(char*, int) in exrinput.cpp.o
      OpenImageIO::v1_7::OpenEXRInputStream::seekg(unsigned long) in exrinput.cpp.o
      OpenImageIO::v1_7::OpenEXROutputStream::OpenEXROutputStream(char const*) in exroutput.cpp.o
      OpenImageIO::v1_7::OpenEXROutputStream::write(char const*, int) in exroutput.cpp.o
      OpenImageIO::v1_7::OpenEXROutputStream::seekp(unsigned long) in exroutput.cpp.o
  "Iex::BaseExc::BaseExc(char const*)", referenced from:
      Imath::Matrix44<float>::inverse(bool) const in field3dinput.cpp.o
      Imath::Matrix44<float>::gjInverse(bool) const in field3dinput.cpp.o
      Imath::Matrix44<float>::inverse(bool) const in field3doutput.cpp.o
      Imath::Matrix44<float>::gjInverse(bool) const in field3doutput.cpp.o
      Iex::InputExc::InputExc(char const*) in exrinput.cpp.o
      Iex::ErrnoExc::ErrnoExc(char const*) in exroutput.cpp.o
      Iex::TypeExc::TypeExc(char const*) in exroutput.cpp.o
      ...
  "Iex::BaseExc::~BaseExc()", referenced from:
      Imath::SingMatrixExc::~SingMatrixExc() in field3dinput.cpp.o
      Imath::SingMatrixExc::~SingMatrixExc() in field3dinput.cpp.o
      Imath::SingMatrixExc::~SingMatrixExc() in field3doutput.cpp.o
      Imath::SingMatrixExc::~SingMatrixExc() in field3doutput.cpp.o
      Iex::InputExc::~InputExc() in exrinput.cpp.o
      Iex::InputExc::~InputExc() in exrinput.cpp.o
      Iex::ErrnoExc::~ErrnoExc() in exroutput.cpp.o
      ...
  "Imf::OutputFile::writePixels(int)", referenced from:
      OpenImageIO::v1_7::OpenEXROutput::write_scanline(int, int, OpenImageIO::v1_7::TypeDesc, void const*, long) in exroutput.cpp.o
      OpenImageIO::v1_7::OpenEXROutput::write_scanlines(int, int, int, OpenImageIO::v1_7::TypeDesc, void const*, long, long) in exroutput.cpp.o
  "Imf::OutputFile::setFrameBuffer(Imf::FrameBuffer const&)", referenced from:
      OpenImageIO::v1_7::OpenEXROutput::write_scanline(int, int, OpenImageIO::v1_7::TypeDesc, void const*, long) in exroutput.cpp.o
      OpenImageIO::v1_7::OpenEXROutput::write_scanlines(int, int, int, OpenImageIO::v1_7::TypeDesc, void const*, long, long) in exroutput.cpp.o
  "Imf::OutputFile::OutputFile(Imf::OStream&, Imf::Header const&, int)", referenced from:
      OpenImageIO::v1_7::OpenEXROutput::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpenImageIO::v1_7::ImageSpec const&, OpenImageIO::v1_7::ImageOutput::OpenMode) in exroutput.cpp.o

**Comment by jtran56** [comment]
Filed as internal issue #153728.

**Comment by meshula** [comment]
If you run cmake-gui, open the OIIO build folder with it, click Show Advanced in the upper right hand corner, it might reveal some clues. When this sort of thing happens it's often because you built OpenEXR some other way, and Cmake is preferring the one it cached globally. Irrespective of make's global cache, cmake might be preferring one installed in a known global location, such as /opt if you have used macports at any point.

**Comment by sunyab** [comment]
Hi @robpieke, I haven't been able to reproduce this issue locally. I do wonder if it's something like @meshula suggests: the build is picking up another version of OpenEXR that you have installed somewhere in your PATH.

By default, the build script writes out log files into the build directories in <install dir>/build -- there should be a log.txt file in the directory for OIIO, for example. Also, if you search the CMakeCache.txt in that directory for the string "OPENEXR", you can see which OpenEXR the build is picking up.

**Comment by sunyab** [comment]
I think the commit above should fix this issue. It looks like OpenImageIO's build would give precedence to OpenEXR in locations like /usr/local, etc. over the one installed by the build script. The build script now explicitly specifies the OpenEXR to use, which should take care of that.
