### ISSUE TITLE
Display Colors are wrong in USD View

### ISSUE THREAD

**Issue by jonassorgenfrei** [PixarAnimationStudios/USD#3267]
Hey 

i just build the latest version of OpenUSD with the build script (using python3.11 on windows) and i was facing some color issues when i first opened usdview. 
I tried to export the geo with the colors from houdini (which can be seen on the left side). 
Unfortunatly the geo get's in just red-tinted. 

![grafik](https://github.com/user-attachments/assets/fdf6966e-a3c8-466c-9b4b-57639b5bfedf)
I have the same issue when importing the Usd Kitchen scene.
![grafik](https://github.com/user-attachments/assets/1e024b94-5e05-44fb-b35a-8bb2d60f402d)

Any idea or suggestion what could be causing the issue? 
Thanks in advance 

Cheers
Jonas

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10057

**Comment by asluk** [comment]
My rough guess is that this build of usdview is defaulting to use an integrated GPU rather than a discrete one (I haven't found any way to bootstrap this other than using tools like the NVIDIA Control Panel to set the python that runs usdview to use the discrete GPU.

**Comment by jonassorgenfrei** [comment]
Hey @asluk 

thanks for your suggestion, i was double checking but i don't believe that this is the issue.
I was trying to force the python executable to use the discrete GPU but that didn't do the trick. Actullay i don't even have an integrated GPU. 
Any other idea what could be wrong?

Cheers
Jonas

**Comment by jonassorgenfrei** [comment]
Hmm i tried to compile and run on a different system (windows11) with the same python3.11.2 version and there it is not showing this behaviour. Guess it's some system setting. Will try to clear env vars and recompile.

**Comment by jonassorgenfrei** [comment]
The issue seemed to be a corrupt old .usdview setting, after running --defaultsettings the issue was gone!
