### ISSUE TITLE
How to obtain the path of the material referenced by Prim？

### ISSUE THREAD

**Issue by yufengsjtu** [PixarAnimationStudios/USD#3290]
Hi，when i load a usd file like this:
![image](https://github.com/user-attachments/assets/f3153d3a-ffc2-4a22-ba52-f25e1081f439)
How can i obtain the value (i.e. the referenced material path of the drawer mesh) marked in the picture with python usd-core?

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10113

**Comment by spiffmon** [comment]
```
gprim = stage.GetPrimAtPath("/world/workshop/drawer/drawer")
mbAPI = UsdShade.MaterialBindingAPI(gprim)
material = mbAPI.ComputeBoundMaterial()[0]
if material:
    print(material.GetPrim().GetPath())
```

See the referenced methods for options, please.
