### ISSUE TITLE
cmake drops opensubdiv defines intended for Hd

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#33]
This is because the CMakeLists for Hd is using _add_define(), the effects of which have already been applied by the time individual libraries are reached, instead of add_definitions().

https://github.com/PixarAnimationStudios/USD/blob/2eb01f5cd4c2dae4e1ef9912ca27a93083bb6ef4/pxr/imaging/lib/hd/CMakeLists.txt#L10

I have a fix.

**Comment by jtran56** [comment]
Filed as internal issue #136468.

**Comment by sunyab** [comment]
This change has been merged into the latest 0.7.1 release. Closing, thanks!
