### ISSUE TITLE
Would be nice to get diagnostic messages from BG threads

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#331]
### Description of Issue
I'm in a situation where stderr and stdout are never (meaningfully) available, but USD uses these for diagnostic messages when the message originates from a background thread.

It would be nice if the diagnostic delegate could declare itself thread safe to receive messages from background threads.

**Comment by spiffmon** [comment]
Good news, Jeremy! The next release will contain Josh's recent work to do just that, including a ready-to-use delegate in UsdUtils that will do error and warning coalescing. 

--SpiffiPhone

**Comment by jcowles** [comment]
W00t!

**Comment by jtran56** [comment]
Filed as internal issue #154178.

**Comment by spiffmon** [comment]
See https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/lib/usdUtils/coalescingDiagnosticDelegate.h#L27
