### ISSUE TITLE
[Maya] usdExport cannot export shading with instances

### ISSUE THREAD

**Issue by stolyaroleh** [PixarAnimationStudios/USD#332]
### Description of Issue

There seems to be a fundamental difference between how Maya and USD handle instancing and material assignment.

In Maya, it's possible to override material assignment for instances: an instanced shape has an array attribute `instObjGroups`, the elements of which can be connected to multiple shading nodes. In this way, instances share geometry, but can have different materials.

As far as I understand, in USD, a reference to material lives on a Gprim. Since `usdExport` translates Maya instances into USD instances, authoring edits on instanced Gprims is forbidden, which is exactly what `PxrUsdMayaShadingModeExporter` tries to do.

Additionally, it is possible to crash usdExport and Maya if there is a name conflict between instanced shapes, coming from a referenced scene. I think this happens because `PxrUsdMayaUtil::MDagPathToUsdPath`, used by `PxrUsdMayaShadingModeExporterContext::GetAssignments` is not injective: it maps distinct `MDagPath`s `foo|bar|baz` and `foo:bar|baz` to the same `SdfPath`. This confuses usdExport: it attempts to write to a null prim, which raises a `SIGABRT`.

### Steps to Reproduce
1. Open attached scene [usdexport_shading_instances.ma](https://github.com/PixarAnimationStudios/USD/files/1495065/test_scene.zip)
2. Run the following:
```python
from maya import cmds
cmds.usdExport(
    file='~/test.usda',
    exportInstances=True,
    shadingMode='displayColor'
)
```
3. Observe errors in console:
```
Coding Error: in _ValidateEditPrimAtPath at line 1183 of /home/oleh.stolyar/src/wwfx-bin/thirdparty/USD/pxr/usd/lib/usd/stage.cpp -- Cannot create prim at path </Cube_1/Looks>; authoring to an instance proxy is not allowed.
```
4. Create a new scene, and add a cube to it.
5. Add a reference to `usdexport_shading_instances.ma` (File -> Create Reference...).
6. Rename cube transform node to `usdexport_shading_instances_Cube_1` and shape node to `usdexport_shading_instances_Shape`.
7. Repeat step 2.
8. Observe a crash:
```
------------------------ 'maya.bin' is dying ------------------------
maya.bin crashed. FATAL ERROR: Used null prim
in Usd_IssueFatalPrimAccessError at line 224 of /home/oleh.stolyar/src/wwfx-bin/thirdparty/USD/pxr/usd/lib/usd/primData.cpp
```

### System Information (OS, Hardware)
CentOS 7

### Package Versions
v0.8.1

### Build Flags
Mostly default.

**Comment by stolyaroleh** [comment]
What would be a good way to handle shading and instances?
I was wondering if it's possible to isolate shading in a separate, stronger layer, which would override instanceability and provide opinions about material references at locations of instance proxies. If yes, would geometry still be shared between prims?

**Comment by spiffmon** [comment]
Hi Oleh- thanks for reporting these issues. Funnily enough, we are currently working to extend the material binding system in UsdShade to allow binding "by collections ", which will allow us to assign materials to instanced prims from "outside" the instance. Look for a "Roadmap update" post on the interest forum soon for more details. 

The second issue is not something we've run into, and we'll look into it. We may use this issue primarily to target the #2 bug in the report. 

--SpiffiPhone

**Comment by jtran56** [comment]
Filed as internal issue #154222.

**Comment by sunyab** [comment]
Maya plugin development has migrated to Autodesk's maya-usd project, so this is no longer relevant. Closing this out.
