### ISSUE TITLE
alias required in plugInfo.json

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#3377]
### Description of Issue
It looks like a schema does not work unless there is an `"alias":` metadata. I cannot tell if this is intended behavior, my guess is that it should act like the `alias` is equal to the name used in the `plugInfo.json` file.

In addition trying to make an `alias` that is equal to the name of any of the entries in the `plugInfo.json` file produces an error.

If this is intended behavior a fix to the documentation to say the `alias` is required would be helpful.

### Steps to Reproduce
1. Edit a `plugInfo.json` file, change the name of one of the items to match its `alias` and delete the `alias` metadata.
2. Try to use the schema, it acts like it exists but is a blank prim.
3. Paste the `alias` back in but leave the name equal and you get an error about a name collision.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10356

**Comment by spiffmon** [comment]
Hi @spitzak , you should find this issue resolved in 24.11 - a schema whose name is the same as the alias would be will no longer attempt to create an alias (you'll need to rerun `usdGenSchema`)
