### ISSUE TITLE
cant running schema  Python Example；UsdSchemaExamples ；UsdSchemaExamples.ParamsAPI.Apply；

### ISSUE THREAD

**Issue by fzss2012** [PixarAnimationStudios/USD#3380]
### Description of Issue
cant running schema  Python Example.

### Steps to Reproduce

from pxr import Usd, UsdSchemaExamples
stage = Usd.Stage.Open("test.usda")
cp = stage.GetPrimAtPath("/Complex")
simple = UsdSchemaExamples.Simple(cp)
target = simple.GetTargetRel()
intAttr = simple.GetIntAttrAttr()
complex = UsdSchemaExamples.Complex(cp)
print('complexString: %s' % complex.GetComplexStringAttr().Get())
obj = stage.GetPrimAtPath("/Object")

paramsAPI = UsdSchemaExamples.ParamsAPI.Apply(obj)  #pxr.Tf.ErrorException

assert obj.HasAPI(UsdSchemaExamples.ParamsAPI)
print('mass: %s' % paramsAPI.GetMassAttr().Get())
print('velocity: %s' % paramsAPI.GetVelocityAttr().Get())
print('volume: %s' % paramsAPI.GetVolumeAttr().Get())

-------------------------------------------------------
(usdenv) root@hcss-ecs-e6b2:/home/test# /home/usdenv/bin/python /home/test/payload.py
complexString: a really complex string
Traceback (most recent call last):
  File "/home/test/payload.py", line 10, in <module>
    paramsAPI = UsdSchemaExamples.ParamsAPI.Apply(obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pxr.Tf.ErrorException: 
        Error in 'pxrInternal_v0_24_11__pxrReserved__::UsdPrim::ApplyAPI' at line 1127 in file /home/OpenUSD/pxr/usd/usd/prim.h : 'Class 'UsdSchemaExamplesParamsAPI' is not correctly registered with the UsdSchemaRegistry as a schema type. The schema may need to be regenerated.'

### System Information (OS, Hardware)
Ubuntu 22.04 server 64bit

### Package Versions
USD 24.11
Python 3.12.7

**Comment by asluk** [comment]
I believe the install location of the examples in https://github.com/PixarAnimationStudios/OpenUSD/tree/release/extras/usd/examples is not bootstrapped by default -- you may need to add find usdSchemaExamples.so in your install hierarchy and add its location to PATH and/or PXR_PLUGINPATH_NAME -- see also https://openusd.org/release/tut_generating_new_schema.html#using-the-schema-classes

**Comment by fzss2012** [comment]
@asluk 
Thanks, I'll try again.

**Comment by fzss2012** [comment]
@asluk 
I noticed that the capitalization of the library name in the compilation and the class name in the Python binding don't seem to match, and it’s affecting the compilation process.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10359
