### ISSUE TITLE
Different behavior of SdfLayer::GetSpecType() in identical ASCII/Crate scenes

### ISSUE THREAD

**Issue by stolyaroleh** [PixarAnimationStudios/USD#340]
### Description of Issue

Given the following (simplified) `usda` scene:
```
#usda 1.0
(
    defaultPrim = "pSphere1"
    endTimeCode = 1
    startTimeCode = 1
    upAxis = "Y"
)

def Xform "pSphere1" (
    kind = "component"
)
{
    def Sphere "pSphereShape1"
    {
        rel material:binding = </pSphere1/Looks/initialShadingGroup>
    }

    def Scope "Looks"
    {
        def Material "initialShadingGroup"
        {
            color3f interface:displayColor = (0.21763764, 0.21763764, 0.21763764)
            float interface:displayOpacity
            color3f interface:transparency
            rel ri:interfaceRecipientsOf:displayColor = </pSphere1/Looks/initialShadingGroup/initialShadingGroup_lambert.diffuseColor>
            rel ri:interfaceRecipientsOf:transparency = </pSphere1/Looks/initialShadingGroup/initialShadingGroup_lambert.transmissionColor>

            def RisBxdf "initialShadingGroup_lambert"
            {
                color3f diffuseColor
                asset info:filePath = @PxrDiffuse@
                color3f transmissionColor
            }
        }
    }
}
```
...and an identical `usdc` scene, generated using:
```bash
usdcat test.usda -o test.usdc
```
`SdfLayer::GetSpecType()` will return different values for path `/pSphere1/pSphereShape1.material:binding[/pSphere1/Looks/initialShadingGroup]`.

### Steps to Reproduce
1. Extract `test.cpp`, `test.usda` and `test.usdc` from [test.zip](https://github.com/PixarAnimationStudios/USD/files/1527848/test.zip).

2. Compile and run attached C++ script:
```bash
./test /path/to/test.usda /path/to/test.usdc
```

3. Observe different output.

### System Information (OS, Hardware)
CentOS 7

### Package Versions
0.8.2 (dev branch), reproduced on commit 4f3b44f

### Build Flags
Mostly default.

**Comment by stolyaroleh** [comment]
I am [testing](https://groups.google.com/forum/#!topic/usd-interest/bepHU2owJ5g) the new Sdf Spec Copy API. My goal is to simplify scene hierarchy; I export extra metadata from Maya using a chaser, and then construct a simplified prim tree. I noticed that, when using ascii files, `SdfCopySpec` would preserve old values on relationships, even though the paths are broken because I changed hierarchy. This is good, since I have a mapping from old to new paths that I can use to fix them after prims were copied. Crate files, though, return `SdfSpecTypeUnknown` instead of `SdfSpecTypeRelationshipTarget` [here](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/lib/sdf/copyUtils.cpp#L552), which prevents further copying.

**Comment by gitamohr** [comment]
Thanks for the great report!  We've observed this issue internally as well and are working on a fix.

**Comment by jtran56** [comment]
Filed as internal issue #154663.

**Comment by stolyaroleh** [comment]
4b471e7 fixed it! Thanks, @sunyab.
