### ISSUE TITLE
Houdini plugin

### ISSUE THREAD

**Issue by sanlwy** [PixarAnimationStudios/USD#342]
### Description of Issue
Houdini Tree View window does not update properly when dealing with variantsSets
1. If the prim only contains a variantSet it doesn't show anything when toggling with Show/Hide variants
2. If a variant is chosen, the Tree Viewer doesn't update (for instance if you have a nested variants, it will not list the nested variantSet)

### Steps to Reproduce
1. load 
[test.zip](https://github.com/PixarAnimationStudios/USD/files/1535939/test.zip)
in houdini and open tree view
2. Once the initial bug is fix, pick the 'default' AnmVariantSet and the tree view gui will not update

### Package Versions
0.8.1

**Comment by jtran56** [comment]
Filed as internal issue #154694.

**Comment by sunyab** [comment]
Closing out old issue, USD no longer includes a Houdini plugin in favor of native USD support in Houdini Solaris.
