### ISSUE TITLE
Katana plugin

### ISSUE THREAD

**Issue by sanlwy** [PixarAnimationStudios/USD#343]
### Description of Issue
PxrUsdIn plugin doesn't import uvs where the interpolation = "vertex" properly. It just maps the primvars:st:indices as is instead of expanding it before mapping it to the primvars:st coordinates

### Steps to Reproduce
1. Load 
[plane_uv.zip](https://github.com/PixarAnimationStudios/USD/files/1535956/plane_uv.zip)
in katana
2. Open the UV window

**Comment by sanlwy** [comment]
hmm actually there a note in ../usdKatana/readPrim.cpp (line 658)

        // Note that 'varying' vs 'vertex' require special handling, as in
        // Katana they are both expressed as 'point' scope above. To get
        // 'vertex' interpolation we must set an additional
        // 'interpolationType' attribute.  So we will flag that here.

Does renderman figure out the mapping at render time?

Thanks
Sandy

**Comment by jtran56** [comment]
Filed as internal issue #154695.

**Comment by sanlwy** [comment]
Sorry not really a pxrUsdIn plugin issue, the renderer should add support for vertex interpolation and katana should fix the uv viewer window issue
