### ISSUE TITLE
Too Many Warnings from vt\value.cpp:508

### ISSUE THREAD

**Issue by zhoub** [PixarAnimationStudios/USD#345]
### Description of Issue
Too many warnings from vt\values.cpp

Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'SdfSpecifier'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'TfToken'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'SdfSpecifier'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'TfToken'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'SdfSpecifier'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'TfToken'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'SdfSpecifier'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'TfToken'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'SdfSpecifier'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'TfToken'
Coding Error: in _FailGet at line 508 of C:\Users\Bo\Forge\USDJ-repo\pxr\base\lib\vt\value.cpp -- Attempted to get value of type 'string' from VtValue holding 'SdfSpecifier'

### Steps to Reproduce
Just read the sequence of cache.

### System Information (OS, Hardware)
Windows

### Package Versions
v0.8.2

### Build Flags
Release

**Comment by jtran56** [comment]
Filed as internal issue #154997.

**Comment by spiffmon** [comment]
Hi Zhoub,
   Could you please clarify your repro steps?  Particularly: what tool or script are you running?  And could you attach the usd file (or a stripped down one) that causes the errors?

Thanks!

**Comment by sunyab** [comment]
Closing out this old issue, please let us know if you're still running into this problem and can provide steps to reproduce the errors. Thanks!
