### ISSUE TITLE
UsdSkel: Documentation of Transform Types and how they compose to produce final animation

### ISSUE THREAD

**Issue by shumash** [PixarAnimationStudios/USD#3457]
I am using USD python API to extract skinning weights as well as bones and transforms out of a USD file exported from blender. The skinning weights are correct. I am also using [UsdSkelSkeletonQuery.ComputeSkinningTransforms](https://openusd.org/dev/api/class_usd_skel_skeleton_query.html#ad37a92f259f583ff99b5f354c42f268a) to get transforms, and the bone transforms are consistent with transforms that appear in blender. When applied to the mesh vertices, the animation looks almost correct, but there seems to be a huge discrepancy in the translation and some other small differences. I think I need to modify the transforms I am getting by some other transform. **Is there a mathematical explanation of how all the different transforms, returned by UsdSkelSkeletonQuery compose?**  

I am following [Official UsdSkel schema overview](https://openusd.org/dev/api/_usd_skel__a_p_i__intro.html), and [UskSkelSkelQuery docs](https://openusd.org/dev/api/class_usd_skel_skeleton_query.html). 

Thanks in advance!

**Comment by spiffmon** [comment]
Hi @shumash , without digging into code, [this](https://openusd.org/dev/api/_usd_skel__intro.html#UsdSkel_TransformSpaces) is the only possibly more helpful explanation I could find.

**Comment by shumash** [comment]
Thank you @spiffmon . This was really helpful. What I was missing is that the skinning transform takes the world space points to **skeleton space** locations, so one has to also multiply by the Skeleton's Local2World to get back to world.
