### ISSUE TITLE
[Katana] Instancing produces random results in pxrUsdIn when "as sources and instances" is enabled

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#349]
### Description of Issue
When using instances that instance instances themselves pxrUsdIn fails to create the sources properly when instanceMode is set to "as sources and instances".

The issue happens because of the change introduced in 523ee0a3 . If you look at pxrUsdIn.cpp:503, you can see why it fails. The loop properly iterates through the masters, but the locationParent is going to be the same for all the masters, so the last master (in the case of the example scene, m19) will always overwrite usdPrimPath and usdPrimName, thus the following loop (line 528) will only iterate through one master.

### Steps to Reproduce
1. Load up the attached file in katana
2. Set instanceMode to "as sources and instances"
3. Expand the scene graph, and inspect /root/world/geo/Masters/master/variants. There is only one instance, m19.

### Package Versions
Latest dev.

**Comment by sirpalee** [comment]
Updated the title of the ticket and attached a simpler file to reproduce the issue. The random behaviour can be seen on only one level of instancing.

[instancing_bug_generated_single.usda.zip](https://github.com/PixarAnimationStudios/USD/files/1550398/instancing_bug_generated_single.usda.zip)

**Comment by jtran56** [comment]
Filed as internal issue #154999.

**Comment by nrusch** [comment]
@sirpalee Was this also fixed by https://github.com/PixarAnimationStudios/USD/commit/7172773bd3651132ce3ae9c93a0336280950fda4?

**Comment by c64kernal** [comment]
Closing this as we are in the process of deprecating the Katana plugins from the USD repo.
