### ISSUE TITLE
Same plugin loaded twice

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#358]
### Description of Issue

Hi - so we've had issues a few times where USD attempts to load the same plugin twice, leading to nasty error messages or straight-up-crashes.

This can happen if the same path ends up in the plugin search path twice... in our case, we got this because the at-build-time install location is baked into libplug.so, and added to the search path, and we had subsequently copied the install to a second location.

This happens because the PlugPlugin::_NewXXXPlugin() functions aren't properly locking on their plugin identifier, leading to the race conditions - ie, right now, the steps are:

1) Get Lock
2) Check if another plugin with same name is registered
3) Release Lock
4) Make plugin
5) Get Lock
6) Add plugin to registry
7) Release lock

So, if we have two threads, A and B, and they have an execution order like this:

A1-3, B1-3, A4, B4

...then you can see we get the same plugin loaded twice, and have problems.

This is easy to fix by adding a dummy entry to the plugin hashtables within the scope as the initial check, before the lock is released - ie, do:

1) Get Lock
2) Check if another plugin with same name is registered
3) Add null-ptr plugin entry to registry
3) Release Lock
4) Make plugin
5) Get Lock
6) Add real plugin to registry (overwriting our null entry)
7) Release lock

This should solve any race conditions - the only downside is that we have no guarantee of "fallback" behavior - ie, if the same plugin is on the path twice, but one copy is "bad", and will fail to register somehow, and the second is "good", then, depending on order of operations, we may sometimes fail, sometimes succeed, etc.

Assuming you don't care about that - it's not unreasonable to require all plugins on the path to be functional - then I'll make a PR for my simple fix.

**Comment by jtran56** [comment]
Filed as internal issue #155341.

**Comment by elrond79** [comment]
Just filed a PR which should fix this...

**Comment by sunyab** [comment]
This should be addressed by commit 9ad3c35335a38db94736ab3ee13b6fafa50956c0.

**Comment by sunyab** [comment]
This fix is in release v0.8.3. Closing, thanks!
