### ISSUE TITLE
UsdShade AreBiDirectionalInterfaceConnectionsEnabled has no API decl

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#361]
Missing USDSHADE_API here:

https://github.com/PixarAnimationStudios/USD/blob/65320d266057ae0a68626217f54a0298ac092799/pxr/usd/lib/usdShade/connectableAPI.h#L581

Found in v0.8.2

**Comment by jtran56** [comment]
Filed as internal issue #155669.

**Comment by c64kernal** [comment]
Thanks Jeremy!  We'll fix shortly.  Note that this API is deprecated.
