### ISSUE TITLE
Houdini: Add st primvar <-> uv attribute conversion

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#362]
The Maya USD integration plugin includes special-case handling of the `st` primvar for geometry: it reads `st` into Maya's default `map1` UV set on import, and likewise exports `map1` to the `st` primvar.

The `pxrUsdIn` Katana op also reads the `st` primvar in a way that it is generally interpreted as a UV set, though this could almost be considered a happy accident (though I'm reasonably sure it wasn't) based on the fact that A) the op reads primvars into the `geometry.arbitrary` group, and B) many renderer plugins interpret `geometry.arbitrary.st` as a UV set.

Currently, the USD Houdini plugin does not treat the `st` primvar in any special way, so artists wishing to utilize UVs in "standard" ways must manually copy the primvar data to one of Houdini's `uv` attributes on import (as well as converting it from a `vector2` to a `vector`), and subsequently reverse that process on export if they wish to modify UV data in Houdini.

There was a [previous discussion](https://groups.google.com/d/msg/usd-interest/Paz_H4MjI0o/qXysKd-OBQAJ) that touched on this topic, where there was mention of some uncertainty surrounding the current status quo with regard to USD's handling (or not) of UV data. However, with no alternative core changes on the horizon, I think it would be worthwhile to add support for automatic conversion between the `st` primvar and Houdini's `uv` attribute to the `Gusd` libraries to provide a more intuitive "out-of-the-box" interchange workflow. Making the conversion optional would help avoid interference with more customized site-specific workflows.

**Comment by jtran56** [comment]
Filed as internal issue #155727.

**Comment by spiffmon** [comment]
Hey Nathan,
    Sorry for the delay here!  Our Fx devs have given their OK for adding
this conversion.  We already do something similar for displayColor <-> Cd ,
and they ask you follow the same pattern (i.e. if both st and uv appear on
a prim, prefer uv over st when importing).

--spiff

**Comment by nrusch** [comment]
Will do. I should hopefully have a PR ready in the next few days.

**Comment by nrusch** [comment]
One question: Since the imported/exported primvars are governed by a pattern string (which defaults to `"Cd"`), I'm wondering if the following logic sounds sensible with regard to respecting the pattern:

- If both `uv` and `st` match the pattern, and `primvars:uv` exists on the prim, read it into `uv`.
- If both `uv` and `st` match the pattern, but `primvars:uv` does *not* exist on the prim, read `primvars:st` into `uv` (if present).
- If only `st` matches the pattern, read `primvars:st` into `uv`.

**Comment by spiffmon** [comment]
Hey Nathan,
    Agreed it sounds best to have gusd be the only actor dealing with conversion between vec3f and vec2f.

    The idea behind a TextureCoordinate role is not that we'd immediately start creating and requiring support for textureCoordinate3f's (though it would now be possible for dcc's to robustly interchange such things, though I think you'd need extra metadata that provides the coordinate system in which the encoding is specified), but rather that we'd start making all uv primvars be encoded as textureCoordinate2f arrays, eventually deprecating import logic that considers all float2-arrays as possibly being uvs.  We'd still require gusd convert to textureCoordinate2f  on export.

**Comment by nrusch** [comment]
@spiffmon Thanks, that makes sense to me. So once this new `textureCoordinate2f` role is live (assuming it's more or less a done deal at this point), will USD still consider `st` to be the canonical primvar for storing the "default" UV set?

**Comment by spiffmon** [comment]
Yes, st would be the primary uvset, and should be of typeName
textureCoordinate2f.  Thanks, Nathan!

--spiff

**Comment by distancetozero** [comment]
Digging into testing usd one thing I am running into is exporting geometry into usd with multiple uv sets. Is there something in usd that allows me to export multiple uv sets from houdini?  I have the vertex attributes on the Geo but it seems in Katana doesn't quite understand what to do with them. 

So I have a few questions.

 Is this a limitation of the Katana plug-in? And could one make a Katana plug-in that can read "uv attributes" arbitrarily? 

Does usd internally have a notion of multiple uv sets? 

What is the current plan for uv sets and is a more generic attribute driven approach possible?

**Comment by sunyab** [comment]
Closing out old issue related to retired Houdini plugin.
