### ISSUE TITLE
Plugin system looks in original install location even after relocating build

### ISSUE THREAD

**Issue by sunyab** [PixarAnimationStudios/USD#363]
### Description of Issue
This was reported on the usd-interest forum here: https://groups.google.com/forum/#!topic/usd-interest/68NnvsdmzlI

If you relocate the USD installation to a different location, the plugin system will look not only in the new location, but also at the original install location for libraries. This can cause problems if a user has a USD installation in the original location and then tries to use the relocated build: the plugin system may wind up trying to load the same library twice, or get mismatched library versions, etc.

This appears to be due to the build system always defining PXR_INSTALL_LOCATION when compiling libraries. PXR_INSTALL_LOCATION was intended to be an optional setting to allow users to specify other locations to look for plugins, but it shouldn't be passed along if it's not being used.

### Steps to Reproduce
1. Build USD (let's say into /tmp/USD_1)
2. Recursively copy /tmp/USD_1 to /tmp/USD_2
3. Try to run usdview or anything using the build in /tmp/USD_2.

### System Information (OS, Hardware)
all

### Package Versions
0.8.2, earlier versions probably affected as well

**Comment by chadrik** [comment]
@sirpalee @elrond79 will be interested to keep an eye on this.
