### ISSUE TITLE
This file locks up usdview

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#368]
### Steps to Reproduce

Open file, usdview hangs.

python build_monolithic_py\bin\usdview "testRecording.usd"

Attached:
[testRecording.zip](https://github.com/PixarAnimationStudios/USD/files/1645683/testRecording.zip)

### System Information (OS, Hardware)
Windows

### Package Versions
USD v0.8.2

### Build Flags
python build_scripts\build_usd.py
    --build-monolithic
    --no-tests
    --no-docs 
    --no-ptex 
    --no-embree
    --alembic
    --no-hdf5
    build_monolithic_py

**Comment by jtran56** [comment]
Filed as internal issue #156102.
