### ISSUE TITLE
Build fails on boost 1.55.0 - argument error

### ISSUE THREAD

**Issue by asisudai** [PixarAnimationStudios/USD#383]
### Description of Issue
Build fails on installing boost 1.55.0

### Steps to Reproduce
1. Fresh Centos build
2. run build command (/usr/bin/python USD/build_scripts/build_usd.py -v --force-all /usr/local/USD)

### System Information (OS, Hardware)
Centos 7.4.1708 

### Package Versions
v0.8.2

### Build Flags
/usr/bin/python USD/build_scripts/build_usd.py -v --force-all /usr/local/USD

### Build Log
run: /usr/bin/python USD/build_scripts/build_usd.py -v --force-all /usr/local/USD

Building with settings:
  USD source directory          /tmp/USD
  USD install directory         /usr/local/USD
  3rd-party source directory    /usr/local/USD/src
  3rd-party install directory   /usr/local/USD
  Build directory               /usr/local/USD/build

  Building                      Shared libraries
    Imaging                     On
      Ptex support:             Off
    UsdImaging                  On
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off

    Dependencies                boost, TBB, JPEG, TIFF, PNG, OpenEXR, GLEW, OpenImageIO, OpenSubdiv

STATUS: Installing boost...
INFO: Downloading http://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.gz to /usr/local/USD/src/boost_1_55_0.tar.gz
INFO: Extracting archive to /usr/local/USD/src/boost_1_55_0
INFO: Running "./bootstrap.sh --prefix="/usr/local/USD""
INFO: Running "./b2 --prefix="/usr/local/USD" --build-dir="/usr/local/USD/build" -j12 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-date_time --with-filesystem --with-program_options --with-python --with-regex --with-system --with-thread -a install"
2018-01-24 13:18
./bootstrap.sh --prefix="/usr/local/USD"
Building Boost.Build engine with toolset gcc... tools/build/v2/engine/bin.linuxx86_64/b2
Detecting Python version... run: /usr/bin/python -c import sys; print ("%d.%d" % (sys.version_info[0], sys.version_info[1])) 2.7
Detecting Python root... run: /usr/bin/python -c import sys; print sys.prefix /usr
Unicode/ICU support for Boost.Regex?... not found.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/boost-build2/doc/html/index.html

2018-01-24 13:18
./b2 --prefix="/usr/local/USD" --build-dir="/usr/local/USD/build" -j12 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-date_time --with-filesystem --with-program_options --with-python --with-regex --with-system --with-thread -a install
/usr/local/USD/src/boost_1_55_0/tools/build/v2/build/toolset.jam:41: in toolset.using
*** argument error
* rule python.init ( version ? : cmd-or-prefix ? : includes * : libraries ? : condition * : extension-suffix ? )
* called with: ( run: /usr/bin/python -c import sys; print (%d.%d % (sys.version_info[0], sys.version_info[1])) 2.7 : run: /usr/bin/python -c import sys; print sys.prefix /usr :  :  :  :  :  :  )
* extra argument /usr/bin/python
/usr/local/USD/src/boost_1_55_0/tools/build/v2/tools/python.jam:99:see definition of rule 'python.init' being called
/usr/local/USD/src/boost_1_55_0/tools/build/v2/build/project.jam:1007: in using
project-config.jam:20: in modules.load
/usr/local/USD/src/boost_1_55_0/tools/build/v2/build-system.jam:249: in load-config
/usr/local/USD/src/boost_1_55_0/tools/build/v2/build-system.jam:412: in load-configuration-files
/usr/local/USD/src/boost_1_55_0/tools/build/v2/build-system.jam:524: in load
/usr/local/USD/src/boost_1_55_0/tools/build/v2/kernel/modules.jam:289: in import
/usr/local/USD/src/boost_1_55_0/tools/build/v2/kernel/bootstrap.jam:139: in boost-build
/usr/local/USD/src/boost_1_55_0/boost-build.jam:17: in module scope

ERROR: Failed to run './b2 --prefix="/usr/local/USD" --build-dir="/usr/local/USD/build" -j12 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-date_time --with-filesystem --with-program_options --with-python --with-regex --with-system --with-thread -a install'
See /usr/local/USD/src/boost_1_55_0/log.txt for more details.

**Comment by sunyab** [comment]
Hi @asisudai, do you an environment setting or something that could cause commands in shell scripts to be echoed before their results are assigned to variables? Something seems to be fouling up boost's detection of the Python version:

Detecting Python version... run: /usr/bin/python -c import sys; print ("%d.%d" % (sys.version_info[0], sys.version_info[1])) 2.7
Detecting Python root... run: /usr/bin/python -c import sys; print sys.prefix /usr

Normally, this would just be printing "2.7" and "/usr", but it seems to be getting some extra output that causes the boost build to fail later on.

**Comment by asisudai** [comment]
Thank you @sunyab that was the issue - the installer picked up a different version of python I had installed. Thank you again.
