### ISSUE TITLE
usdview does not set y-up correctly

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#385]
### Steps to Reproduce
1. Open a stage that has upAxis=Y in usdview
2. When you first open the stage, z will be up
3. Reload the stage
4. Y is now up (properly)

### Build Flags

Happens when built off of latest dev (f9f7979ce3a406ab68357e6cb58d2147468ce85b)

**Comment by jtran56** [comment]
Filed as internal issue #156379.
