### ISSUE TITLE
Compiling Maya Plugin - ZLIB_1.2.9 not found

### ISSUE THREAD

**Issue by asisudai** [PixarAnimationStudios/USD#389]
### Description of Issue
After successfully compiling Maya plugin (pxrUsd.so) it complains about ZLIB_1.2.9 not found.
Which makes sense, since I only have libz.1.2.7 installed, at /lib64. So I downloaded v1.2.9 and did `make install` it to /usr/local/lib. Unfortunately, the pxrUsd.so points to /lib64. I tried also adding adding to LD_LIBRARY_PATH. still, it's looking at /lib64.

Questions is, and excuse me for the novice question, how would you recommend I go about it? (I'm afraid to manually upgrade/stump /lib64/libz.so since it's such a core library for the OS. 

##### Error message when loading plugin in Maya:
/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/USD/lib64/libpng16.so.16) // 
// Error: file: /usr/autodesk/maya2018/scripts/others/pluginWin.mel line 290: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/USD/lib64/libpng16.so.16) (pxrUsd) // 

##### Error message when doing `ldd /usr/local/USD/third_party/maya/plugin/pxrUsd.so`:
USD/third_party/maya/plugin/pxrUsd.so: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/USD/lib64/libpng16.so.16)

### System Information (OS, Hardware)
Centos7 3.10.0-693.11.1.el7.x86_64

### Package Versions
USD v0.8.2

### Build Flags

python USD/build_scripts/build_usd.py --docs --maya --maya-location=/usr/autodesk/maya2018 --docs /usr/local/USD

**Comment by jtran56** [comment]
Filed as internal issue #156421.

**Comment by sunyab** [comment]
Hi @asisudai, sorry for the very late reply. 

I'm not sure exactly what's happening here as I've not seen this problem before. In particular, I'm not sure why libpng would be asking for ZLIB_1.2.9. Could you post the log file from the libpng build? I believe it would be located for you in /usr/local/USD/build/libpng-1.6.29/log.txt. That file should mention which libz was found, which might shed more light on this.

**Comment by asisudai** [comment]
Hi @sunyab,
Of course, please see attached log.

To resolve the issue, I built libz v1.2.9 (outside of USD) and installed it in **/lib64**. It solved my issue.
Thank you for looking into this, much appreciated.

If it helps, seems that some of USD dependent libraries are conflicting with existing OS/usr libraries, outside of the USD installation. For example, this case of libz and also libOpenImageIO (`libOpenImageIO.so.1.7: undefined symbol: _ZTIN3Iex7BaseExcE` seems to be conflicting with outside/none USD dependencies) 

## Partial /usr/local/USD/build/libpng-1.6.29/log.txt
2018-01-25 19:00
cmake -DCMAKE_INSTALL_PREFIX="/usr/local/USD" -DCMAKE_PREFIX_PATH="/usr/local/USD"    "/usr/local/USD/src/libpng-1.6.29"
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.9") 
-- Performing Test HAVE_LD_VERSION_SCRIPT
-- Performing Test HAVE_LD_VERSION_SCRIPT - Success

[log.txt](https://github.com/PixarAnimationStudios/USD/files/1783357/log.txt)

**Comment by asisudai** [comment]
Hi @sunyab I solved this issue by changing OpenImageIO to the recommended version v1.5.11, instead v1.7.11 of the default in 0.84 build_script.
