### ISSUE TITLE
Use Qt5 and PySide2

### ISSUE THREAD

**Issue by dakerfp** [PixarAnimationStudios/USD#40]

**Comment by meshula** [comment]
I gave this a go, but on macOS, qmake is defaulting to not setting the c++11 flag, which is required to build Qt :\ For some reason, setting the CXXFLAGS=c++11 environment variable works for building shiboken, but it fails during the build of PySide itself. If anyone has worked this one out on macOS, I'd love a recipe.

**Comment by jtran56** [comment]
Filed as internal issue #136789.

**Comment by sunyab** [comment]
The commit above adds initial experimental support for Qt5 and PySide2. The build currently prefers PySide, but if it isn't found or PYSIDE_USE_PYSIDE2=TRUE is specified at cmake time, it will try to use PySide2 instead.
