### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by leonardlan** [PixarAnimationStudios/USD#402]
### Description of Issue
I get this error when running "python build_scripts/build_usd.py ~/USD". I'm using virtualenv too.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLUT_Xmu_LIBRARY (ADVANCED)
    linked by target "tiffgt" in directory /home/llan/USD/src/tiff-4.0.7/tools

-- Configuring incomplete, errors occurred!
See also "/home/llan/sandbox/USD/CMakeFiles/CMakeOutput.log".
See also "/home/llan/sandbox/USD/CMakeFiles/CMakeError.log".

### Steps to Reproduce
1. python build_scripts/build_usd.py ~/USD

### System Information (OS, Hardware)
Centos

**Comment by jtran56** [comment]
Filed as internal issue #156712.

**Comment by sunyab** [comment]
Hi @leonardlan, sorry for the late reply here. I believe you should be able to fix this issue by installing the libxmu-dev package on your VM.

The USD build does not actually need the tiffgt binary that's causing this error. We may want to disable building those tools by default -- we already do this on Windows for other reasons.
