### ISSUE TITLE
Maya shader binding incorrect for shapes that have other xforms alongside

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#404]
### Description of Issue

Say you have these objects in your maya scene:

```
|myCubeXform|myCubeShape
|myCubeXform|mySphereXform
|myCubeXform|mySphereXform|mySphereShape
```

Then when you export these items, myCubeShape will not be collapsed into myCubeXform, due to the presence of mySphereXform alongside it; however, it's shader will be bound to myCubeXform, which is incorrect.

### Steps to Reproduce
1. Clearest reproduction can be found in this commit, where I've added a test:

https://github.com/LumaPictures/USD/commit/7124cd93ee9055a535a448d15b8d887fe540e813

### Package Versions

Usd is post-0.8.2, from this commit (latest at time of writing):
https://github.com/PixarAnimationStudios/USD/commit/50bec3104a21a8ec2dfb1a6c9c734a78b7225d83

### Notes

So, the real culprit here is that there are two separate code-paths for doing the maya-dagpath-to-usd-sdfpath translation - one in MayaTransformWriter:

https://github.com/PixarAnimationStudios/USD/blob/50bec3104a21a8ec2dfb1a6c9c734a78b7225d83/third_party/maya/lib/usdMaya/MayaTransformWriter.cpp#L413

...and one in MDagPathToUsdPath:

https://github.com/PixarAnimationStudios/USD/blob/50bec3104a21a8ec2dfb1a6c9c734a78b7225d83/third_party/maya/lib/usdMaya/util.cpp#L1142

These have diverged, resulting in this bug.  I started doing some work on unifying them, but got pulled away onto a different task.  The main issue is that, in order to use the more "correct" version in MayaTransformWriter, we need to pass more information through to areas where MDagPathToUsdPath is called, such as whether we're exporting instances, and whether we're only exporting renderable objects.  This would be made easier (now and in the future) if we could switch to passing around the JobExportArgs object in more places, but instead the working paradigm seems to always be to pass through collections of individual settings.

The main reason I can think for doing that would be to insulate plugins from ABI changes requiring re-compiling, whenever any change is made to JobArgs.  However, the code prefers passing individual options even within "internal" code where we're not breaking any plugin "boundaries" - ie, the code call structure in some places looks like this:

```
topFunc(jobArgs.exportFoos, jobArgs.exportBars)
    innerFunc1(exportFoos, exportBars)
        pluginFunc(exportFoos, exportBars)
        =========================================== << plugin interface boundary
            subclassedPluginFunc(exportFoos, exportBars)
```

Assuming the reason for splitting out args is to preserve the ABI for plugins, we should still be able to do this:

```
topFunc(jobArgs)
    innerFunc1(jobArgs)
        pluginFunc(jobArgs.exportFoos, jobArgs.exportBars)
        =========================================== << plugin interface boundary
            subclassedPluginFunc(exportFoos, exportBars)
```

**Comment by jtran56** [comment]
Filed as internal issue #156817.

**Comment by spiffmon** [comment]
Hi Paul!
   Without intending to detract from your motivation (and possible
necessity?) of changing the API's to pass around JobArgs in their entirety,
there *is* another motivation to the current function signatures, which is
that they give you more precise information about what inputs are really
important to the function, as a reader of calling sites.

--spiff

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
