### ISSUE TITLE
Thoughts about Unreal Engine

### ISSUE THREAD

**Issue by Schizo** [PixarAnimationStudios/USD#411]
### Description of Issue
I couldn't find any information out there about the current status about USD for Unreal-Engine. The last news was i came across was a [GDC]( https://uploadvr.com/epic-games-unreal-engine-april/) Article and a unanswered [Unreal Question. ](https://answers.unrealengine.com/questions/573940/where-is-the-pixar-usd-support.html)

Can someone shed light what the current status is?

Thanks

**Comment by c64kernal** [comment]
Hi Schizo,

The only USD plugin for Unreal that I'm aware of is maintained by Epic and ships with Unreal, I believe starting in version 4.17 (see release notes here: https://docs.unrealengine.com/latest/INT/Support/Builds/ReleaseNotes/4_17/index.html).  They'd have more information about it, if you'd like to ask to them.  Hope that helps!

**Comment by Schizo** [comment]
@c64kernal 

Thanks for the useful information.
