### ISSUE TITLE
[Houdini] Reload button on USD Import does not work.

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#416]
### Description of Issue
The reload button on USD Import does not behave as expected. Changes to the geometry stored in the USD file are not updated unless the primitive's path is also changed. When using the GPrim traversal option, new meshes show up and removed ones disappear, but geometry changes still don't work.

After a bit of digging around, the UsdStage stored in the GusdStageCache is properly updated and does hold the updated file.

### Steps to Reproduce
1. Import a USD file using USD Import.
2. Change the geometry in the file, save the file.
3. Press the reload button.

### System Information (OS, Hardware)
Centos 7

### Package Versions
Houdini 16.5.323, latest dev branch.

**Comment by jtran56** [comment]
Filed as internal issue #157684.

**Comment by sunyab** [comment]
Closing out old issue -- USD no longer ships a separate Houdini plugin.
