### ISSUE TITLE
Maya plugin - Toggling Playback & Full

### ISSUE THREAD

**Issue by sanlwy** [PixarAnimationStudios/USD#418]
### Description of Issue
In usd-0.8.3 : from the UsdAssembly node toggling from playback to full, then back to playback does not draw in the viewport anymore

### Steps to Reproduce
1. Open Maya
2. Create a UsdReferenceAssembly and load any usd file
3. Switch to playback, it draw fine
4. Switch to full, still ok
5. Switch back to playback and nothing gets drawn in the viewport

### Package Versions
usd-0.8.3, maya-2018

**Comment by jtran56** [comment]
Filed as internal issue #157843.

**Comment by sanlwy** [comment]
Looks like this has been fixed in the dev branch
