### ISSUE TITLE
Importing in Maya a usd with RFM shader contains PxrSeExpr

### ISSUE THREAD

**Issue by BSalem** [PixarAnimationStudios/USD#42]
Importing a usd that was exported with RFM shaders where the shading network has a PxrSeExpr crashes maya.
The usd file seem to be correct when viewed in usdview or usdedit

[has_seExpr.usda.tar.gz](https://github.com/PixarAnimationStudios/USD/files/453533/has_seExpr.usda.tar.gz)

**Comment by jtran56** [comment]
Filed as internal issue #136889.

**Comment by BSalem** [comment]
Correction to the issue causes:
It turned out that maya was crashing because the object has creased edges and is being imported by maya file->import from maya interface... so there is nothing to be done with SeExpr itself.
Using usdImport directly to import the USD, then everything works as expected. 
Note: the issue of crashing when using Maya file->import is reported already in different ticket.
