### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'project-config.jam'

### ISSUE THREAD

**Issue by ghost** [PixarAnimationStudios/USD#420]
### Description of Issue
While trying to build the USD with Maya plugins project i receive an error with the text
ERROR: [Errno 2] No such file or directory: 'project-config.jam'

### Steps to Reproduce
1. git clone the usd project
2. navigate to the builds_script folder inside it
3. run build_usd.py "C:\Program Files\USD" -v --maya --maya-location "C:\Program Files\Autodesk\Maya2018\bin"

### System Information (OS, Hardware)
Windows 10 Version 1709 build 16299.248

### Package Versions
Happens on both dev and master branches 
Python2.7.14 64 bit version installed + pip
Visual Studio community 2017

### Build Flags
Described in steps to reproduce. Doesn't get to compile with flags. 
I think it's not able to build boost for some reason

```
Desktop\USD\build_scripts>build_usd.py "C:\Program Files\USD" -v --maya --maya-location "C:\Program Files\Autodesk\Maya2018\bin"

Building with settings:
  USD source directory          C:\Users\Red\Desktop\USD
  USD install directory         C:\Program Files\USD
  3rd-party source directory    C:\Program Files\USD\src
  3rd-party install directory   C:\Program Files\USD
  Build directory               C:\Program Files\USD\build
  CMake generator               Default

  Building                      Shared libraries
    Imaging                     On
      Ptex support:             Off
    UsdImaging                  On
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    Maya Plugin                 On
    Katana Plugin               Off
    Houdini Plugin              Off

    Dependencies                boost, TBB, JPEG, TIFF, PNG, OpenEXR, GLEW, OpenImageIO, OpenSubdiv

STATUS: Installing boost...
INFO: C:\Program Files\USD\src\boost_1_61_0.tar.gz already exists, skipping download
INFO: Directory C:\Program Files\USD\src\boost_1_61_0 already exists, skipping extract
INFO: Running "bootstrap.bat --prefix="C:\Program Files\USD""
ERROR: [Errno 2] No such file or directory: 'project-config.jam'
```

Edit:
Attached the bootstrap logs as well
[bootstrap.log](https://github.com/PixarAnimationStudios/USD/files/1779133/bootstrap.log)
[log.txt](https://github.com/PixarAnimationStudios/USD/files/1779134/log.txt)

**Comment by sunyab** [comment]
Hi @igsabiescu, unfortunately there are issues running the build script with MSVC 2017 -- see https://github.com/PixarAnimationStudios/USD/issues/294 for more information. There's a workaround patch to the script in the issue that might help. I would also try re-running the script with the `--force` option to see if that helps too.

**Comment by jtran56** [comment]
Filed as internal issue #157954

**Comment by sunyab** [comment]
The newest release of USD (18.09) adds support for Visual Studio 2017 to build_usd.py, so please give that a try. I'm going to close this out in the interim, but feel free to reopen or file a new issue if you're still running into problems. Thanks!
