### ISSUE TITLE
Houdini USD Import creates lots of stages

### ISSUE THREAD

**Issue by spitzak** [PixarAnimationStudios/USD#421]
### Description of Issue

Especially if a scene does not have any "containers" then the USD Import creates a different stage for every prim being imported.

### Steps to Reproduce

* Use a simple scene with two objects that do not have kind==container.
* Run the USD import and first import the root,
* then change the tree to import the two object separately.
* Check the stage of the UsdPrim from each resulting prim and you will see it is the same.
* Save the houdini script, exit, then run Houdini again on the same script.
* Check the stage of the UsdPrim from each resulting prim and they are different.

Personally we would like to share stages even if there are different Houdini objects, not just prims inside the same objects.

**Comment by spitzak** [comment]
Sebastian Grassia said there is plan to fix this:

   We'll also be pushing out a change, soon, that:
a) changes the default "didn't find a component ancestor" behavior in _ExpandStageMask
b) provides an env-var controlled override that disables masking altogether

Looking at the code there are a few unanswered questions.

* I am assuming the main change will be to import the root if no components are found.
* If so you must test for component before testing to see if the prim is in the mask.
* It also looks like ExpandPopulationMask must be moved afterwards, or a reference to outside a component will import the root. The current code looks wrong to me, it will only import references from the requested prim, not from the component. Conversely it will import the entire component that any reference is in.
* I am unclear if it is desirable to keep two components on different stages. My tests indicate that fewer stages is faster for virtually any operation. If so a major rewrite might help where it adds the components of new prims to the already created stage. It will run Recompose once per prim however, if this is a problem I think it would be best to fix UsdStage::SetPopulationMask (or perhaps implement AddPopulationMask) to do a minimal recompose.

**Comment by spitzak** [comment]
Also wondering what the desired behavior is if the user imports a non-root that is the parent of some components. If this should only import that prim and not the root then it will have to do a search inside. Possibly this search can be limited by depth.

**Comment by spiffmon** [comment]
Hi Bill,
   Believe it or not, the current implementation **is** a major rewrite of our original cache that operated as you suggest, which tried to utilize as few stages as possible, adding (loading) prims to an existing stage as long as there was no conflicts in requested variant settings (the "editing" part).  The **problem** with that approach is multithreading: mutating (which is even loading/unloading) a stage means no other threads can even read from the stage for the duration.  So as a consequence, the original implementation required a per-stage **global lock**, which is pretty unsatisfactory (and which you'd need to use around all your attempts to image from the stage, also), given that USD derives much of its performance from multi-threaded reading.  True, it can be a reader/writer lock, but still.

Masked stages gives us an elegant alternative. though we're not claiming it's the best solution for all time - it's particularly useful for the variant/edit case, upon which our internal crowd/sim system is built.

We'll hopefully have the improvements ready soon, though!

**Comment by jtran56** [comment]
Filed as internal issue #158033.
