### ISSUE TITLE
[Build] Cannot build on Windows 10

### ISSUE THREAD

**Issue by devGitHub48** [PixarAnimationStudios/USD#423]
### Description of Issue
Hi!

I try to compile USD on Windows and I have several issues :)
First of all, not being an administrator of my machine prevented me from compiling correctly Boost... 

Thanks to Geoge, I was able to compile libjpeg : 
[https://github.com/PixarAnimationStudios/USD/issues/271](url)  The Nasm python package does not work correclty.

Here are my issue:
* if I try to compile the Maya plugin, the core of USD is not compiled or created correctly (for example usdView.cmd)
* When I use the --maya flag, I don't have any error but the third_party directory is not created.
Should the location of Maya be the SDK or the real Maya installation? 
* I cannot compile the Houdini plugin:
`CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Houdini (missing: HOUDINI_LIB_DIRS) (found version
  "16.5.323")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindHoudini.cmake:138 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:153 (find_package)
  CMakeLists.txt:33 (include)`
### Steps to Reproduce
1. I use this commandline in VS2015 prompt as administrator :
`python USD\build_scripts\build_usd.py --imaging --alembic --no-houdini --houdini-location "C:\Program Files\Side Effects Software\Houdini 16.5.323" --no-maya --maya-location "E:\DXM\external\Maya\sdk\2018" --force-all --verbose "d:\dxm\usd" `
And I switch the --no-maya and --no-houdini to build the plugin accordingly

### System Information (OS, Hardware)
Windows 10, Visual 2015
Python2.7.14 64 bit version

Thanks a lot for you help.

**Comment by sunyab** [comment]
Hi @devGitHub48,

- You would typically pass the root of the Maya installation to --maya-location, e.g. "C:\Program Files\Autodesk\Maya2017". The build expects to find the Maya headers and libraries in "include" and "lib" subdirectories under that path.

- Unfortunately, we don't currently support building the Houdini plugin on Windows.

Hope that helps!

**Comment by jtran56** [comment]
Filed as internal issue #158218.

**Comment by devGitHub48** [comment]
@sunyab thank you very much! I will modify the path for Maya. (sdk is not distributed anymore with Maya so I downloaded it somewhere else)
Is there a lot missing for Houdini on Windows?

Thanks again.

**Comment by devGitHub48** [comment]
@sunyab so, the issue was deeper :)
Checking all the CMakeError.log and here are the errors :
ZLib 
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1803959/CMakeError.log)
:
`
D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CheckTypeSize\OFF64_T.c(19): error C2065: 'off64_t': undeclared identifier [D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_e5c1f.vcxproj]

D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CheckTypeSize\OFF64_T.c(20): error C2065: 'off64_t': undeclared identifier [D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_e5c1f.vcxproj]

D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CheckTypeSize\OFF64_T.c(21): error C2065: 'off64_t': undeclared identifier [D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_e5c1f.vcxproj]

D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CheckTypeSize\OFF64_T.c(22): error C2065: 'off64_t': undeclared identifier [D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_e5c1f.vcxproj]

D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CheckTypeSize\OFF64_T.c(23): error C2065: 'off64_t': undeclared identifier [D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_e5c1f.vcxproj]

Génération du projet "D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_e5c1f.vcxproj" terminée (cibles par défaut) -- ÉCHEC.

...
  D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [D:\dxm\usd\build\zlib-1.2.11\CMakeFiles\CMakeTmp\cmTC_d6fed.vcxproj]
`
IlmBase 👍 
OpenEXR 
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1803960/CMakeError.log)
: 
`  D:\dxm\usd\build\OpenEXR\CMakeFiles\CMakeTmp\src.cxx(13): fatal error C1189: #error:  No GCC style inline asm supported for AVX instructions [D:\dxm\usd\build\OpenEXR\CMakeFiles\CMakeTmp\cmTC_f0746.vcxproj]`

Alembic 
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1803961/CMakeError.log)
:
`  D:\dxm\usd\build\alembic-1.7.1\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\dxm\usd\build\alembic-1.7.1\CMakeFiles\CMakeTmp\cmTC_0a9fb.vcxproj]`

libjpg 👍 

Tiff 
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1803962/CMakeError.log)
:
`  cl : Command line error D8021: invalid numeric argument '/Wl,--version-script=D:/dxm/usd/build/tiff-4.0.7/conftest.map' [D:\dxm\usd\build\tiff-4.0.7\CMakeFiles\CMakeTmp\cmTC_ea3f8.vcxproj]
...
D:\dxm\usd\build\tiff-4.0.7\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory [D:\dxm\usd\build\tiff-4.0.7\CMakeFiles\CMakeTmp\cmTC_e9e3d.vcxproj]
...
  D:\dxm\usd\build\tiff-4.0.7\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory [D:\dxm\usd\build\tiff-4.0.7\CMakeFiles\CMakeTmp\cmTC_51005.vcxproj]
....`

libpng 
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1803963/CMakeError.log)
:
`  cl : Command line error D8021: invalid numeric argument '/Wl,--version-script='D:/dxm/usd/build/libpng-1.6.29/conftest.map'' [D:\dxm\usd\build\libpng-1.6.29\CMakeFiles\CMakeTmp\cmTC_7249e.vcxproj]`

OpenIO 
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1803967/CMakeError.log)
:
`D:\dxm\usd\build\oiio-Release-1.7.14\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\dxm\usd\build\oiio-Release-1.7.14\CMakeFiles\CMakeTmp\cmTC_c6d73.vcxproj]`

OpenSubdiv 👍 

Everything looks fine at then end of the build :
`
Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    d:\dxm\usd\lib\python

    The following in your PATH environment variable:
    d:\dxm\usd\bin
    d:\dxm\usd\lib

See documentation at http://openusd.org/docs/Maya-USD-Plugins.html for setting up the Maya plugin.
`

Sorry my Windows is in French :(

If you have any idea, feel free to help me :)

**Comment by devGitHub48** [comment]
### System information:
Windows 10 Entreprise (French Canadian)
Visual Studio 2015 14.0.25431.01 Update 3
Tested with Developer Command Prompt for VS2015 as administrator

**Comment by sunyab** [comment]
@devGitHub48: The CMakeError.log files are a little misleading -- many of the errors are generated when the various libraries are trying to figure out whether you have certain headers on your platform or not. So in other words, they're expected. 

The build script will print out any 'real' errors that occur during the build process. If the script finishes and prints out that "Success" message, then all of the dependencies and USD have been built and should be ready to use. So it looks like you should be all set!

**Comment by c64kernal** [comment]
Closing this out as @devGitHub48 is up and running now.  @devGitHub48 please re-open if I'm mistaken!
