### ISSUE TITLE
[usdKatana] PxrUsdInCore_LooksGroupOp does not run location decorators

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#438]
### Description of Issue

The `PxrUsdInCore_LooksGroupOp ` is run for prims named "Looks" that are immediate children of "model" prims. It handles the creation of `material` locations for any `Material` prims in the group, and then prevents `pxrUsdIn` from traversing any of its children.

However, it does not currently execute any "location decorator" ops, which causes inconsistent behavior compared to a "Looks" group placed anywhere else in a model's hierarchy.

### Package Versions

USD 0.8.4, Katana 2.6

**Comment by jtran56** [comment]
Filed as internal issue #158736.

**Comment by sunyab** [comment]
This was addressed by commit a845511697. Closing this out, thanks!
