### ISSUE TITLE
compile problem oiio failed to run cmake

### ISSUE THREAD

**Issue by svenfraeys** [PixarAnimationStudios/USD#441]
Trying to compile USD but it failes when working on open image IO oiio.
I upgraded my cmake to 3.11.

Any ideas how to get further ? Log files are in attachements.

`sudo python build_scripts/build_usd.py /usr/local/USD`

`cmake version 3.11.0-rc4`

`ERROR: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="/usr/local/USD" -DCMAKE_PREFIX_PATH="/usr/local/USD"   -DOIIO_BUILD_TOOLS=OFF -DOIIO_BUILD_TESTS=OFF -DUSE_PYTHON=OFF -DSTOP_ON_WARNING=OFF -DOPENEXR_HOME="/usr/local/USD" -DUSE_PTEX=OFF "/usr/local/USD/src/oiio-Release-1.7.14"'
See /usr/local/USD/build/oiio-Release-1.7.14/log.txt for more details.
`
I do not know what the exact error is from the log. One of the problems that do appear are these 
`
/usr/local/USD/build/oiio-Release-1.7.14/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_MAC’ was not declared in this scope
   return ((int*)(&Q_WS_MAC))[argc];
                   ^
CMakeFiles/cmTC_33106.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_33106.dir/CheckSymbolExists.cxx.o' failed

`

[log.txt](https://github.com/PixarAnimationStudios/USD/files/1845376/log.txt)

[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/1845372/CMakeError.log)
[CMakeOutput.log](https://github.com/PixarAnimationStudios/USD/files/1845373/CMakeOutput.log)

**Comment by meshula** [comment]
Looks like you've got an incomplete boost somewhere in your path that cmake is discovering.

Have a look at other issues around boost and OIIO, they'll probably help. Here's one:

https://github.com/PixarAnimationStudios/USD/issues/419

**Comment by jtran56** [comment]
Filed as internal issue #158779.

**Comment by sunyab** [comment]
Hi @svenfraeys, can you post the CMakeCache.txt file from your /usr/local/USD/build/oiio-Release-1.7.14 directory? That can help us figure out where CMake is picking up boost. Thanks!

**Comment by svenfraeys** [comment]
@sunyab ah k I will send you the content of the file tonight.
I will also double check the state of my boost.

Keep you posted !

**Comment by svenfraeys** [comment]
@sunyab you might be on the good path indeed.
Looking at the file it does contain 140 NOTFOUND words in the file, so I do not know if boost will be the only thing missing.
Any idea how to proceed with this ? Will look for a solution myself but not really an idea where to start....

//The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=Boost_DIR-NOTFOUND

[CMakeCache.txt](https://github.com/PixarAnimationStudios/USD/files/1853684/CMakeCache.txt)

**Comment by Anti-Distinctlyminty** [comment]
I seem to be having the same issue. I have a fresh install of cmake 3.11
I've attached the CMakeCache.txt
[CMakeCache.txt](https://github.com/PixarAnimationStudios/USD/files/1900475/CMakeCache.txt)
Which seems to have the same boost issues, which is odd because the boost libraries are downloaded and built by the build_usd.py script.

I'm not really sure what to try next.

**Comment by svenfraeys** [comment]
@Anti-Distinctlyminty I also did not find any solution so far, so I am still stuck, let me know if you find anything on your side.

**Comment by Anti-Distinctlyminty** [comment]
@svenfraeys I never managed to get past that issue. I also read that the Houdini plugins are not available for Windows, which was stated in the user group here
[https://groups.google.com/d/msg/usd-interest/Ce1U3T4euDU/YdDcRs6MAQAJ](url)

**Comment by sunyab** [comment]
I'm going to close this out for now. There's been a significant amount of work over the last release or two on getting build_usd.py to fix boost-related issues so I am hoping that these problems are resolved in the latest release. If you're still running into this in 20.05, please let us know. Thanks!
