### ISSUE TITLE
Invalid zlib path in build_usd.py

### ISSUE THREAD

**Issue by PascalArtus** [PixarAnimationStudios/USD#449]
Hi,

build_usd.py:368

The default url to download zlib is currently "https://github.com/madler/zlib/archive/v1.2.11.zip", but no such file can be found at this location, resulting in an obscure error message when executing the script.
An easy workaround is to use "https://zlib.net/zlib1211.zip" 

Best regards.

**Comment by jtran56** [comment]
Filed as internal issue #159322.

**Comment by jcowles** [comment]
The URL does actually exist, but the message looks like it's a server error having to do with SSL protocol mismatch -- this thread seems relevant:
https://github.com/requests/requests/issues/1847

**Comment by jcowles** [comment]
Note that this also happens with Alembic, TBB, OpenEXR, OIIO, OpenSubidv, and libjpeg-turbo; I believe because they are all hosted on GitHub.

If anyone else is hitting this issue, running build_usd.py with "--verbose" will print out the local path for each downloaded file. You can then download each file manually and move them to the path where build_usd.py searches.

**Comment by jcowles** [comment]
Both builds were started from clean directories.

**Comment by PascalArtus** [comment]
Hi,

At the time of reporting the file couldn't be found under this address for some reason (as in I couldn't reach it within my browser too). Now it's there again and the building script is working.

**Comment by jcowles** [comment]
FYI, I'm using Python 2.7.3 and cannot easily upgrade.

**Comment by jcowles** [comment]
I'm curious though, why did this only recently start happening?

**Comment by sunyab** [comment]
@jcowles - I posted earlier about github requiring TLS v1.2+ starting at the end of February, was there another issue you were running into that wasn't covered by that?
