### ISSUE TITLE
macOs libraries compiling but not working 

### ISSUE THREAD

**Issue by skarone** [PixarAnimationStudios/USD#46]
I got all the libraries compiled in macOS... but when I try to import them in python 2.7, I'm getting an error 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python/pxr/Gf/__init__.py", line 31, in <module>
    from pxr import Tf
  File "/usr/local/lib/python/pxr/Tf/__init__.py", line 85, in <module>
    from . import _tf
ImportError: cannot import name _tf`

This is just one example but I'm getting the same problem with all of them... 
I tried with Debug and Release libraries from xcode.

Some one is getting the same problem???

**Comment by asluk** [comment]
This is covered in issue #19 - you can symlink the dylib's to so's, or direct Xcode to build the python bindings as so's.

**Comment by skarone** [comment]
Thanks!, haha I solved the problem just renaming... and came back to report.. you are fast!

**Comment by c64kernal** [comment]
Thank you both.
