### ISSUE TITLE
Can't build with --katana option

### ISSUE THREAD

**Issue by Jay2008p** [PixarAnimationStudios/USD#468]
### Description of Issue
Problems with building USD using the option --katana: ERROR: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="C:\Program Files\USD" -DCMAKE_PREFIX_PATH="C:\Program Files\USD"  -G "Visual Studio 14 2015 Win64" -DPXR_ENABLE_PYTHON_SUPPORT=ON -DBUILD_SHARED_LIBS=ON -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_MAYA_PLUGIN=OFF -DPXR_BUILD_KATANA_PLUGIN=ON -DPXR_BUILD_HOUDINI_PLUGIN=OFF -DCMAKE_CXX_FLAGS="/Zm150" "C:\Python27\USD"'
See C:\Program Files\USD\build\USD\log.txt for more details.

Log file here: [log.txt](https://github.com/PixarAnimationStudios/USD/files/1922589/log.txt)

### Steps to Reproduce
1. Open 64 bit VS Command Prompt
2. Run C:\Python27\USD\build_scripts\build_usd.py --katana "C:\Program Files\USD"

### System Information (OS, Hardware)
OS: Windows 10 16299.192
CPU: Intel Core i5-6400
GPU: NVIDIA GTX 970
RAM: 8 GB DDR3

### Package Versions
Python: 2.7.11
CMake: 3.7.2
MSVC: 14.0 (VS 2015)

**Comment by Jay2008p** [comment]
Really tried to figure this out by myself but any help is appreciated!

**Comment by jtran56** [comment]
Filed as internal issue #159772.

**Comment by spiffmon** [comment]
Hi Jay,
   We should probably document it more clearly, but our distro does not yet support the katana (or houdini) plugins on Windows, yet, and it's a tough sell for development resources here, given our linux focus.  You might want to tell Foundry about your interest?

**Comment by bdeda** [comment]
Jay, 

I have been trying to get a windows build of the Katana plugin working too. I have been documenting some of the roadblocks in a thread in the usd-interest group. 

https://groups.google.com/forum/#!topic/usd-interest/3JkWfKmegOg 

Unfortunately, compilation was only the initial problem, and now I am debugging crashes when Katana tries to expand/load the usd data. I could do a PR or make a branch with what I have if there is anyone else interested in helping get it working. 

A working windows build is a requirement for us at Blizzard. We have a large portion of our production environment on Windows here at Blizzard. We could work around it and render only on linux, but that is not ideal.

**Comment by sunyab** [comment]
Closing this out, this option and the Katana USD plugin was removed in favor of the plugin supported by the Foundry, located here: https://github.com/TheFoundryVisionmongers/KatanaUsdPlugins.
