### ISSUE TITLE
Maya crash on usdImport of geo with creased edges

### ISSUE THREAD

**Issue by BSalem** [PixarAnimationStudios/USD#47]
As in the subject, importing a usd with edge creases into maya crashes maya.. (the same USDs work fine in katana and viewed properly in usdview)

Stack trace:
  Tarray::changeLogicalSizeBy(int)
  MFnMesh::setUVs(MFloatArray const&, MFloatArray const&, MString const_)
  PxrUsdMayaTranslatorMesh::_AssignUVSetPrimvarToMesh(UsdGeomPrimvar const&, MFnMesh&)
  PxrUsdMayaTranslatorMesh::Create(UsdGeomMesh const&, MObject, PxrUsdMayaPrimReaderArgs const&, PxrUsdMayaPrimReaderContext_)
  /opt/pixar/usd/third_party/maya/lib/libusdMaya.so(+0x7cf98) [0x7f66bded8f98]
  usdReadJob::_DoImport(UsdTreeIterator&, UsdPrim const&)
  usdReadJob::doIt(std::vector<MDagPath, std::allocator<MDagPath> >_)
  usdTranslatorImport::reader(MFileObject const&, MString const&, MPxFileTranslator::FileAccessMode)
  THfileConverter::reader(TsceneFile&)
  TfileTranslator::read(TsceneFile&)
  TglobalTranslator::doReadFile(TsceneFile&, bool, bool)
  TfileUtil::readFile(TsceneFile_, bool, bool, bool)
  TfileImporter::importFileToSceneFile(TsceneFile_, TsceneFile&, bool, bool, Tstring const_, TnamespaceSwapper_, TfileTranslator_, Tnamespace*_)
  TfileImporter::importFile(TsceneFile_, bool, bool, TglobalTranslatorBase::TrefIOMode, Tstring const_, TnamespaceSwapper_, bool)
  TfileCmd::handleFileImportFlag(TargDatabase&, TsceneFile_, TnamespaceSwapper_)
  TfileCmd::handleFlags(TargDatabase&, TsceneFile_, TnamespaceSwapper_, TgraphDiff_)
  TfileCmd::handleFlags(TargDatabase&, Tstring const&)
  TfileCmd::doCommand(TargList&)
  Mel_Command_Dispatch(SphNode_)
  node_exec
  sophia_call_executable
  SophiaExecutable::evaluate(void_)
  TcommandEngine::executeCommand(SophiaExecutable_, void_)
  TevalEchoCmd::doCommand(TargList&)
  Mel_Command_Dispatch(SphNode_)
  node_exec

**Comment by jtran56** [comment]
Filed as internal issue #136986.

**Comment by spiffmon** [comment]
Thanks, Belal!  Any chance you can attach a small usda file that demoes the behavior?

**Comment by BSalem** [comment]
Please find here a maya scene with a simple creased cube and the same cube exported into usda out of this scene.
[crashing_creased_geo.tar.gz](https://github.com/PixarAnimationStudios/USD/files/463741/crashing_creased_geo.tar.gz)

**Comment by BSalem** [comment]
One more thing I noticed regarding to this issue here that should minimize the area where the bug lives:
** if you import the USD using the usdImport command directly, then the file gets imported properly and maya doesn't crash (I didn't test passing optional flags but just used the defaults as this):
cmd.usdImport(f=usdFilePath)

But if you use the maya import method (file->import), then maya will crash even when trying different options for the import.

**Comment by spiffmon** [comment]
Thanks, Belal - we'll be looking into this soon!

**Comment by sdao** [comment]
Looks like the crash is Maya-side (we'll be reporting this to Autodesk, but we have a workaround in the meantime).

The crash occurs on a call to MFnMesh.setUVs() but if I set the UVs by hardcoding some dummy values into the code, the crash still occurs. The crash only occurs if we add a crease set in _AddCreaseSet() first before setting UVs.

There's a workaround that appears to work by manually calling MFnMesh.setCurrentUVSetName() before setting the UVs.

The attached `crash_maya.py` replicates some of what the importer is doing, and it will also trigger the crash. Create an empty scene with a single cube (pCube1) and then run the script; Maya will
crash (checked with 2016.sp6).

[crash_maya.py.tar.gz](https://github.com/PixarAnimationStudios/USD/files/488517/crash_maya.py.tar.gz)

**Comment by sunyab** [comment]
Closing out old issue -- this workaround was released in 0.7.2 in commit 6a8803f.
