### ISSUE TITLE
Issue compiling because of Plug_RegistrationMetadata

### ISSUE THREAD

**Issue by devGitHub48** [PixarAnimationStudios/USD#476]
### Description of Issue
Hi!

With Fastbuild, and Visual 2015, I have this issue :
\usd\include\pxr\base\plug\plugin.h(45): warning C4099: 'pxrInternal_v0_8__pxrReserved__::Plug_RegistrationMetadata': type name first seen using 'struct' now seen using 'class'

In usd\include\pxr\base\plug\plugin.h : class Plug_RegistrationMetadata;
In usd\include\pxr\base\plug\registry.h : struct Plug_RegistrationMetadata;
### Steps to Reproduce
1.  Include
2. Compile

### System Information (OS, Hardware)
Visual 2015, Windows 10, FastBuild
### Package Versions
I can't rememebr, 1 month ago
### Build Flags
Not the /w4099

Thanks

**Comment by jtran56** [comment]
Filed as internal issue #160084.

**Comment by sunyab** [comment]
Hi @devGitHub48, that warning should have been fixed by #439, which was merged into the dev branch in commit 47a2338e. I'm going to close this out, but please reopen if you're still running into this issue. Thanks!
