### ISSUE TITLE
NOOB - Running USD

### ISSUE THREAD

**Issue by HeilFigure** [PixarAnimationStudios/USD#48]
Hi, i'm very new to USD as well is Running GITHub OpenSource applications.

Could someone kindly show me a guide on how to get up and running with USD ( as if i'm opening up 3D's Max or any regular pre-packaged requiring User installation to C Drive plus desktop icons.

lol, Yes i'm a noob to Code, not ashamed. hahah.

Back to the matter at hand. So i downloaded VisualStudio15 and Linked the Repo On Github as instructed by tutorial.

So what do i do now? how do i get to use USD like normal software as i have seen in Some Pixar examples illustrating the strength of USD. Being a software enthusiast, i really want to give this a go but dont know how :(

I also have Python Commnd & Python GUI installed, i do see on the video examples, they load it using Python if im not mistaken.

Please help guys, i have tried to explain my issue as best as i can and looking for Solutions, I would be very greatful.

P.S ( does anyone know how to create a GitHub / Opensource / General (Installer) so that after you download all the zipped files and or folders. You just run the Installer, determine location path contain your software files..Set an installation path or after locating Files. It Reads (a pre-written code or script file provided by the creator so it works with The Installer) or copy over a "plugin" script to the folder containing the downloaded file (or customize the coded document by simply copy over and editing a simple line of code that the Installer searches for once you determine folder location so the installation can begin / or better Run The Software Direct From The Installer (installation not necessary) 

lol, i'm sure i sound pretty idiotic right now. but ah well.

**Comment by jtran56** [comment]
Filed as internal issue #137095.

**Comment by c64kernal** [comment]
Hi HeilFigure, thanks for your interest in USD.  Unfortunately, USD is more of a set of libraries geared mostly towards folks who use it to write software at this stage.  We're working with vendors in the industry to help them provide their customers with applications that support USD.  I hope you will see support for USD in your favorite 3D applications pop up in the not too distant future.  Also, the Windows port work is still on-going and not quite ready.

Having said that, if you'd like to put on a hard hat and learn how to build and use these libraries, we'd love to hear your perspective and feedback!  To help with that, it looks like you already found the documentation that we publish.  There's also a google group called usd-interest that has lots of helpful folks discussing various issues about USD, including how to build it.

Hope that helps!

**Comment by sunyab** [comment]
In the time since this issue was filed, we've added a build script to the repository that allows users to build USD and its dependencies with a single command. I'd definitely encourage anyone wanting to play around with USD to read the [documentation](https://github.com/PixarAnimationStudios/USD/blob/master/README.md) and give it a try. Hopefully it's enough to get people started; if it's not, please feel free to send feedback about how it could be made better!

Closing this out, thanks!
