### ISSUE TITLE
Simplified installation process (package manager?)

### ISSUE THREAD

**Issue by laserpanda** [PixarAnimationStudios/USD#49]
Steve would never have approved the installation process. Why not use some kind of package manager that takes care of all the dependencies and paths for you?

**Comment by jtran56** [comment]
Filed as internal issue #137180.

**Comment by derpDiggler** [comment]
thanks, I appreciate it!

**Comment by sunyab** [comment]
Version 0.7.6 includes a new build script that we hope will make it easier for people to build USD and its dependencies. Please see the documentation in [README.md](https://github.com/PixarAnimationStudios/USD/blob/master/README.md#getting-and-building-the-code) for examples on how to run the script, which is located here: https://github.com/PixarAnimationStudios/USD/tree/master/build_scripts. 

We've already gotten some feedback on the build script and would love to get more. In the meantime, I think the core of this issue has been addressed, so I'm going to close this out. Thanks!
