### ISSUE TITLE
Unused data type

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#491]
https://github.com/PixarAnimationStudios/USD/blob/f15793adc74d7b164509b3a38bab193148b462e3/pxr/usd/lib/usd/schemaBase.h#L57

Seems like it should have been removed in https://github.com/PixarAnimationStudios/USD/commit/a8421adf594d43cb46cee01c1f09e291ad4469c0

**Comment by jtran56** [comment]
Filed as internal issue #160749.

**Comment by blevin** [comment]
More generally, we should really do a cleanup pass to remove all traces of the old "unspecified bool" idiom in favor of the "explicit bool" operator available in C++11.  Patches welcome!
