### ISSUE TITLE
[usdMaya] TestUsdImportMesh fails

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#496]
### Description of Issue
testUsdImportMesh fails when running the maya testsuite. There is a dangling "from pixar import UsdGeom" in the global scope, which should be placed in the try / except logic just below.

https://github.com/PixarAnimationStudios/USD/blob/dev/third_party/maya/lib/usdMaya/testenv/testUsdImportMesh.py#L33

### Steps to Reproduce
1. run the testsuite with the maya plugin enabled

**Comment by jtran56** [comment]
Filed as internal issue #160790.

**Comment by sunyab** [comment]
Hey @sirpalee, this should be fixed in commit 8fff808e. This issue was introduced in commit 8e25139b in the dev branch and is not in 0.8.5, so I'm going to close this out as fixed. Sorry for the trouble!
