### ISSUE TITLE
libtiff fails to download using ftp link in build script

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#498]
I was unable to download libtiff on linux using the link in the build script.

TIFF_URL = "ftp://download.osgeo.org/libtiff/tiff-4.0.7.zip"

If I change the ftp:// to http:// it can connect and the script will progress.

Centos 7

USD-0.8.5

**Comment by 21cores** [comment]
me too

**Comment by jtran56** [comment]
Filed as internal issue #160886.

**Comment by sunyab** [comment]
Hi all, this was addressed by pull request #499, which was just merged into the dev branch. Marking this as pending release. Thanks!

**Comment by sunyab** [comment]
This fix was released with v0.8.5a, closing this out. Thanks!
