### ISSUE TITLE
Tests get stuck with USD_EDITOR = vim

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/USD#505]
### Description of Issue
When the USD_EDITOR environment variable is set to vi/vim, it's not possible to run all tests.
For example, `testUsdEditFilePermissions2` is testing if a write protected file can be opened with `usdedit` in a read only way. That works but doesn't return and so the test is stuck.
These kind of tests could use a modified test environment where USD_EDITOR is set to emacs or another suitable editor.

### Steps to Reproduce
1. `setenv USD_EDITOR vim`   (or `export USD_EDITOR=vim`)
2. `ctest -R testUsdEditFilePermissions2`

### System Information (OS, Hardware)
centos7

### Package Versions
0.8.5

### Build Flags
-DPXR_BUILD_TESTS=TRUE

**Comment by jtran56** [comment]
Filed as internal issue #161150.

**Comment by c64kernal** [comment]
Hey @AlexSchwank @spiffmon and I looked at this briefly and we think the issue is that in the CMakeLists.txt file we're setting EDITOR to head but we think we should be setting USD_EDITOR instead.  Thanks for the report!
