### ISSUE TITLE
[usdview] Embree giving framebuffer error

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/USD#509]
### Description of Issue
When using Embree as renderer in usdview 0.8.5, clicking in the viewport gives an error message: 
```
Traceback (most recent call last):
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 1813, in mousePressEvent
    event.button(), event.modifiers())
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 1997, in pickObject
    selectedInstanceIndex, selectedElementIndex = self.pick(pickFrustum)
  File "/.../usd/0.8.5/.../lib/python/pxr/Usdviewq/stageView.py", line 1946, in pick
    self._dataModel.stage.GetPseudoRoot(), self._renderParams)
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_8__pxrReserved__::HdxIntersector::Query' at line 266 in file /.../build/pxr/imaging/lib/hdx/intersector.cpp : 'framebuffer object not supported'
```

This might be related to https://github.com/PixarAnimationStudios/USD/issues/508

### Steps to Reproduce
1. Build usdview with the embree plugin (-DPXR_BUILD_EMBREE_PLUGIN=TRUE)
2. `usdview myTestFile.usd`
3. Click in viewport

### System Information (OS, Hardware)
centos7

### Package Versions
0.8.5

### Build Flags
-DPXR_BUILD_EMBREE_PLUGIN=TRUE

**Comment by jtran56** [comment]
Filed as internal issue #161153.

**Comment by c64kernal** [comment]
Hi @AlexSchwank, do you mind trying this out in the dev branch?  It should be fixed now.

**Comment by AlexSchwank** [comment]
HI @c64kernal , unfortunately I'm unable to fully test the fix. #508 is now directly causing a segfault on the dev branch. However, in the tests I was able to do it looks good.

**Comment by sunyab** [comment]
Going to close out this old issue, it looks like this has been fixed for some time. Thanks!
