### ISSUE TITLE
Katana: Assigned PxrRis NetworkMaterial from USD crashes renderman

### ISSUE THREAD

**Issue by BSalem** [PixarAnimationStudios/USD#51]
Rendering an object with a USD NetworkMaterial assigned to it crashes Renderman(21.1)
please find attached recipe/usd produced this issue with me.
[shdNetwork.tar.gz](https://github.com/PixarAnimationStudios/USD/files/468281/shdNetwork.tar.gz)

**Comment by jtran56** [comment]
Filed as internal issue #137246.

**Comment by c64kernal** [comment]
As the Katana plugins will be removed from the USD repo, closing this issue.
