### ISSUE TITLE
build_usd.py: Windows builds should generate debug info by default

### ISSUE THREAD

**Issue by zomgrolf** [PixarAnimationStudios/USD#515]
There is little reason not to generate debug info when building USD (and its dependencies) on Windows, as it has virtually no impact on produced binaries and it makes debugging **much** easier.

Requires only some  minor changes to make this work: inside `RunCMake`, use `RelWithDebInfo` configuration instead of `Release`, when calling `cmake --build`. Optionally, pass `debug-symbols=on` to b2, when building Boost.

Minor change, but makes for a much nicer 'out-of-the-box' experience when building and using USD on Windows. 

Major bonus points for installing generated PDBs alongside the binaries (i.e. copying them to the bin/ and lib/ directories), but that would require more substantial changes, I imagine.

**Comment by jtran56** [comment]
Filed as internal issue #161322.

**Comment by meshula** [comment]
Actually, publishing the pdbs is pretty easy, it would be a simple modification to the pxr_library functcion in the cmake scripts, something like  this -

install(
    FILES
        $<TARGET_PDB_FILE:${NAME}>
    DESTINATION
        bin OPTIONAL)

**Comment by zomgrolf** [comment]
Awesome, thanks for the tip, Nick! Will definitely try this out. I don't have much experience with CMake yet (esp. on Windows) and this makes my life easier. Much appreciated!

**Comment by meshula** [comment]
Oh! There's already a pull request with this fix! 

https://github.com/PixarAnimationStudios/USD/pull/502

**Comment by devGitHub48** [comment]
Hello!
Did the change make it to the main branch?

**Comment by c64kernal** [comment]
Hi @devGitHub48  -- no, unfortunately this change hasn't been merged back yet.

**Comment by BrianHarris** [comment]
PR 502 was integrated into USD 19.05

**Comment by sunyab** [comment]
Yep, this landed in v19.05 as commit b3015dc. Closing this out, thanks!
