### ISSUE TITLE
Build fails with "'isnan' was not declared in this scope" on Ubuntu

### ISSUE THREAD

**Issue by popey** [PixarAnimationStudios/USD#52]
See below for extract. I'm building on Ubuntu 16.04, 64-bit, and have got the following when building either the release, or the tip of trunk.

[ 25%] Building CXX object pxr/base/lib/gf/CMakeFiles/gf.dir/bbox3d.cpp.o
[ 25%] Building CXX object pxr/base/lib/gf/CMakeFiles/gf.dir/camera.cpp.o
[ 25%] Building CXX object pxr/base/lib/gf/CMakeFiles/gf.dir/colorRamp.cpp.o
In file included from /root/parts/usd/build/include/pxr/base/gf/colorRamp.h:28:0,
                 from /root/parts/usd/src/pxr/base/lib/gf/colorRamp.cpp:24:
/root/parts/usd/build/include/pxr/base/gf/rgb.h: In member function 'bool GfRGB::IsValid() const':
/root/parts/usd/build/include/pxr/base/gf/rgb.h:80:49: error: 'isnan' was not declared in this scope
     bool IsValid() const { return !isnan(_rgb[0]); }
                                                 ^
/root/parts/usd/build/include/pxr/base/gf/rgb.h:80:49: note: suggested alternative:
In file included from /root/parts/usd/build/include/pxr/base/arch/math.h:36:0,
                 from /root/parts/usd/build/include/pxr/base/gf/math.h:27,
                 from /root/parts/usd/build/include/pxr/base/gf/colorRamp.h:27,
                 from /root/parts/usd/src/pxr/base/lib/gf/colorRamp.cpp:24:
/usr/include/c++/5/cmath:641:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
pxr/base/lib/gf/CMakeFiles/gf.dir/build.make:386: recipe for target 'pxr/base/lib/gf/CMakeFiles/gf.dir/colorRamp.cpp.o' failed
make[2]: **\* [pxr/base/lib/gf/CMakeFiles/gf.dir/colorRamp.cpp.o] Error 1
CMakeFiles/Makefile2:1345: recipe for target 'pxr/base/lib/gf/CMakeFiles/gf.dir/all' failed
make[1]: **\* [pxr/base/lib/gf/CMakeFiles/gf.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by jtran56** [comment]
Filed as internal issue #137247.

**Comment by doctormo** [comment]
@popey can you give that pull request a try and confirm if it works for you?

**Comment by popey** [comment]
Thanks @doctormo - that got it past this issue. Much appreciated.
