### ISSUE TITLE
UsdGeomModelAPI cardGeometry always displays as cross

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#522]
I am unable to get UsdGeomModelAPI model:cardGeometry to display anything other than cross. Setting the attribute to "box" or "fromTexture" always displays as cross.

I am using the modelAPI to create the model:cardGeometry and model:drawMode on a Prototypes prim under the PointInstancer, and the prototypes references are kind components. 

This is on 0.8.5 in both USDView and Maya as a proxy.

Spiff was able to repeat the error and posted so in this forum post.

https://groups.google.com/forum/#!topic/usd-interest/sFfxXMX6K2s

### Steps to Reproduce
1.  Set model:drawMode to "cards"
2. Set model:cardGeometry to "box" or "fromTexture"

Linux Centos 7

0.8.5

**Comment by jtran56** [comment]
Filed as internal issue #161680.

**Comment by radon199** [comment]
After further disscusions on the forum this was determined to be because I was writing the attribute not on the “kind = component” asset, and also because I had prims without a kind between the root and the component on my stage.

This can be resolved.

**Comment by c64kernal** [comment]
Thanks @radon199. @tcauchois has updated the documentation as well.
