### ISSUE TITLE
[usdImaging] Some xxxLightAdapter classes are not built

### ISSUE THREAD

**Issue by tariollef** [PixarAnimationStudios/USD#523]
### Description of Issue
Following 3 classes are not built in usdImaging library:

```
        cylinderLightAdapter
        diskLightAdapter
        distantLightAdapter
```

I had to add those 3 lines in `PUBLIC_CLASSES` section of `pxr_library(usdImaging LIBRARIES ...)` code in pxr/usdImaging/lib/usdImaging/CMakeLists.txt

### Steps to Reproduce
1. Build USD v0.8.5a
2. In a custom hydra plugin (for instance), try to include one of these 3 headers: they're missing.
3. Even if you install those headers manually from USD source tree, linking your custom plugin fails because implementation of these 3 classes is not built into usdImaging library.

### System Information (OS, Hardware)
Win 10, CentOS 7

### Package Versions
0.8.5a

**Comment by sunyab** [comment]
Thanks for filing this @tariollef, we've just pushed a fix up to the dev branch which will be included in the next release.

**Comment by jtran56** [comment]
Filed as internal issue #161682.
