### ISSUE TITLE
[Windows] Issue with Boost 1.61 and c++17

### ISSUE THREAD

**Issue by devGitHub48** [PixarAnimationStudios/USD#531]
### Description of Issue
While compiling with Visual 2017 and with ISO C++17 Standard (/std:c++17) flag, I have a lot of error with Boost 1.61

I can't remember when I last get the USD depot :(
### Steps to Reproduce
1.  Build usd with python USD\build_scripts\build_usd.py "C:\Program Files\USD" --force-all --no-maya --no-houdini --no-python --no-imaging
2. In a cpp file :
`
#ifdef _DEBUG
#define TBB_USE_DEBUG 1
#endif

#pragma warning(push)
#pragma warning (disable:4800)

#include "pxr/usd/usd/usdFileFormat.h"
#include "pxr/usd/usd/common.h"
#include "pxr/usd/usd/stage.h"
#include "pxr/base/tf/errorMark.h"
#include "pxr/base/plug/registry.h"
#include "pxr/base/plug/plugin.h"
#include "pxr/usd/sdf/schema.h"
#include "pxr/usd/usd/attribute.h"
#include "pxr/usd/usd/relationship.h"
#include "pxr/usd/usd/references.h"
#include "pxr/usd/usdGeom/modelAPI.h"
#include "pxr/usd/usdGeom/mesh.h"
#include "pxr/usd/usdGeom/xformCommonAPI.h"
#include "pxr/usd/usdGeom/faceSetAPI.h"
#include "pxr/usd/usdGeom/metrics.h"
#include "pxr/base/tf/getenv.h"
#include "pxr/base/tf/setenv.h"
#include "pxr/usd/ar/defaultResolver.h"
#include "pxr/usd/ar/defineResolver.h"
#include "pxr/base/gf/rotation.h"
#include "pxr/usd/usd/variantSets.h"
#include "pxr/usd/usd/debugCodes.h"
#include "pxr/usd/kind/registry.h"
`

3. Compile with Visual 2017 and with ISO C++17 Standard (/std:c++17) flag
### System Information (OS, Hardware)
Windows 10, Visual 2017, with ISO C++17 Standard (/std:c++17) flag
### Build Flags
We are using Fast build to generate our projects

**Comment by devGitHub48** [comment]
Well, could it be possible not to use Boost ? :D

**Comment by spiffmon** [comment]
De-boostifying is a future goal, but it's a gigantic project that will cause ripples through our larger in-house codebase, also.  So it's going to take some time!

**Comment by devGitHub48** [comment]
using Boost_1.67 fixed my issues.

To get boost, I used vcpkg from Microsoft and only a subset thanks to Nick!
