### ISSUE TITLE
[Boost] boost python lib not found on USD build

### ISSUE THREAD

**Issue by RDelet** [PixarAnimationStudios/USD#538]
I everyone,

I try to build USD with python support for build maya plugin. But with python support I have an error on usd build. boost_python libraries was not found.

**Steps to Reproduce :**
1.  I change python file "build_usd.py" for update boost library.
    - With Boost lib 1.61 few boost lib was not found and USD not build
    - With Boost lib 1.64 just boost python was not found USD build with --no-python flag.
    - With Boost 1.63, 1.65, 1.66, 1.67 build have error.
2.  Use "build_usd.py" for build USD. All modules build without error

**System Information :**
windows 10
cmake 3.11.0
VisualStudio 14 2015

**Package Versions :**
last master

**Build Flags :**
--force FORCE_BUILD --python --alembic --tests --maya, I try with this flag too --force FORCE_BUILD --python
[log.txt](https://github.com/PixarAnimationStudios/USD/files/2118992/log.txt)

**Comment by RDelet** [comment]
I found solution.

I loose file user-config.jam  in %HOMEPATH% with python parameter.

**Comment by jtran56** [comment]
Field as internal issue #162207.

**Comment by arzezniczak** [comment]
@RDelet Could you please elaborate how did you resolved this issue?
I'm trying to use Boost 1.67, I've edited `build_usd.py` but I'm getting error about missing boost_python library. But I don't understand how you resolved it.

**Comment by sunyab** [comment]
Closing out this issue. We've made several improvements to the detection of boost in the build so hopefully this won't be a problem going forward.

@arzezniczak - the boost 1.67 issue with the missing boost_python should be resolved by commit 4a8ce90 which was just checked into the dev branch earlier today.
