### ISSUE TITLE
[Maya USD exporter] Negative values converted to NaNs

### ISSUE THREAD

**Issue by sourimantg** [PixarAnimationStudios/USD#539]
### Description of Issue

When exporting (from Maya) objects that have a PxrSurface shader attached, with a Physical definition of a specular lobe, potential negative values (in the extinction coefficient for instance) are exported as NaNs in the target usd file.

Context: I was trying to make PxrSurface definitions match an existing Mitsuba scene, where in some rare occasions the extinction goes to very small negative values, which should be possible to handle.

### Steps to Reproduce
1. Open Maya (2017 in my case)
2. Create a simple geometry and attach a PxrSurface shader to it
3. In the _Primary Specular_ section, set the _Specular Fresnel Mode_ to _Physical_
4. Modify the red component of the extinction coefficient to a negative value (e.g. -0.1) in RGB [0,1] mode
5. Export to USD

### System Information (OS, Hardware)
Windows 7

### Package Versions
0.8.5a

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
