### ISSUE TITLE
[Maya USD exporter] Maya crash while exporting to file in use

### ISSUE THREAD

**Issue by sourimantg** [PixarAnimationStudios/USD#540]
### Description of Issue
When exporting from Maya a USD file that is already in use, Maya simply crashes instead of indicating it cannot write to the file.

### Steps to Reproduce
1. Open Maya
2. Export a maya scene to a USD file
3. Open the USD file in usdview (and keep it open)
4. Re-export the scene from Maya to the very same USD file -> maya crashes

### System Information (OS, Hardware)
Windows 7, Maya 2017

### Package Versions
0.8.5a

**Comment by jtran56** [comment]
Filed as internal issue #162208.

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
