### ISSUE TITLE
Link to jpegsrc.v9b is down

### ISSUE THREAD

**Issue by illera88** [PixarAnimationStudios/USD#551]
### Description of Issue
It seems that the link to download `jpegsrc.v9b` used in the python build_usd.py is down.
this is the URL: http://www.ijg.org/files/jpegsrc.v9b.tar.gz
### Steps to Reproduce
1. Just run the build command ` python build_scripts/build_usd.py --no-python -vvv build`

### System Information (OS, Hardware)
Centos 7
### Package Versions
latest
### Build Flags
 python build_scripts/build_usd.py --no-python -vvv build

**Comment by sunyab** [comment]
Seems like this might have been a temporary issue, the URL is working for me now. Closing, thanks!
