### ISSUE TITLE
[sdf/layer] UpdateExternalReference for variants

### ISSUE THREAD

**Issue by fabal** [PixarAnimationStudios/USD#553]
### Description of Issue
Just wondering if there's any plan to implement variant's [support](https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/sdf/layer.cpp#L2825) in UpdateExternalReference?

### Steps to Reproduce
1.

**Comment by jtran56** [comment]
Filed as internal issue #162818.

**Comment by c64kernal** [comment]
Thanks for the report, yes we should absolutely support payloads, we'll use this issue to track the work of adding the support.  Thanks again!

**Comment by spiffmon** [comment]
Hi Fabal, when you mentioned it's actually VariantSets, I realized that this is an issue we fixed in dev about a month ago, with [commit 21d8dd8](https://github.com/PixarAnimationStudios/USD/commit/21d8dd81abe5e6da40629f37e157878d1be161da#diff-f866aa480a9aa5fc9b1f69bebaea10d5)

Closing!
