### ISSUE TITLE
MSVC 15.7+ Code analysis reports syntax errors in USD headers

### ISSUE THREAD

**Issue by zomgrolf** [PixarAnimationStudios/USD#571]
### Description of Issue
When trying to run code analysis on code that uses USD 0.8.5, I get a lot of errors reported by Visual Studio, even after adding USD to CAExcludePath:

```
\include\pxr\base\tf\diagnosticlite.h(81,62): error C2144:  syntax error: 'int' should be preceded by ';'
\include\pxr\base\tf\diagnosticlite.h(81,62): error C2144:         char const *fmt, ...) const ARCH_PRINTF_FUNCTION(2,3);
\include\pxr\base\tf\diagnosticlite.h(81,62): error C2144:                                                              ^
\include\pxr\base\tf\diagnosticlite.h(81,62): error C2208:  'int': no members defined using this type
\include\pxr\base\tf\diagnosticlite.h(81,62): error C2208:         char const *fmt, ...) const ARCH_PRINTF_FUNCTION(2,3);
```
Looking at the reported code:
```
base/tf/diagnosticlite.h
    TF_API void IssueError(
        char const *fmt, ...) const ARCH_PRINTF_FUNCTION(2,3);
    TF_API void IssueFatalError(
        char const *fmt, ...) const ARCH_PRINTF_FUNCTION(2,3);
    TF_API void IssueWarning(
        char const *fmt, ...) const ARCH_PRINTF_FUNCTION(2,3);
    TF_API void IssueStatus(
        char const *fmt, ...) const ARCH_PRINTF_FUNCTION(2,3);
```
And the definition of ARCH_PRINTF_FUNCTION:
```
base/arch/attributes.h

#   include <SAL.h>
#   define ARCH_PRINTF_FUNCTION(_fmt, _firstArg) \
        _Printf_format_string_
#   define ARCH_SCANF_FUNCTION(_fmt, _firstArg)	\
        _Printf_format_string_
#   define ARCH_NOINLINE // __declspec(noinline)
#   define ARCH_UNUSED_ARG
#   define ARCH_USED_FUNCTION        
```

Now, I might be mistaken, but it looks to me that `_Printf_format_string_` is meant to be used as an annotation for the format string argument in a printf-like function, not an annotation that follows the function signature (unlike __attribute__((format(printf))), so it's more like:
`void IssueError(char const* _Printf_format_string_ fmt, ...)`
Or simply define ARCH_PRINTF_FUNCTION and ARCH_SCANF_FUNCTION to nothing, when using MSVC.

Builds without code analysis are fine.

### System Information (OS, Hardware)
Windows 10 64-bit (Home & Pro) ver. 1803, VS 2017 Pro 15.7+ (might be present in older versions as well), 64-bit build

**Comment by c64kernal** [comment]
Thanks for reporting!  You're totally right.  I think the SAL extensions get turned off when not running static analysis.

**Comment by jtran56** [comment]
Filed as internal issue #163149.
