### ISSUE TITLE
[USD katana] Arnold katana is unable to render USD point instances

### ISSUE THREAD

**Issue by NickWu** [PixarAnimationStudios/USD#572]
### Description of Issue
Arnold katana is unable to render nested USD point instances. 

### Steps to Reproduce
1.Open ballGrid.katana from within attached file. 
2.Do a preview render on Render node.
3.You will notice that the small cubes are missing in the render, only showing cones. 
4.Disconnect AttributeCopy2 and connect AttributeCopy5 to Merge9 node, then do a preview render again. The small cubes now should appear in the render.

[katana_USD.tar.gz](https://github.com/PixarAnimationStudios/USD/files/2228622/katana_USD.tar.gz)

### System Information (OS, Hardware)
CentOS 7

### Package Versions
0.8.5

**Comment by spiffmon** [comment]
Hi Nick!
   Unfortunately, since we don't use Arnold, I don't think we're going to
be able to field this one.  Can you contact Foundry about the issue?

--spiff

**Comment by NickWu** [comment]
Many thanks. Will do.

**Comment by jtran56** [comment]
Filed as internal issue #163334.
