### ISSUE TITLE
[usdview] random attribute value representation changes

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/USD#574]
### Description of Issue
The attribute value representation in the _value_ tab can differ when opening a single file multiple times.
For example, a matrix is sometimes displayed like
```
Gf.Matrix4d(1.0, 0.0, 0.0, 0.0,
            0.0, 1.0, 0.0, 0.0,
            0.0, 0.0, 1.0, 0.0,
            20.0, 0.0, -10.0, 1.0)
```
And sometimes like this:
```
1, 0, 0, 0
0, 1, 0, 0
0, 0, 1, 0
20, 0, -10, 1
```

### Steps to Reproduce
I couldn't find a way to consistently reproduce this. I just opened the same file over and over again and checked how the matrix is represented.

### System Information (OS, Hardware)
centos7
### Package Versions
0.8.5a

**Comment by jtran56** [comment]
Filed as internal issue #163335.
