### ISSUE TITLE
usdview segfault on UsdPreviewSurface example (dev branch)

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#576]
### Description of Issue
usdview segfaults while trying to open the attached file, which was copied from https://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html

[example-surface.zip](https://github.com/PixarAnimationStudios/USD/files/2242052/example-surface.zip)

### Steps to Reproduce
0. Sync and build the USD **dev** branch
1.  open the attached file with usdview
2. segfault

### System Information (OS, Hardware)
Windows 10, VS 2015
GTX 980

### Package Versions
Defaults from build script

### Build Flags
python build_scripts\build_usd.py --build-monolithic --no-tests --no-docs --no-ptex --no-embree --alembic --no-hdf5 ..\usd_dev_py-v0.8.5

**Comment by spiffmon** [comment]
Hi Jeremy,
    When I open example-surface.usd in our internal build of usdview, I get no segfault, and the expected warnings about missing textures.  I did note some problems with the example in the spec that we should fix:
1. The plane is Z-up, but we're not declaring that in the layer metadata... we should probably just make it Y-up :-)
2. The plane doesn't have an authored extent, so you get clipping while orbiting
3. We should make use of the _fallback_ parameter of the UsdUVTexture node!

We'll shortly be pushing a bunch of work to github, which hopefully will resolve the segfault you're seeing.

**Comment by jcowles** [comment]
Cool, thanks Spiff!

**Comment by jtran56** [comment]
Filed as internal issue #163444.

**Comment by c64kernal** [comment]
@jcowles Hey Jeremy, do you mind confirming that you no longer get the segfault here in dev anymore and close this out, if so?

**Comment by jcowles** [comment]
Yep, looks good!
