### ISSUE TITLE
CreateAttribute failed 

### ISSUE THREAD

**Issue by TongkuiSu** [PixarAnimationStudios/USD#579]
```
bool Valid = ShaderPrim.GetPrim().CreateAttribute(USDAttributeName, pxr::SdfValueTypeNames->Color3f, false).Set(OmniverseConvert(OverriddenValue->ParameterValue));
```
When the `USDAttributeName` is "Scale" or "Transform", it works well, but when its value is "Diamond Color" or "Field Color", it returns false,  both of the attribute are vector, it seems that `CreateAttribute` failed and I guess `USDAttributeName` doesn't match what usd requires, but I didn't find any doc about the rule of 'usdattribute' name, can anyone help me?

**Comment by spiffmon** [comment]
It looks like the documentation describing property name syntax is pretty
well buried - we'll need to improve that!  Property names (attributes and
relationships) follow C/python identifier semantics with the addition of
":" to create "namespaced properties".  each namespace component must begin
with an alphabetic character or underscore, followed by an alnum char or
underscore.

Legal:
primvars:displayColor
__faceIndex
_99

Illegal:
no spaces
99

etc.
--spiff

**Comment by spiffmon** [comment]
The helper function, which unfortunately does not describe the syntax, is
SdfPath::IsValidNamespacedIdentifier()
<http://graphics.pixar.com/usd/docs/api/class_sdf_path.html#a8c66a8d5eadec9b49cd9a5f32747834e>
(and
IsValidIdentifier, for prim-path components, which cannot be namespaced
with ':'s.  The syntax is described in the lower-level function that these
functions call, TfIsValidIdentifier()
<http://graphics.pixar.com/usd/docs/api/group__group__tf___string.html#ga1008cfa78840de3ddd9730dc94e9d0da>

--spiff

**Comment by TongkuiSu** [comment]
Thanks!
