### ISSUE TITLE
Cannot build Maya plugin & Alembic plugin properly on Fedora 23

### ISSUE THREAD

**Issue by duyyudus** [PixarAnimationStudios/USD#58]
CMake run with warnings cannot generate safe runtime search path for _usdAbc, usdAbc, _usdMaya, usdMaya target.
make built successfully, but when I try to load pxrUsd.so in Maya, an error occur : 
> // Error: line 1: Unable to dynamically load : /usr/local/third_party/maya/plugin/pxrUsd.so
> /usr/local/third_party/maya/plugin/../../../lib/libglf.so: undefined symbol: _ZN4Ptex4v2_29PtexCache6createEimbPNS0_16PtexInputHandlerEPNS0_16PtexErrorHandlerE // 
> // Error: line 1: /usr/local/third_party/maya/plugin/../../../lib/libglf.so: undefined symbol: _ZN4Ptex4v2_29PtexCache6createEimbPNS0_16PtexInputHandlerEPNS0_16PtexErrorHandlerE (pxrUsd) // 

And when I open .abc file using _usdview_, it can't determine file format.

I'm using Fedora 23 and Maya 2016, hope you can help, thank you :)

**CMake log:**
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   python
--   regex
--   system
--   program_options
-- Using default system allocator because PXR_MALLOC_LIBRARY is unspecified
-- Found PySide Tools: /usr/bin/pyside-uic, /usr/bin/pyside-rcc
-- Configuring done
CMake Warning (dev) at cmake/macros/Public.cmake:63 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "/usr/lib64/libboost_program_options.so" of target
  "sdfdump" does not exist.
Call Stack (most recent call first):
  pxr/usd/bin/sdfdump/CMakeLists.txt:1 (pxr_cpp_bin)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at cmake/macros/Public.cmake:131 (add_library):
  Cannot generate a safe runtime search path for target _usdAbc because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/macros/Public.cmake:606 (pxr_shared_library)
  pxr/usd/plugin/usdAbc/CMakeLists.txt:9 (pxr_plugin)

CMake Warning at cmake/macros/Public.cmake:467 (add_library):
  Cannot generate a safe runtime search path for target usdAbc because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  pxr/usd/plugin/usdAbc/CMakeLists.txt:9 (pxr_plugin)

CMake Warning at cmake/macros/Public.cmake:131 (add_library):
  Cannot generate a safe runtime search path for target pxrUsdMayaGL because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libtbb.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libpython2.7.so.1.0] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libtbbmalloc.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  third_party/maya/lib/pxrUsdMayaGL/CMakeLists.txt:3 (pxr_shared_library)

CMake Warning at cmake/macros/Public.cmake:131 (add_library):
  Cannot generate a safe runtime search path for target _usdMaya because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libpython2.7.so.1.0] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libtbb.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libtbbmalloc.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/macros/Public.cmake:293 (pxr_shared_library)
  third_party/maya/lib/usdMaya/CMakeLists.txt:3 (pxr_shared_library)

CMake Warning at cmake/macros/Public.cmake:131 (add_library):
  Cannot generate a safe runtime search path for target usdMaya because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libpython2.7.so.1.0] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libtbb.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libtbbmalloc.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  third_party/maya/lib/usdMaya/CMakeLists.txt:3 (pxr_shared_library)

CMake Warning at cmake/macros/Public.cmake:467 (add_library):
  Cannot generate a safe runtime search path for target pxrUsd because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libtbb.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libpython2.7.so.1.0] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib
    runtime library [libtbbmalloc.so.2] in /usr/lib64 may be hidden by files in:
      /usr/autodesk/maya2016.5/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  third_party/maya/plugin/pxrUsd/CMakeLists.txt:3 (pxr_plugin)

-- Generating done
-- Build files have been written to: /home/myname/Documents/Git-Repo/USD/build

**Comment by jtran56** [comment]
Filed as internal issue #137519.

**Comment by spiffmon** [comment]
The ptex issue is discussed here: https://groups.google.com/d/msg/usd-interest/wJr8c_iTO7k/8fpP2PvrDwAJ

The second issue, not finding the usdAbc plugin, is discussed here, with workaround: https://groups.google.com/d/msg/usd-interest/CDBCebkVY-I/BqB4tiR8CwAJ

Hopefully that can help you make some progress?

**Comment by duyyudus** [comment]
Thank spiffmon,

usdAbc works well now.
However ptex issue is still there after stopgap workaround ( remove libPtex.so )
Anyway, now I just need some way to convert my asset into Usd format, usdAbc is enough temporarily :)

**Comment by spiffmon** [comment]
You can simply use usdcat to convert Alembic files to USD!

usdcat -o foo.usd foo.abc

--SpiffiPhone
