### ISSUE TITLE
Glf fails to read half-float EXR images

### ISSUE THREAD

**Issue by sourimantg** [PixarAnimationStudios/USD#581]
### Description of Issue

While using Glf to read input EXR files, in which each channel is encoded as a half float (tpypical use-case: environment lights), a segmentation fault occurs.

### Steps to Reproduce
1. Properly setup Glf for image reading
```
pxr::GlfImageSharedPtr image = pxr::GlfImage::OpenForReading(texName);
pxr::GlfImage::StorageSpec storage;
[...]
image->Read(storage); // <- segfault happens here
```

`texName` refers to a valid, resolved path to an EXR image with half float channels.
`storage` is initialized properly.

### Solution proposal

The problem seems to come from the method `_GetOIIOBaseType(GLenum type)`, in the file `oiioImage.cpp`. The conversion between a GLenum and a TypeDesc is missing the half float case. The implementation should look something like this:
```
/// Converts a GL type into its OpenImageIO component type equivalent.
static TypeDesc
_GetOIIOBaseType(GLenum type)
{
    switch (type) {
    case GL_UNSIGNED_BYTE:
    case GL_BYTE:
        return TypeDesc::UINT8;
    case GL_UNSIGNED_INT:
    case GL_INT:
        return TypeDesc::UINT;
    case GL_HALF_FLOAT:        // new line
        return TypeDesc::HALF; // new line
    case GL_FLOAT:
        return TypeDesc::FLOAT;
    default:
        TF_CODING_ERROR("Unsupported type");
        return TypeDesc::FLOAT;
    }
}
```
It's worth noting that the reverse conversion implemented in `_GLTypeFromImageData(TypeDesc typedesc)` properly addresses the half float case.

Applying this modification solves the problem on my tests.

### System Information (OS, Hardware)

Windows 7, but should be similar on other platforms

### Package Versions

0.8.5a, not tested on dev branch but according to a git blame, the problem should be in this branch too.

### Build Flags

(stripped the directory-related directives)
```
cmake -G "Visual Studio 14 2015 Win64"
-DBoost_NO_SYSTEM_PATHS=ON 
-DPXR_ENABLE_PYTHON_SUPPORT=ON 
-DBUILD_SHARED_LIBS=ON 
-DPXR_BUILD_DOCUMENTATION=OFF 
-DPXR_BUILD_TESTS=OFF
-DPXR_BUILD_IMAGING=ON 
-DPXR_ENABLE_PTEX_SUPPORT=OFF 
-DPXR_BUILD_EMBREE_PLUGIN=OFF 
-DPXR_BUILD_USD_IMAGING=ON 
-DPXR_BUILD_ALEMBIC_PLUGIN=OFF 
-DPXR_BUILD_MAYA_PLUGIN=ON 
-DPXR_BUILD_KATANA_PLUGIN=OFF 
-DPXR_BUILD_HOUDINI_PLUGIN=OFF 
-DCMAKE_CXX_FLAGS="/Zm150"
```

**Comment by jtran56** [comment]
Filed as internal issue #164138.
