### ISSUE TITLE
Houdini Plugin on Mac

### ISSUE THREAD

**Issue by jbartolozzi** [PixarAnimationStudios/USD#586]
Not sure if this is the right place to ask this question, but what is the current state of the Houdini plugin on Mac? 
I didn't see anywhere that it wasn't supported. Then in order to get any feedback from my build attempts I had to run cmake manually which is where I finally saw that it isn't supported.
Is this something that USD is working on / SideFX?

**Comment by spiffmon** [comment]
Hi James,
   We can't speak for SideFx, but OSX support for the Pixar Houdini plugins
has not been a priority for us.

--spiff

**Comment by jtran56** [comment]
Filed as internal issue #164141.

**Comment by amotarzi** [comment]
Indeed, Houdini 17 now has a toolkit folder with a much simplified USD plugin install process (see under "usd_houdini_plugins") and they load perfectly on Mac!

Hope other DCC vendors are taking notice with USD build processes for Maya etc. on OSX. It's all a bit targeted at devs not artists as it would be great to work in Pixar's beautiful new way of handling 3D scenes without all the current Python headaches.

**Comment by jbartolozzi** [comment]
> Indeed, Houdini 17 now has a toolkit folder with a much simplified USD plugin install process (see under "usd_houdini_plugins") and they load perfectly on Mac!
> 
> Hope other DCC vendors are taking notice with USD build processes for Maya etc. on OSX. It's all a bit targeted at devs not artists as it would be great to work in Pixar's beautiful new way of handling 3D scenes without all the current Python headaches.

This indeed works well, thanks @amotarzi

**Comment by sunyab** [comment]
Closing this out, since the Houdini plugin has been removed in favor of native USD support in Houdini Solaris. Thanks!
