### ISSUE TITLE
No module named pixar.UsdMaya / unable to export (macOS + MAYA plugin)

### ISSUE THREAD

**Issue by jselikof** [PixarAnimationStudios/USD#596]
### Description of Issue
pxrUsd and pxrUsdTranslators plugins have been built.  $MAYA_PLUG_IN_PATH and other required environment variables are configured.  pxrUsdTranslators loads without error. Loading pxrUsd produces the error: "No module named pixar.UsdMaya".  Additional errors are produced when attempting to export a selection:

> // Error: line 0: Cannot find procedure "usdTranslatorExport". // 
> // Error: Failed verification: ' fileFormat ' -- Coding Error in _CreateNew at line 415 of /Users/jselikof/Repos/USD/pxr/usd/lib/sdf/layer.cpp // 
> // Error: Failed to create stage file '/Users/jselikof/Downloads/oldSchool_v05_baked 2/oldSchoolDisc.usd' -- Runtime Error in _OpenFile at line 371 of /Users/jselikof/Repos/USD/third_party/maya/lib/usdMaya/writeJobContext.cpp // 
> // Error: line 0: Could not save file "/Users/jselikof/Downloads/oldSchool_v05_baked 2/oldSchoolDisc.usd". // 
> // Warning: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/startup/scriptEditorPanel.mel line 1845: Could not find the specified string. // 
> 

### Steps to Reproduce
1. Build using: "python build_scripts/build_usd.py --maya ~/USD"
2. Install pxrUsdTranslators and pxrUsd using Plug-in Manager
3. Export a selection as pxrUsdExport

### System Information (OS, Hardware)
macOS High Sierra version 10.13.6
MacBook Pro Retina 13-inch Mid 2014 
### Package Versions
master

### Build Flags
--maya

**Comment by jtran56** [comment]
Filed as internal issue #164200.

**Comment by pukeanddie** [comment]
I am having the exact same issue. Is there any solution?

**Comment by veekayr** [comment]
I am having same issue in maya 2018

**Comment by c64kernal** [comment]
Reopening the issue given the new reports.

**Comment by mattyjams** [comment]
Hi all,

Sorry for the pxr/pixar namespace confusion here. Change https://github.com/PixarAnimationStudios/USD/commit/02aeeea277a375968eed01acc68e31d0e24352f4 currently in the dev branch should be available in the next USD release and will help clear this up, leaving only the 'pxr' namespace.

Aside from that, if you're still seeing this issue, can you make sure that your PYTHONPATH environment variable (along with the other variables mentioned [here](https://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html)) is setup correctly for Maya? If you're able to build successfully, that's the only thing I can think of that might prevent the Python module from being found.

**Comment by michaelb-01** [comment]
I'm getting the same error. I cloned the repo last week so it should be up to date? My error is:

`# Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: ImportError: file <maya console> line 4: No module named pixar.UsdMaya # `

I have set the PYTHONPATH (and all other variables) in my env file, e.g:

```
USD_ROOT = C:/dev/USD/Build3
PYTHONPATH = %USD_ROOT%/lib/python;
```

I looked at the change that @mattyjams referenced but I don't have that file:

`third_party/maya/lib/usdMaya/AEpxrUsdReferenceAssemblyTemplate.py`

I did however find the file in this location:

`lib/python/pxr/UsdMaya/AEpxrUsdReferenceAssemblyTemplate.py`

but it is still using the try except to import, so does this mean my USD version is out of date? I'm guessing I can't simply update the import methods to match the method described in the change?

**Comment by mattyjams** [comment]
Hi @michaelb-01,

I don't have access to a Windows machine at the moment, so I can't give you exact information about building on Windows, but the issue sounds the same to me as the earlier reports on macOS.

The change I mentioned should go out with the next release of USD, but it is not in the master branch yet. If you wanted to, you could pull the dev branch of the repo to try it now, or you can definitely go ahead and make the same changes in your own local repo. Either way though, I think the best you'll then see is that you get the same error about "pxr.UsdMaya". The try/excepts were there to deal with a build system oddity internal to Pixar that we've now resolved.

The real issue still looks to be that Maya either can't find or can't import the pxr.UsdMaya module from your build. The first path you mentioned to `AEpxrUsdReferenceAssemblyTemplate.py` looks like its path in the code repo, while the second looks like its path in your build. At first glance, that second path looks correct to me. Do you know whether you're building USD against the same version of Python as Maya? Also, are you able to `import pxr` in the script editor? That might help narrow it down to an issue specific to the Maya plugin versus a larger issue with your USD build in general.

**Comment by mattyjams** [comment]
Commit https://github.com/PixarAnimationStudios/USD/commit/02aeeea277a375968eed01acc68e31d0e24352f4 is now in master and part of the latest USD release, so all `from pixar import UsdMaya` imports should be gone.

If instead you now see complaints about "No module named pxr.UsdMaya", I think that would still suggest either an issue with the build, or an issue with the Maya and/or Python environment setup.

**Comment by mathurdeepak13** [comment]
> Commit [02aeeea](https://github.com/PixarAnimationStudios/USD/commit/02aeeea277a375968eed01acc68e31d0e24352f4) is now in master and part of the latest USD release, so all `from pixar import UsdMaya` imports should be gone.
> 
> If instead you now see complaints about "No module named pxr.UsdMaya", I think that would still suggest either an issue with the build, or an issue with the Maya and/or Python environment setup.

hi Matt,

I'm still having an issue unable to `import pxr` in the script editor.
My python maya version is set to:
2.7.11 (default, Jul  1 2016, 02:08:48) [MSC v.1900 64 bit (AMD64)]
and installed python is set to:
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32

I did try changing %PATH% and pointing to "C:\Program Files\Autodesk\Maya2018\Python\Scripts" but without any luck.

**Comment by mattyjams** [comment]
@mathurdeepak13 I unfortunately don't have access to a Windows machine at the moment, so I can't give you detailed info about building for Windows, but if you're not able to `import pxr`, then that suggests that Maya can't find your USD installation at all, let alone the Maya plugin.

Can you double-check that you've defined all of the necessary [environment variables](https://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html), and in particular, make sure that `PYTHONPATH` looks correct? For Windows, you'll need to define *all* of the variables listed on that page, not just `PATH`.

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
