### ISSUE TITLE
RfM Material import fails with "Unsupported type 'asset' for texture file paths

### ISSUE THREAD

**Issue by simpassi** [PixarAnimationStudios/USD#598]
### Description of Issue
When using the pxrUsd Maya plug-in pxrUsdImport / pxrUsdExport functionality, any texture map nodes lose their file paths during import, with the following error:

// Error: Unsupported type 'asset' for USD attribute '/pCube1/Looks/PxrSurface1SG/texture_node_name.inputs:fileTextureName' -- Coding Error in setPlugValue at line 1532 of /Users/svirokan/extsrc/USD/third_party/maya/lib/usdMaya/util.cpp // 

..and the resulting node graph has no file names. This happens with Maya file nodes and pxrTexture nodes alike. I can see the full file paths in the resulting .usd file though.

### Steps to Reproduce
1. Create a scene with an object, attach a pxrSurface shader and plug a texture node (file or pxrTexture or you name it) into a color channel
1. Export a USD file with the pxrUsdExport exporter in Maya - select "RfM Materials"
1. Open a new scene and import the created USD file with "RfM Materials" selected
1. The material network is created but none of the textures have file paths

### System Information (OS, Hardware)
Any Mac

### Package Versions
* MacOS 10.x
* Maya 2018.2
* USD 18.09

### Build Flags
Using the [improved build_usd.py](https://groups.google.com/d/msg/usd-interest/2PwKbYARZmg/FjGmEH4eAQAJ) (with --use-maya-python)

**Comment by simpassi** [comment]
This is a partial fix (does not handle asset path arrays) that got it going for me:

```diff
diff --git a/third_party/maya/lib/usdMaya/util.cpp b/third_party/maya/lib/usdMaya/util.cpp
index 90fcb449..b8e4bbc8 100644
--- a/third_party/maya/lib/usdMaya/util.cpp
+++ b/third_party/maya/lib/usdMaya/util.cpp
@@ -37,6 +37,7 @@
 #include "pxr/base/vt/types.h"
 #include "pxr/base/vt/value.h"
 #include "pxr/usd/usdGeom/mesh.h"
+#include "pxr/usd/sdf/schema.h"
 
 #include <maya/MAnimControl.h>
 #include <maya/MAnimUtil.h>
@@ -1237,6 +1238,9 @@ UsdMayaUtil::setPlugValue(
     else if (val.IsHolding<std::string>()) {
         status = attrPlug.setString(val.UncheckedGet<std::string>().c_str());
     }
+    else if (val.IsHolding<SdfAssetPath>()) {
+        status = attrPlug.setString(val.UncheckedGet<SdfAssetPath>().GetResolvedPath().c_str());
+    }
     else if (val.IsHolding<TfToken>()) {
         const TfToken token(val.UncheckedGet<TfToken>());
         const MObject attrObj = attrPlug.attribute(&status);
```

**Comment by jtran56** [comment]
Filed as internal issue #USD-4696.
