### ISSUE TITLE
Payload not loaded when parent prim is activated

### ISSUE THREAD

**Issue by mgland** [PixarAnimationStudios/USD#604]
### Description of Issue
Hi there,
When a deactivated prim-A got a payload, whose child prim B also got one, then activating the prim-A won't load the child B's payload, despite the fact that the stage is loaded with LoadAll flag. 
The payload of prim-A is loaded through.

This will cause the fact that when LayerDidChange event is emitted, the payload of child prim B is not loaded yet, thus the data will be missed during the event handling.

I saw a related issue: https://github.com/PixarAnimationStudios/USD/issues/156
Cheers,
Miguel Gao

### Steps to Reproduce
1. Create a usda file called bootstrap.usda:
```
#usda 1.0
(
    defaultPrim = "shot"
)

def Xform "shot" (
)
{
    def Xform "camera" (
    )
    {
        def Xform "cache"(
            active = false
            payload = @cache_payload.usda@
        ){
            def "cam"(
                payload = @camera_cache.usda@
            ){
            }
        }
    }
}
```
2. Create a file called cache_payload.usda:
```
#usda 1.0
(
    defaultPrim = "cam_extra"
)

def "cam_extra" (
)
{
    // Some heavy data goes here...
    def "cache_payload"(){}
}
```

3. Create a file called camera_cache.usda:
```
#usda 1.0
(
    defaultPrim = "cam"
)

def Xform "cam" (
)
{
    // Some heavy data goes here...
    def "cam_payload"(){}
}
```

4. Put all three files within same folder, run python code to test:
```
from pxr import Usd
stage = Usd.Stage.Open('/path/to/bootstrap.usda', Usd.Stage.LoadAll)
stage.SetEditTarget(stage.GetSessionLayer())
cachePrim = stage.GetPrimAtPath('/shot/camera/cache')
cachePrim.SetActive(True)
cachePayloadPrim = stage.GetPrimAtPath('/shot/camera/cache/cache_payload')
print 'The payload for cache is loaded: %s' % cachePayloadPrim.IsValid()
cameraPayloadPrim = stage.GetPrimAtPath('/shot/camera/cache/cam/cam_payload')
print 'The payload for cam is loaded: %s' % cameraPayloadPrim.IsValid()  # This is the problem
cachePrim.Load()
cameraPayloadPrim = stage.GetPrimAtPath('/shot/camera/cache/cam/cam_payload')
print 'The payload for cam is loaded after manually calling Load(): %s' % cameraPayloadPrim.IsValid()

```
### System Information (OS, Hardware)
Linux, CentOS 7

### Package Versions
0.8.5

**Comment by spiffmon** [comment]
I can reproduce - thanks for reporting this, Miguel - we'll get on it!

--spiff

**Comment by jtran56** [comment]
Filed as internal issue #USD-4712.
