### ISSUE TITLE
UsdPrim has no GetPayload() method

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#608]
### Description of Issue
There is UsdPrim::HasPayload and UsdPrim::SetPayload, but no UsdPrim::GetPayload.

See this thread:
https://groups.google.com/d/msg/usd-interest/s4AM0v60uBI/DX7aQGqQCAAJ

/CC @spitzak

**Comment by sunyab** [comment]
Closing out old issue. UsdPrim::GetPayloads has been available since v19.03.
