### ISSUE TITLE
MaterialX plugin wont compile on windows

### ISSUE THREAD

**Issue by jamesmclaren** [PixarAnimationStudios/USD#611]
### Description of Issue
When compiling with MaterialX plugin on windows, the compilation of USD fails with missing (MATERIALX_LIB_DIRS)
### Steps to Reproduce
1. compile the app with the following options

python  %ROOT_DIR%\build_scripts\build_usd.py ^
	--generator "Visual Studio 14 2015 Win64" ^
	--materialx

### System Information (OS, Hardware)
windows 10 64bit
### Package Versions
1809
### Build Flags

This is due to FindMaterialX.cmake looking for libMaterialXCore.a instead of MaterialXCore.lib

I changed this, now getting another bug _usdMtlx project can't find usdMtlx.lib in the usdMtlx\Release folder.

Not sure how to fix this one as usdMtlx project seems to be defining all the methods in api.h correctly with export statements.

Have also tested this with visual studio 2017 win64

**Comment by c64kernal** [comment]
Thanks @jamesmclaren -- I put up a branch that compiles here: https://github.com/c64kernal/USD/tree/dev_matxwin, we'll look into getting it merged soon.  Hope that helps!

**Comment by jtran56** [comment]
Filed as internal issue #USD-4723.

**Comment by jamesmclaren** [comment]
Excellent, that worked well, glad it was a simple fix, I get on with testing it.
Any news on what is happening with the Houndini win32 plugin? I had a go at fixing it a couple of releases ago, but it was a bit beyond me.

**Comment by c64kernal** [comment]
Great, glad that worked for you.  

As for the Windows Houdini plugin, the only effort I'm currently aware of is the one happening on this thread: https://groups.google.com/forum/#!topic/usd-interest/23XmMOONKdI
