### ISSUE TITLE
build_usd.py can not find VS C++ compiler on non english systems

### ISSUE THREAD

**Issue by ephb** [PixarAnimationStudios/USD#613]
### Description of Issue

Line 99 ind build_usd.py uses the string to determine wether the c++ compiler is installed.
 "Compiler Version (\d+).(\d+).(\d+)", 
This is string however seems to be localized. And since I installed Visual Studio in English I assume this is taken from the system locale.
'cl'  on my system returns 'Optimierungscompiler Version 19.15.26726 für x86'.

So in my case simply changing one letter in the search string is sufficient but I imagine this will also affect other languages this why I opened this issue instead of providing a pull request with two different strings.

I think there must be a better way than to simply list all possible names of the copmpiler.

### Steps to Reproduce
1. Run build_usd.py on a Windows 10 Machine where the system locale is set to something other than English it will report "C++ compiler not found -- please install a compiler".

### System Information (OS, Hardware)
Windows 10 1803. Hardware seems to be irrelevant here.
### Package Versions
18.09 
### Build Flags
none

**Comment by jtran56** [comment]
Filed as internal issue #USD-4727.

**Comment by sunyab** [comment]
Hi @ephb, thanks for the report! This might be as simple as modifying the regex to look for just the version number. We may also want to look for the "x64" string, since users should be using the x64 developer command prompt / compiler for building USD.

**Comment by Trafle** [comment]
@ephb, So how do u fix this? That would help me

**Comment by sunyab** [comment]
@Trafle This issue was fixed in 2019. If you're still running into problems please file a new issue with more details. Thank you!

**Comment by Trafle** [comment]
@sunyab gocha. Thank u
