### ISSUE TITLE
Incorrect Pick ID Calculated in OpenGL RefEngine

### ISSUE THREAD

**Issue by nathanquirl** [PixarAnimationStudios/USD#616]
### Description of Issue
On macOS when using the OpenGL engine in Hydra, the TestIntersection method does not return a path to a picked object. When running the usdview example app, on macOS, picking does not appear to be working.

Hydra appears to be using the fallback RefEngine implementation on macOS due to it's older OpenGL implementation. When unpacking a pick ID from a buffer color, one component is set to 1 which appears to be causing the wrong integer value to be calculated. When this incorrect value is passed to the path mapping method, it is unable to find a valid shape path.

Recommended changes:

Change primIdColor[3] = 1; 

to 

primIdColor[3] = ((float)((primId & 0xff000000) >> 24)) / 255.0f;

In this method in RefEngine.h:

static GfVec4f Unpack(ValueType primId) {
            GfVec4f primIdColor;                                                     
            // Convert the instance Id into an rbg color. We could potentially
            // use alpha if we want to extend the range.
            primIdColor[0] = ((float)((primId & 0x000000ff) >>  0)) / 255.0f;
            primIdColor[1] = ((float)((primId & 0x0000ff00) >>  8)) / 255.0f;
            primIdColor[2] = ((float)((primId & 0x00ff0000) >> 16)) / 255.0f;
            primIdColor[3] = 1;

            return primIdColor;
        }

Also update relevant Pack method.

Change occurrences of:

glColorPointer(3, GL_FLOAT, 0, (GLvoid*)offset); to glColorPointer(4, GL_FLOAT, 0, (GLvoid*)offset);

to:

glColorPointer(4, GL_FLOAT, 0, (GLvoid*)offset); to glColorPointer(4, GL_FLOAT, 0, (GLvoid*)offset);

in RefEngine.cpp

I ran a test with these changes and it appeared to fix the issue. I can submit a pull request with this fix if no one else is working on it.

### Steps to Reproduce
1. Run usdview on macOS
2: Observe picking behavior 

### System Information (OS, Hardware)
macOS High Sierra (10.13.6)
Macbook Pro (15-inch, 2017)
2.9 Ghz Intel Core i7, 16GB
Radeon Pro 560 

### Package Versions
Python 2.7

### Build Flags
Python enabled
OpenGL enabled
Imaging enabled

**Comment by jtran56** [comment]
Filed as internal issue #USD-4734.

**Comment by c64kernal** [comment]
Thanks @nathanquirl -- I'm pretty sure no one is working on this, so please do submit the PR if you'd like.  Long term, we're hoping to deprecate the ref engine (because it is anything but "ref" at this point :)).  Thanks again!

**Comment by sunyab** [comment]
Closing old issue. The ref engine was removed in fc24f3ff4ed which is currently in dev and will be part of the next USD release.
