### ISSUE TITLE
UsdImaging doesn't trigger updates when a material network changes

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#617]
### Description of Issue
Updating the definition of a material assigned to a mesh by changing the connections between the material's UsdShade nodes does not cause the viewport representation of the material to update. In the attached example, a texture node connection is replaced with a primvar reader (which requires reading an additional primvar from the mesh).

### Steps to Reproduce
1. Use usdview to open the attached bricks.usda. It contains a grid with a preview surface material assigned, using a brick wall texture (bricks.png).
2. In the Interpreter window, "import bricks" to load bricks.py.
3. Run "bricks.changemat(usdviewApi)". This will change the material definition to eliminate the use of the texture map, and instead feed the diffuseColor with a primvar on the grid called "foo".
4. Notice that the viewport doesn't update with the changed material.
5. Switch the renderer to embree, than back to GL to see the proper modified material.

[bricks.zip](https://github.com/PixarAnimationStudios/USD/files/2376657/bricks.zip)

**Comment by jtran56** [comment]
Filed as internal issue #USD-4735.
