### ISSUE TITLE
Maya usdExport sometimes exports a static mesh

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#633]
### Description of Issue

We were getting an issue where when animators would do usd exports on their local computer, the mesh was coming out static.  After a lot of investigation, it seems that the root cause is a maya bug in 2018, that makes the mesh vertex attributes not update properly when GPU graph evaluation is enabled.  However, there's a relatively simple fix - if you explicitly mark all plugs connected to time1.outTime as dirty (and all animCurve nodes), then the mesh vertices will be properly updated.

However, I haven't bothered making a PR for it, because I confirmed the issue is fixed in maya-2019... and we're going to just tell our animators to always export on the farm until we make that switch.  I am including a reproduction scene / script.

### Steps to Reproduce

[test_gpu_deform_no_vert_change.zip](https://github.com/PixarAnimationStudios/USD/files/2403135/test_gpu_deform_no_vert_change.zip)

1. Download and extract the attached zip
2. Edit `test_gpu_deform_no_vert_change.py` so that `filepath` holds the path to your extracted `squash_sphere.ma`
3. Launch a maya-2018 GUI session
4. Set the evaluation mode (in the maya animation settings) to "Parallel", and make sure the GPU checkbox is turned on.
5. Run the downloaded `test_gpu_deform_no_vert_change.py`
6. It should say that it failed, because it didn't detect any change in the vert positions (even though you can see the mesh animating in the viewport)
7. To test a potential fix, edit `test_gpu_deform_no_vert_change.py`, and uncomment the lines that force dirtying of the time1.outTime connections, and any animCurve nodes.
8. Run again, and confirm that the test passes.

### System Information (OS, Hardware)

Maya-2018
Linux (CentOS 7)
Nvidia card

### Package Versions
usd-0.18.11 (develop branch)

**Comment by jtran56** [comment]
Filed as internal issue #USD-4776.

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD. From the description it also seems like this was a Maya bug that was fixed in Maya-2019.
