### ISSUE TITLE
JavaScript plugin for reading and viewing USD files for browsers

### ISSUE THREAD

**Issue by M94antony** [PixarAnimationStudios/USD#634]
Enhancement 
### Description of Proposal
Hi I was wondering if there are plans to make a USD Reader or viewer Javascript plugin. So clients can view their  USD Scene via browsers.

### System Information (OS, Hardware)
All

**Comment by c64kernal** [comment]
Hi @M94antony -- we don't have any plans on developing that internally currently.  For web technology, we're hoping the work we did with Apple on usdz will open more doors for being able to see your usd files on the web.
