### ISSUE TITLE
Problems editing existing files using maya plugins.

### ISSUE THREAD

**Issue by ChrisKAtTippett** [PixarAnimationStudios/USD#636]
### Steps to Reproduce

I have a USD file that has several sublayers. In my example the top level usd file represents a shot. The sublayer is initially empty, my task is to add a camera to that layer. Other sublayers contain the set.

Open an empty maya scene. Import the shot usd using the File->Import menu item and set the filetype to pxrUsd. Create the camera object and a compose a nice shot. Select the camera's transform node and usd File->Export Selection and set the file type to pxrUsdExport.

You will get an error like this:

// Creating stage file '/nethome/chrisk/crz_usd/shot_structure/tst_001_camera.usda'
// Error: A layer already exists with identifier '/nethome/chrisk/crz_usd/shot_structure/tst_001_camera.usda' -- Coding Error in _CreateNew at line 439 of /tip/rnd/3rdparty/managed/usd/18.09/USD-18.09/pxr/usd/lib/sdf/layer.cpp // 
// Error: Failed to create stage file '/nethome/chrisk/crz_usd/shot_structure/tst_001_camera.usda' -- Runtime Error in _OpenFile at line 371 of /tip/rnd/3rdparty/managed/usd/18.09/USD-18.09/third_party/maya/lib/usdMaya/writeJobContext.cpp // 
// Error: line 0: Could not save file "/nethome/chrisk/crz_usd/shot_structure/tst_001_camera.usda". //

This is a well know problem in USD circles. In the Houdini plugins, we always write to a temp file and then move the temp file to the target filename. The Maya plugins need to do something similar.

Thanks,
Chris

**Comment by jtran56** [comment]
Filed as internal issue #USD-4784.
