### ISSUE TITLE
USD compilation crash with error: ‘std::function’ has not been declared

### ISSUE THREAD

**Issue by col-one** [PixarAnimationStudios/USD#637]
crash during compilation with script:
`python USD/build_scripts/build_usd.py /usr/local/USD`
raise error : 
`error: ‘std::function’ has not been declared` in file USD/pxr/imaging/lib/hd/renderThread.h

### Steps to Reproduce
1. run `python USD/build_scripts/build_usd.py /usr/local/USD`

### System Information (OS, Hardware)
Linux Kubuntu17

### Package Versions
Last.

### Build Flags
Default. 

### Issue resolved
by add `#include <functional>` to the file. 

Thanks.

**Comment by sunyab** [comment]
Hi @col-one, this issue was addressed in #595 -- the fix is already in the dev branch and will be included in the next release. Closing this out, thanks!
