### ISSUE TITLE
Windows Quath copy constructors are not properly decorated

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#64]
### System Information (OS, Hardware, etc.)

Windows
### Steps to Reproduce
1.  Make another library that uses Quath from gf.dll
2. Try to compile

Error should be something like:

Error   LNK2019 unresolved external symbol "public: __cdecl GfQuath::GfQuath(class GfQuatd const &)" (??0GfQuath@@QEAA@AEBVGfQuatd@@@Z) referenced in function CSharp_pxr_new_GfQuath__SWIG_4   UsdCs   C:\src\usd\UsdBindings\vs2015\UsdCs\usdCs_wrap.obj

It just needs GF_API before the constructors, however this generated more questions: 

Seems like this should be part of the Jinja template, but isn't currently?

It also seems like many functions are not prefixed with the declspec/GF_API -- is that intentional?

**Comment by JamieKenyonFoundry** [comment]
Hi Jeremy,

There maybe a few cases were we've missed __declspec( dllexport ) from classes and functions.

It makes sense to me to add it to the Ninja template too.

**Comment by jcowles** [comment]
Cool, I can do that

**Comment by ZeroCrunch** [comment]
The GF_API part?

**Comment by jtran56** [comment]
Filed as internal issue #137856.

**Comment by jcowles** [comment]
I can add GF_API to the jinja templates, test it, and send a pull request -- if you want.

**Comment by JamieKenyonFoundry** [comment]
No objections from me!!

**Comment by sunyab** [comment]
This should have been addressed with commit 56bfe99, which is included in release 0.7.4. Closing this out.
