### ISSUE TITLE
[Houdini] USD Import with Custom Traversal on Visibility seems wrong

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#649]
When using the USD Import SOP in Houdini, with the Traversal set to Custom, and using the "Visibility" based traversal, the results seem wrong. If the hierarchy is like this:
```
/foo
  /bar            invisible
    /spangle      inherited
```
and the traversal by prim type or kind causes /foo/bar/spangle to be imported, it gets imported whether the "Visibility" test is "True" or "False". I would expect it to be treated as if it were invisible.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4820.
