### ISSUE TITLE
Bug returning the same string for any index [Houdini]

### ISSUE THREAD

**Issue by sriravic** [PixarAnimationStudios/USD#653]
There's a bug in this access routine, where the same string at index '0' is returned for any offset passed as parameter.
It should be 

`return _data[o]` instead of `return _data[0]`

https://github.com/PixarAnimationStudios/USD/blob/6c50b29bb76f0a7c176bae05668ab195520a019b/third_party/houdini/lib/gusd/GT_VtStringArray.h#L64

**Comment by marktucker** [comment]
I could submit a pull request to fix this, but I suspect it will be easier for someone there to just apply the fix described here?

**Comment by jtran56** [comment]
Filed as internal issue USD-4824.
