### ISSUE TITLE
Connections to public interface inputs for "interfaceOnly" inputs not consistently handled by imaging/Stream  

### ISSUE THREAD

**Issue by spiffmon** [PixarAnimationStudios/USD#654]
### Description of Issue
See [this simple texture mapping example](https://groups.google.com/d/msg/usd-interest/objs_kJh6hc/AxXPbLPxBQAJ) with a zipped repro - you want to look at the "with_material.usda" file.

The UsdUVReader's _file_ input is connected to its containing Material's _diffuse_file_ input, similarly to how the _varname_ input is connected to the containing Material's _frame:stPrimvarName_ input.  Both _file_ and _varname_ are defined as "interfaceOnly" inputs.  However, while _varname_'s connection is correctly processed, _file_'s is assumed to be a shader-to-shader connection, which results in errors because the Material prim to which it is connected is not a shader.

I'm hoping this is due to the special-case network processing that the gl/stream code does, but we should test this with hdPrman as well.

### Steps to Reproduce
1. usdview with_material.usda

**Comment by jtran56** [comment]
Filed as internal issue #USD-4825.
