### ISSUE TITLE
UsdMaya does not export visibility if connected 

### ISSUE THREAD

**Issue by bfloch** [PixarAnimationStudios/USD#656]
### Description of Issue
When exporting a transform that has the visibility channel connected to a __non-animated__ attribute, it will fail to write the visibility if Animation is not exported. 

### Steps to Reproduce

Skip step 1-3 and load the .ma in [visibility.zip](https://github.com/PixarAnimationStudios/USD/files/2474708/visibility.zip)

1. Have a geometry and a control with a custom bool attribute.
2. Connect the visibility of the transform to the controls attribute.
3. Set the attribute on the control to off, which drives the visibility of the geo to off.
4. Select the geo transform
5. Export selected
6. Set Export Visibility on, Animation off.  

Visibility is not being written.
It is expected to write visibility as invisible since the driving connection is not animated itself and the value at the defaultTime should apply.

### Cause and Fix

Maya's API does not provide a very good way to tell if an object or plug is animated.
Fortunately you provide better check in util.h via isPlugAnimated.

For some reason this function is not being used in getPlugValue:
https://github.com/PixarAnimationStudios/USD/blob/master/third_party/maya/lib/usdMaya/util.h#L355

Any connection is treated as isAnimated.
This fixes the issue on the line in question:
```C++
*isAnimated = isPlugAnimated(plg);
```

### System Information (OS, Hardware)

Centos7 x64, Maya 2018 Update 4

### Package Versions

usd 18.09

### Build Flags
Nothing relevant

**Comment by jtran56** [comment]
Filed as internal issue #USD-4827.
