### ISSUE TITLE
Narrowing cast issues in Gf headers

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#659]
### Description of Issue
Several double literals in lib Gf are being down cast to float -- strict compiler options cause this to be an error.

Here is an example:
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/base/lib/gf/vec3h.h#L279

**Comment by jtran56** [comment]
Filed as internal issue #USD-4832.

**Comment by sunyab** [comment]
I believe this was fixed by #2060 in the 23.02 release. Closing this out.
