### ISSUE TITLE
NdrParserPlugin::DiscoveryTypes and ::SourceType missing NDR_API

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#660]
### Description of Issue

I believe the API declaration is missing for these public static members:
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/ndr/parserPlugin.h#L140

**Comment by jtran56** [comment]
Field as internal issue #USD-4833.

**Comment by sunyab** [comment]
Thanks @jcowles, these members were removed in commit 1ddacf0b. Marking as pending release.

**Comment by sunyab** [comment]
This fix was released in version 19.01, closing!
