### ISSUE TITLE
Alembic 1.7.9 support

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/USD#667]
### Description of Issue
The Alembic API changed a bit from 1.7.7 to 1.7.9:

https://github.com/alembic/alembic/blob/1.7.7/lib/Alembic/AbcCoreOgawa/ReadWrite.h#L72
`ReadArchive( size_t iNumStreams );`

https://github.com/alembic/alembic/blob/1.7.9/lib/Alembic/AbcCoreOgawa/ReadWrite.h#L73
`ReadArchive( size_t iNumStreams, bool iUseMMap );`

So the AlembicReader would need to be updated to support both versions: https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/plugin/usdAbc/alembicReader.cpp#L1377

### Steps to Reproduce
1. Try to build USD 18.11 with Alembic 1.7.9

### Package Versions
Tested in 18.09 and 18.11 but the same for older versions too.

### Build Flags
`-DPXR_BUILD_ALEMBIC_PLUGIN=ON`

**Comment by jtran56** [comment]
Filed as internal issue #USD-4850.

**Comment by elrond79** [comment]
I assume now that #825 is merged, this should be closed?

(One caveat - we might want to update the BUILDING.md to note that Alembic-1.7.9 is supported. Or at least make it say 1.5.2+?)

**Comment by c64kernal** [comment]
Thanks @elrond79  -- yeah, good call on closing this one out, and good call on updating the BUILDING.md docs as well.  We were taking a pass through recently and of course a lot of stuff is out of date, so we'll have to take a more concerted look at how we represent these version numbers.  One caveat also is that while we're supporting 1.7.9 after this merge, we only test against 1.5.2 so far.  This is the same problem with the gcc 6+ support that we have too.  We'll need to find the right way to word that properly in the docs.

Thanks again!
