### ISSUE TITLE
UsdCollectionAPI::IsCollectionPath is declared but not defined

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#669]
### Description of Issue
Here is a search of the repository for the "IsCollectionPath":

https://github.com/PixarAnimationStudios/USD/search?q=IsCollectionPath&unscoped_q=IsCollectionPath

**Comment by c64kernal** [comment]
Thanks @jcowles -- this was an oversight from another API update.  That method should be removed.  We'll take care of it in the next round of updates.
