### ISSUE TITLE
Build USD Script Running Issues in Mac Mojave

### ISSUE THREAD

**Issue by AnanlaTech** [PixarAnimationStudios/USD#671]
### Description of Issue
Running the script causes -
python USD/build_scripts/build_usd.py /opt/local/USD

Building with settings:
  USD source directory          /Users/**/Desktop/USD
  USD install directory         /opt/local/USD
  3rd-party source directory    /opt/local/USD/src
  3rd-party install directory   /opt/local/USD
  Build directory               /opt/local/USD/build
  CMake generator               Default
  Downloader                    curl

  Building                      Shared libraries
    Imaging                     On
      Ptex support:             Off
      OpenImageIO support:      Off 
    UsdImaging                  On
      usdview:                  On
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    MaterialX Plugin            Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off

  Dependencies                  zlib, boost, TBB, OpenEXR, GLEW, OpenSubdiv, PyOpenGL, PySide
PyOpenGL is not installed. If you have pip installed, run "pip install PyOpenGL" to install it, then re-run this script.
If PyOpenGL is already installed, you may need to update your PYTHONPATH to indicate where it is located.
PySide is not installed. If you have pip installed, follow the instructions at https://wiki.qt.io/Qt_for_Python/GettingStarted to install PySide2 from published wheels, then re-run this script.
If PySide is already installed, you may need to update your PYTHONPATH to indicate where it is located.
### Steps to Reproduce
1. I have installed PySide2 and PyOpenGL.

### System Information (OS, Hardware)
Mac OS Mojave

**Comment by usmanredsoft** [comment]
Hi please hope me same issue we are getting on Mac Mojave : 

PyOpenGL is not installed. If you have pip installed, run "pip install PyOpenGL" to install it, then re-run this script.
If PyOpenGL is already installed, you may need to update your PYTHONPATH to indicate where it is located.
PySide is not installed. If you have pip installed, follow the instructions at https://wiki.qt.io/Qt_for_Python/GettingStarted to install PySide2 from published wheels, then re-run this script.
If PySide is already installed, you may need to update your PYTHONPATH to indicate where it is located.

**Comment by meshula** [comment]
If you have macports or brew, pip will install PyOpenGL into those copies of python. If that is the reason for the problem, then if you type

```sh
python -m pip install PyOpenGL
```

it should succeed. Similarly, when installing PySide2, instead of using the exact command line they specify, use python -m instead.

```sh
python -m pip install --index-url=https://download.qt.io/official_releases/QtForPython/ pyside2 --trusted-host download.qt.io
```

This worked for me.

**Comment by sunyab** [comment]
Closing old issue out. 

Note that PyOpenGL and PySide/PySide2 must be accessible from the python interpreter being used to run build_usd.py. If `python -c import OpenGL` or `python -c import PySide` (or PySide2) fail then the modules haven't been installed in the proper location or the PYTHONPATH env variable needs to be updated to point to where they have been installed.

**Comment by tungtanium** [comment]
Hi @sunyab ,

I have `PyOpenGL` & `PySide2` installed. I can execute the following from the terminal

```bash
python -c "import OpenGL"
python -c "import PySide2"
```
But when running the build script I still have error:

```bash
PyOpenGL is not installed. If you have pip installed, run "pip install PyOpenGL" to install it, then re-run this script.
If PyOpenGL is already installed, you may need to update your PYTHONPATH to indicate where it is located.
PySide2 is not installed. If you have pip installed, run "pip install PySide2" to install it, then re-run this script.
If PySide2 is already installed, you may need to update your PYTHONPATH to indicate where it is located.
```
I even create an env `$PYTHONPATH` set it to `/home/$USER/.local/lib/python2.7`. Hope you can shed some light on this for me.

Thank you!

**Comment by hlin-neo4j** [comment]
Getting same issue as @tungtanium

**Comment by tungtanium** [comment]
Hey @hlin-neo4j ,

I managed to get around the issue by installing `PyOpenGL` & `Pyside2` with `sudo pip`. I am still not sure why the `.local/lib` has already been in the `$PYTHONPATH` but the build script doesnt find it.

Cheers,
