### ISSUE TITLE
[Houdini] Running ginfo on a USD file crashes

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#673]
### Description of Issue

Running Houdini's "ginfo" utility on a USD file uses the GEO_IOTranslator from the gusd library. This calls
some global Houdini "CH" library function which rely on the existence of a "CH_Manager" object. But
ginfo (unlike houdini or hython) does not create a CH_Manager, so calling these functions leads to a
crash.

### Steps to Reproduce

1. Make sure USD is built and installed with Houdini support.
2. Run "ginfo foo.usd" on any USD file from a shell that has access to Houdini. This will crash.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4860.

**Comment by sunyab** [comment]
This fix was released in version 19.01. Closing!
