### ISSUE TITLE
Internal references to primitives inside variants not working properly

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#677]
### Description of Issue

Two related issues here. In the attached zip archive [variantrefs.zip](https://github.com/PixarAnimationStudios/USD/files/2523661/variantrefs.zip) is a variant_oddity1.usda file which contains a prim with a variant set, with only one variant choice. The variant contains a cube prim, and them three other prims. One references, one inherits, and one specializes the first cube prim.
When I load this file into usdview I get the following error:

Warning: in _ReportErrors at line 2780 of f:\dev_tools\src\usd\usd-18.11\usd\pxr\usd\lib\usd\stage.cpp -- Cycle detected:
@variant_oddity_1.usda@,@anon:000000004E023880:variant_oddity_1-session.usda@</objects/geos/cube_1>
uses variant:
@variant_oddity_1.usda@,@anon:000000004E023880:variant_oddity_1-session.usda@</objects{model=duplicate3}geos/cube_1>
which references:
@variant_oddity_1.usda@,@anon:000000004E023880:variant_oddity_1-session.usda@</objects>
which CANNOT use variant:
@variant_oddity_1.usda@,@anon:000000004E023880:variant_oddity_1-session.usda@</objects{model=duplicate3}>
 (instantiating stage on stage @variant_oddity_1.usda@ <000000004E048700>)

And in usdview, the "references" cube doesn't show up. But the inherits and specializes cubes are perfectly happy. This seems to be a bug in handling of the Reference arc.

In attempting to work around this issue, I created the variant_oddity2.usda file, which is exactly the same, except the Reference, Inherit, and Specialize prim paths all specify the variant in the path, and all three arcs seem to work properly in this case. But Spiff indicated in a usd-interest discussion (https://groups.google.com/d/topic/usd-interest/dH43TRIEgLs/discussion) that in fact none of these should work (which is why variant specifications are stripped in the SdfCopySpec implementation).

**Comment by jtran56** [comment]
Filed as internal issue #USD-4878.
