### ISSUE TITLE
UsdMaya UV Editor breaks selection drawing

### ISSUE THREAD

**Issue by bfloch** [PixarAnimationStudios/USD#678]
### Description of Issue

When PxrReferenceAssemblies are present in hydra rendering, opening the maya UV Editor window will cause the rendering to not show selection in Usd 18.11.
In 18.09 it would even hide the drawing.

Not sure if this is a problem with Usd or Maya 

### Steps to Reproduce
1. Open a .usd in a PxrReferenceAssemly
2. Set it to playback or expanded
3. Select a prim
4. Open Windows -> Modeling Editors -> UV Editor

The selection disappeared and will not work anymore.

5. Close the uv editor

Back to normal.

### System Information (OS, Hardware)
Centos7 x64, Maya 2018 Update 4

### Package Versions

Usd 18.11

### Build Flags

Nothing relevant

**Comment by jtran56** [comment]
Filed as internal issue #USD-4879.

**Comment by c64kernal** [comment]
The Maya plugin is no longer being maintained in this repo and we don't believe this is a problem in the new VP2.0 plugin that is hosted on the Autodesk repo. Hope that works better for you!
