### ISSUE TITLE
Req: Expose default asset resolver in API so a custom resolver can defer to it's implementation

### ISSUE THREAD

**Issue by j-stroud** [PixarAnimationStudios/USD#68]
If one is writing a custom asset resolver and needs similar filesystem behaviour to that provided by the default asset resolver then the Ar_DefaultResolver code needs to be duplicated in the custom implementation.

If the Ar_DefaultResolver class could be exposed as part of the public API then a custom resolver could  either derive from or contain an internal instance of this class and defer to it's implementation.

Alternately, if there was API to get the previous 'current' or default asset resolver such that it could be called in the constructor of a custom resolver. e.g. ArGetDefaultResolver().

**Comment by jtran56** [comment]
Filed as internal issue #138123.
