### ISSUE TITLE
How to build USD with hydra_houdini_plugin using Embree backend?

### ISSUE THREAD

**Issue by juxi500** [PixarAnimationStudios/USD#681]
### Description of Issue
Hello, for some time I was reading about USD and Hydra and it seems pretty exciting.
Few days ago I discovered that [Walter](https://github.com/rodeofx/OpenWalter) can also use [Embree](https://www.youtube.com/watch?v=puy2bm-VAtQ) as a rendering backend for Hydra. If I understand correctly, according to [this](https://github.com/PixarAnimationStudios/USD/blob/e9e8e08ccd3215144bd13afbfcaf861d64500b5f/third_party/houdini/plugin/Hydra/README.md) when I load USD geometry inside Houdini, it is not being rendered by native Houdini viewport, but by Hydra. But is it also possible to [tell](https://www.youtube.com/watch?v=F8UK_RcOJ2M) Hydra which backend should it use for rendering inside Houdini? Is it possible to build USD in a way that we could render USD geometry inside Houdini viewport with Embree? If yes please could you shed some light how to do this? Thank you very much and have a nice day :)

### System Information (OS, Hardware)
EL7.5, x86 64bit

### Package Versions
Latest

**Comment by spitzak** [comment]
The current version of USD in Houdini does not use Hydra to draw things.
The following proposed patch adds this:

https://github.com/PixarAnimationStudios/USD/pull/600

This interacts with Hydra at a pretty high level and it is unclear if other
backends would work at all. It also has to revert to drawing geometry using
Houdini equivalents for hit detection and selection indication and multiple
instances of the same prim, all of these require changes to Hydra or
Houdini or both to fix. It's main advantage is that animated USD and
extremely large scenes play back at practical speeds so you don't have to
freeze the frame number in the import.

**Comment by juxi500** [comment]
Please, do you have any experience, how much more effective could be Hydra (using "default backend") when displaying extremely large scene with many many instances compared to native Houdini viewport? (When both are using packed geometry)

**Comment by juxi500** [comment]
IIRC OpenGL must deinstance all the instanced geometry inside the GPU, that's why probably Embree could have advantages in very big scenes with many many instances, or am I wrong? Can Hydra somehow overcome this OGL limitation?

**Comment by spitzak** [comment]
I feel like the main savings is that Hydra can turn usd data into OpenGL
rendering much faster than the Houdini code, as the speed of tumbling the
scene without changing the frame number is not much different since the
default version has already converted USD into Houdini data structures.
That is the main reason animations and huge instances are much faster. The
other advantage is that normals are more accurate and types other than Mesh
draw correctly. I would guess it also uses less memory and graphics
resources.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4889.

**Comment by sunyab** [comment]
Houdini's Solaris is integrated with Hydra and provides the ability to switch between different render delegates. Please refer to the Houdini and Solaris documentation for more details. Thanks!
