### ISSUE TITLE
UsdMaya does not export visibility if plug is animated and usdTime.IsDefault()

### ISSUE THREAD

**Issue by msercheli** [PixarAnimationStudios/USD#682]
### Description of Issue
Having an animated visibility channel (of a transform node in Maya) while "exporting selected" with "Export Animation" OFF, will cause the visibility token in Usd to not be written.

Since the "Export Animation" flag is OFF (causing usdTime.IsDefault() to be TRUE) and the visibility plug is categorized as "animated", UsdMayaPrimWriter::Write (primWriter.cpp, line 113) will not export the visibility token.

I expect that, since the user is requesting (through GUI) to export visibility, that the plugin would get the plug value from the current frame of Maya, and write that data using Usd default time (since the user doesn't want animation to be exported). But, silently ignoring the user request sounds wrong.

### Steps to Reproduce
1. New Maya scene
2. Create a group (transform node)
3. Set visibility of the newly created node to OFF
4. Set key to the visibility channel
5. Select the created transform
5. File > Export Selection...
6. "Export Visibility" ON
7. "Export Animation" OFF

The resulting USD file does not write the visibility = invisible token.

### System Information (OS, Hardware)
CentOS 7

### Package Versions
18.11

**Comment by jtran56** [comment]
Filed as internal issue #USD-4890.
