### ISSUE TITLE
Crash in Hydra when deleting a prim and updating a collection

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#684]
### Description of Issue
If you have a stage loaded into a hydra viewer, and make an edit to the stage that:
1) deletes a prim
2) updates or deletes a collection that pointed directly at that deleted prim
there will be a crash the next time hydra tries to update the scene.

### Steps to Reproduce
1. Extract the files from [collection_crash.zip](https://github.com/PixarAnimationStudios/USD/files/2543385/collection_crash.zip)
2. Load collection_crash.usda into usdview.
3. In the Composition tab, select the collection_crash.usda layer
4. In the Interpreter window, run the following to delete a prim and a collection that refers to that prim:
import collection_crash
collection_crash.crash(usdviewApi.layer)
5. Tumble the viewport to force a refresh, and usdview will crash.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4892.

**Comment by sunyab** [comment]
This was addressed by pull request #685, which was just merged into the dev branch.

**Comment by sunyab** [comment]
This fix was released in v19.01. Closing!
