### ISSUE TITLE
UsdAbc should allow non-HDF5 builds of Alembic

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#69]
If Alembic is built without HDF5 support, the AbcCoreHDF5/ headers are not published, and alembicReader.cpp will not compile. Since HDF5 support is deprecated, it should be possible to build without it. Perhaps the UsdAbc Cmake script could detect the existence of the AbcCoreHDF5 headers, and add a preprocessor directive such as HAVE_NO_HDF5 if appropriate.

**Comment by jtran56** [comment]
Filed as internal issue #138128.
