### ISSUE TITLE
Python bindings for resolver RefreshContext

### ISSUE THREAD

**Issue by WD-stefaang** [PixarAnimationStudios/USD#694]
### Description of Issue
Python bindings are missing for resolver.RefreshContext () ... The documentation indicates that you should use it to flush caches, e.g. in a URI resolver you could clean the cache to enforce that all assets get resolved and fetched again.

### Steps to Reproduce

    resolver = Ar.GetResolver() #pylint: disable=no-member
    resolver.ConfigureResolverForAsset(usd_file)
    stage = Usd.Stage.Open(usd_file)
    context = resolver.GetCurrentContext()
    resolver.RefreshContext(context) ---> missing

or just refresh the default context with

    resolver.RefreshContext(None)

### System Information (OS, Hardware)
Ubuntu

### Package Versions
Basic USD 18.11 + S3 resolver

### Build Flags
-

**Comment by jtran56** [comment]
Filed as internal issue #USD-4917.

**Comment by sunyab** [comment]
Closing old issue, this Python binding was added in #820 some time ago.
