### ISSUE TITLE
USD can’t import bool primvars into Katana

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#696]
### Description of Issue

The USD plugin for Katana will turn BOOL attributes in a usd into INT, but not for bool primvar, instead throwing an error.

It however produces a mangled geometry.arbitrary attribute without a type or value, which causes a large number of warnings in Katana when rendering.

### Steps to Reproduce
1. Have a bool primvar in your usd file and import to Katana.

2. Usd will print an error saying it is unable to convert.

3. Katana will print an error per mesh that inherits this bad bool attribute.

### System Information (OS, Hardware)
CentOS7

### Package Versions
usd-18.09
katana-3.0

**Comment by jtran56** [comment]
Filed as internal issue #USD-4920.

**Comment by c64kernal** [comment]
Closing this issue as we are in the process of deprecating the Katana plugins from the USD repo.
