### ISSUE TITLE
build_usd.py fails on german visual studio

### ISSUE THREAD

**Issue by haggi** [PixarAnimationStudios/USD#697]
### Description of Issue
build_usd.py does not find a c++ compiler on a current windows10 with VS 2017. 
### Steps to Reproduce
1. execute build_usd.py

The problem is that the build_usd.py searches for "Compiler Version (\d+).(\d+).(\d+)" whereas the output of the cl.exe command in my version is: "C/C++-Optimierungscompiler Version ...." If I change the uppercase "Compiler" to lowercase "compiler" it works fine.

**Comment by superfunc** [comment]
This looks like it may be similar to #613; it'd be nice if there were a more programmatic way of checking this on Windows.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4921.
