### ISSUE TITLE
macOS - "Failed axiom: ' Py_IsInitialized() '" due to Homebrew Python2.7 installed - WORKAROUND FOUND

### ISSUE THREAD

**Issue by otri** [PixarAnimationStudios/USD#699]
Referring to Issue #19 

@meshula and I were working on this issue together, and figured out a work-around.
Could be something for the cmake script to resolve more effectively.

### Description of Issue

All the generated python utilities like `usdcat`, `usdchecker`, `usddiff`, `usdedit`, etc.. reference the incorrect python version, at the top of each script:

> #!/usr/local/bin/python2.7

Because cmake builds all the libs with system python, the references are to that python version.
So instead, all these scripts should instead reference system python at:

> #!/usr/bin/python

### System Information (OS, Hardware)
macOS 10.14.1
homebrew installed Python 2.7

**Comment by jtran56** [comment]
Filed as internal issue #USD-4923.
