### ISSUE TITLE
invalid public link in the readme

### ISSUE THREAD

**Issue by heckj** [PixarAnimationStudios/USD#7]
https://github.com/PixarAnimationStudios/USD/blame/master/README.md#L22:

`http://openusd.org/docs/Getting-Help-With-USD.html` is resolving to http://graphics.pixar.com/usd/docs/Getting-Help-With-USD.html, and that's returning a 404.

**Comment by amooty** [comment]
Filed as internal issue #135160.

**Comment by sunyab** [comment]
Closing this issue out, thanks again @heckj!
