### ISSUE TITLE
PcpLayerStackSite is missing PCP_API

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#703]
### Description of Issue
Notice PcpSite is setup correctly, but PcpLayerStackSite is not:

https://github.com/PixarAnimationStudios/USD/blob/56c2e1def36ee07121f4ecb349c1626472b3c338/pxr/usd/lib/pcp/site.h#L79

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD 18.11

### Build Flags
--build-monolithic

**Comment by jtran56** [comment]
Filed as internal issue #USD-4940.
