### ISSUE TITLE
PcpNodeRef::GetUniqueIdentifier is missing PCP_API, but referenced from public header

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#704]
### Description of Issue
Missing PCP_API:
https://github.com/PixarAnimationStudios/USD/blob/56c2e1def36ee07121f4ecb349c1626472b3c338/pxr/usd/lib/pcp/node.h#L105

And in-lined here:
https://github.com/PixarAnimationStudios/USD/blob/56c2e1def36ee07121f4ecb349c1626472b3c338/pxr/usd/lib/pcp/node.h#L98

Which means anything including node.h can't compile

### Steps to Reproduce
1. Include node.h from an external application.

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD 18.11

### Build Flags
--build-monolithic

**Comment by jtran56** [comment]
Filed as internal issue #USD-4941.
