### ISSUE TITLE
Sdf*ViewPredicate classes are missing SDF_API declarations

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#705]
### Description of Issue
https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/lib/sdf/proxyPolicies.h#L237

### System Information (OS, Hardware)
Windows 10

### Package Versions
USD 18.11

### Build Flags
--build-monolithic

**Comment by jtran56** [comment]
Filed as internal issue #USD-4942.
