### ISSUE TITLE
Is it possible to use non-PBR materials?

### ISSUE THREAD

**Issue by zeman-88** [PixarAnimationStudios/USD#708]
I couldn't find any references to any other shading approximations in the API, e.g. Phong, Blinn, etc.
Is it possible at all to define USD stages which use these types of shading rather than PBR?

**Comment by c64kernal** [comment]
Hi @zeman-88,

We currently only ship USD with UsdPreviewSurface set of shading nodes (see a detailed description here: http://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html).  However, the system is completely extensible of course and you can provide your own shaders and express them in USD using the UsdShade schemas (which you can read about here: http://graphics.pixar.com/usd/docs/api/usd_shade_page_front.html)

Hope that helps, I'll close this issue out, but if you need more information, please let us know!
