### ISSUE TITLE
Cmake OpenEXR detection should detect library suffixes

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#71]
OpenEXR library builds add suffixes on Windows and macOS, such as -

`Iex-2_2.dll

libIex-2_2.12.0.0.dylib
`
On Linux, the Cmake script doesn't fail because I imagine that the names have been resolved either through renaming or symlinks.

Linking against symlinked versions of the libraries is not user-friendly on Windows or macOS, because on those platforms users have the ability to move applications, and they do, no matter how many times you ask them not to do. So, linking against the real dylibs/dlls would be beneficial to end users.

The Cmake script goes to the trouble of extracting the OpenEXR version number, in the example case it discovers

`2.2.0
`

Inconsistently, OpenEXR does not suffix Half.dll. Just throwing that out there as a note.

It would be very helpful if the Cmake detection script, after failing to find Iex.dll or Iex.dylib, ran again using a regex or something to allow for the fully suffixed libraries to be detected.

**Comment by drwave** [comment]
Here are the libraries I currently have to symlink on the Mac:

ln -s libHalf.12.0.0.dylib libHalf.dylib
ln -s libHalf.12.0.0.dylib libHalf.12.dylib
ln -s libOpenImageIO.1.7.6.dylib libOpenImageIO.1.7.dylib
ln -s libOpenImageIO_Util.1.7.6.dylib libOpenImageIO_Util.1.7.dylib
ln -s libIlmImf-2_2.22.0.0.dylib libIlmImf-2_2.22.dylib
ln -s libImath-2_2.12.0.0.dylib libImath-2_2.12.dylib
ln -s libIex-2_2.12.0.0.dylib libIex-2_2.12.dylib
ln -s libIlmThread-2_2.12.0.0.dylib libIlmThread-2_2.12.dylib
ln -s libpng16.16.22.0.dylib libpng16.16.dylib
ln -s libOpenColorIO.1.0.9.dylib libOpenColorIO.1.dylib

**Comment by jtran56** [comment]
Filed as internal issue #138130.

**Comment by salamanderrake** [comment]
Still fails to find OpenEXR libs on linux.
