### ISSUE TITLE
Maya plugin import symbol not found error 

### ISSUE THREAD

**Issue by pukeanddie** [PixarAnimationStudios/USD#712]
### Description of Issue
When importing the pxrUsd.bundle or the pxrUsdTranslator.bundle Maya is throwing the following error:

`// Error: file: /Applications/Autodesk/maya2017/Maya.app/Contents/scripts/others/pluginWin.mel line 767: Unable to dynamically load : /usr/local/USD/third_party/maya/plugin/pxrUsdTranslators.bundle
dlopen(/usr/local/USD/third_party/maya/plugin/pxrUsdTranslators.bundle, 1): Symbol not found: __ZN8Autodesk4Maya16OpenMaya201800007MObject8kNullObjE
  Referenced from: /usr/local/USD/third_party/maya/lib/libusdMaya.dylib
  Expected in: /Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libFoundation.dylib
 in /usr/local/USD/third_party/maya/lib/libusdMaya.dylib // `

### Steps to Reproduce
1. checkout build v18.11
2. add environment variables as described in documentation
3. run python USD/build_scripts/build_usd.py /usr/local/USD --maya --maya-location /Applications/Autodesk/maya2017/
4. After build succeeds launch Maya 2017 and load pxrUsd.bundle from plugin manager.

### System Information (OS, Hardware)
Mac OS 10.13.6

### Package Versions
v18.11

**Comment by pukeanddie** [comment]
I'm not sure how, but I've been able to resolve this specific issue by starting over completely. I believe I was inadvertently still pointing to Maya 2018 when building the plugin and trying to import it into maya2017. I have no idea if this is the sort of error that would result from that.

**Comment by usmanredsoft** [comment]
Hello natwales,

Can you help me Pixar USD plugin doesnt load for mac Mojave / maya 2018. 

// Error: loadPlugin /Applications/Autodesk/maya2018/plug-ins/pxrUSD/pxrUsd.bundle; //
// Error: Line 1.12: Syntax error //

or could you send me complied plugin files or some help appreciate ?
