### ISSUE TITLE
Nested instances are not highlighted correctly in usdview

### ISSUE THREAD

**Issue by luh-idcc** [PixarAnimationStudios/USD#713]
### Description of Issue

Load the USD scene [NestedInstantiatedSphereMeshes.zip](https://github.com/PixarAnimationStudios/USD/files/2649758/NestedInstantiatedSphereMeshes.zip) from the USD 18.09 and select only one of the spheres in the USDView, the OpenGL viewport gives wrong highlighting, that it seems a lot of spheres are selected.

Narrowing down the issue, the Hydra selection buffer seems to contain wrong selection information. So this issue may affect any Hydra supported third party viewports.

### Steps to Reproduce
1. load the attached USD scene in USDView
2. select /Left/LeftSphere/Back/BackSphere/Bottom/BottomSphere/Rotate/Sphere, from the item tree or by pixel pick
3. see four spheres are highlighted
Expected: only one sphere is highlighted

### System Information (OS, Hardware)
Windows 10
Centos 7.5

### Package Versions
USD 18.09

### Build Flags
Consistent with gcc, cl, and debug and optimized builds.

**Comment by spiffmon** [comment]
Hi @DrLUH - thanks for the nice repro case!

This is a known limitation of Hydra's picking logic, and related to some other problems involving instancing and hiliting.  We have identified a good number of issues related to processing of instances in the USD scene delegate, and drawing them in the gl renderer, and there are several performance and refactoring tasks we consider higher priority than this issue, but we do hope to get to it eventually.

Cheers,
--spiff

**Comment by jtran56** [comment]
Filed as internal issue #USD-4970.
