### ISSUE TITLE
Shouldn't detect X11 on macOS

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#72]
The bit of code below will mess up macOS users with X11 installed, in the sense that an X11 dependency will be baked into USD. When a developer builds, say a Maya plugin for USD, and then attempts to distribute it to an artist, the artist will be doomed to install X11. Since the graphics functions on macOS don't use X11, X11 should not be searched for at all on macOS. Ditto for Windows of course.

```
if (PXR_BUILD_IMAGING)
    # --OpenImageIO
    find_package(OpenImageIO REQUIRED)
    # --OpenGL
    find_package(OpenGL REQUIRED)
    find_package(GLEW REQUIRED)
    # --Opensubdiv
    find_package(OpenSubdiv 3 REQUIRED)
    # --Ptex
    find_package(PTex REQUIRED)
    # --X11
    find_package(X11)
    # --Qt
    find_package(Qt4)
    if (QT4_FOUND)
        find_package(PySide REQUIRED)
    endif()
endif()

```

**Comment by jtran56** [comment]
Filed as internal issue #138150.
