### ISSUE TITLE
ImportError: No module named pxr.Usdviewq

### ISSUE THREAD

**Issue by ehsan1772** [PixarAnimationStudios/USD#724]
### Description of Issue
After installing USD in Windows, running usdview results in the following error:

Traceback (most recent call last):
  File "C:\Program Files\USD\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
ImportError: No module named pxr.Usdviewq

### Steps to Reproduce
1. Install USD on Windows by following the instructions
2. Test the installation by running 👍 
usdview extras/usd/tutorials/convertingLayerFormats/Sphere.usda

### System Information (OS, Hardware)
Windows 10
### Package Versions
Not sure about the version, cloned the master branch from Github on 12/17/2018

**Comment by c64kernal** [comment]
Hi @ehsan1772 -- this is most typically a path problem, e.g., PYTHONPATH and PATH.  Are those environment variables set correctly in your setup?

**Comment by jtran56** [comment]
Filed as internal issue #USD-4981.

**Comment by ehsan1772** [comment]
I am closing this issue since now I can pass this issue after using the 64 bit version of the developer command line, I filed a new issue here:

https://github.com/PixarAnimationStudios/USD/issues/732

**Comment by michsiu** [comment]
I run the code on x64 developer command line but i have the same issue
