### ISSUE TITLE
[Maya USD Exporter] Maya crashes when more bind pose members than joints

### ISSUE THREAD

**Issue by pstuart42** [PixarAnimationStudios/USD#725]
### Description of Issue

USD Export crashes Maya when there are more members connected to the bind pose DagPose node than there are joints.

The segfault happens due to `dagPaths` being accessed with an out of bounds index here:
https://github.com/PixarAnimationStudios/USD/blob/1845291a9701ab0a3a7d591bc243a1a80fdcba8a/third_party/maya/plugin/pxrUsdTranslators/jointWriter.cpp#L333

### Fix
We haven't submitted a contributor agreement yet (I believe that should all be done in a couple weeks) so I can't submit a PR for the fix. However, I'll post the fix here in case someone else runs into the problem. The fix is to change:

https://github.com/PixarAnimationStudios/USD/blob/1845291a9701ab0a3a7d591bc243a1a80fdcba8a/third_party/maya/plugin/pxrUsdTranslators/jointWriter.cpp#L312

to:
`indices->resize(dagPaths.size(), -1);`

My reading of the code is that `indices` maps joints to members of the DagPose so the size should match the list of joints `dagPaths`, not the number of DagPose members.

**Comment by jtran56** [comment]
Filed as internal issue #USD-4979.
