### ISSUE TITLE
HdxTaskContoller doesn't clean up the HRenderTask properly

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#726]
### Description of Issue
The HdxTaskController used by a UsdImagingGLEngine doesn't clean up the render task properly in its destructor, which leads to a crash when destroying the HdxTaskController.

### Steps to Reproduce
1. Create a UsdImagingGLEngine, direct it to use the Embree render delegate, and call:
_taskController->SetRenderOutputs({ HdAovTokens->color, HdAovTokens->depth })
2. When the HdxTaskController is destroyed, the destructor calls:
GetRenderIndex()->RemoveTask(tasks[i]);
for the HdRenderTask it spun up. Then it calls:
GetRenderIndex()->RemoveBprim(HdPrimTypeTokens->renderBuffer, id);
to delete all the HdRenderBuffer bprims created by the render delegate.
3. At this point your app will crash, as the embree renderer is still running in the background, and writing data to the (now deleted) render buffers. The HdRenderTask has not been destroyed! This is because the _tasks memeber of the HdxTaskController (filled in by the GetTasks method) is still holding a shared pointer to the HdRenderTask. The _tasks vector is only cleared at the end of the destructor, after the render buffers are destroyed and the app has crashed.

The simple solution is to call _tasks.clear() in the HdxTaskController destructor before or immediately after the loop that calls GetRenderIndex()->RemoveTask() on all the tasks.

### Package Versions
19.01

**Comment by jtran56** [comment]
Filed as internal issue #USD-4980.
