### ISSUE TITLE
usdview clipping planes are often wrong and will not update

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#729]
### Description of Issue
This is really two different issues:

1) Something about my assets is incompatible with usdview clipping plane adjustment algorithm, which means as soon as I move the camera after opening an asset, objects start getting clipped.

2) The hotkey "C" to readjust clipping planes only works initially, but often will do nothing.

This is frustrating when in a tight loop of debugging an asset, for example:
 * Open an asset
 * Zoom in on the detail I'm trying to debug
 * Object is now invisible because of poorly chosen clipping planes
 * Hit C, sometimes it works, sometimes it does nothing
 * If C did nothing, dig through the menus to find the clipping plane setting
 * Key in good clipping values
 * one second of inspection tells me the asset is still broken, close usdview (usdview cannot reload assets, bug incoming)
 * Rinse, repeat.

### Steps to Reproduce
I think this may require an asset authored in meters instead of centimeters.

### System Information (OS, Hardware)
Windows

### Package Versions
18.11

### Build Flags
--build-monolithic --openimageio

**Comment by spiffmon** [comment]
Sorry to hear about this, Jeremy!  Any chance you can get us a USD file we
can use to repro?  In the interrim, unless you really need camera guides,
perhaps you can turn them off and then "Reload Stage" will work.

--spiff

**Comment by jtran56** [comment]
Filed as internal issue #USD-4994.

**Comment by spiffmon** [comment]
I'm going to close this, Jeremy, since as of 19.05, auto-clipping is opt-in.  Please reopen or refile if you're still having problems and can give us a repro!
