### ISSUE TITLE
Usda ascii parser is too restrictive for asset paths

### ISSUE THREAD

**Issue by spiffmon** [PixarAnimationStudios/USD#73]
Paste the following to a text file named asset.usda (which was generated without error using the python API), and attempt to usdcat or usdedit it.  You will get something like:

Failed to open 'asset.usda' - 
    Error in 'textFileFormatYyerror' at line 3074 in file pxr/pxr/usd/sdf/textFileFormat.yy : 'syntax error at 'fr' in </root.assAttr> on line 11 in file /scratch/asset.usda
'
Error: Failed to open file asset.usda, exiting.

The ascii parser is very restrictive in what it allows in asset paths... partly due to some internal tricks we play for fast dependency analysis, partly because we were over-fitting for filesystem-based paths.  People want to use UIR's that require many non-alnum characters, and we need to provide for being able to parse them out of ascii robustly.

**Comment by spiffmon** [comment]
#usda 1.0
(
    doc = """Generated from Composed Stage of root layer 
"""
)

def "root"
{
    custom asset assAttr = @foo@.bar@
    asset assAttr.timeSamples = {
        10: @fd@42@fr@,
        20: @fd@42?fr@,
    }
}

**Comment by jtran56** [comment]
Filed as internal issue #138165.

**Comment by murphyeoin** [comment]
Great - this has been a problem for us to which we patched, and were going to put a PR in for once we'd gotten our fork of the public github repo working properly. Our uri syntax is along the lines of:
ams:/JOB(name)/ASSETTYPE(foo)/ASSET(bar)?version=vXXX&file=blah.txt
Thanks!
Eoin
