### ISSUE TITLE
Windows Installation Error (ImportError: DLL load failed)

### ISSUE THREAD

**Issue by ehsan1772** [PixarAnimationStudios/USD#732]
### Description of Issue

Installed USD on Windows by cloning the master branch and following the instructions. The installation went by with no errors, but  when I tried to run:

usdview extras/usd/tutorials/convertingLayerFormats/Sphere.usda

I get his error:

Traceback (most recent call last):
  File "C:\Program Files\USD\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "C:\Program Files\USD\lib\python\pxr\Usdviewq\__init__.py", line 26, in <module>
    from qt import QtWidgets
  File "C:\Program Files\USD\lib\python\pxr\Usdviewq\qt.py", line 26, in <module>
    from attributeValueEditorUI import QtCore
  File "C:\Program Files\USD\lib\python\pxr\Usdviewq\attributeValueEditorUI.py", line 10, in <module>
    from PySide import QtCore, QtGui
ImportError: DLL load failed: %1 is not a valid Win32 application.

### Steps to Reproduce
1. Download the master branch
2. Follow the instructions to install USD
3. Run : usdview extras/usd/tutorials/convertingLayerFormats/Sphere.usda

### System Information (OS, Hardware)

Windows 10
### Build Flags
no flags were used

**Comment by ehsan1772** [comment]
Tried to install Qt module, and now I am getting:

C:\Users\ebar\Downloads\USD-master>usdview extras/usd/tutorials/convertingLayerFormats/Sphere.usda
Traceback (most recent call last):
  File "C:\Program Files\USD\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "C:\Program Files\USD\lib\python\pxr\Usdviewq\__init__.py", line 26, in <module>
    from qt import QtWidgets
ModuleNotFoundError: No module named 'qt'

I was under the impression that all the dependencies get installed through the USD installer ...

**Comment by c64kernal** [comment]
Hi @ehsan1772  -- the first step in the readme asks you to install some per-requisites manually (for a number of reasons we don't install them for you).  Here's a snippet:

1. Install prerequisites (see Dependencies for required versions)

    Required:
        C++ compiler:
            gcc
            Xcode
            Microsoft Visual Studio
        NASM (required for Imaging on Windows)
        CMake
    Optional (Can be ignored by passing --no-python as an argument to build_usd.py)
        Python (required for bindings and tests)
        PyOpenGL (required for usdview)
        PySide or PySide2 (experimental) (required for usdview)

In particular you need to make sure you "pip install pyside" and "pip install PyOpenGL"

Hope that helps resolve this for you.

**Comment by ehsan1772** [comment]
So the root of the error seemed to be not using a 64 bit version of Python.
