### ISSUE TITLE
USD plugin doesnt work on mac Mojave

### ISSUE THREAD

**Issue by usmanredsoft** [PixarAnimationStudios/USD#733]
### Description of Issue

USD plugin doesnt work on mac Mojave

loadPlugin /Applications/Autodesk/maya2018/plug-ins/pxrUSD/pxrUsd.bundle;
// Error: loadPlugin /Applications/Autodesk/maya2018/plug-ins/pxrUSD/pxrUsd.bundle; // 
// Error: Line 1.12: Syntax error // 

http://prntscr.com/m3r8rw

### Steps to Reproduce
Windows > Settings > load plugin browse pxrUsd.bundle but always getting error

### System Information (OS, Hardware)
Maya 2018
Mac OS Majove 10.14
### Build Flags

**Comment by c64kernal** [comment]
Hi @usmanredsoft -- Apologies that no one here so far has been unable to help you solve your problems, and I saw that you posted a request to many other issues, which I'm not sure will get you much farther along unfortunately.  A suggestion I thought I'd offer up is to consider looking on the Apple developer community forums or maybe even the Autodesk ones.  You might be able to find folks there who are much more familiar with the kinds of problems you're running into.  Best of luck!
