### ISSUE TITLE
[usdMaya] instancer not imaging usd assemblies when they are children

### ISSUE THREAD

**Issue by mrharris** [PixarAnimationStudios/USD#739]
### Description of Issue
The ability to use usd assemblies in maya's instancer was added in https://github.com/PixarAnimationStudios/USD/commit/09a4b01586e03512617d8b9c5b674d57560850c8 which is really helpful! However, it only works when then usd assembly node itself is directly added to the instancer node. If instead the assembly is a child of a transform/locator and you add _that_ to the instancer - viewport2 will not draw the instances unless they are in "Full" representation. It still correctly exports as far as I can tell - it seems like it is just a drawing issue?
![instance_under_transform](https://user-images.githubusercontent.com/1923447/50959671-648e5480-14bb-11e9-9360-989b43c47227.gif)

### Steps to Reproduce
1. create a usd assembly
2. parent it under a transform
3. add that parent to an instancer 
4. set the display representation to Full
5. instances draw as expected
6. set the representation to anything else
7. no instancers are drawn

### System Information (OS, Hardware)
Centos7, maya2018.5

### Package Versions
19.01

**Comment by jtran56** [comment]
Filed as internal issue #USD-5012.

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
