### ISSUE TITLE
Switch to Disable Test

### ISSUE THREAD

**Issue by zhoub** [PixarAnimationStudios/USD#74]
Hi,

Is there possible to supply a CMake switch to discard the all test ? Thanks very much.

**Comment by jtran56** [comment]
Filed as internal issue #138203.

**Comment by sunyab** [comment]
Commit eaad278e4 added a cmake option 'PXR_BUILD_TESTS' that can be set to FALSE to disable building and running tests.

**Comment by sunyab** [comment]
Commit has been merged into release v0.7.2, closing.
