### ISSUE TITLE
Using USD in MSVC Project: error C2653: 'UsdStage': is not a class or namespace name

### ISSUE THREAD

**Issue by ebargoogle** [PixarAnimationStudios/USD#740]
### Description of Issue
I added the USD lib to a C++ console application is VS 2017, The project compiles fine after adding the dependencies to the linker and include directories. This is all I have in my ConsoleApplication.cpp file:

#include "pch.h"
#include <iostream>
#include "pxr/usd/usd/stage.h"

int main()
{	
    UsdStage::CreateNew("Test.usda");
    std::cout << "Hello World!\n"; 
}

It fails to compile with "error C2653: 'UsdStage': is not a class or namespace name" error. Even though I can CTRL+Click into the header file, for some reason it cannot recognize the UsdStage class. Am I adding the wrong header file?

If I change that line to :
pxrInternal_v0_19__pxrReserved__::UsdStage::CreateNew("Test.usda");	

The compile error goes away, but then I get a run time error that seems to be caused by the linker:

error LNK2001: unresolved external symbol "__declspec(dllimport) private: static struct pxrInternal_v0_19__pxrReserved__::TfRefBase::UniqueChangedListener pxrInternal_v0_19__pxrReserved__::TfRefBase::_uniqueChangedListener" (__imp_?_uniqueChangedListener@TfRefBase@pxrInternal_v0_19__pxrReserved__@@0UUniqueChangedListener@12@A)

Am I including the wrong header file?

### Steps to Reproduce
1- Created a new project in Visual Studio 2017 : File > New Project > Visual C++ > Windows Console Application
2-  Add the USD header files and libs to the project
3- Add these lines to the main cpp file:

#include "pch.h"
#include <iostream>
#include "pxr/usd/usd/stage.h"

int main()
{	
    UsdStage::CreateNew("Test.usda");
    std::cout << "Hello World!\n"; 
}

**Comment by jtran56** [comment]
Filed as internal issue #USD-5013.
