### ISSUE TITLE
Crash when calling python Usd.Prim.IsDefined() on a null prim

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#753]
### Description of Issue
When you have a null prim object in Python, calling almost any method on it throws a python exception. A few methods (like IsValid()) return values. But IsDefined() crashes the applications

### Steps to Reproduce
1. Open any USD file in usdview.
2. In the Interpreter window run:
p = usdviewApi.stage.GetPrimAtPath('/not_a_prim')
p.IsDefined()
3. usdview crashes

This is because in usd/wrapObject.cpp, in __getattribute__, there is a specific test done for a few method names. One of which is "IsDefined". This check allows the IsDefined method to be run even if the primitive is invalid (just as it allows IsValid() to return False instead of raising an exception). Every other Prim method (IsActive for example) raises an exception. The simple solution, I believe, is to just remove IsDefined from this list. But it's possible that this method really should be in this list, in which case I thinkit's implementation in wrapPrim.cpp needs to be changed to explicitly check for the null prim case?

The actual "crash" is caused in Usd_PrimDataHandle::operator->, where it calls UsdIssueFatalPrimAccessError().

**Comment by spiffmon** [comment]
Thanks, @marktucker ! I'd vote for removing IsDefined from the whitelist, since its behavior relies on the presence of authored scene data, but would like for @gitamohr to weigh in.

**Comment by spitzak** [comment]
Behavior should match between Python and C++. So either python throws an
exception and C++ crashes, or both return false.
