### ISSUE TITLE
Houdini USD Cameras cant be framed

### ISSUE THREAD

**Issue by infernalspawn** [PixarAnimationStudios/USD#755]
### Description of Issue
unable to frame a loaded usd-camera in houdini's viewport
### Steps to Reproduce
1.  create a pixar::usdcamera - node
2. load a .usd file containing a camera in the camera node (e.g. attached file with a /renderCamera/renderCameraShape - node 
3. select the camera-node in the network view
4. move your mouse over the Scene-View & hit 'f'

### System Information (OS, Hardware)
Windows, Houdini 16.5.536 
### Package Versions
18.11
### Build Flags

[renderCamera.zip](https://github.com/PixarAnimationStudios/USD/files/2795408/renderCamera.zip)

**Comment by jtran56** [comment]
Filed as internal issue #USD-5046.

**Comment by c64kernal** [comment]
Hi @infernalspawn -- USD cameras in our Houdini plugins are meant to be read only.  This capability is not supported unfortunately.  We hope that future, deeper integration of USD and Houdini will solve these workflow issues.  I'll close this now, thanks again for reporting and apologies for no action here.
