### ISSUE TITLE
Houdini usdz to alembic 

### ISSUE THREAD

**Issue by Mockermockery** [PixarAnimationStudios/USD#756]
### Description of Issue
I have an issue where I would like to convert USD files to other formats. I know that houdini has plugin that support usd and thought that plugins would be able to convert these files. I am very new to usd and Houdini and want to learn how to use houdini. 

I have loaded the model in houdini from usdimport.
![image](https://user-images.githubusercontent.com/20675466/51741192-4291f600-20a7-11e9-824b-652807739a00.png)

System Houdini, Windows 10.

**Comment by spitzak** [comment]
An unpack will convert the USD geometry into Houdini geometry, which will
probably let many of the Houdini exports run.

**Comment by jtran56** [comment]
Filed as internal issue #USD-5047.

**Comment by sunyab** [comment]
USD no longer distributes a Houdini plugin, in favor of the native USD support in Solaris. Please refer to the Houdini and Solaris documentation for more information. Thanks!
