### ISSUE TITLE
[usdImagingGL] Engine IsColorCorrectionCapable calling wrong version of IsHydraEnabled?

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#762]
The UsdImagingGLEngine::IsColorCorrectionCapable() method calls _IsHydraEnabled() (note the underscore), which checks if a GL context is currently enabled (along with a number of other checks). Is there some reason the cached IsHydraEnabled() (no underscore) method isn't used instead?

The way it is now is slower than necessary, and requires a GL context to be active whenever there is a call to "IsColorCorrectionCapable()" or "SetColorCorrectionSettings()" (which calls IsColorCorrectionCapable). This seems like a mistake, which results in TF_CODING_ERROR messages when calling these methods.

**Comment by sunyab** [comment]
Thanks for catching this @marktucker! We have a fix we'll push out to the release candidate shortly.
