### ISSUE TITLE
generatedSchema.usda not loaded from symlinks.

### ISSUE THREAD

**Issue by jdwilder-google** [PixarAnimationStudios/USD#763]
When any generatedSchema.usda is located in a symlink, `_GetGeneratedSchema` (in schemaRegistry.cpp) fails, which later causes errors when setting attributes.

This can be fixed by changing `TfIsFile(fname)` to `TfIsFile(fname, true)` in `_GetGeneratedSchema`.  It appears that the lack of symlink support is unintentional due to the omission of the default parameter.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5139
