### ISSUE TITLE
usdview: 'OpenGL context required, using reference renderer' Segmentation Fault on startup

### ISSUE THREAD

**Issue by ianlawson** [PixarAnimationStudios/USD#764]
### Description of Issue
I've noticed in the latest dev branch that if I disable 'Redraw on Frame Scrub' and close usdview when I reopen it I hit a Segmentation Fault. I'm then forced to delete my preferences in order to relaunch usdview.

`
Traceback (most recent call last):
  File ".../usd_install/lib/python/pxr/Usdviewq/stageView.py", line 2140, in glDraw
    if not self._getRenderer():
  File ".../usd_install/lib/python/pxr/Usdviewq/stageView.py", line 906, in _getRenderer
    self._renderer = UsdImagingGL.Engine()
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_19__pxrReserved__::{anonymous}::_IsHydraEnabled' at line 73 in file .../USD/pxr/usdImaging/lib/usdImagingGL/engine.cpp : 'OpenGL context required, using reference renderer'
Segmentation fault
`

### Steps to Reproduce
1. Launch **usdview**.
2. Disable 'Redraw on Frame Scrub'
3. Close usdview.
4. Reopen usdview.

### System Information (OS, Hardware)

CentOS7

### Package Versions

DEV 19.05

**Comment by spiffmon** [comment]
Hi Ian,
    I'm unfortunately not able to reproduce this issue, and the error
message seems indicative of something much deeper than that GUI interaction
setting... I'm curious do you get that _IsHydraEnabled() error all the
time, or only in this case when it's about to segfault?

--spiff

**Comment by ianlawson** [comment]
I only see the hydra error when it's about to segfault. Launching a fresh usdview with the redraw option enabled, I see no error from hydra and the UI loads as expected.

Good to know you can't reproduce on your end - I'll have a dig around and see if I can find out what's going on in my build!

**Comment by jtran56** [comment]
Filed as internal issue #USD-5073.

**Comment by sunyab** [comment]
Hi @ianlawson, so I've also been unable to reproduce this on a CentOS 7 machine, but I was able to reproduce this on a Mac. We're not sure why we don't see this on a CentOS machines though.

- Could you run a fresh usdview with the environment variable  TF_DEBUG set to "GLF_DEBUG_CONTEXT_CAPS" and post the results? This should dump some info to terminal that would be useful for debugging.

- Do you still hit the crash if you run usdview with the --renderer flag, like "usdview --renderer GL" or "usdview --renderer HydraDisabled"? (Also "usdview --renderer Embree" if you have the Embree plugin installed)

Thanks!

**Comment by ianlawson** [comment]
GlfContextCaps: 
  GL version                         = 460
  GLSL version                       = 460
  GL_MAX_UNIFORM_BLOCK_SIZE          = 65536
  GL_MAX_SHADER_STORAGE_BLOCK_SIZE   = 2147483647
  GL_MAX_TEXTURE_BUFFER_SIZE         = 134217728
  GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 256
  ARB_bindless_texture               = 0
  ARB_direct_state_access            = 1
  ARB_explicit_uniform_location      = 1
  ARB_multi_draw_indirect            = 1
  ARB_shader_draw_parameters   = 1
  ARB_shader_storage_buffer_object   = 1
  ARB_shading_language_420pack       = 1
  NV_shader_buffer_load              = 0
Segmentation fault

**Comment by ianlawson** [comment]
I still see the error with both:

- --renderer GL
- --renderer HydraDisabled
