### ISSUE TITLE
OSX Build Fails with Cuda Installed

### ISSUE THREAD

**Issue by jbartolozzi** [PixarAnimationStudios/USD#767]
### Description of Issue
Building TBB fails when /usr/local/cuda directory exists.
Build succeeds when I move /usr/local/cuda to another directory.

Created ./build/macos_intel64_clang_cc10.0.0 Found CUDA installation: /usr/local/cuda, version unknown_os10.13.6_release and ..._debug directories
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C "./build/macos_intel64_clang_cc10.0.0 Found CUDA installation: /usr/local/cuda, version unknown_os10.13.6_debug"  -r -f ../../build/Makefile.tbb cfg=debug
make[1]: ../../build/Makefile.tbb: No such file or directory
make[1]: *** No rule to make target `../../build/Makefile.tbb'.  Stop.
make: *** [tbb] Error 2

### Steps to Reproduce
1. python build_scripts/build_usd.py /usr/local/USD

### System Information (OS, Hardware)
MacOS 10.13.6

**Comment by sunyab** [comment]
This appears to be a bug in the TBB build system -- see https://github.com/01org/tbb/issues/44. Besides moving/uninstalling CUDA, a possible workaround is mentioned in https://github.com/spack/spack/issues/6000

**Comment by jtran56** [comment]
Filed as internal issue #USD-5082.
