### ISSUE TITLE
Maya2019 unable to load plugin

### ISSUE THREAD

**Issue by mariusgabris** [PixarAnimationStudios/USD#771]
Hello, 

I'm trying to load maya plugins in maya 2019 on windows. I was able to build the plugin and set the environment variables, but I'm getting this errors when I try to load them in maya:
// Error: line 1: Unable to dynamically load : D:/workTest/usdz-tool/USD/third_party/maya/plugin/pxrUsd.mll
The specified procedure could not be found.
 // 
// Error: line 1: Unable to dynamically load : D:/workTest/usdz-tool/USD/third_party/maya/plugin/pxrUsdPreviewSurface.mll
The specified procedure co
uld not be found.
 // 
// Error: line 1: Unable to dynamically load : D:/workTest/usdz-tool/USD/third_party/maya/plugin/pxrUsdTranslators.mll
The specified procedure could not be found.

I've built the plugin from dev branch.

Does anybody encountered this issue? or can I find additional information about this error message?

Thank you,
Marius

**Comment by jilliene** [comment]
Filed as internal issue #USD-5092

**Comment by AlexLuze** [comment]
Hello,
I want to install in plugins in Maya 2018 on windows. But I don't know how to install it, Do you have some ways to do it? 


Thanks,
Alex

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
