### ISSUE TITLE
Instanced prims don't update transforms in Hydra when the referenced prim changes

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#779]
### Description of Issue
In a USD scene with instanceable references to a source prim, updating the transform of a prim inside the source prim does not cause Hydra to update the transforms on the instances of that prim. This seems to be true of all render delegates, so is likely a framework issue, not an HdStream issue.

### Steps to Reproduce
1. Load the attached USD file into usdview.
[instance_xform_not_updating.zip](https://github.com/PixarAnimationStudios/USD/files/2916167/instance_xform_not_updating.zip)
2. Run the following code inthe interpreter window, to transform the source /geo/cube prim:
xf = UsdGeom.Xformable(usdviewApi.stage.GetPrimAtPath('/geo/cube'))
ops = xf.GetOrderedXformOps()
m = ops[1].Get()
m.SetTranslate((0, 4, 0))
ops[1].Set(m)
3. At this point, all of the cubes should move up by 2 units in y. They do not. Only the source does.
4. Switching to another render delegate and back to HdStream shows the instanced cubes in their proper locations, indicating this is an update issue.

### Package Versions
Tested using USD 19.03.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5122

**Comment by ablev-dwa** [comment]
We hit a similar Hydra issue involving instances and payload loading.

### Steps to reproduce

1. Unzip this example
[instance_payload_loading.zip](https://github.com/PixarAnimationStudios/USD/files/3123198/instance_payload_loading.zip)
2. usdview shot.usd --unloaded
3. In the outliner, right-click "root" and select "Load"
4. Note that, of two instanced triangles, only one is displayed even though the master prim was loaded correctly
5. usdview shot.usd
6. Note three triangles (expected result when payloads have been loaded)
7. Like the earlier example, this happens in both HdStream and HdEmbree, so it appears to be a general Hydra issue and not a specific delegate issue
