### ISSUE TITLE
Cannot define multiple plugins in a single plugInfo.json

### ISSUE THREAD

**Issue by ablev-dwa** [PixarAnimationStudios/USD#780]
### Description of Issue

We're getting into creating plugins for usdview, and recently completed our second plugin. Our deployment strategy was to use a single plugInfo.json file as a single registry for all usdview plugins, but ran into this issue. If you define multiple plugins in a single file, like this example:

```json
{
    "Plugins": [
        {
            "Type": "python",
            "Name": "asset_info",
            "Info": {
                "Types": {
                    "asset_info.AssetInfoPluginContainer": {
                        "bases": ["pxr.Usdviewq.plugin.PluginContainer"],
                        "displayName": "USD Asset Info"
                    }
                }
            }
        },
        {
            "Type": "python",
            "Name": "usd_render",
            "Info": {
                "Types": {
                    "usd_render.UsdRenderPluginContainer": {
                        "bases": ["pxr.Usdviewq.plugin.PluginContainer"],
                        "displayName": "USD Render GUI"
                    }
                }
            }
        }
    ]
}
```

Only one of those plugins will be loaded by libplug. It seems that this code in plug/plugin.cpp, at the top of PlugPlugin::_NewPlugin, indicates the issue:

```c++
    // Already registered?
    auto iresult = _allPlugins->insert(
        std::make_pair(metadata.pluginPath, TfNullPtr));
    if (!iresult.second) {
        auto it = iresult.first;
        TF_VERIFY(it->second);
        return std::make_pair(it->second, false);
    }
```
A quick reading of the code leads me to believe that metadata.pluginPath is the expanded file path of the plugInfo.json file, and that plugins in _allPlugins seem to be keyed by that filepath. This means that, for any given plugInfo.json, only one plugin can be loaded. And, because plugin loading is multithreaded, *which* plugin gets loaded from the plugInfo.json file is non-deterministic (and that was our experience in usdview - sometimes we'd get asset_info, sometimes we'd get usd_render, but never both).

Perhaps this is the intended behavior, and either the documentation is ambiguous or I just didn't read it closely enough. And that's okay, because it's really easy to work around this problem (each plugin gets its own plugInfo.json file, which is how we're solving this in production). But if it's not the intended behavior, then this is a low priority bug and probably worth fixing some day.

### Steps to Reproduce
1. Add this plugInfo.json in your plugin path:

```json
{
    "Plugins": [
        {
            "Type": "resource",
            "Name": "TestA",
            "Info": {
            }
        },
        {
            "Type": "resource",
            "Name": "TestB",
            "Info": {
            }
        }
    ]
}
```

2. Run this script:

```python
from pxr import Plug

for i in sorted([plug.name for plug in Plug.Registry().GetAllPlugins()]):
    print i
```

3. Notice that either TestA is loaded, or TestB is loaded, but never both

### System Information (OS, Hardware)
Linux

### Package Versions
USD-0.18.9 to USD-0.19.3

**Comment by spiffmon** [comment]
Hi @ablev-dwa !
    Yeah, plug wants to find only a single of each top-level key like "python" in a plugInfo.json, and we'll use this ticket to track making it behave better when there is more than one.  All of the top-level containers, though (I believe) can contain multiple sub-entries within them - check out usdMaya for some examples of multiple "python" plugins in a single plugInfo.json

   However, we encourage putting all usdview plugins in a single PluginContainer/module.  Rereading the usdview plugin tutorial I realized we don't discuss that at all, so I've added a new seciton that should appear in the next release.  Like:

# Organizing usdview Plugins in a Production Environment
Although the _PluginContainer_ system allows for any number of plugin modules to be discovered and executed, its design is meant to make it easier for "non-build experts" to add new usdview plugins.  Although in this simple tutorial our registerPlugins() method registered only a single command, it is capable of registering an arbitrary number of commands, and configureView() can create and configure any number of menus.  Putting all plugins in a single module, which is what we do at Pixar, has two advantages:

1. Once that module is set up by a maintainer, users desiring to add new plugins do not need to know about or modify any plugInfo.json files
2. It is much easier to organize all commands into a coherent, well-ordered set of menus when that setup happens in a single place.

**Comment by ablev-dwa** [comment]
Thanks @spiffmon that makes sense.

We did at one point implement the all-plugins-as-one-module approach when trying to figure out this problem, but it wasn't the best match for how we generally work. We may need to reconsider if we start adding enough plugins where controlling menu ordering will become important.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5123

**Comment by spiffmon** [comment]
Hi @ablev-dwa - just wanted to confirm that you have what you need to have more than one usdview command plugin in a single module?  You should be able to have multiple Plugins/Info/Types entries in the same plugInfo, but also as I explained above, the usdview command plugin is designed to allow your python module to create and configure as many commands as you want, from a single plugInfo-declared "Container".

We definitely do restrict each plugInfo to having only a single top-level "plugin", but that can actually contain many independent sub-components in the module.  I'll keep the ticket open to see if we can error in addition to non-deterministic behavior if there's more than one.

**Comment by ablev-dwa** [comment]
Hey @spiffmon , we have found several ways to approach the issue and are not blocked at all, and in fact have deployed these to production. Really the only issue was correcting our understanding of how libplug works, and how we can deploy code to match that structure.

One thing we put together that allows us to bundle each plugin as its own python package is a little shim file to load each package automatically. Our final directory structure looks like this:

```
plugInfo.json
dwausdview.py
asset_info/
    __init__.py
    foo.py
    ...
usd_render/
    __init__.py
    bar.py
    ...
```

Our plugInfo looks like this:
```
{
    "Plugins": [
        {
            "Type": "python",
            "Name": "dwausdview",
            "Info": {
                "Types": {
                    "asset_info.AssetInfoPluginContainer": {
                        "bases": ["pxr.Usdviewq.plugin.PluginContainer"],
                        "displayName": "USD Asset Info"
                    },
                    "usd_render.UsdRenderPluginContainer": {
                        "bases": ["pxr.Usdviewq.plugin.PluginContainer"],
                        "displayName": "USD Render GUI"
                    }
                }
            }
        }
    ]
}
```

And dwausdview.py looks like this:
```
# blindly load all of the subdirectories of this directory

import os
import imp

thisFile = os.path.abspath(__file__)
thisPath = os.path.dirname(thisFile)
for root, dirs, files in os.walk(thisPath):
    # just want dirs from this directory
    break

for d in dirs:
    try:
        filename, pathname, description = imp.find_module(d)
        imp.load_module(d, filename, pathname, description)
    except:
        print "Failed to load usdview plugin", d
```

This accomplishes several things.
- libplug can "import dwausdview", which seems to be a requirement of python plugins (doing a direct import of the "name" of the plugin)
- dwausdview.py will import all of the python packages that are siblings to it (how we want to deploy code in this case)
- each python package / plugin calls Tf.Type.Define in its ```__init__.py``` file, so those all types are implicitly defined when "import dwausdview" is called
- We can add a new plugin by just making a new python package, and then adding an entry to plugInfo.json (a single, non-python point of change to register the entire plugin, which is what we were aiming for in the first place)

Thanks for all your help here getting us to understand how it all works!
