### ISSUE TITLE
Usage of ERROR_ENVVAR_NOT_FOUND in Arch library

### ISSUE THREAD

**Issue by jstone-lucasfilm** [PixarAnimationStudios/USD#781]
Hey all,

Our team was developing platform-agnostic environment variable wrappers for another open-source project, and we noticed that USD is potentially using ERROR_ENVVAR_NOT_FOUND in a dangerous way:

https://github.com/PixarAnimationStudios/USD/blob/56c2e1def36ee07121f4ecb349c1626472b3c338/pxr/base/lib/arch/env.cpp#L61

In the code above, ERROR_ENVVAR_NOT_FOUND is being interpreted as a special-case return value from GetEnvironmentVariable, but it's actually a flag that is intended to be returned from GetLastError:

https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getenvironmentvariable

Assuming we're interpreting this logic correctly, the net result is that ArchGetEnv will incorrectly return an empty string whenever the value of an environment variable happens to be exactly 203 (ERROR_ENVVAR_NOT_FOUND) characters long.  To address this, I believe you can simply omit the comparison of size against ERROR_ENVVAR_NOT_FOUND, and only compare size against zero.

All the best,

-Jonathan

**Comment by c64kernal** [comment]
Thanks so much for spotting that, Jonathan!  We’ll get it fixed up ASAP.

George.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5124
