### ISSUE TITLE
PointInstancer doesn't update in Hydra when adding or removing Scales attribute

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#784]
### Description of Issue
When a point instancer is displayed in usdview with a scales attribute, removing (blocking) that attribute doesn't update the display of the geometry. Similarly, adding a scales attribute doesn't update the viewport.

### Steps to Reproduce
1. Load the attached file into usdview.
[pointinstancer_with_scales.zip](https://github.com/PixarAnimationStudios/USD/files/2938674/pointinstancer_with_scales.zip)

2. In the Interpreter window, run:
p = UsdGeom.PointInstancer(usdviewApi.stage.GetPrimAtPath('/geo'))
v = p.GetScalesAttr().Get()
p.GetScalesAttr().Block()

3. At this point I'd expect to see the point instancer change in the viewport. It does not. The following is printed to the terminal:
Warning: in Get at line 2375 of f:\dev_tools\src\usd\usd-19.03\usd\pxr\usdimaging\lib\usdimaging\delegate.cpp -- Empty VtValue: </geo> scale
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_19__pxrReserved__::UsdImagingDelegate::Get' at line 2370 in file f:\dev_tools\src\usd\usd-19.03\usd\pxr\usdimaging\lib\usdimaging\delegate.cpp : 'Failed verification: ' _GetPrim(usdPath).GetAttribute(key).Get(&value, _time) ' -- /geo, scale

4. Switch to the Embree renderer and back to GL, and everything is as expected without the scales. But then run:
p.GetScalesAttr().Set(v)

5. At this point, I'd expect to see the scales applied, but they are not. Instead the following message is printed to the terminal:
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_19__pxrReserved__::HdStVBOMemoryManager::_StripedBufferArrayRange::CopyData' at line 649 in file f:\dev_tools\src\usd\usd-19.03\usd\pxr\imaging\lib\hdst\vbomemorymanager.cpp : 'Failed verification: ' (VBO && VBO->GetId()) ' -- VBO doesn't exist for scale'

### Package Versions
Tested with 19.03.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5125
