### ISSUE TITLE
[UsdSkel] Explicit Joint Orders not handled by HdxCompute / maya import

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#789]
### Description of Issue

This section describes how "explicit joint orders" are supposed to work for skinned meshes:

https://graphics.pixar.com/usd/docs/api/_usd_skel__schema_overview.html#UsdSkel_SchemaOverview_JointInfluences

IE, each skinned mesh should be able to define it's own (sub)set of joint influences, with a possibly different ordering, in `skel:joints`, and all joint indices for that mesh should then be indices into `skel:joints`.

However, this is apparently not working, for EITHER maya's import, OR the real-time view via HdxComputation.  It DOES work properly if you bake the deformations, via UsdSkel.BakeSkinning, however.

### Steps to Reproduce
1. Open the given `orig_skel_export.usda` in usdview. See how it animates between frames 1 and 2 - this is the desired result.  `orig_skel_export.usda` DOES technically have a `skel:joints`, but it's identical to the `joints` attribute defined on the skeleton, so it's not really testing anything.
2. Now, open `unused_joint_removed.usda` in usdview.  This is identical to `orig_skel_export.usda`, except that one of the unused joints (index 0) has been removed from `skel:joints`, and the corresponding indices subtracted by one to compensate.  It should give the same result, but usdview shows the mesh lifting up, which it shouldn't. 
3. If you open an interpreter window, and run `from pxr import UsdSkel; UsdSkel.BakeSkinning( usdviewApi.stage.Traverse() )`, however, it looks good again.
4. Importing into maya also gives an incorrect result, though less obviously so - the mesh on frame 1 looks like it should at frame 2, and then gets further distorted when you actually move to frame 2.

### System Information (OS, Hardware)
Linux

### Package Versions
USD repo commit:
9a835a5cb9d3cc7c199b681e777ffc34f9def9b4
(pre-0.19.05)

[ExplicitJointOrdersIssue.zip](https://github.com/PixarAnimationStudios/USD/files/2953850/ExplicitJointOrdersIssue.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5134

**Comment by pmolodo** [comment]
The reproduction test now passes (as of 23.02, but I think it was fixed long before this), so I'm closing this.
