### ISSUE TITLE
[UsdMaya] [UsdSkel] Import of some skeletons is offset

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#792]
### Description of Issue

Some skeletons / skins will import offset, even though they show up positioned correctly in, ie, usdview.

This appears to be the result of turning off inheritsTransform, and positioning the mesh transform to the geomBindTransform, in `translatorSkel.cpp`, `_ConfigureSkinnedObjectTransform`.  I tried disabling these, and the skeleton lined up properly.  The comments note that it avoids a double transform, but they should not be necessary - as evidenced by the fact that inheritsTransform is not set off in the original maya scene!

### Steps to Reproduce

1. Launch maya, open the included `offset_on_import.ma`
2. Run this in a maya python script editor:
    ```python
    import maya.cmds as cmds
    cmds.loadPlugin('pxrUsd')
    cmds.select('world', r=1)
    cmds.usdExport(f='offset_on_import.usda', selection=1, exportSkels="auto", exportSkin="auto")
    ```
    If you wish to skip this step, I'm supplied a representative `offset_on_import.usda` as well.
3. View the exported `offset_on_import.usda` in usdview - the skel + mesh should line up the same as they do in maya (which is poorly, but at least in the same ballpark!)
4. Open `offset_on_import.usda` in maya. The skel will be offset from the mesh.

### System Information (OS, Hardware)

Linux (CentOS 7)

### Package Versions

USD: 9a835a5cb9d3cc7c199b681e777ffc34f9def9b4 (pre-19.05)

[offset_on_import.zip](https://github.com/PixarAnimationStudios/USD/files/2963433/offset_on_import.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5158

**Comment by pmolodo** [comment]
Closing - UsdMaya no longer part of this repo.
