### ISSUE TITLE
[UsdMaya] [UsdSkel] Some skeletons / skins crash maya on export

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#793]
### Description of Issue

Attempting to export some skeletons + skins from maya results in a crash.

This is apparently related to the `USD_isUsdSkeleton` attribute. At minimum, the export should not crash.  However, I think the use of an attribute, to denote the state of things at the time an import happened, is dangerous, and should be avoided.  The reason is that Maya is a content authoring and modification system - it should be expected that artists will import a usda, make extensive edits and changes, and then want to re-export at some point in the future.  Whatever the status of certain joints was at the time of the last import, there is no guarantee that status is still valid at the next export.

I understand the need to ensure round-trip equality (or at least similarity) in situations where changes are NOT made, and that this is complicated by the fact that a joint in maya can represent both the skeleton root AND first joint in UsdSkel... however, I think a better solution to this is to use a convention, ie, along the lines of what Jeremy Cowles proposes here:

https://groups.google.com/forum/#!searchin/usd-interest/usdskel%7Csort:date/usd-interest/4Z491ljCh3s/yPsfcVZ3AQAJ

This should be enough to ensure round-tripping correctness.

### Steps to Reproduce

1. Launch maya, open the included `crash_on_export.ma`
2. Run this in a maya python script editor:
    ```python
    import maya.cmds as cmds
    cmds.loadPlugin('pxrUsd')
    cmds.select('Goober', r=1)
    cmds.usdExport(f='crash_on_export.usda', selection=1, exportSkels="auto", exportSkin="auto")
    ```
3. Crash!

### System Information (OS, Hardware)

Linux (CentOS 7)

### Package Versions

USD: 9a835a5cb9d3cc7c199b681e777ffc34f9def9b4 (pre-19.05)

[crash_on_export.zip](https://github.com/PixarAnimationStudios/USD/files/2963436/crash_on_export.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5159

**Comment by pmolodo** [comment]
Closing - UsdMaya no longer part of this repo
