### ISSUE TITLE
[UsdMaya] [UsdSkel] Joints importing with no transform

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#794]
### Description of Issue

Importing some skeletons into maya results in all the joints having no transform relative to the skeleton root, even though they display correctly in usdview.

Note that this reproduction scene may not be correct/complete, as even usdview complains that there are no "restTransforms".  However, maya should at least use whatever fallback behavior that usdview does.

Note: This usda file was the result of a maya export, so the lack of restTransforms is another, separate, issue... however, I no longer have the original .ma it was exported from, and cannot replicate the behavior.  It may be related to the crash on export, which I am reporting as another issue.

### Steps to Reproduce

1. Open the included `joints_collapsed.usda` in usdview. Though it will complain that `size of 'restTransforms' attr [0] does not match the number of joints in the 'joints' attr [62]`, it will display correctly.
2. Open maya, load the 'pxrUsd' plugin, then open `joints_collapsed.usda`.  All joints will be collapsed, with no transform (other than the skeleton root).

### System Information (OS, Hardware)

Linux (CentOS 7)

### Package Versions

USD: 9a835a5cb9d3cc7c199b681e777ffc34f9def9b4 (pre-19.05)

[joints_collapsed.zip](https://github.com/PixarAnimationStudios/USD/files/2963440/joints_collapsed.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5160

**Comment by pmolodo** [comment]
Closing, as UsdMaya no longer in this repo.
