### ISSUE TITLE
[UsdMaya] [UsdSkel] Joint "." created on export, not handled same as BakeSkinning on import

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#795]
### Description of Issue

So, this really might be two separate issues, on export and import, but they're related, and illustrated with the same files, so I'm making them one ticket.

On export, the created USD has a reference to a joint called `"."`, but no such joint exists in the skeleton definition.  I suspect this is again related to an issue with the "USD_isUsdSkeleton" attribute, which I noted in https://github.com/PixarAnimationStudios/USD/issues/793, so the problem with the export might be the same as that issue.

On the import side, we obviously are dealing with a "corrupt" .usda at this point, but we should aim for parity with UsdSkel.BakeSkinning, which in this case (luckily?) ends up doing the right thing.

### Steps to Reproduce

1. Launch maya, open the included `bad_export_import.ma`
2. Run this in a maya python script editor:
    ```python
    import maya.cmds as cmds
    cmds.loadPlugin('pxrUsd')
    cmds.select('world', r=1)
    cmds.usdExport(f='bad_export_import.usda', selection=1, exportSkels="auto", exportSkin="auto")
    ```
3. Open the exported `bad_export_import.usda` in a text editor - you will see that the first item in `/world/char/pCylinder4.skel:joints` is `"."`, but no such joint exists in the skeleton definition at `/world/char/joint1.joints`.
4. Open `bad_export_import.usda` in usdview - note that it will initially look bad, due to https://github.com/PixarAnimationStudios/USD/issues/789.
5. Open a python interpreter in usdview, and run `from pxr import UsdSkel; UsdSkel.BakeSkinning( usdviewApi.stage.Traverse() )`
6. The mesh / skeleton should now look correct (or, at least, the same as they originally did in maya)
7. Back in maya, open `bad_export_import.usda` - it will look incorrect... both because it is offset (due to https://github.com/PixarAnimationStudios/USD/issues/792), but also because it's not handling the missing `"."` joint in the same way as UsdSkel.BakeSkinning

### System Information (OS, Hardware)

Linux (CentOS 7)

### Package Versions

USD: 9a835a5cb9d3cc7c199b681e777ffc34f9def9b4 (pre-19.05)

[bad_export_import.zip](https://github.com/PixarAnimationStudios/USD/files/2963446/bad_export_import.zip)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5161

**Comment by pmolodo** [comment]
Closing, as UsdMaya no longer in this repo.
