### ISSUE TITLE
codgenTemplate for multipleApply API schema has hardcoded entries that should be templates

### ISSUE THREAD

**Issue by ablev-dwa** [PixarAnimationStudios/USD#799]
### Description of Issue

When running usdGenSchema to generate code for a multipleApply API schema, I noticed some bugs when trying to build. I think these are just oversights in the template. I'm filing this here because due to some internal changes our ability to make a public PR is delayed for a while 🙄  and this would be an otherwise easy fix - sorry about that.

Here, this is returning UsdCollectionAPI and warning about collections, when it should return an invalid instance of the new schema class and print a more generic warning:
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usd/codegenTemplates/schemaClass.cpp#L82

These lines refer to UsdTokens, but should probably refer to {{ tokensPrefix }}Tokens:
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usd/codegenTemplates/schemaClass.cpp#L156
https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usd/codegenTemplates/schemaClass.cpp#L158

### Steps to Reproduce
1. Create a new multipleApply API schema
2. Run usdGenSchema
3. Try to compile your new schema - it will fail

### System Information (OS, Hardware)
Linux

### Package Versions
0.18.9 to 0.19.3

**Comment by spiffmon** [comment]
Yikes - we'll try to get that taken care of ASAP, Alan!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5163
