### ISSUE TITLE
VtValue::Get<Type> generates compiler warning on Windows

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#806]
### Description of Issue
When building code that calls VtValue::Get<GfMatrix3d>() (for example - any vector or matrix type produces the same result) you get the following warning:
warning C4506: no definition for inline function 'pxrInternal_v0_19__pxrReserved__::Vt_DefaultValueHolder pxrInternal_v0_19__pxrReserved__::Vt_DefaultValueFactory<pxrInternal_v0_19__pxrReserved__::GfMatrix4d>::Invoke(void)'

### Steps to Reproduce
1. Build the USD library on Windows.
2. Build any other source file outside the USD library, includeing vt/value.h, and calling:
VtValue val;
GfMatrix4d mat = val.Get<GfMatrix4d>();
You should see the compiler warning mentioned in the description. Though the code will finish compiling, linking, and run properly.

### System Information (OS, Hardware)
Windows, compiling with MSVC 15.9.5.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5175
