### ISSUE TITLE
unsafe use of relative rpath libosdGPU.3.0.5.dylib OSX

### ISSUE THREAD

**Issue by skarone** [PixarAnimationStudios/USD#81]
I compiled it for OSX, and make the links so instead of .dylib use .so
But I'm getting this error when I run:
`usdview extras/usd/tutorials/convertingLayerFormats/sphere.usda`

`Traceback (most recent call last):
  File "/usr/local/bin/usdview", line 30, in <module>
    Usdviewq.Launcher().Run()
  File "/usr/local/lib/python/pxr/Usdviewq/__init__.py", line 56, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/usr/local/lib/python/pxr/Usdviewq/__init__.py", line 150, in __LaunchProcess
    from mainWindow import MainWindow
  File "/usr/local/lib/python/pxr/Usdviewq/mainWindow.py", line 25, in <module>
    import stageView
  File "/usr/local/lib/python/pxr/Usdviewq/stageView.py", line 43, in <module>
    from pxr import UsdImaging
  File "/usr/local/lib/python/pxr/UsdImaging/__init__.py", line 24, in <module>
    from . import _usdImaging
ImportError: dlopen(/usr/local/lib/python/pxr/UsdImaging/_usdImaging.so, 2): Library not loaded: libosdGPU.3.0.5.dylib
  Referenced from: /usr/local/lib/python/pxr/UsdImaging/_usdImaging.so
  Reason: unsafe use of relative rpath libosdGPU.3.0.5.dylib in /usr/local/lib/python/pxr/UsdImaging/_usdImaging.so with restricted binary`

**Comment by CreateTheImaginable** [comment]
skarone, this might be related to Apple's System Integrity Protection (SIP) -https://support.apple.com/en-us/HT204899

I have usdview working but I ran into this problem when trying to run usdcat to work on the Mac.  I got it when accessing the usdABC.so library.  I even turned off SIP and was not able to get around it. 

Try building in a Projects directory in your home directory.  Create a Projects directory in /Users/{your user name}/ or ~ like so...  cd ~ and then mkdir Projects.

The above method is what is used by the usdbuildclub for MacOS - https://github.com/vfxpro99/usd-build-club 

I am also curious if anyone else has gotten usdcat to run on MacOS without running into this SIP problem?

**Comment by jtran56** [comment]
Filed as internal issue #138794.

**Comment by meshula** [comment]
FWIW I also build in ~/Projects, rather than patching or working around SIP restrictions.

**Comment by sunyab** [comment]
Closing out this old issue. MacOS support has matured and the build system has undergone many, many changes so it's no longer clear whether this issue still exists. If folks are still running into please file a new issue so we can reprioritize and take another look. Thanks!
