### ISSUE TITLE
i  can´t install in Ubuntu 18.04.  is ot possible? or only work in centos7 / RHEL 

### ISSUE THREAD

**Issue by hdkcreative** [PixarAnimationStudios/USD#810]
### Description of Issue
**Install Doesn't Work**
### Steps to Reproduce
1. Install Doesn't Work
### System Information (OS, Hardware)
**Ubuntu 18,04 in  Google Cloud Servers**

**Comment by jilliene** [comment]
Filed as internal issue #USD-5190

**Comment by c64kernal** [comment]
Hi @hdkcreative  -- it's possible to build USD with Ubuntu.  We'll close this out for now, but please feel free to reopen if you have more details or more questions.
