### ISSUE TITLE
Corruption in crate files if attribute is named the same as defaultPrim

### ISSUE THREAD

**Issue by aloysbaillet** [PixarAnimationStudios/USD#811]
### Description of Issue
This was a strange one to find!
Our original issue looked a lot more complex but we narrowed the problem to having an attribute named the same as the current `defaultPrim`... The file will serialize to crate without any error but loading the file back will set the attribute to be invalid. Running usdcat on the crate file then actually crashes.

### Steps to Reproduce
Create this `/tmp/bad.usda` file:
```
#usda 1.0
(
    defaultPrim = "x"
)

def "x"
{
    int x
}
``` 
run `usdcat /tmp/bad.usda -o /tmp/bad.usd`
run `usdcat /tmp/bad.usd`
crashes:
```
------------------------ 'python2.7' is dying ------------------------
python2.7 crashed. FATAL ERROR: Dereferenced an invalid SdfPropertySpec
in operator-> at line 97 of /scratch/fabricem/workspace/AL_USD/usdBase/pxr/usd/lib/sdf/declareHandles.h

The stack can be found in atoll:/var/tmp/st_python2.7.82597
done.
------------------------------------------------------------------
Aborted
```

### System Information (OS, Hardware)
CentOS-7
gcc-6.3.1

### Package Versions
USD v19.1 and v19.3

### Build Flags
All defaults with Alembic.

**Comment by gitamohr** [comment]
Wow, that's a most excellent bug! I'll look at this tomorrow.

**Comment by aloysbaillet** [comment]
Hi Alex,

Thanks, it's quite an interesting one indeed :-)
Let me know if you can repro properly, I made sure we didn't have any custom plugin loaded but there could always be something in our builds...
Also, we have a workaround (we simply renamed the attribute on our custom schema so it would be different from the typical defaultPrim, we were lucky it was a new schema), so no big urgency, but I can see how this could catch others.

Cheers,

Aloys

**Comment by gitamohr** [comment]
This was a fun one, and a bit embarrassing!  The bug is in the path encoding logic in the crate file writer.  It encodes paths by recording an index in a token table for each path element.  We use signed indexes to distinguish prim elements from property elements.  Prim elements use positive indexes, property indexes use negative.  This fails when the token index is zero.  In your repro, we decode the property path /x.x as the prim path /x/x due to this bug.  This is inconsistent with the rest of the layer data and causes the crash.  I have a fix that writes layers readable by all current software versions.  Already corrupt layers are not (and cannot be) fixed.

**Comment by aloysbaillet** [comment]
Ha! Nice one :-) Thanks Alex!

In our case, the attribute was on a nested prim, but it would still be confused I'm guessing...
FYI we had something like:
```
#usda 1.0
( defaultPrim = "bindings" )
def "bindings"{
  def "foo"{
    def "bar"{
      uniform float[2] bindings = []
  }
}
```

Do you know if this fix would this make it into USD 19.5?

**Comment by c64kernal** [comment]
Hey @aloysbaillet we talked this morning about the need to include it in 19.05, but we thought we were far along in the testing (and didn't want to introduce a new risk of instability) and that this wasn't a recent regression.  However, that's what release candidates are for.  If you feel strongly that we should include it in 19.05, we can definitely reconsider.   Alternatively, if we land it in dev very shortly after 19.05 releases, would that be okay?

**Comment by aloysbaillet** [comment]
Thanks George, as I mentioned we have a workaround and more importantly we have the knowledge of the problem, so we should OK to have that fix later.
We could probably apply the patch locally once it lands in dev if we really need to!

**Comment by c64kernal** [comment]
Sounds good, thanks Aloys!
