### ISSUE TITLE
[19.05-RC] Sdf_GetUnitIndices, private method in public header types.h

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#812]
### Description of Issue
This method (which looks private) is declared in a public header, with no SDF_API guard:
https://github.com/PixarAnimationStudios/USD/blob/v19.05-rc1/pxr/usd/lib/sdf/types.h#L289

This results in the following compiler error on Windows / Visual Studio 2015:
```
Error	LNK2001	unresolved external symbol "struct std::pair<unsigned int,unsigned int> __cdecl pxrInternal_v0_19__pxrReserved__::Sdf_GetUnitIndices(class pxrInternal_v0_19__pxrReserved__::TfEnum const &)" (?Sdf_GetUnitIndices@pxrInternal_v0_19__pxrReserved__@@YA?AU?$pair@II@std@@AEBVTfEnum@1@@Z)

```

### Package Versions
19.05-RC

**Comment by sunyab** [comment]
Hey @jcowles, did this compiler error just start happening for you in 19.05-rc1? It looks like this code has been there for a while. We should definitely remove this from the header, though.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5192

**Comment by jcowles** [comment]
Not sure, I skipped from 19.01 to 19.05
