### ISSUE TITLE
Can not set array value in dictionary from python

### ISSUE THREAD

**Issue by frenchdog** [PixarAnimationStudios/USD#813]
### Description of Issue

Setting an array of string  in the customLayerData field of a layer does not work in Python

### Steps to Reproduce
Running following code 
```
d = {'foo': ['x', 'y']}
stage.SetMetadata('customLayerData', d)
```
create an invalid data looking like this
```#usda 1.0
(

    customLayerData = {

         foo = [x, y]

    }

)
```

### System Information (OS, Hardware)
OSX and Linux

### Package Versions
v19.05

**Comment by jilliene** [comment]
Filed as internal issue #USD-5200
