### ISSUE TITLE
[UsdMaya][UsdSkel] Implement blend shape export from Maya

### ISSUE THREAD

**Issue by pstuart42** [PixarAnimationStudios/USD#816]
### Description of Issue

Add basic support for authoring blend shapes in Maya when exporting UsdSkel meshes. 

The `UsdSkelBlendShape` prim (blend shape target) holds offsets to the base mesh so the plugin should place all of the targets related to a mesh under the base mesh in the USD hierarchy. The name of the `UsdSkelBlendShape` should be the name of the target shape node in Maya.

In Maya in-betweens can be authored by specifying specific weights for each in-between target. The schema is designed to allow for the same behavior so the weights in Maya should map directly over to `inbetween` weights.  ~~However, Maya weights can be any number and USD weights are expected to be in the 0-1 range, so the weights should be normalized by the highest weight. Any weight animation would also need to be normalized.~~

On the base mesh, the names of the blend shapes used in the `skel:blendShapes` attribute can be based on the alias of the blend shape dag node `w` attribute so that the blend shape names can be customized and unified across multiple meshes. This allows for the naming of the blend shape using the Shape Editor for example.

Edit: Corrected bit about requiring weights to be normalized.

**Comment by sgustafso** [comment]
Hi! Quick correction: Usd weights are not required to be in the 0-1 range. Values outside of that range should have the same behavior as they have in Maya. We tried to match Maya's behavior in that regard specifically to simplify this translation problem, so I'm hoping we got that right. :)

**Comment by pstuart42** [comment]
Cool! I guess I assumed the weights should be normalized since special significance is given to the weight 1 inbetween. I see now that you are actually testing inbetween weights > 1 in the blend shape test usda. I updated the description.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5202

**Comment by sunyab** [comment]
Closing this issue out as development on the Maya plugin has been moved over to the Autodesk repo at https://github.com/Autodesk/maya-usd. Thanks!
