### ISSUE TITLE
[python binding]  CreateDefaultContextForAsset return None with custom resolver

### ISSUE THREAD

**Issue by frenchdog** [PixarAnimationStudios/USD#819]
### Description of Issue

I've got an asset resolver plugin that is working as expected in C++ but not in Python.
For example, when using _usdview_, the `GetResolverContext` function in _Usdviewq_ is returning _None_ when my asset path resolver is the current one in my environment.

After some investigation, I found out that I need to import the python package of my resolver first. For example putting the following code in the `__init__.py` of Usdviewq is fixing the issue.
`from myPackage import MyResolver`

Maybe there are some loading order subtlety related to boost python bindings?
I did not found out which one yet.

To make it work in any cases (with or without the custom resolver) I did the following changes in usdview sources (basically, removing the call to
_GetResolverContext_ and just calling _ConfigureResolverForAsset_)

https://github.com/frenchdog/USD/commit/438449ba2abe826f63ca695a6d48be3fdd7027fa

If you think it is OK, I can create a PR with those changes.

### Steps to Reproduce
1. register a custom resolver not installed as part of the pxr python package

### System Information (OS, Hardware)

Linux, OSX

### Package Versions

v19.3

**Comment by spiffmon** [comment]
Hi Guillaume,
   The way it's supposed to work is that if _myPackage_ has a properly laid out and built moduleDeps.cpp, then its python wrappings should be auto-loaded if any  _myPackage_  is loaded (if python has already been initialized), or else when python is initialized at some point in the future.
   Do you have a moduleDeps.cpp?  I note that we really don't talk about its need anywhere in our public documentation.  On the other hand, most studios have their own Ar plugins, and no-one else has raised this particular issue to us.

Cheers,
--spiff

**Comment by frenchdog** [comment]
Hi Spiff,

Yes, I put everything in place... I think. The python binding library got the following files:
    
- module.cpp
- moduleDeps.cpp
- wrapResolver.cpp
- wrapResolverContext.cpp
- wrapTokens.cpp

I can't share the resolver for now but could manage to put a simplified version on our public repo soon if someone is interested to give it a try.

**Comment by frenchdog** [comment]
Here is the public repo of the resolver!
https://github.com/rodeofx/rdo_replace_resolver

Let me know if I'm missing something in the python bindings.

Thanks,
Guillaume

**Comment by jilliene** [comment]
Filed as internal issue #USD-5204

**Comment by gitamohr** [comment]
Hi Guillaume -- thanks for your patience here.  The problem is that you are building 'moduleDeps.cpp' into the python bindings `_replaceResolver.so`, but it needs to be built into the main plugin `replaceResolver.so` (when python support is enabled).  This `moduleDeps.cpp` file tells the system how to find the python bindings so it can load them when needed.  I moved `moduleDeps.cpp` up to the top `add_library()` call in src/CMakeLists.txt, and that fixed the problem.
