### ISSUE TITLE
build_usd.py: file INSTALL cannot find adjustClippingUI.py (windows)

### ISSUE THREAD

**Issue by ndeebook** [PixarAnimationStudios/USD#823]
### Description of Issue
...
-- Installing: C:/_dev/usd_build/lib/python/pxr/Usdviewq/freeCamera.py
  -- Installing: C:/_dev/usd_build/lib/python/pxr/Usdviewq/freeCamera.pyc
  -- Installing: C:/_dev/usd_build/lib/python/pxr/Usdviewq/usdviewstyle.qss
  -- Installing: C:/_dev/usd_build/lib/python/pxr/Usdviewq/mainWindowUI.py
  CMake Error at pxr/usdImaging/lib/usdviewq/cmake_install.cmake:358 (file):
    file INSTALL cannot find
    "C:/_dev/usd_build/build/USD/pxr/usdImaging/lib/usdviewq/adjustClippingUI.py".
  Call Stack (most recent call first):
    pxr/usdImaging/lib/cmake_install.cmake:42 (include)
    pxr/usdImaging/cmake_install.cmake:37 (include)
    pxr/cmake_install.cmake:84 (include)
    cmake_install.cmake:49 (include)

### Steps to Reproduce
python ./build_scripts/build_usd.py C:/some_path/usd

### System Information (OS, Hardware)
Windows 10

### Package Versions
[19.05] - 2019-04-10

### Build Flags
Default

**Comment by jilliene** [comment]
Filed as internal issue #USD-5207

**Comment by ndeebook** [comment]
I was using anaconda and PySide2. I tried again with default python and PySide and it worked.

**Comment by c64kernal** [comment]
Okay thanks for the update, @ndeebook  -- closing this for now.
