### ISSUE TITLE
[usdKatana] Broken reading of PointInstancers with prototypes in a separate hierarchy

### ISSUE THREAD

**Issue by nrusch** [PixarAnimationStudios/USD#834]
### Description of Issue

The current `PointInstancer` reading code does not support prototypes that do not live under the instancer prim itself. In particular, one problematic hierarchy pattern we encountered looks like this:

```
/geo
    /point_instancer
    /prototypes
        /Looks
            /shared_proto_material
        /proto_meshes                   # `shared_proto_material` is bound here
            /proto_A                    # prototype target
            /proto_B                    # prototype target
            /proto_C                    # prototype target
``` 

Because the current instancer reading code searches for the common ancestor of the prototype prim and a (possibly inherited) material binding in order to decide where to start building the `instance source` location, the target paths in the resulting instance array are all incorrect.

We had to release a hotfix for this internally for production needs, but I am working on finalizing a pull request.

### System Information (OS, Hardware)

CentOS 7.3.1611

### Package Versions

USD 0.19.5+ (dev @ d63796726481e9dbe3549f54c6865dc0db92b99e)
Katana 3.0v7

**Comment by jilliene** [comment]
Filed as internal issue #USD-5247

**Comment by nrusch** [comment]
For reference/completeness, it seems there may be another tangentially-related issue with the PointInstancer reading code, which I've outlined here: https://github.com/PixarAnimationStudios/USD/pull/835#issuecomment-499274033

**Comment by nrusch** [comment]
I'm going to close this, since I believe the specific issue with the broken `geometry.instanceSource` paths is technically resolved.

There is still an outstanding bug with the prim hierarchy outlined in this issue, but I'm going to open a new issue for that, since the cause is somewhat more general than the prototypes being children of the `PointInstancer`, and I don't want to cause too much confusion by editing this one in place.
