### ISSUE TITLE
Installing USD error

### ISSUE THREAD

**Issue by feeling1982113** [PixarAnimationStudios/USD#836]
Description of Issue

I am trying to build USD but  didn't succeed。

 huanghaibindeiMac:USD huanghaibin$ python /Users/huanghaibin/USD/build_scripts/build_usd.py --maya /Users/huanghaibin/opt/local/USD --maya-location /Volumes/work/Applications/Autodesk/maya2019 --build /Users/huanghaibin/opt/local/USD/build

Building with settings:
  USD source directory          /Users/huanghaibin/USD
  USD install directory         /Users/huanghaibin/opt/local/USD
  3rd-party source directory    /Users/huanghaibin/opt/local/USD/src
  3rd-party install directory   /Users/huanghaibin/opt/local/USD
  Build directory               /Users/huanghaibin/opt/local/USD/build
  CMake generator               Default
  Downloader                    curl

  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             Off
      OpenImageIO support:      Off 
      OpenColorIO support:      Off 
    UsdImaging                  On
      usdview:                  On
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    MaterialX Plugin            Off
    Maya Plugin                 On
    Katana Plugin               Off
    Houdini Plugin              Off

  Dependencies                  None
STATUS: Installing USD...

[ 39%] Linking CXX shared library libtf.dylib
Undefined symbols for architecture x86_64:
.......................................................
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pxr/base/lib/tf/libtf.dylib] Error 1
make[1]: *** [pxr/base/lib/tf/CMakeFiles/tf.dir/all] Error 2
make: *** [all] Error 2

ERROR: Failed to run 'cmake --build . --config Release --target install -- -j4'
See /Users/huanghaibin/opt/local/USD/build/USD/log.txt for more details.

System Information (OS, Hardware)

MacOS Mojave 10.14.4.

Package Versions

Build Flags

USD huanghaibin$ python /Users/huanghaibin/USD/build_scripts/build_usd.py --maya /Users/huanghaibin/opt/local/USD --maya-location /Volumes/work/Applications/Autodesk/maya2019 --build /Users/huanghaibin/opt/local/USD/build
[log.txt](https://github.com/PixarAnimationStudios/USD/files/3124553/log.txt)
Thank you.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5248

**Comment by feeling1982113** [comment]
I saw the help documentation saying that compiling the Maya version requires the use of Maya's own python. I later changed it to Maya's own python, and also modified the environment variables but still got the same error.

/Volumes/work/Applications/Autodesk/maya2019/Maya.app/Contents/bin/mayapy /Users/huanghaibin/USD/build_scripts/build_usd.py --maya /Users/huanghaibin/opt/local/USD/ --no- Usdview --maya-location /Volumes/work/Applications/Autodesk/maya2019 --build /Users/huanghaibin/opt/local/USD/build

[ 32%] Linking CXX shared library libtf.dylib
Undefined symbols for architecture x86_64:

Ld: symbol(s) not found for architecture x86_64
Clang: error: linker command failed with exit code 1 (use -v to see invocation)
Make[2]: *** [pxr/base/lib/tf/libtf.dylib] Error 1
Make[1]: *** [pxr/base/lib/tf/CMakeFiles/tf.dir/all] Error 2
Make: *** [all] Error 2

I deleted many python versions in the system, only the default version of the system.
I tried to find these files not found.
Who can give a good suggestion or I should not compile with maya2019.
Thank you.

**Comment by feeling1982113** [comment]
I think it may be the reason for boost, I installed multiple versions and multiple places caused confusion, I am doing new tests, thank you.

**Comment by feeling1982113** [comment]
Thank you, it has been compiled successfully.

**Comment by c64kernal** [comment]
Glad you got it resolved @feeling1982113!

**Comment by SimonForgot** [comment]
Do you remember how you solved this problem? I got the same problem as you

**Comment by avalean07** [comment]
I got the same issue, do you have any solution?

Solution: update cmake

This is how I did it: https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line
