### ISSUE TITLE
Crash opening this file with nested point instancers in usdview

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#838]
### Description of Issue
There is a crash in the UsdImagingDelegate when loading the attached usd file, which consists of a cube, which is point instanced, and that point instancer is point instanced, and that point instancer is point instanced.
Here is a (partial) stack trace: 
[nested_instancer_crash.txt](https://github.com/PixarAnimationStudios/USD/files/3129621/nested_instancer_crash.txt)

### Steps to Reproduce
1. Load the attached file in usdview
[crashing_point_instancers.zip](https://github.com/PixarAnimationStudios/USD/files/3129604/crashing_point_instancers.zip)

### System Information (OS, Hardware)
Windows

### Package Versions
USD 19.05

**Comment by jilliene** [comment]
Filed as internal issue #USD-5249
