### ISSUE TITLE
Faled to run usdview

### ISSUE THREAD

**Issue by artofka** [PixarAnimationStudios/USD#842]
Usdview crash when start. Error: 
File "..\USD\lib\python\pxr\Ar\\__init__.py", line 24, in <module>
    import _ar
ImportError: DLL load failed: =x (some random utf-8 symvols)

Windows 7, Python 2.7

**Comment by c64kernal** [comment]
Hi @artofka  -- the most probable cause is missing directories in your PATH -- have you tried setting up your environment as described here: http://graphics.pixar.com/usd/docs/USD-Tutorials.html.  There are also more specific instructions based on your build location that are printed after your build_usd.py command succeeds.

**Comment by artofka** [comment]
Thanks for you reply. Yes, I have setted up env variables. My USD directory in D:\USD

**Comment by jilliene** [comment]
Filed as internal issue #USD-5252

**Comment by sunyab** [comment]
Closing old issue, please file a new one if you're still encountering issues. Thanks!
