### ISSUE TITLE
Crash in UsdImaging when instancing setup is changed

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#847]
### Description of Issue
When applying a certain transformation of a stage involving native instancing, there is a crash in usdImaging/instancerWrapper.cpp.

### Steps to Reproduce
1. Unzip the files in the attached archive: 
[instance_update_crash.zip](https://github.com/PixarAnimationStudios/USD/files/3167050/instance_update_crash.zip)
2. Open usdview pointed at "first.usda".
3. In the Interpreter window, run:
l = Sdf.Layer.FindOrOpen('./second.usda')
usdviewApi.stage.GetRootLayer().TransferContent(l)
4. usdview will crash at this point (you may need to do something to force the viewport to redraw). The problem is that in UsdImagingInstanceAdapter::_Populate, the call to _GetPrim around line 130 (const TfToken& instanceDrawMode = GetModelDrawMode(_GetPrim(_GetPrimPathFromInstancerChain(instancerChain)));) returns an invalid UsdPrim.

### System Information (OS, Hardware)
Windows 10.

### Package Versions
USD 19.05

**Comment by spiffmon** [comment]
Confirming I can repro easily.

@marktucker , I noticed none of the layers in your repro contained _upAxis_ metadata.  If you could please ensure all "potentially root-level" layers call
```
UsdGeomSetStageUpAxis(stage, UsdGeomGetFallbackUpAxis())
```
or the layer-level equivalent (layer->GetPseudoRoot()->SetInfo(UsdGeomTokens->upAxis, ...))

would be much appreciated.

Thanks!
--spiff

**Comment by jtran56** [comment]
Filed as internal issue #USD-5284.
