### ISSUE TITLE
testusdviewSkinning image results differ from expected

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#850]
### Description of Issue
The testusdviewSkinning test creates images, which, when compared by eye, differ a fair amount from the "expected" ones in the repo.

### Steps to Reproduce
1. build usd with tests
2. cd to cmake build dir
3. `ctest --output-on-failure -V -R testusdviewSkinning`
4. Should appear to work, but...
5. Find the most recently created temp test dir (on CentOS, I do:  `ll -lad /tmp/tmp*`)
6. Compare the images in the temp dir to the reference ones in the src dir: `pxr/usdImaging/bin/testusdview/testenv/testUsdviewSkinning/`

### System Information (OS, Hardware)
CentOS 7

### Package Versions
USD-0.19.07 (pre-release, commit d63796726481e9dbe3549f54c6865dc0db92b99e)

**Comment by elrond79** [comment]
So, on closer examination, the differences I'm seeing seem to be due to my camera snapshots being taking looking down the z-axis, while the baseline images are looking down the y-axis.  So that's probably an issue that needs be addressed - likely just some user configuration setting that needs to be set / overridden.

However, Spiff also reported that there were small pose differences (and I'm assuming his camera axis was the same):

https://groups.google.com/d/msg/usd-interest/mK10MSz_Kfo/0LMvYSg6AgAJ

**Comment by spiffmon** [comment]
You indeed found another problem, @elrond79 - the source arm.usda file should contain _upAxis = "Z"_ metadata in it, which is why you're seeing flipping compared to the baselines.  We'll fix that, too!

**Comment by jtran56** [comment]
Filed as internal issue #USD-5286.

**Comment by c64kernal** [comment]
@spiffmon checked in a fix for this that'll end up on github soon!  It was in service of getting PR #832 checked in.
