### ISSUE TITLE
inline _GetNamespacedPropertyName in Codegen template for Multiple Apply Schema should be a static inline?

### ISSUE THREAD

**Issue by swahtz** [PixarAnimationStudios/USD#851]
It seems that the template for the _GetNamespacedPropertyName function declaration that gets built for MultipleAppy API Schemas has the `inline` specifier:

https://github.com/PixarAnimationStudios/USD/blob/38c70fb869c01228f82fd844a8c420860b5131c1/pxr/usd/lib/usd/codegenTemplates/schemaClass.cpp#L225

Without this being inline function being specified with `static` storage, we're seeing an issue where when we link multiple MultipleApply API Schemas compiled in their own compilation units and linked in one shared library, we only get one implementation of the _GetNamespacedPropertyName function being called (thus giving every MultipleApply API Schema in that shared library the same namespace prefix value).

Should _GetNamespacedPropertyName in fact be `static inline`?

**Comment by jilliene** [comment]
Filed as internal issue #USD-5308

**Comment by sunyab** [comment]
Yes, this is definitely a bug and we're looking at a fix now. Thanks for the report!
