### ISSUE TITLE
Incorrect behaviour of translucent blending

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#852]
### Description of Issue
At the moment translucent blending in dev doesn't behave as expected. This is due to an unusual blending logic in oitResolveImageShader and an incorrect OpenGL state setting.

More details in the comments below.

### Steps to Reproduce
1, either hardcode the material tag to translucent for the preview surface (in hydraMaterialAdapter.cpp) or merge in #846 and set PXR_PREVIEW_SURFACE_TRANSLUCENT_TAG to translucent.
2, open any of the attached files.

**Comment by sirpalee** [comment]
The following example shows transparent planes over a plane, with opacity varying from left to right as 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0 and the last plane has an opaque material (opacity is one, and non connected, meaning it doesn't have the translucent material tag).

How it looks with the current dev branch:
![opacity_original](https://user-images.githubusercontent.com/582376/58449491-179bd980-814f-11e9-9f71-26f85a7498c2.png)

After making some changes to the OpenGL state and blending logic (see details below):
![opacity_updated](https://user-images.githubusercontent.com/582376/58449784-8a0cb980-814f-11e9-8d39-f7d59a5b9b51.png)

Reference render using Arnold and a uniform white skydome light:
![opacity_arnold](https://user-images.githubusercontent.com/582376/58449482-0fdc3500-814f-11e9-977d-b505dbdfa833.png)

As you can see, there isn't a smooth interpolation between different opacity values in the original code, and translucent 1.0 doesn't create the same look as non-translucent, opaque.

**Comment by sirpalee** [comment]
The next example shows two, white, planes with 0.5 opacity and a red plane behind them, also with 0.5 opacity.

Original:
![opacity_overlap_original](https://user-images.githubusercontent.com/582376/58449879-cd672800-814f-11e9-8eaa-d44f6bd9ac13.png)

Updated:
![opacity_overlap_updated](https://user-images.githubusercontent.com/582376/58449887-d2c47280-814f-11e9-8226-f2179ffaeba0.png)

Arnold reference:
![opacity_overlap_arnold](https://user-images.githubusercontent.com/582376/58449890-d952ea00-814f-11e9-89c7-322f93305bc7.png)

As you can see, in the original example the red plane is completely hidden.

**Comment by sirpalee** [comment]
Here is a zip file with all the images and source usda files. (I wasn't able to attach usda directly)
[translucency.zip](https://github.com/PixarAnimationStudios/USD/files/3225600/translucency.zip)

**Comment by sirpalee** [comment]
I made these changes to the codebase:

```
diff --git a/pxr/imaging/lib/hdx/oitResolveTask.cpp b/pxr/imaging/lib/hdx/oitResolveTask.cpp
index 36cd92d17fb66ac23c122e7e4bb696cd29d93aab..292c28330e36cbaa0da349cf809f51d83f4b8774 100644
--- a/pxr/imaging/lib/hdx/oitResolveTask.cpp
+++ b/pxr/imaging/lib/hdx/oitResolveTask.cpp
@@ -90,7 +90,7 @@ HdxOitResolveTask::Prepare(HdTaskContext* ctx,
         _renderPassState->SetBlend(
             HdBlendOp::HdBlendOpAdd,
             HdBlendFactor::HdBlendFactorOne,
-            HdBlendFactor::HdBlendFactorOneMinusSrc1Alpha,
+            HdBlendFactor::HdBlendFactorOneMinusSrcAlpha,
             HdBlendOp::HdBlendOpAdd,
             HdBlendFactor::HdBlendFactorOne,
             HdBlendFactor::HdBlendFactorOne);
diff --git a/pxr/imaging/lib/hdx/shaders/oitResolveImageShader.glslfx b/pxr/imaging/lib/hdx/shaders/oitResolveImageShader.glslfx
index abbd5b5db64ca4c0620eb31e31c9b4ffb8a87c82..5681cf6ad14374e686218782cd70ec082199e4e3 100644
--- a/pxr/imaging/lib/hdx/shaders/oitResolveImageShader.glslfx
+++ b/pxr/imaging/lib/hdx/shaders/oitResolveImageShader.glslfx
@@ -72,12 +72,13 @@ vec4 imageShader(vec2 uv)
     int depth = 0;
     vec4 colorAccum = vec4(0,0,0,0);
     while (depth < numDepths) {
-        vec3 cb = sortedColor[depth].rgb * sortedColor[depth].a; 
-        colorAccum.rgb = colorAccum.rgb + cb * (1 - colorAccum.a);
-        colorAccum.a = colorAccum.a + sortedColor[depth].a; 
+        float ca = sortedColor[depth].a * (1 - colorAccum.a);
+        vec3 cb = sortedColor[depth].rgb;
+        colorAccum.rgb = colorAccum.rgb + cb * ca;
+        colorAccum.a = colorAccum.a + ca;
 
         colorAccum = clamp(colorAccum, vec4(0), vec4(1));
 
         depth += 1; 
     }
```

I think the use of HdBlendFactorOneMinusSrc1Alpha (which blends using the dst color, not the dst alpha) instead of HdBlendFactorOneMinusSrcAlpha is a typo.  The other change is multiplying each translucent fragment with the previous values before, creating a similar look like before. Also, the alpha shouldn't be directly added to the accumulated alpha, or the translucency blending stops once the fragment alphas accumulated to 1 (this is the reason why the red plane is missing from the second set of examples). Note, this is just a quick change to get a similar look to Arnold.

**Comment by poljere** [comment]
This is really helpful, many thanks. We will look into this as soon as possible.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5309

**Comment by lumonix** [comment]
Thanks @sirpalee!

The blendmode is definitely a typo.

For the blending math changes, I believe your proposed changes are inline with what we had concluded, but I'm still digging into it a little. 

We have some inconsistencies in our use of pre-multiplied alpha that we need to clean-up so that OIT and other shaders (like PreviewSurface and our internal shaders) are consistent in what they expect for input and what they produce as output.

(For that reason it may take a little longer to implement the fixes your propose, but they are coming)

Thanks again!
