### ISSUE TITLE
Cant build Katana plugin missing variables

### ISSUE THREAD

**Issue by Bradley-Webster** [PixarAnimationStudios/USD#854]
### Description of Issue
I cannot seem to install Katana through the Build Script available with the --katana option.
I have tried manually setting the environment variables but still get no change.

Does the Log I have provided display any tests I can do?

If I cannot install with the --katana option, how would I setup the cmake example?

### Steps to Reproduce
1. Build USD through the Build script with the --katana option

### System Information (OS, Hardware)
CentOS7.4

### Package Versions
latest

### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/USD/files/3231443/log.txt)

--katana  --katana-api-location=$USD_GITLOCATION_DIR\third_party\katana

**Comment by jilliene** [comment]
Filed as internal issue #USD-5310

**Comment by sunyab** [comment]
Hi @Bradley-Webster, the build script assumes you have Katana installed already; the --katana-api-location parameter should be the path to your Katana installation. Hope that helps!

**Comment by Bradley-Webster** [comment]
Hi Sunyab,

I already had Katana installed, which I already tried.

I managed to get it built on another PC, transferring the files and setting up the environment variables seemed to resolve the issues.
