### ISSUE TITLE
Only BlendShape pointIndices use uint arrays?

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/USD#858]
### Description of Issue
In the `BlendShape` schema the `pointIndices` attribute is using a _uint_ array:

```
class BlendShape "BlendShape" (//...)
{
    // ...
    uniform uint[] pointIndices (
    // ...
}
``` 
(see https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usdSkel/schema.usda#L282)

All other indices attributes like `faceVertexIndices` and `creaseIndices` are using *int* arrays. Is there are reason for that? 

### Package Versions
19.05

**Comment by jilliene** [comment]
Filed as internal issue #USD-5341
