### ISSUE TITLE
Prman-plugin: oslc found in path, not used

### ISSUE THREAD

**Issue by simpassi** [PixarAnimationStudios/USD#866]
### Description of Issue
When compiling the latest dev branch, even if oslc is in PATH, it's not used, instead a fixed path to /bin/oslc is being attempted and the build fails.

### Steps to Reproduce
1. Have oslc available in path (e.g. through RenderManProServer-22.5), but not in /bin/oslc
2. Run build-usd.py with the --prman flag

To mitigate for now, we've just created a symbolic link to RmpS-22.5/bin/oslc from /bin/oslc

### System Information (OS, Hardware)
CentOS 7.4.1708

### Package Versions
USD from github, @3cca93e
RenderManProServer-22.5
RH devtoolset-6
Python 2.7.15

### Build Flags
The build line we use is:
build-usd.py --python --alembic --hdf5 --openimageio --materialx --prman $TARGET_DIR

**Comment by sunyab** [comment]
Hi @simpassi, does this work if you pass in `--prman-location <path to RenderManProServer>`?

**Comment by simpassi** [comment]
It does work if i pass it. Somehow I overlooked there is an option in the build script for that. Looks like the auto-discovery doesn't go all the way... Thanks!
