### ISSUE TITLE
usdMaya: pfx-to-basiscurve export

### ISSUE THREAD

**Issue by simpassi** [PixarAnimationStudios/USD#867]
### Description of Issue
Currently the only way to get hair curves from a Maya scene to a USD container, aside from using custom exporter plug-ins, is to convert them to geometry, thus losing the curve properties.

It would be much nicer if pfx hair could be turned into a prim with indexed basiscurves with varying parameters for color and width.

We have a way of doing this by first exporting into a RIB sequence using the RenderMan plug-in, then converting all the curve information in the RIB files into a time-sliced group of USD files, but that requires a few steps and is not optimal.

### Steps to Reproduce
1. Create a hair system in Maya (nHair or similar) that creates a paint effect
2. Export to USD
3. All curves are missing

### System Information (OS, Hardware)
CentOS 7.4

### Package Versions
Maya 2018.5
USD and usdMaya 19.05

### Build Flags
any

**Comment by jilliene** [comment]
Filed as internal issue #USD-5372
