### ISSUE TITLE
Windows Build Can't Open USDC File

### ISSUE THREAD

**Issue by zhoub** [PixarAnimationStudios/USD#87]
Hi,

I found a serious low level issue about CrateFile, that's from the C++ memory layout and object persistent for cross-platform IO.

There is a hack class named.

``` c++
// Tag indicating trivially copyable types, hack since gcc doesn't yet implement
// is_trivially_copyable correctly.
struct _BitwiseReadWrite {};
```

Then all the internal structure will inherent from this class, but the code doesn't consider the alignment on different compilers. After my test, the GCC on Linux will write 16bytes aligned structure but the padded bytes starts from the head, but MSVC might don't follow the same rule.

Here are some structures from my personal tiny test program in a reversed engineering way to figure out where is the problem.

``` c++
struct UsdcFileField
{
    uint32_t mReserved; // Padded by GCC
    uint32_t mTokenIndex;
    uint64_t mValueRep;
};

struct UsdcPathItemHeader
{
    uint32_t mReserved; // Padded by GCC
    uint32_t mIndex;
    uint32_t mElementTokenIndex;
    uint8_t  mBits;
};

struct UsdcSpec
{
    uint32_t mReserved; // Padded by GCC
    uint32_t mPathIndex;
    uint32_t mFieldSetIndex;
    int32_t  mSdfSpecType;
};
```

Also, I suggest to add the unit test for the USDA and USDC file, which makes more sense to cover this kind of issue.

Thank you very much.

**Comment by sunyab** [comment]
Hi @zhoub, I believe commit 753f62b0 should address this problem.

**Comment by jtran56** [comment]
Filed as internal issue #139103.

**Comment by c64kernal** [comment]
Bo, if you can verify with a build that has the fix Sunya mentioned to make sure this isn't another issue, that'd be greatly appreciated, and if it is fixed, we can close this out.  Thanks!

**Comment by c64kernal** [comment]
Going to close this out for now.  Please file a new issue with repro steps if you encounter another similar issue.
