### ISSUE TITLE
usdMaya: "crate bootstrap section corrupt" when opening Kitchen_set.usd

### ISSUE THREAD

**Issue by elrond79** [PixarAnimationStudios/USD#870]
### Description of Issue

I get a a wall of errors, all saying the same thing when I try to open the `Kitchen_set.usd` scene using a maya proxy shape:

```
Runtime Error (secondary thread): in _ReadBootStrap at line 3014 of /mnt/Samsung/projects/rez-build/usd/dev/src/pxr/usd/lib/usd/crateFile.cpp -- Usd crate bootstrap section corrupt
```

It opens fine in usdview; also, even though it spits out these ominous errors, it actually seems to work just fine...

### Steps to Reproduce
1. Launch Maya
2. Paste the following in the python script editor, replace `/path/to/Kitchen_set.usd` with the appropriate location, then run:

```
import maya.cmds as cmds

cmds.loadPlugin("pxrUsd")
loadPlug("pxrUsd")
cmds.file(new=1, f=1)
proxyShape = cmds.createNode('pxrUsdProxyShape')
cmds.setAttr('{}.filePath'.format(proxyShape), '/path/to/Kitchen_set.usd`',
    type="string")
```

### System Information (OS, Hardware)
Linux / CentOS 7

### Package Versions
usd-dev (19.07, 3cca93e648d3fd05bc4ed0cd013f944995b34f81)

**Comment by spiffmon** [comment]
Hi @elrond79 !  We're having trouble reproducing this... any chance this is specific to a gcc 6 build (which we're not really setup to do interactive testing on, yet) ?

**Comment by elrond79** [comment]
That's possible... let me check.

**Comment by gitamohr** [comment]
Do you have any TF_DEBUG flags on?  The usdc 'CanRead' implementation will attempt to read the bootstrap section and if an error is issued, it swallows the issued error and returns false.  Some TF_DEBUG flags will cause errors to be printed when _issued_ though, so you may see some errors that might be expected and handled, like this one.

**Comment by gitamohr** [comment]
For example, we try to open every '.usd' file as a binary file first, and if that fails then we try to open it as an ascii file, so you should see this error be _issued_ (but ultimately handled and not propagated) every time we open a .usd file that's ascii.

**Comment by elrond79** [comment]
Ah! Yes, that was it!
I was using `TF_DEBUG=TF_LOG_STACK_TRACE_ON_ERROR`, which was what was triggering this.
Would be nice to have a way to suppress these stack traces for expected errors.  Maybe something similar to TfErrorMark, or even an optional arg to it?
That's a separate issue, though (and much lower priority), so I'll close this issue for now.  Thanks!

**Comment by gitamohr** [comment]
Cool, I'm glad it's just that.  Also I agree -- what I'd like is for us to _capture_ the stack trace when errors are issued with that flag on, but not log them until the time when the error would otherwise have been reported unhandled.
