### ISSUE TITLE
Usdview error using 19.07-rc1 on windows

### ISSUE THREAD

**Issue by 1xinghuan** [PixarAnimationStudios/USD#877]
I build the USD 19.07-rc1 on windows and there's GL error when I use usdview to open a stage:

```
Warning: in _PrepareOitBuffers at line 173 of F:\Temp\USD\usd_1907\usd\src\pxr\i
maging\lib\hdx\oitRenderTask.cpp -- glClearNamedBufferData missing for OIT (old
glew?)
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_19__pxrReserved__::GlfPostPendingGLErrors' at l
ine 80 in file F:\Temp\USD\usd_1907\usd\src\pxr\imaging\lib\glf\diagnostic.cpp :
 'GL error: invalid operation, reported from bool __cdecl pxrInternal_v0_19__pxr
Reserved__::HdxColorCorrectionTask::_CreateBufferResources(void)'
ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_19__pxrReserved__::GlfPostPendingGLErrors' at l
ine 80 in file F:\Temp\USD\usd_1907\usd\src\pxr\imaging\lib\glf\diagnostic.cpp :
 'GL error: invalid operation, reported from bool __cdecl pxrInternal_v0_19__pxr
Reserved__::HdxColorCorrectionTask::_CreateFramebufferResources(unsigned int *)'

ERROR: Usdview encountered an error while rendering.
        Error in 'pxrInternal_v0_19__pxrReserved__::GlfPostPendingGLErrors' at l
ine 80 in file F:\Temp\USD\usd_1907\usd\src\pxr\imaging\lib\glf\diagnostic.cpp :
 'GL error: invalid operation, reported from bool __cdecl pxrInternal_v0_19__pxr
Reserved__::HdxColorCorrectionTask::_CreateFramebufferResources(unsigned int *)'
```

I also built 19.05 and it's ok.

### System Information (OS, Hardware)
Windows

### Package Versions
19.07-rc1

### Build Flags
python build_usd.py --tests --docs --openimageio --opencolorio --embree --embree-location=%embree_dir% --alembic --prman --prman-location=%prman_dir% %USD_ROOT%

**Comment by c64kernal** [comment]
Hi @1xinghuan  -- thanks so much for reporting this.  Can you let us know what hardware you're running?  We're having a hard time reproducing this.  Also, if you set the environment variable 'HDX_ENABLE_OIT' to 0 before starting usdview, does that avoid the problem?

**Comment by jilliene** [comment]
Filed as internal issue #USD-5375

**Comment by 1xinghuan** [comment]
@c64kernal Here's my hardware information:
CPU: Intel Core i7-4810MQ
Display Device: AMD FirePro M5100
Memory: 16GB

I set the 'HDX_ENABLE_OIT' to 0 and the warning disappear but error still exist. And I already use the GLEW 2.0.0 but why it can't find 'glClearNamedBufferData'.

**Comment by c64kernal** [comment]
Thanks for the information @1xinghuan -- we need to get this fixed up, but my guess is that your drivers don't support OpenGL 4.5 (maybe a driver upgrade could help?).  At any rate, we should be at least checking the context caps before invoking such API.  We'll work on a fix, thanks so much for reporting.

**Comment by lumonix** [comment]
We should indeed add a check for context caps, but is that the issue here?
OIT issues a warning that the desired GL api is not available, which is harmless.
Using HDX_ENABLE_OIT=0 gets rid of the warning as discovered.

The actual error seems elsewhere and it looks like the GLF_POST_PENDING_GL_ERRORS in the color correction task is the first thing that picks up on the error.

(That doesn't fully rule out OIT, but it may not be OIT that is the cause)

**Comment by 1xinghuan** [comment]
@c64kernal I checked my driver and it only support OpenGL 4.1... So is that the reason? 
Btw, I also have a similar error in katana3.1:

```
[WARN plugins.HydraViewer.LoggerDelegate]: ..\pxr\imaging\lib\hd\renderContextCa
ps.cpp: _LoadCaps: 267: HD_ENABLE_GPU_COMPUTE can't be enabled (OpenGL 4.3 requi
red).

## GL_ERROR ##    GL_INVALID_OPERATION at t:\apps\katana\plugins\viewerplugins\b
alllocationtype\objects\win-64-x86-release-14.0.24210-dynamic\fnkatcopy-a4a9d2b\
fnglshaderprogram.cpp:292  Foundry::Katana::ViewerUtils::GLShaderProgram::setUni
form    ---   ProjectionMatrix

[ERROR plugins.HydraViewer.LoggerDelegate]: ..\pxr\imaging\lib\glf\diagnostic.cp
p: GlfPostPendingGLErrors: 73: GL error: invalid operation, reported from bool _
_cdecl pxrInternal_v0_8__pxrReserved__::HdxIntersector::Query(const struct pxrIn
ternal_v0_8__pxrReserved__::HdxIntersector::Params &,const class pxrInternal_v0_
8__pxrReserved__::HdRprimCollection &,class pxrInternal_v0_8__pxrReserved__::HdE
ngine *,class pxrInternal_v0_8__pxrReserved__::HdxIntersector::Result *)
```

I have never thought it's because of my driver, because katana 3.0 is ok and it's also requiring opengl 4.3 in release_notes.

I will change another driver and try.

**Comment by 1xinghuan** [comment]
@c64kernal I changed a nvidia graphics card then everything is ok. So maybe we can close this issue.
Thanks for reminding.

**Comment by c64kernal** [comment]
Thanks for the update @1xinghuan -- we definitely still want to fix this for others who don't necessarily have access to newer hardware, at least it shouldn't crash for them.  Also, it looks like PR #884 might already address this thanks to @sirpalee

**Comment by c64kernal** [comment]
We've done what we think we can about this issue (the fixes should be in the dev branch) however, I still don't think we've really gotten to the bottom of what was going wrong for you, but we don't have a repro.  So we'll close for now and we can revisit if we can find a repro.

**Comment by boycey10802002** [comment]
I will give that a try when I switch back to 19.07. Thank you.
