### ISSUE TITLE
Crash when unmuting layer

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#883]
### Description of Issue
It is possible to cause a crash when unmuting a layer on a stage, generating the error message "attempted member lookup on NULL TfWeakPtr<PcpLayerStack>".

### Steps to Reproduce
1. Unzip the attached set of simple usda files. The content is not important, but the composition hierarchy does seem relevant (root layer with a sublayer that payloads a layer with a sublayer).
[unmute_crash.zip](https://github.com/PixarAnimationStudios/USD/files/3308865/unmute_crash.zip)
2. Run python in the directory containing the unzipped usda files. Run the following python code:
from pxr import Usd
import os
s = Usd.Stage.CreateInMemory()
r = s.GetRootLayer()
r.subLayerPaths.append('d.usda')
s2 = Usd.Stage.CreateInMemory()
r2 = s2.GetRootLayer()
r2.subLayerPaths.append('d.usda')
s.MuteAndUnmuteLayers([os.getcwd() + '/c.usda'], [])
s2.MuteAndUnmuteLayers([os.getcwd() + '/c.usda'], [])
r.subLayerPaths.clear()
r.subLayerPaths.append('e.usda')
s.MuteAndUnmuteLayers([], [os.getcwd() + '/c.usda'])
3. Executing the last line should generate the message: "attempted member lookup on NULL TfWeakPtr<PcpLayerStack>", followed by a crash.

### Package Versions
19.07

**Comment by jilliene** [comment]
Filed as internal issue #USD-5386
