### ISSUE TITLE
Problem with per-instance shading variation in Hydra GL with primvar named "diffuseColor"

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#887]
### Description of Issue
In general per-instance shading variation works with HydraGL. However if the variation is being driven by a primvar named diffuseColor (which matches the preview surface material parameter the primvar is overriding), the per-instance variation stops working.

### Steps to Reproduce
1. Load the attached USD files into usdview. 
[hydragl_bad_primvar_name.zip](https://github.com/PixarAnimationStudios/USD/files/3333034/hydragl_bad_primvar_name.zip)

2. The iv_good.usda file shows per-instance shading variation in Hydra GL. The iv_bad.usda file does not show per-instance shading variation in Hydra GL. The only different between the two files is that in the first, the primvar is named "basecolor, and in the second it is named "diffuseColor".
Both files look fine using hdprman to render.
Both files look fine if the instanceable flag is removed from all the referencing prims.

### Package Versions
dev branch from June 26th (f625663a5e4f9dd57f92d3ea87b33cae95742fc2)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5398
