### ISSUE TITLE
Missing library in PxrUsdIn plugin

### ISSUE THREAD

**Issue by ChrisKing123** [PixarAnimationStudios/USD#889]
I was attempting to write a plugin for the pxrUsdIn node.
PxrUsdIn::cook was crashing whenever I registered my plugin.
Further investigation found that FnAttribute::_attrSuite was not getting initialized.
The PxrUsdIn plugin seemed to be missing the Foundry::Katana::Bootstrap function that is required for Katana to properly initialize plugins.
Adding katanaAttrfncApi to the CMakeLists.txt in the pxrUsdIn directory fixes this.

Thanks,
Chris

P.S. Stevel has some state on this. He led me to the solution.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5401

**Comment by ChrisKing123** [comment]
Thanks Jilliene
