### ISSUE TITLE
Vt fails to build on OSX, cf. issue #28

### ISSUE THREAD

**Issue by asluk** [PixarAnimationStudios/USD#89]
After https://github.com/PixarAnimationStudios/USD/commit/f5d73aa1e1b61e0a16e8d2db8663db292760fbf1#diff-a3c1820c344553f04552258f508b35a1 , issue #28 now manifests when building Vt.

A workaround is to move the pyLock.h include in vt/value.h to come after pyObjWrapper.h , once again violating coding conventions as in the fix for #28 , but maybe it's better to require python 2.7.13+ for OSX so that we don't have to inject workarounds every time this manifests.

I'll upgrade my local python to 2.7.13 for now and verify that everything builds properly.
---

In file included from /Users/asluk/Desktop/bin/usd-dev/USD/pxr/base/lib/vt/dictionary.cpp:24:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/vt/dictionary.h:31:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/vt/keyValue.h:27:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/vt/value.h:32:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/tf/pyObjWrapper.h:27:
In file included from /usr/local/include/boost/functional/hash.hpp:6:
In file included from /usr/local/include/boost/functional/hash/hash.hpp:558:
In file included from /usr/local/include/boost/functional/hash/extensions.hpp:22:
In file included from /usr/local/include/boost/detail/container_fwd.hpp:98:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/complex:247:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:138:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:468:15: error: C++ requires a type specifier for all declarations
    char_type toupper(char_type __c) const
              ^
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/pxr/base/lib/vt/dictionary.cpp:24:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/vt/dictionary.h:31:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/vt/keyValue.h:27:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/vt/value.h:31:
In file included from /Users/asluk/Desktop/bin/usd-dev/USD/build/include/pxr/base/tf/pyLock.h:27:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:58:
/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pyport.h:731:29: note: expanded from macro 'toupper'
# define toupper(c) towupper(btowc(c))

**Comment by asluk** [comment]
Ah, I see python 2.7.13 has not been released, so we'd have to use the workaround to keep the OSX build going. I'll make a pull request.

**Comment by jtran56** [comment]
Filed as internal issue #139262.

**Comment by meshula** [comment]
macOS currently ships with 2.7.10, so this workaround is a good solution from my perspective.

**Comment by asluk** [comment]
Verified on latest cut of dev.
