### ISSUE TITLE
Maya Error: Error: line 0: Cannot find procedure "usdTranslatorImport".

### ISSUE THREAD

**Issue by emilche** [PixarAnimationStudios/USD#891]
### Description of Issue
When importing a usd file to maya I get the following command error: "Error: line 0: Cannot find procedure "usdTranslatorImport"." I am still able to import the usd file but it gets flipped. Maya has the setting Y-up. And it does not always import correctly. (some missing textures and never imports animations.) I am not able to change any settings while trying to import.

and when exporting i am getting:
// Error: line 0: Cannot find procedure "usdTranslatorExport". // 
But I am still able to export.

This is my mayaenv:
MAYA_PLUG_IN_PATH = C:/Program Files/USD/third_party/maya/plugin
MAYA_SCRIPT_PATH = C:/Program Files/USD/third_party/maya/plugin/pxrUsdPreviewSurface/resources:C:/Program Files/USD/third_party/maya/plugin/pxrUsdPreviewSurface/resources/
PYTHONPATH = C:/Program Files/USD/lib/python
XBMLANGPATH = C:/Program Files/USD/third_party/maya/lib/usd/usdMaya/resources
PATH = C:/Program Files/USD/lib;C:/Program Files/USD/bin;C:/Program Files/USD/third_party/maya/lib

### System Information (OS, Hardware)
Windows 10, Maya 2019
usd v19.07

**Comment by jilliene** [comment]
Filed as internal issue #USD-5403

**Comment by mattyjams** [comment]
Hi @emilche,

That error makes it sound like Maya is not finding the Mel scripts that are installed with the usdMaya library. "usdTranslatorImport" is a function defined in this script file:
https://github.com/PixarAnimationStudios/USD/blob/master/third_party/maya/lib/usdMaya/usdTranslatorImport.mel

Can you double-check your setting for MAYA_SCRIPT_PATH? In the dump of your Maya env settings that you posted, I see the resources dir for the pxrUsdPreviewSurface plugin listed twice and the usdMaya library one missing. That should probably look something like this instead:

MAYA_SCRIPT_PATH = C:/Program Files/USD/third_party/maya/lib/usd/usdMaya/resources:C:/Program Files/USD/third_party/maya/plugin/pxrUsdPreviewSurface/resources/

**Comment by emilche** [comment]
That did the trick. Just had to change : to a ; 
Thank you for the help!
