### ISSUE TITLE
Prototypes inherit per instance primvar in Katana causing a warning.

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#893]
### Description of Issue
We have a Instancer written out from Houdini with a per point attribute with a random value. When loaded into Katana this attribute is put on the Instancer root group as well as the Instancer location itself. This causes the per instance primvar to be inherited by all prototypes which then complain that this per instance attribute does not have the same number of values as the mesh vertexs.

### Steps to Reproduce
1. Create per instance attribute on a PointInstancer
2. Render the point instancer in Katana

### System Information (OS, Hardware)
Linux CentOS7

### Package Versions
19.05

### Build Flags

**Comment by jilliene** [comment]
Filed as internal issue #USD-5405

**Comment by emeroo** [comment]
Hi there! What renderer are you using?

**Comment by emeroo** [comment]
I ask because RMan (RfK) ships with a render terminal op that removes primvars from "usd point instancer" locations (as part of flattening primvars down to the leaf level), which explains why we haven't encountered this issue internally.

**Comment by emeroo** [comment]
Ah, but then the primvars *are* indeed being flattened down to the mesh level, which is, as you described, not desirable. It looks like one of our internal ops is pruning primvars from point instancers wholesale before the flattener runs and *that* is why we haven't encountered the issue.

**Comment by radon199** [comment]
Hey, yes, we are using Renderman for Katana.
