### ISSUE TITLE
[Feature Request] Add 'GetTime' virtual method to HdSceneDelegate

### ISSUE THREAD

**Issue by hshakula** [PixarAnimationStudios/USD#897]
HdSceneDelegate provides us ways of getting transform, instancerTransform and primvar of particular time via a set of 'Sample*' methods, but there is no way to query the current time.

The current implementation of UsdImagingDelegate has ['GetTime'](https://github.com/PixarAnimationStudios/USD/blob/v19.07/pxr/usdImaging/lib/usdImaging/delegate.h#L155) method. But it would not be reliable to use any form of casting HdSceneDelegate to UsdImagingDelegate and using 'GetTime' method from it.

So I wonder about your opinion on this feature. And if you think it will fit in design I would like to add appropriate changes via PR.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5428

**Comment by c64kernal** [comment]
Hi @hshakula -- we were wondering why you might need such a thing and then I looked at the referenced issue, and am wondering if what you're looking for already exists in the form of a method on scene delegates, called SamplePrimvar -- note that you pass it times relative to the current time in the scene delegate.

**Comment by hshakula** [comment]
Oh, I totally missed this information, thanks for pointing me in the right direction
