### ISSUE TITLE
katana build usd

### ISSUE THREAD

**Issue by Qinjiaxin** [PixarAnimationStudios/USD#905]
### Description of Issue
CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaAttrfncApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaAttrfncApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaAttrfncApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaAttrfncApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaOpApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaOpApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaOpApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaOpApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaPluginApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaPluginApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaPluginApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:katanaPluginApi>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.
### Steps to Reproduce
1. 

### System Information (OS, Hardware)
Win10
Visual Studio 2017
Katana3.0v5
### Build Flags
python usd\build_scripts\build_usd.py --force-all --python --hdf5 --katana --katana-api-location "C:\Program Files\Katana3.0v5"

**Comment by jtran56** [comment]
Filed as internal issue #USD-5449.

**Comment by tusharsankhala** [comment]
Any Update on this issue i am also getting the same issue.

**Comment by abelvargas** [comment]
I'm getting the same error if I pass the Katana argument. 

python usd\build_scripts\build_usd.py "directory/location" works great

python build_usd.py "C:\Program Files\USD" --katana --katana-api-location "C:\Program Files\Katana3.5v2\bin"  get me this error.

**Comment by c64kernal** [comment]
Hi @abelvargas -- I'm sorry I don't have an answer for you, but I did want to mention that the Katana plugins are deprecated in this repo and will be removed soon. Your best bet is to pursue getting the plugins working that are now hosted by The Foundry here: https://github.com/TheFoundryVisionmongers/KatanaUsdPlugins

**Comment by abelvargas** [comment]
> 
> 
> Hi @abelvargas -- I'm sorry I don't have an answer for you, but I did want to mention that the Katana plugins are deprecated in this repo and will be removed soon. Your best bet is to pursue getting the plugins working that are now hosted by The Foundry here: https://github.com/TheFoundryVisionmongers/KatanaUsdPlugins

Thank you!
