### ISSUE TITLE
Changing material assignments makes some instances vanish

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#917]
### Description of Issue
When using native instancing, a change to material assignments can result in some instances disappearing completely.

### Steps to Reproduce
1. Unzip the attached file, and open usdview on "first.usda". Use HdStream, though .
[disappearing_instances.zip](https://github.com/PixarAnimationStudios/USD/files/3429812/disappearing_instances.zip)
Copy first.usda to third.usda.

2. In the Interpreter window run:
`rl = usdviewApi.stage.GetRootLayer()`
`s = Sdf.Layer.FindOrOpen("second.usda")`
`t = Sdf.Layer.FindOrOpen("third.usda")`
`rl.TransferContent(s)`

3. One torus disappears. Now run:
`rl.TransferContent(t)`

4. Even more tori disappear. And not just the ones that are having their materials changed. This happens regardless of the choice of render delegate (HdStream, embree, hdprman, and two of our own), so I am fairly sure it is UsdImaging at fault, not any render delegate.

### System Information (OS, Hardware)
Tested on Windows.

### Package Versions
dev branch build from a week after 19.07 release.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5465
