### ISSUE TITLE
[Maya crash] maya usdSkel export crash with joints are not connected to bindPose

### ISSUE THREAD

**Issue by sergiy-nazarenko** [PixarAnimationStudios/USD#918]
Hello!

We have a character rig with some joints are not connected to bindPose maya node. 
This cause maya crash if we want to export skel to usd.

I take a look at code in function _FindDagPoseMembers
and found some potential danger code :)
In our case dagPaths.size() > membersPlug.numElements();
and here
https://github.com/PixarAnimationStudios/USD/blob/32ca7df94c83ae19e6fd38f7928d07f0e4cf5040/third_party/maya/plugin/pxrUsdTranslators/jointWriter.cpp#L339
we try to set element out of bound std::vector<unsigned int>* indices
Thanks!

**Comment by sergiy-nazarenko** [comment]
I added to line
https://github.com/PixarAnimationStudios/USD/blob/32ca7df94c83ae19e6fd38f7928d07f0e4cf5040/third_party/maya/plugin/pxrUsdTranslators/jointWriter.cpp#L121
check if bindPose connection exists then we push_back(path) and maya not crached yet

I don't know if it is can be solution

**Comment by jilliene** [comment]
Filed as internal issue #USD-5466

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
