### ISSUE TITLE
Multiple shader nodes in one shader source asset file

### ISSUE THREAD

**Issue by lkettnerNV** [PixarAnimationStudios/USD#919]
Material definition languages like NVIDIA MDL can have multiple materials and functions
in a single MDL file. To refer to an MDL file in USD, we would like to use the `sourceAsset`
attribute, as in:

    def Shader "flex_material"
    {
        uniform token info:implementationSource = "sourceAsset"
        uniform asset info:mdl:sourceAsset = @nvidia/core_definitions.mdl@
        …
    }

This falls short of working if `core_definitions.mdl` contains multiple definitions,
in particular with the shader registry in the USD SDK (`SdrRegistry`).

A proposal from Pixar suggests a new attribute, `subIdentifier`, to address that, as in:

    def Shader "flex_material"
    {
        uniform token info:implementationSource = "sourceAsset"
        uniform asset info:mdl:sourceAsset = @nvidia/core_definitions.mdl@
        uniform token info:mdl:sourceAsset:subIdentifier = "::nvidia::core_definitions::flex_material"
        …
    }

This proposal would work well for embedding MDL definitions in USD.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5467
