### ISSUE TITLE
Windows build can't find pthread.h

### ISSUE THREAD

**Issue by Ryanagogo** [PixarAnimationStudios/USD#921]
### Description of Issue

Hello, 

I'm trying to build USD on my windows 10.  During the build it's getting this error:

fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

I've attached the cmake output and error logs, so you can see more details

Thank you in advance for any help you can give me!

Ryan

[CMakeOutput.log](https://github.com/PixarAnimationStudios/USD/files/3433571/CMakeOutput.log)
[CMakeError.log](https://github.com/PixarAnimationStudios/USD/files/3433573/CMakeError.log)

**Comment by jilliene** [comment]
Filed as internal issue #USD-5468

**Comment by sunyab** [comment]
Hi @Ryanagogo, I believe the log files you've posted are from CMake trying to determine whether pthread.h exists on your system and don't indicate the real cause of the build failure. Can you post the log files from the full build? This should be in D:\USDBuild\build\USD\log.txt given your build set up.

**Comment by Ryanagogo** [comment]
Here is the log.txt, sorry for not including it before!
[log.txt](https://github.com/PixarAnimationStudios/USD/files/3458590/log.txt)

**Comment by sunyab** [comment]
Thanks! From the log file, it looks like the build is running into errors when trying to build boost python:

```
<snip>
D:\Python27\libs\python27.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'

D:\USDBuild\build\boost\bin.v2\libs\python\build\msvc-14.1\release\address-model-64\threading-multi\boost_python-vc141-mt-1_65_1.dll : fatal error LNK1120: 135 unresolved externals
```

It looks like you may have installed the 32-bit Python libraries and SDK for Windows, but you'll need the 64-bit version instead. Let me know if that helps!

**Comment by Ryanagogo** [comment]
You are right, using the 32 bit python was the issue.  I changed it out and now it builds without errors.

Is there a script that can do a prerequisite check for building USD?

Thank you for the help!

Ryan

**Comment by sunyab** [comment]
Glad that helped! We might be able to add a check to build_usd.py to see if the Python you're running is 32-bit or 64-bit. I'll explore that a bit and see what can be done.
