### ISSUE TITLE
Failing link in debug on clang, and some gcc versions in Debug

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#93]
Hi there,

TF_INSTANTIATE_SINGLETON fails in debug on clang and some versions of gcc, e.g. redhat linux with gcc 4.8.4.

e.g. from gcc

```
/var/tmp/doNotRemove/BuildTarget/bundles/XXX/RHEL6_AMD64_GCC484_DEBUG/dso/libplug.so: undefined reference to `TfSingleton<PlugRegistry>::GetInstance()'
/var/tmp/doNotRemove/BuildTarget/bundles/XXX/RHEL6_AMD64_GCC484_DEBUG/dso/libplug.so: undefined reference to `TfSingleton<PlugRegistry>::SetInstanceConstructed(PlugRegistry&)'
collect2: error: ld returned 1 exit status
```

also from clang

```
Undefined symbols for architecture x86_64:
  "TfSingleton<TfDiagnosticMgr>::GetInstance()", referenced from:
      TfDiagnosticMgr::GetInstance() in wrapError.o
  "TfSingleton<TfRefPtrTracker>::GetInstance()", referenced from:
      TfRefPtrTracker::GetInstance() in wrapRefPtrTracker.o
  "TfSingleton<Tf_PyEnumRegistry>::GetInstance()", referenced from:
      Tf_PyEnumRegistry::GetInstance() in wrapDiagnostic.o
      Tf_PyEnumRegistry::GetInstance() in wrapTestTfPython.o
  "TfSingleton<TfScriptModuleLoader>::GetInstance()", referenced from:
      TfScriptModuleLoader::GetInstance() in wrapScriptModuleLoader.o
  "TfSingleton<Tf_PyWeakObjectRegistry>::GetInstance()", referenced from:
      Tf_PyWeakObjectRegistry::GetInstance() in wrapNotice.o
```

A fix that works is to modify the macro as follows.

```
#define TF_INSTANTIATE_SINGLETON(T)                               \
    template <> std::mutex* TfSingleton<T>::_mutex = 0;           \
    template <> T* TfSingleton<T>::_instance = 0;                 \
                                                                  \
    template T& TfSingleton< T >::_CreateInstance();              \
    template void TfSingleton< T >::_DestroyInstance();           \
                                                                  \
    template T& TfSingleton< T >::GetInstance();                  \
    template void TfSingleton< T >::SetInstanceConstructed(T& instance)
```

**Comment by jtran56** [comment]
Filed as internal issue #139369.

**Comment by gitamohr** [comment]
Nick these are inline functions defined in the .h file -- do you know why we're getting undefined symbols for them but not for other inline functions?  I'd like to understand better what's going on here.

**Comment by meshula** [comment]
The symbols for GetInstance and SetInstanceConstructed do not appear in the symbol table. I haven't had time to investigate further, but my working hypothesis is that in Release mode the methods actually get inlined so there is no problem, but in Debug, the compiler assumes that they have been instantiated, but actually they have not, and so must be explicitly instantiated.

**Comment by gitamohr** [comment]
The thing I'm having trouble with is that if this is true, then it seems like we should be having the same problem with zillions of other inline functions in debug mode.  GfVec3d::Normalize(), for example.  What's different about these?

**Comment by meshula** [comment]
Yes, that is bothering me too as it is inconsistent. The problem appeared recently. I will try a completely clean machine, and if the problem persists, regressing commits to see if there is something else triggering the issue.

**Comment by carlospzlz** [comment]
Hi,

I'm experiencing the same problem about the missing symbol:
`undefined reference to 'TfSingleton<TfDiagnosticMgr>::GetInstance()'`

I was wondering if there was any progress on this.

Thanks!
Carlos

**Comment by meshula** [comment]
Unfortunately I currently do not have a repro.

**Comment by ZeroCrunch** [comment]
Hey Nick!

Carlos does have a repo case on Linux. I'll ask him to email you guys.

Thanks!

**Comment by meshula** [comment]
closing as no longer an issue
