### ISSUE TITLE
Mis-match between CreateSpec documentation and implementation

### ISSUE THREAD

**Issue by BrianHarris** [PixarAnimationStudios/USD#930]
### Description of Issue

The documentation for [SdfAbstractData::CreateSpec](https://graphics.pixar.com/usd/docs/api/class_sdf_abstract_data.html#ac0ace196eea440b316f4a60655aaa6ee) says "If the spec already exists the spec type will be changed."

That's how it's implemented in [SdfData::CreateSpec](https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/sdf/data.cpp#L98)

However, [Usd_CrateDataImpl](https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usd/crateData.cpp#L378) doesn't implement it that way.

Additionally, [SdfLayer::_CreateSpec](https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/sdf/layer.cpp#L3885) throws an error if you try it.

So I'm not sure which is correct, the code or the documentation.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5483
