### ISSUE TITLE
 Houdini open tree view error

### ISSUE THREAD

**Issue by dishuman** [PixarAnimationStudios/USD#932]
### Description of Issue
"C:\Program Files\Side Effects Software\Houdini 17.5.327\toolkit\usd_houdini_plugins"
to build plugin 
after set the path to USD, then click treeview
new window appears error msg:
________________________________________________________
There is an error in the Usd Tree View script.

Traceback (most recent call last):
     File "", line 10, in 
    ImportError: No module named Gusd.treeview
________________________________________________________

### Steps to Reproduce
1. just follow the readme file to build the this plugin
 "C:\Program Files\Side Effects Software\Houdini 17.5.327\toolkit\usd_houdini_plugins"

### System Information (OS, Hardware)
windows 10 
### Package Versions
vs 2017

**Comment by jilliene** [comment]
Filed as internal issue #USD-5492

**Comment by sunyab** [comment]
We are no longer supporting the Houdini plugin distributed with previous versions of USD, in favor of Houdini's native USD support in Solaris. Closing this out.
