### ISSUE TITLE
What is the correct version of Boost that should be getting used?

### ISSUE THREAD

**Issue by dtlindsey** [PixarAnimationStudios/USD#934]
### Description of Issue
Building USD on Windows

### Steps to Reproduce
1.  Visual Studio 2017 x64 NativeCommandPrompt, build with --generator "Visual Studio 14 2015 Win64"
2.  This downloads Boost 1_65

1. Visual Studio 2015 x64 NativeCommandPrompt, build with --generator "Visual Studio 14 2015"
2. This downloads Boost 1_61

### System Information (OS, Hardware)
Windows 10

### Package Versions
v19.05, and master

### Build Flags
python build_scripts\build_usd.py --generator "Visual Studio 14 2015 Win64" --build-args=boost,"toolset=msvc-14.0 --with-date_time --with-thread --with-system --with-filesystem" --no-maya --ptex --materialx --alembic --openimageio --opencolorio --verbose --force-all "C:\Users\lindd067\dev\external\install\USD-19.05-all"

**Comment by Wouterdek** [comment]
Under linux, the build script seems to download 1.55.0.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5493

**Comment by dtlindsey** [comment]
Thank you for filling the issue, but, in the mean time, is there a recommended version of boost that should be used?

**Comment by c64kernal** [comment]
Hi @dtlindsey  -- If you're running on VS2015, the minimum version that will work is 1.61.0.  This version won't work on 2017, and you'll need at least boost version 1.65.1.  There have been reports that later versions of boost work fine on both systems.  Hope that helps.

**Comment by dtlindsey** [comment]
It does. Thank you.


Thanks,
-Daniel

On Aug 22, 2019 at 8:29 PM, George ElKoura <notifications@github.com>
wrote:

Hi @dtlindsey <https://github.com/dtlindsey> -- If you're running on
VS2015, the minimum version that will work is 1.61.0. This version won't
work on 2017, and you'll need at least boost version 1.65.1. There have
been reports that later versions of boost work fine on both systems. Hope
that helps.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PixarAnimationStudios/USD/issues/934?email_source=notifications&email_token=AAXTVX2QN2ZSGU7HKAAALB3QF5KRJA5CNFSM4ILGBLT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD47ANZI#issuecomment-524158693>,
or mute the thread
