### ISSUE TITLE
usdGenSchema not building or installing

### ISSUE THREAD

**Issue by dtlindsey** [PixarAnimationStudios/USD#935]
### Description of Issue
usdGenSchema not building or installing, but failing quietly

### Steps to Reproduce
1. git clone https://github.com/PixarAnimationStudios/USD.git

2.  python build_scripts\build_usd.py --generator "Visual Studio 14 2015 Win64" --build-args=boost,"toolset=msvc-14.0 --with-date_time --with-thread --with-system --with-filesystem" --no-maya --ptex --materialx --alembic --openimageio --opencolorio --verbose --force-all "C:\Users\lindd067\dev\external\install\USD-19.05-all"

3. The build completes but usdGenSchema isn't in the bin directory

### System Information (OS, Hardware)
Windows 10 (company image)

### Package Versions
master, of 19.05

### Build Flags
see above

**Comment by charlesfleche** [comment]
I'm not familiar with the Windows build, but are you sure that you build the Python binding ? Without those I don't think `usdGenSchema` is built.

**Comment by asluk** [comment]
I think you need to make sure that jinja2 is installed for your python. Otherwise, cmake will skip usdGenSchema. It will issue a warning, but it’s easy to miss, and it wasn’t until I looked at the cmake file that I figured out what was going on with my local build.

**Comment by dtlindsey** [comment]
Thanks @asluk I will give this a shot.  I didn't even think to dig into the cmake file to find that.

**Comment by dtlindsey** [comment]
@asluk  this fixed the issue.  Thanks for the help.
