### ISSUE TITLE
Changes to inherited primvars don't update child primitives

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#937]
### Description of Issue
If a mesh prim inherits its displayColor from its parent prim, and that parent prim's displayColor is changed, the child mesh doesn't get updated by Hydra unless the parent is instanceable.

### Steps to Reproduce
1. Open the nomat_noinst.usda file from the attached archive in usdview.
[inherit_primvars.zip](https://github.com/PixarAnimationStudios/USD/files/3507039/inherit_primvars.zip)
2. Make sure you can see all the tori. In the Interpreter run:
a = usdviewApi.stage.GetPrimAtPath("/instancer1/Instance0").GetAttribute("primvars:displayColor")
a.Set(Vt.Vec3fArray(1, (Gf.Vec3f(1.0, 0.0, 1.0),)))
which should turn one of the tori purple. But nothing happens. This is the bug.
3. Open nomat_inst.usda and run the same code. This time one torus turns purple as expected. Though this may just be because this one torus breaks instancing and is getting created as a new primitive...

Also attached are versions of these files with a preview surface material assigned. They have the same behavior (update doesn't happen unless the ancestor prim is instanceable).

### System Information (OS, Hardware)
Windows 10

### Package Versions
19.07+ dev branch from June 25th

**Comment by jilliene** [comment]
Filed as internal issue #USD-5494
