### ISSUE TITLE
HdPrman doesn’t respect scene up for dome light orientation

### ISSUE THREAD

**Issue by radon199** [PixarAnimationStudios/USD#938]
### Description of Issue
As per this post on the forums : https://groups.google.com/d/msg/usd-interest/w2TLrpVVZvQ/wQuUOqQvCQAJ

HdPrman seems to always orient dome lights on the Z- axis regardless of if the stage is oriented on Z up or Y up. Even when the scene is set to Z up the dome draws as upside down vs how Usdview orients the camera.

### Steps to Reproduce
1. Create a scene with a dome light and texture and stage metadata set to Y up.
2. Render with HdPrman and check dome orientation via the texture.

### System Information (OS, Hardware)
CentOs7
### Package Versions
Usd19.07
### Build Flags

**Comment by jilliene** [comment]
Filed as internal issue #USD-5495
