### ISSUE TITLE
Export of MASH particle instancer fails if objects have a namespace

### ISSUE THREAD

**Issue by Wouterdek** [PixarAnimationStudios/USD#941]
### Description of Issue
When exporting a Maya scene with a MASH network particle instancer, the export fails if the instanced objects have a namespace.

The error that is produced is:

```
// Opening layer '/uvfx/Homes/wdekeersmaecker/Desktop/export.usd' for writing // 
// Warning: Invalid prim name 'foo:pCube1_0' // 
// Error: Path must be an absolute path: <> -- Coding Error in _IsValidPathForCreatingPrim at line 3098 of /home/centos/USD/pxr/usd/lib/usd/stage.cpp // 
// Error: Cannot add target <> to relationship </MASH1_Instancer.prototypes>: Cannot map <> to layer @/uvfx/Homes/wdekeersmaecker/Desktop/export.usd@ via stage's EditTarget -- Coding Error in AddTarget at line 110 of /home/centos/USD/pxr/usd/lib/usd/relationship.cpp // 
// Warning: /MASH1_Instancer -- no prototypes // 
```

The exporter option "Strip namespaces" has no effect.

### Steps to Reproduce
1. Create a new scene in Maya
2. Add a poly cube
3. Add a new namespace and apply the namespace to the cube
4. Create a MASH network using the cube
5. Under the menu MASH -> Utilities, press "Switch MASH Geometry Type" to set the geometry type to "Particle Instancer"
6. Try to export the scene as USD.

### System Information (OS, Hardware)
Centos 7, Maya 2018.5

### Package Versions
USD v19.07

### Build Flags
python build_usd.py --maya

**Comment by jilliene** [comment]
Filed as internal issue #USD-5498

**Comment by sunyab** [comment]
Closing this out since this is related to the old Maya plugin which has migrated to https://github.com/Autodesk/maya-usd and no longer ships with USD.
