### ISSUE TITLE
Storm - PointInstancer disappears during selection if it has 6+ primvars

### ISSUE THREAD

**Issue by ablev-dwa** [PixarAnimationStudios/USD#943]
# Description of Issue

If a PointInstancer has 6 or more primvars, it will disappear during selection of any object in the scene when using the Storm render delegate. If it has more than 3 primvars, it will also print errors to the terminal, like:

```
Warning: in Link at line 204 of /usr/pic1/usd/cmake/pxr/imaging/lib/hdSt/glslProgram.cpp -- Failed to link shader: Fragment info
-------------
0(452) : error C5058: no buffers available for bindable storage buffer 

ERROR: Usdview encountered an error while rendering.
	Error in 'pxrInternal_v0_19__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 241 in file /usr/pic1/usd/cmake/pxr/imaging/lib/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /scatter/Geometry/triangles.proto0_triangle_id0.'
	Error in 'pxrInternal_v0_19__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 268 in file /usr/pic1/usd/cmake/pxr/imaging/lib/hdSt/drawBatch.cpp : 'Failed verification: ' res ''
	Error in 'pxrInternal_v0_19__pxrReserved__::HdSt_IndirectDrawBatch::ExecuteDraw' at line 1116 in file /usr/pic1/usd/cmake/pxr/imaging/lib/hdSt/indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
```

If the PointInstancer has 3 or fewer primvars, everything works fine.

This happens whether or not we use PreviewSurface shaders.

### Steps to Reproduce
1. Open pointinstancer_selection.usda in usdview from [pointinstancer_selection.zip](https://github.com/PixarAnimationStudios/USD/files/3517129/pointinstancer_selection.zip)
2. Set purpose to "render"
3. Click the box named "/scatter/Geometry/ClickMe"
4. The PointInstancer, which scatters a single instance of a single triangle, will disappear, and errors will print to the shell

### System Information (OS, Hardware)
Linux CentOS7
Nvidia driver 418.43

### Package Versions
USD-0.19.7

### Build Flags
python build_usd.py /usr/pic1/usdtest --tests --alembic --openimageio

**Comment by jilliene** [comment]
Filed as internal issue #USD-5505

**Comment by c64kernal** [comment]
Thanks for the report @ablev-dwa  -- @davidgyu has a fix that should be pushed up to dev soon.
