### ISSUE TITLE
Use different oslc location?

### ISSUE THREAD

**Issue by AlexSchwank** [PixarAnimationStudios/USD#946]
### Description of Issue
This is rather a question than a real issue.
Would it be better not to assume `oslc` is installed with prman under `${RENDERMAN_LOCATION}/bin/oslc`? (see https://github.com/PixarAnimationStudios/USD/blob/master/third_party/renderman-22/shaders/CMakeLists.txt#L8)
One could use  `${OSL_OSLC_EXECUTABLE}` but arguably `${RENDERMAN_LOCATION}/bin/oslc` can be valid too. 

### Package Versions
19.07

**Comment by jilliene** [comment]
Filed as internal issue #USD-5515

**Comment by c64kernal** [comment]
Hey @AlexSchwank -- our renderman folks think that the renderman location is the right one given that it is only being used by renderman.  Let us know if you have any other thoughts!
