### ISSUE TITLE
Lingering use of boost::shared_ptr in Vt

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#95]
Any reason Vt_DefaultValueHolder uses a boost::shared_ptr? Can it just be switched to a shared_ptr now? It's the only usage in vt.

**Comment by jtran56** [comment]
Filed as internal issue #139512.

**Comment by sunyab** [comment]
This was addressed with dae34557d and 5ecad404.

**Comment by meshula** [comment]
Cheers :)
