### ISSUE TITLE
katana plugin window  C249

### ISSUE THREAD

**Issue by ArthurChiu** [PixarAnimationStudios/USD#954]
### Steps to Reproduce
1.  error C2491: 'Foundry::Katana::Attribute::_attrSuite' : definition of dllimport static data member not allowed 
error C2491: 'Foundry::Katana::AttributeFunction::_apiName' : definition of dllimport static data member not allowed
error C2491: 'Foundry::Katana::Attribute::_attrSuite' : definition of dllimport static data member not allowed

....
...

### System Information (OS, Hardware)
window 10
### Package Versions
19.01-19.07

**Comment by jilliene** [comment]
Filed as internal issue #USD-5523

**Comment by c64kernal** [comment]
Hi @ArthurChiu, unfortunately we don't currently support our Katana plugins on Windows.  This might be a good thing to bring up with the Foundry though.  Closing for now.
