### ISSUE TITLE
Activate Renderer after starting usdview with -noRender flag

### ISSUE THREAD

**Issue by Schizo** [PixarAnimationStudios/USD#958]
Is there  a way to restart the Viewer when usdview was launched with the `norender` flag? Once it's started with `-norender`. You can't choose/activate the render engine, I was wondering if there is a callback hidden that could be called through the interpreter. 

The same goes for the `--renderer HydraDisabled` flag, cannot bring in the view again after launching usdview with that flag.

Thanks

**Comment by spiffmon** [comment]
There is no such callback - sorry!  If you're looking for a "fast launch"
that you can then expand from, if your assets are deployed with payloads,
then you can launch usdview with the "--unloaded" flag, and then load the
things you're interested in (and a Load operation on your scene's root prim
will load everything).

--spiff

**Comment by jilliene** [comment]
Filed as internal issue #USD-5537
