### ISSUE TITLE
Potential crash or corruption issue in PcpRaiseErrors

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/USD#96]
TF_RUNTIME_ERROR expects a C style format string as the first parameter. If the err string has a percent sign in it, bad things could happen. Easy fix is to add "%s" as first parameter.

void 
PcpRaiseErrors(const PcpErrorVector &errors)
{
    TF_FOR_ALL(err, errors) {
        TF_RUNTIME_ERROR((*err)->ToString().c_str());
    }
}

**Comment by jtran56** [comment]
Filed as internal issue #139513.

**Comment by blevin** [comment]
Thanks Nick!  That's a great find.
