### ISSUE TITLE
Unable to get instance list from Master prim

### ISSUE THREAD

**Issue by NiallPRedmond** [PixarAnimationStudios/USD#962]
As per a discussion with Spiff in this post on the interest group:
https://groups.google.com/forum/#!topic/usd-interest/awNZFmWKXGk

In native instancing, there is no functionality available in the public API for getting a list of instances served by a Master prim, which would be handy to be able to access.

Package Versions
Usd19.07

**Comment by jilliene** [comment]
Filed as internal issue #USD-5544
