### ISSUE TITLE
UDIM paths on UsdShadeMaterial inputs

### ISSUE THREAD

**Issue by pierre-ed** [PixarAnimationStudios/USD#970]
### Description of Issue
HdStream does not properly handle texture paths requiring UDIM expansion when said paths are set as material inputs that are connected to the inputs:file attribute of a UsdUVTexture node.

### Steps to Reproduce
From the directory where the [archive](https://github.com/PixarAnimationStudios/USD/files/3631231/issue_UDIM_as_material_input.zip) is extracted, run `usdview issue_UDIM_as_material.usda`. 

### System Information (OS, Hardware)
Linux x64 CentOS7

### Package Versions
v19.07 Commit 32ca7df9

**Comment by jilliene** [comment]
Filed as internal issue #USD-5566

**Comment by sunyab** [comment]
This issue should be resolved in the 20.08 release -- see 4e4265654. I was able to load the test asset you provided (thank you!) and see the expected texture, and I also saw the texture change as I updated primvars:st. 

Closing this out, thanks!
