### ISSUE TITLE
Unable to change variant selection for instance sources in Katana

### ISSUE THREAD

**Issue by ainaerco** [PixarAnimationStudios/USD#979]
### Description of Issue
I can't find a way to change variant selection on instance sources using UsdInVariantSelect using "as sources and instances" mode. After some investigation turned out that prim location differs between usd and Katana scenegraph. For example instance sources for point instancing have "geo" group which doesn't appear in usd and usdview.
Which make me wonder if:
1. Scenegraph hierarchy is constructed to match usd hierarchy.
2. UsdInVariantSelect have to have additional parameter to specify usd location (Which may be beneficial when scene hierarchy changed before UsdInVariantSelect is used).

**Comment by jtran56** [comment]
Filed as internal issue #USD-5581.

**Comment by stevelavietes** [comment]
In that mode, the "instance source" locations created under Masters are made from the USD masters. Those masters are a product of USD composition based on the unique combinations of references, variant selections, etc.

PxrUsdInVariantSelect should work if you target the instance location (or locations) which use that master (as that's what results in a specific master being created on the usd stage). This will result in a new master.

PxrUsdInVariantSelect's pop-up menus for variantSetName and variantSelection are filled from "info.usd" attr values on the targeted location. (If those are not present on the "instance" locations created in the mode, you can manually type them into the combobox to test. I'd consider it a bug if that info attr wasn't there but I'm not confident it's there as we don't currently use that mode within the studio).

**Comment by spiffmon** [comment]
Closing, as Pixar no longer publishes Katana plugins.
