### ISSUE TITLE
usdview shading modes do not work

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#98]
### System Information (OS, Hardware, etc.)
Windows

### Steps to Reproduce
1. launch usdview on a usd file
2. select view > shading mode > (pick any)

the shading mode never changes.

**Comment by jtran56** [comment]
Filed as internal issue #139515.

**Comment by sunyab** [comment]
This issue appears to be due to the way MSVC deals with enum values stored in bitfields. This should be fixed by commit 92cd4ba4e8d031af786cc5d59a053cb02c126a3c. Closing this out.
