### ISSUE TITLE
usdview does not respect the USD spec in regards to PreviewSurface opacityThreshold

### ISSUE THREAD

**Issue by hybridherbst** [PixarAnimationStudios/USD#990]
### Description of Issue
According to the docs, opacityThreshold should act as a toggle between "translucent OR masked" ([see here](https://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html)).
However, usdview does not seem to respect that spec, and instead combines translucency and masking into always-transparent surfaces with no way to get them to behave "opaque but masked".

### Steps to Reproduce
1. open the attached file in usdview
[infinitygames-galicnik.zip](https://github.com/PixarAnimationStudios/USD/files/3687993/infinitygames-galicnik.zip)

2. note that the "worn paper object" is half transparent despite having an opacity texture that only has clear white and clear black and a opacityThreshold of 0.25
![20191003-223231_python](https://user-images.githubusercontent.com/2693840/66162360-7bb73880-e62e-11e9-8347-e5e37eab2fa8.png)
3. go to https://infinitygames-galicnik.glitch.me/ on a Desktop - this is the GLB version of the file which looks as intended (all surfaces are solid with a cutout)
4. go to https://infinitygames-galicnik.glitch.me/ on an iOS device - QuickLook will open with the USDZ version as interpreted by Apple's QuickLook which has its own issues but the "worn paper object" is solid as per the spec

For reference, this is what it's supposed to look like -
![image](https://user-images.githubusercontent.com/2693840/66162413-95588000-e62e-11e9-8ff6-5ccc382d827a.png)
All these objects have solid 0 or 1 alpha channels and use alpha cutoff.

Additional example: **reference** (white on black with no alpha cutoff):
![image](https://user-images.githubusercontent.com/2693840/66166191-ea988f80-e636-11e9-8682-3e2aa10aa8a7.png)
**actual usdviewer result** (looks like albedo is actually multiplied with opacity values!)
![image](https://user-images.githubusercontent.com/2693840/66166212-013ee680-e637-11e9-8119-deb329f8c2ee.png)

### System Information (OS, Hardware)
Windows 10

### Package Versions / Build Flags
using the pre-built binaries from https://github.com/VictorYudin/saturn/ with version 19.07

**Comment by poljere** [comment]
This is indeed an issue. We have not yet fully catch up with the spec in Storm (GL renderer), the differences you are seeing are expected since the work to support opacityThreshold has not been done yet. We will post an update when it is available, thanks!

**Comment by soraryu** [comment]
Thanks for the reply!
I guess my main question then is "what's the reference implementation for USD" - I'm trying to get stuff into QuickLook, and they seem closer to the spec but also not right. Is there anything that will give me "ground truth"?
(I thought usdview is the reference implementation)

**Comment by jtran56** [comment]
Filed as internal issue #USD-5608.

**Comment by mistafunk** [comment]
There is a nice example from the Khronos GLTF project for this case: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest
