### ISSUE TITLE
Cannot reliably deactivate nested instances inside of SdfChangeBlock

### ISSUE THREAD

**Issue by lbiasco** [PixarAnimationStudios/USD#993]
### Description of Issue
USD can either fail or crash on trying to access nested instances after certain other prims are deactivated inside of an SdfChangeBlock. As narrow as I could debug it, the failure case seems to be when 
- The nested instances are a payload
- Multiple container instances are deactivated within a changeblock (and I assume the source instances have to be part of that group, as the failure is only definite when all container instances are deactivated)
- The 'nested' master or nested instance is accessed

(Additionally, it seems completely safe to deactivate only a single container instance)

The error from trying stage.GetMasters (from [here](https://github.com/PixarAnimationStudios/USD/blob/32ca7df94c83ae19e6fd38f7928d07f0e4cf5040/pxr/usd/lib/usd/stage.cpp#L2321)) is 
`'Failed verification: ' p ' -- Failed to find prim at master path </__Master_3>.` 
and attempting to directly access the master or an instance proxy crashes python.
### Steps to Reproduce
1. Define a set of at least 2 nested instances:

nested_instance_test.usd
```
#usda 1.0
(
    defaultPrim = "Scene"
)
def Xform "Scene"
{
    def Xform "instance_m1" (
        instanceable = true
        prepend references = @instance.usd@
    )
    {
    }
    def Xform "instance_m2" (
        instanceable = true
        prepend references = @instance.usd@
    )
    {
    }
}
```
instance.usd
```
#usda 1.0
(
    defaultPrim = "instance"
)

over "instance"
{
    def Scope "nested_instance" (
        instanceable = true
        payload = @nested_instance.usd@
    )
    {
    }
}
```
nested_instance.usd
```
#usda 1.0
(
    defaultPrim = "nested_instance"
)

over "nested_instance"
{
    def Sphere "mesh"
    {
    }
}
```
2. Deactivate at least 2 of the container instances inside of a changeblock (deactivating all instances will always make GetMasters fail, but deactivating a portion will only sometimes make GetMasters fail)

```
from pxr import Usd, Sdf

stage = Usd.Stage.Open('nested_instance_test.usd')
stage.GetMasters()

instance_paths = ['/Scene/instance_m1', '/Scene/instance_m2']
layer = stage.GetSessionLayer()

Sdf.BeginChangeBlock()
for path in instance_paths:
    primspec = Sdf.CreatePrimInLayer(layer, path)
    primspec.active = False
Sdf.EndChangeBlock()

stage.GetMasters()
```

3. A more severe crash can occur if 3 instances are created, 2 of them are deactivated, and the third is traversed.

### System Information (OS, Hardware)
Linux, CentOS 7
### Package Versions
USD-0.19.7

**Comment by jilliene** [comment]
Filed as internal issue #USD-5617

**Comment by gitamohr** [comment]
Thanks for the report!  Is there any chance you could try this in dev?  We've made some fixes in this area recently.

**Comment by ablev-dwa** [comment]
I'll put together a dev build later today and we'll try it out.

**Comment by gitamohr** [comment]
Great, let me know how it goes.  I tried this in our internal build (which roughly corresponds to dev) including making up to 5 instances, deactivating various subsets, traversing, etc, and I have not seen a crash.

**Comment by ablev-dwa** [comment]
A build of the dev branch does indeed appear to not have this problem.

**Comment by lbiasco** [comment]
Great, thank you! Then unless anything else needs to be tracked, this issue can be closed, right?

**Comment by gitamohr** [comment]
Great, I'm glad to hear dev fixes it.  I'll close this out for now -- please reach out if it crops up again.
