### ISSUE TITLE
Lifting of the path restriction on class prims

### ISSUE THREAD

**Issue by pierre-ed** [PixarAnimationStudios/USD#994]
### Description of Issue
UsdStage::CreateClassPrim forbids the creation of abstract prims at paths that are not at the root level. Discussion around this limitation suggests it could be removed.

### Steps to Reproduce
Run the python script attached to this issue ([here](https://github.com/PixarAnimationStudios/USD/files/3711912/issue_createClassPrim.zip)). It both highlights the issue and shows its current workaround.

### System Information (OS, Hardware)
Linux x64 CentOS7

### Package Versions
v19.07 Commit 32ca7df

**Comment by jilliene** [comment]
Filed as internal issue #USD-5621
