### ISSUE TITLE
Floating-Point Precision Colors in HdxPrman

### ISSUE THREAD

**Issue by guillaume-lafo-mpc** [PixarAnimationStudios/USD#995]
Hello,

I'm currently implementing color-management, through OpenColorIO, in an internal image generation application. This application is built on top of USD 19.07 and export 8-bit precision images that we present to the user in a separate application. The image generation application offers three Hydra-based rendering engines, including HdxPrman and HdSt. We want to feed OpenColorIO with the most precise color values possible, so we've been researching how to get Hydra to draw in floating-point textures.

I was able to change HdSt through its draw-attachments, so that it writes out to floating-point precision textures. That seems to work quite well.

Unfortunately, in USD 19.07, HdxPrman downgrades the floating-point precision color values that it receives from Renderman into byte precision. My team was hoping to avoid implementing a render-context similar to HdxPrman, built on top of HdPrman: that would replicate a lot of efforts/code done by the USD team. Could you please make the precision of the color buffer in HdxPrman configurable?

What are your plans for color-management in Hydra?

**Comment by jilliene** [comment]
Filed as internal issue #USD-5622

**Comment by lumonix** [comment]
Hi Guillaume,

In the about to be released 19.11 you'll see that Storm and HdPrman will be rendering into 16/32bit aovs. 

For Storm, the 16bit aov pixels are then given to ColorCorrection task to apply sRGB or OCIO color correction.

For Hdprman, we are slightly behind in that pipeline and instead (in 19.11) we convert the 32bit pixels directly in ColorizeTask with sRGB conversion. ColorCorrection is not run for Renderman in 19.11.

In the (near-ish) future we'll be re-working the task system so that all renderers are running through the same gpu post-pipeline, which includes ColorCorrection with OCIO.

**Comment by guillaume-lafo-mpc** [comment]
Thanks for the information; I appreciate the quick feedback!

I look forward to upgrading to USD 19.11, we should do the upgrade as soon as it is released. I'm glad to hear that a future version of the USD SDK will do the OCIO correction in HdPrman. Could you please confirm that in USD 19.11, it will be possible to disable the sRGB conversion in HdPrman so that we can do the OCIO correction separately, once we receive the color buffer?

**Comment by lumonix** [comment]
To disable all forms of color correction in UsdView you would use the menu option:
View / Color Management / disabled

If you are in another app that is using HdxTaskController, call SetColorCorrectionParams(...) and make sure to set the mode to disabled.

If you are in an app that is pushing its own tasks without task controller, but is pushing ColorizeTask, then disable colorQuantization on the HdxColorizeTaskParams.

If you are using your own tasks and not pushing ColorizeTask or ColorCorrectionTask then no sRGB conversion will be applied on the HdPrman aov and you can 'map / unmap' it yourself and apply OCIO yourself.

**Comment by guillaume-lafo-mpc** [comment]
Thanks for the information on how to disable the sRGB conversion in HdPrman!
I'll note that for our internal tracker -- once 19.11 is released, we can give it a shot.
