### ISSUE TITLE
When using SamplePrimvar(), indirect arrays aren't being expanded by Hydra

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#996]
### Description of Issue
When trying to evaluate instance primvars using SamplePrimvar() instead of Get(), it seems that some indirect arrays aren't being expanded by Hydra.

### Steps to Reproduce
After loading the attached file
[primvar_expand.zip](https://github.com/PixarAnimationStudios/USD/files/3720168/primvar_expand.zip)
into a usdImaging delegate within Hydra, calling:
sd->SamplePrimvar("/torus1_0", "basecolor", 1, times, values)
Will return a VtValue that has an array of 1 color.

Calling:
sd->Get("/torus1_0", "basecolor");
Will return a VtValue that has an array of 10 colors (which is expected).

Comments from @poljere :
We are not doing the right thing when sampling instance primvars. It does not look like a new issue though, more so a feature we never added to the sampling path. We would need to do something similar to what is happening during UpdateForTime in InstanceAdapter where we walk through the inherited primvars and collect their values.

### Package Versions
USD 19.11rc1

**Comment by jilliene** [comment]
Filed as internal issue #USD-5630
